 'use client'
import {useEffect,useRef,useState,useCallback} from 'react'
import {createPortal} from 'react-dom'
import {Headphones,PhoneCall,ArrowUpRight,ArrowLeft,Mic,MicOff,Volume2,X,MessageCircle,Clock3,ShieldCheck,Check,PhoneOff,Sparkles,ChevronDown,RefreshCw,Globe2} from 'lucide-react'
import {usePathname} from 'next/navigation'
import type {HotlineConfig,Locale,PublicSnapshot,RouteNode} from '../types'
import {LANGUAGES,QUEUES,humanDuration} from '../model'
import {text} from '../copy'
import {hotlineRequest} from '../client'
import {useHotlineMedia} from './useHotlineMedia'
import styles from '../hotline.module.css'
type Configuration={enabled:boolean;config:HotlineConfig|null;version:string|null;voiceReady:boolean;open:boolean;agents:{queues:string[];locales:Locale[]}[];audio:Record<string,string>}
export function HotlinePublic({initialLocale='fr'}:{initialLocale?:Locale}){
 const pathname=usePathname();const routeLocale=(pathname?.match(/\/angelcare-marketplace\/(ar|en|fr)(?:\/|$)/)?.[1]||initialLocale) as Locale;const [mounted,setMounted]=useState(false),[open,setOpen]=useState(false),[locale,setLocale]=useState(initialLocale),[stage,setStage]=useState<'home'|'language'|'menu'|'context'|'session'>('home'),[mode,setMode]=useState<'voice'|'direct'|'message'|'callback'|'chat'>('voice'),[info,setInfo]=useState<Configuration|null>(null),[answers,setAnswers]=useState<{node:string;key:string}[]>([]),[nodeId,setNodeId]=useState('needs'),[queue,setQueue]=useState('general'),[snapshot,setSnapshot]=useState<PublicSnapshot|null>(null),[pending,setPending]=useState(false),[error,setError]=useState(''),[audioBlocked,setAudioBlocked]=useState(false),[musicVolume,setMusicVolume]=useState(.25),[now,setNow]=useState(Date.now()),[message,setMessage]=useState(''),[confirmEnd,setConfirmEnd]=useState(false),[callbackOpen,setCallbackOpen]=useState(false),[form,setForm]=useState({name:'',contact:'',details:'',reference:'',followUp:'',consent:false});const panel=useRef<HTMLDivElement>(null),launcher=useRef<HTMLButtonElement>(null),prompt=useRef<HTMLAudioElement|null>(null),music=useRef<HTMLAudioElement|null>(null),currentId=useRef(''),pendingPoll=useRef(false),mountedRef=useRef(true),media=useHotlineMedia();const t=text(locale);const config=info?.config;const node=config?.nodes.find(n=>n.id===nodeId);const session=snapshot?.session;const terminal=session&&['ended','abandoned','failed','callback','message'].includes(session.state);const live=session&&!terminal;const currentStage=live?'session':stage
 useEffect(()=>{setMounted(true);mountedRef.current=true;return()=>{mountedRef.current=false;prompt.current?.pause();music.current?.pause()}},[])
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[])
 useEffect(()=>{if(!live)setLocale(routeLocale)},[routeLocale,live])
 const load=useCallback(async()=>{const result=await hotlineRequest<Configuration>('config');if(mountedRef.current)setInfo(result);return result},[])
 useEffect(()=>{let active=true;hotlineRequest<PublicSnapshot|null>('resume').then(s=>{if(active&&s&&['queued','offered','connecting','connected'].includes(s.session.state)){setSnapshot(s);setStage('session');setLocale(s.session.locale)}}).catch(()=>{});return()=>{active=false}},[])
 useEffect(()=>{if(open){load().catch(e=>setError(e.message));const timer=setTimeout(()=>panel.current?.querySelector<HTMLElement>('button,input')?.focus(),20);return()=>clearTimeout(timer)}},[open,load])
 useEffect(()=>{if(!open)return;const previous=document.activeElement as HTMLElement;const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);return}if(e.key==='Tab'){const items=Array.from(panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,textarea,select,a[href]')||[]).filter(el=>el.offsetParent!==null);const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);document.dispatchEvent(new CustomEvent('angelcare:hotline-open'));return()=>{document.removeEventListener('keydown',key);previous?.focus()}},[open])
 useEffect(()=>{const show=()=>setOpen(true);window.addEventListener('angelcare:open-hotline',show);return()=>window.removeEventListener('angelcare:open-hotline',show)},[])
 useEffect(()=>{if(!session||terminal)return;let active=true;currentId.current=session.id;const poll=async()=>{if(pendingPoll.current)return;pendingPoll.current=true;try{const s=await hotlineRequest<PublicSnapshot>(`sessions/${session.id}`);if(active&&currentId.current===s.session.id){setSnapshot(s)}}catch(e){if(active)setError(e instanceof Error?e.message:String(e))}finally{pendingPoll.current=false}};poll();const timer=setInterval(poll,3000);return()=>{active=false;clearInterval(timer)}},[session?.id,terminal])
 useEffect(()=>{if(session?.channel==='voice'&&['connecting','connected'].includes(session.state)){music.current?.pause();prompt.current?.pause();media.connect(session.id,session.room_name)}else media.disconnect()},[session?.id,session?.state,session?.channel,session?.room_name,media.connect,media.disconnect])
 useEffect(()=>{if(snapshot?.musicUrl&&(session?.state==='queued'||session?.state==='offered'||session?.held)){if(!music.current||music.current.src!==new URL(snapshot.musicUrl,location.origin).href){music.current?.pause();music.current=new Audio(snapshot.musicUrl);music.current.loop=true}music.current.volume=musicVolume;music.current.play().then(()=>setAudioBlocked(false)).catch(()=>setAudioBlocked(true))}else music.current?.pause();return()=>{music.current?.pause()}},[snapshot?.musicUrl,session?.state,session?.held,musicVolume])
 useEffect(()=>{media.setHold(Boolean(session?.held)).catch(()=>{})},[session?.held,media.status,media.setHold])
 const play=useCallback((url?:string)=>{prompt.current?.pause();if(!url)return;prompt.current=new Audio(url);prompt.current.play().then(()=>setAudioBlocked(false)).catch(()=>setAudioBlocked(true))},[])
 const start=async(next:typeof mode)=>{setError('');setMode(next);setAnswers([]);setQueue('general');setNodeId(config?.entry||'needs');setStage('language');try{const result=await load();if(!result.enabled){setError(t.unavailable)}}catch(e){setError(e instanceof Error?e.message:String(e))}}
 const finishRoute=(id:string,nextAnswers:typeof answers,chosenLocale:Locale=locale,silent=false)=>{const n=config?.nodes.find(n=>n.id===id);if(!n){setError(t.error);return}if(n.kind==='condition'){const value=n.condition==='locale'?chosenLocale:nextAnswers.reduce((rhythm,a)=>config?.nodes.find(node=>node.id===a.node)?.choices.find(c=>c.key===a.key)?.assign?.rhythm||rhythm,'');finishRoute(n.matches?.[value]||n.otherwise||'',nextAnswers,chosenLocale,silent);return}if(n.kind==='queue'||n.kind==='offline'){setQueue(n.queue||'general');setAnswers(nextAnswers);setStage('context');setForm(f=>({...f,details:f.details||n.title[chosenLocale]}));prompt.current?.pause()}else{setAnswers(nextAnswers);setNodeId(id);setStage('menu');if(!silent&&info?.open)play(info?.audio[n.prompt[chosenLocale]||''])}}
 const choose=(key:string)=>{if(mode==='direct'||mode==='message'||mode==='callback'||mode==='chat'){const q=QUEUES.find((_,i)=>String(i+1)===key);if(q){setQueue(q.key);setStage('context');setForm(f=>({...f,details:f.details||q.label[locale]}))}return}const choice=node?.choices.find(c=>c.key===key);if(choice)finishRoute(choice.next,[...answers,{node:node!.id,key}]);else if(/^[1-9]$/.test(key))play(info?.audio[config?.error[locale]||''])}
 useEffect(()=>{if(!open||currentStage!=='menu')return;const press=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches('input,textarea,select'))return;if(e.key==='0'){setMode('direct');setQueue('general');setForm(f=>({...f,details:f.details||QUEUES.find(q=>q.key==='general')!.label[locale]}));setStage('context');prompt.current?.pause()}else if(e.key==='*'){back()}else if(e.key==='9'&&!node?.choices.some(c=>c.key==='9'))play(info?.audio[node?.prompt[locale]||'']);else choose(e.key)};window.addEventListener('keydown',press);return()=>window.removeEventListener('keydown',press)})
 function back(){setError('');prompt.current?.pause();if(stage==='context'&&answers.length){const last=answers[answers.length-1];setNodeId(last.node);setAnswers(answers.slice(0,-1));setStage('menu')}else if(stage==='menu'&&answers.length){const last=answers[answers.length-1];setNodeId(last.node);setAnswers(answers.slice(0,-1))}else if(stage==='menu'||stage==='context')setStage('language');else setStage('home')}
 const receive=async()=>{setError('');if(!form.consent){setError(t.required);return}setPending(true);try{let requestedMode=mode;const serving=info?.agents.some(a=>a.queues.includes(queue)&&a.locales.includes(locale));if((mode==='voice'||mode==='direct'||mode==='chat')&&(!info?.open||!serving||mode!=='chat'&&!info?.voiceReady)){setError(info?.open?t.busy:t.closed);setPending(false);return}if(mode==='voice'||mode==='direct'){if(!navigator.mediaDevices?.getUserMedia)throw Error(t.denied);try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});stream.getTracks().forEach(track=>track.stop())}catch{throw Error(t.denied)}}const s=await hotlineRequest<PublicSnapshot>('receive',{...form,followUp:form.followUp?new Date(form.followUp+'Z').toISOString():'',locale,queue,answers,direct:mode!=='voice',mode:requestedMode,channel:mode==='chat'?'chat':'voice',sourcePath:pathname});setSnapshot(s);setStage('session');prompt.current?.pause()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setPending(false)}}
 const action=async(name:string,body:unknown={})=>{if(!session)return;setPending(true);setError('');try{const s=await hotlineRequest<PublicSnapshot>(`sessions/${session.id}/${name}`,body);setSnapshot(s);if(name==='message')setMessage('');if(['end','callback'].includes(name)){media.disconnect();music.current?.pause();setConfirmEnd(false);setCallbackOpen(false)}}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setPending(false)}}
 const retrySound=()=>{prompt.current?.play().catch(()=>{});music.current?.play().catch(()=>{});media.enableSound();setAudioBlocked(false)}
 const available=info?.enabled&&info.open&&info.voiceReady;const selectedQueue=QUEUES.find(q=>q.key===queue);const choices=mode==='voice'?node?.choices:QUEUES.map((q,i)=>({key:String(i+1),label:q.label,next:''}));const waiting=live&&['queued','offered'].includes(session.state)
 if(!mounted||pathname?.includes('/admin')||pathname?.includes('/preview'))return null
 const body=<div className={styles.publicHost} data-hotline-state={session?.state||stage} dir={locale==='ar'?'rtl':'ltr'} lang={locale}>
  <button ref={launcher} type="button" className={styles.launcher} onClick={()=>setOpen(!open)} aria-label={t.open} aria-expanded={open} aria-controls="angelcare-hotline-window"><span className={styles.launcherOrb}><Headphones size={27}/><span className={styles.launcherDot}/></span><span className={styles.launcherLabel}>{live?t.minimized:t.support}<small>{live?humanDuration(Math.max(0,(now-Date.parse(session.created_at))/1000),locale):t.new+' · '+t.free}</small></span></button>
  {open?<div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div ref={panel} className={styles.publicWindow} id="angelcare-hotline-window" role="dialog" aria-modal="true" aria-label={t.support}>
   <header className={styles.publicHeader}><div className={styles.brand}><img src="/brand/angelcare-pearl-rim-colour-r1.png" alt="AngelCare"/><span>HOTLINE <b>LIVE CARE</b></span></div><div className={styles.headerControls}><select aria-label={t.language} value={locale} disabled={Boolean(live)} onChange={e=>setLocale(e.target.value as Locale)}><option value="ar">العربية</option><option value="fr">Français</option><option value="en">English</option></select><button type="button" onClick={()=>setOpen(false)} aria-label={t.close}><ChevronDown/></button></div></header>
   <div className={styles.publicBody}>
    {currentStage==='home'?<><div className={styles.welcome}><span className={styles.eyebrow}><Sparkles size={14}/>{t.new} · {t.free}</span><h2>{t.headline}</h2><p>{config?.label[locale]||t.subtitle}</p><div className={styles.heroArt} aria-hidden="true"><div className={styles.orbitOne}/><div className={styles.orbitTwo}/><div className={styles.heroHeadset}><Headphones size={74}/><span>♡</span></div><i/><i/><i/></div><div className={styles.availability}><span className={styles.statusDot} data-inactive={!available}/>{info?available?t.voice:t.offline:t.loading}</div></div><button className={styles.primaryCard} type="button" onClick={()=>start('voice')}><span className={styles.cardIcon}><PhoneCall/></span><span><b>{t.voice}</b><small>{t.voiceNote}</small></span><ArrowUpRight/></button><button className={styles.secondaryCard} type="button" onClick={()=>start('direct')}><Headphones/><span><b>{t.direct}</b><small>{t.directNote}</small></span><ArrowUpRight/></button><div className={styles.bottomChoices}><button type="button" onClick={()=>start('chat')}><MessageCircle size={17}/>{t.chat}</button><button type="button" onClick={()=>start('message')}>{t.text}</button></div></>:null}
    {currentStage==='language'?<><div className={styles.stepHead}><span>01 / 05 · LANGUAGE</span><h2>{t.language}</h2><p>{t.subtitle}</p></div><div className={styles.languageCards}>{LANGUAGES.map((l,i)=><button type="button" key={l} onClick={()=>{setLocale(l);if(mode==='voice'){finishRoute(config?.entry||'needs',[],l,true);play(info?.audio[(info?.open?config?.greeting[l]:config?.closed[l])||'']);if(prompt.current)prompt.current.onended=()=>finishRoute(config?.entry||'needs',[],l)}else{setStage('menu');setNodeId(config?.entry||'needs');play(info?.audio[(info?.open?config?.greeting[l]:config?.closed[l])||''])}}}><span>{i+1}</span><b>{l==='ar'?'العربية':l==='fr'?'Français':'English'}</b><small>{l==='ar'?'اضغط 1':l==='fr'?'Appuyez sur 2':'Press 3'}</small><Globe2/></button>)}</div><p className={styles.help}>{t.mic}</p></>:null}
    {currentStage==='menu'?<><div className={styles.stepHead}><span>0{Math.min(2+answers.length,4)} / 05 · RECEPTION</span><h2>{mode==='voice'?node?.title[locale]||t.need:t.need}</h2><p>{mode==='voice'?t.voiceNote:t.directNote}</p></div><div className={styles.keypad}>{choices?.map(c=><button type="button" key={c.key} onClick={()=>choose(c.key)}><kbd>{c.key}</kbd><span>{c.label[locale]}</span><ArrowUpRight size={18}/></button>)}</div>{mode==='voice'?<div className={styles.menuTools}><button type="button" onClick={()=>play(info?.audio[node?.prompt[locale]||''])}><Volume2 size={16}/>{t.repeat}</button><button type="button" onClick={()=>{setMode('direct');setQueue('general');setForm(f=>({...f,details:f.details||QUEUES.find(q=>q.key==='general')!.label[locale]}));setStage('context');prompt.current?.pause()}}>0 · {t.direct}</button></div>:null}</>:null}
    {currentStage==='context'?<><div className={styles.stepHead}><span>05 / 05 · {selectedQueue?.label[locale]}</span><h2>{t.context}</h2><p>{info?.open?t.mic:t.closed}</p></div><form onSubmit={e=>{e.preventDefault();receive()}} className={styles.contextForm}><label>{t.name}<input maxLength={120} value={form.name} autoComplete="name" onChange={e=>setForm({...form,name:e.target.value})}/></label><label>{t.contact}<input maxLength={180} required={mode==='message'||mode==='callback'} value={form.contact} onChange={e=>setForm({...form,contact:e.target.value})}/></label><label>{t.reference}<input maxLength={120} value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><label>{t.message}<textarea required rows={3} maxLength={3000} value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/></label>{mode==='callback'?<label>{t.callbackAt}<input type="datetime-local" value={form.followUp} onChange={e=>setForm({...form,followUp:e.target.value})}/></label>:null}<label className={styles.consent}><input type="checkbox" checked={form.consent} onChange={e=>setForm({...form,consent:e.target.checked})}/><span>{t.consent}</span></label><button className={styles.primaryButton} disabled={pending||!info?.enabled} type="submit">{pending?t.loading:mode==='message'||mode==='callback'?t.send:t.join}<ArrowUpRight size={18}/></button></form><div className={styles.bottomChoices}><button type="button" onClick={()=>setMode('message')}>{t.text}</button><button type="button" onClick={()=>setMode('callback')}>{t.callback}</button></div></>:null}
    {currentStage==='session'&&snapshot?<><div className={styles.sessionHead}><span className={styles.eyebrow}>{snapshot.case.public_reference} · {QUEUES.find(q=>q.key===session?.queue_key)?.label[locale]}</span><h2>{waiting?t.queue:terminal?session?.state==='callback'||session?.state==='message'?t.received:t.ended:session?.state==='connected'?t.connected:t.connecting}</h2><p>{terminal?t.follow:snapshot.agentName||t.subtitle}</p></div>{waiting?<><div className={styles.waitArt} aria-hidden="true"><Headphones size={64}/><span/><span/><span/></div><div className={styles.queueMetrics}><div><b>{snapshot.position??'—'}</b><small>{t.position}</small></div><div><b>{snapshot.agents}</b><small>{t.agents}</small></div><div><b>{humanDuration(snapshot.estimatedWaitSeconds,locale)}</b><small>{t.wait}</small></div><div><b>{humanDuration(snapshot.averageSeconds,locale)}</b><small>{t.average}</small></div></div><p className={styles.help}>{t.queueInfo}</p><div className={styles.musicControl}><Volume2 size={18}/><label>{t.music}<input aria-label={t.music} type="range" min="0" max="1" step=".05" value={musicVolume} onChange={e=>setMusicVolume(Number(e.target.value))}/></label><span>{humanDuration(Math.max(0,(now-Date.parse(session!.created_at))/1000),locale)}</span></div><div className={styles.bottomChoices}><button type="button" disabled={pending} onClick={()=>{setForm(f=>({...f,contact:f.contact||session?.contact||''}));setCallbackOpen(true)}}>{t.callback}</button><button type="button" onClick={()=>setConfirmEnd(true)}>{t.leave}</button></div></>:null}
     {live&&!waiting?<><div className={styles.callArt} style={{'--voice-level':String(media.level)} as React.CSSProperties}><div/><Headphones size={64}/><span>{session?.held?(locale==='fr'?'Votre conseiller prépare la suite…':locale==='ar'?'يجهز مستشاركم الخطوة التالية…':'Your adviser is preparing the next step…'):session?.channel==='chat'?t.chat:media.status==='connected'?snapshot.agentName||t.agent:t.connecting}</span><b>{session?.connected_at?humanDuration(Math.max(0,(now-Date.parse(session.connected_at))/1000),locale):'…'}</b></div>{session?.channel==='voice'?<><div className={styles.callControls}><button type="button" className={media.muted?styles.muted:''} onClick={()=>media.toggle()} aria-label={media.muted?t.unmute:t.mute}>{media.muted?<MicOff/>:<Mic/>}</button><button type="button" className={styles.endButton} onClick={()=>setConfirmEnd(true)} aria-label={t.hangup}><PhoneOff/></button><button type="button" onClick={()=>setOpen(false)} aria-label={t.close}><ChevronDown/></button></div><label className={styles.volume}>{t.speaker}<input type="range" min="0" max="1" step=".05" value={media.volume} onChange={e=>media.setVolume(Number(e.target.value))}/></label>{media.devices.length?<div className={styles.deviceRow}>{(['audioinput','audiooutput'] as const).map(kind=><label key={kind}>{kind==='audioinput'?t.microphone:t.speaker}<select onChange={e=>media.chooseDevice(kind,e.target.value)}>{media.devices.filter(d=>d.kind===kind).map(d=><option value={d.deviceId} key={d.deviceId}>{d.label||kind}</option>)}</select></label>)}</div>:null}{media.error?<div className={styles.error}>{t.queueLost}<button type="button" onClick={()=>media.connect(session!.id,session!.room_name)}>{t.retry}</button><button type="button" onClick={retrySound}>{t.sound}</button></div>:null}</>:<button type="button" onClick={()=>setConfirmEnd(true)}>{t.hangup}</button>}</>:null}
     <div className={styles.conversation}><h3>{t.notes}</h3>{snapshot.events.filter(e=>e.body&&['message','case_updated'].includes(e.kind)).map(e=><div className={e.actor_id?styles.agentBubble:styles.customerBubble} key={e.id}><small>{e.actor_id?t.agent:form.name||t.name} · {new Date(e.created_at).toLocaleTimeString(locale)}</small><p>{e.body}</p></div>)}{live||['callback','message'].includes(session!.state)?<form onSubmit={e=>{e.preventDefault();action('message',{body:message})}}><label className={styles.srOnly} htmlFor="ac-hotline-message">{t.write}</label><input id="ac-hotline-message" value={message} maxLength={3000} placeholder={t.write} onChange={e=>setMessage(e.target.value)}/><button type="submit" disabled={pending||!message.trim()} aria-label={t.send}><ArrowUpRight/></button></form>:null}</div>{terminal?<div className={styles.receipt}><ShieldCheck/><div><b>{t.case}: {snapshot.case.public_reference}</b><p>{t.follow}</p><span>{t.status}: {snapshot.case.status}</span>{snapshot.case.follow_up_at?<p>{t.callbackAt}: {new Date(snapshot.case.follow_up_at).toISOString().slice(0,16).replace('T',' ')}</p>:null}</div></div>:null}
    </>:null}
    {!info?.enabled&&info?<a className={styles.supportFallback} href={`/angelcare-marketplace/${locale}/account/support`}>{t.text} <ArrowUpRight size={16}/></a>:null}{error?<div className={styles.error} role="alert">{error}<button type="button" onClick={()=>load().catch(()=>{})}><RefreshCw size={15}/>{t.retry}</button></div>:null}{audioBlocked?<button type="button" className={styles.soundButton} onClick={retrySound}><Volume2 size={16}/>{t.sound}</button>:null}
   </div>
   <footer className={styles.publicFooter}>{!live&&stage!=='home'?<button type="button" onClick={back}><ArrowLeft size={15}/>{t.back}</button>:<span><ShieldCheck size={14}/> ANGELCARE CARE</span>}<small>{config?.hours.map(h=>`${String(Math.floor(h.start)).padStart(2,'0')}:${String(Math.round(h.start%1*60)).padStart(2,'0')}–${String(Math.floor(h.end)).padStart(2,'0')}:${String(Math.round(h.end%1*60)).padStart(2,'0')}`).join(' · ')||t.hours} UTC+0</small></footer><p className={styles.disclaimer}>{t.privacy} {t.scope}</p>
   {callbackOpen?<div className={styles.confirmLayer}><form className={styles.callbackForm} onSubmit={e=>{e.preventDefault();action('callback',{contact:form.contact,followUp:form.followUp?new Date(form.followUp+'Z').toISOString():''})}}><h3>{t.callback}</h3><label>{t.contact}<input required value={form.contact} onChange={e=>setForm({...form,contact:e.target.value})}/></label><label>{t.callbackAt}<input type="datetime-local" value={form.followUp} onChange={e=>setForm({...form,followUp:e.target.value})}/></label><button type="submit" className={styles.primaryButton} disabled={pending}>{t.send}</button><button type="button" onClick={()=>setCallbackOpen(false)}>{t.cancel}</button></form></div>:null}{confirmEnd?<div className={styles.confirmLayer}><div><PhoneOff/><h3>{t.confirm}</h3><button type="button" className={styles.endButton} disabled={pending} onClick={()=>action('end')}>{t.hangup}</button><button type="button" onClick={()=>setConfirmEnd(false)}>{t.cancel}</button></div></div>:null}
  </div></div>:null}
 </div>
 return createPortal(body,document.body)
}
