import type { AcCapitalOsFoundationContract, AcCapitalOsWorkspace } from './types';

export const AC_CAPITAL_OS_FOUNDATION: AcCapitalOsFoundationContract = {
  moduleName: 'AC CAPITAL OS',
  route: '/ac-capital-os',
  signedBackend: true,
  signedFrontEnd: true,
  protectedInternalAccess: true,
  megaZip: 8,
  mission:
    'Keep AngelCare permanently capital-ready through AI-assisted fundraising intelligence, qualification, case preparation, doctrine injection, data-room readiness and coordinator execution control.',
  visualDoctrine:
    'Premium finance command universe: McKinsey-grade capital strategy room, Bloomberg-style intelligence, VC pipeline cockpit and institutional bank dossier control plane.',
};

export const AC_CAPITAL_OS_WORKSPACES: AcCapitalOsWorkspace[] = [
  {
    key: 'executive-cockpit',
    name: 'Capital Executive Cockpit',
    route: '/ac-capital-os',
    universe: 'capital command room',
    mission: 'Expose the day’s capital priorities, deadline risks, AI-prepared actions and readiness score in under 60 seconds.',
    status: 'activated-mz2',
    accent: 'navy',
    protected: true,
    megaZip: 2,
    frontEndObligation: 'Premium capital dashboard with readiness score, AI actions, pipeline value, blockers and command plan.',
    backEndObligation: 'Aggregate opportunities, cases, documents, tasks, deadlines, doctrine and AI run signals.',
    backofficeObligation: 'Leadership-ready status, alerts, ownership and readiness controls.',
  },
  {
    key: 'capital-radar',
    name: 'Capital Radar',
    route: '/ac-capital-os/radar',
    universe: 'global radar / funding intelligence map',
    mission: 'Detect Morocco, Africa, MENA and international funding, VC, grant, bank and accelerator opportunities.',
    status: 'activated-mz3',
    accent: 'blue',
    protected: true,
    megaZip: 3,
    frontEndObligation: 'Opportunity stream, source confidence, deadline heat, funding type filters and send-to-qualification actions.',
    backEndObligation: 'Research run records, opportunity capture, source metadata and confidence scoring.',
    backofficeObligation: 'Radar source configuration, scan history and ignored/accepted source control.',
  },
  {
    key: 'qualification-engine',
    name: 'Qualification Engine',
    route: '/ac-capital-os/qualification',
    universe: 'investment committee scoring room',
    mission: 'Score every opportunity against AngelCare’s exact fundraising reality and decide pursue, prepare, watch or reject.',
    status: 'activated-mz4',
    accent: 'teal',
    protected: true,
    megaZip: 4,
    frontEndObligation: 'Fit dossier with score bars, decision label, risks, missing documents and human next action.',
    backEndObligation: 'Eligibility scoring, scoring weights, decision states and qualification history.',
    backofficeObligation: 'Editable scoring criteria, override reasons and committee review trace.',
  },
  {
    key: 'funder-intelligence',
    name: 'Funder Intelligence Room',
    route: '/ac-capital-os/funders',
    universe: 'private investor intelligence office',
    mission: 'Profile funders, investors, banks and programs with psychology, objections, best narrative and relationship status.',
    status: 'activated-mz5',
    accent: 'purple',
    protected: true,
    megaZip: 5,
    frontEndObligation: 'Investor dossiers, relationship map, likely objections, contact panel and next-message strategy.',
    backEndObligation: 'Funder profiles, contacts, relationship events, notes, stage focus and investment thesis metadata.',
    backofficeObligation: 'Relationship ownership, next contact, interaction history and intelligence review.',
  },
  {
    key: 'case-builder',
    name: 'Fundraising Case Builder',
    route: '/ac-capital-os/cases',
    universe: 'capital dossier factory',
    mission: 'Prepare full fundraising packages: strategy, documents, financials, pitch, emails, scripts and annexes.',
    status: 'activated-mz7',
    accent: 'green',
    protected: true,
    megaZip: 7,
    frontEndObligation: 'Left-to-right case factory with document statuses and approval actions.',
    backEndObligation: 'Case records, document versions, generation jobs, approvals and package readiness.',
    backofficeObligation: 'Founder approval, document locking, regeneration history and submission readiness.',
  },
  {
    key: 'data-room',
    name: 'Due Diligence Data Room',
    route: '/ac-capital-os/data-room',
    universe: 'secure institutional data vault',
    mission: 'Keep AngelCare permanently bank, VC, grant and investor data-room ready.',
    status: 'activated-mz8',
    accent: 'navy',
    protected: true,
    megaZip: 8,
    frontEndObligation: 'Document vault, pack generator, expiry alerts, missing documents and case recommendations.',
    backEndObligation: 'Document metadata, category, version, status, expiry, reviewer and case relations.',
    backofficeObligation: 'Document approval, reusable proof tagging, missing-doc queue and pack exports.',
  },
  {
    key: 'capital-pipeline',
    name: 'Capital Pipeline CRM',
    route: '/ac-capital-os/pipeline',
    universe: 'deal-flow board / capital pipeline floor',
    mission: 'Track every funder, opportunity, deadline, submission, follow-up, negotiation and learning state.',
    status: 'locked-future-zip',
    accent: 'amber',
    protected: true,
    megaZip: 9,
    frontEndObligation: 'Board, table, timeline, calendar and value forecast views.',
    backEndObligation: 'Pipeline stages, opportunity states, follow-up records and decision outcomes.',
    backofficeObligation: 'Stage configuration, assignment, export, overdue alerts and won/lost learning.',
  },
  {
    key: 'coordinator-cockpit',
    name: 'Human Coordinator Cockpit',
    route: '/ac-capital-os/coordinator',
    universe: 'mission control task desk',
    mission: 'Reduce the human role to clear approval, communication, upload, signature and follow-up execution.',
    status: 'locked-future-zip',
    accent: 'teal',
    protected: true,
    megaZip: 10,
    frontEndObligation: 'Today’s actions, calls, emails, uploads, signatures, AI-prepared tasks and escalation actions.',
    backEndObligation: 'Task records, approval states, execution proof, reminders and coordinator notes.',
    backofficeObligation: 'Task ownership, deadlines, proof upload, escalation and completion audit.',
  },
  {
    key: 'doctrine-vault',
    name: 'Capital Doctrine Vault',
    route: '/ac-capital-os/doctrine',
    universe: 'strategic knowledge vault',
    mission: 'Inject and preserve AngelCare fundraising doctrine, objectives, commands, prompts, skills and monthly AI updates.',
    status: 'activated-mz6',
    accent: 'green',
    protected: true,
    megaZip: 6,
    frontEndObligation: 'Doctrine cards, active/inactive states, version history, conflict warnings and apply-to-cases action.',
    backEndObligation: 'Doctrine records, versions, sources, validity, priority, injected_by and affected workspaces.',
    backofficeObligation: 'Founder approval, conflict resolution, doctrine deprecation and active-case propagation.',
  },
  {
    key: 'ai-command-center',
    name: 'AI Command & Skills Center',
    route: '/ac-capital-os/ai-command',
    universe: 'AI control laboratory',
    mission: 'Manage AI agents, skills, prompts, model/provider settings, confidence, errors and troubleshooting.',
    status: 'locked-future-zip',
    accent: 'red',
    protected: true,
    megaZip: 11,
    frontEndObligation: 'Agent registry, skills library, AI run history, confidence meters, issue tracker and cost controls.',
    backEndObligation: 'Agent configuration, prompt versions, run logs, skill records, issue states and provider settings.',
    backofficeObligation: 'AI approval rules, troubleshooting, doctrine fixes, prompt updates and model governance.',
  },
  {
    key: 'strategy-simulator',
    name: 'Capital Strategy Simulator',
    route: '/ac-capital-os/simulator',
    universe: 'scenario war room',
    mission: 'Compare bank financing, grants, VC, angels, accelerators, blended finance, SaaS investment and expansion routes.',
    status: 'locked-future-zip',
    accent: 'purple',
    protected: true,
    megaZip: 12,
    frontEndObligation: 'Scenario cards, risk radar, runway, dilution, repayment, document readiness and route recommendation.',
    backEndObligation: 'Scenario assumptions, scores, recommendation history and founder decision records.',
    backofficeObligation: 'Scenario templates, assumption editing, final recommendation and export.',
  },
  {
    key: 'reports',
    name: 'Reports',
    route: '/ac-capital-os/reports',
    universe: 'capital reporting suite',
    mission: 'Generate leadership, bank, investor and operational capital readiness reports.',
    status: 'locked-future-zip',
    accent: 'blue',
    protected: true,
    megaZip: 12,
    frontEndObligation: 'Report templates, A4 previews, export controls and evidence summaries.',
    backEndObligation: 'Report generation records, templates, filters and export history.',
    backofficeObligation: 'Approval, export, archive and distribution status.',
  },
  {
    key: 'manual-sop',
    name: 'Manual & SOP',
    route: '/ac-capital-os/manual',
    universe: 'interactive operating academy',
    mission: 'Train coordinators to use AC CAPITAL OS without separate coaching.',
    status: 'foundation-ready',
    accent: 'green',
    protected: true,
    megaZip: 12,
    frontEndObligation: 'Integrated SOP/manual workbook shell with checklists, do/don’t rules, glossary and learning states.',
    backEndObligation: 'Manual chapters, progress states, acknowledgements and role-based workbook sections.',
    backofficeObligation: 'Manual updates, versioning, acknowledgement tracking and downloadable workbook export.',
  },
  {
    key: 'settings',
    name: 'Settings',
    route: '/ac-capital-os/settings',
    universe: 'capital operating configuration',
    mission: 'Configure module behavior, permissions, alert thresholds, scoring defaults, future AI providers and safe modes.',
    status: 'foundation-ready',
    accent: 'navy',
    protected: true,
    megaZip: 1,
    frontEndObligation: 'Settings shell with safe-mode posture, module registry and access doctrine.',
    backEndObligation: 'Feature flags, protected access posture, registry metadata and audit-ready changes.',
    backofficeObligation: 'Only authorized roles can adjust AC CAPITAL OS operating settings.',
  },
];

export function getAcCapitalOsReadinessSummary() {
  const total = AC_CAPITAL_OS_WORKSPACES.length;
  const foundationReady = AC_CAPITAL_OS_WORKSPACES.filter((workspace) => workspace.status === 'foundation-ready').length;
  const activated = AC_CAPITAL_OS_WORKSPACES.filter((workspace) => ['activated-mz2','activated-mz3','activated-mz4','activated-mz5','activated-mz6','activated-mz7','activated-mz8'].includes(workspace.status)).length;
  const contractedNext = AC_CAPITAL_OS_WORKSPACES.filter((workspace) => workspace.status === 'contracted-next').length;
  const futureLocked = AC_CAPITAL_OS_WORKSPACES.filter((workspace) => workspace.status === 'locked-future-zip').length;

  return {
    total,
    activated,
    foundationReady,
    contractedNext,
    futureLocked,
    megaZip: 8,
    readinessLabel: 'Due Diligence Data Room activated — evidence, versions, package readiness, submission archive and capital proof vault controls are now installed',
  };
}

export const AC_CAPITAL_OS_MZ3_TOKEN = 'MZ3_AC_CAPITAL_OS_CAPITAL_RADAR' as const;

export const AC_CAPITAL_OS_MZ5_TOKEN = 'MZ5_AC_CAPITAL_OS_FUNDER_INTELLIGENCE' as const;

export const AC_CAPITAL_OS_MZ6_TOKEN = 'MZ6_AC_CAPITAL_OS_CAPITAL_DOCTRINE' as const;

export const AC_CAPITAL_OS_MZ7_TOKEN = 'MZ7_AC_CAPITAL_OS_FUNDRAISING_CASE_BUILDER' as const;

export const AC_CAPITAL_OS_MZ8_TOKEN = 'MZ8_AC_CAPITAL_OS_DUE_DILIGENCE_DATA_ROOM' as const;
