import type { VendorCommerceLink, SettlementReadiness, OperationsDispute } from '../operations-reconciliation/types'

export type VendorLifecycleStatus='onboarding'|'qualification'|'due_diligence'|'approved'|'contracted'|'active'|'performance_review'|'restricted'|'suspended'|'terminated'
export type VendorContractStatus='draft'|'due_diligence'|'approval_pending'|'approved'|'active'|'renewal_due'|'suspended'|'terminated'|'expired'
export type VendorOrderStatus='requested'|'accepted'|'rejected'|'preparing'|'dispatched'|'delivered'|'evidence_pending'|'validated'|'disputed'|'cancelled'|'closed'
export type VendorQualityStatus='open'|'evidence_required'|'review'|'approved'|'corrective_action'|'failed'|'closed'

export interface VendorContract {id:string;vendor_id:string;public_reference:string;contract_reference:string|null;status:VendorContractStatus;starts_at:string|null;ends_at:string|null;renewal_mode:string;service_level:Record<string,unknown>;commercial_terms:Record<string,unknown>;settlement_terms:Record<string,unknown>;compliance_requirements:Record<string,unknown>;owner_id:string|null;approved_by:string|null;approved_at:string|null;created_by:string|null;updated_by:string|null;created_at:string;updated_at:string;vendor?:Pick<VendorCommerceLink,'id'|'display_name'|'vendor_reference'|'status'>|null}
export interface VendorOrder {id:string;vendor_id:string;fulfillment_case_id:string|null;public_reference:string;status:VendorOrderStatus;amount:number;currency:string;expected_at:string|null;delivered_at:string|null;evidence_status:string;quality_status:string;settlement_status:string;owner_id:string|null;tenant_id:string|null;territory_id:string|null;created_by:string|null;created_at:string;updated_at:string;vendor?:Pick<VendorCommerceLink,'id'|'display_name'|'vendor_reference'|'status'>|null}
export interface VendorInventory {id:string;vendor_id:string;catalog_item_id:string;status:string;quantity_available:number|null;quantity_reserved:number;lead_time_minutes:number|null;source:string;source_reference:string|null;observed_at:string;updated_by:string|null;vendor?:Pick<VendorCommerceLink,'id'|'display_name'|'vendor_reference'>|null}
export interface VendorQualityReview {id:string;vendor_id:string;vendor_order_id:string|null;review_type:string;status:VendorQualityStatus;score:number|null;findings:Record<string,unknown>;corrective_actions:unknown[]|Record<string,unknown>;owner_id:string|null;reviewed_by:string|null;reviewed_at:string|null;due_at:string|null;created_at:string;updated_at:string;vendor?:Pick<VendorCommerceLink,'id'|'display_name'|'vendor_reference'>|null}
export interface VendorPerformanceEvent {id:string;vendor_id:string;event_type:string;score:number|null;severity:string|null;related_object_type:string|null;related_object_id:string|null;details:Record<string,unknown>;recorded_by:string|null;created_at:string;vendor?:Pick<VendorCommerceLink,'id'|'display_name'|'vendor_reference'>|null}
export interface VendorAuthoritySnapshot {vendors:VendorCommerceLink[];contracts:VendorContract[];orders:VendorOrder[];inventory:VendorInventory[];quality:VendorQualityReview[];performance:VendorPerformanceEvent[];settlements:SettlementReadiness[];disputes:OperationsDispute[]}
