import {createServiceClient} from '@/lib/supabase/server'
import type {MarketplaceRequestContext} from '../domain/types'
import type {FinanceCustomerOption,FinanceException,FinanceInvoice,FinanceMetrics,FinanceNextMove,FinanceOrderOption,FinancePayment,FinanceReceipt,FinanceReconciliation,FinanceRefund,FinanceSeverity,FinanceSubscription,FinanceWallet,FinancialControlLedgerSnapshot} from './types'
type Row=Record<string,any>
const rows=(v:unknown):Row[]=>Array.isArray(v)?v as Row[]:[]
const text=(v:unknown)=>String(v??'').trim()
const nullable=(v:unknown)=>{const s=text(v);return s||null}
const num=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0
const obj=(v:unknown):Row=>v&&typeof v==='object'&&!Array.isArray(v)?v as Row:{}
const iso=(v:unknown)=>{const s=text(v);if(!s)return null;const d=new Date(s);return Number.isFinite(d.getTime())?d.toISOString():null}
const hoursSince=(v:unknown)=>{const s=iso(v);return s?Math.max(0,Math.round((Date.now()-new Date(s).getTime())/3600000)):0}
async function optional<T>(work:()=>PromiseLike<any>,fallback:T):Promise<T>{try{const r=await work();if(r?.error)return fallback;return (r?.data??fallback) as T}catch{return fallback}}
function globalScope(context:MarketplaceRequestContext){return context.roleKeys.includes('marketplace_admin')||context.roleKeys.includes('marketplace_super_admin')||context.roleKeys.includes('marketplace_executive')||context.assignments.some(a=>a.scopeType==='global')}
function moneyFromJourney(row:Row){const f=obj(row.financial_status);return num(f.grand_total||f.total_amount||f.total||f.order_total||f.expected_amount||obj(row.assisted_order_payload).amount)}
function paymentSeverity(row:FinancePayment):FinanceSeverity{if(['failed','chargeback','disputed'].includes(row.status))return'critical';if(row.outstanding>0||row.reconciliationOpen>0)return'attention';if(['pending','requires_customer_action','requires_method','reconciliation_pending'].includes(row.status))return'watch';return'healthy'}
export async function financialControlLedgerSnapshot(context:MarketplaceRequestContext):Promise<FinancialControlLedgerSnapshot>{
 const db=await createServiceClient();const since=new Date(Date.now()-365*24*3600000).toISOString()
 const [paymentRows,attemptRows,refundRows,paymentReconRows,disputeRows,invoiceRows,receiptRows,walletRows,walletLedgerRows,walletRiskRows,walletReconRows,subscriptionRows,financeReconRows,customerRows,journeyRows,catalogRows]=await Promise.all([
  optional<Row[]>(()=>db.from('angelcare_marketplace_payment_intents').select('*').gte('updated_at',since).order('updated_at',{ascending:false}).limit(1800),[]),
  optional<Row[]>(()=>db.from('angelcare_marketplace_payment_attempts').select('*').gte('updated_at',since).order('created_at',{ascending:false}).limit(5000),[]),
  optional<Row[]>(()=>db.from('angelcare_marketplace_payment_refunds').select('*').gte('updated_at',since).order('created_at',{ascending:false}).limit(2500),[]),
  optional<Row[]>(()=>db.from('angelcare_marketplace_payment_reconciliation_items').select('*').gte('updated_at',since).order('updated_at',{ascending:false}).limit(2500),[]),
  optional<Row[]>(()=>db.from('angelcare_marketplace_payment_disputes').select('*').gte('updated_at',since).order('updated_at',{ascending:false}).limit(1200),[]),
  optional<Row[]>(()=>db.from('angelcare_marketplace_finance_invoices').select('*').gte('updated_at',since).order('updated_at',{ascending:false}).limit(2200),[]),
  optional<Row[]>(()=>db.from('angelcare_marketplace_finance_receipts').select('*').gte('issued_at',since).order('issued_at',{ascending:false}).limit(2500),[]),
  optional<Row[]>(()=>db.from('angelcare_marketplace_wallet_accounts').select('*').order('updated_at',{ascending:false}).limit(1800),[]),
  optional<Row[]>(()=>db.from('angelcare_marketplace_wallet_ledger_entries').select('*').gte('created_at',since).order('created_at',{ascending:false}).limit(6000),[]),
  optional<Row[]>(()=>db.from('angelcare_marketplace_wallet_risk_cases').select('*').order('updated_at',{ascending:false}).limit(2000),[]),
  optional<Row[]>(()=>db.from('angelcare_marketplace_wallet_reconciliation_items').select('*').order('updated_at',{ascending:false}).limit(2500),[]),
  optional<Row[]>(()=>db.from('angelcare_marketplace_customer_subscriptions').select('*').gte('updated_at',since).order('updated_at',{ascending:false}).limit(2200),[]),
  optional<Row[]>(()=>db.from('angelcare_marketplace_finance_reconciliation_events').select('*').gte('created_at',since).order('created_at',{ascending:false}).limit(2500),[]),
  optional<Row[]>(()=>db.from('angelcare_marketplace_customer_accounts').select('id,public_reference,display_name,email,tenant_id,territory_id').limit(5000),[]),
  optional<Row[]>(()=>db.from('angelcare_marketplace_journeys').select('id,public_reference,title,customer_account_id,tenant_id,territory_id,financial_status,assisted_order_payload,status,updated_at').gte('updated_at',since).limit(3500),[]),
  optional<Row[]>(()=>db.from('angelcare_marketplace_catalog_items').select('id,public_reference,name_fr').limit(4000),[]),
 ])
 const customersAll=rows(customerRows),journeysAll=rows(journeyRows)
 const allowedCustomerIds=new Set<string>()
 if(globalScope(context)){for(const c of customersAll)allowedCustomerIds.add(text(c.id))}else for(const c of customersAll){if(context.tenantId&&text(c.tenant_id)===context.tenantId)allowedCustomerIds.add(text(c.id));else if(!context.tenantId&&context.territoryId&&text(c.territory_id)===context.territoryId)allowedCustomerIds.add(text(c.id));else if(!context.tenantId&&!context.territoryId)allowedCustomerIds.add(text(c.id))}
 const customersMap=new Map(customersAll.filter(c=>allowedCustomerIds.has(text(c.id))).map(c=>[text(c.id),c]))
 const journeys=journeysAll.filter(j=>!j.customer_account_id||allowedCustomerIds.has(text(j.customer_account_id)))
 const journeyMap=new Map(journeys.map(j=>[text(j.id),j]))
 const catalogMap=new Map(rows(catalogRows).map(c=>[text(c.id),c]))
 const filteredPayments=rows(paymentRows).filter(p=>!p.customer_account_id||allowedCustomerIds.has(text(p.customer_account_id)))
 const paymentIds=new Set(filteredPayments.map(p=>text(p.id)))
 const attempts=rows(attemptRows).filter(x=>paymentIds.has(text(x.payment_intent_id)))
 const refundsRaw=rows(refundRows).filter(x=>paymentIds.has(text(x.payment_intent_id)))
 const paymentRecon=rows(paymentReconRows).filter(x=>!x.payment_intent_id||paymentIds.has(text(x.payment_intent_id)))
 const disputes=rows(disputeRows).filter(x=>paymentIds.has(text(x.payment_intent_id)))
 const invoicesRaw=rows(invoiceRows).filter(x=>allowedCustomerIds.has(text(x.customer_account_id)))
 const invoiceIds=new Set(invoicesRaw.map(x=>text(x.id)))
 const receiptsRaw=rows(receiptRows).filter(x=>!x.customer_account_id||allowedCustomerIds.has(text(x.customer_account_id)))
 const walletsRaw=rows(walletRows).filter(x=>allowedCustomerIds.has(text(x.customer_account_id)))
 const walletIds=new Set(walletsRaw.map(x=>text(x.id)))
 const walletLedger=rows(walletLedgerRows).filter(x=>walletIds.has(text(x.wallet_account_id)))
 const walletRisks=rows(walletRiskRows).filter(x=>walletIds.has(text(x.wallet_account_id)))
 const walletRecon=rows(walletReconRows).filter(x=>!x.wallet_account_id||walletIds.has(text(x.wallet_account_id)))
 const subscriptionsRaw=rows(subscriptionRows).filter(x=>allowedCustomerIds.has(text(x.customer_account_id)))
 const payments:FinancePayment[]=filteredPayments.map(p=>{const customer=customersMap.get(text(p.customer_account_id));const order=journeyMap.get(text(p.canonical_object_id));const rs=refundsRaw.filter(x=>text(x.payment_intent_id)===text(p.id));const recon=paymentRecon.filter(x=>text(x.payment_intent_id)===text(p.id)&&!['reconciled','waived'].includes(text(x.status)));const inv=invoicesRaw.find(x=>text(x.journey_id)===text(p.canonical_object_id));const receipt=receiptsRaw.find(x=>text(x.payment_intent_id)===text(p.id));const ats=attempts.filter(x=>text(x.payment_intent_id)===text(p.id));const expected=num(p.expected_amount),captured=num(p.captured_amount),refunded=num(p.refunded_amount);return{id:text(p.id),reference:text(p.public_reference)||`PAY-${text(p.id).slice(0,8)}`,customerId:nullable(p.customer_account_id),customerName:text(customer?.display_name)||'Client ANGELCARE',customerReference:text(customer?.public_reference),orderId:order?text(order.id):nullable(p.canonical_object_id),orderReference:text(order?.public_reference),status:text(p.status),currency:text(p.currency_label)||'Dh',expected,authorized:num(p.authorized_amount),captured,refunded,outstanding:['cancelled','expired','refunded'].includes(text(p.status))?0:Math.max(0,expected-captured),walletContribution:num(p.wallet_contribution),externalContribution:num(p.external_contribution),method:text(p.selected_method)||'—',provider:text(p.provider_key)||'—',providerReference:nullable(p.provider_reference),attemptCount:ats.length,failedAttemptCount:ats.filter(a=>text(a.status)==='failed'||Boolean(a.failure_code)).length,refundCount:rs.length,reconciliationOpen:recon.length,invoiceId:inv?text(inv.id):null,invoiceReference:inv?text(inv.public_reference||inv.invoice_number):null,receiptId:receipt?text(receipt.id):null,receiptReference:receipt?text(receipt.public_reference||receipt.receipt_number):null,updatedAt:text(p.updated_at)}})
 const paymentMap=new Map(payments.map(p=>[p.id,p]))
 const invoices:FinanceInvoice[]=invoicesRaw.map(i=>{const c=customersMap.get(text(i.customer_account_id));const order=journeyMap.get(text(i.journey_id));const receiptCount=receiptsRaw.filter(r=>text(r.invoice_id)===text(i.id)).length;return{id:text(i.id),reference:text(i.public_reference)||text(i.invoice_number),invoiceNumber:text(i.invoice_number),customerId:text(i.customer_account_id),customerName:text(c?.display_name)||'Client ANGELCARE',customerReference:text(c?.public_reference),orderId:nullable(i.journey_id),orderReference:text(order?.public_reference),status:text(i.status),currency:text(i.currency_label)||'Dh',subtotal:num(i.subtotal),discount:num(i.discount_total),tax:num(i.tax_total),total:num(i.total_amount),paid:num(i.paid_amount),balance:num(i.balance_due),dueAt:iso(i.due_at),issuedAt:iso(i.issued_at),receiptCount,updatedAt:text(i.updated_at)}})
 const invoiceMap=new Map(invoices.map(i=>[i.id,i]))
 const receipts:FinanceReceipt[]=receiptsRaw.map(r=>{const p=paymentMap.get(text(r.payment_intent_id));const i=invoiceMap.get(text(r.invoice_id));const c=customersMap.get(text(r.customer_account_id));return{id:text(r.id),reference:text(r.public_reference)||text(r.receipt_number),receiptNumber:text(r.receipt_number),paymentId:text(r.payment_intent_id),paymentReference:p?.reference||'',invoiceId:nullable(r.invoice_id),invoiceReference:i?.reference||'',customerId:nullable(r.customer_account_id),customerName:text(c?.display_name)||p?.customerName||'Client ANGELCARE',amount:num(r.amount),currency:text(r.currency_label)||'Dh',method:text(r.payment_method)||p?.method||'—',providerReference:nullable(r.provider_reference),status:text(r.status),issuedAt:text(r.issued_at)}})
 const refunds:FinanceRefund[]=refundsRaw.map(r=>{const p=paymentMap.get(text(r.payment_intent_id));const c=customersMap.get(text(r.customer_account_id));return{id:text(r.id),reference:text(r.public_reference)||`RFD-${text(r.id).slice(0,8)}`,paymentId:text(r.payment_intent_id),paymentReference:p?.reference||'',customerId:nullable(r.customer_account_id),customerName:text(c?.display_name)||p?.customerName||'Client ANGELCARE',orderReference:p?.orderReference||'',status:text(r.status),requested:num(r.requested_amount),walletRestore:num(r.wallet_restore_amount),externalRefund:num(r.external_refund_amount),promotionalRestore:num(r.promotional_restore_amount),reasonCode:text(r.reason_code),reason:text(r.reason),providerReference:nullable(r.provider_reference),createdAt:text(r.created_at),completedAt:iso(r.completed_at)}})
 const wallets:FinanceWallet[]=walletsRaw.map(w=>{const c=customersMap.get(text(w.customer_account_id));return{id:text(w.id),reference:text(w.public_reference)||`ACW-${text(w.id).slice(0,8)}`,customerId:text(w.customer_account_id),customerName:text(c?.display_name)||'Client ANGELCARE',customerReference:text(c?.public_reference),status:text(w.status),currency:text(w.currency_label)||'Dh',available:num(w.available_balance),purchased:num(w.purchased_balance),bonus:num(w.bonus_balance),reserved:num(w.reserved_balance),expiring:num(w.expiring_balance),lifetimeFunded:num(w.lifetime_funded),lifetimeSpent:num(w.lifetime_spent),lifetimeSavings:num(w.lifetime_savings),riskReason:nullable(w.risk_reason),openRisks:walletRisks.filter(r=>text(r.wallet_account_id)===text(w.id)&&text(r.status)==='open').length,openReconciliation:walletRecon.filter(r=>text(r.wallet_account_id)===text(w.id)&&!['reconciled','waived'].includes(text(r.status))).length,ledgerCount:walletLedger.filter(l=>text(l.wallet_account_id)===text(w.id)).length,updatedAt:text(w.updated_at)}})
 const subscriptions:FinanceSubscription[]=subscriptionsRaw.map(s=>{const c=customersMap.get(text(s.customer_account_id));const item=catalogMap.get(text(s.catalog_item_id));return{id:text(s.id),reference:text(s.public_reference)||`SUB-${text(s.id).slice(0,8)}`,customerId:text(s.customer_account_id),customerName:text(c?.display_name)||'Client ANGELCARE',customerReference:text(c?.public_reference),catalogItemId:nullable(s.catalog_item_id),catalogItemName:text(item?.name_fr)||'Abonnement ANGELCARE',status:text(s.status),billingPeriod:text(s.billing_period),quantity:num(s.quantity),amount:num(s.amount),currency:text(s.currency_label)||'Dh',startsAt:iso(s.starts_at),periodEndsAt:iso(s.current_period_ends_at),nextBillingAt:iso(s.next_billing_at),renewalMode:text(s.renewal_mode),cancelReason:nullable(s.cancel_reason),updatedAt:text(s.updated_at)}})
 const reconciliation:FinanceReconciliation[]=[
  ...paymentRecon.map(r=>{const p=r.payment_intent_id?paymentMap.get(text(r.payment_intent_id)):null;return{id:text(r.id),reference:`PAY-REC-${text(r.id).slice(0,8).toUpperCase()}`,source:'payment' as const,paymentId:nullable(r.payment_intent_id),walletId:null,customerName:p?.customerName||'Paiement',orderReference:p?.orderReference||'',expected:num(r.expected_amount),observed:num(r.provider_amount),difference:num(r.difference_amount),status:text(r.status),reason:text(obj(r.evidence).decision_reason),createdAt:text(r.created_at),resolvedAt:iso(r.reconciled_at)}}),
  ...walletRecon.map(r=>{const w=r.wallet_account_id?wallets.find(x=>x.id===text(r.wallet_account_id)):null;return{id:text(r.id),reference:`ACW-REC-${text(r.id).slice(0,8).toUpperCase()}`,source:'wallet' as const,paymentId:nullable(r.payment_intent_id),walletId:nullable(r.wallet_account_id),customerName:w?.customerName||'AngelCare Credit',orderReference:'',expected:num(r.expected_amount),observed:num(r.actual_amount),difference:num(r.actual_amount)-num(r.expected_amount),status:text(r.status),reason:text(r.reason),createdAt:text(r.created_at),resolvedAt:iso(r.reconciled_at)}}),
  ...rows(financeReconRows).map(r=>({id:text(r.id),reference:text(r.public_reference)||`REC-${text(r.id).slice(0,8)}`,source:'finance' as const,paymentId:null,walletId:null,customerName:text(r.source_system),orderReference:text(r.source_reference),expected:num(r.expected_amount),observed:num(r.observed_amount),difference:num(r.difference_amount),status:text(r.status),reason:text(r.resolution_note),createdAt:text(r.created_at),resolvedAt:iso(r.resolved_at)}))
 ].sort((a,b)=>b.createdAt.localeCompare(a.createdAt))
 const exceptions:FinanceException[]=[]
 for(const p of payments){const sev=paymentSeverity(p);if(['failed','chargeback','disputed'].includes(p.status))exceptions.push({id:`payment-${p.id}`,kind:'payment_failed',reference:p.reference,title:'Payment requires recovery',detail:`${p.status} · ${p.failedAttemptCount} failed attempt(s)`,customerName:p.customerName,orderReference:p.orderReference,amount:Math.max(p.outstanding,p.expected),severity:sev,ageHours:hoursSince(p.updatedAt),drawerKind:'payment',drawerId:p.id});else if(p.outstanding>0)exceptions.push({id:`outstanding-${p.id}`,kind:'outstanding',reference:p.reference,title:'Outstanding customer balance',detail:`${p.outstanding.toFixed(2)} ${p.currency} remains uncaptured`,customerName:p.customerName,orderReference:p.orderReference,amount:p.outstanding,severity:p.outstanding>=1000?'attention':'watch',ageHours:hoursSince(p.updatedAt),drawerKind:'payment',drawerId:p.id})}
 const now=Date.now();for(const i of invoices)if(i.status==='overdue'||(i.balance>0&&i.dueAt&&new Date(i.dueAt).getTime()<now))exceptions.push({id:`invoice-${i.id}`,kind:'invoice_overdue',reference:i.reference,title:'Invoice overdue',detail:`${i.balance.toFixed(2)} ${i.currency} outstanding`,customerName:i.customerName,orderReference:i.orderReference,amount:i.balance,severity:i.balance>=2500?'critical':'attention',ageHours:hoursSince(i.dueAt||i.updatedAt),drawerKind:'invoice',drawerId:i.id})
 for(const r of refunds)if(!['completed','cancelled','reconciled'].includes(r.status))exceptions.push({id:`refund-${r.id}`,kind:'refund_pending',reference:r.reference,title:'Refund awaiting completion',detail:`${r.status} · ${r.reasonCode}`,customerName:r.customerName,orderReference:r.orderReference,amount:r.requested,severity:r.status==='failed'?'critical':'attention',ageHours:hoursSince(r.createdAt),drawerKind:'refund',drawerId:r.id})
 for(const w of wallets)if(w.openRisks>0||w.status!=='active')exceptions.push({id:`wallet-${w.id}`,kind:'wallet_risk',reference:w.reference,title:'AngelCare Credit risk',detail:w.riskReason||`${w.openRisks} open wallet risk case(s)`,customerName:w.customerName,orderReference:'',amount:w.available,severity:w.status==='frozen'?'critical':'attention',ageHours:hoursSince(w.updatedAt),drawerKind:'credit',drawerId:w.id})
 for(const r of reconciliation)if(!['reconciled','resolved','waived','matched'].includes(r.status))exceptions.push({id:`recon-${r.source}-${r.id}`,kind:'reconciliation',reference:r.reference,title:'Financial mismatch',detail:`Difference ${r.difference.toFixed(2)} Dh · ${r.status}`,customerName:r.customerName,orderReference:r.orderReference,amount:Math.abs(r.difference),severity:Math.abs(r.difference)>=1000?'critical':'attention',ageHours:hoursSince(r.createdAt),drawerKind:'reconciliation',drawerId:`${r.source}:${r.id}`})
 for(const s of subscriptions)if(s.status==='past_due')exceptions.push({id:`sub-${s.id}`,kind:'subscription_past_due',reference:s.reference,title:'Subscription past due',detail:`${s.catalogItemName} · ${s.amount.toFixed(2)} ${s.currency}`,customerName:s.customerName,orderReference:'',amount:s.amount,severity:'attention',ageHours:hoursSince(s.updatedAt),drawerKind:'subscription',drawerId:s.id})
 for(const p of payments)if(p.captured>0&&!p.receiptId&&!['refunded','cancelled'].includes(p.status))exceptions.push({id:`receipt-${p.id}`,kind:'receipt_missing',reference:p.reference,title:'Captured payment without receipt',detail:`${p.captured.toFixed(2)} ${p.currency} captured`,customerName:p.customerName,orderReference:p.orderReference,amount:p.captured,severity:'watch',ageHours:hoursSince(p.updatedAt),drawerKind:'payment',drawerId:p.id})
 exceptions.sort((a,b)=>({critical:3,attention:2,watch:1,healthy:0}[b.severity]-{critical:3,attention:2,watch:1,healthy:0}[a.severity])||b.amount-a.amount)
 const expected=payments.reduce((s,p)=>s+p.expected,0),authorized=payments.reduce((s,p)=>s+p.authorized,0),captured=payments.reduce((s,p)=>s+p.captured,0),outstanding=payments.reduce((s,p)=>s+p.outstanding,0),refunded=payments.reduce((s,p)=>s+p.refunded,0),walletUsed=payments.reduce((s,p)=>s+p.walletContribution,0),offlineCaptured=payments.filter(p=>['manual_verified','bank_transfer','cash_on_delivery','pay_at_location'].includes(p.method)).reduce((s,p)=>s+p.captured,0),invoiceOutstanding=invoices.reduce((s,i)=>s+i.balance,0),unreconciled=reconciliation.filter(r=>!['reconciled','resolved','waived','matched'].includes(r.status)).reduce((s,r)=>s+Math.abs(r.difference),0)
 const reconciledCount=reconciliation.filter(r=>['reconciled','resolved','waived','matched'].includes(r.status)).length
 const metrics:FinanceMetrics={expected,authorized,captured,outstanding,refunded,walletUsed,offlineCaptured,invoiceOutstanding,unreconciled,failedPayments:payments.filter(p=>['failed','chargeback','disputed'].includes(p.status)).length,overdueInvoices:invoices.filter(i=>i.status==='overdue'||(i.balance>0&&Boolean(i.dueAt)&&new Date(i.dueAt!).getTime()<now)).length,pendingRefunds:refunds.filter(r=>!['completed','cancelled','reconciled'].includes(r.status)).length,walletRisk:wallets.filter(w=>w.openRisks>0||w.status!=='active').length,pastDueSubscriptions:subscriptions.filter(s=>s.status==='past_due').length,reconciliationRate:reconciliation.length?Math.round(reconciledCount/reconciliation.length*1000)/10:100}
 const nextMoves:FinanceNextMove[]=[]
 if(metrics.failedPayments)nextMoves.push({id:'failed',title:`Recover ${metrics.failedPayments} failed payment${metrics.failedPayments===1?'':'s'}`,detail:`${exceptions.filter(e=>e.kind==='payment_failed').reduce((s,e)=>s+e.amount,0).toFixed(2)} Dh exposed`,mode:'payments'})
 if(metrics.overdueInvoices)nextMoves.push({id:'overdue',title:`Resolve ${metrics.overdueInvoices} overdue invoice${metrics.overdueInvoices===1?'':'s'}`,detail:`${invoiceOutstanding.toFixed(2)} Dh total invoice balance`,mode:'invoices'})
 if(metrics.pendingRefunds)nextMoves.push({id:'refunds',title:`Close ${metrics.pendingRefunds} pending refund${metrics.pendingRefunds===1?'':'s'}`,detail:`Refund operations require financial completion`,mode:'refunds'})
 if(metrics.unreconciled>0)nextMoves.push({id:'recon',title:'Resolve financial mismatches',detail:`${metrics.unreconciled.toFixed(2)} Dh currently unmatched`,mode:'reconciliation'})
 if(metrics.walletRisk)nextMoves.push({id:'credit-risk',title:`Review ${metrics.walletRisk} AngelCare Credit risk${metrics.walletRisk===1?'':'s'}`,detail:'Restrictions, risk cases or reconciliation require attention',mode:'credit'})
 if(!nextMoves.length)nextMoves.push({id:'healthy',title:'Financial estate within current controls',detail:'No high-priority financial interruption detected from recorded state.',mode:'overview'})
 const customers:FinanceCustomerOption[]=[...customersMap.values()].map(c=>({id:text(c.id),reference:text(c.public_reference),name:text(c.display_name)||'Client ANGELCARE',email:nullable(c.email)})).sort((a,b)=>a.name.localeCompare(b.name)).slice(0,1200)
 const orders:FinanceOrderOption[]=journeys.map(j=>({id:text(j.id),reference:text(j.public_reference),title:text(j.title),customerId:nullable(j.customer_account_id),amount:moneyFromJourney(j)})).sort((a,b)=>a.reference.localeCompare(b.reference)).slice(0,1800)
 return{generatedAt:new Date().toISOString(),metrics,payments,invoices,receipts,refunds,wallets,subscriptions,reconciliation,exceptions,nextMoves,customers,orders}
}
