'use client'

import { Boxes, Edit3, GitBranch, PackagePlus, Plus, ShieldCheck, Sparkles } from 'lucide-react'
import { useDigitalTwin } from '../../DigitalTwinContext'
import { bundleRecord, relationshipRecord } from '../twin-entity-mappers'
import type { TwinRouteProps } from '../twin-experience-types'
import { TwinEmpty, TwinPanel, TwinRelationship, TwinRouteMasthead, TwinSafetyBanner, TwinStat, TwinStatus, TwinTag, twinExperienceStyles } from '../TwinExperiencePrimitives'

export default function BundlesCombinationsExperience({ openEditor }: TwinRouteProps) {
  const { twin } = useDigitalTwin()
  const activeRelations = twin.offerRelationships.filter((item) => item.active)
  const protectedBundles = twin.bundles.filter((item) => typeof item.protectedMarginPct === 'number')
  const prohibited = twin.offerRelationships.filter((item) => item.relationshipType === 'prohibited')
  const offerName = (code: string) => twin.offers.find((item) => item.code === code)?.commercialName || code

  return <div className={`${twinExperienceStyles.routeShell} space-y-5`} data-twin-route-id="MZ25-TWIN-BUNDLES-COMBINATIONS">
    <TwinRouteMasthead eyebrow="Commercial packaging" title="Bundles & combinaisons" subtitle="Composer des propositions cohérentes sans confondre appartenance à un bundle, complémentarité, prérequis, montée en gamme ou relation interdite." concept="Commercial Packaging Studio" icon={PackagePlus} mode={twin.storageMode} freshness={twin.generatedAt} authority="Combinaisons gouvernées · marge protégée" primary={{ label: 'Nouveau bundle', onClick: () => openEditor('bundle') }} secondary={{ label: 'Voir les offres', href: '/revenue-command-os/digital-twin/offers-services' }}>
      <div className="grid grid-cols-3 gap-2"><TwinStat label="Bundles" value={twin.bundles.length} tone="violet"/><TwinStat label="Relations" value={activeRelations.length} tone="cyan"/><TwinStat label="Interdites" value={prohibited.length} tone={prohibited.length ? 'rose' : 'emerald'}/></div>
    </TwinRouteMasthead>

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><TwinStat label="Offres combinées" value={new Set(twin.bundles.flatMap((item) => item.offerCodes)).size} note="Codes uniques en bundle" tone="cyan"/><TwinStat label="Segments couverts" value={new Set(twin.bundles.flatMap((item) => item.segmentCodes)).size} note="Cibles consolidées" tone="blue"/><TwinStat label="Marges protégées" value={protectedBundles.length} note="Bundles avec seuil explicite" tone="emerald"/><TwinStat label="Relations actives" value={activeRelations.length} note="Liens de portefeuille" tone="violet"/></div>

    <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <section className="space-y-4">{twin.bundles.length ? twin.bundles.map((bundle) => <article key={bundle.code} className="rounded-[30px] border border-slate-200 bg-white p-5 shadow-[0_18px_50px_rgba(15,23,42,.055)]"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-600 text-white"><Boxes size={21}/></span><div><div className="flex flex-wrap items-center gap-2"><TwinStatus status={bundle.status}/><TwinTag tone="violet">{bundle.bundleType}</TwinTag></div><h2 className="mt-2 text-lg font-black text-slate-950">{bundle.name}</h2><p className="mt-1 text-[9px] font-black uppercase tracking-[.12em] text-slate-600">{bundle.code}</p></div></div><button onClick={() => openEditor('bundle', bundleRecord(bundle))} aria-label={`Modifier ${bundle.name}`} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 text-slate-700 hover:border-violet-300 hover:text-violet-800"><Edit3 size={16}/></button></div><div className="mt-4 rounded-[22px] bg-slate-950 p-4 text-white"><p className="text-[9px] font-black uppercase text-violet-200">Promesse commerciale</p><p className="mt-2 text-sm font-black leading-6 text-white">{bundle.commercialPromise}</p></div><div className="mt-4 grid gap-4 md:grid-cols-2"><div><p className="text-[9px] font-black uppercase text-slate-600">Offres composantes</p><div className="mt-2 flex flex-wrap gap-2">{bundle.offerCodes.map((code) => <TwinTag key={code} tone="cyan">{offerName(code)}</TwinTag>)}</div></div><div><p className="text-[9px] font-black uppercase text-slate-600">Segments</p><div className="mt-2 flex flex-wrap gap-2">{bundle.segmentCodes.map((code) => <TwinTag key={code} tone="blue">{code}</TwinTag>)}</div></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-emerald-50 p-3"><p className="text-[8px] font-black uppercase text-emerald-800">Marge protégée</p><p className="mt-1 text-lg font-black text-slate-950">{typeof bundle.protectedMarginPct === 'number' ? `${bundle.protectedMarginPct}%` : 'Non calculé'}</p></div><div className="rounded-2xl bg-slate-50 p-3"><p className="text-[8px] font-black uppercase text-slate-700">Logique tarifaire</p><p className="mt-1 text-[11px] font-semibold leading-5 text-slate-800">{bundle.pricingLogic || 'Indisponible'}</p></div></div></article>) : <TwinEmpty title="Aucun bundle" description="Le modèle ne contient encore aucune combinaison d’offres. Créez un bundle uniquement lorsqu’une promesse, une logique tarifaire et des offres composantes sont explicites."/>}</section>

      <div className="space-y-5"><TwinPanel eyebrow="Relationship logic" title="Relations entre offres" icon={GitBranch} tone="cyan" action={<button onClick={() => openEditor('offer-relationship')} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-3 py-2 text-[10px] font-black text-white"><Plus size={14}/> Relation</button>}><div className="space-y-3">{twin.offerRelationships.slice(0, 8).map((relationship) => <div key={relationship.code} className="rounded-[22px] border border-slate-200 bg-white p-3"><button onClick={() => openEditor('offer-relationship', relationshipRecord(relationship))} className="w-full text-left"><TwinRelationship source={offerName(relationship.sourceOfferCode)} target={offerName(relationship.targetOfferCode)} label={relationship.relationshipType}/><p className="mt-2 text-[10px] font-semibold leading-5 text-slate-700">{relationship.rationale}</p></button></div>)}</div></TwinPanel><TwinPanel eyebrow="Protection" title="Règles de composition" icon={ShieldCheck} tone="emerald"><div className="space-y-3"><div className="rounded-[20px] border border-emerald-200 bg-emerald-50 p-4"><p className="text-sm font-black text-slate-950">La marge ne doit pas être déduite</p><p className="mt-1 text-[11px] font-semibold leading-5 text-slate-700">Une marge absente reste “Non calculé”; elle n’est jamais remplacée par zéro.</p></div><div className="rounded-[20px] border border-rose-200 bg-rose-50 p-4"><p className="text-sm font-black text-slate-950">{prohibited.length} relation(s) interdite(s)</p><p className="mt-1 text-[11px] font-semibold leading-5 text-slate-700">Les incompatibilités restent visibles et ne sont jamais présentées comme opportunités.</p></div></div></TwinPanel></div>
    </div>
    <TwinSafetyBanner detail="La composition d’un bundle modélise une proposition; elle ne crée ni prix, ni devis, ni engagement client."/>
  </div>
}
