'use client'

import { ArrowRight, Edit3, RadioTower, Route, ShieldCheck, Workflow } from 'lucide-react'
import { useDigitalTwin } from '../../DigitalTwinContext'
import { channelRecord, journeyRecord } from '../twin-entity-mappers'
import type { TwinRouteProps } from '../twin-experience-types'
import { TwinEmpty, TwinPanel, TwinRouteMasthead, TwinSafetyBanner, TwinStat, TwinStatus, TwinTag, twinExperienceStyles } from '../TwinExperiencePrimitives'

export default function ChannelsJourneysExperience({ openEditor }: TwinRouteProps) {
  const { twin } = useDigitalTwin()
  const activeChannels = twin.channels.filter((item) => item.status === 'active')
  const activeJourneys = twin.journeys.filter((item) => item.status === 'active')
  const stageCount = twin.journeys.reduce((sum, item) => sum + item.stages.length, 0)

  return <div className={`${twinExperienceStyles.routeShell} space-y-5`} data-twin-route-id="MZ25-TWIN-CHANNELS-JOURNEYS">
    <TwinRouteMasthead eyebrow="Route-to-market" title="Canaux & parcours" subtitle="Séparer les canaux d’acquisition des parcours commerciaux, puis relier chaque étape, preuve, responsable, succès, échec et route de récupération." concept="Route-to-Market Journey Architecture" icon={Route} mode={twin.storageMode} freshness={twin.generatedAt} authority="Orchestration commerciale · effets externes verrouillés" primary={{ label: 'Nouveau canal', onClick: () => openEditor('channel') }} secondary={{ label: 'Segments', href: '/revenue-command-os/digital-twin/customer-segments' }}>
      <div className="grid grid-cols-3 gap-2"><TwinStat label="Canaux actifs" value={activeChannels.length} tone="cyan"/><TwinStat label="Parcours actifs" value={activeJourneys.length} tone="blue"/><TwinStat label="Étapes" value={stageCount} tone="violet"/></div>
    </TwinRouteMasthead>

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><TwinStat label="Canaux modélisés" value={twin.channels.length} note="Routes d’approche" tone="cyan"/><TwinStat label="Segments couverts" value={new Set(twin.channels.flatMap((item) => item.bestForSegments)).size} note="Adéquation déclarée" tone="blue"/><TwinStat label="Parcours structurés" value={twin.journeys.length} note="Séquences machine-readable" tone="violet"/><TwinStat label="Récupérations" value={twin.journeys.reduce((sum, journey) => sum + journey.stages.filter((stage) => Boolean(stage.recoveryRoute)).length, 0)} note="Routes d’échec documentées" tone="emerald"/></div>

    <div className="grid gap-5 xl:grid-cols-[.85fr_1.15fr]">
      <TwinPanel eyebrow="Channel registry" title="Canaux commerciaux" icon={RadioTower} tone="cyan" action={<button onClick={() => openEditor('channel')} className="rounded-xl bg-slate-950 px-3 py-2 text-[10px] font-black text-white">Ajouter</button>}>
        {twin.channels.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-1">{twin.channels.map((channel) => <article key={channel.code} className="rounded-[22px] border border-slate-200 bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><TwinStatus status={channel.status}/><TwinTag tone="cyan">{channel.channelType}</TwinTag></div><h3 className="mt-3 text-sm font-black text-slate-950">{channel.name}</h3><p className="mt-1 text-[9px] font-black uppercase text-slate-600">{channel.code}</p></div><button onClick={() => openEditor('channel', channelRecord(channel))} aria-label={`Modifier ${channel.name}`} className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200 bg-white text-slate-700"><Edit3 size={15}/></button></div><p className="mt-3 text-[10px] font-semibold leading-5 text-slate-700">{channel.governance}</p><div className="mt-3 flex flex-wrap gap-1.5">{channel.bestForStages.map((item)=><TwinTag key={item} tone="blue">{item}</TwinTag>)}</div><div className="mt-3 border-t border-slate-200 pt-3"><p className="text-[8px] font-black uppercase text-slate-600">Mesures</p><div className="mt-2 flex flex-wrap gap-1.5">{channel.measurement.map((item)=><TwinTag key={item} tone="slate">{item}</TwinTag>)}</div></div></article>)}</div> : <TwinEmpty title="Aucun canal" description="Aucun canal n’est modélisé. Ajoutez une route d’approche avec sa gouvernance, ses étapes adaptées et ses mesures réelles."/>}
      </TwinPanel>

      <TwinPanel eyebrow="Journey blueprints" title="Parcours de conversion" icon={Workflow} tone="violet" action={<button onClick={() => openEditor('journey')} className="rounded-xl bg-violet-600 px-3 py-2 text-[10px] font-black text-white">Nouveau parcours</button>}>
        {twin.journeys.length ? <div className="space-y-5">{twin.journeys.map((journey) => <article key={journey.code} className="rounded-[26px] border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><TwinStatus status={journey.status}/><TwinTag tone="violet">{journey.stages.length} étapes</TwinTag></div><h3 className="mt-3 text-base font-black text-slate-950">{journey.name}</h3><p className="mt-1 text-[10px] font-semibold leading-5 text-slate-700">{journey.objective}</p></div><button onClick={() => openEditor('journey', journeyRecord(journey))} aria-label={`Modifier ${journey.name}`} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 text-slate-700"><Edit3 size={16}/></button></div><div className="mt-5 overflow-x-auto pb-2"><div className="flex min-w-max items-stretch gap-2">{[...journey.stages].sort((a,b)=>a.order-b.order).map((stage,index)=><div key={stage.code} className="flex items-center gap-2"><div className="w-56 rounded-[22px] border border-slate-200 bg-slate-50 p-3"><div className="flex items-center justify-between"><span className="grid h-8 w-8 place-items-center rounded-xl bg-slate-950 text-[10px] font-black text-white">{stage.order}</span><TwinTag tone="cyan">{stage.maximumRecommendedDays} j max</TwinTag></div><p className="mt-3 text-xs font-black text-slate-950">{stage.name}</p><p className="mt-2 text-[9px] font-semibold leading-4 text-slate-700">Responsable · {stage.responsibleRole}</p><div className="mt-3 rounded-xl bg-emerald-50 p-2"><p className="text-[8px] font-black uppercase text-emerald-800">Succès</p><p className="mt-1 text-[9px] font-semibold text-slate-800">{stage.successEvent}</p></div><div className="mt-2 rounded-xl bg-rose-50 p-2"><p className="text-[8px] font-black uppercase text-rose-800">Récupération</p><p className="mt-1 text-[9px] font-semibold text-slate-800">{stage.recoveryRoute || 'Non documentée'}</p></div></div>{index<journey.stages.length-1?<ArrowRight className="shrink-0 text-violet-500" size={18}/>:null}</div>)}</div></div><div className="mt-4 flex flex-wrap gap-1.5">{journey.segmentCodes.map((code)=><TwinTag key={code} tone="blue">{code}</TwinTag>)}{journey.offerCodes.map((code)=><TwinTag key={code} tone="cyan">{code}</TwinTag>)}</div></article>)}</div> : <TwinEmpty title="Aucun parcours" description="Aucun parcours n’est modélisé. Ajoutez une séquence avec critères d’entrée, sortie, preuves, responsable et route de récupération."/>}
      </TwinPanel>
    </div>
    <TwinSafetyBanner detail="Les canaux et parcours décrivent une orchestration possible. Ils n’envoient aucun email, message, appel ou effet externe."/>
  </div>
}
