'use client'

import Link from 'next/link'
import { Edit3, Eye, ShieldCheck, Target, UserRoundCog, UsersRound } from 'lucide-react'
import { useDigitalTwin } from '../../DigitalTwinContext'
import { decisionMakerRecord } from '../twin-entity-mappers'
import type { TwinRouteProps } from '../twin-experience-types'
import { TwinEmpty, TwinPanel, TwinRouteMasthead, TwinSafetyBanner, TwinStat, TwinStatus, TwinTag, twinExperienceStyles } from '../TwinExperiencePrimitives'

export default function DecisionMakersExperience({ openEditor }: TwinRouteProps) {
  const { twin } = useDigitalTwin()
  const finalDeciders = twin.decisionMakers.filter((item) => item.authorityLevel === 'final-decider')
  const gatekeepers = twin.decisionMakers.filter((item) => item.authorityLevel === 'gatekeeper')
  const noEvidence = twin.decisionMakers.filter((item) => !item.requiredEvidence.length)

  return <div className={`${twinExperienceStyles.routeShell} space-y-5`} data-twin-route-id="MZ25-TWIN-DECISION-MAKERS">
    <TwinRouteMasthead eyebrow="Influence intelligence" title="Décideurs" subtitle="Modéliser les rôles d’autorité, leurs préoccupations, motivations, preuves attendues, objections et styles d’approche sans inventer de personnes ni de coordonnées." concept="Commercial Influence Directory" icon={UserRoundCog} mode={twin.storageMode} freshness={twin.generatedAt} authority="Profils de rôle · aucune identité personnelle" primary={{ label: 'Nouveau profil', onClick: () => openEditor('decision-maker') }} secondary={{ label: 'Segments clients', href: '/revenue-command-os/digital-twin/customer-segments' }}>
      <div className="grid grid-cols-3 gap-2"><TwinStat label="Profils" value={twin.decisionMakers.length} tone="violet"/><TwinStat label="Décideurs finaux" value={finalDeciders.length} tone="rose"/><TwinStat label="Gatekeepers" value={gatekeepers.length} tone="amber"/></div>
    </TwinRouteMasthead>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><TwinStat label="Organisations couvertes" value={new Set(twin.decisionMakers.flatMap((item) => item.organizationTypes)).size} note="Typologies distinctes" tone="cyan"/><TwinStat label="Offres reliées" value={new Set(twin.decisionMakers.flatMap((item) => item.relevantOfferCodes)).size} note="Propositions pertinentes" tone="blue"/><TwinStat label="Preuves attendues" value={new Set(twin.decisionMakers.flatMap((item) => item.requiredEvidence)).size} note="Signaux de confiance" tone="emerald"/><TwinStat label="Profils sans preuve" value={noEvidence.length} note="Intelligence incomplète" tone={noEvidence.length ? 'amber' : 'emerald'}/></section>

    {twin.decisionMakers.length ? <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
      <section className="grid gap-4 lg:grid-cols-2">{twin.decisionMakers.map((profile) => <article key={profile.code} className="rounded-[30px] border border-slate-200 bg-white p-5 shadow-[0_18px_50px_rgba(15,23,42,.055)]"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-600 text-white"><UserRoundCog size={21}/></span><div><div className="flex flex-wrap items-center gap-2"><TwinStatus status={profile.status}/><TwinTag tone={profile.authorityLevel === 'final-decider' ? 'rose' : profile.authorityLevel === 'gatekeeper' ? 'amber' : 'violet'}>{profile.authorityLevel}</TwinTag></div><h2 className="mt-2 text-lg font-black text-slate-950">{profile.roleName}</h2><p className="mt-1 text-[9px] font-black uppercase tracking-[.12em] text-slate-600">{profile.code}</p></div></div><button onClick={() => openEditor('decision-maker', decisionMakerRecord(profile))} aria-label={`Modifier ${profile.roleName}`} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 text-slate-700 hover:border-violet-300 hover:text-violet-800"><Edit3 size={16}/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-rose-50 p-3"><p className="text-[8px] font-black uppercase text-rose-800">Préoccupations</p><div className="mt-2 space-y-1">{profile.primaryConcerns.slice(0,3).map((item)=><p key={item} className="text-[10px] font-semibold leading-4 text-slate-800">• {item}</p>)}</div></div><div className="rounded-2xl bg-emerald-50 p-3"><p className="text-[8px] font-black uppercase text-emerald-800">Motivations</p><div className="mt-2 space-y-1">{profile.motivations.slice(0,3).map((item)=><p key={item} className="text-[10px] font-semibold leading-4 text-slate-800">• {item}</p>)}</div></div></div><div className="mt-4 rounded-[22px] border border-blue-200 bg-blue-50 p-4"><p className="text-[9px] font-black uppercase text-blue-800">Stratégie de contact</p><p className="mt-2 text-[11px] font-semibold leading-5 text-slate-800">{profile.contactStrategy}</p></div><div className="mt-4 flex flex-wrap gap-2">{profile.organizationTypes.map((item)=><TwinTag key={item} tone="slate">{item}</TwinTag>)}{profile.relevantOfferCodes.slice(0,3).map((code)=><TwinTag key={code} tone="blue">{code}</TwinTag>)}</div></article>)}</section>
      <div className="space-y-5"><TwinPanel eyebrow="Evidence architecture" title="Preuves requises" icon={ShieldCheck} tone="emerald"><div className="space-y-3">{twin.decisionMakers.slice(0,6).map((profile)=><div key={profile.code} className="rounded-[20px] border border-slate-200 bg-slate-50 p-3"><p className="text-xs font-black text-slate-950">{profile.roleName}</p><div className="mt-2 flex flex-wrap gap-1.5">{profile.requiredEvidence.length ? profile.requiredEvidence.slice(0,5).map((item)=><TwinTag key={item} tone="emerald">{item}</TwinTag>) : <TwinTag tone="amber">Non documenté</TwinTag>}</div></div>)}</div></TwinPanel><TwinPanel eyebrow="Objection posture" title="Risques de décision" icon={Target} tone="amber"><div className="space-y-3">{twin.decisionMakers.slice(0,5).map((profile)=><div key={profile.code} className="rounded-[20px] border border-amber-200 bg-amber-50 p-3"><p className="text-xs font-black text-slate-950">{profile.roleName}</p><p className="mt-1 text-[10px] font-semibold leading-5 text-slate-700">{profile.objections[0] || 'Objection non documentée'}</p><p className="mt-2 text-[9px] font-black uppercase text-amber-800">Style · {profile.preferredStyle}</p></div>)}</div></TwinPanel><Link href="/revenue-command-os/digital-twin/channels-journeys" className="flex items-center justify-between rounded-[26px] border border-cyan-200 bg-cyan-50 p-5 text-cyan-950"><div><p className="text-[9px] font-black uppercase">Parcours d’influence</p><p className="mt-1 text-sm font-black">Relier les rôles aux étapes</p></div><Eye size={22}/></Link></div>
    </div> : <TwinEmpty title="Aucun profil décideur" description="Le modèle est sain mais ne contient aucun rôle acheteur. Créez des profils de rôle uniquement, sans identité personnelle ni coordonnées inventées."/>}
    <TwinSafetyBanner detail="Cette page modélise des rôles acheteurs et leurs attentes; elle ne fabrique aucune personne, adresse ou donnée de contact."/>
  </div>
}
