import { NextRequest, NextResponse } from 'next/server'
import { getCurrentUser } from '@/lib/getUser'
import { normalizeRevenueOsError, RevenueOsError } from '@/lib/revenue-command-os/errors'
import { mutateRevenueDoctrine,persistKnowledgeValidation,queueKnowledgeIndexJob,readRevenueKnowledgeMemory,resolveKnowledgeConflict,updateKnowledgeValidationStatus } from '@/lib/revenue-command-os/knowledge-memory/repository'
import type { RevenueDoctrineMutationInput,RevenueKnowledgeConflictStatus,RevenueKnowledgeValidationIssue } from '@/lib/revenue-command-os/types'
export const dynamic='force-dynamic';export const runtime='nodejs'
function actor(user:any){return{id:String(user?.id||''),label:String(user?.name||user?.full_name||user?.email||'Direction Revenue')}}
function errorResponse(error:unknown){const e=normalizeRevenueOsError(error);return NextResponse.json({ok:false,error:{code:e.code,message:e.message,recoverable:e.recoverable}},{status:e.status})}
export async function GET(){try{const user=await getCurrentUser();if(!user)return NextResponse.json({ok:false,error:{code:'UNAUTHENTICATED',message:'Authentification requise.'}},{status:401});const{bootstrap,warnings}=await readRevenueKnowledgeMemory();return NextResponse.json({ok:true,data:bootstrap,warnings,mode:'live',advisoryOnly:true},{headers:{'Cache-Control':'no-store'}})}catch(error){return errorResponse(error)}}
export async function POST(request:NextRequest){try{const user=await getCurrentUser();if(!user)return NextResponse.json({ok:false,error:{code:'UNAUTHENTICATED',message:'Authentification requise.'}},{status:401});const body=await request.json();const action=String(body?.action||'');
if(action==='mutate_doctrine'){const payload=body?.payload||{};const input:RevenueDoctrineMutationInput={operation:payload.operation,id:typeof payload.id==='string'?payload.id:undefined,payload:payload.data&&typeof payload.data==='object'?{...payload.data,requiredApprovals:[],prohibitedActions:[],advisoryOnly:true}: {advisoryOnly:true}};const data=await mutateRevenueDoctrine(input,actor(user));return NextResponse.json({ok:true,data,mode:'live'},{status:input.operation==='create'?201:200})}
if(action==='decide_approval'){const id=String(body?.payload?.id||'');if(!id)throw new RevenueOsError('REVENUE_KNOWLEDGE_INVALID_INPUT','Doctrine requise.',{status:400});const data=await mutateRevenueDoctrine({operation:'activate',id,payload:{advisoryOnly:true,requiredApprovals:[],prohibitedActions:[]}},actor(user));return NextResponse.json({ok:true,data,mode:'live',legacyAction:'decide_approval',effectiveAction:'activate'})}
if(action==='resolve_conflict'){const id=String(body?.payload?.id||'');const status=body?.payload?.status as RevenueKnowledgeConflictStatus;const resolution=String(body?.payload?.resolution||'');if(!id)throw new RevenueOsError('REVENUE_KNOWLEDGE_INVALID_INPUT','Conflit requis.',{status:400});return NextResponse.json({ok:true,data:await resolveKnowledgeConflict(id,status,resolution,actor(user)),mode:'live'})}
if(action==='queue_index'){const assetId=String(body?.payload?.assetId||'');if(!assetId)throw new RevenueOsError('REVENUE_KNOWLEDGE_INVALID_INPUT','Actif requis.',{status:400});return NextResponse.json({ok:true,data:await queueKnowledgeIndexJob(assetId,actor(user)),mode:'live'},{status:201})}
if(action==='run_validation')return NextResponse.json({ok:true,data:await persistKnowledgeValidation(actor(user)),mode:'live',blocking:false})
if(action==='update_validation_status'){const id=String(body?.payload?.id||'');const status=body?.payload?.status as RevenueKnowledgeValidationIssue['status'];if(!id)throw new RevenueOsError('REVENUE_KNOWLEDGE_INVALID_INPUT','Point de validation requis.',{status:400});return NextResponse.json({ok:true,data:await updateKnowledgeValidationStatus(id,status,actor(user)),mode:'live'})}
throw new RevenueOsError('REVENUE_KNOWLEDGE_ACTION_NOT_ALLOWED','Action Doctrine & mémoire non supportée.',{status:400})}catch(error){return errorResponse(error)}}
