'use client'

import Image from 'next/image'
import type { ReactNode } from 'react'
import { SERVICE_DOCUMENT_SECTION_LABELS, getServiceDocumentTemplate } from './templateRegistry'
import { paginateServiceDocument } from './previewLayout'
import type { ServiceDocumentSectionKey, ServiceDocumentSource, ServiceDocumentSettings } from './types'
import styles from './ServiceDocumentStudio.module.css'

const logoPath = '/b2b-plaquette-partenaires/assets/angelcare-original-logo.png'
const show = (value?: string | number | null) => value === undefined || value === null || value === '' ? 'Non renseigné' : String(value)
const money = (value?: number | null, currency = 'Dh') => value === null || value === undefined ? 'Sur devis' : `${new Intl.NumberFormat('fr-FR', { maximumFractionDigits: 2 }).format(value)} ${currency}`

function List({ values, empty = 'Aucune donnée enregistrée.' }: { values: string[]; empty?: string }) {
  return values.length ? <ul className="grid gap-1.5 text-[10px] font-semibold leading-4 text-slate-700">{values.map((value, index) => <li key={`${value}-${index}`} className="flex gap-2"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--doc-accent)]"/><span>{value}</span></li>)}</ul> : <p className="text-[10px] font-semibold italic text-slate-400">{empty}</p>
}

function Section({ sectionKey, source }: { sectionKey: ServiceDocumentSectionKey; source: ServiceDocumentSource }) {
  const title = SERVICE_DOCUMENT_SECTION_LABELS[sectionKey]
  const wrap = (children: ReactNode) => <section className={`${styles.section} p-3.5`}><h3 className={`${styles.sectionTitle} mb-3 pl-2 text-[11px] font-black uppercase tracking-[.12em]`}>{title}</h3>{children}</section>
  if (sectionKey === 'executive_summary') return wrap(<p className="text-[11px] font-semibold leading-5 text-slate-700">{source.executiveSummary || source.promise || 'Synthèse à compléter depuis la source réelle.'}</p>)
  if (sectionKey === 'identity') return wrap(<div className={styles.metaGrid}>{[['Référence', source.reference || source.code], ['Version', source.version], ['Statut', source.status], ['Catégorie', source.category], ['Univers', source.universe], ['Période', [source.dateFrom, source.dateTo].filter(Boolean).join(' — ')], ['Responsable', source.owner], ['Validation', source.approver]].map(([label, value]) => <div key={label} className="rounded-lg bg-slate-50 p-2"><p className="text-[8px] font-black uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-1 text-[10px] font-black text-slate-800">{show(value)}</p></div>)}</div>)
  if (sectionKey === 'customer_beneficiary') return wrap(<div className="grid grid-cols-2 gap-3"><div className="rounded-lg bg-slate-50 p-3"><p className="text-[8px] font-black uppercase tracking-[.12em] text-slate-400">Client</p><p className="mt-1 text-xs font-black">{show(source.customerName)}</p><p className="mt-1 text-[9px] font-semibold text-slate-500">{show(source.customerType)} · {show(source.location)}</p></div><div className="rounded-lg bg-slate-50 p-3"><p className="text-[8px] font-black uppercase tracking-[.12em] text-slate-400">Bénéficiaire</p><p className="mt-1 text-xs font-black">{show(source.beneficiaryName)}</p><p className="mt-1 text-[9px] font-semibold text-slate-500">{show(source.beneficiaryProfile)}</p></div></div>)
  if (sectionKey === 'objectives_outcomes') return wrap(<div className="grid grid-cols-3 gap-3"><div><p className="mb-2 text-[8px] font-black uppercase tracking-[.12em] text-slate-400">Objectifs</p><List values={source.objectives}/></div><div><p className="mb-2 text-[8px] font-black uppercase tracking-[.12em] text-slate-400">Résultats</p><List values={source.outcomes}/></div><div><p className="mb-2 text-[8px] font-black uppercase tracking-[.12em] text-slate-400">Enjeux</p><List values={source.painPoints}/></div></div>)
  if (sectionKey === 'timeline') return wrap(<div>{source.days.length ? source.days.map((day, dayIndex) => <div key={day.id || `${day.date}-${dayIndex}`} className="mb-4 last:mb-0"><div className="flex items-center justify-between rounded-lg bg-[var(--doc-soft)] px-3 py-2"><div><p className="text-[9px] font-black uppercase tracking-[.12em] text-[var(--doc-accent)]">{day.label || `Jour ${dayIndex + 1}`}</p><p className="text-[10px] font-bold text-slate-700">{show(day.date)} · {show(day.objective)}</p></div><p className="text-[10px] font-black">{show(day.start)} — {show(day.end)}</p></div>{day.blocks.map((block, index) => <div key={block.id || `${block.title}-${index}`} className={styles.timelineRow}><p className="text-[9px] font-black text-[var(--doc-accent)]">{show(block.start)}</p><div><p className="text-[10px] font-black text-slate-800">{block.title}</p><p className="text-[9px] font-semibold text-slate-500">{block.detail || block.activityCode || 'Bloc structuré'}</p></div><p className="text-right text-[8px] font-black uppercase text-slate-400">{show(block.end)}</p></div>)}</div>) : <p className="text-[10px] font-semibold italic text-slate-400">Aucun bloc horaire résolu. Le PDF ne fabriquera pas de timeline.</p>}</div>)
  if (sectionKey === 'multi_day_progression') return wrap(<div className="grid grid-cols-2 gap-2">{source.days.length ? source.days.map((day, index) => <div key={day.id || index} className="rounded-lg border border-slate-200 p-2.5"><p className="text-[9px] font-black text-[var(--doc-accent)]">{day.label || `Jour ${index + 1}`}</p><p className="mt-1 text-[9px] font-semibold text-slate-600">{day.phase || day.objective || show(day.date)}</p></div>) : <p className="col-span-2 text-[10px] italic text-slate-400">Aucune progression multi-jours disponible.</p>}</div>)
  if (sectionKey === 'activities_materials') return wrap(<div className="grid grid-cols-2 gap-4"><div><p className="mb-2 text-[8px] font-black uppercase text-slate-400">Activités</p><List values={source.activities}/></div><div><p className="mb-2 text-[8px] font-black uppercase text-slate-400">Matériels</p><List values={source.materials}/></div></div>)
  if (sectionKey === 'staffing_competencies') return wrap(<div className="grid grid-cols-2 gap-4"><div><p className="mb-2 text-[8px] font-black uppercase text-slate-400">Staffing</p><List values={source.staffing}/></div><div><p className="mb-2 text-[8px] font-black uppercase text-slate-400">Compétences</p><List values={source.competencies}/></div></div>)
  if (sectionKey === 'safety_risks') return wrap(<div className="grid grid-cols-2 gap-4"><div><p className="mb-2 text-[8px] font-black uppercase text-slate-400">Contrôles</p><List values={source.safeguards}/></div><div><p className="mb-2 text-[8px] font-black uppercase text-slate-400">Risques</p><List values={source.risks}/></div></div>)
  if (sectionKey === 'checklists_reporting') return wrap(<div className="grid grid-cols-2 gap-4"><div><p className="mb-2 text-[8px] font-black uppercase text-slate-400">Checklists</p><List values={source.checklists}/></div><div><p className="mb-2 text-[8px] font-black uppercase text-slate-400">Reporting</p><List values={source.reporting}/></div></div>)
  if (sectionKey === 'route_transport') return wrap(<List values={source.routes} empty="Aucun parcours ou transport enregistré."/>)
  if (sectionKey === 'commercial_package') return wrap(<div className="grid grid-cols-2 gap-4"><div><p className="mb-2 text-[8px] font-black uppercase text-slate-400">Promesse client</p><p className="text-[11px] font-semibold leading-5 text-slate-700">{source.promise || 'Non renseignée'}</p></div><div><p className="mb-2 text-[8px] font-black uppercase text-slate-400">Routines & options</p><List values={source.routines}/></div></div>)
  if (sectionKey === 'pricing_economics') return wrap(<div><div className="grid gap-1">{source.priceLines.length ? source.priceLines.map((line, index) => <div key={line.id || index} className="grid grid-cols-[1fr_65px_85px_90px] gap-2 border-b border-slate-100 py-1.5 text-[9px]"><span className="font-bold">{line.label}</span><span className="text-right">{line.quantity ?? 1}</span><span className="text-right">{money(line.unitPrice, source.currency)}</span><span className="text-right font-black">{money(line.total, source.currency)}</span></div>) : <p className="text-[10px] italic text-slate-400">Aucune ligne tarifaire résolue.</p>}</div><div className="mt-3 ml-auto grid max-w-[280px] gap-1 rounded-lg bg-slate-950 p-3 text-white"><div className="flex justify-between text-[9px]"><span>Total client</span><strong>{money(source.total, source.currency)}</strong></div><div className="flex justify-between text-[9px]"><span>Coût</span><strong>{money(source.cost, source.currency)}</strong></div><div className="flex justify-between text-[9px]"><span>Marge</span><strong>{source.margin == null ? 'Non renseignée' : `${source.margin}%`}</strong></div></div></div>)
  if (sectionKey === 'deployment_sites') return wrap(<div className="grid gap-2">{source.sites.length ? source.sites.map((site, index) => <div key={site.id || index} className="grid grid-cols-[1fr_90px_80px_110px] gap-2 rounded-lg bg-slate-50 p-2 text-[9px]"><strong>{site.name}</strong><span>{show(site.city)}</span><span>{site.beneficiaries ?? '—'} bénéfic.</span><span>{show(site.serviceWindow)}</span></div>) : <p className="text-[10px] italic text-slate-400">Aucun site enregistré.</p>}</div>)
  if (sectionKey === 'quality_readiness') return wrap(<div className={styles.metricGrid}>{source.metrics.length ? source.metrics.map((metric, index) => <div key={`${metric.label}-${index}`} className="rounded-lg bg-slate-50 p-2"><p className="text-[8px] font-black uppercase text-slate-400">{metric.label}</p><p className="mt-1 text-lg font-black text-slate-900">{metric.value}</p><p className="text-[8px] font-semibold text-slate-500">{metric.detail}</p></div>) : <p className="col-span-3 text-[10px] italic text-slate-400">Aucun indicateur probant disponible.</p>}</div>)
  if (sectionKey === 'lineage_approvals') return wrap(<div className="grid grid-cols-2 gap-4"><div><p className="mb-2 text-[8px] font-black uppercase text-slate-400">Lignage</p>{source.lineage.length ? source.lineage.map((item, index) => <div key={`${item.label}-${index}`} className="flex justify-between gap-4 border-b border-slate-100 py-1.5 text-[9px]"><span className="font-semibold text-slate-500">{item.label}</span><strong>{item.value}</strong></div>) : <p className="text-[10px] italic text-slate-400">Aucun lignage disponible.</p>}</div><div><p className="mb-2 text-[8px] font-black uppercase text-slate-400">Validations</p>{source.approvals.length ? source.approvals.map((item, index) => <div key={index} className="mb-2 rounded-lg border border-slate-200 p-2 text-[9px]"><strong>{show(item.authority)}</strong><p>{show(item.decision)} · {show(item.date)}</p></div>) : <p className="text-[10px] italic text-slate-400">Aucune validation enregistrée.</p>}</div></div>)
  return wrap(<List values={source.notes}/>)
}

export function DocumentPreview({ source, settings, zoom = 0.72, activePage = 0 }: { source: ServiceDocumentSource; settings: ServiceDocumentSettings; zoom?: number; activePage?: number }) {
  const template = getServiceDocumentTemplate(settings.templateId)
  const pages = paginateServiceDocument(source, settings)
  return <div className={`${styles.previewViewport} rounded-[30px] border border-slate-200 p-5`}><div className={styles.printRoot}>{pages.map((page) => <article key={page.index} className={`${styles.page} ${settings.orientation === 'portrait' ? styles.pagePortrait : styles.pageLandscape} ${page.index !== activePage ? styles.pageInactive : ''}`} style={{ transform: `scale(${zoom})`, marginBottom: `${-(1 - zoom) * (settings.orientation === 'portrait' ? 1120 : 790)}px`, ['--doc-accent' as string]: template.accent, ['--doc-soft' as string]: template.accentSoft }}><header className={`${styles.pageHeader} flex items-start justify-between gap-6 px-[12mm] pb-3 pt-[10mm]`}><div className="flex items-center gap-4">{settings.showLogo ? <Image src={logoPath} alt="ANGELCARE" width={154} height={48} className={`${styles.logo} h-10 w-auto`}/> : null}<div><p className="text-[8px] font-black uppercase tracking-[.22em] text-[var(--doc-accent)]">ANGELCARE · SERVICE DESIGN OS</p><h1 className="mt-1 text-[18px] font-black tracking-[-.035em] text-slate-950">{settings.documentTitle || source.title}</h1><p className="mt-1 text-[9px] font-semibold text-slate-500">{template.name} · {template.code}</p></div></div><div className="text-right"><span className="inline-flex rounded-full px-3 py-1 text-[8px] font-black uppercase tracking-[.13em] text-white" style={{ background: template.accent }}>{settings.confidentiality}</span><p className="mt-2 text-[9px] font-bold text-slate-500">Réf. {settings.documentReference || source.reference || source.code || source.sourceId || 'À attribuer'}</p></div></header><main className="grid gap-3 px-[12mm] pb-[26mm] pt-4">{page.blocks.map((block) => <Section key={`${page.index}-${block.key}`} sectionKey={block.key} source={source}/>)}</main><footer className={`${styles.footer} flex items-end justify-between gap-6 text-[7px] font-semibold leading-3 text-slate-500`}><div>{settings.showLegalFooter ? <><p className="font-black text-slate-700">ANGELCARE UNITÉ D’AFFAIRE ARTAB S.A.R.L (A.U)</p><p>www.angelcarehub.com · backoffice@angelcarehub.com · +212 537 581 462</p></> : null}{settings.showSourceReferences ? <p>Source: {source.sourceKind} · {source.sourceId || source.code || 'non résolue'} · Version {source.version || '—'}</p> : null}</div><div className="text-right"><p>{settings.confidentiality.toUpperCase()} · {settings.audience.toUpperCase()}</p><p>Page {page.index + 1} / {pages.length}</p></div></footer></article>)}</div></div>
}
