'use client'
import {useState} from 'react'
import type {OperatingApproval,OperatingCaseStatus,OperatingEvidence,OperatingException,OperatingRecoveryAction} from '../types'
import styles from '../admin-operating.module.css'

type ApiEnvelope<T>={data?:T;error?:{message?:string}}
async function post<T>(url:string,body:Record<string,unknown>):Promise<T>{const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({})) as ApiEnvelope<T>;if(!response.ok)throw new Error(payload.error?.message||'Action impossible.');return payload.data as T}

function DecisionRow({label,onDecision,options}:{label:string;onDecision:(decision:string,reason:string)=>Promise<unknown>;options:Array<{value:string;label:string}>}){const[reason,setReason]=useState('');const[decision,setDecision]=useState(options[0]?.value||'');const[busy,setBusy]=useState(false);const[error,setError]=useState('');async function run(){if(!reason.trim()||!decision)return;setBusy(true);setError('');try{await onDecision(decision,reason);window.location.reload()}catch(e){setError(e instanceof Error?e.message:'Action impossible.')}finally{setBusy(false)}}return <div className={styles.form}><strong>{label}</strong><select className={styles.select} value={decision} onChange={e=>setDecision(e.target.value)}>{options.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select><textarea className={styles.textarea} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Raison / conclusion obligatoire"/><button className={styles.secondary} disabled={busy||!reason.trim()} onClick={()=>void run()}>{busy?'Exécution…':'Décider et auditer'}</button>{error?<div className={styles.error}>{error}</div>:null}</div>}

export function OperatingDossierActions({caseId,currentStatus,activeExceptionId,evidence,approvals,exceptions,recoveries}:{caseId:string;currentStatus:OperatingCaseStatus;activeExceptionId:string|null;evidence:OperatingEvidence[];approvals:OperatingApproval[];exceptions:OperatingException[];recoveries:OperatingRecoveryAction[]}){
 const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[success,setSuccess]=useState<string|null>(null)
 const[reason,setReason]=useState('');const[nextStatus,setNextStatus]=useState<OperatingCaseStatus>(currentStatus==='blocked'?'recovery':'in_progress')
 const[evidenceTitle,setEvidenceTitle]=useState('');const[evidenceType,setEvidenceType]=useState('execution_proof');const[evidenceReference,setEvidenceReference]=useState('')
 const[exceptionSummary,setExceptionSummary]=useState('');const[comment,setComment]=useState('')
 const[assigneeId,setAssigneeId]=useState('');const[roleLabel,setRoleLabel]=useState('');const[dueAt,setDueAt]=useState('')
 const[approvalKey,setApprovalKey]=useState('operational_signoff');const[requiredRole,setRequiredRole]=useState('')
 const[recoveryType,setRecoveryType]=useState('retry');const[recoveryTitle,setRecoveryTitle]=useState('');const[recoveryOutcome,setRecoveryOutcome]=useState('')
 async function run(label:string,work:()=>Promise<unknown>){setBusy(true);setError(null);setSuccess(null);try{await work();setSuccess(`${label} enregistré.`);window.location.reload()}catch(e){setError(e instanceof Error?e.message:'Action impossible.')}finally{setBusy(false)}}
 const reviewableEvidence=evidence.filter(e=>['submitted','under_review'].includes(e.validation_status))
 const pendingApprovals=approvals.filter(a=>a.status==='pending')
 const openExceptions=exceptions.filter(e=>!['closed','cancelled'].includes(e.status))
 return <div className={styles.shell}>
  <section className={styles.panel}><header className={styles.panelHeader}><div><span className={styles.kicker}>OWNERSHIP</span><h2>Affectation & SLA</h2></div></header><div className={styles.panelBody}><div className={styles.form}><input className={styles.input} value={assigneeId} onChange={e=>setAssigneeId(e.target.value)} placeholder="UUID assignee"/><input className={styles.input} value={roleLabel} onChange={e=>setRoleLabel(e.target.value)} placeholder="Rôle / responsabilité"/><input className={styles.input} type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/><textarea className={styles.textarea} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Raison de l’affectation"/><button className={styles.button} disabled={busy||!assigneeId.trim()||!reason.trim()} onClick={()=>void run('Affectation',()=>post(`/api/angelcare-marketplace/admin/operating/cases/${caseId}/assignments`,{assigneeType:'user',assigneeId,roleLabel:roleLabel||null,reason,dueAt:dueAt||null}))}>Affecter / réaffecter</button></div></div></section>
  <section className={styles.panel}><header className={styles.panelHeader}><div><span className={styles.kicker}>COMMAND AUTHORITY</span><h2>État du dossier</h2></div></header><div className={styles.panelBody}><div className={styles.form}><select className={styles.select} value={nextStatus} onChange={e=>setNextStatus(e.target.value as OperatingCaseStatus)}><option value="intake">Intake</option><option value="validation">Validation</option><option value="qualified">Qualified</option><option value="ready">Ready</option><option value="in_progress">In progress</option><option value="evidence_pending">Evidence pending</option><option value="approval_pending">Approval pending</option><option value="blocked">Blocked</option><option value="recovery">Recovery</option><option value="reconciled">Reconciled</option><option value="closed">Closed</option><option value="cancelled">Cancelled</option></select><textarea className={styles.textarea} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Raison obligatoire de la transition"/><button className={styles.button} disabled={busy||!reason.trim()} onClick={()=>void run('Transition',()=>post(`/api/angelcare-marketplace/admin/operating/cases/${caseId}/transition`,{nextStatus,reason}))}>Appliquer transition</button></div></div></section>
  <section className={styles.panel}><header className={styles.panelHeader}><h2>Soumettre une preuve</h2></header><div className={styles.panelBody}><div className={styles.form}><input className={styles.input} value={evidenceTitle} onChange={e=>setEvidenceTitle(e.target.value)} placeholder="Titre de la preuve"/><input className={styles.input} value={evidenceType} onChange={e=>setEvidenceType(e.target.value)} placeholder="Type de preuve"/><input className={styles.input} value={evidenceReference} onChange={e=>setEvidenceReference(e.target.value)} placeholder="Référence / URL / stockage"/><button className={styles.button} disabled={busy||!evidenceTitle.trim()} onClick={()=>void run('Preuve',()=>post(`/api/angelcare-marketplace/admin/operating/cases/${caseId}/evidence`,{title:evidenceTitle,evidenceType,sourceType:'manual',sourceReference:evidenceReference||null,metadata:{captured_from:'operating_dossier'}}))}>Enregistrer preuve</button></div></div></section>
  {reviewableEvidence.length?<section className={styles.panel}><header className={styles.panelHeader}><h2>Revue des preuves</h2></header><div className={styles.panelBody}>{reviewableEvidence.map(e=><DecisionRow key={e.id} label={`${e.title} · ${e.validation_status}`} options={[{value:'validated',label:'Valider'},{value:'rejected',label:'Rejeter'}]} onDecision={(decision,reviewReason)=>post(`/api/angelcare-marketplace/admin/operating/evidence/${e.id}/review`,{decision,reason:reviewReason})}/>)}</div></section>:null}
  <section className={styles.panel}><header className={styles.panelHeader}><h2>Demander une approbation</h2></header><div className={styles.panelBody}><div className={styles.form}><input className={styles.input} value={approvalKey} onChange={e=>setApprovalKey(e.target.value)} placeholder="Clé d’approbation"/><input className={styles.input} value={requiredRole} onChange={e=>setRequiredRole(e.target.value)} placeholder="Rôle requis (optionnel)"/><button className={styles.button} disabled={busy||!approvalKey.trim()} onClick={()=>void run('Approbation demandée',()=>post(`/api/angelcare-marketplace/admin/operating/cases/${caseId}/approvals`,{approvalKey,requiredRole:requiredRole||null,evidenceIds:evidence.filter(e=>e.validation_status==='validated').map(e=>e.id),metadata:{requested_from:'operating_dossier'}}))}>Créer gate d’approbation</button></div></div></section>
  {pendingApprovals.length?<section className={styles.panel}><header className={styles.panelHeader}><h2>Décisions d’approbation</h2></header><div className={styles.panelBody}>{pendingApprovals.map(a=><DecisionRow key={a.id} label={`${a.approval_key} · v${a.version}`} options={[{value:'approved',label:'Approuver'},{value:'returned_for_rework',label:'Retour rework'},{value:'rejected',label:'Rejeter'},{value:'cancelled',label:'Annuler'}]} onDecision={(decision,decisionReason)=>post(`/api/angelcare-marketplace/admin/operating/approvals/${a.id}/decision`,{decision,reason:decisionReason})}/>)}</div></section>:null}
  <section className={styles.panel}><header className={styles.panelHeader}><h2>Ouvrir une exception</h2></header><div className={styles.panelBody}><div className={styles.form}><textarea className={styles.textarea} value={exceptionSummary} onChange={e=>setExceptionSummary(e.target.value)} placeholder="Décrire le blocker, risque ou écart"/><button className={`${styles.button} ${styles.danger}`} disabled={busy||!exceptionSummary.trim()} onClick={()=>void run('Exception',()=>post(`/api/angelcare-marketplace/admin/operating/cases/${caseId}/exceptions`,{exceptionType:'operational_blocker',severity:'high',summary:exceptionSummary,nextAction:'Triage et plan d’action'}))}>Ouvrir exception</button>{activeExceptionId?<button className={styles.secondary} disabled={busy} onClick={()=>void run('Exception résolue',()=>post(`/api/angelcare-marketplace/admin/operating/exceptions/${activeExceptionId}/transition`,{nextStatus:'resolved',reason:reason||'Résolution opérateur'}))}>Marquer exception résolue</button>:null}</div></div></section>
  {openExceptions.length||currentStatus==='recovery'?<section className={styles.panel}><header className={styles.panelHeader}><h2>Recovery / action compensatoire</h2></header><div className={styles.panelBody}><div className={styles.form}><select className={styles.select} value={recoveryType} onChange={e=>setRecoveryType(e.target.value)}><option value="retry">Retry</option><option value="reassign">Réaffecter</option><option value="rollback">Rollback</option><option value="reconcile">Réconcilier</option><option value="compensating_action">Action compensatoire</option><option value="manual_override">Override gouverné</option></select><input className={styles.input} value={recoveryTitle} onChange={e=>setRecoveryTitle(e.target.value)} placeholder="Titre recovery"/><textarea className={styles.textarea} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Raison recovery"/><textarea className={styles.textarea} value={recoveryOutcome} onChange={e=>setRecoveryOutcome(e.target.value)} placeholder="Outcome si déjà exécuté"/><button className={styles.button} disabled={busy||!recoveryTitle.trim()||!reason.trim()} onClick={()=>void run('Recovery',()=>post(`/api/angelcare-marketplace/admin/operating/cases/${caseId}/recovery`,{exceptionId:openExceptions[0]?.id||null,actionType:recoveryType,title:recoveryTitle,reason,status:recoveryOutcome.trim()?'completed':'planned',outcome:recoveryOutcome||null,idempotencyKey:crypto.randomUUID()}))}>Enregistrer recovery</button><small>{recoveries.length} action(s) recovery déjà tracées.</small></div></div></section>:null}
  <section className={styles.panel}><header className={styles.panelHeader}><h2>Note opérateur</h2></header><div className={styles.panelBody}><div className={styles.form}><textarea className={styles.textarea} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Note interne durable"/><button className={styles.secondary} disabled={busy||!comment.trim()} onClick={()=>void run('Note',()=>post(`/api/angelcare-marketplace/admin/operating/cases/${caseId}/comments`,{body:comment,visibility:'internal'}))}>Ajouter note</button></div></div></section>
  {error?<div className={styles.error}>{error}</div>:null}{success?<div className={styles.success}>{success}</div>:null}
 </div>
}
