'use client'
import Link from 'next/link'
import { BellRing, Check, Mail, MessageCircleMore, Smartphone } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { CatalogLocale } from '../../catalog-discovery/types'
import type { JourneyNotification, MarketplaceJourney } from '../../journey-control/types'
import { CustomerPortalNavigation } from './CustomerPortalNavigation'
import styles from '../customer-commerce.module.css'

type Row={notification:JourneyNotification;journey:MarketplaceJourney}
const iconFor=(channel:JourneyNotification['channel'])=>channel==='email'?<Mail/>:channel==='whatsapp'?<MessageCircleMore/>:channel==='sms'?<Smartphone/>:<BellRing/>
export function CustomerNotificationsWorkspace({journeys,locale}:{journeys:MarketplaceJourney[];locale:CatalogLocale}){
  const source=useMemo<Row[]>(()=>journeys.flatMap(j=>j.notifications.map(notification=>({notification,journey:j}))).sort((a,b)=>b.notification.scheduled_at.localeCompare(a.notification.scheduled_at)),[journeys])
  const[ack,setAck]=useState<string[]>([]);const[showUnread,setShowUnread]=useState(false);const[busy,setBusy]=useState<string|null>(null)
  const isUnread=(n:JourneyNotification)=>n.status!=='acknowledged'&&!ack.includes(n.id)
  const visible=showUnread?source.filter(row=>isUnread(row.notification)):source
  async function acknowledge(id:string){setBusy(id);try{const response=await fetch(`/api/angelcare-marketplace/journeys/notifications/${id}/acknowledge`,{method:'POST'});if(response.ok)setAck(v=>[...v,id])}finally{setBusy(null)}}
  const unread=source.filter(row=>isUnread(row.notification)).length
  return <main className={styles.root} dir={locale==='ar'?'rtl':'ltr'}><div className={styles.portalShell}><section className={styles.utilityHero}><div><span className={styles.eyebrow}>NOTIFICATION CENTER</span><h1>{locale==='fr'?'Mes notifications':locale==='ar'?'إشعاراتي':'My Notifications'}</h1><p>{locale==='fr'?'Messages transactionnels et opérationnels réellement reliés à vos parcours.':locale==='ar'?'رسائل فعلية مرتبطة بمساراتك ومعاملاتك.':'Real transactional and operational messages connected to your journeys.'}</p></div><BellRing/></section><CustomerPortalNavigation locale={locale}/><section className={styles.notificationToolbar}><div><strong>{unread}</strong><span>{locale==='fr'?'non lue(s)':locale==='ar'?'غير مقروءة':'unread'}</span></div><button type="button" data-active={showUnread} onClick={()=>setShowUnread(v=>!v)}>{showUnread?(locale==='fr'?'Tout afficher':locale==='ar'?'عرض الكل':'Show all'):(locale==='fr'?'Non lues uniquement':locale==='ar'?'غير المقروء فقط':'Unread only')}</button></section><section className={styles.utilityPanel}>{visible.length?<div className={styles.notificationInbox}>{visible.map(({notification,journey})=>{const unreadNow=isUnread(notification);const target=notification.deep_link?.startsWith('/angelcare-marketplace/')?notification.deep_link:`/angelcare-marketplace/${locale}/account/journeys/${journey.id}`;return <article className={styles.notificationInboxRow} data-unread={unreadNow} key={`${journey.id}-${notification.id}`}><div className={styles.notificationChannel}>{iconFor(notification.channel)}</div><div><span>{notification.channel} · {new Date(notification.scheduled_at).toLocaleString(locale)}</span><h3>{notification.title}</h3><p>{notification.message}</p><small>{journey.title} · {journey.public_reference}</small></div><div className={styles.notificationActions}><Link href={target}>{locale==='fr'?'Ouvrir':locale==='ar'?'فتح':'Open'}</Link>{unreadNow?<button type="button" disabled={busy===notification.id} onClick={()=>void acknowledge(notification.id)}><Check/> {locale==='fr'?'Lu':locale==='ar'?'تمت القراءة':'Read'}</button>:<span>{locale==='fr'?'Lu':locale==='ar'?'مقروء':'Read'}</span>}</div></article>})}</div>:<div className={styles.emptyState}>{locale==='fr'?'Aucune notification dans cette vue.':locale==='ar'?'لا توجد إشعارات في هذا العرض.':'No notifications in this view.'}</div>}</section></div></main>
}
