'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { Sparkles, WalletCards } from 'lucide-react'
import type { CatalogLocale } from '../../catalog-discovery/types'
import type { WalletComparison } from '../types'
import styles from '../customer-commerce.module.css'
type Envelope<T>={data:T}
export function WalletBenefitTeaser({locale,normalPrice,itemId,categoryKey,schemaKey,territoryId}:{locale:CatalogLocale;normalPrice:number;itemId?:string|null;categoryKey?:string|null;schemaKey?:string|null;territoryId?:string|null}){const[data,setData]=useState<WalletComparison|null>(null);useEffect(()=>{if(!normalPrice)return;const controller=new AbortController();fetch('/api/angelcare-marketplace/wallet/comparison',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({normalPrice,itemId,categoryKey,schemaKey,territoryId}),signal:controller.signal}).then((r)=>r.json()).then((p:Envelope<WalletComparison>)=>setData(p.data)).catch(()=>null);return()=>controller.abort()},[normalPrice,itemId,categoryKey,schemaKey,territoryId]);if(!normalPrice)return null;return <section className={styles.walletTeaser} data-loading={!data}><div className={styles.walletTeaserIcon}><WalletCards/></div><div><b>{locale==='fr'?'Votre avantage AC Privilege Wallet':locale==='ar'?'ميزة محفظة AC المميزة':'Your AC Privilege Wallet advantage'}</b><p>{data?.eligible?(data.priorityLabel||data.reason):(locale==='fr'?'Activez le Wallet pour comparer les avantages disponibles.':locale==='ar'?'فعّل المحفظة لمقارنة المزايا المتاحة.':'Activate Wallet to compare available benefits.')}</p></div><strong>{data?.eligible?`−${data.immediateSaving.toLocaleString(locale)} Dh`:`${normalPrice.toLocaleString(locale)} Dh`}</strong><Link href={`/angelcare-marketplace/${locale}/account/wallet`}>{data?.walletBalance?(locale==='fr'?'Voir mon Wallet':locale==='ar'?'عرض المحفظة':'View Wallet'):(locale==='fr'?'Activer AC Wallet':locale==='ar'?'تفعيل محفظة AC':'Activate AC Wallet')} <Sparkles size={13}/></Link></section>}
