'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import type { Angelcare360AttendanceDayState, Angelcare360AttendanceRecordListRecord } from '@/types/angelcare360/attendance'
import styles from './PresenceZoneBFrame.module.css'
import { attendanceLabel, initials, timeFr } from './presence-ui'
import { ArrivalDetailDrawer, DayClosureChamber, DepartureDetailDrawer, EarlyDepartureDrawer, MissingCheckoutResolutionDrawer, StudentAttendanceQuickPeek, TonePill } from './PresenceCommandSurfaces'

type Lens='all'|'present'|'absent'|'late'|'left_early'|'missing'
export default function PresenceTodayCommand({ dayState, records }: { dayState:Angelcare360AttendanceDayState; records:Angelcare360AttendanceRecordListRecord[] }) {
 const [lens,setLens]=useState<Lens>('all'); const [selected,setSelected]=useState<Angelcare360AttendanceRecordListRecord|null>(null); const [surface,setSurface]=useState<'student'|'arrival'|'departure'|'early'|'missing'|null>(null); const [closure,setClosure]=useState(false)
 const closedSessions=new Set(dayState.sessions.filter((s)=>['closed','locked','completed'].includes(String(s.status).toLowerCase())).map((s)=>s.id))
 const missingCheckout=records.filter((r)=>closedSessions.has(r.attendance_session_id)&&['present','late'].includes(String(r.attendance_status))&&!r.check_out_at)
 const filtered=useMemo(()=>records.filter((r)=>{if(lens==='all')return true;if(lens==='missing')return missingCheckout.some((x)=>x.id===r.id);return r.attendance_status===lens}),[records,lens,missingCheckout.length])
 const open=(record:Angelcare360AttendanceRecordListRecord,what:typeof surface)=>{setSelected(record);setSurface(what)}
 return <div className={styles.page} data-zone-b-page="today">
  <section className={styles.crown}><div className={styles.crownTop}><div><h2 className={styles.crownTitle}>Journée en direct</h2><p className={styles.crownSub}>{dayState.activeSchoolName || 'Établissement'} · {dayState.selectedDate}. Arrivées, présence et départs dans un seul poste de travail.</p></div><div className={styles.contextPills}><span className={styles.pillBlue}>{dayState.totalCompletionRate}% complété</span><button className={styles.secondaryButton} onClick={()=>setClosure(true)}>Clôture journée</button></div></div>
  <div className={styles.metricGrid} style={{gridTemplateColumns:'repeat(6,minmax(120px,1fr))'}}><div className={styles.metric}><span className={styles.metricLabel}>Attendus</span><strong className={styles.metricValue}>{dayState.totalExpectedStudents}</strong></div><div className={styles.metric}><span className={styles.metricLabel}>Pointés</span><strong className={styles.metricValue}>{dayState.totalMarkedStudents}</strong></div><div className={styles.metric}><span className={styles.metricLabel}>Présents</span><strong className={styles.metricValue}>{records.filter(r=>r.attendance_status==='present').length}</strong></div><div className={styles.metric}><span className={styles.metricLabel}>Absents</span><strong className={styles.metricValue}>{records.filter(r=>r.attendance_status==='absent').length}</strong></div><div className={styles.metric}><span className={styles.metricLabel}>Retards</span><strong className={styles.metricValue}>{records.filter(r=>r.attendance_status==='late').length}</strong></div><div className={styles.metric}><span className={styles.metricLabel}>Départs à confirmer</span><strong className={styles.metricValue}>{missingCheckout.length}</strong></div></div></section>

  <section className={styles.panel}><div className={styles.panelHeader}><div><div className={styles.panelEyebrow}>School Day Runway</div><h3 className={styles.panelTitle}>Du portail du matin à la clôture</h3></div></div><div className={styles.runway}><div className={styles.runwayTrack}><div className={styles.runwayHours}>{['07:30','09:00','12:00','14:00','16:00','18:00'].map((h)=><div className={styles.runwayHour} key={h}><span>{h}</span></div>)}</div><div className={`${styles.runwayBand} ${styles.runwayArrival}`}>Arrivées</div><div className={`${styles.runwayBand} ${styles.runwayLearning}`}>Journée</div><div className={`${styles.runwayBand} ${styles.runwayTransition}`}>Transitions</div><div className={`${styles.runwayBand} ${styles.runwayDeparture}`}>Départs</div></div></div></section>

  <div className={styles.filters} role="toolbar" aria-label="Filtres de présence du jour">{([['all','Tous'],['present','Présents'],['absent','Absents'],['late','Retards'],['left_early','Sorties anticipées'],['missing','Départs manquants']] as Array<[Lens,string]>).map(([key,label])=><button type="button" key={key} className={lens===key?styles.primaryButton:styles.secondaryButton} onClick={()=>setLens(key)}>{label}</button>)}</div>

  <section className={styles.panel}><div className={styles.panelHeader}><div><div className={styles.panelEyebrow}>Flux opérationnel</div><h3 className={styles.panelTitle}>{lens==='all'?'Tous les relevés':lens==='missing'?'Départs à confirmer':attendanceLabel(lens)}</h3><p className={styles.panelDescription}>Cliquez un élève pour ouvrir le contexte utile sans quitter cette journée.</p></div></div><div className={styles.list}>{filtered.length?filtered.map((r)=><div className={styles.listRow} key={r.id}><button type="button" className={styles.avatar} style={{border:0,cursor:'pointer'}} onClick={()=>open(r,'student')}>{initials(r.student_full_name)}</button><button type="button" style={{border:0,background:'transparent',textAlign:'left',padding:0,cursor:'pointer'}} className={styles.rowCopy} onClick={()=>open(r,r.attendance_status==='left_early'?'early':missingCheckout.some(x=>x.id===r.id)?'missing':r.check_out_at?'departure':'arrival')}><strong className={styles.rowTitle}>{r.student_full_name || 'Élève'}</strong><span className={styles.rowMeta}>{[r.class_name,r.section_name].filter(Boolean).join(' · ') || 'Classe non renseignée'} · Arrivée {timeFr(r.check_in_at||r.recorded_at)} {r.check_out_at?`· Départ ${timeFr(r.check_out_at)}`:''}</span></button><span className={styles.rowRight}><TonePill value={r.attendance_status}/>{missingCheckout.some(x=>x.id===r.id)?<span className={styles.pillRed}>Départ à confirmer</span>:null}</span></div>):<div className={styles.empty}><strong className={styles.emptyTitle}>Aucun relevé dans cette vue</strong><p className={styles.emptyText}>Changez de filtre ou vérifiez si les sessions de présence ont été ouvertes pour cette date.</p></div>}</div></section>

  {dayState.risks.length?<section className={styles.panel} data-zone-b-secondary="true"><div className={styles.panelHeader}><div><div className={styles.panelEyebrow}>Contrôles</div><h3 className={styles.panelTitle}>Attention opérationnelle</h3></div></div><div className={styles.panelPad}>{dayState.risks.map((risk)=><div className={styles.warning} key={risk} style={{marginBottom:8}}>{risk}</div>)}</div></section>:null}

  <StudentAttendanceQuickPeek open={surface==='student'} onClose={()=>setSurface(null)} record={selected}/><ArrivalDetailDrawer open={surface==='arrival'} onClose={()=>setSurface(null)} record={selected}/><DepartureDetailDrawer open={surface==='departure'} onClose={()=>setSurface(null)} record={selected}/><EarlyDepartureDrawer open={surface==='early'} onClose={()=>setSurface(null)} record={selected}/><MissingCheckoutResolutionDrawer open={surface==='missing'} onClose={()=>setSurface(null)} record={selected}/><DayClosureChamber open={closure} onClose={()=>setClosure(false)} date={dayState.selectedDate} expected={dayState.totalExpectedStudents} marked={dayState.totalMarkedStudents} unresolved={records.filter(r=>r.attendance_status==='absent'&&!r.justification_status).length} missingCheckout={missingCheckout.length}/>
 </div>
}
