import path from 'node:path'
import {readFile} from 'node:fs/promises'
import {stableSemanticKey} from '../hash'
import type {DiscoveredCandidate} from '../types'
import {sha256Node} from './node-hash'

const EXT=new Set(['.json','.yml','.yaml'])
const humanKey=/(label|title|name|description|help|tooltip|placeholder|message|caption|alt|heading|subtitle|content|instruction)/i
function meaningful(value:string){const text=value.trim();return text.length>1&&text.length<4000&&/[A-Za-zÀ-ÿ\u0600-\u06ff]/.test(text)&&!/^https?:\/\//.test(text)}
function candidate(relative:string,keyPath:string[],value:string):DiscoveredCandidate{const clean=value.trim();return{stableKey:stableSemanticKey(['marketplace','content',relative,...keyPath]),sourceTextFr:clean,sourceHash:sha256Node(clean),sourceType:'content_file',sourcePath:relative,domain:'content',contentType:'structured_content',sensitivity:'ordinary',variables:[],supportsHtml:/<\w/.test(clean),directionalityRisk:false,classification:'translatable',confidence:.9,discoveryEvidence:{identity:'file_structural_key_path',keyPath}}}
function jsonLeaves(value:unknown,keyPath:string[]=[]):Array<{keyPath:string[];value:string}>{if(typeof value==='string')return humanKey.test(keyPath.at(-1)||'')&&meaningful(value)?[{keyPath,value}]:[];if(Array.isArray(value))return value.flatMap((item,index)=>{const record=item&&typeof item==='object'?item as Record<string,unknown>:null,semantic=record&&['key','id','code','slug'].map(key=>record[key]).find(candidate=>typeof candidate==='string');return jsonLeaves(item,[...keyPath,semantic?`item:${semantic}`:`item:${index}`])});if(value&&typeof value==='object')return Object.entries(value as Record<string,unknown>).flatMap(([key,item])=>jsonLeaves(item,[...keyPath,key]));return[]}
export async function scanContentFile(filePath:string,appRoot:string):Promise<DiscoveredCandidate[]>{const extension=path.extname(filePath);if(!EXT.has(extension))return[];const source=await readFile(filePath,'utf8'),relative=path.relative(appRoot,filePath);if(extension==='.json'){const parsed=JSON.parse(source)as unknown;return jsonLeaves(parsed).map(item=>candidate(relative,item.keyPath,item.value))}const leaves:Array<{keyPath:string[];value:string}>=[],stack:Array<{indent:number;key:string}>=[];for(const line of source.split(/\r?\n/)){const match=line.match(/^(\s*)([\w.-]+)\s*:\s*["']?(.+?)["']?\s*$/);if(!match)continue;const indent=match[1].length,key=match[2],value=match[3];while(stack.length&&stack.at(-1)!.indent>=indent)stack.pop();const keyPath=[...stack.map(item=>item.key),key];if(humanKey.test(key)&&meaningful(value))leaves.push({keyPath,value});stack.push({indent,key})}return leaves.map(item=>candidate(relative,item.keyPath,item.value))}
