import path from 'node:path'
import {readdir,stat} from 'node:fs/promises'
import {scanSourceAst} from './source-ast'
import {scanContentFile} from './content-files'
import {buildSourceAudienceMap} from './audience-graph'
import type {DiscoveredCandidate,ScanRequest,SourceAdapterType} from '../types'

const IGNORE=new Set(['node_modules','.next','.git','.angelcare-marketplace-backups','dist','build','coverage','documentation','docs','__tests__','tests','test'])
async function walk(root:string):Promise<string[]>{const out:string[]=[];async function visit(directory:string){const names=await readdir(directory);await Promise.all(names.map(async name=>{if(IGNORE.has(name))return;const file=path.join(directory,name),info=await stat(file);if(info.isDirectory())await visit(file);else if(info.size<=2_000_000)out.push(file)}))}await visit(root);return out}
export interface ScanResult{candidates:DiscoveredCandidate[];adapterCounts:Record<string,number>;failures:Array<{adapter:string;source:string;message:string}>;scannedFiles:number}
export async function executeFilesystemScan(appRoot:string,request:ScanRequest):Promise<ScanResult>{
 const roots=['angelcare-marketplace','app/angelcare-marketplace','app/api/angelcare-marketplace'].map(root=>path.join(appRoot,root)),files=request.changedPaths?.length?request.changedPaths.map(file=>path.resolve(appRoot,file)):(await Promise.all(roots.map(root=>walk(root)))).flat(),active=new Set<SourceAdapterType>(request.adapters||['source_ast','backend_api','communication_template','seo_metadata','content_file']),unique=new Map<string,DiscoveredCandidate>(),failures:ScanResult['failures']=[],counts:Record<string,number>={},audienceByFile=await buildSourceAudienceMap(files,appRoot)
 const collect=(adapter:SourceAdapterType,candidates:DiscoveredCandidate[])=>{counts[adapter]=(counts[adapter]||0)+candidates.length;for(const candidate of candidates){const existing=unique.get(candidate.stableKey);if(!existing||candidate.confidence>existing.confidence)unique.set(candidate.stableKey,candidate)}}
 async function scanFile(file:string){const relative=path.relative(appRoot,file);try{if(active.has('source_ast')||active.has('backend_api')||active.has('seo_metadata')){const ast=await scanSourceAst(file,appRoot,audienceByFile.get(path.normalize(file)));if(active.has('source_ast'))collect('source_ast',ast);if(active.has('backend_api')&&/api|server|validation|error|repository|handler/i.test(relative))collect('backend_api',ast.map(candidate=>({...candidate,sourceType:'backend_api' as const,contentType:`backend_${candidate.contentType}`,confidence:.95})));if(active.has('seo_metadata'))collect('seo_metadata',ast.filter(candidate=>/metadata|title|description|open.?graph|canonical/i.test(candidate.contentType)).map(candidate=>({...candidate,sourceType:'seo_metadata' as const,contentType:'seo_metadata',confidence:.96})))}if(active.has('content_file')||active.has('communication_template')){const content=await scanContentFile(file,appRoot);if(active.has('content_file'))collect('content_file',content);if(active.has('communication_template')&&/template|email|sms|whatsapp|notification|certificate|report/i.test(relative))collect('communication_template',content.map(candidate=>({...candidate,sourceType:'communication_template' as const,contentType:'communication_template',confidence:.9})))}}catch(error){failures.push({adapter:'filesystem',source:relative,message:error instanceof Error?error.message:'Erreur inconnue'})}}
 for(let index=0;index<files.length;index+=64)await Promise.all(files.slice(index,index+64).map(scanFile))
 return{candidates:[...unique.values()],adapterCounts:counts,failures,scannedFiles:files.length}
}
