import Link from 'next/link'
import { AlertTriangle, ArrowDownLeft, ArrowUpRight, Link2, Network, ShieldCheck } from 'lucide-react'
import type { CmsDependencyEdge, CmsPage } from '../types'
import styles from '../experience.module.css'

export function DependencyGraphWorkspace({edges,pages}:{edges:CmsDependencyEdge[];pages:CmsPage[]}){
 const pageMap=new Map(pages.map(page=>[page.id,page]));const byRelation=[...new Set(edges.map(edge=>edge.relation_type))].sort();const routes=new Set(pages.map(page=>page.slug==='accueil'?`/angelcare-marketplace/${page.locale}`:`/angelcare-marketplace/${page.locale}/${page.slug}`));const broken=edges.filter(edge=>edge.target_type==='route'&&edge.target_route?.startsWith('/angelcare-marketplace/')&&!routes.has(edge.target_route));const inboundPageIds=new Set(edges.filter(edge=>edge.target_type==='page'&&edge.target_id).map(edge=>edge.target_id!));const orphans=pages.filter(page=>!inboundPageIds.has(page.id)&&page.slug!=='accueil')
 return <div className={styles.graphWorkspace}><section className={styles.registryMetrics}><div><span>Edges</span><strong>{edges.length}</strong><small>dépendances indexées</small></div><div><span>Relations</span><strong>{byRelation.length}</strong><small>{byRelation.join(', ')||'—'}</small></div><div><span>Routes suspectes</span><strong>{broken.length}</strong><small>internes non résolues</small></div><div><span>Pages sans inbound</span><strong>{orphans.length}</strong><small>information, pas blocage global</small></div></section><section className={styles.graphSplit}><div className={styles.graphTable}><header><div><span>LIVE EXPERIENCE GRAPH</span><h2>Source → relation → cible</h2></div><Network size={20}/></header>{edges.slice(0,500).map(edge=><article key={edge.id} data-broken={broken.some(item=>item.id===edge.id)}><div><span><ArrowUpRight size={12}/> SOURCE</span><strong>{pageMap.get(edge.page_id)?.title||edge.page_id}</strong><small>{edge.source_type}:{edge.source_key}{edge.source_field?` · ${edge.source_field}`:''}</small></div><div className={styles.graphRelation}><Link2 size={13}/><strong>{edge.relation_type}</strong></div><div><span><ArrowDownLeft size={12}/> TARGET</span><strong>{edge.target_type}</strong><small>{edge.target_id||edge.target_key||edge.target_route||'—'}</small></div></article>)}{!edges.length?<div className={styles.empty}>Le graphe sera alimenté automatiquement à chaque révision après application de la migration Experience Core.</div>:null}</div><aside className={styles.graphRail}><section><span>IMPACT</span><h2>{broken.length?'Références à vérifier':'Aucun broken link interne détecté'}</h2>{broken.slice(0,15).map(edge=><div className={styles.graphIssue} key={edge.id}><AlertTriangle size={13}/><div><strong>{pageMap.get(edge.page_id)?.title||'Page'}</strong><small>{edge.target_route}</small></div></div>)}</section><section><span>PROTECTED OPERATIONS</span><h2>Delete doit respecter le graphe</h2><p><ShieldCheck size={13}/> Les symboles refusent déjà l’archivage lorsqu’une dépendance les référence. Ce graphe constitue l’autorité Where Used pour étendre la même protection aux pages/assets.</p></section><section><span>ORPHANS</span>{orphans.slice(0,15).map(page=><Link href={`/angelcare-marketplace/admin/experience/pages/${page.id}`} key={page.id}>{page.title}<small>{page.locale} · /{page.slug}</small></Link>)}</section></aside></section></div>
}
