import { ServiceBlueprint, ServiceModule } from './types'
export const angelcareServiceModules: ServiceModule[] = [
 {key:'transport',label:'Transport & mobilité',description:'Gestion trajet, rayon, indemnité, consentement et retard.',defaultEnabled:false,enterpriseImpact:'Sécurise les missions terrain et permet expansion multi-zone.',costWeight:12},
 {key:'school_support',label:'Support école',description:'Présence à l’école, coordination institution, liaison professeur/parent.',defaultEnabled:false,enterpriseImpact:'Ouvre B2B écoles et familles premium.'},
 {key:'meal_support',label:'Repas & routine',description:'Suivi repas, restrictions, hygiène, routines enfant.',defaultEnabled:true,enterpriseImpact:'Standardise le soin quotidien.'},
 {key:'nurse_supervision',label:'Supervision infirmière',description:'Contrôle cas sensibles, postpartum, nouveau-né, santé légère.',defaultEnabled:false,enterpriseImpact:'Crée offre premium sécurisée.',requiredRole:'Nurse Lead',costWeight:18},
 {key:'therapy_coordination',label:'Coordination thérapeutique',description:'Coordination orthophoniste, psychomotricité, protocoles spécifiques.',defaultEnabled:false,enterpriseImpact:'Renforce besoins spécifiques.'},
 {key:'parent_reporting',label:'Reporting parent',description:'Compte rendu mission, photos validées, notes, satisfaction.',defaultEnabled:true,enterpriseImpact:'Augmente confiance et rétention.'},
 {key:'emergency_protocol',label:'Protocole urgence',description:'Escalade, contacts, checklists, incident management.',defaultEnabled:true,enterpriseImpact:'Réduit risque opérationnel.'},
 {key:'montessori_activity',label:'Activités Montessori & ludique',description:'Programme ludique structuré, progression, matériel.',defaultEnabled:false,enterpriseImpact:'Différencie AngelCare sur le parascolaire.'},
 {key:'bilingual_support',label:'Support bilingue',description:'Français, arabe, anglais selon client premium/institution.',defaultEnabled:false,enterpriseImpact:'Positionne offres premium Rabat/Casa/Marrakech.'},
 {key:'overnight_support',label:'Nuit & 24h',description:'Garde nuit, majoration, sécurité et relais.',defaultEnabled:false,enterpriseImpact:'Augmente panier moyen.'},
 {key:'postpartum_mother_support',label:'Maman post-partum',description:'Confort maman, routine, repos, observation bien-être.',defaultEnabled:false,enterpriseImpact:'Nouvelle verticale premium.'},
 {key:'newborn_support',label:'Nouveau-né',description:'Soins légers bébé, sommeil, hygiène, suivi.',defaultEnabled:false,enterpriseImpact:'Offre sensible haut de gamme.'},
 {key:'academy_certification',label:'Certification Academy',description:'Formation obligatoire et renouvellement compétences.',defaultEnabled:false,enterpriseImpact:'Synchronise Academy + HR + Services.'},
 {key:'institution_contract',label:'Contrat institutionnel',description:'SLA, volume, tarification B2B, responsable compte.',defaultEnabled:false,enterpriseImpact:'Débloque écoles, hôtels, cliniques, entreprises.'},
 {key:'quality_audit',label:'Audit qualité',description:'Contrôle mission, score qualité, incident root-cause.',defaultEnabled:true,enterpriseImpact:'Industrialise l’excellence.'},
 {key:'ai_monitoring',label:'AI monitoring',description:'Suggestions, risque, matching, expansion, pricing.',defaultEnabled:false,enterpriseImpact:'Prépare domination marché.'},
]
const workflow=(prefix:string)=>[
 {id:`${prefix}-qualify`,title:'Qualification besoin',ownerRole:'Service Advisor',slaHours:2,required:true,automation:'score besoin + urgence',exitCriteria:'profil client et besoin validés'},
 {id:`${prefix}-configure`,title:'Configuration service',ownerRole:'Ops Manager',slaHours:4,required:true,automation:'modules recommandés',exitCriteria:'blueprint mission complet'},
 {id:`${prefix}-match`,title:'Matching staff',ownerRole:'HR/Ops',slaHours:6,required:true,automation:'staff compatible proposé',exitCriteria:'staff assignable disponible'},
 {id:`${prefix}-contract`,title:'Contrat & consentements',ownerRole:'Admin/Finance',slaHours:8,required:true,automation:'documents requis générés',exitCriteria:'dossier conforme'},
 {id:`${prefix}-launch`,title:'Lancement mission',ownerRole:'Field Coordinator',slaHours:1,required:true,automation:'checklist départ',exitCriteria:'mission démarrée'},
 {id:`${prefix}-quality`,title:'Quality review',ownerRole:'Quality Lead',slaHours:24,required:true,automation:'survey parent + incident scan',exitCriteria:'score qualité enregistré'},
]
export const angelcareBlueprints: ServiceBlueprint[] = [
 {id:'bp-home-care',serviceCode:'#H.S',name:"Garde & accompagnement d'enfants à domicile",family:'Home care',deploymentModes:['home'],summary:'Service cœur pour familles, configurable par durée, âge, routine, reporting et premium zones.',modules:['meal_support','parent_reporting','emergency_protocol','quality_audit','bilingual_support','overnight_support'],rules:[{id:'hs-night',trigger:'time',condition:'mission après 22:00',action:'activer majoration nuit + transport',pricingModifier:1.25,escalation:'Ops Manager',severity:'medium'}],workflows:workflow('hs'),cityDeployments:[{city:'Rabat',active:true,priority:'core',capacity:85,staffPool:34,demandScore:92,riskScore:24,pricingZone:'premium'},{city:'Casablanca',active:true,priority:'growth',capacity:70,staffPool:41,demandScore:96,riskScore:31,pricingZone:'premium'}],version:'1.0.0',readiness:84,marginTarget:32,expansionPriority:95,complianceLevel:'controlled'},
 {id:'bp-special-hybrid',serviceCode:'#S.H',name:'Garde enfant spécial hybride école + domicile',family:'Special needs',deploymentModes:['hybrid','school','home'],summary:'Offre sensible très différenciée pour besoins spécifiques avec protocole école, parent et staff certifié.',modules:['school_support','therapy_coordination','parent_reporting','emergency_protocol','bilingual_support','academy_certification','quality_audit','ai_monitoring'],rules:[{id:'sh-cert',trigger:'complexity',condition:'autisme ou besoin spécifique déclaré',action:'certification spécialisée obligatoire',requiredCertification:'Special Needs Care',escalation:'Clinical/Nurse Supervisor',severity:'critical'}],workflows:workflow('sh'),cityDeployments:[{city:'Rabat',active:true,priority:'premium',capacity:45,staffPool:12,demandScore:88,riskScore:42,pricingZone:'premium'},{city:'Casablanca',active:true,priority:'growth',capacity:52,staffPool:15,demandScore:91,riskScore:48,pricingZone:'premium'}],version:'1.0.0',readiness:78,marginTarget:38,expansionPriority:98,complianceLevel:'critical'},
 {id:'bp-postpartum',serviceCode:'#P.P',name:'Post-partum maman & nouveau-né',family:'Postpartum',deploymentModes:['home'],summary:'Service premium sensible pour maman, bébé, routine, repos, sécurité et accompagnement familial.',modules:['postpartum_mother_support','newborn_support','nurse_supervision','parent_reporting','emergency_protocol','quality_audit','overnight_support'],rules:[{id:'pp-newborn',trigger:'age',condition:'bébé moins de 3 mois',action:'supervision infirmière recommandée + protocole nouveau-né',requiredCertification:'Newborn Safety',severity:'high'}],workflows:workflow('pp'),cityDeployments:[{city:'Rabat',active:true,priority:'premium',capacity:36,staffPool:9,demandScore:86,riskScore:36,pricingZone:'premium'},{city:'Marrakech',active:false,priority:'pilot',capacity:18,staffPool:3,demandScore:78,riskScore:54,pricingZone:'premium'}],version:'1.0.0',readiness:72,marginTarget:42,expansionPriority:90,complianceLevel:'critical'},
 {id:'bp-education-ludique',serviceCode:'#S.L',name:'Parascolaire Montessori & activités ludiques',family:'Education',deploymentModes:['home','academy','institution'],summary:'Offre éducation ludique pour familles, écoles, anniversaires intelligents et programmes réguliers.',modules:['montessori_activity','parent_reporting','academy_certification','institution_contract','quality_audit','ai_monitoring'],rules:[{id:'edu-material',trigger:'contract',condition:'programme institutionnel',action:'kit matériel + curriculum + reporting groupe obligatoire',severity:'medium'}],workflows:workflow('edu'),cityDeployments:[{city:'Rabat',active:true,priority:'core',capacity:80,staffPool:18,demandScore:82,riskScore:18,pricingZone:'standard'},{city:'Casablanca',active:true,priority:'growth',capacity:90,staffPool:20,demandScore:89,riskScore:22,pricingZone:'premium'}],version:'1.0.0',readiness:81,marginTarget:35,expansionPriority:88,complianceLevel:'controlled'},
]
