import AppShell, { PageAction } from '@/app/components/erp/AppShell'
import { createClient } from '@/lib/supabase/server'
import { requireRole } from '@/lib/auth/session'
import { Badge, EmptyState, InsightCard, KpiCard, Panel, TableShell, WorkspaceHero, safeDate } from '../_components/BDWorkspacePrimitives'

export default async function CampaignsWorkspace() {
  await requireRole(['ceo', 'manager'])
  const supabase = await createClient()
  const { data } = await supabase.from('bd_campaigns').select('*').order('created_at', { ascending: false })
  const campaigns = data || []
  const active = campaigns.filter((c:any)=>c.status === 'active').length
  const b2b = campaigns.filter((c:any)=>c.segment === 'b2b').length
  const b2c = campaigns.filter((c:any)=>c.segment === 'b2c').length
  return <AppShell title="Prospecting Campaigns" subtitle="Gestion complète des campagnes B2C, B2B et partenariats." breadcrumbs={[{label:'Revenue',href:'/revenue-command-center'},{label:'Campaigns'}]} actions={<PageAction href="/revenue-command-center/business-development" variant="light">BD Workspace</PageAction>}><div style={pageStyle}><WorkspaceHero badge="Campaign Command" title="Prospecting Campaign Management" subtitle="Planifiez, segmentez, exécutez et ajustez les campagnes: WhatsApp, appels, email, terrain, institutions, prescripteurs et partenariats."/><section style={kpiGrid}><KpiCard label="Campagnes" value={campaigns.length} sub="total"/><KpiCard label="Actives" value={active} sub="en exécution" tone="green"/><KpiCard label="B2B" value={b2b} sub="corporate" tone="purple"/><KpiCard label="B2C" value={b2c} sub="familles" tone="blue"/></section><section style={grid}><Panel title="Campaign Board" subtitle="Vue management des campagnes.">{campaigns.length?<TableShell><table style={table}><thead><tr><th style={th}>Campagne</th><th style={th}>Segment</th><th style={th}>Canal</th><th style={th}>Statut</th><th style={th}>Objectif</th><th style={th}>Date</th></tr></thead><tbody>{campaigns.map((c:any)=><tr key={c.id}><td style={td}><strong>{c.name}</strong></td><td style={td}><Badge tone={c.segment==='b2b'?'purple':'green'}>{c.segment||'global'}</Badge></td><td style={td}>{c.channel||'multi-channel'}</td><td style={td}>{c.status||'draft'}</td><td style={td}>{c.objective||'—'}</td><td style={td}>{safeDate(c.created_at)}</td></tr>)}</tbody></table></TableShell>:<EmptyState text="Aucune campagne structurée."/>}</Panel><Panel title="Execution Playbook" subtitle="Standards corporate d'exécution."><div style={stack}><InsightCard title="Segmentation avant volume" text="Aucune campagne ne doit partir sans segment clair, promesse, canal, objectif et responsable." tone="blue"/><InsightCard title="Cadence de relance" text="Chaque campagne doit créer des tâches de rappel, rendez-vous et logs CRM." tone="amber"/><InsightCard title="Mesure terrain" text="Ne pas juger seulement le nombre de leads: mesurer qualification, rendez-vous, propositions et closing." tone="green"/></div></Panel></section></div></AppShell>
}
const pageStyle:React.CSSProperties={display:'grid',gap:20}; const kpiGrid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:14}; const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'1.4fr .6fr',gap:18,alignItems:'start'}; const stack:React.CSSProperties={display:'grid',gap:12}; const table:React.CSSProperties={width:'100%',borderCollapse:'collapse'}; const th:React.CSSProperties={textAlign:'left',padding:14,background:'#0f172a',color:'#fff'}; const td:React.CSSProperties={padding:14,borderBottom:'1px solid #e2e8f0',color:'#334155'}
