import { requireMarketplaceApiContext } from '../auth/context'
import { apiFailure, apiSuccess, cleanOptionalText, cleanText, parseJsonObject, requestId, requireText } from '../server/request'
import { MarketplaceError } from '../server/errors'
import { requireDate, recordValue, stringArray, validateDiagnostic } from './validation'
import { addSupportMessage, adminListFamilies, adminListRequests, createChild, createDiagnostic, createQuoteRequest, createSupportTicket, getChild, getFamilyDashboard, getMission, getQuoteRequest, getSupportTicket, listChildren, listDiagnostics, listMissions, listQuoteRequests, listSupportTickets, qualifyRequest, updateFamilyAccount } from './repository'

export async function handleFamilyDashboard(request:Request){const id=requestId(request);try{const context=await requireMarketplaceApiContext('marketplace.family.dashboard');return apiSuccess(await getFamilyDashboard(context),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleFamilyAccount(request:Request){const id=requestId(request);try{const context=await requireMarketplaceApiContext(request.method==='GET'?'marketplace.family.profile.view':'marketplace.family.profile.manage');if(request.method==='GET')return apiSuccess((await getFamilyDashboard(context)).account,{requestId:id});const body=await parseJsonObject(request);return apiSuccess(await updateFamilyAccount({patch:{display_name:requireText(body.displayName,'displayName','Nom',180),phone:requireText(body.phone,'phone','Téléphone',80),city:requireText(body.city,'city','Ville',120),preferred_locale:cleanText(body.preferredLocale||'fr',5),consent_status:body.consent===true?'granted':'pending'},context,requestId:id}),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleChildren(request:Request){const id=requestId(request);try{const context=await requireMarketplaceApiContext(request.method==='GET'?'marketplace.family.children.view':'marketplace.family.children.manage');if(request.method==='GET')return apiSuccess(await listChildren(context),{requestId:id});const body=await parseJsonObject(request);return apiSuccess(await createChild({firstName:requireText(body.firstName,'firstName','Prénom',80),birthDate:requireDate(body.birthDate,'birthDate','Date de naissance'),ageGroup:requireText(body.ageGroup,'ageGroup','Tranche d’âge',40),gender:cleanOptionalText(body.gender,30),schoolLevel:cleanOptionalText(body.schoolLevel,80),languages:stringArray(body.languages),interests:stringArray(body.interests),allergies:cleanOptionalText(body.allergies,1000),medicalBoundaries:cleanOptionalText(body.medicalBoundaries,1000),supportNotes:cleanOptionalText(body.supportNotes,2000),context,requestId:id}),{requestId:id,status:201})}catch(error){return apiFailure(error,id)}}
export async function handleChild(request:Request,childId:string){const id=requestId(request);try{const context=await requireMarketplaceApiContext('marketplace.family.children.view');return apiSuccess(await getChild(context,childId),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleDiagnostics(request:Request){const id=requestId(request);try{const context=await requireMarketplaceApiContext(request.method==='GET'?'marketplace.family.diagnostics.view':'marketplace.family.diagnostics.create');if(request.method==='GET')return apiSuccess(await listDiagnostics(context),{requestId:id});const body=await parseJsonObject(request);const developmentGoals=stringArray(body.developmentGoals),routineNeeds=stringArray(body.routineNeeds),familyPriorities=stringArray(body.familyPriorities);validateDiagnostic({developmentGoals,routineNeeds,familyPriorities});return apiSuccess(await createDiagnostic({childId:requireText(body.childId,'childId','Enfant',100),scheduleNeeds:recordValue(body.scheduleNeeds),developmentGoals,routineNeeds,safetyConstraints:stringArray(body.safetyConstraints),familyPriorities,freeContext:cleanOptionalText(body.freeContext,3000),context,requestId:id}),{requestId:id,status:201})}catch(error){return apiFailure(error,id)}}
export async function handleQuoteRequests(request:Request){const id=requestId(request);try{const context=await requireMarketplaceApiContext(request.method==='GET'?'marketplace.family.requests.view':'marketplace.family.requests.create');if(request.method==='GET')return apiSuccess(await listQuoteRequests(context),{requestId:id});const body=await parseJsonObject(request);return apiSuccess(await createQuoteRequest({childId:cleanOptionalText(body.childId,100),diagnosticId:cleanOptionalText(body.diagnosticId,100),serviceFamily:requireText(body.serviceFamily,'serviceFamily','Famille de service',120),city:requireText(body.city,'city','Ville',120),requestedStartDate:cleanOptionalText(body.requestedStartDate,20),schedule:recordValue(body.schedule),durationExpectation:cleanOptionalText(body.durationExpectation,120),locationNotes:cleanOptionalText(body.locationNotes,2000),priorities:stringArray(body.priorities),context,requestId:id}),{requestId:id,status:201})}catch(error){return apiFailure(error,id)}}
export async function handleQuoteRequest(request:Request,idValue:string){const id=requestId(request);try{const context=await requireMarketplaceApiContext('marketplace.family.requests.view');return apiSuccess(await getQuoteRequest(context,idValue),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleMissions(request:Request){const id=requestId(request);try{const context=await requireMarketplaceApiContext('marketplace.family.missions.view');return apiSuccess(await listMissions(context),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleMission(request:Request,missionId:string){const id=requestId(request);try{const context=await requireMarketplaceApiContext('marketplace.family.missions.view');return apiSuccess(await getMission(context,missionId),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleSupport(request:Request){const id=requestId(request);try{const context=await requireMarketplaceApiContext(request.method==='GET'?'marketplace.family.support.view':'marketplace.family.support.create');if(request.method==='GET')return apiSuccess(await listSupportTickets(context),{requestId:id});const body=await parseJsonObject(request);const priority=cleanText(body.priority||'normal',20);if(!['normal','high','urgent'].includes(priority))throw new MarketplaceError('VALIDATION_ERROR','Priorité invalide.');return apiSuccess(await createSupportTicket({subject:requireText(body.subject,'subject','Objet',200),category:requireText(body.category,'category','Catégorie',80),priority,message:requireText(body.message,'message','Message',4000),context,requestId:id}),{requestId:id,status:201})}catch(error){return apiFailure(error,id)}}
export async function handleSupportTicket(request:Request,ticketId:string){const id=requestId(request);try{const context=await requireMarketplaceApiContext('marketplace.family.support.view');return apiSuccess(await getSupportTicket(context,ticketId),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleSupportMessage(request:Request,ticketId:string){const id=requestId(request);try{const context=await requireMarketplaceApiContext('marketplace.family.support.create');const body=await parseJsonObject(request);return apiSuccess(await addSupportMessage({ticketId,body:requireText(body.body,'body','Message',4000),context,requestId:id}),{requestId:id,status:201})}catch(error){return apiFailure(error,id)}}
export async function handleAdminFamilies(request:Request){const id=requestId(request);try{await requireMarketplaceApiContext('marketplace.family.profile.view');return apiSuccess(await adminListFamilies(),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleAdminRequests(request:Request){const id=requestId(request);try{await requireMarketplaceApiContext('marketplace.family.requests.manage');return apiSuccess(await adminListRequests(new URL(request.url).searchParams.get('status')||undefined),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleQualifyRequest(request:Request,requestIdValue:string){const id=requestId(request);try{const context=await requireMarketplaceApiContext('marketplace.family.requests.qualify');const body=await parseJsonObject(request);const status=cleanText(body.status,30);if(!['qualified','proposal_ready','declined'].includes(status))throw new MarketplaceError('VALIDATION_ERROR','Statut de qualification invalide.');return apiSuccess(await qualifyRequest({id:requestIdValue,status:status as 'qualified'|'proposal_ready'|'declined',notes:requireText(body.notes,'notes','Notes de qualification',3000),nextAction:requireText(body.nextAction,'nextAction','Prochaine action',1000),context,requestId:id}),{requestId:id})}catch(error){return apiFailure(error,id)}}
