'use client'
import { Eye, Globe2, Network, Plus, Route, Target } from 'lucide-react'
import type { SovereignHeroProps } from '../hero-types'
import { AngelCareHeroBrand, HeroActionRail, HeroAuthorityBadge, HeroExecutiveBrief, HeroMetricGrid, HeroTruthBadge, HeroWarning } from '../HeroPrimitives'
import styles from '../SovereignHeroes.module.css'

export default function DigitalTwinHero({ state, posture, authority, summary, metrics = [], actions = [], freshness, warning }: SovereignHeroProps) {
  const nodes=[['Marchés','left-[11%] top-[26%]'],['Segments','left-[30%] top-[10%]'],['Offres','left-[45%] top-[40%]'],['Capacité','right-[10%] top-[20%]'],['Contraintes','right-[22%] bottom-[13%]'],['Parcours','left-[19%] bottom-[12%]']]
  return <section className={`${styles.hero} min-h-[420px] bg-[linear-gradient(140deg,#f8fbff_0%,#eef8ff_58%,#f7fbff_100%)] p-6 sm:p-8 xl:p-10`} data-hero-id="MZ22-HERO-03-DIGITAL-TWIN">
    <div className={`absolute inset-0 opacity-55 ${styles.dotField}`} /><div className={`${styles.redTriangle} -right-8 top-8`} />
    <div className="relative grid gap-8 xl:grid-cols-[.9fr_1.1fr] xl:items-center"><div><div className="flex flex-wrap gap-2"><HeroTruthBadge state={state}/><HeroAuthorityBadge>{authority}</HeroAuthorityBadge><span className="rounded-full border border-cyan-200 bg-cyan-50 px-3 py-2 text-[9px] font-black uppercase tracking-[.12em] text-cyan-800">{posture}</span></div><div className="mt-5"><AngelCareHeroBrand /></div><p className="mt-7 text-[10px] font-black uppercase tracking-[.22em] text-cyan-700">Commercial World Model</p><h1 className="mt-2 text-4xl font-black tracking-[-.06em] text-slate-950 sm:text-6xl">Jumeau</h1><p className="mt-4 max-w-2xl text-sm font-semibold leading-7 text-slate-600">Cartographier marchés, offres, segments, territoires, capacités et contraintes comme un monde commercial cohérent et vérifiable.</p><div className="mt-6"><HeroExecutiveBrief>{summary}</HeroExecutiveBrief></div>{freshness ? <p className="mt-3 text-[9px] font-bold uppercase tracking-[.12em] text-slate-400">Modèle actualisé · {freshness}</p> : null}<HeroWarning>{warning}</HeroWarning><div className="mt-5"><HeroActionRail actions={actions}/></div></div>
      <div className="relative min-h-[330px] overflow-hidden rounded-[34px] border border-cyan-200/80 bg-white/80 p-5 shadow-[0_24px_70px_rgba(14,116,144,.10)] backdrop-blur"><svg aria-hidden="true" className="absolute inset-0 h-full w-full" viewBox="0 0 760 330" preserveAspectRatio="none"><path d="M80 90 L240 55 L365 150 L590 75 L650 245 L430 270 L165 245 Z" fill="none" stroke="rgba(8,145,178,.25)" strokeWidth="2"/><path d="M240 55 L165 245 M365 150 L650 245 M590 75 L430 270" stroke="rgba(37,99,235,.16)" strokeWidth="1.5" className={styles.flowLine}/></svg><div className="absolute left-1/2 top-1/2 grid h-28 w-28 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border border-cyan-300 bg-white shadow-[0_20px_50px_rgba(8,145,178,.18)]"><Network className="text-cyan-700" size={29}/><span className="absolute bottom-4 text-[8px] font-black uppercase tracking-[.12em] text-slate-500">World core</span></div>{nodes.map(([label,pos],index)=><div key={label} className={`absolute ${pos} rounded-2xl border border-slate-200 bg-white px-3 py-2 shadow-[0_10px_28px_rgba(15,23,42,.08)]`}><span className="flex items-center gap-2 text-[9px] font-black text-slate-700"><span className={`h-2 w-2 rounded-full ${index===4?'bg-rose-500':'bg-cyan-500'}`}/>{label}</span></div>)}<div className="absolute inset-x-5 bottom-5"><HeroMetricGrid metrics={metrics.slice(0,4)} /></div></div>
    </div>
  </section>
}
