'use client'
import { AlertOctagon, CircleOff, Route, ShieldAlert, TimerReset } from 'lucide-react'
import type { SovereignHeroProps } from '../hero-types'
import { AngelCareHeroBrand, HeroActionRail, HeroAuthorityBadge, HeroExecutiveBrief, HeroMetricGrid, HeroTruthBadge, HeroWarning } from '../HeroPrimitives'
import styles from '../SovereignHeroes.module.css'

export default function ExceptionsHero({ state, posture, authority, summary, metrics = [], actions = [], freshness, warning }: SovereignHeroProps) {
 return <section className={`${styles.hero} min-h-[410px] bg-[linear-gradient(125deg,#0f172a_0%,#301523_50%,#431b22_100%)] p-6 text-white sm:p-8 xl:p-10`} data-hero-surface="dark" data-hero-id="MZ22-HERO-15-EXCEPTIONS"><div className={`absolute inset-0 opacity-18 ${styles.fineGrid}`}/><div className={`${styles.redTriangle} right-3 bottom-7`}/><div className="relative grid gap-8 xl:grid-cols-[1fr_520px] xl:items-center"><div><div className="flex flex-wrap gap-2"><HeroTruthBadge state={state}/><HeroAuthorityBadge inverted>{authority}</HeroAuthorityBadge><span className="rounded-full border border-rose-200/20 bg-rose-300/10 px-3 py-2 text-[9px] font-black uppercase tracking-[.12em] text-rose-100">{posture}</span></div><div className="mt-5"><AngelCareHeroBrand inverted /></div><p className="mt-7 text-[10px] font-black uppercase tracking-[.22em] text-rose-200">Intervention Tower</p><h1 className="mt-2 text-4xl font-black tracking-[-.06em] sm:text-6xl">Exceptions</h1><p className="mt-4 max-w-3xl text-sm font-semibold leading-7 text-slate-300">Maintenir un contrôle calme sous pression, hiérarchiser les escalades et isoler les routes de récupération sans surcharge alarmiste.</p><div className="mt-6"><HeroExecutiveBrief dark>{summary}</HeroExecutiveBrief></div>{freshness ? <p className="mt-3 text-[9px] font-bold uppercase tracking-[.12em] text-slate-400">Intervention priority · {freshness}</p> : null}<HeroWarning dark>{warning}</HeroWarning><div className="mt-5"><HeroActionRail actions={actions} dark /></div></div><aside className="rounded-[34px] border border-rose-200/15 bg-white/[.055] p-5 backdrop-blur-xl"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.16em] text-rose-200">Intervention runway</p><p className="mt-1 text-lg font-black">Recoverable → terminal</p></div><ShieldAlert className="text-rose-200" size={24}/></div><div className="mt-5 space-y-3">{([['Récupérable','Route connue',TimerReset,'emerald'],['Escalade','Autorité requise',AlertOctagon,'amber'],['Bloqué','Cause racine',CircleOff,'rose']] as const).map(([label,note,Icon,tone],index)=><div key={String(label)} className="grid grid-cols-[44px_1fr_auto] items-center gap-3 rounded-2xl border border-white/10 bg-white/[.045] p-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone==='emerald'?'bg-emerald-300/10 text-emerald-200':tone==='amber'?'bg-amber-300/10 text-amber-200':'bg-rose-300/10 text-rose-200'}`}><Icon size={17}/></span><div><p className="text-xs font-black">{label}</p><p className="mt-1 text-[8px] uppercase tracking-[.1em] text-slate-400">{note}</p></div><span className="font-mono text-[9px] text-slate-400">0{index+1}:00</span></div>)}</div><div className="mt-4"><HeroMetricGrid metrics={metrics.slice(0,4)} dark /></div></aside></div></section>
}
