'use client'
import { Archive, FileCheck2, FolderLock, ListChecks, PackageCheck } from 'lucide-react'
import type { SovereignHeroProps } from '../hero-types'
import { AngelCareHeroBrand, HeroActionRail, HeroAuthorityBadge, HeroExecutiveBrief, HeroMetricGrid, HeroTruthBadge, HeroWarning } from '../HeroPrimitives'
import styles from '../SovereignHeroes.module.css'

export default function MissionsHero({ state, posture, authority, summary, metrics = [], actions = [], freshness, warning }: SovereignHeroProps) {
 const folders=['Active','Compiled','Validation','Archive']
 return <section className={`${styles.hero} min-h-[390px] bg-[linear-gradient(135deg,#faf8f4_0%,#ffffff_48%,#f4f7fb_100%)] p-6 sm:p-8 xl:p-10`} data-hero-surface="light" data-hero-id="MZ22-HERO-13-MISSIONS"><div className={`absolute inset-0 opacity-35 ${styles.fineGrid}`}/><div className={`${styles.redTriangle} right-3 bottom-7`}/><div className="relative grid gap-8 xl:grid-cols-[1fr_520px] xl:items-center"><div><div className="flex flex-wrap gap-2"><HeroTruthBadge state={state}/><HeroAuthorityBadge>{authority}</HeroAuthorityBadge><span className="rounded-full border border-blue-200 bg-blue-50 px-3 py-2 text-[9px] font-black uppercase tracking-[.12em] text-blue-800">{posture}</span></div><div className="mt-5"><AngelCareHeroBrand /></div><p className="mt-7 text-[10px] font-black uppercase tracking-[.22em] text-blue-700">Mission Archive Gallery</p><h1 className="mt-2 text-4xl font-black tracking-[-.06em] text-slate-950 sm:text-6xl">Missions</h1><p className="mt-4 max-w-2xl text-sm font-semibold leading-7 text-slate-600">Présenter et gouverner les dossiers compilés comme des objets opérationnels tangibles, classifiés et traçables.</p><div className="mt-6"><HeroExecutiveBrief>{summary}</HeroExecutiveBrief></div>{freshness ? <p className="mt-3 text-[9px] font-bold uppercase tracking-[.12em] text-slate-400">Dossiers · {freshness}</p> : null}<HeroWarning>{warning}</HeroWarning><div className="mt-5"><HeroActionRail actions={actions}/></div></div><aside className="rounded-[34px] border border-stone-200 bg-[#fffefa] p-5 shadow-[0_24px_70px_rgba(68,64,60,.10)]"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.16em] text-blue-700">Classified archive</p><p className="mt-1 text-lg font-black text-slate-950">Dossiers de mission</p></div><Archive className="text-blue-700" size={24}/></div><div className="mt-5 flex gap-3 overflow-hidden">{folders.map((folder,index)=><div key={folder} className={`relative h-40 min-w-24 flex-1 rounded-t-[20px] border border-b-4 p-3 ${index===0?'border-blue-300 bg-blue-50':index===1?'border-violet-300 bg-violet-50':index===2?'border-amber-300 bg-amber-50':'border-slate-300 bg-slate-50'}`}><span className="absolute -top-3 left-3 h-5 w-12 rounded-t-lg border border-b-0 border-current bg-inherit"/><span className="grid h-9 w-9 place-items-center rounded-xl bg-white shadow-sm text-slate-700">{index===0?<ListChecks size={16}/>:index===1?<PackageCheck size={16}/>:index===2?<FileCheck2 size={16}/>:<FolderLock size={16}/>}</span><p className="absolute bottom-4 left-3 text-[8px] font-black uppercase tracking-[.11em] text-slate-600">{folder}</p></div>)}</div><div className="mt-4"><HeroMetricGrid metrics={metrics.slice(0,4)}/></div></aside></div></section>
}
