'use client'
import { AlertTriangle, Boxes, Factory, RefreshCw, Rocket, ShieldCheck, Workflow } from 'lucide-react'
import type { SovereignHeroProps } from '../hero-types'
import { AngelCareHeroBrand, HeroActionRail, HeroAuthorityBadge, HeroExecutiveBrief, HeroMetricGrid, HeroTruthBadge, HeroWarning } from '../HeroPrimitives'
import styles from '../SovereignHeroes.module.css'

export default function ProductionHero({ state, posture, authority, summary, metrics = [], actions = [], freshness, warning }: SovereignHeroProps) {
  const lanes = ['Sources', 'Capacités', 'Queues', 'Contrôles']
  return <section className={`${styles.hero} min-h-[420px] bg-[linear-gradient(120deg,#071528_0%,#102953_44%,#124868_100%)] p-6 text-white sm:p-8 xl:p-10`} data-hero-surface="dark" data-hero-id="MZ22-HERO-02-PRODUCTION">
    <div className={`absolute inset-0 opacity-25 ${styles.fineGrid}`} /><div className={`${styles.redTriangle} right-2 top-8`} />
    <div className="relative grid gap-7 xl:grid-cols-[minmax(0,1fr)_520px] xl:items-center">
      <div><div className="flex flex-wrap gap-2"><HeroTruthBadge state={state}/><HeroAuthorityBadge inverted>{authority}</HeroAuthorityBadge><span className="rounded-full border border-white/15 bg-white/5 px-3 py-2 text-[9px] font-black uppercase tracking-[.12em] text-cyan-100">{posture}</span></div><div className="mt-5"><AngelCareHeroBrand inverted /></div><div className="mt-7 flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-[20px] border border-white/10 bg-white/10 text-cyan-200"><Factory size={27}/></span><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-cyan-200">Revenue Factory Atrium</p><h1 className="mt-1 text-4xl font-black tracking-[-.06em] sm:text-6xl">Production</h1></div></div><p className="mt-4 max-w-3xl text-sm font-semibold leading-7 text-slate-300">Gouverner la production, l’apprentissage, l’évaluation et la stabilisation runtime sans confondre une capacité saine avec une source dégradée.</p><div className="mt-6"><HeroExecutiveBrief dark>{summary}</HeroExecutiveBrief></div>{freshness ? <p className="mt-3 text-[9px] font-bold uppercase tracking-[.12em] text-slate-400">Fraîcheur · {freshness}</p> : null}<HeroWarning dark>{warning}</HeroWarning><div className="mt-5"><HeroActionRail actions={actions} dark /></div></div>
      <div className="relative rounded-[32px] border border-white/10 bg-slate-950/30 p-5 backdrop-blur-xl"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.16em] text-cyan-200">Production chambers</p><p className="mt-1 text-lg font-black">Chaîne industrielle contrôlée</p></div><Boxes className="text-cyan-200" size={23}/></div><div className="mt-5 grid grid-cols-4 gap-2">{lanes.map((lane,index)=><div key={lane} className="relative min-h-40 overflow-hidden rounded-[22px] border border-white/10 bg-white/[.055] p-3"><span className="text-[8px] font-black uppercase tracking-[.12em] text-slate-400">0{index+1}</span><div className="mt-4 space-y-2">{[0,1,2].map((row)=><span key={row} className={`block h-7 rounded-lg border ${index===1&&row===1?'border-amber-300/30 bg-amber-400/10':'border-cyan-300/10 bg-cyan-300/[.07]'}`}/>)}</div><p className="absolute bottom-3 left-3 text-[9px] font-black text-slate-200">{lane}</p></div>)}</div><div className="mt-4"><HeroMetricGrid metrics={metrics.slice(0,4)} dark /></div></div>
    </div>
  </section>
}
