import { createServiceClient } from '@/lib/supabase/server'
import type { MarketplaceRequestContext } from '../domain/types'
import { MarketplaceError } from '../server/errors'
import { getCustomerContext } from '../customer-commerce/customer-auth'
import { LIVE_CAPABILITIES,LIVE_PLACEMENTS,LIVE_PRESETS,LIVE_PURPOSES,LIVE_THEMES,SAFE_FALLBACK } from './registry'
import type { LiveCampaign,LiveKind,LiveLocale,LiveSourceSnapshot,LiveSummary,ResolvedLiveExperience } from './types'
type Row=Record<string,unknown>; type DbError={code?:string;message?:string}|null
const text=(v:unknown)=>typeof v==='string'?v:''
const num=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0
const bool=(v:unknown)=>v===true||v==='true'
const obj=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{}
const arr=(v:unknown):Row[]=>Array.isArray(v)?v.filter((x):x is Row=>Boolean(x)&&typeof x==='object'):[]
const missing=(e:DbError)=>e?.code==='42P01'||e?.code==='PGRST205'
function fail(operation:string,error:DbError){return new MarketplaceError(missing(error)?'CONFIGURATION_ERROR':'INTERNAL_ERROR',missing(error)?'La migration Live Experience Command doit être appliquée.':`Impossible de ${operation}.`,{cause:error||undefined})}
function actor(c:MarketplaceRequestContext){return c.actor.id}
function locale(v:unknown):LiveLocale{return v==='en'||v==='ar'?v:'fr'}
function deterministicBucket(seed:string){let hash=2166136261;for(let i=0;i<seed.length;i++){hash^=seed.charCodeAt(i);hash=Math.imul(hash,16777619)}return(hash>>>0)%10000}
function assignedVariant(experiment:Row,seed:string){const variants=arr(experiment.variants);if(!variants.length)return'';const weighted=variants.map((variant,index)=>({key:text(variant.key)||text(variant.variant_key)||String(index),weight:Math.max(0,num(variant.weight)||num(variant.allocation)||1)}));const total=weighted.reduce((sum,item)=>sum+item.weight,0)||weighted.length;let point=deterministicBucket(seed)/10000*total;for(const item of weighted){point-=item.weight;if(point<=0)return item.key}return weighted[weighted.length-1]?.key||''}
function mapCampaign(r:Row):LiveCampaign{return{id:text(r.id),campaign_key:text(r.campaign_key),name:text(r.name),kind:text(r.kind) as LiveKind,purpose_key:text(r.purpose_key),theme_key:text(r.theme_key),status:text(r.status) as LiveCampaign['status'],priority:num(r.priority),localized_content:obj(r.localized_content) as LiveCampaign['localized_content'],media:obj(r.media),placement:obj(r.placement),trigger:obj(r.trigger),targeting:obj(r.targeting),frequency:obj(r.frequency),schedule:obj(r.schedule),truth_source:obj(r.truth_source),conversion:obj(r.conversion),experiment_id:text(r.experiment_id)||null,starts_at:text(r.starts_at)||null,ends_at:text(r.ends_at)||null,version:num(r.version)||1,created_at:text(r.created_at),updated_at:text(r.updated_at)}}
function mapSource(r:Row):LiveSourceSnapshot{return{id:text(r.id),source_key:text(r.source_key),authority:text(r.authority),entity_type:text(r.entity_type),entity_id:text(r.entity_id)||null,payload:obj(r.payload),verified:bool(r.verified),observed_at:text(r.observed_at),expires_at:text(r.expires_at)||null,status:text(r.status)}}
async function tableRows(table:string,order='updated_at',limit=500){const db=await createServiceClient();const{data,error}=await db.from(table).select('*').order(order,{ascending:false}).limit(limit);if(error){if(missing(error))return[];throw fail(`charger ${table}`,error)}return(data||[]) as Row[]}
export async function liveExperienceSummary(_context:MarketplaceRequestContext):Promise<LiveSummary>{
 const [campaignRows,audienceRows,experimentRows,scheduleRows,sourceRows]=await Promise.all([tableRows('angelcare_marketplace_live_experience_campaigns'),tableRows('angelcare_marketplace_live_experience_audiences'),tableRows('angelcare_marketplace_live_experience_experiments'),tableRows('angelcare_marketplace_live_experience_schedules'),tableRows('angelcare_marketplace_live_experience_source_snapshots','observed_at')])
 const campaigns=campaignRows.map(mapCampaign);const sources=sourceRows.map(mapSource);const db=await createServiceClient();
 const analytics:Record<string,number>={impressions:0,interactions:0,conversions:0,dismissals:0};
 for(const [table,key] of [['angelcare_marketplace_live_experience_impressions','impressions'],['angelcare_marketplace_live_experience_interactions','interactions'],['angelcare_marketplace_live_experience_conversions','conversions']] as const){const{count,error}=await db.from(table).select('id',{count:'exact',head:true});if(!error)analytics[key]=count||0}
 const conflicts=campaigns.filter((c)=>c.status==='active').reduce((n,c,i,all)=>n+(all.some((x,j)=>j<i&&x.kind===c.kind&&text(x.placement.slot)===text(c.placement.slot)&&x.priority===c.priority)?1:0),0)
 return{...SAFE_FALLBACK,campaigns,purposes:[...LIVE_PURPOSES],themes:[...LIVE_THEMES],presets:[...LIVE_PRESETS],capabilities:[...LIVE_CAPABILITIES],placements:[...LIVE_PLACEMENTS],audiences:audienceRows,experiments:experimentRows,schedules:scheduleRows,sources,analytics,counts:{campaigns:campaigns.length,live:campaigns.filter(x=>x.status==='active').length,scheduled:campaigns.filter(x=>x.status==='scheduled').length,popups:campaigns.filter(x=>x.kind==='popup').length,broadcasts:campaigns.filter(x=>x.kind==='broadcast').length,proof:campaigns.filter(x=>x.kind==='proof').length,presets:LIVE_PRESETS.length,capabilities:LIVE_CAPABILITIES.length,conflicts}}
}
function validateCampaign(input:Record<string,unknown>){const kind=text(input.kind) as LiveKind;if(!['popup','broadcast','proof'].includes(kind))throw new MarketplaceError('VALIDATION_ERROR','Type d’expérience invalide.');const purpose=text(input.purpose_key||input.purposeKey);const theme=text(input.theme_key||input.themeKey);if(!LIVE_PURPOSES.some(x=>x.key===purpose&&x.kind===kind))throw new MarketplaceError('VALIDATION_ERROR','Purpose non reconnu.');if(!LIVE_THEMES.some(x=>x.key===theme&&x.kind===kind))throw new MarketplaceError('VALIDATION_ERROR','Thème non reconnu.');const content=obj(input.localized_content||input.localizedContent);if(!text(obj(content.fr).title))throw new MarketplaceError('VALIDATION_ERROR','Le titre français est requis.');if(kind==='proof'&&!text(obj(input.truth_source||input.truthSource).source_key))throw new MarketplaceError('VALIDATION_ERROR','Un widget de preuve exige une source canonique vérifiée.');return{kind,purpose,theme,content}}
export async function saveLiveCampaign(input:Record<string,unknown>,context:MarketplaceRequestContext):Promise<LiveCampaign>{
 const validation=validateCampaign(input),db=await createServiceClient(),id=text(input.id)||undefined,key=text(input.campaign_key||input.campaignKey)||`LXC-${Date.now()}`;
 let preservedStatus='draft',nextVersion=1,createdBy=actor(context),createdAt:undefined|string=undefined;
 if(id){const{data,error}=await db.from('angelcare_marketplace_live_experience_campaigns').select('status,version,created_by,created_at').eq('id',id).single();if(error||!data)throw fail('charger la campagne avant modification',error);preservedStatus=text(data.status)||'draft';nextVersion=Math.max(1,num(data.version)+1);createdBy=text(data.created_by)||actor(context);createdAt=text(data.created_at)||undefined}
 const payload={campaign_key:key,name:text(input.name)||text(obj(validation.content.fr).title),kind:validation.kind,purpose_key:validation.purpose,theme_key:validation.theme,status:preservedStatus,priority:Math.max(0,Math.min(999,num(input.priority)||100)),localized_content:validation.content,media:obj(input.media),placement:obj(input.placement),trigger:obj(input.trigger),targeting:obj(input.targeting),frequency:obj(input.frequency),schedule:obj(input.schedule),truth_source:obj(input.truth_source||input.truthSource),conversion:obj(input.conversion),experiment_id:text(input.experiment_id)||null,starts_at:text(input.starts_at)||null,ends_at:text(input.ends_at)||null,version:nextVersion,updated_by:actor(context),updated_at:new Date().toISOString()};
 let result;if(id)result=await db.from('angelcare_marketplace_live_experience_campaigns').update(payload).eq('id',id).select('*').single();else result=await db.from('angelcare_marketplace_live_experience_campaigns').insert({...payload,created_by:createdBy,created_at:createdAt}).select('*').single();if(result.error||!result.data)throw fail('enregistrer la campagne Live Experience',result.error);
 const record=mapCampaign(result.data as Row);await db.from('angelcare_marketplace_live_experience_versions').insert({campaign_id:record.id,version:record.version,snapshot:result.data,created_by:actor(context)});await audit(db,context,'campaign.saved',record.id,{status:record.status,kind:record.kind,version:record.version});return record
}
async function sourceForCampaign(db:any,campaign:LiveCampaign){const key=text(campaign.truth_source.source_key);if(!key)return null;const{data,error}=await db.from('angelcare_marketplace_live_experience_source_snapshots').select('*').eq('source_key',key).eq('verified',true).eq('status','active').order('observed_at',{ascending:false}).limit(1).maybeSingle();if(error&&!missing(error))throw fail('charger la preuve canonique',error);if(!data)return null;const source=mapSource(data as Row);if(source.expires_at&&new Date(source.expires_at).getTime()<=Date.now())return null;return source}
function validatePublish(campaign:LiveCampaign){
 for(const localeKey of ['fr','en','ar']){const content=obj(campaign.localized_content[localeKey]);if(!text(content.title)||!text(content.message))throw new MarketplaceError('VALIDATION_ERROR',`Le contenu ${localeKey.toUpperCase()} doit être complet avant publication.`);const href=text(content.cta_href);if(href&&!href.startsWith('/')&&!href.startsWith('https://')&&!href.startsWith('mailto:'))throw new MarketplaceError('VALIDATION_ERROR',`Le lien CTA ${localeKey.toUpperCase()} n’est pas autorisé.`)}
 if(campaign.starts_at&&campaign.ends_at&&new Date(campaign.starts_at)>=new Date(campaign.ends_at))throw new MarketplaceError('VALIDATION_ERROR','La fin de campagne doit être postérieure au début.');
 if((campaign.purpose_key.includes('countdown')||campaign.purpose_key.includes('urgency'))&&!campaign.ends_at)throw new MarketplaceError('VALIDATION_ERROR','Cette expérience exige une date de fin persistante.');
 if(num(campaign.frequency.per_session)<=0)throw new MarketplaceError('VALIDATION_ERROR','La fréquence par session doit être supérieure à zéro.');
}
export async function liveCampaignAction(id:string,action:string,context:MarketplaceRequestContext){const db=await createServiceClient();const{data,error}=await db.from('angelcare_marketplace_live_experience_campaigns').select('*').eq('id',id).single();if(error||!data)throw fail('charger la campagne',error);const campaign=mapCampaign(data as Row);if(action==='duplicate'){const clone={...(data as Row),id:undefined,campaign_key:`${campaign.campaign_key}-COPY-${Date.now()}`,name:`${campaign.name} — Copie`,status:'draft',version:1,created_by:actor(context),updated_by:actor(context),created_at:undefined,updated_at:new Date().toISOString()};const{data:created,error:createError}=await db.from('angelcare_marketplace_live_experience_campaigns').insert(clone).select('*').single();if(createError||!created)throw fail('dupliquer la campagne',createError);return{record:mapCampaign(created as Row)}}
 const transitions:Record<string,string>={activate:'active',publish:'active',schedule:'scheduled',suspend:'suspended',resume:'active',archive:'archived',expire:'expired'};const next=transitions[action];if(!next)throw new MarketplaceError('VALIDATION_ERROR','Action de campagne non supportée.');if(next==='active'||next==='scheduled')validatePublish(campaign);if((next==='active'||next==='scheduled')&&campaign.kind==='proof'&&!await sourceForCampaign(db,campaign))throw new MarketplaceError('DEPENDENCY_BLOCKED','La preuve canonique est absente, non vérifiée ou expirée. Le widget reste masqué.');const{data:updated,error:updateError}=await db.from('angelcare_marketplace_live_experience_campaigns').update({status:next,version:campaign.version+1,updated_by:actor(context),updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(updateError||!updated)throw fail('modifier le statut de campagne',updateError);await db.from('angelcare_marketplace_live_experience_versions').insert({campaign_id:id,version:campaign.version+1,snapshot:updated,created_by:actor(context)});await audit(db,context,`campaign.${action}`,id,{from:campaign.status,to:next});return{record:mapCampaign(updated as Row)}}
async function audit(db:any,context:MarketplaceRequestContext,action:string,objectId:string,evidence:Record<string,unknown>){await db.from('angelcare_marketplace_live_experience_audit_events').insert({actor_id:actor(context),action,object_type:'live_experience_campaign',object_id:objectId,evidence})}
function matches(c:LiveCampaign,ctx:Record<string,unknown>){const reasons:string[]=[];const t=c.targeting,pathname=text(ctx.pathname),device=text(ctx.device),audience=text(ctx.audience),localeKey=text(ctx.locale),territory=text(ctx.territoryId),walletMember=bool(ctx.walletMember),walletTier=text(ctx.walletTier);const routes=Array.isArray(t.routes)?t.routes.map(String):[];if(routes.length&&!routes.some(x=>pathname.startsWith(x)))reasons.push('route');const devices=Array.isArray(t.devices)?t.devices.map(String):[];if(devices.length&&!devices.includes(device))reasons.push('device');const audiences=Array.isArray(t.audiences)?t.audiences.map(String):[];if(audiences.length&&!audiences.includes(audience))reasons.push('audience');const locales=Array.isArray(t.locales)?t.locales.map(String):[];if(locales.length&&!locales.includes(localeKey))reasons.push('locale');const territories=Array.isArray(t.territories)?t.territories.map(String):[];if(territories.length&&!territories.includes(territory))reasons.push('territory');if(t.wallet_member===true&&!walletMember)reasons.push('wallet_member');if(text(t.wallet_tier)&&text(t.wallet_tier)!==walletTier)reasons.push('wallet_tier');return{eligible:reasons.length===0,reasons}}
export async function simulateLiveExperience(input:Record<string,unknown>){const campaign=input.campaign as LiveCampaign|undefined;if(!campaign)throw new MarketplaceError('VALIDATION_ERROR','Campagne requise pour la simulation.');const evaluation=matches(campaign,obj(input.context));const source=campaign.kind==='proof'?await sourceForCampaign(await createServiceClient(),campaign):null;return{eligible:evaluation.eligible&&(campaign.kind!=='proof'||Boolean(source)),reasons:[...evaluation.reasons,...(campaign.kind==='proof'&&!source?['truth_source_unavailable']:[])],source,normal_price:num(obj(input.context).normalPrice),wallet_price:num(obj(input.context).walletPrice),preview:{purpose:campaign.purpose_key,theme:campaign.theme_key,placement:campaign.placement}}}
async function publicContext(input:Record<string,unknown>){const customer=await getCustomerContext().catch(()=>null);let walletMember=false,walletTier='',walletBalance=0;if(customer){const db=await createServiceClient();const{data}=await db.from('angelcare_marketplace_wallet_accounts').select('id,status,buckets:angelcare_marketplace_wallet_balance_buckets(*),membership:angelcare_marketplace_wallet_memberships(*,tier:angelcare_marketplace_wallet_tiers(*))').eq('customer_account_id',customer.account.id).maybeSingle();if(data){walletMember=text(data.status)==='active';walletBalance=arr(data.buckets).reduce((s,r)=>s+num(r.available_amount),0);const membership=arr(data.membership)[0];walletTier=text(obj(membership?.tier).tier_key)||text(membership?.tier_key)}}return{...input,locale:locale(input.locale),audience:customer?(customer.account.account_kind==='organization'?'organization':'family'):'anonymous',authenticated:Boolean(customer),customerAccountId:customer?.account.id||null,territoryId:customer?.account.territory_id||text(input.territoryId),walletMember,walletTier,walletBalance}}
export async function resolveLiveExperiences(input:Record<string,unknown>):Promise<{experiences:ResolvedLiveExperience[];context:Record<string,unknown>;generatedAt:string}>{
 const db=await createServiceClient(),ctx=await publicContext(input),now=new Date().toISOString();
 const[campaignResult,experimentResult]=await Promise.all([
  db.from('angelcare_marketplace_live_experience_campaigns').select('*').eq('status','active').or(`starts_at.is.null,starts_at.lte.${now}`).or(`ends_at.is.null,ends_at.gt.${now}`).order('priority',{ascending:false}).limit(100),
  db.from('angelcare_marketplace_live_experience_experiments').select('*').eq('status','active').limit(100),
 ]);
 if(campaignResult.error){if(missing(campaignResult.error))return{experiences:[],context:ctx,generatedAt:now};throw fail('résoudre les expériences publiques',campaignResult.error)}
 const experiments=new Map(((experimentResult.data||[]) as Row[]).map(row=>[text(row.id),row]));
 const resolved:ResolvedLiveExperience[]=[];
 for(const row of (campaignResult.data||[]) as Row[]){
  const c=mapCampaign(row),evaluation=matches(c,ctx);if(!evaluation.eligible)continue;
  let experimentVariant='';
  if(c.experiment_id){const experiment=experiments.get(c.experiment_id);if(!experiment)continue;const seed=`${text(ctx.customerAccountId)||text(input.sessionKey)||'anonymous'}:${c.experiment_id}`;experimentVariant=assignedVariant(experiment,seed);const required=text(c.conversion.experiment_variant);if(required&&required!==experimentVariant)continue}
  const source=c.kind==='proof'?await sourceForCampaign(db,c):null;if(c.kind==='proof'&&!source)continue;
  const theme=LIVE_THEMES.find(x=>x.key===c.theme_key),localizedContent=obj(c.localized_content[text(ctx.locale)]),content=(Object.keys(localizedContent).length?localizedContent:obj(c.localized_content.fr)) as Record<string,string>;
  resolved.push({id:c.id,campaignKey:c.campaign_key,kind:c.kind,purposeKey:c.purpose_key,themeKey:c.theme_key,content,media:c.media,tokens:theme?.tokens||{},placement:c.placement,trigger:c.trigger,frequency:c.frequency,conversion:{...c.conversion,experiment_id:c.experiment_id,experiment_variant:experimentVariant},truth:source?source.payload:null,startsAt:c.starts_at,endsAt:c.ends_at,priority:c.priority})
 }
 const selected=[...resolved.filter(x=>x.kind==='broadcast').slice(0,3),...resolved.filter(x=>x.kind==='popup').slice(0,1),...resolved.filter(x=>x.kind==='proof').slice(0,3)];
 const safeContext={locale:ctx.locale,audience:ctx.audience,authenticated:ctx.authenticated,territoryId:ctx.territoryId,walletMember:ctx.walletMember,walletTier:ctx.walletTier,device:text(input.device)};return{experiences:selected,context:safeContext,generatedAt:now}
}
export async function recordLiveInteraction(input:Record<string,unknown>,request:Request){
 const db=await createServiceClient(),type=text(input.event_type||input.eventType),allowed=new Set(['impression','view','click','dismiss','expand','collapse','form_start','form_complete','conversion']);if(!allowed.has(type))throw new MarketplaceError('VALIDATION_ERROR','Événement Live Experience non autorisé.');
 const campaignId=text(input.campaign_id||input.campaignId),sessionKey=text(input.session_key||input.sessionKey).slice(0,160);if(!campaignId||!sessionKey)throw new MarketplaceError('VALIDATION_ERROR','Campagne et session sont requises.');
 const{data:campaign,error:campaignError}=await db.from('angelcare_marketplace_live_experience_campaigns').select('id,status').eq('id',campaignId).maybeSingle();if(campaignError||!campaign||text(campaign.status)!=='active')throw new MarketplaceError('VALIDATION_ERROR','La campagne n’est pas active.');
 const table=type==='impression'?'angelcare_marketplace_live_experience_impressions':type==='conversion'?'angelcare_marketplace_live_experience_conversions':'angelcare_marketplace_live_experience_interactions',since=new Date(Date.now()-60000).toISOString();const{count}=await db.from(table).select('id',{count:'exact',head:true}).eq('session_key',sessionKey).gte('created_at',since);if((count||0)>=90)throw new MarketplaceError('RATE_LIMITED','Trop d’événements Live Experience pour cette session.');
 const customer=await getCustomerContext().catch(()=>null),metadata=obj(input.metadata);if(JSON.stringify(metadata).length>12000)throw new MarketplaceError('VALIDATION_ERROR','Métadonnées trop volumineuses.');
 const payload={campaign_id:campaignId,event_type:type,session_key:sessionKey,customer_account_id:customer?.account.id||null,pathname:text(input.pathname).slice(0,500)||'/',locale:locale(input.locale),device_class:text(input.device_class||input.deviceClass).slice(0,30)||'unknown',metadata,ip_hash:null,user_agent:text(request.headers.get('user-agent')).slice(0,500),created_at:new Date().toISOString()};const{error}=await db.from(table).insert(payload);if(error&&!missing(error))throw fail('enregistrer l’interaction',error);return{recorded:!error}
}
export async function refreshCanonicalSource(input:Record<string,unknown>,context:MarketplaceRequestContext){const authority=text(input.authority),entityId=text(input.entity_id||input.entityId),sourceKey=text(input.source_key||input.sourceKey);if(!sourceKey||!authority||!entityId)throw new MarketplaceError('VALIDATION_ERROR','Source, autorité et entité sont requises.');const db=await createServiceClient();let payload:Record<string,unknown>={},entityType=authority,ttl=300;
 if(authority==='catalog_item'){const{data,error}=await db.from('angelcare_marketplace_catalog_items').select('id,item_key,slug,kind,name_fr,name_en,name_ar,status,price_mode,price_amount,currency_label,availability_status,updated_at').eq('id',entityId).maybeSingle();if(error||!data)throw fail('charger le produit canonique',error);payload=data as Row;ttl=300}
 else if(authority==='catalog_availability'){const{data,error}=await db.from('angelcare_marketplace_catalog_availability').select('*').eq('catalog_item_id',entityId);if(error)throw fail('charger la disponibilité canonique',error);const rows=(data||[]) as Row[];payload={available:rows.some(r=>bool(r.available)),capacity_limit:rows.reduce((s,r)=>s+num(r.capacity_limit),0),territories:rows.map(r=>r.territory_id),observations:rows};ttl=120}
 else if(authority==='academy_cohort'){const{data,error}=await db.from('angelcare_marketplace_academy_cohorts').select('id,public_reference,name,status,capacity,enrolled_count,waitlist_count,starts_at,ends_at,enrollment_opens_at,enrollment_closes_at,updated_at').eq('id',entityId).maybeSingle();if(error||!data)throw fail('charger la cohorte canonique',error);payload={...data,remaining_seats:Math.max(0,num(data.capacity)-num(data.enrolled_count))};ttl=60}
 else if(authority==='wallet_policy'){const{data,error}=await db.from('angelcare_marketplace_wallet_policies').select('id,policy_key,name_fr,name_en,name_ar,status,benefits,conditions,starts_at,ends_at,updated_at').eq('id',entityId).maybeSingle();if(error||!data)throw fail('charger la politique Wallet canonique',error);payload=data as Row;ttl=60}
 else if(authority==='trust_badge'){const{data,error}=await db.from('angelcare_marketplace_trust_badge_issuances').select('*').eq('id',entityId).maybeSingle();if(error||!data)throw fail('charger la preuve Trust canonique',error);payload=data as Row;ttl=900}
 else throw new MarketplaceError('VALIDATION_ERROR','Adaptateur de source canonique non supporté.');const observed=new Date(),expires=new Date(observed.getTime()+ttl*1000);const{data,error}=await db.from('angelcare_marketplace_live_experience_source_snapshots').upsert({source_key:sourceKey,authority,entity_type:entityType,entity_id:entityId,payload,verified:true,observed_at:observed.toISOString(),expires_at:expires.toISOString(),status:'active',refreshed_by:actor(context),updated_at:observed.toISOString()},{onConflict:'source_key'}).select('*').single();if(error||!data)throw fail('enregistrer la preuve canonique',error);await audit(db,context,'source.refreshed',String(data.id),{authority,entityId,sourceKey});return mapSource(data as Row)}

export type LiveGovernanceMode='audiences'|'placements'|'schedules'|'experiments'|'history'|'settings'
const GOVERNANCE_TABLE:Record<Exclude<LiveGovernanceMode,'history'>,string>={audiences:'angelcare_marketplace_live_experience_audiences',placements:'angelcare_marketplace_live_experience_placements',schedules:'angelcare_marketplace_live_experience_schedules',experiments:'angelcare_marketplace_live_experience_experiments',settings:'angelcare_marketplace_live_experience_capabilities'}
const GOVERNANCE_TRANSITIONS:Record<Exclude<LiveGovernanceMode,'history'>,Record<string,string[]>>={
 audiences:{draft:['review','active','archived'],review:['active','draft','archived'],active:['paused','archived'],paused:['active','archived'],archived:[]},
 placements:{draft:['review','active','archived'],review:['active','draft','archived'],active:['paused','archived'],paused:['active','archived'],archived:[]},
 schedules:{draft:['scheduled','cancelled'],scheduled:['active','paused','cancelled'],active:['paused','completed','cancelled'],paused:['active','cancelled'],completed:['archived'],cancelled:['archived'],archived:[]},
 experiments:{draft:['ready','closed'],ready:['running','draft','closed'],running:['paused','significance_review','closed'],paused:['running','significance_review','closed'],significance_review:['winner','running','closed'],winner:['closed'],closed:[]},
 settings:{active:['inactive'],inactive:['active']},
}
function governanceLabel(mode:LiveGovernanceMode,row:Row){return text(row.name)||text(row.label)||text(row.audience_key)||text(row.placement_key)||text(row.schedule_key)||text(row.experiment_key)||text(row.capability_key)||text(row.id)}
export async function listLiveGovernance(mode:LiveGovernanceMode,context:MarketplaceRequestContext){
 if(mode==='history'){const db=await createServiceClient();const[versions,audits]=await Promise.all([db.from('angelcare_marketplace_live_experience_versions').select('*').order('created_at',{ascending:false}).limit(250),db.from('angelcare_marketplace_live_experience_audit_events').select('*').order('created_at',{ascending:false}).limit(250)]);if(versions.error)throw fail('charger les versions Live Experience',versions.error);if(audits.error)throw fail('charger l’audit Live Experience',audits.error);return{rows:[...((versions.data||[]) as Row[]).map(r=>({...r,record_type:'version'})),...((audits.data||[]) as Row[]).map(r=>({...r,record_type:'audit'}))],mode,actor:context.actor.displayName}}
 const rows=await tableRows(GOVERNANCE_TABLE[mode],mode==='settings'?'created_at':'updated_at',500);return{rows,mode,actor:context.actor.displayName}
}
export async function saveLiveGovernance(mode:Exclude<LiveGovernanceMode,'history'>,input:Row,context:MarketplaceRequestContext){const db=await createServiceClient(),id=text(input.id)||undefined,now=new Date().toISOString();let payload:Row
 if(mode==='audiences'){const key=text(input.audience_key||input.key),name=text(input.name);if(!key||!name)throw new MarketplaceError('VALIDATION_ERROR','Clé audience et nom sont requis.');payload={audience_key:key,name,audience_type:text(input.audience_type)||'dynamic',definition:obj(input.definition),status:text(input.status)||'draft',updated_by:actor(context),updated_at:now};if(!id)payload.created_by=actor(context)}
 else if(mode==='placements'){const key=text(input.placement_key||input.key),label=text(input.label||input.name),family=text(input.family);if(!key||!label||!family)throw new MarketplaceError('VALIDATION_ERROR','Clé, label et famille du placement sont requis.');payload={placement_key:key,label,family,configuration:obj(input.configuration),status:text(input.status)||'draft'} }
 else if(mode==='schedules'){const key=text(input.schedule_key||input.key),campaignId=text(input.campaign_id||input.campaignId),starts=text(input.starts_at||input.startsAt)||null,ends=text(input.ends_at||input.endsAt)||null;if(!key||!campaignId)throw new MarketplaceError('VALIDATION_ERROR','Clé schedule et campagne sont requises.');if(starts&&ends&&new Date(ends)<=new Date(starts))throw new MarketplaceError('VALIDATION_ERROR','La fin du schedule doit suivre le début.');const{data:existing,error:e}=await db.from('angelcare_marketplace_live_experience_schedules').select('id,starts_at,ends_at,status').eq('campaign_id',campaignId).in('status',['scheduled','active']);if(e)throw fail('contrôler les conflits schedule',e);const conflict=((existing||[]) as Row[]).some(r=>String(r.id)!==id&&(!ends||!r.starts_at||new Date(String(r.starts_at))<new Date(ends))&&(!r.ends_at||!starts||new Date(String(r.ends_at))>new Date(starts)));if(conflict)throw new MarketplaceError('CONFLICT','Une programmation active de cette campagne chevauche cette fenêtre.');payload={schedule_key:key,campaign_id:campaignId,starts_at:starts,ends_at:ends,timezone:text(input.timezone)||'Africa/Casablanca',recurrence:obj(input.recurrence),status:text(input.status)||'scheduled',execution_evidence:obj(input.execution_evidence||input.executionEvidence),updated_at:now};if(!id)payload.created_by=actor(context)}
 else if(mode==='experiments'){const key=text(input.experiment_key||input.key),name=text(input.name);if(!key||!name)throw new MarketplaceError('VALIDATION_ERROR','Clé experiment et nom sont requis.');const variants=Array.isArray(input.variants)?input.variants:[];if(variants.length<2)throw new MarketplaceError('VALIDATION_ERROR','Une expérimentation exige au moins deux variantes.');payload={experiment_key:key,name,status:text(input.status)||'draft',objective:text(input.objective)||'conversion',allocation:obj(input.allocation),variants,control_variant:text(input.control_variant||input.controlVariant)||null,starts_at:text(input.starts_at||input.startsAt)||null,ends_at:text(input.ends_at||input.endsAt)||null,winner_variant:text(input.winner_variant||input.winnerVariant)||null,evidence:obj(input.evidence),updated_by:actor(context),updated_at:now};if(!id)payload.created_by=actor(context)}
 else {const key=text(input.capability_key||input.key),kind=text(input.kind),description=text(input.description);if(!key||!kind||!description)throw new MarketplaceError('VALIDATION_ERROR','Clé, type et description capability sont requis.');payload={capability_key:key,kind,description,status:text(input.status)||'active'}}
 const table=GOVERNANCE_TABLE[mode];const result=id?await db.from(table).update(payload).eq('id',id).select('*').single():await db.from(table).insert(payload).select('*').single();if(result.error||!result.data)throw fail(`enregistrer ${mode}`,result.error);await audit(db,context,`${mode}.saved`,String(result.data.id),{mode,label:governanceLabel(mode,result.data as Row),status:text((result.data as Row).status)});return result.data as Row}
export async function transitionLiveGovernance(mode:Exclude<LiveGovernanceMode,'history'>,id:string,next:string,reason:string,context:MarketplaceRequestContext){const db=await createServiceClient(),table=GOVERNANCE_TABLE[mode];const{data:current,error:e}=await db.from(table).select('*').eq('id',id).maybeSingle();if(e||!current)throw new MarketplaceError('NOT_FOUND',`${mode} introuvable.`,{cause:e||undefined});const from=text(current.status)||'draft';if(!GOVERNANCE_TRANSITIONS[mode][from]?.includes(next))throw new MarketplaceError('VALIDATION_ERROR',`Transition ${mode} interdite: ${from} → ${next}.`);const patch:Row={status:next};if('updated_at' in current)patch.updated_at=new Date().toISOString();if(mode==='experiments'&&next==='winner'&&!text(current.winner_variant))throw new MarketplaceError('NOT_READY','Le gagnant doit être défini avant la décision winner.');const{data,error}=await db.from(table).update(patch).eq('id',id).select('*').single();if(error||!data)throw fail(`transitionner ${mode}`,error);await audit(db,context,`${mode}.${next}`,id,{from,to:next,reason,label:governanceLabel(mode,data as Row)});return data as Row}
