// Generated from the canonical paid Supabase production schema captured 2026-08-15.
// DO NOT derive this runtime compatibility contract from repository migrations.

export const CANONICAL_TABLE_COLUMNS = {
  "ac_capital_command_results": [
    "id",
    "command_key",
    "workspace_key",
    "actor",
    "request_id",
    "status",
    "summary",
    "records_created",
    "records_updated",
    "events_emitted",
    "warnings",
    "errors",
    "result_snapshot",
    "started_at",
    "completed_at",
    "created_at"
  ],
  "ac_whatsapp_stop_list": [
    "id",
    "whatsapp_id",
    "phone_number_e164",
    "reason",
    "scope",
    "active",
    "created_by",
    "created_at",
    "revoked_by",
    "revoked_at"
  ],
  "academy_alerts": [
    "id",
    "title",
    "message",
    "severity",
    "status",
    "due_at",
    "related_trainee_id",
    "created_at"
  ],
  "academy_notification_queue": [
    "id",
    "channel",
    "target",
    "title",
    "message",
    "status",
    "payload",
    "sent_at",
    "created_at",
    "entity_id",
    "entity_type",
    "trainee_id",
    "enrollment_id",
    "recipient",
    "subject",
    "body",
    "metadata",
    "updated_at"
  ],
  "academy_partners": [
    "id",
    "name",
    "type",
    "city",
    "contact_name",
    "phone",
    "email",
    "status",
    "notes",
    "created_at",
    "placement_capacity"
  ],
  "academy_placement_cases": [
    "id",
    "ref_code",
    "trainee_id",
    "program_id",
    "cohort_id",
    "partner_id",
    "status",
    "priority",
    "target_city",
    "preferred_role",
    "availability",
    "advisor_name",
    "match_score",
    "trainings_passed",
    "spoken_languages",
    "additional_skills",
    "attachments",
    "notes",
    "metadata",
    "created_at",
    "updated_at"
  ],
  "academy_trainer_assignments": [
    "id",
    "trainer_id",
    "trainer_name",
    "assignment_reference",
    "program_id",
    "program_title",
    "cohort_id",
    "cohort_title",
    "title",
    "location",
    "delivery_mode",
    "status",
    "priority",
    "starts_at",
    "ends_at",
    "load_hours",
    "notes",
    "created_at",
    "updated_at"
  ],
  "ai_provider_usage_ledger": [
    "id",
    "occurred_at",
    "module_key",
    "capability",
    "dossier_id",
    "capacity_pool_id",
    "credential_id",
    "reservation_id",
    "model_code",
    "request_count",
    "grounded_request_count",
    "input_tokens",
    "output_tokens",
    "total_tokens",
    "latency_ms",
    "http_status",
    "outcome",
    "error_code",
    "estimated_cost_usd",
    "actor_id",
    "mission_id",
    "command_code",
    "metadata"
  ],
  "angelcare_marketplace_command_idempotency": [
    "id",
    "scope",
    "idempotency_key",
    "actor_id",
    "request_hash",
    "status",
    "result",
    "created_at",
    "completed_at",
    "expires_at"
  ],
  "app_users": [
    "id",
    "full_name",
    "username",
    "password_hash",
    "role",
    "status",
    "language",
    "phone",
    "email",
    "department",
    "job_title",
    "created_by",
    "last_login_at",
    "must_change_password",
    "created_at",
    "updated_at",
    "permissions",
    "profile_photo_path",
    "tenant_id",
    "organization_id"
  ],
  "audit_change_logs": [
    "id",
    "organization_id",
    "user_id",
    "table_name",
    "record_id",
    "operation",
    "old_values",
    "new_values",
    "changed_at",
    "reason"
  ],
  "audit_security_logs": [
    "id",
    "organization_id",
    "user_id",
    "action",
    "target_type",
    "target_id",
    "ip_address",
    "user_agent",
    "risk_level",
    "details",
    "created_at"
  ],
  "auto_events": [
    "id",
    "event_type",
    "organization_id",
    "site_id",
    "actor_user_id",
    "source_type",
    "source_id",
    "payload",
    "created_at",
    "processed_at",
    "status"
  ],
  "b2b_automation_rules": [
    "id",
    "name",
    "trigger_key",
    "conditions",
    "actions",
    "is_active",
    "created_by",
    "created_at",
    "updated_at"
  ],
  "b2b_campaign_prospects": [
    "id",
    "campaign_id",
    "prospect_id",
    "status",
    "sequence_step",
    "last_action_at",
    "next_action_at",
    "outcome",
    "created_at"
  ],
  "b2b_campaigns": [
    "id",
    "name",
    "objective",
    "segment",
    "channel_mix",
    "status",
    "owner_id",
    "target_count",
    "contacted_count",
    "positive_reply_count",
    "meeting_booked_count",
    "proposal_created_count",
    "signed_partner_count",
    "start_at",
    "end_at",
    "notes",
    "created_by",
    "updated_by",
    "created_at",
    "updated_at",
    "archived_at"
  ],
  "b2b_config_items": [
    "id",
    "config_group",
    "config_key",
    "label",
    "value",
    "description",
    "sort_order",
    "is_active",
    "created_by",
    "updated_by",
    "created_at",
    "updated_at",
    "group_key",
    "item_key"
  ],
  "b2b_direct_actions": [
    "id",
    "prospect_id",
    "contact_id",
    "actor_id",
    "action_channel",
    "action_title",
    "template_id",
    "recipient_name",
    "recipient_phone",
    "recipient_email",
    "subject",
    "message_body",
    "outcome",
    "next_follow_up_at",
    "created_task_id",
    "metadata",
    "created_at"
  ],
  "b2b_partner_programs": [
    "id",
    "name",
    "sector_focus",
    "description",
    "services",
    "value_proposition",
    "pricing_models",
    "is_active",
    "created_by",
    "updated_by",
    "created_at",
    "updated_at"
  ],
  "b2b_prospects": [
    "id",
    "name",
    "sector",
    "sub_sector",
    "city",
    "address",
    "website",
    "instagram",
    "linkedin",
    "google_maps_url",
    "phone",
    "email",
    "main_contact_name",
    "main_contact_role",
    "decision_maker_name",
    "decision_maker_role",
    "decision_maker_phone",
    "decision_maker_email",
    "status",
    "priority_score",
    "fit_score",
    "urgency_score",
    "decision_power_score",
    "revenue_potential_score",
    "relationship_warmth",
    "potential_service_fit",
    "current_family_services",
    "pain_points",
    "opportunity_description",
    "estimated_monthly_value",
    "estimated_annual_value",
    "assigned_owner_id",
    "created_by",
    "updated_by",
    "last_contact_at",
    "next_follow_up_at",
    "next_action",
    "loss_reason",
    "not_fit_reason",
    "created_at",
    "updated_at",
    "archived_at",
    "campaign_source",
    "acquisition_source",
    "qualification_score",
    "lifecycle_segment",
    "executive_score",
    "health_status",
    "risk_flags",
    "recommended_next_action",
    "last_quality_review_at",
    "phones",
    "emails",
    "contacts_summary"
  ],
  "b2b_reports": [
    "id",
    "report_type",
    "period_start",
    "period_end",
    "owner_id",
    "metrics",
    "summary",
    "best_opportunities",
    "objections",
    "support_needed",
    "next_week_plan",
    "created_at"
  ],
  "b2b_sequences": [
    "id",
    "name",
    "segment",
    "objective",
    "is_active",
    "created_by",
    "updated_by",
    "created_at",
    "updated_at"
  ],
  "bd_automation_logs": [
    "id",
    "rule_id",
    "entity_type",
    "entity_id",
    "result",
    "created_at"
  ],
  "bd_tasks": [
    "id",
    "title",
    "description",
    "status",
    "assigned_to",
    "related_type",
    "related_id",
    "due_at",
    "created_at",
    "priority",
    "owner_id",
    "planned_start_at",
    "planned_end_at",
    "actual_start_at",
    "actual_end_at",
    "updated_at",
    "reviewer_id",
    "escalation_level",
    "manager_note",
    "completion_note",
    "blocker",
    "timer_started_at",
    "total_focus_seconds",
    "auto_generated",
    "outcome",
    "outcome_note",
    "blocked_at",
    "snoozed_until",
    "escalation_reason",
    "converted_followup_id",
    "linked_id",
    "linked_type",
    "start_at",
    "data",
    "display",
    "error",
    "escalated",
    "followup_id",
    "gap",
    "gridtemplatecolumns",
    "href",
    "label",
    "value"
  ],
  "caregiver_checkins": [
    "id",
    "caregiver_id",
    "mission_id",
    "city",
    "zone",
    "event_type",
    "event_time",
    "notes"
  ],
  "carelink_mission_action_logs": [
    "id",
    "action_type",
    "source_type",
    "source_id",
    "dossier_id",
    "mission_code",
    "actor_name",
    "payload",
    "created_at",
    "mission_id"
  ],
  "carelink_mission_notifications": [
    "id",
    "audience_type",
    "caregiver_id",
    "caregiver_name",
    "title",
    "body",
    "action_type",
    "source_type",
    "source_id",
    "workflow_state_id",
    "priority",
    "delivery_status",
    "is_read",
    "payload",
    "created_by",
    "created_at",
    "read_at",
    "mission_id"
  ],
  "connect_action_assignees": [
    "id",
    "action_id",
    "user_id",
    "assigned_by",
    "assigned_at",
    "completed_at"
  ],
  "core_organizations": [
    "id",
    "name",
    "legal_name",
    "organization_type",
    "status",
    "country_code",
    "city",
    "region",
    "currency_code",
    "timezone",
    "preferred_language",
    "school_year_start_month",
    "school_year_end_month",
    "primary_contact_name",
    "primary_contact_email",
    "primary_contact_phone",
    "billing_email",
    "commercial_owner_id",
    "academy_owner_id",
    "created_by",
    "updated_by",
    "created_at",
    "updated_at",
    "metadata",
    "stage"
  ],
  "email_audit_logs": [
    "id",
    "message_id",
    "actor_user_id",
    "action",
    "payload",
    "ip_address",
    "created_at",
    "thread_id",
    "actor"
  ],
  "email_messages": [
    "id",
    "account_id",
    "thread_id",
    "direction",
    "status",
    "subject",
    "body_html",
    "body_text",
    "from_email",
    "from_name",
    "to_email",
    "to_name",
    "cc",
    "bcc",
    "message_id_header",
    "in_reply_to",
    "business_context",
    "priority",
    "approval_required",
    "template_key",
    "assigned_to",
    "family_id",
    "caregiver_id",
    "lead_id",
    "contract_id",
    "mission_id",
    "invoice_id",
    "incident_id",
    "partner_id",
    "academy_trainee_id",
    "hr_staff_id",
    "sent_at",
    "received_at",
    "metadata",
    "created_at",
    "updated_at",
    "reply_to_message_id",
    "provider_message_id",
    "linked_entity_type",
    "linked_entity_id",
    "scheduled_at",
    "failed_at",
    "failure_reason",
    "classification",
    "variables",
    "attachments",
    "tags",
    "created_by",
    "mailbox_id",
    "to_emails",
    "cc_emails",
    "bcc_emails",
    "html_body",
    "text_body",
    "thread_key",
    "delivery_status",
    "last_delivery_attempt_at",
    "email_account_id",
    "has_attachments",
    "snippet",
    "external_message_id",
    "references_header"
  ],
  "email_os_core_access_audit": [
    "id",
    "principal_type",
    "principal_id",
    "action",
    "mailbox_id",
    "decision",
    "reason",
    "created_at"
  ],
  "email_os_core_attachments": [
    "id",
    "thread_id",
    "draft_id",
    "file_name",
    "mime_type",
    "size_bytes",
    "storage_path",
    "status",
    "created_at"
  ],
  "email_os_core_inbox": [
    "id",
    "mailbox_id",
    "provider_uid",
    "subject",
    "from_email",
    "to_email",
    "preview",
    "status",
    "raw",
    "created_at",
    "updated_at",
    "read_at",
    "starred",
    "starred_at",
    "tag",
    "label",
    "folder",
    "archived_at",
    "deleted_at",
    "spam_at",
    "permanently_deleted_at",
    "ingest_key"
  ],
  "email_os_core_provider_logs": [
    "id",
    "provider",
    "action",
    "status",
    "message",
    "metadata",
    "created_at"
  ],
  "email_os_message_assignments": [
    "id",
    "mailbox_id",
    "message_id",
    "external_id",
    "thread_id",
    "owner_user_id",
    "assigned_by",
    "assigned_at",
    "unassigned_at",
    "metadata_json",
    "created_at",
    "updated_at",
    "assignee_name_snapshot",
    "assignee_email_snapshot",
    "assignee_role_snapshot",
    "assignee_department_snapshot",
    "assignee_title_snapshot",
    "assigned_by_name_snapshot",
    "assigned_by_email_snapshot",
    "assigned_by_role_snapshot",
    "assigned_by_department_snapshot",
    "assigned_by_title_snapshot"
  ],
  "email_threads": [
    "id",
    "thread_key",
    "subject",
    "business_context",
    "priority",
    "status",
    "assigned_to",
    "family_id",
    "caregiver_id",
    "lead_id",
    "contract_id",
    "mission_id",
    "invoice_id",
    "incident_id",
    "partner_id",
    "academy_trainee_id",
    "hr_staff_id",
    "last_message_at",
    "metadata",
    "created_at",
    "updated_at",
    "linked_entity_type",
    "linked_entity_id",
    "owner_name",
    "assigned_team",
    "sla_due_at",
    "risk_score",
    "tags",
    "mailbox_id",
    "category",
    "message_count",
    "last_activity_at"
  ],
  "hr_activity_events": [
    "id",
    "actor_user_id",
    "target_user_id",
    "source",
    "source_ref",
    "event_type",
    "title",
    "description",
    "severity",
    "status",
    "payload",
    "created_at",
    "updated_at"
  ],
  "hr_activity_log": [
    "id",
    "event_type",
    "entity_table",
    "entity_id",
    "actor_id",
    "actor_name",
    "summary",
    "payload",
    "created_at",
    "actor_user_id",
    "source_table",
    "record_id",
    "action",
    "details"
  ],
  "hr_activity_timeline": [
    "id",
    "title",
    "event_type",
    "entity_type",
    "severity",
    "status",
    "event_at",
    "summary",
    "notes",
    "created_at",
    "updated_at",
    "action",
    "entity_id",
    "source",
    "payload",
    "metadata",
    "activity_type",
    "module",
    "actor_user_id",
    "actor_label",
    "source_table",
    "record_id",
    "details",
    "description"
  ],
  "hr_approval_requests": [
    "id",
    "user_id",
    "type",
    "status",
    "created_at",
    "title",
    "approval_type",
    "entity_type",
    "entity_id",
    "priority",
    "requested_by",
    "requested_reason",
    "decided_by",
    "decided_at",
    "decision_notes",
    "notes",
    "updated_at",
    "approved_by",
    "metadata",
    "decision"
  ],
  "hr_approvals": [
    "id",
    "title",
    "approval_type",
    "status",
    "priority",
    "requester_id",
    "requester_name",
    "approver_id",
    "approver_name",
    "target_staff_id",
    "target_name",
    "source_record_id",
    "decision_note",
    "payload",
    "created_at",
    "decided_at",
    "updated_at"
  ],
  "hr_attendance": [
    "id",
    "staff_id",
    "staff_name",
    "attendance_date",
    "clock_in",
    "clock_out",
    "status",
    "stage",
    "notes",
    "created_at",
    "updated_at",
    "check_in",
    "check_out",
    "validation_status",
    "correction_reason",
    "approved_by"
  ],
  "hr_audit_logs": [
    "id",
    "actor_id",
    "action",
    "entity_type",
    "entity_id",
    "stage",
    "status",
    "metadata",
    "notes",
    "created_at",
    "updated_at",
    "source_table",
    "severity",
    "before",
    "after",
    "payload",
    "details",
    "module",
    "source",
    "actor_user_id",
    "actor_label",
    "record_id",
    "title",
    "description"
  ],
  "hr_data_quality_checks": [
    "id",
    "check_key",
    "severity",
    "title",
    "source_table",
    "source_record_id",
    "status",
    "recommendation",
    "created_at",
    "resolved_at",
    "code",
    "affected_count",
    "details",
    "updated_at"
  ],
  "hr_interviews": [
    "id",
    "candidate_id",
    "opening_id",
    "interview_type",
    "scheduled_at",
    "interviewer",
    "status",
    "score",
    "notes",
    "created_at",
    "updated_at"
  ],
  "hr_job_openings": [
    "id",
    "title",
    "department",
    "position",
    "location",
    "contract_type",
    "priority",
    "status",
    "stage",
    "headcount",
    "salary_min",
    "salary_max",
    "description",
    "requirements",
    "notes",
    "created_at",
    "updated_at",
    "city",
    "hiring_priority",
    "openings_count",
    "target_start_date",
    "required_skills",
    "mission_context",
    "approval_owner"
  ],
  "hr_notifications": [
    "id",
    "title",
    "channel",
    "audience",
    "severity",
    "message",
    "status",
    "sent_at",
    "created_by",
    "notes",
    "created_at",
    "updated_at"
  ],
  "hr_onboarding_activity": [
    "id",
    "journey_id",
    "type",
    "title",
    "body",
    "created_at",
    "channel",
    "phone",
    "wa_url",
    "stage",
    "onboarding_id",
    "staff_id",
    "candidate_id",
    "status",
    "notes"
  ],
  "hr_onboarding_checklists": [
    "id",
    "user_id",
    "stage",
    "checklist",
    "status",
    "owner_user_id",
    "created_at",
    "updated_at",
    "name",
    "role_key",
    "department_id",
    "notes"
  ],
  "hr_onboarding_documents": [
    "id",
    "journey_id",
    "title",
    "status",
    "file_url",
    "created_at",
    "onboarding_id",
    "staff_id",
    "candidate_id",
    "document_type",
    "due_date",
    "notes"
  ],
  "hr_onboarding_journeys": [
    "id",
    "title",
    "position",
    "status",
    "start_date",
    "department",
    "manager",
    "location",
    "employment_type",
    "email",
    "phone",
    "progress",
    "owner",
    "created_at",
    "updated_at",
    "staff_id",
    "candidate_id",
    "stage",
    "completion_rate",
    "notes"
  ],
  "hr_onboarding_steps": [
    "id",
    "onboarding_id",
    "staff_id",
    "candidate_id",
    "title",
    "category",
    "stage",
    "status",
    "owner_id",
    "due_at",
    "completed_at",
    "evidence_url",
    "notes",
    "created_at",
    "updated_at"
  ],
  "hr_onboarding_tasks": [
    "id",
    "employee_id",
    "staff_id",
    "profile_id",
    "title",
    "task",
    "status",
    "priority",
    "due_date",
    "source",
    "created_at",
    "updated_at",
    "candidate_id",
    "owner_role",
    "due_at",
    "checklist",
    "metadata",
    "onboarding_id",
    "category",
    "stage",
    "owner",
    "completed_at",
    "evidence_url",
    "notes"
  ],
  "hr_staff_profiles": [
    "id",
    "user_id",
    "position",
    "department",
    "contract_type",
    "status",
    "created_at",
    "manager_user_id",
    "start_date",
    "probation_end_date",
    "salary_base",
    "payroll_code",
    "notes",
    "metadata",
    "updated_at",
    "full_name",
    "phone",
    "emergency_contact",
    "profile_status",
    "readiness_score",
    "employee_code",
    "work_location",
    "risk_level",
    "employment_status",
    "profile_completion",
    "last_hr_action_at",
    "operational_status",
    "execution_notes",
    "app_user_id",
    "email",
    "city",
    "skills",
    "certifications",
    "performance_notes",
    "end_date",
    "compliance_status",
    "mission_capacity",
    "hourly_cost",
    "monthly_salary",
    "source",
    "identity_status",
    "identity_source",
    "identity_linked_at",
    "profile_id",
    "first_name",
    "last_name",
    "preferred_name",
    "name",
    "display_name",
    "work_email",
    "mobile",
    "national_id",
    "cin",
    "date_of_birth",
    "place_of_birth",
    "nationality",
    "gender",
    "marital_status",
    "children_count",
    "address",
    "postal_code",
    "country",
    "branch_office",
    "office",
    "location",
    "work_city",
    "remote_option",
    "work_type",
    "job_title",
    "manager",
    "reports_to",
    "employment_type",
    "hire_date",
    "salary",
    "base_salary",
    "currency",
    "payment_method",
    "cnss_number",
    "amo_number",
    "emergency_contact_name",
    "emergency_contact_phone",
    "emergency_contact_relation",
    "onboarding_status",
    "create_login_account",
    "send_welcome_email",
    "profile_completeness",
    "risk_score",
    "department_id",
    "position_id",
    "role",
    "archived_at"
  ],
  "hr_training_assignments": [
    "id",
    "staff_id",
    "staff_name",
    "title",
    "training_type",
    "status",
    "priority",
    "due_date",
    "completion_note",
    "score",
    "metadata",
    "created_by",
    "created_at",
    "updated_at",
    "completed_at",
    "description",
    "user_id",
    "program_id",
    "module_id",
    "position",
    "department",
    "assignment_type",
    "progress",
    "assigned_at",
    "due_at",
    "approved_at",
    "approved_by",
    "notes",
    "staff_email",
    "employee_name",
    "user_name",
    "position_title",
    "training_id",
    "training_title",
    "assignment_group_id",
    "start_at",
    "alert_level",
    "source",
    "category",
    "audience",
    "progress_percent",
    "starting_at",
    "last_activity_at",
    "resource_url"
  ],
  "hsd_handoff_amendments": [
    "id",
    "tenant_id",
    "handoff_id",
    "amendment_type",
    "status",
    "reason",
    "requested_changes",
    "applies_from_date",
    "impact_summary",
    "created_by",
    "created_at",
    "approved_by",
    "approved_at",
    "propagated_at"
  ],
  "incidents": [
    "id",
    "incident_title",
    "incident_type",
    "severity",
    "status",
    "source_module",
    "mission_id",
    "caregiver_id",
    "family_id",
    "lead_id",
    "description",
    "resolution_notes",
    "assigned_to",
    "created_by",
    "created_at",
    "resolved_at",
    "is_archived",
    "archived_at"
  ],
  "intervention_audit_logs": [
    "id",
    "at",
    "actor",
    "role",
    "entityType",
    "entityId",
    "event",
    "summary",
    "riskLevel",
    "metadata"
  ],
  "leads": [
    "id",
    "parent_name",
    "phone",
    "city",
    "source",
    "service_needed",
    "urgency",
    "children_count",
    "children_ages",
    "special_needs",
    "preferred_schedule",
    "status",
    "created_at",
    "service_interests",
    "timeline_note",
    "offer_needed",
    "quote_needed",
    "product_explanation_needed",
    "reminder_reason",
    "reminder_at",
    "converted_to_mission_id",
    "family_id",
    "is_archived",
    "archived_at",
    "name",
    "service_interest",
    "last_contact_at",
    "contact_attempts",
    "assigned_to",
    "full_name",
    "email",
    "child_age",
    "pipeline_stage",
    "priority",
    "lead_score",
    "next_action",
    "next_action_date",
    "expected_value",
    "probability",
    "lost_reason",
    "notes",
    "updated_at"
  ],
  "learn_assignments": [
    "id",
    "organization_id",
    "module_id",
    "user_id",
    "assigned_by",
    "assigned_at",
    "due_at",
    "status",
    "metadata"
  ],
  "learn_certificates": [
    "id",
    "organization_id",
    "module_id",
    "user_id",
    "certificate_number",
    "certificate_url",
    "issued_at",
    "status",
    "metadata"
  ],
  "learn_progress": [
    "id",
    "assignment_id",
    "module_id",
    "user_id",
    "progress_percent",
    "started_at",
    "completed_at",
    "last_activity_at",
    "status",
    "metadata"
  ],
  "learn_quizzes": [
    "id",
    "module_id",
    "title",
    "passing_score",
    "max_attempts",
    "status",
    "metadata"
  ],
  "learn_refresh_reminders": [
    "id",
    "organization_id",
    "course_id",
    "module_id",
    "user_id",
    "due_date",
    "reminder_type",
    "status",
    "sent_at",
    "metadata"
  ],
  "market_ai_command_schedules": [
    "id",
    "name",
    "command_id",
    "command_code",
    "frequency",
    "timezone",
    "hour",
    "minute",
    "day_of_week",
    "day_of_month",
    "enabled",
    "authority_mode",
    "objective",
    "context",
    "last_run_at",
    "next_run_at",
    "created_by",
    "updated_by",
    "created_at",
    "updated_at"
  ],
  "market_content_source_replacements": [
    "id",
    "dossier_id",
    "content_code",
    "previous_source_id",
    "new_source_id",
    "status",
    "reason",
    "previous_bridge_file_id",
    "previous_storage_key",
    "previous_sha256_hash",
    "previous_filename",
    "previous_size_bytes",
    "new_bridge_file_id",
    "new_storage_key",
    "error",
    "requested_by",
    "requested_by_name",
    "committed_at",
    "previous_deleted_at",
    "failed_at",
    "created_at",
    "updated_at"
  ],
  "market_os_actions": [
    "id",
    "action_key",
    "action_label",
    "engine",
    "record_id",
    "actor_name",
    "status",
    "payload",
    "created_at"
  ],
  "missions": [
    "id",
    "family_id",
    "caregiver_id",
    "service_type",
    "mission_date",
    "start_time",
    "end_time",
    "status",
    "urgency",
    "notes",
    "created_at",
    "city",
    "zone",
    "missionnaire_data",
    "route_lines",
    "parameter_config",
    "transport_config",
    "allowance_config",
    "program_lines",
    "mission_object",
    "special_conditions",
    "staff_id",
    "grade_level",
    "staff_status",
    "personal_address",
    "mobile",
    "home_address",
    "mission_reference",
    "pages_total",
    "pdf_generated_at",
    "started_at",
    "completed_at",
    "incident_note",
    "is_archived",
    "archived_at",
    "contract_id",
    "mission_code",
    "duration_hours",
    "contract_row_order",
    "cancelled_at",
    "confirmed_at",
    "incident_at",
    "ops_priority",
    "execution_status",
    "confirmation_status",
    "replacement_required",
    "replacement_reason",
    "risk_level",
    "next_action_at",
    "caregiver_confirmed_at",
    "client_confirmed_at",
    "actual_start_at",
    "actual_end_at",
    "ops_notes",
    "dispatch_score",
    "parent_mission_id",
    "mission_group_id",
    "mission_kind",
    "recurrence_type",
    "recurrence_rule",
    "recurrence_start_date",
    "recurrence_end_date",
    "occurrence_index",
    "dossier_reference",
    "dossier_status",
    "lifecycle_stage",
    "readiness_status",
    "validation_status",
    "report_status",
    "sla_status",
    "service_family",
    "mission_scope",
    "internal_procedure_level",
    "report_submitted_at",
    "validated_at",
    "validated_by",
    "archived_reason",
    "service_category",
    "backup_caregiver_id",
    "dispatch_status",
    "language",
    "required_skills",
    "safety_notes",
    "scheduled_start",
    "scheduled_end",
    "updated_at",
    "arrival_confirmed_at",
    "checked_in_at",
    "delay_reported_at",
    "replacement_requested_at",
    "last_mobile_action",
    "last_mobile_action_at"
  ],
  "opsos_action_logs": [
    "id",
    "action_key",
    "action_label",
    "action_type",
    "scope",
    "target",
    "status",
    "before_json",
    "after_json",
    "payload",
    "result",
    "rollback_available",
    "created_by",
    "created_at",
    "is_archived"
  ],
  "revenue_command_records": [
    "id",
    "module_key",
    "page_key",
    "record_type",
    "title",
    "description",
    "owner_id",
    "owner_name",
    "department",
    "status",
    "priority",
    "risk_level",
    "stage",
    "value_mad",
    "confidence_score",
    "sla_due_at",
    "next_action_at",
    "source_table",
    "source_id",
    "tags",
    "metadata",
    "created_at",
    "updated_at",
    "due_at",
    "next_action",
    "score",
    "owner",
    "health",
    "completed_at",
    "due_date",
    "started_at",
    "archived_at",
    "deleted_at",
    "escalated_at",
    "sla_minutes",
    "source"
  ],
  "revenue_documents": [
    "id",
    "workspace_slug",
    "entity_type",
    "entity_id",
    "title",
    "file_url",
    "document_type",
    "status",
    "created_by",
    "created_at",
    "updated_at",
    "tenant_id",
    "user_id",
    "priority",
    "owner",
    "metadata",
    "archived_at",
    "partnership_id",
    "prospect_id"
  ],
  "service_pricing_rules": [
    "id",
    "service_id",
    "duration",
    "city",
    "client_type",
    "skill_level",
    "price",
    "created_at"
  ],
  "system_runtime_events": [
    "id",
    "event_type",
    "from_mode",
    "to_mode",
    "actor_email",
    "actor_role",
    "payload",
    "created_at"
  ],
  "trn_attendance_records": [
    "id",
    "session_id",
    "participant_id",
    "session_date_id",
    "check_in_at",
    "check_out_at",
    "attendance_status",
    "signature_url",
    "validated_by",
    "validated_at",
    "metadata"
  ],
  "trn_delivery_checklists": [
    "id",
    "session_id",
    "checklist_type",
    "item_label",
    "required",
    "completed",
    "completed_by",
    "completed_at",
    "evidence_url",
    "metadata"
  ],
  "trn_session_dates": [
    "id",
    "session_id",
    "date_label",
    "starts_at",
    "ends_at",
    "duration_minutes",
    "agenda",
    "status",
    "metadata"
  ],
  "trn_session_participants": [
    "id",
    "session_id",
    "organization_id",
    "site_id",
    "user_id",
    "full_name",
    "email",
    "phone",
    "job_title",
    "participant_type",
    "attendance_status",
    "quiz_pre_score",
    "quiz_post_score",
    "certificate_status",
    "refresh_access_status",
    "created_at",
    "metadata"
  ],
  "trn_session_resources_allocated": [
    "id",
    "session_id",
    "resource_id",
    "participant_id",
    "allocated_quantity",
    "delivery_status",
    "delivered_at",
    "metadata"
  ],
  "trn_session_trainers": [
    "id",
    "session_id",
    "trainer_id",
    "role",
    "assigned_at",
    "status",
    "metadata"
  ],
  "whatsapp_contact_attempts": [
    "id",
    "context_id",
    "workspace_id",
    "user_id",
    "device_id",
    "normalized_phone",
    "purpose",
    "prepared_message_snapshot",
    "opened_at",
    "declared_sent_at",
    "outcome_status",
    "outcome_recorded_at",
    "outcome_note",
    "next_action_at",
    "related_task_id",
    "evidence_reference",
    "status",
    "metadata",
    "created_at",
    "updated_at"
  ],
  "workspace_broadcast_memo_receipts": [
    "id",
    "memo_id",
    "user_id",
    "acknowledged_at",
    "comment",
    "commented_at",
    "created_at",
    "updated_at",
    "admin_response",
    "admin_responded_at",
    "followup_status",
    "closed_at",
    "closed_by"
  ]
} as const

export const RELATION_ALIASES = {
  "hr_training_course_assignments": {
    "table": "hr_training_assignments",
    "sink": "metadata"
  },
  "intervention_config_items": {
    "table": "b2b_config_items",
    "sink": "value"
  },
  "b2b_workspace_automation_rules": {
    "table": "b2b_automation_rules"
  },
  "b2b_workspace_partner_programs": {
    "table": "b2b_partner_programs"
  },
  "b2b_workspace_reports": {
    "table": "b2b_reports"
  },
  "hr_employee_cases": {
    "table": "hr_activity_log",
    "sink": "payload",
    "scope": {
      "entity_table": "hr_employee_cases"
    }
  },
  "hr_employee_lifecycle_events": {
    "table": "hr_activity_log",
    "sink": "payload",
    "scope": {
      "entity_table": "hr_employee_lifecycle_events"
    }
  },
  "traininghub_internal_actions": {
    "table": "auto_events",
    "sink": "payload",
    "scope": {
      "source_type": "traininghub_internal_actions"
    }
  },
  "b2b_workspace_settings": {
    "table": "b2b_config_items",
    "sink": "value",
    "scope": {
      "config_group": "b2b_workspace_settings"
    }
  },
  "ac_capital_command_activity": {
    "table": "ac_capital_command_results",
    "sink": "result_snapshot"
  },
  "hr_employee_360_audit_events": {
    "table": "hr_activity_log",
    "sink": "payload",
    "scope": {
      "entity_table": "hr_employee_360_audit_events"
    }
  },
  "hr_employee_360_idempotency": {
    "table": "angelcare_marketplace_command_idempotency",
    "sink": "result"
  },
  "hr_record_links": {
    "table": "hr_activity_log",
    "sink": "payload",
    "scope": {
      "event_type": "hr_record_link"
    }
  },
  "academy_partner_activities": {
    "table": "hr_activity_log",
    "sink": "payload",
    "scope": {
      "event_type": "academy_partner_activity"
    }
  },
  "partner_activity_events": {
    "table": "auto_events",
    "sink": "payload",
    "scope": {
      "source_type": "partner_activity_events"
    }
  },
  "hr_interview_activity": {
    "table": "hr_activity_log",
    "sink": "payload",
    "scope": {
      "event_type": "hr_interview_activity"
    }
  },
  "intervention_config_audit_logs": {
    "table": "intervention_audit_logs",
    "sink": "metadata"
  },
  "marketing_ai_schedules": {
    "table": "market_ai_command_schedules",
    "sink": "context"
  },
  "hr_openings": {
    "table": "hr_job_openings"
  },
  "partner_requests": {
    "table": "auto_events",
    "sink": "payload",
    "scope": {
      "source_type": "partner_requests"
    }
  },
  "revenue_document_command_view": {
    "table": "revenue_documents",
    "sink": "metadata"
  },
  "workspace_broadcast_memo_targets": {
    "table": "workspace_broadcast_memo_receipts"
  },
  "hr_training_course_command_extensions": {
    "table": "hr_training_assignments",
    "sink": "metadata"
  },
  "revenue_command_analytics_view": {
    "table": "revenue_command_records",
    "sink": "metadata",
    "scope": {
      "record_type": "analytics"
    }
  },
  "revenue_command_center_analytics": {
    "table": "revenue_command_records",
    "sink": "metadata",
    "scope": {
      "record_type": "analytics"
    }
  }
} as const

export const COLUMN_ALIASES = {
  "ac_whatsapp_stop_list": {
    "contact_id": null
  },
  "academy_alerts": {
    "trainee_id": "related_trainee_id",
    "updated_at": null
  },
  "academy_notification_queue": {
    "entity": null
  },
  "academy_partners": {
    "updated_at": null
  },
  "academy_placement_cases": {
    "partner_name": null
  },
  "academy_trainer_assignments": {
    "assignment_date": "starts_at",
    "cohort_label": "cohort_title",
    "cohort_reference": "cohort_id",
    "delivery_format": "delivery_mode",
    "end_time": "ends_at",
    "program_label": "program_title",
    "start_time": "starts_at"
  },
  "ai_provider_usage_ledger": {
    "created_at": "occurred_at"
  },
  "app_users": {
    "name": "full_name",
    "role_key": "role",
    "user_email": "email"
  },
  "audit_change_logs": {
    "action": "operation",
    "actor_user_id": "user_id",
    "entity_id": "record_id",
    "entity_type": "table_name",
    "message": "reason",
    "metadata": null,
    "severity": null
  },
  "audit_security_logs": {
    "actor_user_id": "user_id",
    "entity_id": "target_id",
    "entity_type": "target_type",
    "message": "details",
    "metadata": "details",
    "severity": "risk_level"
  },
  "auto_events": {
    "title": null
  },
  "b2b_automation_rules": {
    "last_run_at": "updated_at"
  },
  "b2b_campaign_prospects": {
    "current_step_order": "sequence_step",
    "last_step_at": "last_action_at"
  },
  "b2b_campaigns": {
    "enrolled_count": null
  },
  "b2b_direct_actions": {
    "action_type": "action_title",
    "channel": "action_channel",
    "created_by": "actor_id"
  },
  "b2b_prospects": {
    "campaign_status": "status",
    "last_campaign_touch_at": "last_contact_at",
    "priority": null
  },
  "b2b_sequences": {
    "description": "objective"
  },
  "bd_automation_logs": {
    "action": null,
    "error": null,
    "message": null,
    "payload": null,
    "rule_name": null,
    "status": null,
    "trigger_type": null
  },
  "bd_tasks": {
    "end_at": "planned_end_at",
    "is_archived": null
  },
  "caregiver_checkins": {
    "created_at": "event_time"
  },
  "carelink_mission_action_logs": {
    "canonical_bridge_status": null,
    "created_by": null
  },
  "carelink_mission_notifications": {
    "mission_code": null
  },
  "connect_action_assignees": {
    "created_at": "assigned_at"
  },
  "core_organizations": {
    "access_status": "status",
    "archived_at": null,
    "deleted_at": null,
    "display_name": "name",
    "is_active": null
  },
  "email_audit_logs": {
    "account_id": null,
    "details": "payload",
    "entity_id": null,
    "entity_type": null
  },
  "email_messages": {
    "message_id": "message_id_header",
    "provider_uid": "provider_message_id",
    "raw_headers": "metadata"
  },
  "email_os_core_access_audit": {
    "actor": "principal_id",
    "resource": "mailbox_id"
  },
  "email_os_core_attachments": {
    "mailbox_id": null
  },
  "email_os_core_inbox": {
    "external_id": "provider_uid",
    "message_id": "provider_uid"
  },
  "email_os_core_provider_logs": {
    "email_address": null,
    "error": "message",
    "provider_profile_id": null,
    "test_type": "action",
    "tested_at": "created_at"
  },
  "email_os_message_assignments": {
    "note": null,
    "status": null
  },
  "email_threads": {
    "account_id": "mailbox_id",
    "assigned_owner_label": "owner_name",
    "external_thread_id": "thread_key",
    "participants": null
  },
  "hr_activity_events": {
    "action": "event_type",
    "entity_id": "source_ref",
    "entity_type": "source",
    "metadata": "payload"
  },
  "hr_activity_timeline": {
    "actor_id": "actor_user_id"
  },
  "hr_approval_requests": {
    "approver_name": null,
    "request_type": "approval_type",
    "requester_name": null
  },
  "hr_approvals": {
    "entity_id": "source_record_id",
    "entity_type": null,
    "request_type": "approval_type"
  },
  "hr_attendance": {
    "work_date": "attendance_date"
  },
  "hr_audit_logs": {
    "entity": "entity_type"
  },
  "hr_data_quality_checks": {
    "check_type": "check_key",
    "entity_id": "source_record_id",
    "entity_table": "source_table",
    "finding": "details",
    "notes": "details",
    "recommended_fix": "recommendation"
  },
  "hr_interviews": {
    "cancellation_reason": "notes",
    "pipeline_stage_after": null,
    "updated_by": null,
    "version": null
  },
  "hr_notifications": {
    "audience_role": "audience",
    "body": "message",
    "payload": null,
    "user_id": null
  },
  "hr_onboarding_documents": {
    "document_key": "id",
    "storage_bucket": null,
    "storage_path": "file_url"
  },
  "hr_staff_profiles": {
    "archive_reason": null,
    "archived_by": null,
    "lifecycle_state": "employment_status",
    "terminated_at": "end_date",
    "termination_reason": null,
    "updated_by": null,
    "version": null
  },
  "hsd_handoff_amendments": {
    "code": null,
    "requested_by": "created_by"
  },
  "incidents": {
    "metadata": null
  },
  "leads": {
    "assigned_user_id": "assigned_to"
  },
  "learn_assignments": {
    "completed_at": null,
    "completion_status": "status",
    "site_id": null
  },
  "learn_certificates": {
    "expires_at": null,
    "site_id": null
  },
  "learn_progress": {
    "last_accessed_at": "last_activity_at",
    "lesson_id": "module_id",
    "organization_id": null,
    "progress_status": "status",
    "score_percent": null,
    "site_id": null
  },
  "learn_quizzes": {
    "created_at": null
  },
  "learn_refresh_reminders": {
    "completed_at": null,
    "due_at": "due_date",
    "reminder_status": "status",
    "site_id": null
  },
  "market_content_source_replacements": {
    "requested_at": "created_at"
  },
  "market_os_actions": {
    "owner_agent": "actor_name"
  },
  "missions": {
    "address": "home_address"
  },
  "opsos_action_logs": {
    "actor": "created_by",
    "payload_json": "payload",
    "reason": null,
    "result_json": "result"
  },
  "service_pricing_rules": {
    "notes": null,
    "region": null,
    "status": null
  },
  "system_runtime_events": {
    "message": null,
    "metadata": null,
    "module_key": null,
    "route": null,
    "severity": null
  },
  "trn_attendance_records": {
    "created_at": null
  },
  "trn_delivery_checklists": {
    "checklist_title": "item_label",
    "created_at": null,
    "status": null
  },
  "trn_session_dates": {
    "end_at": "ends_at",
    "location_address": null,
    "start_at": "starts_at"
  },
  "trn_session_participants": {
    "status": "attendance_status"
  },
  "trn_session_resources_allocated": {
    "notes": null,
    "status": "delivery_status"
  },
  "trn_session_trainers": {
    "assignment_status": "status"
  },
  "whatsapp_contact_attempts": {
    "business_stage_update": null
  },
  "hr_training_course_assignments": {
    "resource_id": null,
    "course_title": "training_title",
    "scheduled_at": "start_at",
    "trainer_name": null,
    "session_mode": "assignment_type",
    "score_percent": "score",
    "pass_score": null,
    "attempt_count": null,
    "delayed_reason": null,
    "evidence_url": "resource_url",
    "employee_id": "staff_id"
  },
  "intervention_config_items": {
    "id": "item_key",
    "scope": "config_group",
    "code": "config_key",
    "status": null,
    "owner_role": null,
    "impacts": null,
    "audit_event": null,
    "metadata": "value"
  },
  "b2b_workspace_automation_rules": {
    "status": null,
    "sector": null,
    "trigger": "trigger_key",
    "condition": null,
    "action": null,
    "cadence": null,
    "owner": null,
    "severity": null,
    "channels": null,
    "ai_brief": null,
    "expected_impact": null,
    "field_key": null,
    "score_delta": null,
    "deleted_at": null,
    "updated_by": null,
    "payload": null
  },
  "b2b_workspace_partner_programs": {
    "sector": "sector_focus",
    "pricing_models": "pricing_models",
    "deleted_at": null,
    "payload": null,
    "status": null
  },
  "b2b_workspace_reports": {
    "kind": null,
    "purpose": "report_type",
    "sector": null,
    "title": null,
    "reference": null,
    "period": null,
    "status": null,
    "generated_at": "created_at",
    "owner": "owner_id",
    "executive_summary": "summary",
    "alerts": null,
    "congratulations": null,
    "coaching": null,
    "revenueMoves": null,
    "reminders": null,
    "marketInsights": null,
    "kpis": null,
    "actionPlan": null,
    "payload": null,
    "deleted_at": null,
    "is_active": null,
    "updated_at": null,
    "created_by": null,
    "updated_by": null
  },
  "hr_employee_cases": {
    "employee_id": "entity_id",
    "case_type": null,
    "domain": null,
    "title": "summary",
    "description": null,
    "status": null,
    "priority": null,
    "owner_id": "actor_id",
    "owner_name": "actor_name",
    "due_at": null,
    "metadata": "payload",
    "created_by": "actor_user_id",
    "updated_by": null,
    "updated_at": null
  },
  "hr_employee_lifecycle_events": {
    "employee_id": "entity_id",
    "from_state": null,
    "to_state": null,
    "effective_at": "created_at",
    "reason": "summary",
    "actor_id": "actor_id",
    "actor_name": "actor_name",
    "employee_version": null,
    "metadata": "payload"
  },
  "traininghub_internal_actions": {
    "module": null,
    "action": "event_type",
    "entity_id": null,
    "organization_id": "organization_id",
    "status": "status",
    "notes": null,
    "metadata": "payload"
  },
  "b2b_workspace_settings": {
    "workspace_key": "config_key",
    "settings": "value"
  },
  "ac_capital_command_activity": {
    "client_action_id": "command_key",
    "title": null,
    "message": "summary",
    "route": null,
    "stage": null,
    "action_href": null,
    "audit_ref": null,
    "affected_records": null,
    "detail_json": "result_snapshot",
    "is_read": null,
    "updated_at": null
  },
  "hr_employee_360_audit_events": {
    "employee_id": "entity_id",
    "tenant_id": null,
    "organization_id": null,
    "event_type": "event_type",
    "domain": null,
    "action": "action",
    "title": "summary",
    "summary": "summary",
    "actor_id": "actor_id",
    "actor_name": "actor_name",
    "risk_level": null,
    "before_state": null,
    "after_state": null,
    "metadata": "payload",
    "correlation_id": null
  },
  "hr_employee_360_idempotency": {
    "employee_id": "scope",
    "response_payload": "result"
  },
  "hr_record_links": {
    "source_table": "source_table",
    "source_id": "record_id",
    "target_table": null,
    "target_id": "entity_id",
    "link_type": "action",
    "status": null,
    "notes": "summary"
  },
  "academy_partner_activities": {
    "partner_id": "entity_id",
    "partner_name": null,
    "title": "summary",
    "action_type": "action",
    "status": null,
    "priority": null,
    "due_date": null,
    "owner": null,
    "notes": null,
    "updated_at": null
  },
  "partner_activity_events": {
    "organization_id": "organization_id",
    "event_type": "event_type",
    "title": null,
    "body": null,
    "metadata": "payload"
  },
  "hr_interview_activity": {
    "interview_id": "entity_id",
    "candidate_id": null,
    "action": "action",
    "event_type": "event_type",
    "title": "summary",
    "notes": null,
    "metadata": "payload"
  },
  "intervention_config_audit_logs": {
    "entity_type": "entityType",
    "entity_id": "entityId",
    "risk_level": "riskLevel",
    "created_at": "at"
  },
  "marketing_ai_schedules": {
    "provider_type": null,
    "model": null,
    "status": null,
    "metadata": "context"
  },
  "partner_requests": {
    "requester_user_id": "actor_user_id",
    "request_type": "event_type",
    "title": null,
    "description": null,
    "priority": null,
    "metadata": "payload"
  },
  "revenue_document_command_view": {
    "storage_bucket": null,
    "storage_path": "file_url",
    "file_name": null,
    "mime_type": null,
    "file_size": null,
    "version": null,
    "uploaded_by": "created_by"
  },
  "workspace_broadcast_memo_targets": {
    "target_user_id": "user_id"
  },
  "hr_training_course_command_extensions": {
    "resource_id": null,
    "course_title": "training_title",
    "html_course_code": null,
    "course_builder_prompt": null,
    "live_assessment_enabled": null,
    "pass_score": null,
    "assessment_capture_mode": null,
    "notes": "notes"
  }
} as const

export const TABLE_SINKS = {
  "academy_notification_queue": "metadata",
  "academy_placement_cases": "metadata",
  "audit_change_logs": "new_values",
  "audit_security_logs": "details",
  "auto_events": "payload",
  "b2b_direct_actions": "metadata",
  "bd_automation_logs": "result",
  "bd_tasks": "data",
  "carelink_mission_action_logs": "payload",
  "carelink_mission_notifications": "payload",
  "core_organizations": "metadata",
  "email_audit_logs": "payload",
  "email_messages": "metadata",
  "email_os_core_provider_logs": "metadata",
  "email_os_message_assignments": "metadata_json",
  "email_threads": "metadata",
  "hr_activity_events": "payload",
  "hr_activity_timeline": "metadata",
  "hr_approval_requests": "metadata",
  "hr_approvals": "payload",
  "hr_audit_logs": "metadata",
  "hr_data_quality_checks": "details",
  "hr_notifications": "notes",
  "hr_staff_profiles": "metadata",
  "incidents": null,
  "learn_assignments": "metadata",
  "learn_certificates": "metadata",
  "learn_progress": "metadata",
  "learn_quizzes": "metadata",
  "learn_refresh_reminders": "metadata",
  "opsos_action_logs": "payload",
  "system_runtime_events": "payload",
  "trn_attendance_records": "metadata",
  "trn_delivery_checklists": "metadata",
  "trn_session_dates": "metadata",
  "trn_session_participants": "metadata",
  "trn_session_resources_allocated": "metadata",
  "trn_session_trainers": "metadata",
  "whatsapp_contact_attempts": "metadata"
} as const

export const DROP_FILTERS = {
  "hr_staff_profiles": [
    "version"
  ],
  "hr_interviews": [
    "version"
  ]
} as const

export const RESPONSE_DEFAULTS = {
  "hr_onboarding_documents": {
    "storage_bucket": "hr-onboarding-documents"
  }
} as const

export const INSERT_DEFAULTS = {
  "hr_training_course_assignments": {
    "title": "Assigned training"
  },
  "b2b_workspace_settings": {
    "config_group": "b2b_workspace_settings",
    "label": "B2B Workspace Settings",
    "is_active": true,
    "sort_order": 100
  },
  "ac_capital_command_activity": {
    "workspace_key": "ac-capital-os",
    "status": "completed"
  },
  "hr_employee_cases": {
    "event_type": "employee_case"
  },
  "hr_employee_lifecycle_events": {
    "event_type": "employee_lifecycle_event"
  },
  "traininghub_internal_actions": {
    "event_type": "traininghub.internal.action",
    "status": "pending"
  },
  "hr_employee_360_audit_events": {
    "event_type": "employee_360_audit"
  },
  "hr_record_links": {
    "event_type": "hr_record_link"
  },
  "academy_partner_activities": {
    "event_type": "academy_partner_activity"
  },
  "partner_activity_events": {
    "event_type": "partner_activity",
    "status": "recorded"
  },
  "hr_interview_activity": {
    "event_type": "hr_interview_activity"
  },
  "partner_requests": {
    "event_type": "partner_request",
    "status": "open"
  },
  "hr_training_course_command_extensions": {
    "title": "Course command extension"
  }
} as const

export const SPECIAL_RELATION_RULES = {
  "hr_employee_360_idempotency": {
    "scopePrefix": "hr_employee_360:"
  }
} as const

export const MISSING_RPC_SHIMS = [
  'connect_current_user_ids',
  'hr_onboarding_ensure_journey',
  'hr_onboarding_execute',
] as const
