import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import Module, { createRequire } from "node:module";
import { EventEmitter } from "node:events";
const require = createRequire(import.meta.url); let nextId=9000;
class WC extends EventEmitter { constructor(session){super();this.id=nextId++;this._session=session;this._url="about:blank";this._destroyed=false;this.navigationHistory={canGoBack:()=>false,canGoForward:()=>false,goBack(){},goForward(){}}} setWindowOpenHandler(){} setZoomFactor(){} getZoomFactor(){return 1} getURL(){return this._url} getTitle(){return this._url} isDestroyed(){return this._destroyed} focus(){} close(){this._destroyed=true} stop(){} reload(){} setUserAgent(){} getUserAgent(){return "Mock"} async loadURL(url){this._url=String(url);this.emit("did-navigate",{},this._url);this.emit("did-stop-loading")} get session(){return this._session}}
class View { constructor({webPreferences={}}={}){this.webContents=new WC(webPreferences.session)} setBackgroundColor(){} setVisible(){} setBounds(){}}
const sess=()=>({setPermissionRequestHandler(){},setPermissionCheckHandler(){},setDevicePermissionHandler(){},setDisplayMediaRequestHandler(){},on(){},clearCache:async()=>{},clearStorageData:async()=>{}});
const original=Module._load; Module._load=function(req,p,m){if(req==="electron")return{session:{fromPartition:()=>sess()},WebContentsView:View};return original.call(this,req,p,m)};
const temp=fs.mkdtempSync(path.join(os.tmpdir(),"angelcare-mz15-disabled-"));
try { const {createCorporateBrowser}=require("../src/runtime/corporate-browser.cjs"); const trusted=sess(); const main=new View({webPreferences:{session:trusted}}); await main.webContents.loadURL("https://opsmanagement.angelcarehub.com/dashboard"); const policy={mode:"locked",maximum_tabs:8,maximum_ac_plus_tabs:6,ac_plus_enabled:false,ac_plus_allowed_modes:["standard","focus","locked"],split_enabled:false,split_allowed_modes:["standard","focus","locked"],split_modes:[2,3,4],restore_tabs:true,browser:{default_action:"deny",allowed_schemes:["https:"],allowed_domains:["angelcarehub.com","opsmanagement.angelcarehub.com"],blocked_domains:[],allowed_private_hosts:[],include_subdomains:true,google_search_enabled:false,gmail_enabled:false,microsoft_365_enabled:false,popups:"deny",external_open:false,downloads:"deny",uploads:"allow",printing:"allow",clipboard_read:"deny",clipboard_write:"allow",camera:"deny",microphone:"deny",notifications:"deny",geolocation:"deny",fullscreen:"allow",maximum_download_bytes:1000000,safe_download_directory:"Downloads",blocked_extensions:[".exe"],domain_permission_overrides:{},default_tabs:[],pinned_tabs:[],mandatory_tabs:[],tab_order:[]}}; const browser=createCorporateBrowser({app:{getPath:()=>temp,getVersion:()=>"1.7.3"},mainWindow:{contentView:{addChildView(){},removeChildView(){}}},logger:{info(){},warn(){},error(){}},dialog:{showMessageBox:async()=>({response:0})},shell:{openPath:async()=>"",openExternal:async()=>{}},getBounds:()=>({x:0,y:108,width:1200,height:700}),getPolicy:()=>policy,initialOperatingMode:"locked",trustedAngelcareSession:trusted,trustedPreloadPath:"/trusted/preload.cjs",angelcareOrigin:"https://opsmanagement.angelcarehub.com",angelcareDashboardUrl:"https://opsmanagement.angelcarehub.com/dashboard",getSystemTabView:id=>id==="angelcare-system"?main:null,getSystemTabWebContents:id=>id==="angelcare-system"?main.webContents:null,getSystemTabStatus:()=>({activated:true})}); const state=await browser.restore(); assert.equal(state.acPlus.enabled,false); assert.equal(state.split.enabled,false); assert.match(state.acPlus.disabledReason,/désactivé par la politique/); assert.match(state.split.disabledReason,/désactivés par la politique/); browser.destroy(); console.log("MZ15_EXPLICIT_CAPABILITY_DISABLE_SMOKE_PASSED"); } finally { Module._load=original; fs.rmSync(temp,{recursive:true,force:true}); }
