'use client'
import Link from 'next/link'
import {useEffect,useRef,useState} from 'react'
import {ArrowUpRight,BriefcaseBusiness,CheckCircle2,Clock3,FileCheck2,Inbox,Mail,MessageCircle,RefreshCw,Search,ShieldCheck,UserRound,X} from 'lucide-react'
import {SOURCE_LABELS,validAction,type IntakeRow,type IntakeSnapshot} from './contracts'
import styles from './intake.module.css'
type Event={id:string;action:string;reason:string;created_at:string;actor_id:string|null}
type Dossier={row:IntakeRow;events:Event[]}
async function api<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{cache:'no-store',...init,headers:{'Content-Type':'application/json',...init?.headers}});const p=await r.json();if(!r.ok||!p.data)throw Error(p.error?.message||'Action impossible. Vos données sont conservées.');return p.data as T}
const amount=(r:IntakeRow)=>r.amount==null?'À établir':new Intl.NumberFormat('fr-MA',{maximumFractionDigits:2}).format(Number(r.amount))+' '+r.currency
const label=(s:string)=>({awaiting_angelcare:'À valider',registered:'Reçue',submitted:'Soumise',new:'Nouvelle',qualified:'Qualifiée',triaged:'Triée',pending:'Paiement attendu',quote_required:'Montant à établir',captured:'Fonds reçus',authorized:'Autorisation',requires_customer_action:'Action de paiement',not_required:'Sans paiement immédiat',converted:'Diagnostic ouvert',closed:'Clôturée'} as Record<string,string>)[s]||s.replaceAll('_',' ')
const actions=[['claim','Prendre en charge'],['triage','Trier la demande'],['qualify','Qualifier'],['proposal','Préparer la proposition'],['diagnostic','Ouvrir un diagnostic'],['crm','Créer / ouvrir le lead CRM'],['note','Enregistrer une note'],['reject','Décliner'],['cancel','Annuler'],['close','Clôturer'],['archive','Archiver']]
function DataFields({value}:{value:unknown}){if(value==null)return <span>Non renseigné</span>;if(typeof value!=='object')return <span>{String(value)}</span>;if(Array.isArray(value))return <div className={styles.fields}>{value.map((v,i)=><article key={i}><DataFields value={v}/></article>)}</div>;return <dl className={styles.fields}>{Object.entries(value as Record<string,unknown>).filter(([k])=>!['visitor_reference_hash','idempotency_key'].includes(k)).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd><DataFields value={v}/></dd></div>)}</dl>}
export function IntakeWorkspace({initial,initialSource=''}:{initial:IntakeSnapshot;initialSource?:string}){
 const [snapshot,setSnapshot]=useState(initial),[source,setSource]=useState(initialSource),[status,setStatus]=useState('open'),[owner,setOwner]=useState('all'),[query,setQuery]=useState(''),[page,setPage]=useState(1)
 const [dossier,setDossier]=useState<Dossier|null>(null),[tab,setTab]=useState('brief'),[reason,setReason]=useState(''),[pending,setPending]=useState<string|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const mounted=useRef(false),detailAbort=useRef<AbortController|null>(null),lock=useRef(false)
 const params=()=>new URLSearchParams({source,status,owner,q:query,page:String(page)}).toString()
 async function refresh(){setLoading(true);setError('');try{setSnapshot(await api<IntakeSnapshot>('/api/angelcare-marketplace/admin/intake?'+params()))}catch(e){setError(e instanceof Error?e.message:'Lecture impossible.')}finally{setLoading(false)}}
 useEffect(()=>{if(!mounted.current){mounted.current=true;return}const abort=new AbortController();const timer=setTimeout(()=>{setLoading(true);setError('');void api<IntakeSnapshot>('/api/angelcare-marketplace/admin/intake?'+params(),{signal:abort.signal}).then(setSnapshot).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!abort.signal.aborted)setLoading(false)})},250);return()=>{clearTimeout(timer);abort.abort()}},[source,status,owner,query,page])
 useEffect(()=>()=>detailAbort.current?.abort(),[])
 useEffect(()=>{const params=new URLSearchParams(window.location.search),id=params.get('id'),kind=initialSource||params.get('source');if(id&&['b2b','journey','inquiry','family'].includes(kind||'')&&/^[a-f\d-]{36}$/i.test(id))void open({source_id:id,source_type:kind} as IntakeRow)},[initialSource])
 async function open(row:IntakeRow){detailAbort.current?.abort();const abort=new AbortController();detailAbort.current=abort;setError('');setReason('');setPending(null);setTab('brief');setDossier(null);setLoading(true);try{const data=await api<Dossier>(`/api/angelcare-marketplace/admin/intake/${row.source_type}/${row.source_id}`,{signal:abort.signal});if(!abort.signal.aborted)setDossier(data)}catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Dossier indisponible.')}finally{if(!abort.signal.aborted)setLoading(false)}}
 async function operate(){if(!dossier||!pending||lock.current||reason.trim().length<3)return;lock.current=true;setBusy(true);setError('');try{const data=await api<Dossier>(`/api/angelcare-marketplace/admin/intake/${dossier.row.source_type}/${dossier.row.source_id}`,{method:'PATCH',body:JSON.stringify({action:pending,reason})});setDossier(data);setPending(null);setReason('');setNotice('Action enregistrée dans le dossier.');await refresh()}catch(e){setError(e instanceof Error?e.message:'Action impossible.')}finally{lock.current=false;setBusy(false)}}
 const row=dossier?.row,canManage=row&&snapshot.canManage[row.source_type], pages=Math.max(1,Math.ceil(snapshot.total/snapshot.pageSize))
 return <main className={styles.root} data-ac-operational-intake="r1"><header className={styles.hero}><div><span className={styles.eyebrow}><Inbox size={15}/> ANGELCARE · OPERATIONAL RECEPTION</span><h1>{initialSource==='b2b'?'Chaque projet B2B, un propriétaire et une direction.':'Aucune demande reçue ne doit rester sans direction.'}</h1><p>Commandes, besoins familles et projets organisations : qualifiez le périmètre, suivez le paiement réel et transmettez au bon moteur d’exécution.</p><nav><Link href="/angelcare-marketplace/admin/orders">Commandes <ArrowUpRight size={14}/></Link><Link href="/angelcare-marketplace/admin/customers">Clients <ArrowUpRight size={14}/></Link><Link href="/angelcare-marketplace/admin/payments">Finance <ArrowUpRight size={14}/></Link><Link href="/angelcare-marketplace/admin/conversion/sessions">Parcours à reprendre <ArrowUpRight size={14}/></Link></nav></div><aside className={styles.signal}><ShieldCheck size={27}/><span>RÉCEPTION ≠ PAIEMENT ≠ EXÉCUTION</span><strong>{snapshot.total}</strong><small>dossiers correspondant aux filtres</small><time>Lecture : {new Date(snapshot.generatedAt).toLocaleTimeString('fr-FR')}</time><button onClick={()=>void refresh()} disabled={loading||busy}><RefreshCw size={15}/> Actualiser</button></aside></header>
 <section className={styles.doctrine}><article><Inbox/><div><b>01 · Reçue</b><span>Référence et informations persistées</span></div></article><article><FileCheck2/><div><b>02 · Qualifiée</b><span>Périmètre et prochaine action opérateur</span></div></article><article><BriefcaseBusiness/><div><b>03 · Prise en charge</b><span>Autorité métier, paiement et exécution distincts</span></div></article></section>
 {error?<div className={styles.error} role="alert">{error}<button onClick={()=>void refresh()} disabled={loading}>Réessayer</button></div>:null}{notice?<p className={styles.notice} role="status"><CheckCircle2 size={16}/>{notice}</p>:null}
 <section className={styles.filters}><label><Search size={16}/><input aria-label="Rechercher les dossiers" placeholder="Référence, contact, organisation, email…" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><select aria-label="Origine" value={source} onChange={e=>{setSource(e.target.value);setPage(1)}}><option value="">Toutes les sources autorisées</option>{snapshot.sources.map(s=><option key={s} value={s}>{SOURCE_LABELS[s]}</option>)}</select><select aria-label="État" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}>{['open','all','submitted','awaiting_angelcare','qualified','triaged','converted','pending','closed'].map(s=><option key={s} value={s}>{s==='open'?'Dossiers ouverts':s==='all'?'Tous les états':label(s)}</option>)}</select><select aria-label="Responsabilité" value={owner} onChange={e=>{setOwner(e.target.value);setPage(1)}}><option value="all">Tous propriétaires</option><option value="mine">Pris en charge par moi</option><option value="unassigned">À attribuer</option></select></section>
 <section className={styles.layout} aria-busy={loading}><div className={styles.registry}><header><h2>Registre de réception</h2><span>{snapshot.total} résultat(s) · page {snapshot.page}/{pages}</span></header><div className={styles.records}>{snapshot.rows.map(r=><button key={r.source_type+r.source_id} className={styles.record} data-selected={row?.source_id===r.source_id} onClick={()=>void open(r)}><div className={styles.recordIcon}>{r.source_type==='b2b'?<BriefcaseBusiness/>:<Inbox/>}</div><div><small>{SOURCE_LABELS[r.source_type]} · {r.reference}</small><strong>{r.title}</strong><span>{r.contact_name} · {r.vertical||'Périmètre à préciser'}</span><footer><i data-state={r.status}>{label(r.status)}</i><i>{r.owner_id?'Propriétaire attribué':'À attribuer'}</i></footer></div><aside><b>{amount(r)}</b><span>{label(r.payment_status||'pending')}</span><time>{new Date(r.created_at).toLocaleDateString('fr-FR')}</time><ArrowUpRight size={16}/></aside></button>)}{!snapshot.rows.length&&!loading?<div className={styles.empty}><Inbox size={32}/><h3>Aucun dossier dans ce filtre.</h3><p>Élargissez les critères ou actualisez. Les erreurs de lecture sont affichées séparément.</p></div>:null}</div><footer className={styles.pagination}><button disabled={page<=1||loading} onClick={()=>setPage(p=>p-1)}>Précédent</button><span>{snapshot.page}/{pages}</span><button disabled={page>=pages||loading} onClick={()=>setPage(p=>p+1)}>Suivant</button></footer></div>
 {row?<aside className={styles.dossier}><header><div><span className={styles.eyebrow}>{row.reference}</span><h2>{row.title}</h2><span className={styles.badge}>{label(row.status)}</span></div><button aria-label="Fermer le dossier" disabled={busy} onClick={()=>setDossier(null)}><X size={18}/></button></header><div className={styles.contact}><p><UserRound size={15}/>{row.contact_name}</p>{row.email?<a href={`mailto:${row.email}`}><Mail size={15}/>{row.email}</a>:null}{row.phone?<a href={`https://wa.me/${row.phone.replace(/\D/g,'')}`} target="_blank" rel="noopener noreferrer"><MessageCircle size={15}/>{row.phone}</a>:null}<small>{row.source_route||'Source historique sans route enregistrée'}</small></div><nav className={styles.tabs}>{[['brief','Projet & contexte'],['configuration','Configuration'],['history','Journal']].map(([k,l])=><button key={k} aria-pressed={tab===k} onClick={()=>setTab(k)}>{l}</button>)}</nav>
 {tab==='brief'?<><div className={styles.brief}><strong>{row.source_type==='b2b'?'Besoin organisationnel':'Contexte transmis'}</strong><p>{String(row.source_data.needs||row.source_data.message||row.source_data.location_notes||row.source_data.subtitle||'Consultez la configuration et le dossier métier pour le périmètre complet.')}</p><div><span>Obligation connue</span><b>{amount(row)}</b><span>Finance</span><b>{label(row.payment_status||'not_required')}</b><span>Responsabilité</span><b>{row.owner_id?'Attribuée':'Non attribuée'}</b></div></div><div className={styles.links}><Link href={row.detail_url}>Dossier métier <ArrowUpRight size={14}/></Link>{row.customer_id?<Link href={`/angelcare-marketplace/admin/customers/${row.customer_id}`}>Dossier client</Link>:null}{row.journey_id?<Link href={`/angelcare-marketplace/admin/orders/${row.journey_id}/command`}>Commande liée</Link>:null}{row.source_data.diagnostic_id?<Link href={`/angelcare-marketplace/admin/verticals/organizations/${row.source_data.organization_id}`}>Diagnostic créé</Link>:null}{row.source_data.crm_lead_id?<Link href="/angelcare-marketplace/admin/commercial/leads">Lead CRM créé</Link>:null}{snapshot.canCreateOrder&&['inquiry','family'].includes(row.source_type)?<Link href={`/angelcare-marketplace/admin/orders?${new URLSearchParams(row.source_type==='inquiry'?{inquiry:row.source_id,guestName:row.contact_name,guestEmail:row.email||'',guestPhone:row.phone||''}:{familyRequest:row.source_id,customer:row.customer_id||'',guestName:row.contact_name,guestEmail:row.email||'',guestPhone:row.phone||''}).toString()}`}>Préparer une commande / réservation</Link>:null}</div></>:tab==='configuration'?<DataFields value={row.source_data.configuration||row.source_data.schedule||row.source_data.answers||row.source_data}/>:<div className={styles.timeline}>{dossier?.events.map(e=><article key={e.id}><Clock3 size={15}/><div><b>{e.action.replaceAll('_',' ')}</b><p>{e.reason}</p><time>{new Date(e.created_at).toLocaleString('fr-FR')}</time></div></article>)}{!dossier?.events.length?<p>Aucune action enregistrée dans ce journal. Les historiques métier restent accessibles dans le dossier lié.</p>:null}</div>}
 {canManage?<section className={styles.actionPanel}><h3>Prochaine action légitime</h3><div className={styles.actionGrid}>{actions.filter(([a])=>validAction(row.source_type,row.status,a)&&(!['crm','diagnostic'].includes(a)||snapshot.canConvertB2b)).map(([a,l])=><button key={a} disabled={busy} data-active={pending===a} data-danger={['reject','cancel','archive'].includes(a)} onClick={()=>{setPending(a);setNotice('')}}>{l}</button>)}</div>{pending?<div className={styles.decision}><strong>{actions.find(([a])=>a===pending)?.[1]}</strong><p>{pending==='diagnostic'?'Crée ou retrouve un diagnostic institutionnel lié. Aucun programme ou contrat n’est activé.':pending==='qualify'?'Enregistre la qualification; ne déclare aucun paiement reçu et ne garantit aucune affectation.':'Cette décision sera enregistrée avec votre identité et votre motif.'}</p><label>Motif / prochaine action<textarea value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)}/></label><button className={styles.primary} disabled={busy||reason.trim().length<3} onClick={()=>void operate()}>{busy?'Enregistrement…':'Enregistrer la décision'}<CheckCircle2 size={16}/></button></div>:null}</section>:<p className={styles.readOnly}><ShieldCheck size={15}/> Consultation autorisée. Les décisions nécessitent la permission métier.</p>}</aside>:<aside className={styles.context}><ShieldCheck size={34}/><h2>Ouvrez un dossier pour agir avec son contexte.</h2><p>Le brief, les choix, les contacts, les états financiers et les décisions sont réunis ici. Un paiement en attente ne signifie pas une demande perdue.</p><Link href="/angelcare-marketplace/admin/verticals/requests">Réception B2B <ArrowUpRight size={15}/></Link><Link href="/angelcare-marketplace/admin/family-requests">Family Command <ArrowUpRight size={15}/></Link></aside>}</section></main>
}
