'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CheckCircle2, Circle, Code2, Database, Download, Eye, Gauge, GitBranch, History, KeyRound, Layers3, Loader2, Network, Play, Plus, RefreshCw, RotateCcw, Save, Search, ShieldAlert, ShieldCheck, SlidersHorizontal, Trash2, Workflow, X, Zap } from 'lucide-react'
import styles from '../SaasFactoryCommandCenter.module.css'
import { factoryPages } from '@/lib/saas-factory/data'
import { seedActions } from '@/lib/saas-factory/actions-runtime'

type Action = typeof seedActions[number]
type Summary = { sourceConfidence:string; lastRefreshedAt:string; metrics:any; actions:Action[]; categories:any[]; modules:any[]; policies:any[]; dependencies:any[]; executions:any[]; warnings:any[]; recommendations:any[]; disabledActions:any[] }
type Workflow = null | { key:'control'|'register'|'detail'|'policy'|'bulk'|'history'|'rollback'|'safety'|'export'; title:string; action?:Action }

function buildFallback(): Summary {
  const actions = seedActions
  const categories = Array.from(new Set(actions.map((a) => a.category))).map((name) => ({ id: `cat_${name}`, name, count: actions.filter((a) => a.category === name).length }))
  const dependencies = actions.map((a) => ({ actionKey: a.key, dependsOn: a.dependencies, blocks: actions.filter((x) => x.dependencies.includes(a.key)).map((x) => x.key), blockers: a.blockers, status: a.blockers.length ? 'blocked' : a.dependencies.length ? 'warning' : 'clear' }))
  const policies = actions.flatMap((a) => [
    { id: `roles_${a.key}`, actionKey: a.key, rule: 'role_clearance', status: a.allowedRoles.length ? 'passed' : 'blocked', detail: a.allowedRoles.join(', ') || 'No roles configured.', requiredFix: 'Add allowed roles.' },
    { id: `endpoint_${a.key}`, actionKey: a.key, rule: 'endpoint_scope', status: a.endpoint.startsWith('/api/saas-factory/') ? 'passed' : 'warning', detail: a.endpoint, requiredFix: 'Use SaaS Factory API namespace.' },
    { id: `blockers_${a.key}`, actionKey: a.key, rule: 'blockers', status: a.blockers.length ? 'blocked' : 'passed', detail: a.blockers.join(', ') || 'No blockers.', requiredFix: 'Resolve blockers.' },
  ])
  return {
    sourceConfidence: 'client-fallback',
    lastRefreshedAt: new Date().toISOString(),
    metrics: {
      totalActions: actions.length,
      readyActions: actions.filter((a) => a.status === 'ready').length,
      reviewActions: actions.filter((a) => a.status === 'requires_review').length,
      blockedActions: actions.filter((a) => a.status === 'blocked').length,
      criticalActions: actions.filter((a) => a.risk === 'critical').length,
      executions: 0,
      failedExecutions: 0,
      readinessScore: 42,
      dryRunCapable: actions.filter((a) => a.requiresDryRun).length,
      rollbackCapable: actions.filter((a) => a.rollbackAvailable).length,
      payloadActions: actions.filter((a) => a.requiresPayload).length,
    },
    actions, categories, modules: [], policies, dependencies, executions: [], warnings: [], recommendations: [], disabledActions: [],
  }
}

function arr<T>(v:any): T[] { return Array.isArray(v) ? v : [] }
function norm(input:any): Summary {
  if (!input || !Array.isArray(input.actions) || input.actions.length === 0) return buildFallback()
  return { ...buildFallback(), ...input, sourceConfidence: String(input.sourceConfidence ?? input.source ?? 'runtime'), actions: arr(input.actions), categories: arr(input.categories), modules: arr(input.modules), policies: arr(input.policies), dependencies: arr(input.dependencies), executions: arr(input.executions), warnings: arr(input.warnings), recommendations: arr(input.recommendations), disabledActions: arr(input.disabledActions), metrics: { ...buildFallback().metrics, ...(input.metrics ?? {}) } }
}
const iconMap: Record<string, any> = { Circle, Database, Gauge, Network, ShieldCheck, SlidersHorizontal, Workflow }
function IconFor({name}:{name:string}){ const Icon=iconMap[name]||Circle; return <Icon size={18}/> }
function Pill({value}:{value:string}){ const v=String(value||'unknown'); const cls=['ready','success','passed','low','clear','preview'].includes(v)?styles.pillGreen:['requires_review','warning','medium','queued','running'].includes(v)?styles.pillYellow:['blocked','failed','critical','high','disabled'].includes(v)?styles.pillRed:styles.pillPurple; return <span className={`${styles.pill} ${cls}`}>{v.replace(/_/g,' ')}</span> }
function Metric({label,value,sub,icon}:{label:string;value:any;sub:string;icon:any}){ return <div className={styles.metric}><div className={styles.metricTop}><span>{label}</span><span className={styles.info}>{icon}</span></div><div className={styles.metricValue}>{value}</div><div className={styles.metricSub}>{sub}</div></div> }
function Card({title,subtitle,span=4,children,action}:{title:string;subtitle?:string;span?:number;children:any;action?:any}){ return <section className={`${styles.card} ${styles[`span${span}` as keyof typeof styles]||styles.span4}`}><div className={styles.cardPad}><div className={styles.cardTitle}><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>{children}</div></section> }

export default function SaasFactoryActionsCommandCenter(){
  const [summary,setSummary]=useState<Summary>(buildFallback()),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState(''),[workflow,setWorkflow]=useState<Workflow>(null),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[risk,setRisk]=useState('all'),[selected,setSelected]=useState<string[]>([])
  async function refresh(){
    setLoading(true); setError('')
    try{
      const r=await fetch('/api/saas-factory/actions/summary',{cache:'no-store'})
      const text=await r.text()
      let data:any
      try { data=JSON.parse(text) } catch { throw new Error(`Actions API returned HTML/non-JSON: ${text.slice(0,80)}`) }
      setSummary(norm(data))
    }catch(e){
      setError(e instanceof Error?e.message:'Unable to load actions API. Using client fallback registry.')
      setSummary(buildFallback())
    }finally{ setLoading(false) }
  }
  useEffect(()=>{refresh()},[])
  const s=norm(summary); const actions=s.actions; const filtered=useMemo(()=>actions.filter(a=>(category==='all'||a.category===category)&&(risk==='all'||a.risk===risk)&&(!query||`${a.key} ${a.label} ${a.description} ${a.module} ${a.endpoint}`.toLowerCase().includes(query.toLowerCase()))),[actions,category,risk,query])
  async function execute(actionKey:string,payload:any={},mode='execute'){
    setBusy(true); setError('')
    try{ const r=await fetch('/api/saas-factory/actions/execute',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actionKey,payload,actor:'SaaS Factory Operator',mode})}); const result=await r.json(); if(!result.ok)setError(result.message||'Action blocked'); else setToast(result.message||'Action completed'); await refresh(); return result }catch(e){ const m=e instanceof Error?e.message:'Execution failed'; setError(m); return {ok:false,message:m} }finally{setBusy(false)}
  }
  function toggle(key:string){setSelected(c=>c.includes(key)?c.filter(x=>x!==key):[...c,key])}

  return <div className={styles.shell}>
    <aside className={styles.sidebar}><div className={styles.brand}><div className={styles.mark}/><div><div className={styles.brandTitle}>ANGELCARE</div><div className={styles.brandSub}>SAAS FACTORY COMMAND</div></div></div><div className={styles.navLabel}>Command Center</div>{factoryPages.map(item=><Link key={item.key} className={`${styles.navItem} ${item.key==='actions'?styles.navActive:''}`} href={item.href}><IconFor name={item.icon}/>{item.label}</Link>)}<div className={styles.sideCard}><div className={styles.navLabel} style={{marginTop:0}}>Actions Clearance</div><div>Source: <b>{s.sourceConfidence.toUpperCase()}</b></div><div className={styles.statusRing}><div className={styles.statusRingInner}><div><b>{s.metrics.readinessScore}%</b><br/><small>Readiness</small></div></div></div><div className={styles.up}>● {s.metrics.readyActions} ready</div><div className={s.metrics.blockedActions?styles.warn:styles.up}>● {s.metrics.blockedActions} blocked</div></div></aside>
    <main className={styles.main}><div className={styles.topbar}><div><div className={styles.titleRow}><h1 className={styles.title}>Actions Command Center</h1><span className={styles.liveBadge}>{s.sourceConfidence.toUpperCase()}</span></div><div className={styles.subtitle}>Action control room: dry-run, payload contract, permissions, dependencies, impact, rollback, execution and audit.</div></div><div className={styles.controls}><button className={styles.button} onClick={refresh}>{loading?<Loader2 size={16}/>:<RefreshCw size={16}/>} Refresh</button><button className={`${styles.button} ${styles.primary}`} onClick={()=>setWorkflow({key:'register',title:'Register Governed Action'})}><Plus size={16}/> Register</button><button className={styles.button} onClick={()=>setWorkflow({key:'export',title:'Export Actions'})}><Download size={16}/> Export</button></div></div>
    {error&&<div className={styles.livePanel} style={{borderColor:'rgba(248,113,113,.38)'}}><AlertTriangle size={16}/> {error}</div>}
    <div className={styles.metricGrid}><Metric label="Actions" value={s.metrics.totalActions} sub="registered" icon={<Workflow size={16}/>}/><Metric label="Ready" value={s.metrics.readyActions} sub="clear to run" icon={<CheckCircle2 size={16}/>}/><Metric label="Review" value={s.metrics.reviewActions} sub="needs approval" icon={<ShieldCheck size={16}/>}/><Metric label="Blocked" value={s.metrics.blockedActions} sub="safety gated" icon={<ShieldAlert size={16}/>}/><Metric label="Dry-run" value={s.metrics.dryRunCapable} sub="preview capable" icon={<Play size={16}/>}/><Metric label="Rollback" value={s.metrics.rollbackCapable} sub="recoverable" icon={<RotateCcw size={16}/>}/><Metric label="Payloads" value={s.metrics.payloadActions} sub="schema actions" icon={<Code2 size={16}/>}/><Metric label="Readiness" value={`${s.metrics.readinessScore}%`} sub="clearance" icon={<Gauge size={16}/>}/></div>
    <div className={styles.grid}>
      <Card title="Action Registry" subtitle="Every row opens a real control room with dry-run, execute, policy, impact and rollback" span={8} action={<button className={`${styles.button} ${styles.primary}`} onClick={()=>setWorkflow({key:'register',title:'Register Governed Action'})}><Plus size={16}/> Action</button>}><div className={styles.toolbar}><div className={styles.searchBox}><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search actions, modules, endpoints..."/></div><select className={styles.input} value={category} onChange={e=>setCategory(e.target.value)}><option value="all">all categories</option>{s.categories.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select><select className={styles.input} value={risk} onChange={e=>setRisk(e.target.value)}><option value="all">all risks</option><option>low</option><option>medium</option><option>high</option><option>critical</option></select><button className={styles.button} onClick={()=>setWorkflow({key:'bulk',title:'Bulk Action Control'})}><Layers3 size={16}/> Bulk</button></div><div className={styles.liveTableWrap}><table className={styles.table}><thead><tr><th></th><th>Action</th><th>Module</th><th>Endpoint</th><th>Status</th><th>Risk</th><th>Dry-run</th><th>Rollback</th><th>Actions</th></tr></thead><tbody>{filtered.map((a,i)=><tr key={`${a.key}-${i}`}><td><input type="checkbox" checked={selected.includes(a.key)} onChange={()=>toggle(a.key)}/></td><td><b>{a.label}</b><br/><small>{a.key}</small></td><td>{a.module}</td><td><code>{a.endpoint}</code><br/><small>{a.method}</small></td><td><Pill value={a.status}/></td><td><Pill value={a.risk}/></td><td>{a.requiresDryRun?'required':'optional'}</td><td>{a.rollbackAvailable?'yes':'no'}</td><td><button className={styles.button} onClick={()=>setWorkflow({key:'control',title:'Action Control Room',action:a})}><Zap size={14}/> Control</button><button className={styles.button} onClick={()=>setWorkflow({key:'detail',title:'Action Evidence Room',action:a})}><Eye size={14}/> View</button></td></tr>)}</tbody></table></div></Card>
      <Card title="Operational Workflows" subtitle="No generic modal: each path is policy and impact-aware" span={4}>{[['register','Register Action','Create action with endpoint, schema and approval.',<Plus size={16}/>],['policy','Policy Matrix','Validate role, dry-run, endpoint and blockers.',<ShieldCheck size={16}/>],['bulk','Bulk Control','Preview selected action group safely.',<Layers3 size={16}/>],['history','Execution Evidence','Payloads, evidence, result and impact.',<History size={16}/>],['rollback','Rollback Center','Checkpoint and eligibility logic.',<RotateCcw size={16}/>],['safety','Safety Gates','Emergency freeze and hard delete blocked evidence.',<ShieldAlert size={16}/>]].map(([key,title,detail,icon])=><button key={String(key)} className={styles.feedItem} style={{width:'100%',color:'inherit',cursor:'pointer'}} onClick={()=>setWorkflow({key:key as any,title:String(title)})}><span className={styles.info}>{icon}</span><div><b>{title}</b><br/><small>{detail}</small></div></button>)}</Card>
      <Card title="Dependency Graph" subtitle="What blocks or depends on each action" span={4}>{s.dependencies.map((d:any)=><div className={styles.feedItem} key={d.actionKey}><GitBranch size={16}/><div><b>{d.actionKey}</b><br/><small>depends: {d.dependsOn.join(', ')||'none'} · blocks: {d.blocks.join(', ')||'none'}</small></div><Pill value={d.status}/></div>)}</Card>
      <Card title="Policy Matrix" subtitle="Role, endpoint, dry-run, confirmation and blocker validation" span={4}>{s.policies.slice(0,10).map((p:any)=><div className={styles.feedItem} key={p.id}><span className={p.status==='passed'?styles.dot:p.status==='blocked'?styles.dotBad:styles.dotWarn}/><div><b>{p.actionKey}</b><br/><small>{p.rule} · {p.detail}</small></div></div>)}</Card>
      <Card title="Execution Evidence" subtitle="Audit-grade history of dry-runs, blocked attempts and real executions" span={4}>{s.executions.slice(0,8).map((e:any)=><div className={styles.feedItem} key={e.id}><History size={16}/><div><b>{e.label}</b><br/><small>{e.status} · {e.result}</small></div><Pill value={e.status}/></div>)}</Card>
    </div></main>
    {workflow&&<ActionModal workflow={workflow} summary={s} selected={selected} busy={busy} onClose={()=>setWorkflow(null)} execute={execute}/>}
    {toast&&<div className={styles.toast} onClick={()=>setToast('')}>{toast}</div>}
  </div>
}

function ActionModal({workflow,summary,selected,busy,onClose,execute}:{workflow:Workflow;summary:Summary;selected:string[];busy:boolean;onClose:()=>void;execute:(key:string,payload?:any,mode?:string)=>Promise<any>}){
  const action=workflow?.action; const [payload,setPayload]=useState<any>({}); const [form,setForm]=useState<any>({label:'',key:'',description:'',category:'custom',module:'saas-factory',page:'/saas-factory-command/actions',endpoint:'/api/saas-factory/actions/execute',method:'POST',risk:'medium',reason:''})
  function up(k:string,v:any){setPayload((c:any)=>({...c,[k]:v}))} function uf(k:string,v:any){setForm((c:any)=>({...c,[k]:v}))}
  return <div className={styles.modalBackdrop}><div className={styles.modal} style={{width:'min(1380px,98vw)',maxHeight:'92vh',overflow:'auto'}}><div className={styles.cardTitle}><div><h3>{workflow?.title}</h3><p>Operational action workflow · readiness {summary.metrics.readinessScore}% · source {summary.sourceConfidence}</p></div><button className={styles.button} onClick={onClose}><X size={16}/> Close</button></div>
    {workflow?.key==='control'&&action&&<div className={styles.grid}><Card title="1. Execution Identity" span={4}><div className={styles.feedItem}><Zap size={18}/><div><b>{action.label}</b><br/><small>{action.key}</small></div><Pill value={action.status}/></div><p>{action.description}</p><div className={styles.livePanel}>Owner {action.owner} · SLA {action.sla}</div></Card><Card title="2. Payload Builder" span={4}>{action.payloadSchema.length===0?<div className={styles.emptyLiveState}>No payload required.</div>:action.payloadSchema.map(f=><label key={f.key}>{f.label}{f.type==='textarea'?<textarea className={styles.textarea} value={payload[f.key]??''} onChange={e=>up(f.key,e.target.value)} placeholder={f.placeholder}/>:<input className={styles.input} value={payload[f.key]??''} onChange={e=>up(f.key,e.target.value)} placeholder={f.placeholder}/>}</label>)}{action.requiresDryRun&&<label style={{display:'flex',gap:8,alignItems:'center',marginTop:8}}><input type="checkbox" checked={Boolean(payload.dryRunAccepted)} onChange={e=>up('dryRunAccepted',e.target.checked)}/> Dry-run reviewed and accepted</label>}</Card><Card title="3. Impact & Clearance" span={4}><div className={styles.feedItem}><Database size={16}/><div><b>Tables</b><br/><small>{action.affectedTables.join(', ')||'none'}</small></div></div><div className={styles.feedItem}><Network size={16}/><div><b>Modules</b><br/><small>{action.affectedModules.join(', ')||'none'}</small></div></div><div className={styles.feedItem}><KeyRound size={16}/><div><b>Roles</b><br/><small>{action.allowedRoles.join(', ')||'none'}</small></div></div><div className={styles.feedItem}><RotateCcw size={16}/><div><b>Rollback</b><br/><small>{action.rollbackPlan||'not available'}</small></div></div></Card><Card title="4. Execute Path" span={12}><button className={styles.button} disabled={busy} onClick={()=>execute(action.key,payload,'dry_run')}><Play size={16}/> Dry-run preview</button><button className={`${styles.button} ${action.risk==='critical'?styles.danger:styles.primary}`} disabled={busy} onClick={()=>execute(action.key,payload,'execute')}><Zap size={16}/> Execute with audit</button></Card></div>}
    {workflow?.key==='register'&&<div className={styles.grid}><Card title="Register Action" span={6}><div className={styles.modalGrid}>{['label','key','category','module','endpoint','page','reason'].map(k=><label key={k}>{k}<input className={styles.input} value={form[k]??''} onChange={e=>uf(k,e.target.value)}/></label>)}<label>Risk<select className={styles.input} value={form.risk} onChange={e=>uf('risk',e.target.value)}><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label></div><textarea className={styles.textarea} value={form.description} onChange={e=>uf('description',e.target.value)} placeholder="Operational description and impact."/></Card><Card title="Governance Preview" span={6}><div className={styles.livePanel}><ShieldCheck size={16}/> New actions are review-required, dry-run gated and auditable.</div><button className={`${styles.button} ${styles.primary}`} disabled={busy} onClick={()=>execute('register_action',form,'register')}><Save size={16}/> Register action</button></Card></div>}
    {workflow?.key==='detail'&&action&&<div className={styles.grid}><Card title="Action Contract" span={6}><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(action,null,2)}</pre></Card><Card title="Related Policies" span={6}>{summary.policies.filter((p:any)=>p.actionKey===action.key).map((p:any)=><div className={styles.feedItem} key={p.id}><span className={p.status==='passed'?styles.dot:p.status==='blocked'?styles.dotBad:styles.dotWarn}/><div><b>{p.rule}</b><br/><small>{p.detail}</small></div><Pill value={p.status}/></div>)}</Card></div>}
    {workflow?.key==='policy'&&<div className={styles.liveTableWrap}><table className={styles.table}><thead><tr><th>Action</th><th>Rule</th><th>Status</th><th>Detail</th><th>Fix</th></tr></thead><tbody>{summary.policies.map((p:any)=><tr key={p.id}><td>{p.actionKey}</td><td>{p.rule}</td><td><Pill value={p.status}/></td><td>{p.detail}</td><td>{p.requiredFix}</td></tr>)}</tbody></table></div>}
    {workflow?.key==='bulk'&&<div><div className={styles.livePanel}><Layers3 size={16}/> {selected.length} selected action(s). Bulk mutation is blocked; validation and dry-run previews are allowed.</div><button className={styles.button} onClick={()=>execute('validate_action_registry',{selectedKeys:selected},'policy')}><ShieldCheck size={16}/> Validate selected</button><button className={styles.button} onClick={()=>execute('sync_options_runtime',{targetGroup:'selected_actions',reason:`Bulk dry-run for ${selected.length} actions`,dryRunAccepted:true},'dry_run')}><Play size={16}/> Dry-run selected</button></div>}
    {workflow?.key==='history'&&<div className={styles.liveTableWrap}><table className={styles.table}><thead><tr><th>Action</th><th>Status</th><th>Mode</th><th>Actor</th><th>Payload</th><th>Impact</th><th>Result</th></tr></thead><tbody>{summary.executions.map((e:any)=><tr key={e.id}><td>{e.label}</td><td><Pill value={e.status}/></td><td>{e.mode}</td><td>{e.actor}</td><td><code>{JSON.stringify(e.payload)}</code></td><td>{[...e.impact.modules,...e.impact.tables].join(', ')}</td><td>{e.result}</td></tr>)}</tbody></table></div>}
    {workflow?.key==='rollback'&&<div><div className={styles.emptyLiveState}><RotateCcw size={22}/><b>Rollback center</b><p>Rollback is action-specific. Generic rollback is blocked unless checkpoint evidence exists.</p></div><button className={styles.button} onClick={()=>execute('sync_options_runtime',{targetGroup:'rollback_preview',reason:'Rollback eligibility preview',dryRunAccepted:true},'dry_run')}><RotateCcw size={16}/> Preview eligibility</button></div>}
    {workflow?.key==='safety'&&<div className={styles.grid}><Card title="Emergency Freeze" span={6}><button className={`${styles.button} ${styles.danger}`} onClick={()=>execute('emergency_freeze',{reason:'Manual operator request',duration:'manual'})}><ShieldAlert size={16}/> Attempt freeze</button></Card><Card title="Hard Delete Block" span={6}><button className={`${styles.button} ${styles.danger}`} onClick={()=>execute('hard_delete_action',{actionKey:'manual_attempt',reason:'operator test'})}><Trash2 size={16}/> Audit blocked delete</button></Card></div>}
    {workflow?.key==='export'&&<div><a className={`${styles.button} ${styles.primary}`} href="/api/saas-factory/actions/export?format=json"><Download size={16}/> JSON</a><a className={styles.button} href="/api/saas-factory/actions/export?format=csv"><Download size={16}/> CSV</a></div>}
  </div></div>
}
