import type { AmbassadorProgramSnapshot, AmbassadorTierRule } from "./ambassador-program-types";

export const defaultTierRules: AmbassadorTierRule[] = [
  {
    tier: "bronze",
    label: "Bronze Ambassador",
    minHealthScore: 60,
    minApprovedProofs: 0,
    minRevenueMad: 0,
    commissionRate: 3,
    monthlyBonusMad: 0,
    permissions: ["basic_missions", "training_access"],
  },
  {
    tier: "silver",
    label: "Silver Ambassador",
    minHealthScore: 70,
    minApprovedProofs: 5,
    minRevenueMad: 5000,
    commissionRate: 5,
    monthlyBonusMad: 250,
    permissions: ["basic_missions", "priority_missions", "training_access"],
  },
  {
    tier: "gold",
    label: "Gold Ambassador",
    minHealthScore: 80,
    minApprovedProofs: 15,
    minRevenueMad: 20000,
    commissionRate: 7,
    monthlyBonusMad: 600,
    permissions: ["priority_missions", "campaign_leads", "training_access"],
  },
  {
    tier: "platinum",
    label: "Platinum Ambassador",
    minHealthScore: 88,
    minApprovedProofs: 35,
    minRevenueMad: 60000,
    commissionRate: 9,
    monthlyBonusMad: 1200,
    permissions: ["premium_missions", "campaign_leads", "mentor_access"],
  },
  {
    tier: "elite",
    label: "Elite Ambassador",
    minHealthScore: 92,
    minApprovedProofs: 60,
    minRevenueMad: 120000,
    commissionRate: 12,
    monthlyBonusMad: 2500,
    permissions: ["premium_missions", "regional_activation", "mentor_access"],
  },
];

export const ambassadorProgramSnapshot: AmbassadorProgramSnapshot = {
  programs: [
    {
      id: "program-healthcare",
      name: "Healthcare Influence Ambassador Program",
      type: "healthcare",
      status: "active",
      owner: "Ambassador Director",
      cityScope: ["Rabat", "Casablanca", "Marrakech"],
      activeAmbassadors: 73,
      targetAmbassadors: 120,
      eligibilityRules: [
        { id: "elig-health", label: "Health score minimum", metric: "health_score", operator: "gte", value: 75, required: true },
        { id: "elig-proof", label: "Proof approval rate", metric: "proof_approval_rate", operator: "gte", value: 80, required: true },
        { id: "elig-compliance", label: "Compliance cases maximum", metric: "compliance_cases", operator: "lte", value: 1, required: true },
      ],
      tierRules: defaultTierRules,
      rewardRules: [
        {
          id: "reward-proof",
          name: "Approved proof bonus",
          type: "fixed_bonus",
          trigger: "proof_approved",
          amountMad: 75,
          status: "active",
          financeApprovalRequired: false,
        },
        {
          id: "reward-conversion",
          name: "Converted lead commission",
          type: "commission",
          trigger: "lead_converted",
          commissionRate: 7,
          status: "active",
          financeApprovalRequired: true,
        },
      ],
      policies: [
        {
          id: "policy-healthcare",
          name: "Healthcare safe communication policy",
          description: "All healthcare messaging must follow approved claims and proof requirements.",
          proofRequired: true,
          maxMissionsPerWeek: 4,
          minimumTrainingLevel: "silver",
          payoutCycle: "monthly",
          complianceReviewRequired: true,
          managerApprovalRequired: true,
        },
      ],
    },
    {
      id: "program-academy",
      name: "AngelCare Academy Referral Program",
      type: "academy",
      status: "active",
      owner: "Academy Growth Manager",
      cityScope: ["Casablanca", "Rabat", "Fes", "Agadir"],
      activeAmbassadors: 48,
      targetAmbassadors: 90,
      eligibilityRules: [
        { id: "elig-training", label: "Training score", metric: "training_score", operator: "gte", value: 82, required: true },
        { id: "elig-participation", label: "Campaign participation", metric: "campaign_participation", operator: "gte", value: 70, required: true },
      ],
      tierRules: defaultTierRules,
      rewardRules: [
        {
          id: "reward-academy-lead",
          name: "Academy qualified lead reward",
          type: "fixed_bonus",
          trigger: "lead_converted",
          amountMad: 150,
          status: "active",
          financeApprovalRequired: true,
        },
      ],
      policies: [
        {
          id: "policy-academy",
          name: "Academy referral policy",
          description: "Ambassadors must use approved academy scripts and lead qualification forms.",
          proofRequired: true,
          maxMissionsPerWeek: 5,
          minimumTrainingLevel: "bronze",
          payoutCycle: "biweekly",
          complianceReviewRequired: false,
          managerApprovalRequired: true,
        },
      ],
    },
  ],
  governance: [
    {
      id: "gov-001",
      title: "Healthcare program requires strict compliance review",
      area: "compliance",
      severity: "critical",
      owner: "Compliance Manager",
      status: "open",
      recommendation: "Keep healthcare program manager approval required and block missions for unresolved compliance cases.",
    },
    {
      id: "gov-002",
      title: "Academy payout cycle may increase finance workload",
      area: "finance",
      severity: "medium",
      owner: "Finance Operations",
      status: "reviewing",
      recommendation: "Monitor payout volume before scaling biweekly rewards across all cities.",
    },
  ],
};
