'use client'
import Link from 'next/link'
import { useEffect,useState } from 'react'
import { Activity, BadgeDollarSign, MessageSquareText, ShoppingBag } from 'lucide-react'
import type { BusinessPulseSnapshot } from '../types'
import styles from '../enterprise-command.module.css'
type Envelope<T>={data:T}
export function BusinessPulseCommand(){const[data,setData]=useState<BusinessPulseSnapshot|null>(null);useEffect(()=>{let t:any;const load=()=>{if(document.visibilityState!=='visible')return;fetch('/api/angelcare-marketplace/admin/enterprise-command/pulse',{cache:'no-store'}).then(r=>r.json()).then((p:Envelope<BusinessPulseSnapshot>)=>p.data&&setData(p.data)).catch(()=>{})};load();t=setInterval(load,20000);return()=>clearInterval(t)},[]);return <div className={styles.command}><section className={styles.hero}><div className={styles.eyebrow}>Live Business Pulse</div><h1 className={styles.title}>Le Marketplace raconte ce qui se passe maintenant</h1><p className={styles.lead}>Événements bornés, visibility-aware, sans boucle milliseconde : commandes, paiements, demandes et fulfillment.</p></section><div className={styles.metricGrid}><M icon={<ShoppingBag/>} label="Nouvelles commandes" v={data?.newOrders||0}/><M icon={<BadgeDollarSign/>} label="Paiements capturés" v={data?.capturedPayments||0}/><M icon={<MessageSquareText/>} label="Demandes" v={data?.newInquiries||0}/><M icon={<Activity/>} label="Fulfillment actif" v={data?.activeFulfillment||0}/></div><div className={styles.panel}><div className={styles.timeline}>{data?.events.map(e=><Link href={e.route} key={`${e.kind}-${e.id}`} className={styles.event} style={{textDecoration:'none',color:'inherit'}}><i className={styles.eventDot}/><div><strong>{e.title}</strong><div className={styles.muted}>{e.reference} · {e.subtitle} · {new Date(e.occurredAt).toLocaleString('fr-FR')}</div></div></Link>)}</div></div></div>}
function M({icon,label,v}:{icon:React.ReactNode;label:string;v:number}){return <div className={styles.metric}>{icon}<strong>{v}</strong><span>{label}</span></div>}
