'use client'
import Link from 'next/link'
import { useEffect,useMemo,useState } from 'react'
import { AlertTriangle, CheckCircle2, Clock3, Navigation, RefreshCcw, ShieldCheck, Sparkles, Truck, UserRoundCheck } from 'lucide-react'
import type { FulfillmentMission, FulfillmentMissionSnapshot } from '../types'
import type { AssignmentProposal, MissionDossierData, OperationsMission } from '../../operations-execution/types'
import styles from '../enterprise-command.module.css'
type Row=Record<string,unknown>; type Envelope<T>={data:T}
const txt=(r:Row|null|undefined,k:string)=>String(r?.[k]??'')
export function FulfillmentMissionControl(){
 const[data,setData]=useState<FulfillmentMissionSnapshot|null>(null),[selected,setSelected]=useState<FulfillmentMission|null>(null),[ops,setOps]=useState<MissionDossierData|null>(null),[providers,setProviders]=useState<Row[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 async function load(){try{const [r,pr]=await Promise.all([fetch('/api/angelcare-marketplace/admin/enterprise-command/missions',{cache:'no-store'}),fetch('/api/angelcare-marketplace/operations/providers',{cache:'no-store'})]);const p=await r.json() as Envelope<FulfillmentMissionSnapshot>;const pp=await pr.json() as Envelope<Row[]>;if(r.ok&&p.data){setData(p.data);if(selected){const fresh=p.data.missions.find(m=>m.id===selected.id);if(fresh){setSelected(fresh);if(fresh.operationsMissionId)void loadMission(fresh.operationsMissionId)}}}if(pr.ok&&Array.isArray(pp.data))setProviders(pp.data)}catch{}}
 async function loadMission(id:string){try{const r=await fetch(`/api/angelcare-marketplace/operations/missions/${id}`,{cache:'no-store'});const p=await r.json() as Envelope<MissionDossierData>;if(r.ok&&p.data)setOps(p.data)}catch{setOps(null)}}
 useEffect(()=>{let timer:ReturnType<typeof setInterval>;void load();timer=setInterval(()=>{if(document.visibilityState==='visible')void load()},25000);return()=>clearInterval(timer)},[])
 function pick(m:FulfillmentMission){setSelected(m);setOps(null);if(m.operationsMissionId)void loadMission(m.operationsMissionId)}
 async function ensureMission(){if(!selected)return null;if(selected.operationsMissionId){await loadMission(selected.operationsMissionId);return selected.operationsMissionId}setBusy(true);setNotice('');try{const start=selected.scheduledAt||new Date(Date.now()+3600000).toISOString();const end=selected.scheduledEndAt||new Date(new Date(start).getTime()+2*3600000).toISOString();const r=await fetch('/api/angelcare-marketplace/operations/missions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sourceType:'marketplace_journey',sourceId:selected.id,familyAccountId:selected.familyAccountId,territoryId:selected.territory,serviceType:selected.journeyType||'marketplace_service',title:selected.title,scheduledStart:start,scheduledEnd:end,timezone:'Africa/Casablanca',location:{customer:selected.customer,orderReference:selected.reference},operationalZone:selected.territory})});const p=await r.json().catch(()=>({})) as Envelope<OperationsMission>&{error?:{message?:string}};if(!r.ok||!p.data){setNotice(p.error?.message||'Création mission impossible.');return null}setNotice(`Mission opérationnelle ${p.data.public_reference} créée et reliée à la commande.`);await load();await loadMission(p.data.id);return p.data.id}finally{setBusy(false)}}
 async function generateProposals(){const missionId=await ensureMission();if(!missionId)return;setBusy(true);try{const r=await fetch(`/api/angelcare-marketplace/operations/missions/${missionId}/dispatch`,{method:'POST'});const p=await r.json().catch(()=>({})) as {error?:{message?:string}};if(!r.ok){setNotice(p.error?.message||'Scoring provider impossible.');return}setNotice('Scoring provider exécuté sur éligibilité, territoire, disponibilité et conflits.');await loadMission(missionId);await load()}finally{setBusy(false)}}
 async function decide(proposal:AssignmentProposal,decision:'accept'|'reject'){setBusy(true);try{const r=await fetch(`/api/angelcare-marketplace/operations/proposals/${proposal.id}/decision`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({decision,reason:`Décision depuis Mission Control · ${selected?.reference}`})});const p=await r.json().catch(()=>({})) as {error?:{message?:string}};if(!r.ok){setNotice(p.error?.message||'Décision impossible.');return}if(decision==='accept'&&selected){const provider=providers.find(x=>txt(x,'provider_id')===proposal.provider_id);await fetch(`/api/angelcare-marketplace/admin/enterprise-command/orders/${selected.id}/operate`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({providerId:proposal.provider_id,providerName:txt(provider,'display_name')||proposal.provider_id,providerSnapshot:provider||{},fulfillmentStatus:'assigned',nextActionLabel:'Provider assigné · préparer mission',reason:'Accepted scored provider proposal'})})}setNotice(decision==='accept'?'Provider assigné depuis proposition scorée.':'Proposition rejetée et conservée dans la preuve dispatch.');if(ops)await loadMission(ops.mission.id);await load()}finally{setBusy(false)}}
 async function transition(nextStatus:string){if(!ops)return;setBusy(true);try{const r=await fetch(`/api/angelcare-marketplace/operations/missions/${ops.mission.id}/transition`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({nextStatus,reason:`Mission Control · ${selected?.reference}`})});const p=await r.json().catch(()=>({})) as {error?:{message?:string}};if(!r.ok){setNotice(p.error?.message||'Transition impossible.');return}setNotice(`Mission passée à ${nextStatus}.`);await loadMission(ops.mission.id);await load()}finally{setBusy(false)}}
 const lanes=useMemo(()=>({prepare:data?.missions.filter(m=>['confirmed','preparation','assigned','scheduled'].includes(m.status))||[],active:data?.missions.filter(m=>['execution','in_progress'].includes(m.status))||[],blocked:data?.missions.filter(m=>['blocked','recovery'].includes(m.status))||[],done:data?.missions.filter(m=>m.status==='completed').slice(0,30)||[]}),[data])
 return <div className={styles.command}><section className={styles.hero}><div className={styles.panelTitle}><div><div className={styles.eyebrow}>Fulfillment Mission Control · Authoritative Dispatch</div><h1 className={styles.title}>Scoring provider, assignation, preuve, exécution & recovery</h1><p className={styles.lead}>La vue commande est reliée au moteur Operations Execution existant : missions canoniques, propositions scorées, conflits, acceptation provider, incidents et dossier fulfillment.</p></div><button className={styles.buttonSecondary} onClick={()=>void load()}><RefreshCcw size={14}/>Actualiser</button></div></section>
 <div className={styles.metricGrid}><M icon={<Clock3/>} label="À préparer" v={data?.pending||0}/><M icon={<Navigation/>} label="En exécution" v={data?.active||0}/><M icon={<AlertTriangle/>} label="Bloquées" v={data?.blocked||0}/><M icon={<CheckCircle2/>} label="Terminées aujourd’hui" v={data?.completedToday||0}/></div>
 <div className={styles.missionBoard}>{Object.entries(lanes).map(([key,items])=><section className={styles.missionLane} key={key}><div className={styles.panelTitle}><h3>{key==='prepare'?'Préparation':key==='active'?'Exécution':key==='blocked'?'Exceptions / Recovery':'Terminées'}</h3><span className={styles.chip}>{items.length}</span></div>{items.map(m=><button key={m.id} className={`${styles.missionCard} ${selected?.id===m.id?styles.missionCardActive:''}`} onClick={()=>pick(m)}><strong>{m.reference}</strong><span>{m.customer}</span><small>{m.scheduledAt?new Date(m.scheduledAt).toLocaleString('fr-FR'):'Non planifiée'} · {m.provider||'À assigner'}</small><div className={styles.rowActions}><span className={styles.chip}>{m.status}</span>{m.operationsMissionStatus?<span className={styles.chip}>OPS {m.operationsMissionStatus}</span>:null}{m.riskLevel?<span className={styles.chip}>Risk {m.riskLevel}</span>:null}</div></button>)}{!items.length?<p className={styles.muted}>Aucune mission.</p>:null}</section>)}</div>
 {selected?<section className={styles.dispatchDock}><div className={styles.panelTitle}><div><div className={styles.eyebrow}>Dispatch dossier · {selected.reference}</div><h3>{selected.customer} · {selected.title}</h3><span className={styles.muted}>{selected.amount.toLocaleString('fr-FR')} Dh · {selected.paymentStatus} · {selected.journeyType}</span></div><div className={styles.rowActions}><Link className={styles.buttonSecondary} href={selected.route}>Order Command</Link>{selected.fulfillmentCaseId?<Link className={styles.buttonSecondary} href={`/angelcare-marketplace/admin/operations/fulfillment/${selected.fulfillmentCaseId}`}><Truck size={13}/>Fulfillment dossier</Link>:null}</div></div>
   {!ops?<div className={styles.dispatchAuthority}><ShieldCheck size={20}/><div><strong>Aucune mission Operations Execution reliée</strong><p>Créez la mission canonique à partir de cette commande avant scoring/dispatch.</p></div><button className={styles.button} disabled={busy} onClick={()=>void ensureMission()}><Sparkles size={14}/>Matérialiser mission</button></div>:<>
    <div className={styles.grid3}><M icon={<Truck/>} label="Mission OPS" v={ops.mission.public_reference}/><M icon={<Navigation/>} label="Statut" v={ops.mission.status}/><M icon={<AlertTriangle/>} label="Incidents" v={ops.incidents.length}/></div>
    <div className={styles.rowActions}><button className={styles.button} disabled={busy} onClick={()=>void generateProposals()}><Sparkles size={14}/>Scorer providers éligibles</button>{ops.mission.status==='draft'?<button className={styles.buttonSecondary} disabled={busy} onClick={()=>void transition('awaiting_authorization')}>Soumettre autorisation</button>:null}{ops.mission.status==='awaiting_authorization'?<button className={styles.buttonSecondary} disabled={busy} onClick={()=>void transition('authorized')}>Autoriser</button>:null}{ops.mission.status==='assigned'?<button className={styles.buttonSecondary} disabled={busy} onClick={()=>void transition('awaiting_acceptance')}>Demander acceptation</button>:null}{ops.mission.status==='awaiting_acceptance'?<button className={styles.buttonSecondary} disabled={busy} onClick={()=>void transition('accept')}>Confirmer acceptation</button>:null}</div>
    <div className={styles.proposalGrid}>{ops.proposals.map(proposal=>{const provider=providers.find(x=>txt(x,'provider_id')===proposal.provider_id);return <article className={styles.proposalCard} key={proposal.id}><div className={styles.panelTitle}><div><strong>{txt(provider,'display_name')||proposal.provider_id}</strong><div className={styles.muted}>{proposal.provider_id}</div></div><span className={styles.scorePill}>{Math.round(Number(proposal.score||0))}</span></div><div className={styles.proposalFacts}><span>Éligibilité: {txt(proposal.eligibility_snapshot as Row,'status')||'calculée'}</span><span>Conflits: {proposal.conflicts.length?proposal.conflicts.join(', '):'aucun détecté'}</span><span>Statut: {proposal.status}</span></div>{proposal.status==='proposed'?<div className={styles.rowActions}><button className={styles.button} disabled={busy} onClick={()=>void decide(proposal,'accept')}><UserRoundCheck size={13}/>Assigner</button><button className={styles.buttonDanger} disabled={busy} onClick={()=>void decide(proposal,'reject')}>Rejeter</button></div>:null}</article>})}{!ops.proposals.length?<p className={styles.muted}>Aucune proposition. Lancez le scoring provider.</p>:null}</div>
   </>}
   {notice?<div className={styles.notice}>{notice}</div>:null}
 </section>:null}
 </div>}
function M({icon,label,v}:{icon:React.ReactNode;label:string;v:unknown}){return <div className={styles.metric}>{icon}<strong>{String(v)}</strong><span>{label}</span></div>}
