'use client'

import { useEffect, useState } from 'react'
import { AlertTriangle, ArrowRight, BadgeCheck, BookOpen, CheckCircle2, Clock3, Edit3, FileCheck2, Shield, X } from 'lucide-react'
import type { RevenueDoctrine } from '@/lib/revenue-command-os/types'
import { useKnowledgeMemory } from './KnowledgeMemoryContext'

function tone(status:string){if(status==='effective')return'bg-emerald-50 text-emerald-700 ring-emerald-200';if(status==='approved')return'bg-blue-50 text-blue-700 ring-blue-200';if(status==='in-review')return'bg-amber-50 text-amber-700 ring-amber-200';if(status==='rejected'||status==='suspended')return'bg-rose-50 text-rose-700 ring-rose-200';return'bg-slate-100 text-slate-600 ring-slate-200'}

export default function DoctrineDrawer({doctrine,onClose}:{doctrine:RevenueDoctrine|null;onClose:()=>void}){
  const {mutateDoctrine,busy}=useKnowledgeMemory(); const [editing,setEditing]=useState(false); const [title,setTitle]=useState(''); const [summary,setSummary]=useState('');
  useEffect(()=>{setTitle(doctrine?.title||'');setSummary(doctrine?.summary||'');setEditing(false)},[doctrine])
  if(!doctrine)return null
  async function action(operation:'update'|'submit-review'|'approve'|'activate'|'suspend'|'retire'){
    const data=operation==='update'?{title,summary,changeReason:'Mise à jour depuis le Studio Doctrine'}:{changeReason:`Transition ${operation}`}
    await mutateDoctrine({operation,id:doctrine!.id,payload:data}); if(operation==='update')setEditing(false)
  }
  return <div className="fixed inset-0 z-[150] bg-slate-950/28 backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside className="absolute inset-y-0 right-0 flex w-full max-w-[760px] flex-col border-l border-slate-200 bg-white shadow-[-24px_0_80px_rgba(15,23,42,.18)]">
    <header className="border-b border-slate-100 px-6 py-5"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ring-1 ${tone(doctrine.status)}`}>{doctrine.status}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[9px] font-black uppercase text-slate-600">v{doctrine.version}</span><span className="rounded-full bg-violet-50 px-2.5 py-1 text-[9px] font-black uppercase text-violet-700">{doctrine.knowledgeType}</span></div><p className="mt-3 text-[10px] font-black uppercase tracking-[.16em] text-emerald-700">{doctrine.code}</p>{editing?<input value={title} onChange={e=>setTitle(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2 text-xl font-black outline-none focus:border-blue-500"/>:<h2 className="mt-2 text-2xl font-black tracking-tight text-slate-950">{doctrine.title}</h2>}</div><button onClick={onClose} className="rounded-xl border border-slate-200 p-2 text-slate-500 hover:bg-slate-50"><X size={18}/></button></div>{editing?<textarea value={summary} onChange={e=>setSummary(e.target.value)} rows={4} className="mt-4 w-full rounded-2xl border border-slate-200 px-3 py-3 text-sm leading-6 outline-none focus:border-blue-500"/>:<p className="mt-3 text-sm leading-6 text-slate-600">{doctrine.summary}</p>}</header>
    <div className="flex-1 overflow-y-auto px-6 py-5"><div className="grid gap-3 sm:grid-cols-3"><Info icon={Shield} label="Autorité" value={doctrine.ownerRole}/><Info icon={Clock3} label="Prochaine revue" value={doctrine.nextReviewAt||'À définir'}/><Info icon={FileCheck2} label="Preuves liées" value={String(doctrine.evidenceRefs.length)}/></div>
      <section className="mt-6"><h3 className="flex items-center gap-2 text-sm font-black text-slate-950"><BookOpen size={17} className="text-emerald-700"/>Contenu institutionnel</h3><div className="mt-3 space-y-3">{doctrine.contentBlocks.sort((a,b)=>a.order-b.order).map(block=><article key={block.code} className="rounded-2xl border border-slate-200 bg-slate-50/60 p-4"><div className="flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-[.13em] text-slate-500">{block.heading}</p><span className="rounded-lg bg-white px-2 py-1 text-[9px] font-black text-slate-500 ring-1 ring-slate-200">{block.blockType}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{block.body}</p></article>)}</div></section>
      <section className="mt-6"><h3 className="flex items-center gap-2 text-sm font-black text-slate-950"><BadgeCheck size={17} className="text-blue-700"/>Règles exécutables</h3><div className="mt-3 space-y-3">{doctrine.rules.map(rule=><article key={rule.code} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-start gap-3"><span className={`mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-xl ${rule.severity==='high'?'bg-rose-50 text-rose-700':'bg-blue-50 text-blue-700'}`}>{rule.machineEnforceable?<CheckCircle2 size={16}/>:<AlertTriangle size={16}/>}</span><div><p className="text-sm font-black text-slate-900">{rule.name}</p><p className="mt-1 text-xs leading-5 text-slate-600">{rule.requiredAction}</p>{rule.prohibitedAction?<p className="mt-2 text-[11px] font-bold text-rose-700">Interdit: {rule.prohibitedAction}</p>:null}</div></div></article>)}</div></section>
      <section className="mt-6 rounded-[24px] border border-slate-200 bg-slate-950 p-5 text-white"><p className="text-[10px] font-black uppercase tracking-[.15em] text-emerald-300">Source d’autorité</p><p className="mt-2 text-sm leading-6 text-slate-200">{doctrine.sourceAuthority}</p><div className="mt-4 flex flex-wrap gap-2">{doctrine.applicableCommandFamilies.map(item=><span key={item} className="rounded-full bg-white/10 px-2.5 py-1 text-[9px] font-black">{item}</span>)}</div></section>
    </div>
    <footer className="border-t border-slate-100 bg-white px-6 py-4"><div className="flex flex-wrap items-center justify-between gap-3"><button onClick={()=>setEditing(!editing)} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-black text-slate-700"><Edit3 size={15}/>{editing?'Annuler':'Modifier'}</button><div className="flex flex-wrap gap-2">{editing?<button disabled={busy} onClick={()=>action('update')} className="rounded-xl bg-blue-700 px-4 py-2 text-xs font-black text-white">Enregistrer</button>:null}{doctrine.status==='draft'?<button disabled={busy} onClick={()=>action('submit-review')} className="rounded-xl bg-amber-500 px-4 py-2 text-xs font-black text-white">Soumettre</button>:null}{doctrine.status==='in-review'?<button disabled={busy} onClick={()=>action('approve')} className="rounded-xl bg-blue-700 px-4 py-2 text-xs font-black text-white">Approuver</button>:null}{doctrine.status==='approved'?<button disabled={busy} onClick={()=>action('activate')} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2 text-xs font-black text-white">Activer <ArrowRight size={14}/></button>:null}{doctrine.status==='effective'?<button disabled={busy} onClick={()=>action('suspend')} className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-2 text-xs font-black text-rose-700">Suspendre</button>:null}</div></div></footer>
  </aside></div>
}

function Info({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-3"><Icon size={16} className="text-blue-700"/><p className="mt-3 text-[9px] font-black uppercase tracking-[.13em] text-slate-400">{label}</p><p className="mt-1 text-xs font-black text-slate-800">{value}</p></div>}
