import 'server-only'
import { createClient } from '@/lib/supabase/server'
import { REVENUE_OS_CONTRACT_VERSION } from '../constants'
import { REVENUE_COMMAND_FAMILIES, REVENUE_COMMAND_KERNEL_EXTERNAL_ACTIONS, REVENUE_COMMAND_KERNEL_EXECUTION_POSTURE, REVENUE_COMMAND_KERNEL_MODULE_VERSION, REVENUE_COMMAND_KERNEL_RELEASE_CODE } from './constants'
import { REVENUE_COMMAND_SEED_COMMANDS, REVENUE_COMMAND_SEED_GRAPHS, REVENUE_COMMAND_SEED_SCHEDULES, REVENUE_COMMAND_SEED_TRIGGERS, REVENUE_COMMAND_SEED_VERSIONS } from './seed-data'
import cumulativeCommands from './commands-3000/commands-3000.commands.json'
import cumulativeVersions from './commands-3000/commands-3000.versions.json'
import cumulativeTriggers from './commands-3000/commands-3000.triggers.json'
import cumulativeSchedules from './commands-3000/commands-3000.schedules.json'
import cumulativeGraphs from './commands-3000/commands-3000.graphs.json'
import { routeRevenueCommands } from './router'
import { executeShadowPlan } from './runtime'
import { validateRevenueCommandKernel } from './validation'
import type { RevenueCommandDefinition, RevenueCommandGraph, RevenueCommandKernelBootstrap, RevenueCommandRun, RevenueCommandSchedule, RevenueCommandSituation, RevenueCommandTrigger, RevenueCommandVersion } from './types'
const arr=(v:unknown)=>Array.isArray(v)?v:[]
async function safeSelect(client:any,table:string){const result=await client.from(table).select('*').order('created_at',{ascending:true});if(result.error)throw result.error;return result.data||[]}
function command(row:any):RevenueCommandDefinition{return{id:String(row.id),commandCode:String(row.command_code),name:String(row.name),family:row.family_code,purpose:String(row.purpose),ownerRole:String(row.owner_role),status:row.status,activeVersion:String(row.active_version),businessUnits:arr(row.business_units).map(String),segments:arr(row.segments).map(String),territories:arr(row.territories).map(String),commercialStages:arr(row.commercial_stages).map(String),triggerTypes:arr(row.trigger_types) as any,eligibilityRules:arr(row.eligibility_rules) as any,requiredContext:arr(row.required_context) as any,optionalContext:arr(row.optional_context) as any,toolPermissions:arr(row.tool_permissions) as any,inputSchema:arr(row.input_schema) as any,outputSchema:arr(row.output_schema) as any,validatorChain:arr(row.validator_chain).map(String),approvalClass:row.approval_class,downstreamCompiler:row.downstream_compiler?String(row.downstream_compiler):undefined,cooldown:row.cooldown_policy,retryPolicy:row.retry_policy,failurePolicy:row.failure_policy,fallbackCommandCodes:arr(row.fallback_command_codes).map(String),performanceMetrics:arr(row.performance_metrics).map(String),prohibitedCases:arr(row.prohibited_cases).map(String),expectedOutcomes:arr(row.expected_outcomes).map(String),tags:arr(row.tags).map(String),createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString()}}
export async function readRevenueCommandKernel():Promise<{bootstrap:RevenueCommandKernelBootstrap;warnings:string[]}>{const warnings:string[]=[];let storageMode:'supabase'|'kernel-fallback'='kernel-fallback';let commands=cumulativeCommands as RevenueCommandDefinition[],versions=cumulativeVersions as RevenueCommandVersion[],triggers=cumulativeTriggers as RevenueCommandTrigger[],schedules=cumulativeSchedules as RevenueCommandSchedule[],graphs=cumulativeGraphs as RevenueCommandGraph[],runs:RevenueCommandRun[]=[];try{const client=await createClient();const [c,v,t,s,g,r]=await Promise.all([safeSelect(client,'revenue_os_command_definitions'),safeSelect(client,'revenue_os_command_versions'),safeSelect(client,'revenue_os_command_triggers'),safeSelect(client,'revenue_os_command_schedules'),safeSelect(client,'revenue_os_command_graphs'),safeSelect(client,'revenue_os_command_runs')]);if(c.length){
  const persisted=c.map(command)
  const operational=persisted.filter((item:RevenueCommandDefinition)=>item.tags.includes('golden-300')||item.tags.includes('new-700')||item.tags.includes('new-1000')||item.tags.includes('final-1000'))
  const operationalCodes=new Set(operational.map((item:RevenueCommandDefinition)=>item.commandCode))
  commands=operational
  versions=(v as RevenueCommandVersion[]).filter(item=>operationalCodes.has(item.commandCode))
  triggers=(t as RevenueCommandTrigger[]).filter(item=>operationalCodes.has(item.commandCode))
  schedules=(s as RevenueCommandSchedule[]).filter(item=>operationalCodes.has(item.commandCode))
  graphs=(g.map((x:any)=>x.graph_payload) as RevenueCommandGraph[]).filter(graph=>graph.nodes.every(node=>operationalCodes.has(node.commandCode)))
  runs=r as RevenueCommandRun[]
  storageMode='supabase'
}}catch(error){warnings.push(`Mode fallback MZ09: ${error instanceof Error?error.message:'base indisponible'}`)}const validation=validateRevenueCommandKernel(commands,graphs,schedules);const bootstrap:RevenueCommandKernelBootstrap={contractVersion:REVENUE_OS_CONTRACT_VERSION,releaseCode:REVENUE_COMMAND_KERNEL_RELEASE_CODE,moduleVersion:REVENUE_COMMAND_KERNEL_MODULE_VERSION,executionPosture:REVENUE_COMMAND_KERNEL_EXECUTION_POSTURE,externalActionsEnabled:REVENUE_COMMAND_KERNEL_EXTERNAL_ACTIONS,generatedAt:new Date().toISOString(),storageMode,families:REVENUE_COMMAND_FAMILIES,commands,versions,triggers,schedules,graphs,runs,issues:validation.issues,readiness:validation.readiness,counters:{commands:commands.length,approved:commands.filter(c=>c.status==='approved').length,rejected:commands.filter(c=>c.status==='rejected').length,families:REVENUE_COMMAND_FAMILIES.length,triggers:triggers.length,schedules:schedules.length,graphs:graphs.length,runs:runs.length,issues:validation.issues.length,externalActions:0,golden300:commands.filter(c=>c.tags.includes('golden-300')).length,mz07New700:commands.filter(c=>c.tags.includes('new-700')).length,commands1000:commands.filter(c=>c.tags.includes('golden-300')||c.tags.includes('new-700')).length,mz08New1000:commands.filter(c=>c.tags.includes('new-1000')).length,commands2000:commands.filter(c=>c.tags.includes('golden-300')||c.tags.includes('new-700')||c.tags.includes('new-1000')).length,mz09Final1000:commands.filter(c=>c.tags.includes('final-1000')).length,commands3000:commands.filter(c=>c.tags.includes('golden-300')||c.tags.includes('new-700')||c.tags.includes('new-1000')||c.tags.includes('final-1000')).length,mz05Proof:commands.filter(c=>!c.tags.includes('golden-300')&&!c.tags.includes('new-700')).length}};return{bootstrap,warnings}}
export async function simulateRevenueCommandSituation(situation:RevenueCommandSituation){const {bootstrap}=await readRevenueCommandKernel();const plan=routeRevenueCommands(bootstrap.commands,situation);const execution=executeShadowPlan(plan,bootstrap.commands);return{plan,execution,posture:'shadow',externalActionsPerformed:0}}
export async function persistKernelValidation(){const {bootstrap}=await readRevenueCommandKernel();return{readiness:bootstrap.readiness,issues:bootstrap.issues,persisted:false,reason:'La persistance est disponible après application de la migration MZ09.'}}
