'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import type {PartnerPlan,PartnerTenant,TenantWorkspaceData} from '../types'
import s from '../partner.module.css'
type Envelope<T>={data?:T;error?:{message?:string}}
async function post<T=unknown>(url:string,body:Record<string,unknown>){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json() as Envelope<T>;if(!r.ok)throw new Error(j.error?.message||'Action Partner OS refusée.');return j.data as T}
function useAction(){const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[error,setError]=useState('');const router=useRouter();return{busy,msg,error,run:async(label:string,fn:()=>Promise<unknown>)=>{setBusy(true);setError('');setMsg('');try{await fn();setMsg(label);router.refresh()}catch(e){setError(e instanceof Error?e.message:'Erreur Partner OS')}finally{setBusy(false)}}}}
function Feedback({a}:{a:ReturnType<typeof useAction>}){return <>{a.msg?<div className={s.success}>{a.msg}</div>:null}{a.error?<div className={s.danger}>{a.error}</div>:null}</>}
export function TenantLifecycleDesk({tenant,workspace,plans}:{tenant:PartnerTenant;workspace:TenantWorkspaceData;plans:PartnerPlan[]}){const[target,setTarget]=useState('active');const[reason,setReason]=useState('');const[planId,setPlanId]=useState(plans[0]?.id||'');const[subStatus,setSubStatus]=useState('active');const[moduleKey,setModuleKey]=useState('marketplace-core');const a=useAction();return <div className={s.shell}><section className={s.panel}><h2>Lifecycle tenant</h2><div className={s.form}><div className={s.notice}>État actuel <strong>{tenant.status}</strong> · onboarding {tenant.onboarding_score}% · santé {tenant.health_status}</div><select value={target} onChange={e=>setTarget(e.target.value)}>{['onboarding','trial','active','suspended','cancelled','archived'].map(x=><option key={x}>{x}</option>)}</select><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Raison et preuve de la transition"/><button disabled={a.busy||!reason.trim()} onClick={()=>void a.run('Lifecycle tenant mis à jour',()=>post(`/api/angelcare-marketplace/partner-os/tenants/${tenant.id}/transition`,{target,reason}))}>Appliquer lifecycle</button></div></section><section className={s.panel}><h2>Plan & abonnement</h2><div className={s.form}><select value={planId} onChange={e=>setPlanId(e.target.value)}>{plans.map(p=><option value={p.id} key={p.id}>{p.name_fr} · {p.base_price??'sur devis'} {p.currency_label}</option>)}</select><select value={subStatus} onChange={e=>setSubStatus(e.target.value)}><option value="draft">draft</option><option value="trial">trial</option><option value="active">active</option></select><button disabled={a.busy||!planId} onClick={()=>void a.run('Abonnement tenant assigné',()=>post(`/api/angelcare-marketplace/partner-os/tenants/${tenant.id}/subscription`,{planId,status:subStatus,renewalMode:'contractual',amount:null}))}>Affecter abonnement</button><div className={s.subtle}>{workspace.subscription?`Actuel: ${workspace.subscription.public_reference} · ${workspace.subscription.status}`:'Aucun abonnement actif'}</div></div></section><section className={s.panel}><h2>Module activation</h2><div className={s.form}><input value={moduleKey} onChange={e=>setModuleKey(e.target.value)} placeholder="module_key"/><button disabled={a.busy||!moduleKey.trim()} onClick={()=>void a.run('Module tenant activé',()=>post(`/api/angelcare-marketplace/partner-os/tenants/${tenant.id}/modules`,{moduleKey,status:'active',configuration:{},usageLimit:{}}))}>Activer module</button></div></section><section className={s.panel}><h2>Runway onboarding</h2><div className={s.rows}>{workspace.onboarding.map(check=><OnboardingCheck key={check.id} tenantId={tenant.id} check={check} a={a}/>)}</div></section><Feedback a={a}/></div>}
function OnboardingCheck({tenantId,check,a}:{tenantId:string;check:TenantWorkspaceData['onboarding'][number];a:ReturnType<typeof useAction>}){return <div className={s.row}><div><strong>{check.title_fr}</strong><div className={s.subtle}>{check.required?'Obligatoire':'Recommandé'}</div></div><span>{check.owner_id?'Owner assigné':'Owner à affecter'}</span><span className={s.status}>{check.status}</span><button disabled={a.busy} onClick={()=>void a.run(`${check.title_fr}: validé`,()=>post(`/api/angelcare-marketplace/partner-os/tenants/${tenantId}/onboarding/${check.id}`,{status:'passed',evidence:{confirmed_by:'admin'},reason:'Validation Admin'}))}>Valider</button><button disabled={a.busy} onClick={()=>void a.run(`${check.title_fr}: en revue`,()=>post(`/api/angelcare-marketplace/partner-os/tenants/${tenantId}/onboarding/${check.id}`,{status:'in_progress',evidence:{},reason:'Revue requise'}))}>Revoir</button></div>}
export function TenantCreateDesk(){const[legalName,setLegalName]=useState('');const[displayName,setDisplayName]=useState('');const[type,setType]=useState('establishment');const a=useAction();return <section className={s.panel}><h2>Créer un tenant Partner OS</h2><div className={s.form}><input value={legalName} onChange={e=>setLegalName(e.target.value)} placeholder="Raison sociale"/><input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Nom affiché"/><select value={type} onChange={e=>setType(e.target.value)}><option value="establishment">Établissement</option><option value="corporate">Corporate</option><option value="hospitality">Hospitality</option><option value="healthcare">Healthcare</option></select><button disabled={a.busy||!legalName.trim()} onClick={()=>void a.run('Tenant créé',()=>post('/api/angelcare-marketplace/partner-os/tenants',{legal_name:legalName,display_name:displayName||legalName,tenant_type:type,default_locale:'fr',currency_label:'Dh'}))}>Créer tenant + runway onboarding</button><Feedback a={a}/></div></section>}
