"use client";

import { Activity, BadgeAlert, Bot, BrainCircuit, CircleDollarSign, Cpu, FileCode2, Gauge, Link2, PauseCircle, PlayCircle, ShieldCheck, Sparkles, TriangleAlert, UserCheck } from "lucide-react";
import { useCallback, useMemo, useState } from "react";
import { AcCapitalShell } from "../../core/AcCapitalShell";
import { EmptyState, ErrorState, LoadingState } from "../../core/AsyncState";
import { ActionFeedback, Field } from "../../core/FormParts";
import { MetricTile } from "../../core/MetricTile";
import { Dialog, Drawer } from "../../core/Overlay";
import { StatusBadge } from "../../core/StatusBadge";
import { AuditTimeline, FactGrid, PrimaryButton, SecondaryButton, SectionHeading, TruthChip } from "../../core/WorkspaceParts";
import { postEnvelope } from "../../core/api";
import { number, rowsFrom, shortDate, text } from "../../core/data";
import type { CapitalActor, Row } from "../../core/types";
import { useAction } from "../../core/useAction";
import { useActionQuery } from "../../core/useActionQuery";
import { useWorkspace } from "../../core/useWorkspace";
import styles from "./ai-command.module.css";

type Modal="run"|"issue"|"pause"|"approval"|null;

export function AiCommandPage({actor}:{actor:CapitalActor}){
 const workspace=useWorkspace("/api/ac-capital-os/ai-command-center");const action=useAction();const [selected,setSelected]=useState<Row|null>(null);const [modal,setModal]=useState<Modal>(null);const [runResult,setRunResult]=useState<Record<string,unknown>|null>(null);
 const [run,setRun]=useState({prompt:"Analyze the current AC CAPITAL OS context and produce a source-aware capital readiness brief. Separate confirmed facts, missing evidence, risks, recommendations and required human actions. Do not perform any external action.",skill:"Capital intelligence",doctrineUsed:"Founder-control policy",confidence:70,riskLevel:"Medium",approvalStatus:"Human Review Required",liveRequested:true});
 const [issue,setIssue]=useState({issueTitle:"",category:"AI troubleshooting",severity:"Medium",workspace:"AI Command Center",reproductionNote:"",impact:"",recommendedFix:"Review source, prompt, doctrine and skill binding.",owner:"AI System Admin"});
 const [pauseReason,setPauseReason]=useState("");
 const [approval,setApproval]=useState({title:"",reason:"",targetApprover:"Founder / Managing Director",dueAt:""});
 const openAction=useCallback((next:Modal)=>setModal(next),[]);useActionQuery({run:"run",issue:"issue"},openAction);
 const agents=rowsFrom(workspace.envelope,"agents");const runs=rowsFrom(workspace.envelope,"agentRuns");const prompts=rowsFrom(workspace.envelope,"prompts");const skills=rowsFrom(workspace.envelope,"skills");const adapters=rowsFrom(workspace.envelope,"researchAdapters");const providers=rowsFrom(workspace.envelope,"providerSettings");const safety=rowsFrom(workspace.envelope,"safetyRules");const issues=rowsFrom(workspace.envelope,"troubleshootingIssues");const confidence=rowsFrom(workspace.envelope,"confidencePolicies");const costs=rowsFrom(workspace.envelope,"costUsage");const approvals=rowsFrom(workspace.envelope,"humanApprovalQueue");const bridge=rowsFrom(workspace.envelope,"providerBridge");
 const selectedRuns=selected?runs.filter(row=>String(row.agent_id)===String(selected.id)):[];
 const active=agents.filter(row=>!/paused|disabled/i.test(text(row,["status"],""))).length;const openIssues=issues.filter(row=>!/resolved|closed/i.test(text(row,["status"],""))).length;const pendingApprovals=approvals.filter(row=>/pending/i.test(text(row,["status"],""))).length;const totalCost=costs.reduce((sum,row)=>sum+number(row,["cost_amount","estimated_cost","amount"],0),0);
 async function dryRun(){
   if(!selected&&!run.prompt.trim())return action.validate("Select an agent or provide a prompt.");
   const result=await action.execute(()=>postEnvelope<Record<string,unknown>>("/api/ac-capital-os/ai-command-center/run",{...run,agentId:selected?.id,agentKey:selected?text(selected,["agent_key"]):undefined,workspace:"AI Command Center",doctrineUsed:run.doctrineUsed.split(",").map(v=>v.trim()).filter(Boolean)}),run.liveRequested?"Governed Gemini execution completed.":"Dry-run completed with a real API response.");
   if(result?.data)setRunResult(result.data as Record<string,unknown>);
   await workspace.refresh();
 }
 async function reportIssue(){if(!issue.issueTitle.trim())return action.validate("Issue title is required.");await action.execute(()=>postEnvelope("/api/ac-capital-os/ai-command-center/issue",{...issue,agentId:selected?.id}),"AI issue recorded.");await workspace.refresh();}
 async function pauseAgent(){if(!selected)return action.validate("Select an agent.");await action.execute(()=>postEnvelope("/api/ac-capital-os/ai-command-center",{action:"pause-agent",id:selected.id,reason:pauseReason}),"Agent paused.");await workspace.refresh();}
 async function createApproval(){if(!approval.title.trim())return action.validate("Approval title is required.");await action.execute(()=>postEnvelope("/api/ac-capital-os/ai-command-center",{action:"approval-queue",...approval,agentId:selected?.id}),"AI prepared action sent to human approval queue.");await workspace.refresh();}
 const insights=[{label:"Execution mode",value:"Provider-control ready; every live run is manually requested and governed"},{label:"Provider bridge",value:`${bridge.length||providers.length} provider configuration records`},{label:"Safety wall",value:`${safety.length} safety rules and ${confidence.length} confidence policies`},{label:"Human control",value:`${pendingApprovals} pending AI approvals`}];

 return <AcCapitalShell actor={actor} workspaceKey="ai-capital-brain" title="AI Capital Brain Control Lab" subtitle="A governed AI operations laboratory for agents, provider assignments, prompts, skills, doctrine bindings, dry-runs, safety, cost and human approval." envelope={workspace.envelope} insights={insights} primaryAction="Run Governed Test" onPrimaryAction={()=>setModal("run")}>
  {workspace.loading?<LoadingState label="Loading AI agents, safety policies and run history…"/>:workspace.error?<ErrorState message={workspace.error} onRetry={()=>void workspace.refresh()}/>:<>
   <section className={styles.labHero}><div><span><BrainCircuit size={15}/> Governed Capital Intelligence</span><h2>Powerful AI should be inspectable, attributable and unable to bypass human authority.</h2><p>Every agent exposes provider state, prompt/skill/doctrine context, confidence, risk, run history, issues and human approval requirements.</p><div><PrimaryButton onClick={()=>setModal("run")}>Run governed capital test</PrimaryButton><SecondaryButton onClick={()=>setModal("issue")}>Report AI issue</SecondaryButton></div></div><div className={styles.core}><Cpu/><strong>{active}/{agents.length}</strong><span>Agents active</span><TruthChip kind="safe">Manual governed live execution</TruthChip></div></section>
   <section className={styles.metrics}><MetricTile label="Agents" value={String(agents.length)} detail={`${active} active according to stored status.`} tone="violet"/><MetricTile label="Dry-run history" value={String(runs.length)} detail="Stored agent run rows." tone="blue"/><MetricTile label="Open issues" value={String(openIssues)} detail="Unresolved troubleshooting records." tone={openIssues?"red":"green"}/><MetricTile label="Pending approvals" value={String(pendingApprovals)} detail="Human approval queue." tone={pendingApprovals?"amber":"green"}/></section>

   <section className={styles.agentConstellation}><SectionHeading eyebrow="Agent Constellation" title="Capital agents and execution state" copy="Choose an agent to inspect its run history, prompts, skills, provider and safety context."/>
    {agents.length?<div className={styles.agentGrid}>{agents.map((row,index)=><button key={String(row.id)} className={`${styles.agentCard} ${selected?.id===row.id?styles.selected:""}`} onClick={()=>setSelected(row)}><span className={`${styles.signal} ${/paused|disabled/i.test(text(row,["status"],""))?styles.signalOff:""}`}/><Bot/><strong>{text(row,["agent_name","agent_key"],`Agent ${index+1}`)}</strong><p>{text(row,["mission","description"],"Capital intelligence agent")}</p><footer><StatusBadge value={text(row,["status"],"Configured")}/><span>{text(row,["provider_mode","provider_assignment"],"Provider-control")}</span></footer></button>)}</div>:<EmptyState title="No AI agents registered" copy="The lab will not fabricate agent status. Register agents in the AI Command Center tables first." action="Report configuration issue" onAction={()=>setModal("issue")}/>}
   </section>

   {selected?<section className={styles.controlDeck}><div><SectionHeading eyebrow="Selected Agent Control" title={text(selected,["agent_name","agent_key"],"Agent")} copy={text(selected,["mission","description"],"No mission recorded.")}/><div className={styles.controlGrid}><button onClick={()=>setModal("run")}><PlayCircle/><strong>Run governed test</strong><span>Choose dry-run or central Gemini execution.</span></button><button onClick={()=>setModal("approval")}><UserCheck/><strong>Send to human queue</strong><span>Prepared action cannot self-approve.</span></button><button onClick={()=>setModal("issue")}><BadgeAlert/><strong>Report issue</strong><span>Source, confidence or output defect.</span></button><button onClick={()=>setModal("pause")}><PauseCircle/><strong>Pause agent</strong><span>Persist a safety pause.</span></button></div></div><aside><h3>Agent safety snapshot</h3><p><b>Provider:</b> {text(selected,["provider_mode","provider_assignment"],"Provider-control")}</p><p><b>Status:</b> {text(selected,["status"],"Configured")}</p><p><b>Last failure:</b> {text(selected,["last_failure"],"None recorded")}</p><p><b>Human approval:</b> required for sensitive output</p></aside></section>:null}

   <section className={styles.safetyWall}><div><SectionHeading eyebrow="Safety & Provider Wall" title="Configuration truth"/><div className={styles.wallGrid}><article><Link2/><strong>{bridge.length||providers.length}</strong><span>Provider bridge/settings records</span></article><article><ShieldCheck/><strong>{safety.length}</strong><span>Safety rules</span></article><article><Gauge/><strong>{confidence.length}</strong><span>Confidence policies</span></article><article><FileCode2/><strong>{prompts.length}</strong><span>Prompt records</span></article><article><Sparkles/><strong>{skills.length}</strong><span>Skill records</span></article><article><CircleDollarSign/><strong>{totalCost?`${totalCost.toFixed(2)}`:"—"}</strong><span>Stored cost amount only</span></article></div></div><aside><h3>Open AI issues</h3>{issues.slice(0,6).map(row=><button key={String(row.id)} onClick={()=>{setSelected(agents.find(agent=>String(agent.id)===String(row.affected_agent_id))||null);setModal("issue")}}><TriangleAlert/><div><strong>{text(row,["issue_title"],"AI issue")}</strong><span>{text(row,["severity"],"Medium")} · {text(row,["status"],"New")}</span></div></button>)}{!issues.length?<p>No issue rows returned.</p>:null}</aside></section>
  </>}

  <Drawer open={Boolean(selected)} title={selected?text(selected,["agent_name","agent_key"],"Agent"):"Agent"} eyebrow="AI Agent Inspection Drawer" onClose={()=>setSelected(null)} footer={<><SecondaryButton onClick={()=>setModal("issue")}>Report issue</SecondaryButton><SecondaryButton onClick={()=>setModal("approval")}>Human queue</SecondaryButton><PrimaryButton onClick={()=>setModal("run")}>Run governed test</PrimaryButton></>}>
   {selected?<><FactGrid facts={[{label:"Agent key",value:text(selected,["agent_key"])},{label:"Status",value:text(selected,["status"])},{label:"Provider",value:text(selected,["provider_mode","provider_assignment"])},{label:"Workspace",value:text(selected,["workspace","primary_workspace"])},{label:"Risk",value:text(selected,["risk_level"],"Controlled")},{label:"Approval policy",value:"Human approval for sensitive output"}]}/><div className={styles.drawerBlock}><h3>Run history</h3><AuditTimeline items={selectedRuns.map(row=>({title:text(row,["output_type","status"],"Agent run"),meta:`${text(row,["status"])} · ${shortDate(row.started_at||row.created_at)}`,note:`Confidence ${number(row,["confidence"],0)}% · ${text(row,["risk_level"],"Medium")}`}))}/></div><div className={styles.drawerBlock}><h3>Prompt / skill context</h3><p>{prompts.filter(row=>String(row.target_agent)===text(selected,["agent_key","agent_name"],"")).length} linked prompt records · {skills.filter(row=>Array.isArray(row.applicable_agents)&&row.applicable_agents.map(String).includes(String(selected.id))).length} linked skills.</p></div></>:null}
  </Drawer>

  <Dialog open={modal==="run"} title="Governed Capital AI Run" eyebrow="AI Provider Control · Gemini · Human Authority" wide onClose={()=>{setModal(null);action.reset();setRunResult(null)}} footer={<><SecondaryButton onClick={()=>setModal(null)}>Cancel</SecondaryButton><PrimaryButton onClick={()=>void dryRun()} disabled={action.state.phase==="submitting"}>{run.liveRequested?"Execute governed Gemini run":"Execute dry-run"}</PrimaryButton></>}><div className={styles.formGrid}><Field label="Prompt"><textarea value={run.prompt} onChange={e=>setRun({...run,prompt:e.target.value})}/></Field><Field label="Skill"><input value={run.skill} onChange={e=>setRun({...run,skill:e.target.value})}/></Field><Field label="Doctrine used"><textarea value={run.doctrineUsed} onChange={e=>setRun({...run,doctrineUsed:e.target.value})}/></Field><Field label="Confidence"><input type="number" min="0" max="100" value={run.confidence} onChange={e=>setRun({...run,confidence:Number(e.target.value)})}/></Field><Field label="Risk level"><select value={run.riskLevel} onChange={e=>setRun({...run,riskLevel:e.target.value})}><option>Low</option><option>Medium</option><option>High</option><option>Financial Sensitive</option></select></Field></div><label className={styles.check}><input type="checkbox" checked={run.liveRequested} onChange={e=>setRun({...run,liveRequested:e.target.checked})}/> Execute through the dedicated Gemini assignment in AI Provider Control</label>{runResult?<div className={styles.outputPanel}><h3>Actual API output</h3><pre>{JSON.stringify(runResult,null,2)}</pre></div>:null}<ActionFeedback phase={action.state.phase} message={action.state.message}/></Dialog>

  <Dialog open={modal==="issue"} title="Report AI Issue" eyebrow="Troubleshooting & Safety" wide onClose={()=>{setModal(null);action.reset()}} footer={<><SecondaryButton onClick={()=>setModal(null)}>Cancel</SecondaryButton><PrimaryButton onClick={()=>void reportIssue()}>Create issue</PrimaryButton></>}><div className={styles.formGrid}><Field label="Issue title"><input value={issue.issueTitle} onChange={e=>setIssue({...issue,issueTitle:e.target.value})}/></Field><Field label="Severity"><select value={issue.severity} onChange={e=>setIssue({...issue,severity:e.target.value})}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></Field><Field label="Reproduction note"><textarea value={issue.reproductionNote} onChange={e=>setIssue({...issue,reproductionNote:e.target.value})}/></Field><Field label="Impact"><textarea value={issue.impact} onChange={e=>setIssue({...issue,impact:e.target.value})}/></Field><Field label="Recommended fix"><textarea value={issue.recommendedFix} onChange={e=>setIssue({...issue,recommendedFix:e.target.value})}/></Field><Field label="Owner"><input value={issue.owner} onChange={e=>setIssue({...issue,owner:e.target.value})}/></Field></div><ActionFeedback phase={action.state.phase} message={action.state.message}/></Dialog>

  <Dialog open={modal==="pause"} title="Pause AI Agent" eyebrow="Immediate Safety Control" onClose={()=>{setModal(null);action.reset()}} footer={<><SecondaryButton onClick={()=>setModal(null)}>Cancel</SecondaryButton><PrimaryButton onClick={()=>void pauseAgent()}>Pause agent</PrimaryButton></>}><Field label="Safety reason"><textarea value={pauseReason} onChange={e=>setPauseReason(e.target.value)}/></Field><TruthChip kind="safe">Pause is persisted; this does not delete agent history.</TruthChip><ActionFeedback phase={action.state.phase} message={action.state.message}/></Dialog>

  <Dialog open={modal==="approval"} title="Send AI Action to Human Queue" eyebrow="Human Authority" onClose={()=>{setModal(null);action.reset()}} footer={<><SecondaryButton onClick={()=>setModal(null)}>Cancel</SecondaryButton><PrimaryButton onClick={()=>void createApproval()}>Create approval item</PrimaryButton></>}><div className={styles.formGrid}><Field label="Approval title"><input value={approval.title} onChange={e=>setApproval({...approval,title:e.target.value})}/></Field><Field label="Target approver"><input value={approval.targetApprover} onChange={e=>setApproval({...approval,targetApprover:e.target.value})}/></Field><Field label="Due at"><input type="datetime-local" value={approval.dueAt} onChange={e=>setApproval({...approval,dueAt:e.target.value})}/></Field><Field label="Reason"><textarea value={approval.reason} onChange={e=>setApproval({...approval,reason:e.target.value})}/></Field></div><ActionFeedback phase={action.state.phase} message={action.state.message}/></Dialog>
 </AcCapitalShell>
}
