begin;
create extension if not exists pgcrypto;
create table if not exists public.angelcare360_settings_definitions(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,configuration_key text not null,label text not null,description text not null,family_key text not null,family_label text not null,value_type text not null,default_value_json jsonb not null default '{}'::jsonb,validation_json jsonb not null default '{}'::jsonb,allowed_values_json jsonb not null default '[]'::jsonb,scope_label text not null default 'Établissement',inheritance_label text not null default 'Valeur de l’établissement',approval_class text not null default 'Administration',entitlement_key text,can_override boolean not null default true,requires_impact_preview boolean not null default true,state text not null default 'active',owner_id uuid references public.app_users(id) on delete set null,owner_label text,created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(school_id,configuration_key));
create table if not exists public.angelcare360_settings_schema_versions(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,configuration_key text not null,version_number integer not null,schema_json jsonb not null default '{}'::jsonb,state text not null default 'draft',effective_from timestamptz,effective_to timestamptz,created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now(),unique(school_id,configuration_key,version_number));
create table if not exists public.angelcare360_settings_scope_bindings(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,configuration_key text not null,scope_type text not null,scope_id uuid,scope_label text not null,inherits_from_id uuid references public.angelcare360_settings_scope_bindings(id) on delete set null,override_allowed boolean not null default true,effective_from timestamptz,effective_to timestamptz,state text not null default 'active',created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.angelcare360_settings_local_variations(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,configuration_key text not null,configuration_label text not null,institution_id uuid,institution_label text,site_id uuid,site_label text,parent_value_json jsonb not null default '{}'::jsonb,local_value_json jsonb not null default '{}'::jsonb,reason text not null,starts_at timestamptz,ends_at timestamptz,review_at timestamptz,state text not null default 'draft',approval_label text,approved_by uuid references public.app_users(id) on delete set null,approved_at timestamptz,ended_at timestamptz,created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare360_settings_change_requests(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,configuration_key text not null,title text not null,reason text not null,current_value_json jsonb not null default '{}'::jsonb,proposed_value_json jsonb not null default '{}'::jsonb,scope_json jsonb not null default '{}'::jsonb,target_at timestamptz,state text not null default 'requested',requester_id uuid references public.app_users(id) on delete set null,reviewer_id uuid references public.app_users(id) on delete set null,decision_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare360_settings_releases(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,release_code text not null,name text not null,purpose text not null,scope_label text not null default 'Établissement',target_at timestamptz,state text not null default 'draft',item_count integer not null default 0,successful_count integer not null default 0,failed_count integer not null default 0,rollback_version_id uuid references public.angelcare360_governance_configuration_versions(id) on delete set null,approved_by uuid references public.app_users(id) on delete set null,approved_at timestamptz,activated_by uuid references public.app_users(id) on delete set null,activated_at timestamptz,completed_at timestamptz,created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(school_id,release_code));
create table if not exists public.angelcare360_settings_release_items(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,release_id uuid not null references public.angelcare360_settings_releases(id) on delete cascade,configuration_key text not null,changeset_id uuid references public.angelcare360_governance_configuration_changesets(id) on delete set null,label text not null,sequence_number integer not null default 1,state text not null default 'included',created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare360_settings_release_outcomes(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,release_id uuid not null references public.angelcare360_settings_releases(id) on delete cascade,release_item_id uuid not null references public.angelcare360_settings_release_items(id) on delete cascade,configuration_key text not null,state text not null default 'pending',message text,attempt_count integer not null default 0,executed_by uuid references public.app_users(id) on delete set null,executed_at timestamptz,result_json jsonb not null default '{}'::jsonb,unique(release_id,release_item_id));
create table if not exists public.angelcare360_settings_rollback_runs(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,source_release_id uuid references public.angelcare360_settings_releases(id) on delete set null,target_version_id uuid references public.angelcare360_governance_configuration_versions(id) on delete set null,scope_json jsonb not null default '{}'::jsonb,reason text not null,state text not null default 'pending',requested_by uuid references public.app_users(id) on delete set null,approved_by uuid references public.app_users(id) on delete set null,approved_at timestamptz,executed_by uuid references public.app_users(id) on delete set null,executed_at timestamptz,result_json jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare360_settings_emergency_events(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,configuration_key text not null,reason text not null,scope_json jsonb not null default '{}'::jsonb,proposed_value_json jsonb not null default '{}'::jsonb,starts_at timestamptz not null,ends_at timestamptz,state text not null default 'pending',requested_by uuid references public.app_users(id) on delete set null,approved_by uuid references public.app_users(id) on delete set null,approved_at timestamptz,activated_at timestamptz,reviewed_by uuid references public.app_users(id) on delete set null,reviewed_at timestamptz,ended_at timestamptz,rollback_plan_json jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare360_settings_template_versions(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,template_key text not null,label text not null,purpose text not null,content_text text not null default '',channels_json jsonb not null default '[]'::jsonb,languages_json jsonb not null default '["fr"]'::jsonb,variable_keys_json jsonb not null default '[]'::jsonb,scope_label text not null default 'Établissement',version_number integer not null,state text not null default 'draft',last_validated_at timestamptz,published_by uuid references public.app_users(id) on delete set null,published_at timestamptz,replaces_version_id uuid references public.angelcare360_settings_template_versions(id) on delete set null,created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(school_id,template_key,version_number));
create table if not exists public.angelcare360_settings_template_variables(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,variable_key text not null,label text not null,description text,value_type text not null default 'text',sensitive boolean not null default false,allowed_channels_json jsonb not null default '[]'::jsonb,state text not null default 'active',created_at timestamptz not null default now(),unique(school_id,variable_key));
create table if not exists public.angelcare360_settings_notification_policy_versions(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,policy_key text not null,label text not null,event_key text not null,channel_key text not null,recipient_policy_json jsonb not null default '{}'::jsonb,cadence_json jsonb not null default '{}'::jsonb,quiet_hours_json jsonb not null default '{}'::jsonb,fallback_json jsonb not null default '{}'::jsonb,version_number integer not null,state text not null default 'draft',effective_from timestamptz,effective_to timestamptz,created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(school_id,policy_key,version_number));
create table if not exists public.angelcare360_settings_integration_configurations(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,integration_key text not null,label text not null,purpose text not null,entitlement_state text not null default 'included',connection_state text not null default 'disconnected',affected_modules_json jsonb not null default '[]'::jsonb,data_scope_label text not null default 'Périmètre limité',credential_reference text,last_verified_at timestamptz,credential_review_at timestamptz,issue_count integer not null default 0,created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(school_id,integration_key));
create table if not exists public.angelcare360_settings_conflicts(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,fingerprint text not null,configuration_key text,configuration_id uuid,configuration_label text,title text not null,detail text not null,consequence text,severity text not null default 'high',state text not null default 'open',owner_id uuid references public.app_users(id) on delete set null,owner_label text,due_at timestamptz,resolved_at timestamptz,created_at timestamptz not null default now(),unique(school_id,fingerprint));
create table if not exists public.angelcare360_settings_drift_findings(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,fingerprint text not null,configuration_key text,configuration_id uuid,configuration_label text,title text not null,detail text not null,consequence text,severity text not null default 'warning',expected_signature text,actual_signature text,state text not null default 'open',owner_label text,due_at timestamptz,resolved_at timestamptz,detected_at timestamptz not null default now(),unique(school_id,fingerprint));
create table if not exists public.angelcare360_settings_issues(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,fingerprint text not null,category text not null,title text not null,detail text not null,consequence text,entity_kind text,entity_id uuid,entity_label text,severity text not null default 'warning',state text not null default 'open',owner_id uuid references public.app_users(id) on delete set null,owner_label text,due_at timestamptz,recommended_action_key text,recommended_action_label text,resolution_reason text,resolved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(school_id,fingerprint));
create table if not exists public.angelcare360_settings_tasks(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,entity_type text not null,entity_id uuid,title text not null,detail text,owner_id uuid references public.app_users(id) on delete set null,owner_label text,due_at timestamptz,state text not null default 'open',completed_at timestamptz,created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare360_settings_notes(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,entity_type text not null,entity_id uuid,note text not null,created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.angelcare360_settings_approval_reviews(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,entity_type text not null,entity_id uuid,approval_class text not null,state text not null default 'pending',reviewer_id uuid references public.app_users(id) on delete set null,decision_reason text,reviewed_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.angelcare360_settings_evidence_requests(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,entity_type text not null,entity_id uuid,request_label text not null,reason text,state text not null default 'requested',requested_by uuid references public.app_users(id) on delete set null,due_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.angelcare360_settings_topup_requests(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,capability_key text not null,quantity integer not null default 1,package_version_id uuid,state text not null default 'requested',source_context jsonb not null default '{}'::jsonb,requested_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.angelcare360_settings_history(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,event_key text not null,label text not null,entity_type text not null,entity_id uuid,detail text,actor_id uuid references public.app_users(id) on delete set null,actor_label text,metadata_json jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.angelcare360_settings_action_receipts(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,action_key text not null,idempotency_key text not null,entity_type text,entity_id uuid,message text,result_json jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),unique(school_id,action_key,idempotency_key));
create index if not exists angelcare360_settings_definitions_school_idx on public.angelcare360_settings_definitions(school_id);
create index if not exists angelcare360_settings_schema_versions_school_idx on public.angelcare360_settings_schema_versions(school_id);
create index if not exists angelcare360_settings_scope_bindings_school_idx on public.angelcare360_settings_scope_bindings(school_id);
create index if not exists angelcare360_settings_local_variations_school_idx on public.angelcare360_settings_local_variations(school_id);
create index if not exists angelcare360_settings_change_requests_school_idx on public.angelcare360_settings_change_requests(school_id);
create index if not exists angelcare360_settings_releases_school_idx on public.angelcare360_settings_releases(school_id);
create index if not exists angelcare360_settings_release_items_school_idx on public.angelcare360_settings_release_items(school_id);
create index if not exists angelcare360_settings_release_outcomes_school_idx on public.angelcare360_settings_release_outcomes(school_id);
create index if not exists angelcare360_settings_rollback_runs_school_idx on public.angelcare360_settings_rollback_runs(school_id);
create index if not exists angelcare360_settings_emergency_events_school_idx on public.angelcare360_settings_emergency_events(school_id);
create index if not exists angelcare360_settings_template_versions_school_idx on public.angelcare360_settings_template_versions(school_id);
create index if not exists angelcare360_settings_template_variables_school_idx on public.angelcare360_settings_template_variables(school_id);
create index if not exists angelcare360_settings_notification_policy_versions_school_idx on public.angelcare360_settings_notification_policy_versions(school_id);
create index if not exists angelcare360_settings_integration_configurations_school_idx on public.angelcare360_settings_integration_configurations(school_id);
create index if not exists angelcare360_settings_conflicts_school_idx on public.angelcare360_settings_conflicts(school_id);
create index if not exists angelcare360_settings_drift_findings_school_idx on public.angelcare360_settings_drift_findings(school_id);
create index if not exists angelcare360_settings_issues_school_idx on public.angelcare360_settings_issues(school_id);
create index if not exists angelcare360_settings_tasks_school_idx on public.angelcare360_settings_tasks(school_id);
create index if not exists angelcare360_settings_notes_school_idx on public.angelcare360_settings_notes(school_id);
create index if not exists angelcare360_settings_approval_reviews_school_idx on public.angelcare360_settings_approval_reviews(school_id);
create index if not exists angelcare360_settings_evidence_requests_school_idx on public.angelcare360_settings_evidence_requests(school_id);
create index if not exists angelcare360_settings_topup_requests_school_idx on public.angelcare360_settings_topup_requests(school_id);
create index if not exists angelcare360_settings_history_school_idx on public.angelcare360_settings_history(school_id);
create index if not exists angelcare360_settings_action_receipts_school_idx on public.angelcare360_settings_action_receipts(school_id);
create index if not exists angelcare360_settings_variations_expiry_idx on public.angelcare360_settings_local_variations(school_id,state,ends_at);
create index if not exists angelcare360_settings_releases_state_idx on public.angelcare360_settings_releases(school_id,state,target_at);
create index if not exists angelcare360_settings_conflicts_state_idx on public.angelcare360_settings_conflicts(school_id,state,severity);
create index if not exists angelcare360_settings_drift_state_idx on public.angelcare360_settings_drift_findings(school_id,state,severity);
do $$ declare t text; begin foreach t in array array['angelcare360_settings_definitions','angelcare360_settings_schema_versions','angelcare360_settings_scope_bindings','angelcare360_settings_local_variations','angelcare360_settings_change_requests','angelcare360_settings_releases','angelcare360_settings_release_items','angelcare360_settings_release_outcomes','angelcare360_settings_rollback_runs','angelcare360_settings_emergency_events','angelcare360_settings_template_versions','angelcare360_settings_template_variables','angelcare360_settings_notification_policy_versions','angelcare360_settings_integration_configurations','angelcare360_settings_conflicts','angelcare360_settings_drift_findings','angelcare360_settings_issues','angelcare360_settings_tasks','angelcare360_settings_notes','angelcare360_settings_approval_reviews','angelcare360_settings_evidence_requests','angelcare360_settings_topup_requests','angelcare360_settings_history','angelcare360_settings_action_receipts'] loop execute format('alter table public.%I enable row level security',t); execute format('revoke insert,update,delete on public.%I from anon,authenticated',t); end loop; end $$;
insert into public.angelcare360_settings_definitions(school_id,configuration_key,label,description,family_key,family_label,value_type,default_value_json,scope_label,approval_class,state) select v.school_id,v.configuration_key,v.label,v.description,v.family_key,v.family_label,v.value_type,v.default_value_json,v.scope_label,v.approval_class,v.state from public.angelcare360_schools s cross join lateral (values (s.id,'institution.identity','Identité de l’établissement','Nom, logo autorisé, coordonnées et présentation visible.','general','Identité de l’établissement','object','{}'::jsonb,'Établissement','Direction','active'),(s.id,'institution.locale','Formats & localisation','Langue, fuseau horaire, formats de date et début de semaine.','general','Localisation et formats','object','{"language":"fr","timezone":"Africa/Casablanca","currency":"Dh"}'::jsonb,'Établissement','Administration','active'),(s.id,'academic.period_template','Modèle de périodes','Organisation attendue des trimestres ou semestres.','academic','Calendrier de fonctionnement','object','{}'::jsonb,'Année scolaire','Direction','active'),(s.id,'capacity.reservation_duration','Durée de réservation d’une place','Durée pendant laquelle une place reste bloquée avant confirmation.','capacity','Classes et capacités','duration','{"days":7}'::jsonb,'Établissement','Administration','active'),(s.id,'curriculum.required_domains','Domaines pédagogiques obligatoires','Domaines attendus pour chaque niveau.','curriculum','Programme pédagogique','multi','[]'::jsonb,'Réseau','Coordination pédagogique','active'),(s.id,'assignment.workload_threshold','Seuil de charge pédagogique','Seuil déclenchant une vérification avant une nouvelle affectation.','assignments','Équipe et affectations','number','{"hours_per_week":24}'::jsonb,'Établissement','Direction','active'),(s.id,'access.review_frequency','Fréquence de revue des accès','Période entre deux revues formelles des accès sensibles.','access','Utilisateurs et accès','duration','{"days":90}'::jsonb,'Réseau','Direction','active'),(s.id,'notifications.quiet_hours','Heures sans notifications','Plage pendant laquelle les notifications non urgentes sont différées.','notifications','Notifications','object','{"from":"20:00","to":"07:00"}'::jsonb,'Établissement','Administration','active'),(s.id,'documents.communication_footer','Signature des communications','Pied de page utilisé dans les communications autorisées.','templates','Documents','text','{"text":""}'::jsonb,'Établissement','Administration','active'),(s.id,'integrations.messaging','Messagerie institutionnelle','Configuration gouvernée du connecteur de messagerie.','integrations','Intégrations','object','{}'::jsonb,'Établissement','Direction','active')) as v(school_id,configuration_key,label,description,family_key,family_label,value_type,default_value_json,scope_label,approval_class,state) on conflict(school_id,configuration_key) do nothing;
insert into public.angelcare360_settings_template_variables(school_id,variable_key,label,value_type,sensitive,state) select v.school_id,v.variable_key,v.label,v.value_type,v.sensitive,v.state from public.angelcare360_schools s cross join lateral (values (s.id,'child_name','Prénom de l’enfant','text',false,'active'),(s.id,'parent_name','Nom du parent','text',false,'active'),(s.id,'institution_name','Nom de l’établissement','text',false,'active'),(s.id,'class_name','Classe','text',false,'active'),(s.id,'due_date','Date d’échéance','text',false,'active'),(s.id,'outstanding_amount','Montant restant','text',true,'active'),(s.id,'appointment_date','Date du rendez-vous','text',false,'active'),(s.id,'school_contact','Contact de l’établissement','text',false,'active')) as v(school_id,variable_key,label,value_type,sensitive,state) on conflict(school_id,variable_key) do nothing;
insert into public.angelcare360_operator_product_operations(operation_key,route_path,feature_key,operation_name,permission_key,audit_event,mutation_endpoints,source_confidence,status) values
('configuration_item.create','/angelcare-360-command-center/administration?plane=settings','administration.settings','create','angelcare360.administration.configure','customer.settings.configuration_item.create','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_item.update_draft','/angelcare-360-command-center/administration?plane=settings','administration.settings','update draft','angelcare360.administration.configure','customer.settings.configuration_item.update_draft','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_item.validate','/angelcare-360-command-center/administration?plane=settings','administration.settings','validate','angelcare360.administration.configure','customer.settings.configuration_item.validate','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_item.request_approval','/angelcare-360-command-center/administration?plane=settings','administration.settings','request approval','angelcare360.administration.configure','customer.settings.configuration_item.request_approval','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_item.approve','/angelcare-360-command-center/administration?plane=settings','administration.settings','approve','angelcare360.administration.approve','customer.settings.configuration_item.approve','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_item.schedule','/angelcare-360-command-center/administration?plane=settings','administration.settings','schedule','angelcare360.administration.configure','customer.settings.configuration_item.schedule','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_item.activate','/angelcare-360-command-center/administration?plane=settings','administration.settings','activate','angelcare360.administration.approve','customer.settings.configuration_item.activate','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_item.suspend','/angelcare-360-command-center/administration?plane=settings','administration.settings','suspend','angelcare360.administration.configure','customer.settings.configuration_item.suspend','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_item.replace','/angelcare-360-command-center/administration?plane=settings','administration.settings','replace','angelcare360.administration.configure','customer.settings.configuration_item.replace','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_item.archive','/angelcare-360-command-center/administration?plane=settings','administration.settings','archive','angelcare360.administration.configure','customer.settings.configuration_item.archive','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('policy.create','/angelcare-360-command-center/administration?plane=settings','administration.settings','create','angelcare360.administration.configure','customer.settings.policy.create','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('policy.update_draft','/angelcare-360-command-center/administration?plane=settings','administration.settings','update draft','angelcare360.administration.configure','customer.settings.policy.update_draft','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('policy.prepare_version','/angelcare-360-command-center/administration?plane=settings','administration.settings','prepare version','angelcare360.administration.configure','customer.settings.policy.prepare_version','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('policy.compare_version','/angelcare-360-command-center/administration?plane=settings','administration.settings','compare version','angelcare360.administration.configure','customer.settings.policy.compare_version','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('policy.request_approval','/angelcare-360-command-center/administration?plane=settings','administration.settings','request approval','angelcare360.administration.configure','customer.settings.policy.request_approval','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('policy.approve','/angelcare-360-command-center/administration?plane=settings','administration.settings','approve','angelcare360.administration.approve','customer.settings.policy.approve','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('policy.publish_version','/angelcare-360-command-center/administration?plane=settings','administration.settings','publish version','angelcare360.administration.approve','customer.settings.policy.publish_version','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('policy.schedule_end','/angelcare-360-command-center/administration?plane=settings','administration.settings','schedule end','angelcare360.administration.configure','customer.settings.policy.schedule_end','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('policy.retire','/angelcare-360-command-center/administration?plane=settings','administration.settings','retire','angelcare360.administration.configure','customer.settings.policy.retire','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_variation.create','/angelcare-360-command-center/administration?plane=settings','administration.settings','create','angelcare360.administration.configure','customer.settings.configuration_variation.create','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_variation.update','/angelcare-360-command-center/administration?plane=settings','administration.settings','update','angelcare360.administration.configure','customer.settings.configuration_variation.update','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_variation.request_approval','/angelcare-360-command-center/administration?plane=settings','administration.settings','request approval','angelcare360.administration.configure','customer.settings.configuration_variation.request_approval','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_variation.approve','/angelcare-360-command-center/administration?plane=settings','administration.settings','approve','angelcare360.administration.approve','customer.settings.configuration_variation.approve','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_variation.reject','/angelcare-360-command-center/administration?plane=settings','administration.settings','reject','angelcare360.administration.configure','customer.settings.configuration_variation.reject','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_variation.activate','/angelcare-360-command-center/administration?plane=settings','administration.settings','activate','angelcare360.administration.approve','customer.settings.configuration_variation.activate','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_variation.end','/angelcare-360-command-center/administration?plane=settings','administration.settings','end','angelcare360.administration.configure','customer.settings.configuration_variation.end','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_variation.expire','/angelcare-360-command-center/administration?plane=settings','administration.settings','expire','angelcare360.administration.configure','customer.settings.configuration_variation.expire','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_release.create','/angelcare-360-command-center/administration?plane=settings','administration.settings','create','angelcare360.administration.configure','customer.settings.configuration_release.create','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_release.add_item','/angelcare-360-command-center/administration?plane=settings','administration.settings','add item','angelcare360.administration.configure','customer.settings.configuration_release.add_item','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_release.remove_item','/angelcare-360-command-center/administration?plane=settings','administration.settings','remove item','angelcare360.administration.configure','customer.settings.configuration_release.remove_item','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_release.validate','/angelcare-360-command-center/administration?plane=settings','administration.settings','validate','angelcare360.administration.configure','customer.settings.configuration_release.validate','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_release.request_approval','/angelcare-360-command-center/administration?plane=settings','administration.settings','request approval','angelcare360.administration.configure','customer.settings.configuration_release.request_approval','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_release.approve','/angelcare-360-command-center/administration?plane=settings','administration.settings','approve','angelcare360.administration.approve','customer.settings.configuration_release.approve','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_release.schedule','/angelcare-360-command-center/administration?plane=settings','administration.settings','schedule','angelcare360.administration.configure','customer.settings.configuration_release.schedule','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_release.activate','/angelcare-360-command-center/administration?plane=settings','administration.settings','activate','angelcare360.administration.approve','customer.settings.configuration_release.activate','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_release.retry_item','/angelcare-360-command-center/administration?plane=settings','administration.settings','retry item','angelcare360.administration.configure','customer.settings.configuration_release.retry_item','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_release.complete','/angelcare-360-command-center/administration?plane=settings','administration.settings','complete','angelcare360.administration.configure','customer.settings.configuration_release.complete','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_release.cancel','/angelcare-360-command-center/administration?plane=settings','administration.settings','cancel','angelcare360.administration.configure','customer.settings.configuration_release.cancel','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_rollback.preview','/angelcare-360-command-center/administration?plane=settings','administration.settings','preview','angelcare360.administration.configure','customer.settings.configuration_rollback.preview','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_rollback.request','/angelcare-360-command-center/administration?plane=settings','administration.settings','request','angelcare360.administration.configure','customer.settings.configuration_rollback.request','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_rollback.approve','/angelcare-360-command-center/administration?plane=settings','administration.settings','approve','angelcare360.administration.approve','customer.settings.configuration_rollback.approve','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_rollback.execute','/angelcare-360-command-center/administration?plane=settings','administration.settings','execute','angelcare360.administration.approve','customer.settings.configuration_rollback.execute','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_emergency.request','/angelcare-360-command-center/administration?plane=settings','administration.settings','request','angelcare360.administration.configure','customer.settings.configuration_emergency.request','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_emergency.approve','/angelcare-360-command-center/administration?plane=settings','administration.settings','approve','angelcare360.administration.approve','customer.settings.configuration_emergency.approve','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_emergency.activate','/angelcare-360-command-center/administration?plane=settings','administration.settings','activate','angelcare360.administration.approve','customer.settings.configuration_emergency.activate','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_emergency.review','/angelcare-360-command-center/administration?plane=settings','administration.settings','review','angelcare360.administration.configure','customer.settings.configuration_emergency.review','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_emergency.end','/angelcare-360-command-center/administration?plane=settings','administration.settings','end','angelcare360.administration.configure','customer.settings.configuration_emergency.end','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('template.create','/angelcare-360-command-center/administration?plane=settings','administration.settings','create','angelcare360.administration.configure','customer.settings.template.create','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('template.update_draft','/angelcare-360-command-center/administration?plane=settings','administration.settings','update draft','angelcare360.administration.configure','customer.settings.template.update_draft','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('template.preview','/angelcare-360-command-center/administration?plane=settings','administration.settings','preview','angelcare360.administration.configure','customer.settings.template.preview','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('template.validate','/angelcare-360-command-center/administration?plane=settings','administration.settings','validate','angelcare360.administration.configure','customer.settings.template.validate','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('template.request_approval','/angelcare-360-command-center/administration?plane=settings','administration.settings','request approval','angelcare360.administration.configure','customer.settings.template.request_approval','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('template.publish_version','/angelcare-360-command-center/administration?plane=settings','administration.settings','publish version','angelcare360.administration.approve','customer.settings.template.publish_version','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('template.replace','/angelcare-360-command-center/administration?plane=settings','administration.settings','replace','angelcare360.administration.configure','customer.settings.template.replace','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('template.retire','/angelcare-360-command-center/administration?plane=settings','administration.settings','retire','angelcare360.administration.configure','customer.settings.template.retire','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('notification_policy.create','/angelcare-360-command-center/administration?plane=settings','administration.settings','create','angelcare360.administration.configure','customer.settings.notification_policy.create','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('notification_policy.update','/angelcare-360-command-center/administration?plane=settings','administration.settings','update','angelcare360.administration.configure','customer.settings.notification_policy.update','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('notification_policy.activate','/angelcare-360-command-center/administration?plane=settings','administration.settings','activate','angelcare360.administration.approve','customer.settings.notification_policy.activate','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('notification_policy.suspend','/angelcare-360-command-center/administration?plane=settings','administration.settings','suspend','angelcare360.administration.configure','customer.settings.notification_policy.suspend','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('integration_configuration.create','/angelcare-360-command-center/administration?plane=settings','administration.settings','create','angelcare360.integrations.configure','customer.settings.integration_configuration.create','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('integration_configuration.verify','/angelcare-360-command-center/administration?plane=settings','administration.settings','verify','angelcare360.integrations.configure','customer.settings.integration_configuration.verify','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('integration_configuration.update','/angelcare-360-command-center/administration?plane=settings','administration.settings','update','angelcare360.integrations.configure','customer.settings.integration_configuration.update','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('integration_configuration.suspend','/angelcare-360-command-center/administration?plane=settings','administration.settings','suspend','angelcare360.integrations.configure','customer.settings.integration_configuration.suspend','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('integration_configuration.restore','/angelcare-360-command-center/administration?plane=settings','administration.settings','restore','angelcare360.integrations.configure','customer.settings.integration_configuration.restore','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('integration_configuration.disconnect','/angelcare-360-command-center/administration?plane=settings','administration.settings','disconnect','angelcare360.integrations.configure','customer.settings.integration_configuration.disconnect','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_issue.assign','/angelcare-360-command-center/administration?plane=settings','administration.settings','assign','angelcare360.administration.audit','customer.settings.configuration_issue.assign','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_issue.resolve','/angelcare-360-command-center/administration?plane=settings','administration.settings','resolve','angelcare360.administration.audit','customer.settings.configuration_issue.resolve','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_issue.reopen','/angelcare-360-command-center/administration?plane=settings','administration.settings','reopen','angelcare360.administration.audit','customer.settings.configuration_issue.reopen','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_task.assign','/angelcare-360-command-center/administration?plane=settings','administration.settings','assign','angelcare360.administration.audit','customer.settings.configuration_task.assign','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_task.complete','/angelcare-360-command-center/administration?plane=settings','administration.settings','complete','angelcare360.administration.audit','customer.settings.configuration_task.complete','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_task.reopen','/angelcare-360-command-center/administration?plane=settings','administration.settings','reopen','angelcare360.administration.audit','customer.settings.configuration_task.reopen','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_note.add','/angelcare-360-command-center/administration?plane=settings','administration.settings','add','angelcare360.administration.configure','customer.settings.configuration_note.add','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_evidence.request','/angelcare-360-command-center/administration?plane=settings','administration.settings','request','angelcare360.administration.configure','customer.settings.configuration_evidence.request','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published'),
('configuration_topup.request','/angelcare-360-command-center/administration?plane=settings','administration.settings','request','angelcare360.administration.configure','customer.settings.configuration_topup.request','["/api/angelcare360/settings"]'::jsonb,'signed_area7_contract','published')
on conflict(operation_key) do update set route_path=excluded.route_path,feature_key=excluded.feature_key,operation_name=excluded.operation_name,permission_key=excluded.permission_key,audit_event=excluded.audit_event,mutation_endpoints=excluded.mutation_endpoints,source_confidence=excluded.source_confidence,status=excluded.status,updated_at=now();
commit;
