BEGIN;
SET LOCAL lock_timeout='5min';
SET LOCAL statement_timeout='15min';
SELECT pg_advisory_xact_lock(84746003);
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE OR REPLACE FUNCTION public.hsd_commercial_current_tenant() RETURNS text LANGUAGE sql STABLE AS $$
 SELECT coalesce(auth.jwt()->>'tenant_id',auth.jwt()->'app_metadata'->>'tenant_id',auth.jwt()->'user_metadata'->>'tenant_id');
$$;
DO $$ BEGIN IF to_regclass('public.hsd_service_categories') IS NULL THEN RAISE EXCEPTION 'UMZ1 baseline missing'; END IF; IF to_regclass('public.hsd_technical_plan_versions') IS NULL THEN RAISE EXCEPTION 'UMZ2 baseline missing'; END IF; END $$;
CREATE TABLE IF NOT EXISTS public.hsd_commercial_requests (id uuid primary key default gen_random_uuid(),tenant_id text not null,code text not null,title text not null,universe text not null check(universe in ('b2c','b2b')),status text not null default 'draft',technical_plan_id uuid not null references public.hsd_technical_plans(id),technical_plan_version_id uuid not null references public.hsd_technical_plan_versions(id),category_id uuid references public.hsd_service_categories(id),customer_segment text not null,commercial_objective text not null,scenario_count int not null default 1 check(scenario_count between 1 and 10),constraints jsonb not null default '{}',created_by text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,code));
ALTER TABLE public.hsd_commercial_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_commercial_requests_tenant_select ON public.hsd_commercial_requests;
CREATE POLICY hsd_commercial_requests_tenant_select ON public.hsd_commercial_requests FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_commercial_request_constraints (id uuid primary key default gen_random_uuid(),tenant_id text not null,request_id uuid not null references public.hsd_commercial_requests(id) on delete cascade,constraint_code text not null,value_json jsonb not null,mandatory boolean not null default true,created_at timestamptz not null default now());
ALTER TABLE public.hsd_commercial_request_constraints ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_commercial_request_constraints_tenant_select ON public.hsd_commercial_request_constraints;
CREATE POLICY hsd_commercial_request_constraints_tenant_select ON public.hsd_commercial_request_constraints FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_commercial_generation_runs (id uuid primary key default gen_random_uuid(),tenant_id text not null,request_id uuid not null references public.hsd_commercial_requests(id),task text not null,status text not null,provider_route text not null default 'openrouter/free' check(provider_route='openrouter/free'),actual_model text,provider_response_id text,duration_ms int,prompt_tokens int not null default 0,completion_tokens int not null default 0,total_tokens int not null default 0,retry_count int not null default 0,failure_code text,failure_message text,created_by text,started_at timestamptz not null default now(),created_at timestamptz not null default now(),completed_at timestamptz);
ALTER TABLE public.hsd_commercial_generation_runs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_commercial_generation_runs_tenant_select ON public.hsd_commercial_generation_runs;
CREATE POLICY hsd_commercial_generation_runs_tenant_select ON public.hsd_commercial_generation_runs FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_commercial_generation_sources (id uuid primary key default gen_random_uuid(),tenant_id text not null,run_id uuid not null references public.hsd_commercial_generation_runs(id) on delete cascade,source_type text not null,source_id text not null,source_version text,snapshot_hash text,created_at timestamptz not null default now());
ALTER TABLE public.hsd_commercial_generation_sources ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_commercial_generation_sources_tenant_select ON public.hsd_commercial_generation_sources;
CREATE POLICY hsd_commercial_generation_sources_tenant_select ON public.hsd_commercial_generation_sources FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_commercial_scenarios (id uuid primary key default gen_random_uuid(),tenant_id text not null,request_id uuid not null references public.hsd_commercial_requests(id) on delete cascade,generation_run_id uuid references public.hsd_commercial_generation_runs(id),code text not null,name text not null,intent text not null,promise text not null default '',customer_fit text not null default '',beneficiary_fit text not null default '',status text not null default 'composed',technical_plan_version_id uuid not null references public.hsd_technical_plan_versions(id),included_features jsonb not null default '[]',optional_topups jsonb not null default '[]',recommended_upsells jsonb not null default '[]',commercial_risks jsonb not null default '[]',upgrade_path text not null default '',calculation_snapshot jsonb,provider_route text not null default 'openrouter/free' check(provider_route='openrouter/free'),actual_model text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,code));
ALTER TABLE public.hsd_commercial_scenarios ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_commercial_scenarios_tenant_select ON public.hsd_commercial_scenarios;
CREATE POLICY hsd_commercial_scenarios_tenant_select ON public.hsd_commercial_scenarios FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_commercial_scenario_items (id uuid primary key default gen_random_uuid(),tenant_id text not null,scenario_id uuid not null references public.hsd_commercial_scenarios(id) on delete cascade,item_type text not null,item_code text not null,label text not null,quantity numeric not null default 1,configuration jsonb not null default '{}',sort_order int not null default 0);
ALTER TABLE public.hsd_commercial_scenario_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_commercial_scenario_items_tenant_select ON public.hsd_commercial_scenario_items;
CREATE POLICY hsd_commercial_scenario_items_tenant_select ON public.hsd_commercial_scenario_items FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_commercial_price_books (id uuid primary key default gen_random_uuid(),tenant_id text not null,code text not null,name text not null,universe text not null check(universe in ('b2c','b2b')),status text not null default 'draft',current_version int not null default 1,created_by text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,code));
ALTER TABLE public.hsd_commercial_price_books ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_commercial_price_books_tenant_select ON public.hsd_commercial_price_books;
CREATE POLICY hsd_commercial_price_books_tenant_select ON public.hsd_commercial_price_books FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_commercial_price_book_versions (id uuid primary key default gen_random_uuid(),tenant_id text not null,price_book_id uuid not null references public.hsd_commercial_price_books(id),version_number int not null,status text not null default 'draft',effective_from date,effective_to date,approved_by text,approved_at timestamptz,created_at timestamptz not null default now(),unique(price_book_id,version_number),check(effective_to is null or effective_from is null or effective_to>=effective_from));
ALTER TABLE public.hsd_commercial_price_book_versions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_commercial_price_book_versions_tenant_select ON public.hsd_commercial_price_book_versions;
CREATE POLICY hsd_commercial_price_book_versions_tenant_select ON public.hsd_commercial_price_book_versions FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_commercial_price_entries (id uuid primary key default gen_random_uuid(),tenant_id text not null,price_book_version_id uuid not null references public.hsd_commercial_price_book_versions(id),category_id uuid references public.hsd_service_categories(id),service_reference_id uuid references public.hsd_service_references(id),pricing_basis text not null check(pricing_basis in ('hour','mission','day','dossier','unit','fixed')),customer_segment text,geographic_zone text,quantity_min numeric not null default 1,quantity_max numeric,unit_price numeric(14,2) not null check(unit_price>=0),effective_from date,effective_to date,status text not null default 'active',created_at timestamptz not null default now(),check(quantity_max is null or quantity_max>=quantity_min));
ALTER TABLE public.hsd_commercial_price_entries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_commercial_price_entries_tenant_select ON public.hsd_commercial_price_entries;
CREATE POLICY hsd_commercial_price_entries_tenant_select ON public.hsd_commercial_price_entries FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_cost_books (id uuid primary key default gen_random_uuid(),tenant_id text not null,code text not null,name text not null,status text not null default 'draft',current_version int not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,code));
ALTER TABLE public.hsd_cost_books ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_cost_books_tenant_select ON public.hsd_cost_books;
CREATE POLICY hsd_cost_books_tenant_select ON public.hsd_cost_books FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_cost_entries (id uuid primary key default gen_random_uuid(),tenant_id text not null,cost_book_id uuid not null references public.hsd_cost_books(id),cost_code text not null,label text not null,cost_type text not null,cost_basis text not null,category_id uuid references public.hsd_service_categories(id),amount numeric(14,2),cost_state text not null check(cost_state in ('known','estimated','missing','not_applicable')),confidence numeric(5,2),effective_from date,effective_to date,source_reference text,status text not null default 'active',created_at timestamptz not null default now(),check(amount is null or amount>=0));
ALTER TABLE public.hsd_cost_entries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_cost_entries_tenant_select ON public.hsd_cost_entries;
CREATE POLICY hsd_cost_entries_tenant_select ON public.hsd_cost_entries FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_tax_profiles (id uuid primary key default gen_random_uuid(),tenant_id text not null,code text not null,name text not null,rate numeric(7,4) not null default 0 check(rate>=0),status text not null default 'active',effective_from date,effective_to date,created_at timestamptz not null default now(),unique(tenant_id,code));
ALTER TABLE public.hsd_tax_profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_tax_profiles_tenant_select ON public.hsd_tax_profiles;
CREATE POLICY hsd_tax_profiles_tenant_select ON public.hsd_tax_profiles FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_surcharge_rules (id uuid primary key default gen_random_uuid(),tenant_id text not null,code text not null,name text not null,rule_type text not null check(rule_type in ('night','weekend','holiday','urgency','short_notice','transport_zone','additional_beneficiary','additional_caregiver')),calculation_basis text not null,value numeric(14,4) not null check(value>=0),category_id uuid references public.hsd_service_categories(id),universe text check(universe in ('b2c','b2b')),conditions jsonb not null default '{}',effective_from date,effective_to date,status text not null default 'active',created_at timestamptz not null default now(),unique(tenant_id,code));
ALTER TABLE public.hsd_surcharge_rules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_surcharge_rules_tenant_select ON public.hsd_surcharge_rules;
CREATE POLICY hsd_surcharge_rules_tenant_select ON public.hsd_surcharge_rules FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_discount_rules (id uuid primary key default gen_random_uuid(),tenant_id text not null,code text not null,name text not null,discount_type text not null,calculation_basis text not null,value numeric(14,4) not null check(value>=0),maximum_percent numeric(7,4),maximum_amount numeric(14,2),minimum_margin_after numeric(7,4) not null default 0,universe text check(universe in ('b2c','b2b')),category_id uuid references public.hsd_service_categories(id),quantity_threshold numeric,combinable boolean not null default false,approval_permission text,effective_from date,effective_to date,usage_limit int,status text not null default 'active',created_at timestamptz not null default now(),unique(tenant_id,code));
ALTER TABLE public.hsd_discount_rules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_discount_rules_tenant_select ON public.hsd_discount_rules;
CREATE POLICY hsd_discount_rules_tenant_select ON public.hsd_discount_rules FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_discount_exceptions (id uuid primary key default gen_random_uuid(),tenant_id text not null,offer_id uuid,requested_percent numeric(7,4),requested_amount numeric(14,2),margin_after numeric(7,4),reason text not null,evidence jsonb not null default '[]',status text not null default 'approval_requested',requested_by text not null,decided_by text,decision_reason text,requested_at timestamptz not null default now(),decided_at timestamptz);
ALTER TABLE public.hsd_discount_exceptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_discount_exceptions_tenant_select ON public.hsd_discount_exceptions;
CREATE POLICY hsd_discount_exceptions_tenant_select ON public.hsd_discount_exceptions FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_margin_rules (id uuid primary key default gen_random_uuid(),tenant_id text not null,code text not null,name text not null,universe text check(universe in ('b2c','b2b')),category_id uuid references public.hsd_service_categories(id),minimum_margin_percent numeric(7,4) not null check(minimum_margin_percent>=0),approval_threshold_percent numeric(7,4),block_below_zero boolean not null default true,effective_from date,effective_to date,status text not null default 'active',created_at timestamptz not null default now(),unique(tenant_id,code));
ALTER TABLE public.hsd_margin_rules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_margin_rules_tenant_select ON public.hsd_margin_rules;
CREATE POLICY hsd_margin_rules_tenant_select ON public.hsd_margin_rules FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_offer_drafts (id uuid primary key default gen_random_uuid(),tenant_id text not null,code text not null,title text not null,universe text not null check(universe in ('b2c','b2b')),status text not null default 'draft',technical_plan_version_id uuid not null references public.hsd_technical_plan_versions(id),scenario_id uuid references public.hsd_commercial_scenarios(id),customer_segment text,commercial_name text,promise text,calculation_snapshot jsonb,validity_days int not null default 30 check(validity_days>0),approved_by text,approved_at timestamptz,published_at timestamptz,created_by text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,code));
ALTER TABLE public.hsd_offer_drafts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_offer_drafts_tenant_select ON public.hsd_offer_drafts;
CREATE POLICY hsd_offer_drafts_tenant_select ON public.hsd_offer_drafts FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_offer_versions (id uuid primary key default gen_random_uuid(),tenant_id text not null,offer_id uuid not null references public.hsd_offer_drafts(id),version_number int not null,status text not null,snapshot jsonb not null,calculation_hash text,created_by text,created_at timestamptz not null default now(),unique(offer_id,version_number));
ALTER TABLE public.hsd_offer_versions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_offer_versions_tenant_select ON public.hsd_offer_versions;
CREATE POLICY hsd_offer_versions_tenant_select ON public.hsd_offer_versions FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_offer_items (id uuid primary key default gen_random_uuid(),tenant_id text not null,offer_id uuid not null references public.hsd_offer_drafts(id) on delete cascade,item_type text not null,item_code text not null,label text not null,quantity numeric not null default 1,unit_price numeric(14,2) not null default 0,cost_amount numeric(14,2),taxable boolean not null default true,source_rule_id uuid,source_version text,sort_order int not null default 0);
ALTER TABLE public.hsd_offer_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_offer_items_tenant_select ON public.hsd_offer_items;
CREATE POLICY hsd_offer_items_tenant_select ON public.hsd_offer_items FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_offer_features (id uuid primary key default gen_random_uuid(),tenant_id text not null,offer_id uuid not null references public.hsd_offer_drafts(id) on delete cascade,service_option_id uuid references public.hsd_service_options(id),option_code text not null,label text not null,included boolean not null default true,configuration jsonb not null default '{}',created_at timestamptz not null default now());
ALTER TABLE public.hsd_offer_features ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_offer_features_tenant_select ON public.hsd_offer_features;
CREATE POLICY hsd_offer_features_tenant_select ON public.hsd_offer_features FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_offer_topups (id uuid primary key default gen_random_uuid(),tenant_id text not null,offer_id uuid not null references public.hsd_offer_drafts(id) on delete cascade,service_option_id uuid references public.hsd_service_options(id),option_code text not null,label text not null,quantity numeric not null default 1,configuration jsonb not null default '{}',created_at timestamptz not null default now());
ALTER TABLE public.hsd_offer_topups ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_offer_topups_tenant_select ON public.hsd_offer_topups;
CREATE POLICY hsd_offer_topups_tenant_select ON public.hsd_offer_topups FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_offer_upsells (id uuid primary key default gen_random_uuid(),tenant_id text not null,offer_id uuid not null references public.hsd_offer_drafts(id) on delete cascade,service_option_id uuid references public.hsd_service_options(id),option_code text not null,label text not null,recommendation_reason text,selected boolean not null default false,created_at timestamptz not null default now());
ALTER TABLE public.hsd_offer_upsells ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_offer_upsells_tenant_select ON public.hsd_offer_upsells;
CREATE POLICY hsd_offer_upsells_tenant_select ON public.hsd_offer_upsells FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_offer_calculations (id uuid primary key default gen_random_uuid(),tenant_id text not null,offer_id uuid not null references public.hsd_offer_drafts(id),calculation_version int not null,calculation jsonb not null,customer_total numeric(14,2) not null,known_cost_total numeric(14,2) not null,gross_margin numeric(14,2),margin_percent numeric(7,4),margin_status text not null,missing_cost_codes jsonb not null default '[]',calculated_by text,calculated_at timestamptz not null default now(),unique(offer_id,calculation_version));
ALTER TABLE public.hsd_offer_calculations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_offer_calculations_tenant_select ON public.hsd_offer_calculations;
CREATE POLICY hsd_offer_calculations_tenant_select ON public.hsd_offer_calculations FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_offer_terms (id uuid primary key default gen_random_uuid(),tenant_id text not null,offer_id uuid not null references public.hsd_offer_drafts(id) on delete cascade,term_type text not null,title text not null,content text not null,customer_visible boolean not null default true,sort_order int not null default 0,created_at timestamptz not null default now());
ALTER TABLE public.hsd_offer_terms ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_offer_terms_tenant_select ON public.hsd_offer_terms;
CREATE POLICY hsd_offer_terms_tenant_select ON public.hsd_offer_terms FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_offer_validations (id uuid primary key default gen_random_uuid(),tenant_id text not null,offer_id uuid not null references public.hsd_offer_drafts(id) on delete cascade,discipline text not null,status text not null,severity text,detail text,corrective_action text,owner_id text,resolved_at timestamptz,created_at timestamptz not null default now());
ALTER TABLE public.hsd_offer_validations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_offer_validations_tenant_select ON public.hsd_offer_validations;
CREATE POLICY hsd_offer_validations_tenant_select ON public.hsd_offer_validations FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_offer_approvals (id uuid primary key default gen_random_uuid(),tenant_id text not null,offer_id uuid not null references public.hsd_offer_drafts(id),status text not null default 'requested',requested_by text not null,requested_at timestamptz not null default now(),decided_by text,decided_at timestamptz,decision_reason text);
ALTER TABLE public.hsd_offer_approvals ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_offer_approvals_tenant_select ON public.hsd_offer_approvals;
CREATE POLICY hsd_offer_approvals_tenant_select ON public.hsd_offer_approvals FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_bundles (id uuid primary key default gen_random_uuid(),tenant_id text not null,code text not null,name text not null,universe text not null check(universe in ('b2c','b2b')),status text not null default 'draft',bundle_type text not null,item_count int not null default 0,compatibility_status text not null default 'conditional',calculation_snapshot jsonb,approved_by text,approved_at timestamptz,published_at timestamptz,created_by text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,code));
ALTER TABLE public.hsd_bundles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_bundles_tenant_select ON public.hsd_bundles;
CREATE POLICY hsd_bundles_tenant_select ON public.hsd_bundles FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_bundle_versions (id uuid primary key default gen_random_uuid(),tenant_id text not null,bundle_id uuid not null references public.hsd_bundles(id),version_number int not null,status text not null,snapshot jsonb not null,created_at timestamptz not null default now(),unique(bundle_id,version_number));
ALTER TABLE public.hsd_bundle_versions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_bundle_versions_tenant_select ON public.hsd_bundle_versions;
CREATE POLICY hsd_bundle_versions_tenant_select ON public.hsd_bundle_versions FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_bundle_items (id uuid primary key default gen_random_uuid(),tenant_id text not null,bundle_id uuid not null references public.hsd_bundles(id) on delete cascade,offer_id uuid references public.hsd_offer_drafts(id),sellable_id uuid,item_type text not null,item_code text not null,label text not null,quantity numeric not null default 1,configuration jsonb not null default '{}',sort_order int not null default 0);
ALTER TABLE public.hsd_bundle_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_bundle_items_tenant_select ON public.hsd_bundle_items;
CREATE POLICY hsd_bundle_items_tenant_select ON public.hsd_bundle_items FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_bundle_compatibility_rules (id uuid primary key default gen_random_uuid(),tenant_id text not null,code text not null,rule_type text not null,source_category_id uuid references public.hsd_service_categories(id),target_category_id uuid references public.hsd_service_categories(id),source_service_reference_id uuid references public.hsd_service_references(id),target_service_reference_id uuid references public.hsd_service_references(id),severity text not null,conditions jsonb not null default '{}',resolution text,status text not null default 'active',created_at timestamptz not null default now(),unique(tenant_id,code));
ALTER TABLE public.hsd_bundle_compatibility_rules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_bundle_compatibility_rules_tenant_select ON public.hsd_bundle_compatibility_rules;
CREATE POLICY hsd_bundle_compatibility_rules_tenant_select ON public.hsd_bundle_compatibility_rules FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_bundle_findings (id uuid primary key default gen_random_uuid(),tenant_id text not null,bundle_id uuid not null references public.hsd_bundles(id) on delete cascade,code text not null,severity text not null,title text not null,detail text not null,item_ids jsonb not null default '[]',status text not null default 'open',created_at timestamptz not null default now(),resolved_at timestamptz);
ALTER TABLE public.hsd_bundle_findings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_bundle_findings_tenant_select ON public.hsd_bundle_findings;
CREATE POLICY hsd_bundle_findings_tenant_select ON public.hsd_bundle_findings FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_bundle_calculations (id uuid primary key default gen_random_uuid(),tenant_id text not null,bundle_id uuid not null references public.hsd_bundles(id),version_number int not null,calculation jsonb not null,customer_total numeric(14,2) not null,known_cost_total numeric(14,2) not null,gross_margin numeric(14,2),margin_percent numeric(7,4),created_at timestamptz not null default now(),unique(bundle_id,version_number));
ALTER TABLE public.hsd_bundle_calculations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_bundle_calculations_tenant_select ON public.hsd_bundle_calculations;
CREATE POLICY hsd_bundle_calculations_tenant_select ON public.hsd_bundle_calculations FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_bundle_approvals (id uuid primary key default gen_random_uuid(),tenant_id text not null,bundle_id uuid not null references public.hsd_bundles(id),status text not null default 'requested',requested_by text not null,requested_at timestamptz not null default now(),decided_by text,decided_at timestamptz,decision_reason text);
ALTER TABLE public.hsd_bundle_approvals ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_bundle_approvals_tenant_select ON public.hsd_bundle_approvals;
CREATE POLICY hsd_bundle_approvals_tenant_select ON public.hsd_bundle_approvals FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_sellables (id uuid primary key default gen_random_uuid(),tenant_id text not null,code text not null,commercial_name text not null,technical_name text not null,universe text not null check(universe in ('b2c','b2b')),status text not null default 'draft',category_id uuid references public.hsd_service_categories(id),technical_plan_version_id uuid not null references public.hsd_technical_plan_versions(id),offer_id uuid references public.hsd_offer_drafts(id),bundle_id uuid references public.hsd_bundles(id),active_version int not null default 1,promise text not null default '',calculation_snapshot jsonb,readiness text not null default 'conditional',approved_by text,approved_at timestamptz,published_at timestamptz,created_by text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,code),check((offer_id is not null)::int+(bundle_id is not null)::int=1));
ALTER TABLE public.hsd_sellables ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_sellables_tenant_select ON public.hsd_sellables;
CREATE POLICY hsd_sellables_tenant_select ON public.hsd_sellables FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_sellable_versions (id uuid primary key default gen_random_uuid(),tenant_id text not null,sellable_id uuid not null references public.hsd_sellables(id),version_number int not null,status text not null,snapshot jsonb not null,technical_plan_version_id uuid not null references public.hsd_technical_plan_versions(id),calculation_hash text,approved_by text,approved_at timestamptz,created_at timestamptz not null default now(),unique(sellable_id,version_number));
ALTER TABLE public.hsd_sellable_versions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_sellable_versions_tenant_select ON public.hsd_sellable_versions;
CREATE POLICY hsd_sellable_versions_tenant_select ON public.hsd_sellable_versions FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_sellable_items (id uuid primary key default gen_random_uuid(),tenant_id text not null,sellable_version_id uuid not null references public.hsd_sellable_versions(id),item_type text not null,item_code text not null,label text not null,quantity numeric not null default 1,configuration jsonb not null default '{}',sort_order int not null default 0);
ALTER TABLE public.hsd_sellable_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_sellable_items_tenant_select ON public.hsd_sellable_items;
CREATE POLICY hsd_sellable_items_tenant_select ON public.hsd_sellable_items FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_sellable_prices (id uuid primary key default gen_random_uuid(),tenant_id text not null,sellable_version_id uuid not null references public.hsd_sellable_versions(id),price_book_version_id uuid references public.hsd_commercial_price_book_versions(id),starting_price numeric(14,2),customer_total numeric(14,2),known_cost_total numeric(14,2),gross_margin numeric(14,2),margin_percent numeric(7,4),tax_total numeric(14,2),currency text not null default 'MAD',created_at timestamptz not null default now());
ALTER TABLE public.hsd_sellable_prices ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_sellable_prices_tenant_select ON public.hsd_sellable_prices;
CREATE POLICY hsd_sellable_prices_tenant_select ON public.hsd_sellable_prices FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_sellable_terms (id uuid primary key default gen_random_uuid(),tenant_id text not null,sellable_version_id uuid not null references public.hsd_sellable_versions(id),term_type text not null,title text not null,content text not null,customer_visible boolean not null default true,sort_order int not null default 0);
ALTER TABLE public.hsd_sellable_terms ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_sellable_terms_tenant_select ON public.hsd_sellable_terms;
CREATE POLICY hsd_sellable_terms_tenant_select ON public.hsd_sellable_terms FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_sellable_publications (id uuid primary key default gen_random_uuid(),tenant_id text not null,sellable_id uuid not null references public.hsd_sellables(id),sellable_version_id uuid not null references public.hsd_sellable_versions(id),universe text not null check(universe in ('b2c','b2b')),status text not null,scheduled_at timestamptz,published_at timestamptz,suspended_at timestamptz,retired_at timestamptz,actor_id text not null,reason text,created_at timestamptz not null default now());
ALTER TABLE public.hsd_sellable_publications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_sellable_publications_tenant_select ON public.hsd_sellable_publications;
CREATE POLICY hsd_sellable_publications_tenant_select ON public.hsd_sellable_publications FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_sellable_status_events (id uuid primary key default gen_random_uuid(),tenant_id text not null,sellable_id uuid not null references public.hsd_sellables(id),from_status text,to_status text not null,actor_id text not null,reason text,created_at timestamptz not null default now());
ALTER TABLE public.hsd_sellable_status_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_sellable_status_events_tenant_select ON public.hsd_sellable_status_events;
CREATE POLICY hsd_sellable_status_events_tenant_select ON public.hsd_sellable_status_events FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_sellable_documents (id uuid primary key default gen_random_uuid(),tenant_id text not null,sellable_id uuid not null references public.hsd_sellables(id),document_type text not null,title text not null,current_version int not null default 1,status text not null default 'draft',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
ALTER TABLE public.hsd_sellable_documents ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_sellable_documents_tenant_select ON public.hsd_sellable_documents;
CREATE POLICY hsd_sellable_documents_tenant_select ON public.hsd_sellable_documents FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
CREATE TABLE IF NOT EXISTS public.hsd_package_archetypes (id uuid primary key default gen_random_uuid(),tenant_id text not null,code text not null,name_fr text not null,universe text not null check(universe in ('b2c','b2b','both')),description_fr text not null default '',configuration jsonb not null default '{}',status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,code));
ALTER TABLE public.hsd_package_archetypes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_package_archetypes_tenant_select ON public.hsd_package_archetypes;
CREATE POLICY hsd_package_archetypes_tenant_select ON public.hsd_package_archetypes FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
GRANT SELECT ON public.hsd_package_archetypes TO authenticated; GRANT ALL ON public.hsd_package_archetypes TO service_role;
CREATE TABLE IF NOT EXISTS public.hsd_sellable_document_versions (id uuid primary key default gen_random_uuid(),tenant_id text not null,document_id uuid not null references public.hsd_sellable_documents(id),version_number int not null,sellable_version_id uuid not null references public.hsd_sellable_versions(id),template_code text not null,orientation text not null check(orientation in ('portrait','landscape')),language text not null default 'fr',snapshot jsonb not null,storage_path text,sha256 text,status text not null default 'prepared',created_at timestamptz not null default now(),unique(document_id,version_number));
ALTER TABLE public.hsd_sellable_document_versions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_sellable_document_versions_tenant_select ON public.hsd_sellable_document_versions;
CREATE POLICY hsd_sellable_document_versions_tenant_select ON public.hsd_sellable_document_versions FOR SELECT USING (tenant_id = public.hsd_commercial_current_tenant());
ALTER TABLE public.hsd_discount_exceptions DROP CONSTRAINT IF EXISTS hsd_discount_exceptions_offer_id_fkey; ALTER TABLE public.hsd_discount_exceptions ADD CONSTRAINT hsd_discount_exceptions_offer_id_fkey FOREIGN KEY(offer_id) REFERENCES public.hsd_offer_drafts(id);
ALTER TABLE public.hsd_bundle_items DROP CONSTRAINT IF EXISTS hsd_bundle_items_sellable_id_fkey; ALTER TABLE public.hsd_bundle_items ADD CONSTRAINT hsd_bundle_items_sellable_id_fkey FOREIGN KEY(sellable_id) REFERENCES public.hsd_sellables(id);
CREATE INDEX IF NOT EXISTS idx_hsd_commercial_requests_operating ON public.hsd_commercial_requests(tenant_id,status,updated_at desc);
CREATE INDEX IF NOT EXISTS idx_hsd_commercial_scenarios_operating ON public.hsd_commercial_scenarios(tenant_id,request_id,created_at desc);
CREATE INDEX IF NOT EXISTS idx_hsd_commercial_generation_runs_operating ON public.hsd_commercial_generation_runs(tenant_id,status,created_at desc);
CREATE INDEX IF NOT EXISTS idx_hsd_commercial_price_entries_operating ON public.hsd_commercial_price_entries(tenant_id,price_book_version_id,status);
CREATE INDEX IF NOT EXISTS idx_hsd_cost_entries_operating ON public.hsd_cost_entries(tenant_id,cost_state,status);
CREATE INDEX IF NOT EXISTS idx_hsd_offer_drafts_operating ON public.hsd_offer_drafts(tenant_id,status,updated_at desc);
CREATE INDEX IF NOT EXISTS idx_hsd_bundles_operating ON public.hsd_bundles(tenant_id,status,updated_at desc);
CREATE INDEX IF NOT EXISTS idx_hsd_sellables_operating ON public.hsd_sellables(tenant_id,universe,status,updated_at desc);

CREATE OR REPLACE FUNCTION public.hsd_commercial_immutable_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Immutable commercial record'; END $$;
DO $$ DECLARE x text; BEGIN FOREACH x IN ARRAY ARRAY['hsd_offer_versions','hsd_offer_calculations','hsd_bundle_versions','hsd_bundle_calculations','hsd_sellable_versions','hsd_sellable_prices','hsd_sellable_publications','hsd_sellable_status_events','hsd_sellable_document_versions'] LOOP EXECUTE format('DROP TRIGGER IF EXISTS trg_%I_immutable ON public.%I',x,x); EXECUTE format('CREATE TRIGGER trg_%I_immutable BEFORE UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.hsd_commercial_immutable_guard()',x,x); END LOOP; END $$;
CREATE OR REPLACE FUNCTION public.hsd_sellable_mutation_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF OLD.status IN ('published','superseded','retired') AND (
 NEW.code IS DISTINCT FROM OLD.code OR NEW.commercial_name IS DISTINCT FROM OLD.commercial_name OR NEW.technical_name IS DISTINCT FROM OLD.technical_name OR NEW.universe IS DISTINCT FROM OLD.universe OR NEW.category_id IS DISTINCT FROM OLD.category_id OR NEW.technical_plan_version_id IS DISTINCT FROM OLD.technical_plan_version_id OR NEW.offer_id IS DISTINCT FROM OLD.offer_id OR NEW.bundle_id IS DISTINCT FROM OLD.bundle_id OR NEW.active_version IS DISTINCT FROM OLD.active_version OR NEW.promise IS DISTINCT FROM OLD.promise OR NEW.calculation_snapshot IS DISTINCT FROM OLD.calculation_snapshot OR NEW.readiness IS DISTINCT FROM OLD.readiness
 ) THEN RAISE EXCEPTION 'Published sellable content is immutable; create a new version'; END IF; RETURN NEW; END $$;
DROP TRIGGER IF EXISTS trg_hsd_sellables_immutable_published ON public.hsd_sellables; CREATE TRIGGER trg_hsd_sellables_immutable_published BEFORE UPDATE ON public.hsd_sellables FOR EACH ROW EXECUTE FUNCTION public.hsd_sellable_mutation_guard();
CREATE OR REPLACE VIEW public.hsd_commercial_price_books_v WITH (security_invoker=true) AS SELECT pb.id,pb.tenant_id,pb.code,pb.name,pb.universe,pb.status,pb.current_version version_number,v.effective_from,v.effective_to,count(e.id)::int entry_count FROM public.hsd_commercial_price_books pb LEFT JOIN public.hsd_commercial_price_book_versions v ON v.price_book_id=pb.id AND v.version_number=pb.current_version LEFT JOIN public.hsd_commercial_price_entries e ON e.price_book_version_id=v.id GROUP BY pb.id,v.effective_from,v.effective_to;
CREATE OR REPLACE VIEW public.hsd_sellable_registry_v WITH (security_invoker=true) AS SELECT s.id,s.tenant_id,s.code,s.commercial_name,s.technical_name,s.universe,s.status,s.category_id,s.active_version,s.promise,s.readiness,s.published_at,s.created_at,p.starting_price,p.margin_percent FROM public.hsd_sellables s LEFT JOIN public.hsd_sellable_versions v ON v.sellable_id=s.id AND v.version_number=s.active_version LEFT JOIN public.hsd_sellable_prices p ON p.sellable_version_id=v.id;
GRANT SELECT ON public.hsd_commercial_price_books_v,public.hsd_sellable_registry_v TO authenticated;
GRANT SELECT ON public.hsd_commercial_requests TO authenticated; GRANT ALL ON public.hsd_commercial_requests TO service_role;
GRANT SELECT ON public.hsd_commercial_request_constraints TO authenticated; GRANT ALL ON public.hsd_commercial_request_constraints TO service_role;
GRANT SELECT ON public.hsd_commercial_generation_runs TO authenticated; GRANT ALL ON public.hsd_commercial_generation_runs TO service_role;
GRANT SELECT ON public.hsd_commercial_generation_sources TO authenticated; GRANT ALL ON public.hsd_commercial_generation_sources TO service_role;
GRANT SELECT ON public.hsd_commercial_scenarios TO authenticated; GRANT ALL ON public.hsd_commercial_scenarios TO service_role;
GRANT SELECT ON public.hsd_commercial_scenario_items TO authenticated; GRANT ALL ON public.hsd_commercial_scenario_items TO service_role;
GRANT SELECT ON public.hsd_commercial_price_books TO authenticated; GRANT ALL ON public.hsd_commercial_price_books TO service_role;
GRANT SELECT ON public.hsd_commercial_price_book_versions TO authenticated; GRANT ALL ON public.hsd_commercial_price_book_versions TO service_role;
GRANT SELECT ON public.hsd_commercial_price_entries TO authenticated; GRANT ALL ON public.hsd_commercial_price_entries TO service_role;
GRANT SELECT ON public.hsd_cost_books TO authenticated; GRANT ALL ON public.hsd_cost_books TO service_role;
GRANT SELECT ON public.hsd_cost_entries TO authenticated; GRANT ALL ON public.hsd_cost_entries TO service_role;
GRANT SELECT ON public.hsd_tax_profiles TO authenticated; GRANT ALL ON public.hsd_tax_profiles TO service_role;
GRANT SELECT ON public.hsd_surcharge_rules TO authenticated; GRANT ALL ON public.hsd_surcharge_rules TO service_role;
GRANT SELECT ON public.hsd_discount_rules TO authenticated; GRANT ALL ON public.hsd_discount_rules TO service_role;
GRANT SELECT ON public.hsd_discount_exceptions TO authenticated; GRANT ALL ON public.hsd_discount_exceptions TO service_role;
GRANT SELECT ON public.hsd_margin_rules TO authenticated; GRANT ALL ON public.hsd_margin_rules TO service_role;
GRANT SELECT ON public.hsd_offer_drafts TO authenticated; GRANT ALL ON public.hsd_offer_drafts TO service_role;
GRANT SELECT ON public.hsd_offer_versions TO authenticated; GRANT ALL ON public.hsd_offer_versions TO service_role;
GRANT SELECT ON public.hsd_offer_items TO authenticated; GRANT ALL ON public.hsd_offer_items TO service_role;
GRANT SELECT ON public.hsd_offer_features TO authenticated; GRANT ALL ON public.hsd_offer_features TO service_role;
GRANT SELECT ON public.hsd_offer_topups TO authenticated; GRANT ALL ON public.hsd_offer_topups TO service_role;
GRANT SELECT ON public.hsd_offer_upsells TO authenticated; GRANT ALL ON public.hsd_offer_upsells TO service_role;
GRANT SELECT ON public.hsd_offer_calculations TO authenticated; GRANT ALL ON public.hsd_offer_calculations TO service_role;
GRANT SELECT ON public.hsd_offer_terms TO authenticated; GRANT ALL ON public.hsd_offer_terms TO service_role;
GRANT SELECT ON public.hsd_offer_validations TO authenticated; GRANT ALL ON public.hsd_offer_validations TO service_role;
GRANT SELECT ON public.hsd_offer_approvals TO authenticated; GRANT ALL ON public.hsd_offer_approvals TO service_role;
GRANT SELECT ON public.hsd_bundles TO authenticated; GRANT ALL ON public.hsd_bundles TO service_role;
GRANT SELECT ON public.hsd_bundle_versions TO authenticated; GRANT ALL ON public.hsd_bundle_versions TO service_role;
GRANT SELECT ON public.hsd_bundle_items TO authenticated; GRANT ALL ON public.hsd_bundle_items TO service_role;
GRANT SELECT ON public.hsd_bundle_compatibility_rules TO authenticated; GRANT ALL ON public.hsd_bundle_compatibility_rules TO service_role;
GRANT SELECT ON public.hsd_bundle_findings TO authenticated; GRANT ALL ON public.hsd_bundle_findings TO service_role;
GRANT SELECT ON public.hsd_bundle_calculations TO authenticated; GRANT ALL ON public.hsd_bundle_calculations TO service_role;
GRANT SELECT ON public.hsd_bundle_approvals TO authenticated; GRANT ALL ON public.hsd_bundle_approvals TO service_role;
GRANT SELECT ON public.hsd_sellables TO authenticated; GRANT ALL ON public.hsd_sellables TO service_role;
GRANT SELECT ON public.hsd_sellable_versions TO authenticated; GRANT ALL ON public.hsd_sellable_versions TO service_role;
GRANT SELECT ON public.hsd_sellable_items TO authenticated; GRANT ALL ON public.hsd_sellable_items TO service_role;
GRANT SELECT ON public.hsd_sellable_prices TO authenticated; GRANT ALL ON public.hsd_sellable_prices TO service_role;
GRANT SELECT ON public.hsd_sellable_terms TO authenticated; GRANT ALL ON public.hsd_sellable_terms TO service_role;
GRANT SELECT ON public.hsd_sellable_publications TO authenticated; GRANT ALL ON public.hsd_sellable_publications TO service_role;
GRANT SELECT ON public.hsd_sellable_status_events TO authenticated; GRANT ALL ON public.hsd_sellable_status_events TO service_role;
GRANT SELECT ON public.hsd_sellable_documents TO authenticated; GRANT ALL ON public.hsd_sellable_documents TO service_role;
GRANT SELECT ON public.hsd_sellable_document_versions TO authenticated; GRANT ALL ON public.hsd_sellable_document_versions TO service_role;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.view_commercial','Consulter l’univers commercial','Accès aux offres, bundles, vitrines et calculs non confidentiels.','standard') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.create_commercial_requests','Créer des demandes commerciales','Créer un brief commercial depuis un plan technique approuvé.','standard') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.generate_commercial_scenarios','Générer des scénarios commerciaux','Exécuter OpenRouter Free pour la composition narrative.','standard') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.edit_commercial_scenarios','Modifier des scénarios commerciaux','Ajuster les éléments non techniques des alternatives.','standard') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.manage_price_books','Gérer les grilles tarifaires','Créer et versionner les prix applicables.','high') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.manage_cost_books','Gérer les référentiels de coûts','Administrer les coûts connus, estimés ou manquants.','high') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.manage_tax_profiles','Gérer les profils fiscaux','Administrer les taux et périodes fiscales.','high') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.manage_discount_rules','Gérer les règles de remise','Administrer les plafonds, combinaisons et périodes.','high') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.request_discount_exception','Demander une exception de remise','Soumettre une exception justifiée et documentée.','high') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.approve_discount_exception','Décider une exception de remise','Approuver ou rejeter séparément une exception.','critical') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.view_costs','Consulter les coûts','Voir les coûts confidentiels et leur niveau de confiance.','high') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.view_margins','Consulter les marges','Voir les marges et seuils internes.','high') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.create_offers','Créer des offres','Assembler une offre depuis une source technique approuvée.','standard') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.review_offers','Réviser les offres','Effectuer la validation commerciale formelle.','high') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.approve_offers','Approuver les offres','Prendre la décision commerciale engageante.','critical') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.create_bundles','Créer des bundles','Composer des packages compatibles.','standard') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.approve_bundles','Approuver les bundles','Valider la compatibilité et la structure économique.','critical') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.create_sellables','Créer des références commercialisables','Transformer une offre approuvée en produit service.','high') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.publish_sellables','Publier les références','Publier, reprendre ou superséder une version.','critical') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.suspend_sellables','Suspendre les références','Suspendre une référence sans détruire son historique.','critical') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.retire_sellables','Retirer les références','Retirer et archiver une référence.','critical') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.generate_commercial_documents','Générer les documents commerciaux','Produire des snapshots A4 versionnés.','standard') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.audit_commercial','Auditer l’univers commercial','Consulter décisions, calculs, versions et événements.','high') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;
INSERT INTO public.hsd_permissions(code,name_fr,description_fr,risk_level) VALUES('homeservice_design.admin_commercial','Administrer l’univers commercial','Autorité d’administration commerciale complète.','critical') ON CONFLICT(code) DO UPDATE SET name_fr=excluded.name_fr,description_fr=excluded.description_fr,risk_level=excluded.risk_level;

INSERT INTO public.hsd_package_archetypes(tenant_id,code,name_fr,universe,description_fr,configuration,status)
VALUES
('angelcare-main','single_mission','Mission unique','both','Une mission techniquement validée, configurable selon le segment.','{"minimum_items":1,"maximum_items":1}'::jsonb,'active'),
('angelcare-main','full_day','Journée complète','b2c','Service journée complète avec routines et programme validé.','{"minimum_hours":6,"maximum_hours":12}'::jsonb,'active'),
('angelcare-main','five_days','Pack 5 jours','b2c','Programme multi-jours issu d’un plan UMZ2 approuvé.','{"minimum_days":5,"maximum_days":5}'::jsonb,'active'),
('angelcare-main','twelve_days','Pack 12 jours','b2c','Programme progressif et versionné sur douze jours.','{"minimum_days":12,"maximum_days":12}'::jsonb,'active'),
('angelcare-main','sibling','Pack fratrie','b2c','Configuration multi-bénéficiaires avec ratio et surcharge contrôlés.','{"additional_beneficiary_rule":true}'::jsonb,'active'),
('angelcare-main','postpartum','Pack post-partum','b2c','Soutien familial non médical avec options compatibles.','{"medical_actions":"excluded"}'::jsonb,'active'),
('angelcare-main','hotel_kids','Programme Kids Hôtel','b2b','Programme institutionnel avec capacité, supervision et reporting.','{"site_based":true,"supervision_required":true}'::jsonb,'active'),
('angelcare-main','multi_site','Programme multi-sites','b2b','Déploiement multi-sites avec volumes, phases et reporting.','{"multi_site":true,"volume_pricing":true}'::jsonb,'active')
ON CONFLICT(tenant_id,code) DO UPDATE SET name_fr=excluded.name_fr,universe=excluded.universe,description_fr=excluded.description_fr,configuration=excluded.configuration,status=excluded.status;

COMMIT;
