BEGIN;
SET LOCAL lock_timeout = '5min';
SELECT pg_advisory_xact_lock(84762002);
CREATE EXTENSION IF NOT EXISTS pgcrypto;
DO $$ BEGIN IF to_regclass('public.hsd_service_categories') IS NULL THEN RAISE EXCEPTION 'UMZ1 baseline missing: public.hsd_service_categories'; END IF; END $$;
CREATE TABLE IF NOT EXISTS public.hsd_planning_requests (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,code text not null,title text not null,status text not null default 'draft',category_id uuid not null references public.hsd_service_categories(id),service_version_id uuid,universe text not null default 'b2c',mission_format text not null,customer_profile text not null,objectives jsonb not null default '[]',outcomes jsonb not null default '[]',environment jsonb not null default '{}',constraints jsonb not null default '{}',requested_scenario_count int not null default 1 check(requested_scenario_count between 1 and 10),created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,code));
ALTER TABLE public.hsd_planning_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_planning_requests_tenant_select ON public.hsd_planning_requests;
CREATE POLICY hsd_planning_requests_tenant_select ON public.hsd_planning_requests FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_planning_request_beneficiaries (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,request_id uuid not null references public.hsd_planning_requests(id) on delete cascade,display_name text not null,age_years numeric(4,1),age_band text,profile jsonb not null default '{}',sensitive_profile jsonb not null default '{}',created_at timestamptz not null default now());
ALTER TABLE public.hsd_planning_request_beneficiaries ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_planning_request_beneficiaries_tenant_select ON public.hsd_planning_request_beneficiaries;
CREATE POLICY hsd_planning_request_beneficiaries_tenant_select ON public.hsd_planning_request_beneficiaries FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_planning_request_objectives (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,request_id uuid not null references public.hsd_planning_requests(id) on delete cascade,objective_code text not null,priority int not null default 1,desired_outcome text,created_at timestamptz not null default now());
ALTER TABLE public.hsd_planning_request_objectives ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_planning_request_objectives_tenant_select ON public.hsd_planning_request_objectives;
CREATE POLICY hsd_planning_request_objectives_tenant_select ON public.hsd_planning_request_objectives FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_planning_request_dates (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,request_id uuid not null references public.hsd_planning_requests(id) on delete cascade,service_date date not null,start_time time not null,end_time time not null,declared_minutes int,gross_minutes int not null default 0,handover_minutes int not null default 20,care_routine_minutes int not null default 0,report_minutes int not null default 15,travel_minutes int not null default 0,usable_minutes int not null default 0,status text not null default 'draft',messages jsonb not null default '[]',unique(request_id,service_date));
ALTER TABLE public.hsd_planning_request_dates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_planning_request_dates_tenant_select ON public.hsd_planning_request_dates;
CREATE POLICY hsd_planning_request_dates_tenant_select ON public.hsd_planning_request_dates FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_planning_request_constraints (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,request_id uuid not null references public.hsd_planning_requests(id) on delete cascade,constraint_code text not null,constraint_type text not null,value_json jsonb not null,mandatory boolean not null default true,created_at timestamptz not null default now());
ALTER TABLE public.hsd_planning_request_constraints ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_planning_request_constraints_tenant_select ON public.hsd_planning_request_constraints;
CREATE POLICY hsd_planning_request_constraints_tenant_select ON public.hsd_planning_request_constraints FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_planning_request_environment (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,request_id uuid not null references public.hsd_planning_requests(id) on delete cascade,environment_code text not null,value_json jsonb not null,created_at timestamptz not null default now());
ALTER TABLE public.hsd_planning_request_environment ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_planning_request_environment_tenant_select ON public.hsd_planning_request_environment;
CREATE POLICY hsd_planning_request_environment_tenant_select ON public.hsd_planning_request_environment FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_planning_request_resources (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,request_id uuid not null references public.hsd_planning_requests(id) on delete cascade,resource_code text not null,provided_by text not null,quantity numeric not null default 1,status text not null default 'required');
ALTER TABLE public.hsd_planning_request_resources ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_planning_request_resources_tenant_select ON public.hsd_planning_request_resources;
CREATE POLICY hsd_planning_request_resources_tenant_select ON public.hsd_planning_request_resources FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_feasibility_runs (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,request_id uuid not null references public.hsd_planning_requests(id) on delete cascade,status text not null,rule_snapshot jsonb not null default '{}',started_at timestamptz not null default now(),completed_at timestamptz);
ALTER TABLE public.hsd_feasibility_runs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_feasibility_runs_tenant_select ON public.hsd_feasibility_runs;
CREATE POLICY hsd_feasibility_runs_tenant_select ON public.hsd_feasibility_runs FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_feasibility_findings (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,run_id uuid not null references public.hsd_feasibility_runs(id) on delete cascade,code text not null,severity text not null,title text not null,detail text not null,recovery text,status text not null default 'open');
ALTER TABLE public.hsd_feasibility_findings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_feasibility_findings_tenant_select ON public.hsd_feasibility_findings;
CREATE POLICY hsd_feasibility_findings_tenant_select ON public.hsd_feasibility_findings FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_time_envelopes (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,request_date_id uuid not null references public.hsd_planning_request_dates(id) on delete cascade,gross_minutes int not null,mandatory_minutes int not null,usable_minutes int not null,status text not null,messages jsonb not null default '[]',calculated_at timestamptz not null default now());
ALTER TABLE public.hsd_time_envelopes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_time_envelopes_tenant_select ON public.hsd_time_envelopes;
CREATE POLICY hsd_time_envelopes_tenant_select ON public.hsd_time_envelopes FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_time_envelope_requirements (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,envelope_id uuid not null references public.hsd_time_envelopes(id) on delete cascade,requirement_code text not null,minutes int not null,source_rule_id uuid,mandatory boolean not null default true);
ALTER TABLE public.hsd_time_envelope_requirements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_time_envelope_requirements_tenant_select ON public.hsd_time_envelope_requirements;
CREATE POLICY hsd_time_envelope_requirements_tenant_select ON public.hsd_time_envelope_requirements FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_generation_runs (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,request_id uuid not null references public.hsd_planning_requests(id),status text not null,provider_route text not null default 'openrouter/free' check(provider_route='openrouter/free'),actual_model text,response_id text,started_at timestamptz not null default now(),completed_at timestamptz,duration_ms int,prompt_tokens int not null default 0,completion_tokens int not null default 0,total_tokens int not null default 0,retry_count int not null default 0,failure_message text,created_by uuid,created_at timestamptz not null default now());
ALTER TABLE public.hsd_generation_runs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_generation_runs_tenant_select ON public.hsd_generation_runs;
CREATE POLICY hsd_generation_runs_tenant_select ON public.hsd_generation_runs FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_generation_run_sources (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,run_id uuid not null references public.hsd_generation_runs(id) on delete cascade,source_type text not null,source_id text not null,source_version text,snapshot_hash text);
ALTER TABLE public.hsd_generation_run_sources ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_generation_run_sources_tenant_select ON public.hsd_generation_run_sources;
CREATE POLICY hsd_generation_run_sources_tenant_select ON public.hsd_generation_run_sources FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_generation_run_events (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,run_id uuid not null references public.hsd_generation_runs(id) on delete cascade,event_type text not null,detail jsonb not null default '{}',created_at timestamptz not null default now());
ALTER TABLE public.hsd_generation_run_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_generation_run_events_tenant_select ON public.hsd_generation_run_events;
CREATE POLICY hsd_generation_run_events_tenant_select ON public.hsd_generation_run_events FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_generation_run_usage (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,run_id uuid not null references public.hsd_generation_runs(id) on delete cascade,actual_model text,prompt_tokens int,completion_tokens int,total_tokens int,duration_ms int,created_at timestamptz not null default now());
ALTER TABLE public.hsd_generation_run_usage ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_generation_run_usage_tenant_select ON public.hsd_generation_run_usage;
CREATE POLICY hsd_generation_run_usage_tenant_select ON public.hsd_generation_run_usage FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_generation_run_failures (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,run_id uuid not null references public.hsd_generation_runs(id) on delete cascade,error_code text,error_message text not null,http_status int,retryable boolean not null default false,created_at timestamptz not null default now());
ALTER TABLE public.hsd_generation_run_failures ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_generation_run_failures_tenant_select ON public.hsd_generation_run_failures;
CREATE POLICY hsd_generation_run_failures_tenant_select ON public.hsd_generation_run_failures FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_plan_scenarios (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,request_id uuid not null references public.hsd_planning_requests(id) on delete cascade,generation_run_id uuid references public.hsd_generation_runs(id),code text not null,name text not null,intent text not null,thesis text not null,status text not null default 'generated',customer_fit text,beneficiary_fit text,total_minutes int not null default 0,staffing jsonb not null default '{}',resources jsonb not null default '{}',safety jsonb not null default '{}',deterministic_status text not null default 'conditional',provider_route text not null default 'openrouter/free' check(provider_route='openrouter/free'),actual_model text,created_at timestamptz not null default now(),unique(tenant_id,code));
ALTER TABLE public.hsd_plan_scenarios ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_plan_scenarios_tenant_select ON public.hsd_plan_scenarios;
CREATE POLICY hsd_plan_scenarios_tenant_select ON public.hsd_plan_scenarios FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_plan_scenario_days (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,scenario_id uuid not null references public.hsd_plan_scenarios(id) on delete cascade,service_date date not null,day_number int not null,objective text not null,progression_phase text,start_time time not null,end_time time not null,gross_minutes int not null,usable_minutes int not null,status text not null default 'conditional',messages jsonb not null default '[]',unique(scenario_id,day_number));
ALTER TABLE public.hsd_plan_scenario_days ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_plan_scenario_days_tenant_select ON public.hsd_plan_scenario_days;
CREATE POLICY hsd_plan_scenario_days_tenant_select ON public.hsd_plan_scenario_days FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_plan_scenario_blocks (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,day_id uuid not null references public.hsd_plan_scenario_days(id) on delete cascade,activity_id uuid,activity_code text not null,label text not null,block_kind text not null,start_time time not null,end_time time not null,duration_minutes int not null,objective text,beneficiary_ids jsonb not null default '[]',locked boolean not null default false,status text not null default 'conditional',messages jsonb not null default '[]',sort_order int not null default 0);
ALTER TABLE public.hsd_plan_scenario_blocks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_plan_scenario_blocks_tenant_select ON public.hsd_plan_scenario_blocks;
CREATE POLICY hsd_plan_scenario_blocks_tenant_select ON public.hsd_plan_scenario_blocks FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_plan_block_materials (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,block_id uuid not null references public.hsd_plan_scenario_blocks(id) on delete cascade,material_code text not null,quantity numeric not null default 1,source text,status text not null default 'required');
ALTER TABLE public.hsd_plan_block_materials ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_plan_block_materials_tenant_select ON public.hsd_plan_block_materials;
CREATE POLICY hsd_plan_block_materials_tenant_select ON public.hsd_plan_block_materials FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_plan_block_competencies (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,block_id uuid not null references public.hsd_plan_scenario_blocks(id) on delete cascade,competency_code text not null,required_level text,mandatory boolean not null default true);
ALTER TABLE public.hsd_plan_block_competencies ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_plan_block_competencies_tenant_select ON public.hsd_plan_block_competencies;
CREATE POLICY hsd_plan_block_competencies_tenant_select ON public.hsd_plan_block_competencies FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_plan_block_safeguards (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,block_id uuid not null references public.hsd_plan_scenario_blocks(id) on delete cascade,safeguard_code text not null,control_text text not null,blocking_if_missing boolean not null default true);
ALTER TABLE public.hsd_plan_block_safeguards ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_plan_block_safeguards_tenant_select ON public.hsd_plan_block_safeguards;
CREATE POLICY hsd_plan_block_safeguards_tenant_select ON public.hsd_plan_block_safeguards FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_plan_block_evidence (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,block_id uuid not null references public.hsd_plan_scenario_blocks(id) on delete cascade,evidence_code text not null,evidence_type text not null,mandatory boolean not null default false);
ALTER TABLE public.hsd_plan_block_evidence ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_plan_block_evidence_tenant_select ON public.hsd_plan_block_evidence;
CREATE POLICY hsd_plan_block_evidence_tenant_select ON public.hsd_plan_block_evidence FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_plan_block_checklists (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,block_id uuid not null references public.hsd_plan_scenario_blocks(id) on delete cascade,checklist_code text not null,item_code text,mandatory boolean not null default true);
ALTER TABLE public.hsd_plan_block_checklists ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_plan_block_checklists_tenant_select ON public.hsd_plan_block_checklists;
CREATE POLICY hsd_plan_block_checklists_tenant_select ON public.hsd_plan_block_checklists FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_technical_plans (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,request_id uuid not null references public.hsd_planning_requests(id),selected_scenario_id uuid references public.hsd_plan_scenarios(id),code text not null,status text not null default 'draft',current_version int not null default 1,approved_version_id uuid,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,code));
ALTER TABLE public.hsd_technical_plans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_technical_plans_tenant_select ON public.hsd_technical_plans;
CREATE POLICY hsd_technical_plans_tenant_select ON public.hsd_technical_plans FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_technical_plan_versions (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,plan_id uuid not null references public.hsd_technical_plans(id) on delete restrict,version_number int not null,status text not null,snapshot jsonb not null,source_scenario_id uuid,service_version_id uuid,doctrine_snapshot_hash text,approved_by uuid,approved_at timestamptz,created_at timestamptz not null default now(),unique(plan_id,version_number));
ALTER TABLE public.hsd_technical_plan_versions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_technical_plan_versions_tenant_select ON public.hsd_technical_plan_versions;
CREATE POLICY hsd_technical_plan_versions_tenant_select ON public.hsd_technical_plan_versions FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_technical_plan_days (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,version_id uuid not null references public.hsd_technical_plan_versions(id) on delete cascade,service_date date not null,day_number int not null,objective text,progression_phase text,start_time time,end_time time,gross_minutes int,usable_minutes int,unique(version_id,day_number));
ALTER TABLE public.hsd_technical_plan_days ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_technical_plan_days_tenant_select ON public.hsd_technical_plan_days;
CREATE POLICY hsd_technical_plan_days_tenant_select ON public.hsd_technical_plan_days FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_technical_plan_blocks (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,plan_day_id uuid not null references public.hsd_technical_plan_days(id) on delete cascade,activity_snapshot jsonb not null,start_time time,end_time time,duration_minutes int,locked boolean not null default false,sort_order int not null default 0);
ALTER TABLE public.hsd_technical_plan_blocks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_technical_plan_blocks_tenant_select ON public.hsd_technical_plan_blocks;
CREATE POLICY hsd_technical_plan_blocks_tenant_select ON public.hsd_technical_plan_blocks FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_technical_plan_snapshots (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,version_id uuid not null references public.hsd_technical_plan_versions(id) on delete cascade,snapshot_type text not null,payload jsonb not null,checksum text not null,created_at timestamptz not null default now());
ALTER TABLE public.hsd_technical_plan_snapshots ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_technical_plan_snapshots_tenant_select ON public.hsd_technical_plan_snapshots;
CREATE POLICY hsd_technical_plan_snapshots_tenant_select ON public.hsd_technical_plan_snapshots FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_plan_validation_runs (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,plan_id uuid not null references public.hsd_technical_plans(id),version_id uuid references public.hsd_technical_plan_versions(id),status text not null,started_at timestamptz not null default now(),completed_at timestamptz,reviewed_by uuid);
ALTER TABLE public.hsd_plan_validation_runs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_plan_validation_runs_tenant_select ON public.hsd_plan_validation_runs;
CREATE POLICY hsd_plan_validation_runs_tenant_select ON public.hsd_plan_validation_runs FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_plan_validation_findings (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,validation_run_id uuid references public.hsd_plan_validation_runs(id) on delete cascade,plan_id uuid not null references public.hsd_technical_plans(id),discipline text not null,severity text not null,rule_code text not null,title text not null,detail text not null,consequence text,corrective_action text,owner_id uuid,due_at timestamptz,status text not null default 'open',evidence jsonb not null default '[]',created_at timestamptz not null default now());
ALTER TABLE public.hsd_plan_validation_findings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_plan_validation_findings_tenant_select ON public.hsd_plan_validation_findings;
CREATE POLICY hsd_plan_validation_findings_tenant_select ON public.hsd_plan_validation_findings FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_plan_approval_requests (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,plan_id uuid not null references public.hsd_technical_plans(id),version_id uuid not null references public.hsd_technical_plan_versions(id),status text not null default 'pending',requested_by uuid,assigned_to uuid,requested_at timestamptz not null default now(),decided_at timestamptz);
ALTER TABLE public.hsd_plan_approval_requests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_plan_approval_requests_tenant_select ON public.hsd_plan_approval_requests;
CREATE POLICY hsd_plan_approval_requests_tenant_select ON public.hsd_plan_approval_requests FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_plan_approval_decisions (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,approval_request_id uuid not null references public.hsd_plan_approval_requests(id) on delete restrict,decision text not null,decided_by uuid not null,reason text not null,conditions jsonb not null default '[]',created_at timestamptz not null default now());
ALTER TABLE public.hsd_plan_approval_decisions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_plan_approval_decisions_tenant_select ON public.hsd_plan_approval_decisions;
CREATE POLICY hsd_plan_approval_decisions_tenant_select ON public.hsd_plan_approval_decisions FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_progression_templates (id uuid primary key default gen_random_uuid(),tenant_id uuid,code text not null,name text not null,description text,category_id uuid references public.hsd_service_categories(id),status text not null default 'active',version int not null default 1,created_at timestamptz not null default now(),unique(tenant_id,code,version));
ALTER TABLE public.hsd_progression_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_progression_templates_tenant_select ON public.hsd_progression_templates;
CREATE POLICY hsd_progression_templates_tenant_select ON public.hsd_progression_templates FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_progression_template_phases (id uuid primary key default gen_random_uuid(),tenant_id uuid,template_id uuid not null references public.hsd_progression_templates(id) on delete cascade,phase_number int not null,name text not null,objective text not null,min_day int,max_day int,configuration jsonb not null default '{}',unique(template_id,phase_number));
ALTER TABLE public.hsd_progression_template_phases ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_progression_template_phases_tenant_select ON public.hsd_progression_template_phases;
CREATE POLICY hsd_progression_template_phases_tenant_select ON public.hsd_progression_template_phases FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_planning_templates (id uuid primary key default gen_random_uuid(),tenant_id uuid,code text not null,name text not null,category_id uuid references public.hsd_service_categories(id),duration_minutes int,configuration jsonb not null default '{}',status text not null default 'active',version int not null default 1,created_at timestamptz not null default now(),unique(tenant_id,code,version));
ALTER TABLE public.hsd_planning_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_planning_templates_tenant_select ON public.hsd_planning_templates;
CREATE POLICY hsd_planning_templates_tenant_select ON public.hsd_planning_templates FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_planning_template_blocks (id uuid primary key default gen_random_uuid(),tenant_id uuid,template_id uuid not null references public.hsd_planning_templates(id) on delete cascade,activity_code text not null,start_offset_minutes int not null,duration_minutes int not null,mandatory boolean not null default false,sort_order int not null default 0);
ALTER TABLE public.hsd_planning_template_blocks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_planning_template_blocks_tenant_select ON public.hsd_planning_template_blocks;
CREATE POLICY hsd_planning_template_blocks_tenant_select ON public.hsd_planning_template_blocks FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_plan_documents (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,plan_id uuid not null references public.hsd_technical_plans(id),document_type text not null,status text not null default 'draft',current_version int not null default 1,created_by uuid,created_at timestamptz not null default now());
ALTER TABLE public.hsd_plan_documents ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_plan_documents_tenant_select ON public.hsd_plan_documents;
CREATE POLICY hsd_plan_documents_tenant_select ON public.hsd_plan_documents FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_plan_document_versions (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,document_id uuid not null references public.hsd_plan_documents(id) on delete cascade,version_number int not null,template_version text not null,payload jsonb not null,file_path text,checksum text,created_at timestamptz not null default now(),unique(document_id,version_number));
ALTER TABLE public.hsd_plan_document_versions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_plan_document_versions_tenant_select ON public.hsd_plan_document_versions;
CREATE POLICY hsd_plan_document_versions_tenant_select ON public.hsd_plan_document_versions FOR SELECT USING (true);
CREATE TABLE IF NOT EXISTS public.hsd_plan_document_exports (id uuid primary key default gen_random_uuid(),tenant_id uuid not null,document_version_id uuid not null references public.hsd_plan_document_versions(id),format text not null,status text not null,requested_by uuid,requested_at timestamptz not null default now(),completed_at timestamptz,failure_message text);
ALTER TABLE public.hsd_plan_document_exports ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hsd_plan_document_exports_tenant_select ON public.hsd_plan_document_exports;
CREATE POLICY hsd_plan_document_exports_tenant_select ON public.hsd_plan_document_exports FOR SELECT USING (true);

CREATE INDEX IF NOT EXISTS idx_hsd_planning_requests_status ON public.hsd_planning_requests(tenant_id,status,updated_at desc);
CREATE INDEX IF NOT EXISTS idx_hsd_plan_scenarios_request ON public.hsd_plan_scenarios(request_id,created_at desc);
CREATE INDEX IF NOT EXISTS idx_hsd_plan_blocks_day ON public.hsd_plan_scenario_blocks(day_id,start_time);
CREATE INDEX IF NOT EXISTS idx_hsd_validation_findings_open ON public.hsd_plan_validation_findings(tenant_id,status,severity);
ALTER TABLE public.hsd_generation_runs ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS idx_hsd_generation_runs_status ON public.hsd_generation_runs(tenant_id,status,created_at desc);
CREATE OR REPLACE VIEW public.hsd_planning_command_v AS SELECT r.tenant_id,count(*) total_requests,count(*) filter(where r.status='ready') ready_requests,count(*) filter(where r.status='approval_requested') approval_queue,count(*) filter(where r.status='approved') approved_plans FROM public.hsd_planning_requests r GROUP BY r.tenant_id;
CREATE OR REPLACE VIEW public.hsd_planning_integrity_v AS SELECT r.id request_id,r.code,r.status,count(d.id) date_count,count(b.id) beneficiary_count,coalesce(bool_and(d.status<>'blocked'),false) time_ready FROM public.hsd_planning_requests r left join public.hsd_planning_request_dates d on d.request_id=r.id left join public.hsd_planning_request_beneficiaries b on b.request_id=r.id group by r.id;
CREATE OR REPLACE FUNCTION public.hsd_prevent_approved_plan_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.status='approved' THEN RAISE EXCEPTION 'Approved HomeService technical plans are immutable; create a revision.'; END IF; RETURN NEW; END $$;
DROP TRIGGER IF EXISTS trg_hsd_technical_plans_immutable ON public.hsd_technical_plans;
CREATE TRIGGER trg_hsd_technical_plans_immutable BEFORE UPDATE OR DELETE ON public.hsd_technical_plans FOR EACH ROW EXECUTE FUNCTION public.hsd_prevent_approved_plan_mutation();
INSERT INTO public.hsd_progression_templates(tenant_id,code,name,description,status,version) VALUES
(NULL,'FAMILIARISATION_12D','Progression 12 jours · familiarisation vers autonomie','Familiarisation, routines, apprentissage, variation, autonomie et clôture.','active',1),
(NULL,'RECURRING_IDENTICAL','Couverture récurrente identique','Structure fixe avec contrôles de continuité.','active',1),
(NULL,'LANGUAGE_ENRICHMENT','Enrichissement linguistique','Progression vocabulaire, compréhension et expression.','active',1),
(NULL,'SENSORY_GENTLE','Progression sensorielle douce','Prévisibilité, régulation et adaptation graduelle.','active',1) ON CONFLICT DO NOTHING;
DO $$ DECLARE t uuid; BEGIN SELECT id INTO t FROM public.hsd_progression_templates WHERE code='FAMILIARISATION_12D' AND tenant_id IS NULL LIMIT 1; IF t IS NOT NULL THEN INSERT INTO public.hsd_progression_template_phases(tenant_id,template_id,phase_number,name,objective,min_day,max_day,configuration) VALUES (NULL,t,1,'Familiarisation','Sécurité, relation et ligne de base',1,2,'{}'),(NULL,t,2,'Installation','Routines et participation guidée',3,5,'{}'),(NULL,t,3,'Confiance','Variation, communication et autonomie',6,9,'{}'),(NULL,t,4,'Maîtrise','Application, consolidation et continuation',10,12,'{}') ON CONFLICT DO NOTHING; END IF; END $$;
COMMIT;
