begin;
create table if not exists public.angelcare_marketplace_qa_test_suites(id uuid primary key default gen_random_uuid(),suite_key text unique not null,name_fr text not null,domain text not null,test_family text not null,criticality text not null,owner_role text not null,status text not null default 'active',case_count int not null default 0,last_run_at timestamptz,last_pass_rate numeric(6,2),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare_marketplace_qa_test_cases(id uuid primary key default gen_random_uuid(),suite_id uuid not null references public.angelcare_marketplace_qa_test_suites(id) on delete cascade,test_case_key text unique not null,title_fr text not null,domain text not null,criticality text not null,preconditions jsonb not null default '{}',steps jsonb not null default '[]',expected_result text not null,automation_reference text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare_marketplace_qa_test_runs(id uuid primary key default gen_random_uuid(),public_reference text unique not null default ('QARUN-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,9))),suite_id uuid references public.angelcare_marketplace_qa_test_suites(id),run_type text not null,environment text not null,source_snapshot text,status text not null default 'queued',total_tests int not null default 0,passed_tests int not null default 0,failed_tests int not null default 0,blocked_tests int not null default 0,started_at timestamptz not null default now(),completed_at timestamptz,executed_by uuid,territory_id uuid,tenant_id uuid,created_at timestamptz not null default now());
create table if not exists public.angelcare_marketplace_qa_test_results(id uuid primary key default gen_random_uuid(),run_id uuid not null references public.angelcare_marketplace_qa_test_runs(id) on delete cascade,test_case_key text not null,domain text not null,criticality text not null,status text not null check(status in('passed','failed','blocked','skipped','not_run')),expected_result text not null,observed_result text,evidence jsonb not null default '{}',duration_ms int,error_reference text,created_at timestamptz not null default now());
create table if not exists public.angelcare_marketplace_qa_defects(id uuid primary key default gen_random_uuid(),public_reference text unique not null default ('DEF-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,11))),title text not null,domain text not null,severity text not null,priority text not null,status text not null default 'reported' check(status in('reported','triaged','confirmed','assigned','in_progress','ready_for_verification','verified','rejected','reopened','deferred_with_approval','closed')),source_run_id uuid references public.angelcare_marketplace_qa_test_runs(id),source_result_id uuid references public.angelcare_marketplace_qa_test_results(id),route text,owner_id uuid,reviewer_id uuid,block_release boolean not null default false,open_flag boolean generated always as (status not in('verified','rejected','closed')) stored,critical_flag boolean generated always as (severity='critical' and status not in('verified','rejected','closed')) stored,description text not null,reproduction_steps text[] not null default '{}',evidence jsonb not null default '{}',due_at timestamptz,verified_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare_marketplace_qa_release_candidates(id uuid primary key default gen_random_uuid(),public_reference text unique not null default ('RC-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,12))),version_label text not null,source_snapshot text not null,status text not null default 'development' check(status in('development','integration_review','system_validation','release_candidate','launch_review','approved_for_controlled_release','controlled_release','monitoring','general_release','paused','rolled_back','retired')),territory_id uuid,tenant_id uuid,target_environment text not null,planned_at timestamptz,approved_at timestamptz,launched_at timestamptz,paused_at timestamptz,rolled_back_at timestamptz,rollback_reason text,owner_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare_marketplace_launch_gates(id uuid primary key default gen_random_uuid(),gate_key text unique not null,name_fr text not null,gate_family text not null,description_fr text not null,requirement_level text not null,status text not null default 'not_started' check(status in('not_started','in_progress','evidence_required','failed','blocked','conditionally_passed','passed','expired','waiver_requested','waiver_approved','not_applicable')),score numeric(6,2) not null default 0,owner_role text not null,reviewer_role text not null,evidence_required boolean not null default true,evidence_count int not null default 0,blocker_reason text,warning_reason text,expires_at timestamptz,last_validated_at timestamptz,territory_id uuid,tenant_id uuid,sort_order int not null default 0,updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare_marketplace_launch_evidence(id uuid primary key default gen_random_uuid(),gate_id uuid not null references public.angelcare_marketplace_launch_gates(id) on delete cascade,evidence_type text not null,source_object_type text not null,source_object_id uuid not null,status text not null default 'submitted',checksum text,submitted_by uuid not null,reviewed_by uuid,reviewed_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.angelcare_marketplace_launch_approvals(id uuid primary key default gen_random_uuid(),release_candidate_id uuid not null references public.angelcare_marketplace_qa_release_candidates(id),approval_type text not null,decision text not null,approver_id uuid not null,role_key text not null,reason text,residual_risks text[] not null default '{}',conditions text[] not null default '{}',approved_at timestamptz not null default now(),expires_at timestamptz);
create table if not exists public.angelcare_marketplace_launch_runbooks(id uuid primary key default gen_random_uuid(),release_candidate_id uuid not null references public.angelcare_marketplace_qa_release_candidates(id),version int not null,status text not null default 'draft',pre_launch_freeze jsonb not null default '{}',migration_sequence text[] not null default '{}',environment_checks text[] not null default '{}',secret_checks text[] not null default '{}',monitoring_checks text[] not null default '{}',backup_checks text[] not null default '{}',rollback_points text[] not null default '{}',smoke_routes text[] not null default '{}',business_validations text[] not null default '{}',security_validations text[] not null default '{}',support_escalation jsonb not null default '{}',go_no_go_authority text[] not null default '{}',approved_by uuid,approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(release_candidate_id,version));
create table if not exists public.angelcare_marketplace_launch_events(id uuid primary key default gen_random_uuid(),release_candidate_id uuid references public.angelcare_marketplace_qa_release_candidates(id),event_type text not null,severity text not null,status text not null,description text not null,actor_id uuid,occurred_at timestamptz not null default now(),evidence jsonb not null default '{}');
create table if not exists public.angelcare_marketplace_post_launch_reviews(id uuid primary key default gen_random_uuid(),release_candidate_id uuid not null references public.angelcare_marketplace_qa_release_candidates(id),monitoring_window_start timestamptz not null,monitoring_window_end timestamptz not null,status text not null default 'planned',operational_owner_id uuid,technical_owner_id uuid,finance_owner_id uuid,support_owner_id uuid,security_owner_id uuid,trust_owner_id uuid,rollback_thresholds jsonb not null default '{}',incidents_count int not null default 0,critical_incidents_count int not null default 0,stabilization_criteria text[] not null default '{}',exit_decision text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
insert into public.angelcare_marketplace_launch_gates(gate_key,name_fr,gate_family,description_fr,requirement_level,status,score,owner_role,reviewer_role,evidence_required,sort_order) values
('product_scope.complete','Product scope complete','Product','All contracted domains and workflows are present.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,10),
('critical_workflows.operational','Critical workflows operational','Product','Critical journeys are persistent and connected.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,20),
('database_migrations.accepted','Database migrations accepted','Data','All additive migrations are applied and verified.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,30),
('data_integrity.accepted','Data integrity accepted','Data','Integrity, constraints and source lineage are accepted.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,40),
('territory_configuration.accepted','Territory configuration accepted','Territory','Territory gates and ownership pass.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,50),
('localization.accepted','Localization accepted','Localization','French source and required locales are current.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,60),
('arabic_rtl.accepted','Arabic RTL accepted','Localization','Structural RTL passes on critical routes.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,70),
('public_content.accepted','Public content accepted','Content','Public routes, claims and SEO are approved.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,80),
('trust_legal.accepted','Trust and legal content accepted','Trust','Evidence-backed trust and sensitive content approval pass.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,90),
('security_review.accepted','Security review accepted','Security','Access, secrets, sessions and audit are accepted.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,100),
('tenant_isolation.accepted','Tenant isolation accepted','Security','Allowed and denied tenant tests pass.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,110),
('territory_isolation.accepted','Territory isolation accepted','Security','Allowed and denied territory tests pass.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,120),
('rbac.accepted','RBAC accepted','Security','Server-side permissions and separation of duties pass.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,130),
('backup.accepted','Backup accepted','Backup & Recovery','Current encrypted backup evidence is approved.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,140),
('recovery_test.accepted','Recovery test accepted','Backup & Recovery','Restore evidence, RPO and RTO are validated.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,150),
('analytics.accepted','Analytics accepted','Analytics','Definitions, sources and data quality pass.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,160),
('monitoring.accepted','Monitoring accepted','Observability','Monitoring and incident ownership are active.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,170),
('performance.accepted','Performance accepted','Performance','Critical performance budgets pass.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,180),
('accessibility.accepted','Accessibility accepted','Accessibility','Critical routes pass accessibility acceptance.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,190),
('critical_defects.closed','Critical defects closed','QA','No unresolved critical release-blocking defect.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,200),
('operator_training.completed','Operator training completed','Operations','Operator handover and training are evidenced.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,210),
('support_path.active','Support path active','Support','Support and escalation routes are active.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,220),
('rollback_plan.accepted','Rollback plan accepted','Release','Decision points and recovery instructions are approved.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,230),
('executive_approval.recorded','Executive approval recorded','Executive','Authorized go/no-go sign-off is recorded.','mandatory_blocking','not_started',0,'domain_owner','executive_reviewer',true,240)
on conflict(gate_key) do update set name_fr=excluded.name_fr,gate_family=excluded.gate_family,description_fr=excluded.description_fr,requirement_level=excluded.requirement_level,sort_order=excluded.sort_order;
insert into public.angelcare_marketplace_qa_test_suites(suite_key,name_fr,domain,test_family,criticality,owner_role,status) values ('contractual.regression','Cumulative MZ01–MZ20 contractual regression','regression','static_contract','critical','release_manager','active'),('api.contracts','API contracts and business errors','api','api_contract','critical','engineering_lead','active'),('database.integrity','Database integrity and migration safety','database','database','critical','data_owner','active'),('security.isolation','Territory and tenant isolation','security','security','critical','security_reviewer','active'),('localization.rtl','French, EN, AR and structural RTL','localization','localization','high','localization_manager','active'),('accessibility.critical','Critical route accessibility','accessibility','accessibility','high','product_quality','active'),('runtime.smoke','Critical runtime smoke routes','runtime','runtime','critical','release_manager','active'),('backup.recovery','Backup and recovery evidence','recovery','recovery','critical','security_reviewer','active') on conflict(suite_key) do update set name_fr=excluded.name_fr,criticality=excluded.criticality,status='active';
create or replace function public.angelcare_marketplace_transition_qa_defect(p_defect_id uuid,p_next_status text,p_reason text,p_actor_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare r public.angelcare_marketplace_qa_defects;begin if p_next_status='closed' and not exists(select 1 from public.angelcare_marketplace_qa_defects where id=p_defect_id and status='verified') then raise exception 'Defect must be verified before closure';end if;update public.angelcare_marketplace_qa_defects set status=p_next_status,reviewer_id=case when p_next_status in('verified','closed') then p_actor_id else reviewer_id end,verified_at=case when p_next_status='verified' then now() else verified_at end,updated_at=now() where id=p_defect_id returning * into r;if r.id is null then raise exception 'Defect introuvable';end if;return to_jsonb(r);end$$;
create or replace function public.angelcare_marketplace_update_launch_gate(p_gate_id uuid,p_status text,p_evidence jsonb,p_reason text,p_actor_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare r public.angelcare_marketplace_launch_gates;begin if p_status='passed' and exists(select 1 from public.angelcare_marketplace_launch_gates where id=p_gate_id and evidence_required and not exists(select 1 from public.angelcare_marketplace_launch_evidence e where e.gate_id=p_gate_id and e.status='approved')) then raise exception 'Approved evidence required';end if;update public.angelcare_marketplace_launch_gates set status=p_status,score=case when p_status='passed' then 100 when p_status='conditionally_passed' then 80 else score end,blocker_reason=case when p_status in('failed','blocked') then p_reason else null end,evidence_count=(select count(*) from public.angelcare_marketplace_launch_evidence e where e.gate_id=p_gate_id and e.status='approved'),last_validated_at=now(),updated_by=p_actor_id,updated_at=now() where id=p_gate_id returning * into r;if r.id is null then raise exception 'Launch gate introuvable';end if;return to_jsonb(r);end$$;
create or replace function public.angelcare_marketplace_transition_release_candidate(p_release_id uuid,p_next_status text,p_reason text,p_actor_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare r public.angelcare_marketplace_qa_release_candidates;blocking int;begin if p_next_status='approved_for_controlled_release' then select count(*) into blocking from public.angelcare_marketplace_launch_gates where requirement_level='mandatory_blocking' and status<>'passed';blocking:=blocking+(select count(*) from public.angelcare_marketplace_qa_defects where critical_flag);if blocking>0 then raise exception 'Release blocked by % mandatory gates or critical defects',blocking;end if;if not exists(select 1 from public.angelcare_marketplace_launch_runbooks where release_candidate_id=p_release_id and status='approved') then raise exception 'Approved launch runbook required';end if;end if;update public.angelcare_marketplace_qa_release_candidates set status=p_next_status,approved_at=case when p_next_status='approved_for_controlled_release' then now() else approved_at end,launched_at=case when p_next_status='controlled_release' then now() else launched_at end,paused_at=case when p_next_status='paused' then now() else paused_at end,rolled_back_at=case when p_next_status='rolled_back' then now() else rolled_back_at end,rollback_reason=case when p_next_status='rolled_back' then p_reason else rollback_reason end,updated_at=now() where id=p_release_id returning * into r;if r.id is null then raise exception 'Release candidate introuvable';end if;insert into public.angelcare_marketplace_launch_events(release_candidate_id,event_type,severity,status,description,actor_id) values(p_release_id,'release.'||p_next_status,case when p_next_status in('rolled_back','paused') then 'critical' else 'info' end,'recorded',coalesce(p_reason,p_next_status),p_actor_id);return to_jsonb(r);end$$;
insert into public.angelcare_marketplace_permissions(permission_key,name,category,sensitive) values ('marketplace.qa.view','Consulter QA Authority','QA',false),('marketplace.qa.manage','Gérer QA','QA',true),('marketplace.qa.execute','Exécuter QA','QA',true),('marketplace.qa.defects.manage','Gérer les defects','QA',true),('marketplace.qa.release_review','Réviser une release','QA',true),('marketplace.launch.view','Consulter Launch Authority','Launch',false),('marketplace.launch.gates.manage','Gérer les gates','Launch',true),('marketplace.launch.gates.review','Réviser les gates','Launch',true),('marketplace.launch.waivers.approve','Approuver les waivers','Launch',true),('marketplace.launch.release.approve','Approuver une release','Launch',true),('marketplace.launch.pause','Mettre le launch en pause','Launch',true),('marketplace.launch.rollback_authorize','Autoriser rollback','Launch',true),('marketplace.launch.post_launch.manage','Gérer le post-launch','Launch',true) on conflict(permission_key) do update set name=excluded.name,category=excluded.category,sensitive=excluded.sensitive;
insert into public.angelcare_marketplace_role_permissions(role_key,permission_key) select r.role_key,p.permission_key from public.angelcare_marketplace_roles r cross join public.angelcare_marketplace_permissions p where r.role_key in('marketplace_super_admin','marketplace_executive') and (p.permission_key like 'marketplace.qa.%' or p.permission_key like 'marketplace.launch.%') on conflict do nothing;
insert into public.angelcare_marketplace_modules(module_key,name,description,route_prefix,module_type,audience,status,enabled,required_permissions,required_dependencies,territory_aware,tenant_aware,locale_aware,health_status,owner_role,introduced_by_mega_zip) values('qa-final-launch-authority','QA & Final Launch Authority','Test authority, defects, gates, runbook and post-launch.','/angelcare-marketplace/admin/launch','final_authority',array['admin','executive']::text[],'enabled',true,array['marketplace.launch.view']::text[],array['analytics-security-assurance','trust-quality-authority','finance-authority']::text[],true,true,true,'healthy','release_authority',20) on conflict(module_key) do update set status='enabled',enabled=true,route_prefix=excluded.route_prefix,required_permissions=excluded.required_permissions,updated_at=now();
insert into public.angelcare_marketplace_feature_flags(flag_key,name,description,enabled,status,reason) values('marketplace.qa-launch.enabled','QA & Final Launch Authority','Final QA and release gates.',true,'active','Ultra Delivery 5/5 · Original MZ20') on conflict(flag_key) do update set enabled=true,status='active',reason=excluded.reason,updated_at=now();
alter table public.angelcare_marketplace_qa_test_suites enable row level security;
alter table public.angelcare_marketplace_qa_test_cases enable row level security;
alter table public.angelcare_marketplace_qa_test_runs enable row level security;
alter table public.angelcare_marketplace_qa_test_results enable row level security;
alter table public.angelcare_marketplace_qa_defects enable row level security;
alter table public.angelcare_marketplace_qa_release_candidates enable row level security;
alter table public.angelcare_marketplace_launch_gates enable row level security;
alter table public.angelcare_marketplace_launch_evidence enable row level security;
alter table public.angelcare_marketplace_launch_approvals enable row level security;
alter table public.angelcare_marketplace_launch_runbooks enable row level security;
alter table public.angelcare_marketplace_launch_events enable row level security;
alter table public.angelcare_marketplace_post_launch_reviews enable row level security;
revoke all on table public.angelcare_marketplace_qa_test_suites,public.angelcare_marketplace_qa_test_cases,public.angelcare_marketplace_qa_test_runs,public.angelcare_marketplace_qa_test_results,public.angelcare_marketplace_qa_defects,public.angelcare_marketplace_qa_release_candidates,public.angelcare_marketplace_launch_gates,public.angelcare_marketplace_launch_evidence,public.angelcare_marketplace_launch_approvals,public.angelcare_marketplace_launch_runbooks,public.angelcare_marketplace_launch_events,public.angelcare_marketplace_post_launch_reviews from anon,authenticated;
grant all on table public.angelcare_marketplace_qa_test_suites,public.angelcare_marketplace_qa_test_cases,public.angelcare_marketplace_qa_test_runs,public.angelcare_marketplace_qa_test_results,public.angelcare_marketplace_qa_defects,public.angelcare_marketplace_qa_release_candidates,public.angelcare_marketplace_launch_gates,public.angelcare_marketplace_launch_evidence,public.angelcare_marketplace_launch_approvals,public.angelcare_marketplace_launch_runbooks,public.angelcare_marketplace_launch_events,public.angelcare_marketplace_post_launch_reviews to service_role;
grant execute on function public.angelcare_marketplace_transition_qa_defect(uuid,text,text,uuid),public.angelcare_marketplace_update_launch_gate(uuid,text,jsonb,text,uuid),public.angelcare_marketplace_transition_release_candidate(uuid,text,text,uuid) to service_role;
create index if not exists ac_qa_defect_release_idx on public.angelcare_marketplace_qa_defects(block_release,critical_flag,status,created_at);create index if not exists ac_launch_gate_status_idx on public.angelcare_marketplace_launch_gates(requirement_level,status,sort_order);
commit;
