begin;
create extension if not exists pgcrypto;
create table if not exists public.angelcare360_access_invitations(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,person_id uuid,email text not null,role_id uuid references public.angelcare360_roles(id) on delete set null,scope_json jsonb not null default '{}',state text not null default 'prepared',starts_at timestamptz,expires_at timestamptz,sent_at timestamptz not null default now(),activated_at timestamptz,cancelled_at timestamptz,invited_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare360_access_role_versions(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,role_id uuid not null references public.angelcare360_roles(id) on delete cascade,version_number integer not null,label text not null,description text,permission_keys jsonb not null default '[]',scope_policy jsonb not null default '{}',state text not null default 'draft',change_reason text,requested_at timestamptz,published_by uuid references public.app_users(id) on delete set null,published_at timestamptz,replaced_at timestamptz,created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(role_id,version_number));
create table if not exists public.angelcare360_access_requests(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,requester_user_id uuid references public.app_users(id) on delete set null,requester_label text,requested_role_id uuid references public.angelcare360_roles(id) on delete set null,requested_role_label text,requested_permission_keys jsonb not null default '[]',scope_label text not null default 'Établissement',reason text not null,starts_at timestamptz,ends_at timestamptz,sensitive_impact text,state text not null default 'pending',risk_score integer not null default 0,reviewer_id uuid references public.app_users(id) on delete set null,reviewer_label text,decision_reason text,reviewed_by uuid references public.app_users(id) on delete set null,reviewed_at timestamptz,created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare360_temporary_access_grants(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,app_user_id uuid not null references public.app_users(id) on delete cascade,role_id uuid references public.angelcare360_roles(id) on delete set null,permission_keys jsonb not null default '[]',scope_json jsonb not null default '{}',reason text not null,starts_at timestamptz not null,ends_at timestamptz not null,state text not null default 'pending',approved_by uuid references public.app_users(id) on delete set null,approved_at timestamptz,ended_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ends_at>starts_at));
create table if not exists public.angelcare360_access_delegations(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,delegator_user_id uuid not null references public.app_users(id) on delete restrict,delegate_user_id uuid not null references public.app_users(id) on delete restrict,role_id uuid references public.angelcare360_roles(id) on delete set null,operation_keys jsonb not null default '[]',scope_label text not null default 'Établissement',reason text not null,starts_at timestamptz not null,ends_at timestamptz,state text not null default 'draft',approval_label text,requested_at timestamptz,approved_by uuid references public.app_users(id) on delete set null,approved_at timestamptz,activated_at timestamptz,ended_at timestamptz,usage_count integer not null default 0,created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ends_at is null or ends_at>starts_at));
create table if not exists public.angelcare360_sensitive_access_grants(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,app_user_id uuid not null references public.app_users(id) on delete cascade,category_key text not null,category_label text not null,purpose text not null,scope_label text not null,starts_at timestamptz,ends_at timestamptz,state text not null default 'pending',approval_label text,requested_by uuid references public.app_users(id) on delete set null,approved_by uuid references public.app_users(id) on delete set null,approved_at timestamptz,last_reviewed_at timestamptz,next_review_at timestamptz,reviewed_by uuid references public.app_users(id) on delete set null,revoked_by uuid references public.app_users(id) on delete set null,revoked_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare360_access_review_campaigns(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,name text not null,scope_label text not null,scope_json jsonb not null default '{}',reviewer_id uuid references public.app_users(id) on delete set null,reviewer_label text,due_at timestamptz,state text not null default 'draft',user_count integer not null default 0,completed_by uuid references public.app_users(id) on delete set null,completed_at timestamptz,created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare360_access_review_decisions(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,review_id uuid not null references public.angelcare360_access_review_campaigns(id) on delete cascade,app_user_id uuid not null references public.app_users(id) on delete cascade,decision text not null,reason text,decided_by uuid references public.app_users(id) on delete set null,decided_at timestamptz not null default now(),result_json jsonb not null default '{}',unique(review_id,app_user_id));
create table if not exists public.angelcare360_emergency_access_events(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,app_user_id uuid not null references public.app_users(id) on delete cascade,operation_keys jsonb not null default '[]',scope_json jsonb not null default '{}',reason text not null,starts_at timestamptz not null,ends_at timestamptz not null,state text not null default 'pending',requested_by uuid references public.app_users(id) on delete set null,approved_by uuid references public.app_users(id) on delete set null,approved_at timestamptz,activated_at timestamptz,revoked_by uuid references public.app_users(id) on delete set null,revoked_at timestamptz,reviewed_by uuid references public.app_users(id) on delete set null,reviewed_at timestamptz,review_notes text,created_at timestamptz not null default now(),check(ends_at>starts_at));
create table if not exists public.angelcare360_access_separation_findings(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,fingerprint text not null,app_user_id uuid references public.app_users(id) on delete cascade,rule_key text not null,conflicting_operations jsonb not null default '[]',severity text not null default 'high',state text not null default 'open',exception_id uuid,detected_at timestamptz not null default now(),resolved_at timestamptz,unique(school_id,fingerprint));
create table if not exists public.angelcare360_access_issues(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,fingerprint text not null,category text not null,title text not null,detail text not null,consequence text,app_user_id uuid references public.app_users(id) on delete set null,user_label text,role_id uuid references public.angelcare360_roles(id) on delete set null,role_label text,severity text not null default 'warning',state text not null default 'open',owner_id uuid references public.app_users(id) on delete set null,owner_label text,due_at timestamptz,recommended_action_key text,recommended_action_label text,resolution_reason text,resolved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(school_id,fingerprint));
create table if not exists public.angelcare360_access_tasks(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,app_user_id uuid references public.app_users(id) on delete set null,issue_id uuid references public.angelcare360_access_issues(id) on delete set null,title text not null,detail text,owner_id uuid references public.app_users(id) on delete set null,owner_label text,due_at timestamptz,state text not null default 'open',completed_at timestamptz,created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare360_access_notes(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,entity_type text not null,entity_id uuid,note text not null,created_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.angelcare360_access_evidence_requests(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,app_user_id uuid references public.app_users(id) on delete set null,category_key text not null,request_text text not null,state text not null default 'requested',requested_by uuid references public.app_users(id) on delete set null,due_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.angelcare360_access_topup_requests(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,requested_quantity integer not null check(requested_quantity>0),meter_key text not null,package_version_id uuid,state text not null default 'requested',source_context jsonb not null default '{}',requested_by uuid references public.app_users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare360_access_history(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,entity_type text not null,entity_id uuid,action_key text not null,label text not null,detail text,actor_id uuid references public.app_users(id) on delete set null,actor_label text,state text not null default 'recorded',created_at timestamptz not null default now());
create table if not exists public.angelcare360_access_action_receipts(id uuid primary key default gen_random_uuid(),school_id uuid not null references public.angelcare360_schools(id) on delete cascade,action_key text not null,idempotency_key text not null,result_json jsonb not null default '{}',created_at timestamptz not null default now(),unique(school_id,action_key,idempotency_key));
create index if not exists ac360_access_invites_idx on public.angelcare360_access_invitations(school_id,state,expires_at);
create index if not exists ac360_access_requests_idx on public.angelcare360_access_requests(school_id,state,created_at desc);
create index if not exists ac360_access_delegations_idx on public.angelcare360_access_delegations(school_id,state,starts_at,ends_at);
create index if not exists ac360_sensitive_access_idx on public.angelcare360_sensitive_access_grants(school_id,state,next_review_at);
create index if not exists ac360_access_reviews_idx on public.angelcare360_access_review_campaigns(school_id,state,due_at);
create index if not exists ac360_access_issues_idx on public.angelcare360_access_issues(school_id,state,severity,due_at);
create index if not exists ac360_access_history_idx on public.angelcare360_access_history(school_id,created_at desc);
do $$ declare t text; begin foreach t in array array['angelcare360_access_invitations','angelcare360_access_role_versions','angelcare360_access_requests','angelcare360_temporary_access_grants','angelcare360_access_delegations','angelcare360_sensitive_access_grants','angelcare360_access_review_campaigns','angelcare360_access_review_decisions','angelcare360_emergency_access_events','angelcare360_access_separation_findings','angelcare360_access_issues','angelcare360_access_tasks','angelcare360_access_notes','angelcare360_access_evidence_requests','angelcare360_access_topup_requests','angelcare360_access_history','angelcare360_access_action_receipts'] loop execute format('alter table public.%I enable row level security',t); execute format('revoke insert,update,delete on public.%I from anon,authenticated',t); end loop; end $$;
insert into public.angelcare360_permissions(permission_key,domain_key,action_key,label,description,risk_level,status) values
('angelcare360.securite.view','securite','view','Voir les utilisateurs et accès','Consulter les rôles, périmètres, demandes et revues de son établissement.','medium','active'),
('angelcare360.securite.configure','securite','configure','Configurer les accès de l’établissement','Inviter, attribuer des rôles approuvés et maintenir les périmètres.','high','active'),
('angelcare360.securite.approve','securite','approve','Valider les accès sensibles','Approuver les rôles, délégations, urgences et revues à fort impact.','critical','active'),
('angelcare360.securite.audit','securite','audit','Auditer les accès','Examiner les versions, décisions et traces d’accès.','high','active') on conflict(permission_key) do update set label=excluded.label,description=excluded.description,risk_level=excluded.risk_level,status=excluded.status,updated_at=now();

insert into public.angelcare360_operator_product_operations(operation_key,route_path,feature_key,operation_name,permission_key,audit_event,mutation_endpoints,source_confidence,status) values
('user_access.invite','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','invite','angelcare360.securite.configure','customer.access.user_access.invite','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('user_access.resend_invitation','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','resend invitation','angelcare360.securite.configure','customer.access.user_access.resend_invitation','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('user_access.cancel_invitation','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','cancel invitation','angelcare360.securite.configure','customer.access.user_access.cancel_invitation','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('user_access.activate','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','activate','angelcare360.securite.configure','customer.access.user_access.activate','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('user_access.suspend','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','suspend','angelcare360.securite.configure','customer.access.user_access.suspend','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('user_access.restore','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','restore','angelcare360.securite.configure','customer.access.user_access.restore','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('user_access.end','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','end','angelcare360.securite.approve','customer.access.user_access.end','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('user_access.revoke_sessions','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','revoke sessions','angelcare360.securite.audit','customer.access.user_access.revoke_sessions','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('role.create','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','create','angelcare360.securite.configure','customer.access.role.create','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('role.update','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','update','angelcare360.securite.configure','customer.access.role.update','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('role.prepare_version','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','prepare version','angelcare360.securite.configure','customer.access.role.prepare_version','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('role.request_approval','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','request approval','angelcare360.securite.configure','customer.access.role.request_approval','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('role.publish_version','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','publish version','angelcare360.securite.approve','customer.access.role.publish_version','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('role.retire','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','retire','angelcare360.securite.configure','customer.access.role.retire','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('role.archive','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','archive','angelcare360.securite.configure','customer.access.role.archive','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('role_assignment.preview','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','preview','angelcare360.securite.audit','customer.access.role_assignment.preview','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('role_assignment.assign','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','assign','angelcare360.securite.configure','customer.access.role_assignment.assign','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('role_assignment.change_scope','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','change scope','angelcare360.securite.configure','customer.access.role_assignment.change_scope','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('role_assignment.schedule_end','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','schedule end','angelcare360.securite.configure','customer.access.role_assignment.schedule_end','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('role_assignment.end','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','end','angelcare360.securite.configure','customer.access.role_assignment.end','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_request.create','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','create','angelcare360.securite.configure','customer.access.access_request.create','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_request.assign','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','assign','angelcare360.securite.configure','customer.access.access_request.assign','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_request.request_information','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','request information','angelcare360.securite.configure','customer.access.access_request.request_information','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_request.approve','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','approve','angelcare360.securite.approve','customer.access.access_request.approve','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_request.approve_limited','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','approve limited','angelcare360.securite.approve','customer.access.access_request.approve_limited','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_request.reject','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','reject','angelcare360.securite.configure','customer.access.access_request.reject','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_request.cancel','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','cancel','angelcare360.securite.configure','customer.access.access_request.cancel','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('temporary_access.preview','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','preview','angelcare360.securite.audit','customer.access.temporary_access.preview','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('temporary_access.grant','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','grant','angelcare360.securite.configure','customer.access.temporary_access.grant','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('temporary_access.extend','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','extend','angelcare360.securite.configure','customer.access.temporary_access.extend','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('temporary_access.revoke','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','revoke','angelcare360.securite.configure','customer.access.temporary_access.revoke','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('temporary_access.expire','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','expire','angelcare360.securite.configure','customer.access.temporary_access.expire','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('delegation.create','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','create','angelcare360.securite.configure','customer.access.delegation.create','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('delegation.request_approval','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','request approval','angelcare360.securite.configure','customer.access.delegation.request_approval','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('delegation.approve','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','approve','angelcare360.securite.approve','customer.access.delegation.approve','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('delegation.activate','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','activate','angelcare360.securite.approve','customer.access.delegation.activate','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('delegation.revoke','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','revoke','angelcare360.securite.approve','customer.access.delegation.revoke','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('delegation.expire','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','expire','angelcare360.securite.configure','customer.access.delegation.expire','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('sensitive_access.request','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','request','angelcare360.securite.configure','customer.access.sensitive_access.request','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('sensitive_access.approve','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','approve','angelcare360.securite.approve','customer.access.sensitive_access.approve','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('sensitive_access.review','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','review','angelcare360.securite.audit','customer.access.sensitive_access.review','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('sensitive_access.revoke','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','revoke','angelcare360.securite.approve','customer.access.sensitive_access.revoke','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_review.create','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','create','angelcare360.securite.audit','customer.access.access_review.create','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_review.assign','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','assign','angelcare360.securite.audit','customer.access.access_review.assign','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_review.confirm_item','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','confirm item','angelcare360.securite.audit','customer.access.access_review.confirm_item','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_review.reduce_item','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','reduce item','angelcare360.securite.audit','customer.access.access_review.reduce_item','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_review.revoke_item','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','revoke item','angelcare360.securite.audit','customer.access.access_review.revoke_item','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_review.complete','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','complete','angelcare360.securite.approve','customer.access.access_review.complete','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_review.reopen','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','reopen','angelcare360.securite.audit','customer.access.access_review.reopen','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('emergency_access.request','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','request','angelcare360.securite.configure','customer.access.emergency_access.request','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('emergency_access.activate','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','activate','angelcare360.securite.approve','customer.access.emergency_access.activate','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('emergency_access.revoke','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','revoke','angelcare360.securite.configure','customer.access.emergency_access.revoke','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('emergency_access.review','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','review','angelcare360.securite.audit','customer.access.emergency_access.review','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_issue.assign','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','assign','angelcare360.securite.configure','customer.access.access_issue.assign','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_issue.resolve','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','resolve','angelcare360.securite.configure','customer.access.access_issue.resolve','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_issue.reopen','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','reopen','angelcare360.securite.configure','customer.access.access_issue.reopen','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_task.assign','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','assign','angelcare360.securite.configure','customer.access.access_task.assign','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_task.complete','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','complete','angelcare360.securite.approve','customer.access.access_task.complete','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_task.reopen','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','reopen','angelcare360.securite.configure','customer.access.access_task.reopen','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_note.add','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','add','angelcare360.securite.configure','customer.access.access_note.add','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_evidence.request','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','request','angelcare360.securite.configure','customer.access.access_evidence.request','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published'),
('access_topup.request','/angelcare-360-command-center/administration?plane=roles-permissions','administration.roles-permissions','request','angelcare360.securite.configure','customer.access.access_topup.request','["/api/angelcare360/access"]'::jsonb,'signed_area6_contract','published')
on conflict(operation_key) do update set route_path=excluded.route_path,feature_key=excluded.feature_key,operation_name=excluded.operation_name,permission_key=excluded.permission_key,audit_event=excluded.audit_event,mutation_endpoints=excluded.mutation_endpoints,source_confidence=excluded.source_confidence,status=excluded.status,updated_at=now();
commit;
