'use client'
import Link from '@/angelcare-marketplace/navigation-care-orbit/CareOrbitLink'
import { useEffect, useMemo, useRef, useState, type ReactNode, type RefObject } from 'react'
import { ArrowRight, ArrowUpRight, ArrowUp, Heart, Search, Sparkles, ShieldCheck, MapPin, BookOpen, PackageOpen, CalendarDays, Check, X, ChevronDown } from 'lucide-react'
import type { CatalogLocale, DiscoveryItem, StorefrontExperience } from '../../catalog-discovery/types'
import { FAMILY_ATOMIC_STORIES } from '../contract'
import { familyWords, familyLabel, familyDisplayKey, familyDetailHref, familyPrice, familyAvailability, familyRequestHref, selectFamilyItems, type FamilyWords } from '../experience'
import { FAMILY_EDITORIAL_MEDIA, FAMILY_HERO_MEDIA } from '../media'
import { FamilyOfferCard } from '../components/FamilyOfferCard'
import { FamilyCommerceRail } from '../components/FamilyCommerceRail'
import { canonicalCollections, directoryHref, gatewayConfiguration, gatewayDestination, gatewayHref, matchesAge, matchesInterest, matchesRhythm, recommendGateway, type GatewayAge, type GatewayInterest, type GatewayNeed, type GatewayRhythm, type GatewayWorld } from './contract'
import { GATEWAY_COPY as C, INTERESTS, NEEDS, RHYTHMS, WORLDS, words } from './content'
import { useGatewaySelections } from './useGatewaySelections'
import styles from './gateway.module.css'

const editorial = (name: string) => `/angelcare-marketplace/families-world-r2/${name}.jpg`
type Selection = ReturnType<typeof useGatewaySelections>
function Photo({ src, alt = '', priority = false, contain = false }: { src: string; alt?: string; priority?: boolean; contain?: boolean }) {
  return <img src={src} alt={alt} width={1536} height={1024} loading={priority ? 'eager' : 'lazy'} fetchPriority={priority ? 'high' : undefined} decoding="async" data-contain={contain || undefined}/>
}
function Head({ number, title, lead, children }: { number: string; title: string; lead?: string; children?: ReactNode }) {
  return <header className={styles.heading}><div><span className={styles.kicker}>{number} / ANGELCARE FAMILIES</span><h2>{title}</h2>{lead ? <p>{lead}</p> : null}</div>{children}</header>
}
function WorldLink({ locale, world, children, secondary = false }: { locale: CatalogLocale; world: GatewayWorld; children?: ReactNode; secondary?: boolean }) {
  return <Link className={secondary ? styles.secondary : styles.action} href={gatewayHref(locale, world)} data-family-destination={world}>{children || familyWords(WORLDS.find(row => row.key === world)!.title, locale)}<ArrowUpRight size={18}/></Link>
}
function Empty({ locale, world, onReset }: { locale: CatalogLocale; world: GatewayWorld; onReset?: () => void }) {
  return <div className={styles.empty}><Sparkles aria-hidden="true"/><div><h3>{familyWords(C.empty, locale)}</h3><p>{familyWords(C.emptyLead, locale)}</p></div><div className={styles.actions}><WorldLink locale={locale} world={world}/>{onReset ? <button className={styles.secondary} type="button" onClick={onReset}>{familyWords(C.reset, locale)}</button> : null}</div></div>
}
function Offers({ items, locale, selection, label, limit = 4 }: { items: readonly DiscoveryItem[]; locale: CatalogLocale; selection: Selection; label: string; limit?: number }) {
  return <div className={styles.shelf}><FamilyCommerceRail locale={locale} label={label}>{items.slice(0, limit).map(item => <FamilyOfferCard key={item.id} item={item} locale={locale} saved={selection.saved.has(item.id)} pending={selection.pending} onSave={selection.onSave}/>)}</FamilyCommerceRail></div>
}
function useShellOffset(root: RefObject<HTMLDivElement | null>) {
  useEffect(() => {
    const world = root.current
    if (!world) return
    const headers = [...document.querySelectorAll<HTMLElement>('header,nav')].filter(node => !world.contains(node) && getComputedStyle(node).position === 'sticky')
    const measure = () => { const offset = headers.reduce((height, node) => { const top = parseFloat(getComputedStyle(node).top) || 0; const rect = node.getBoundingClientRect(); const forms = [...node.querySelectorAll<HTMLElement>('form')].filter(form => form.getClientRects().length); return Math.max(height, top + Math.max(node.offsetHeight, ...forms.map(form => form.getBoundingClientRect().bottom - rect.top))) }, 0); world.style.setProperty('--family-sticky-offset', `${offset}px`) }
    measure(); const observer = new ResizeObserver(measure); headers.forEach(header => observer.observe(header)); window.addEventListener('resize', measure)
    return () => { observer.disconnect(); window.removeEventListener('resize', measure) }
  }, [root])
}
export function FamilyGateway({ experience, builtinWorldId }: { experience: StorefrontExperience; builtinWorldId?: string | null }) {
  const { locale } = experience, w = (value: FamilyWords) => familyWords(value, locale)
  const root = useRef<HTMLDivElement>(null); useShellOffset(root)
  const all = useMemo(() => selectFamilyItems(experience.items, {}, locale), [experience.items, locale])
  const selection = useGatewaySelections(experience, all)
  const [need, setNeed] = useState<GatewayNeed>('care'), [rhythm, setRhythm] = useState<GatewayRhythm>('all'), [age, setAge] = useState<GatewayAge>('all'), [interest, setInterest] = useState<GatewayInterest>('all'), [query, setQuery] = useState(''), [expanded, setExpanded] = useState(false), [continuation, setContinuation] = useState<'recent' | 'saved'>('recent'), [kitIndex, setKitIndex] = useState(0)
  useEffect(() => {
    let frame = 0, nextFrame = 0
    const openAnchor = () => {
      const id = location.hash.slice(1)
      const legacyId = id.replace(/^rail-/, '')
      const legacy: Record<string, { target: string; need?: GatewayNeed }> = { 'family-postpartum': { target: 'family-finder', need: 'baby' }, 'family-home-activities': { target: 'family-finder', need: 'learn' }, 'family-event-care': { target: 'family-care' }, 'family-more-offers': { target: 'family-featured' } }
      if (legacy[legacyId]) {
        const target = legacy[legacyId]
        if (target.need) { setNeed(target.need); setRhythm('all'); setAge('all') }
        frame = requestAnimationFrame(() => { nextFrame = requestAnimationFrame(() => document.getElementById(target.target)?.scrollIntoView({ block: 'start' })) })
        return
      }
      const story = FAMILY_ATOMIC_STORIES.find(row => row.anchor === id || `rail-${row.anchor}` === id)
      if (!story) return
      setExpanded(true)
      frame = requestAnimationFrame(() => { nextFrame = requestAnimationFrame(() => document.getElementById(id)?.scrollIntoView({ block: 'start' })) })
    }
    openAnchor(); window.addEventListener('hashchange', openAnchor)
    return () => { window.removeEventListener('hashchange', openAnchor); cancelAnimationFrame(frame); cancelAnimationFrame(nextFrame) }
  }, [])
  const care = useMemo(() => all.filter(item => item.kind === 'service'), [all])
  const learning = useMemo(() => all.filter(item => (item.kind === 'product' || item.kind === 'kit') && gatewayDestination(item) === 'development'), [all])
  const kits = useMemo(() => all.filter(item => (item.kind === 'product' || item.kind === 'kit') && gatewayDestination(item) === 'kits'), [all])
  const discovery = useMemo(() => recommendGateway(all, locale, { need, rhythm: need === 'care' ? rhythm : 'all', age }), [all, locale, need, rhythm, age])
  const ageItems = useMemo(() => all.filter(item => (item.kind === 'product' || item.kind === 'kit') && matchesAge(item, age)), [all, age])
  const learningItems = useMemo(() => learning.filter(item => matchesInterest(item, interest)), [learning, interest])
  const featured = useMemo(() => selectFamilyItems(all, { query }, locale).slice(0, 8), [all, locale, query])
  const collections = useMemo(() => canonicalCollections(experience, all), [experience, all])
  const kit = kits[Math.min(kitIndex, Math.max(0, kits.length - 1))], kitConfig = kit ? gatewayConfiguration(kit) : {}
  const components = Array.isArray(kitConfig.components) ? kitConfig.components.filter((value): value is string => typeof value === 'string' && value.length > 0).slice(0, 5) : typeof kitConfig.components === 'string' ? kitConfig.components.split('|').map(value => value.trim()).filter(Boolean).slice(0, 5) : []
  const visited = selection.recent.map(id => all.find(item => item.id === id)).filter((item): item is DiscoveryItem => !!item)
  const continued = continuation === 'saved' ? all.filter(item => selection.saved.has(item.id)) : visited
  const activeNeed = NEEDS.find(row => row.key === need)!
  const chooseNeed = (value: GatewayNeed) => { setNeed(value); setRhythm('all'); setAge('all') }
  const resetFinder = () => { setNeed('care'); setRhythm('all'); setAge('all') }
  const scrollTo = (id: string) => { root.current?.querySelector<HTMLElement>(`#${id}`)?.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'start' }) }
  return <div ref={root} className={styles.world} dir={locale === 'ar' ? 'rtl' : 'ltr'} data-ac-families-storefront="immersive-gateway-r2" data-ac-pea-built-in-storefront={builtinWorldId || undefined} onClickCapture={event => {
    const element = (event.target as HTMLElement).closest<HTMLAnchorElement>('a[href]')
    const item = element?.closest<HTMLElement>('[data-family-offer]')
    if (item && element?.getAttribute('href')?.includes('/marketplace/item/')) selection.remember(item.dataset.familyOffer!)
  }}>
    <section id="family-top" data-family-section="hero" className={styles.hero}>
      <div className={styles.heroCopy}><span className={styles.kicker}>{w(C.eyebrow)}</span><h1>{w(C.hero)}</h1><p>{w(C.heroLead)}</p><div className={styles.actions}><a className={styles.action} href="#family-gateways">{w(C.explore)}<ArrowRight size={18}/></a><a className={styles.secondary} href="#family-finder">{w(C.guide)}<Sparkles size={17}/></a></div><div className={styles.heroMini}>{WORLDS.map(world => <Link key={world.key} href={gatewayHref(locale, world.key)}><span>{w(world.label)}</span><strong>{w(world.title)}<ArrowUpRight size={15}/></strong></Link>)}</div></div>
      <div className={styles.heroScene}><Photo src={FAMILY_HERO_MEDIA} priority/><div className={styles.photoCaption}><span>{w(C.inspiration)}</span><strong>{w(C.photoLine)}</strong></div><div className={styles.floatingNote}><Heart size={18}/><span>{w(words('Votre famille. Votre rythme.', 'Your family. Your rhythm.', 'أسرتكم. إيقاعكم.'))}</span></div></div>
    </section>
    <nav className={styles.localNav} aria-label={w(words('Explorer Families', 'Explore Families', 'استكشفوا عالم الأسرة'))}><a href="#family-gateways" className={styles.navBrand}><Sparkles size={17}/> FAMILIES</a><div>{WORLDS.map(world => <Link key={world.key} href={gatewayHref(locale, world.key)}>{w(world.title)}<ArrowUpRight size={14}/></Link>)}<a href="#family-ages">{w(C.age)}</a><a href="#family-continue"><Heart size={14}/>{w(C.saved)}</a></div><a className={styles.navGuide} href="#family-finder">{w(C.guide)}</a></nav>
    <section id="family-gateways" data-family-section="gateways" className={styles.section}><Head number="02" title={w(C.gatewayTitle)} lead={w(C.gatewayLead)}/><div className={styles.gatewayGrid}>{WORLDS.map((world, index) => <Link key={world.key} href={gatewayHref(locale, world.key)} className={styles.gatewayCard} data-world={world.key} data-family-destination={world.key}><div className={styles.gatewayPhoto}><Photo src={editorial(world.media)}/><span>{String(index + 1).padStart(2, '0')}</span></div><div className={styles.gatewayBody}><small>{w(world.label)}</small><h3>{w(world.title)}</h3><strong>{w(world.promise)}</strong><p>{w(world.detail)}</p><div><span>{w(C.openWorld)}</span><ArrowUpRight size={24}/></div></div></Link>)}</div></section>
    <section id="family-needs" data-family-section="situations" className={styles.section}><Head number="03" title={w(C.needsTitle)} lead={w(C.needsLead)}/><div className={styles.situationGrid}>{NEEDS.map((row, index) => <button type="button" key={row.key} className={styles.situation} data-large={index === 0 || undefined} onClick={() => { chooseNeed(row.key); scrollTo('family-finder') }}><Photo src={editorial(row.media)}/><span className={styles.situationCopy}><small>{w(C.editorial)}</small><strong>{w(row.title)}</strong><span>{w(row.line)}</span><span className={styles.situationArrow}><ArrowUpRight size={22}/></span></span></button>)}</div></section>
    <section id="family-finder" data-family-section="finder" className={`${styles.section} ${styles.finder}`}><span id="family-postpartum"/><span id="rail-family-postpartum"/><span id="family-home-activities"/><span id="rail-family-home-activities"/><Head number="04" title={w(C.finderTitle)} lead={w(C.finderLead)}/><div className={styles.finderControls}><label><span>01 · {w(C.need)}</span><select value={need} onChange={event => chooseNeed(event.target.value as GatewayNeed)}>{NEEDS.map(row => <option key={row.key} value={row.key}>{w(row.title)}</option>)}</select></label><label><span>02 · {w(C.rhythm)}</span><select value={rhythm} disabled={need !== 'care'} onChange={event => setRhythm(event.target.value as GatewayRhythm)}><option value="all">{w(C.allRhythms)}</option>{RHYTHMS.map(row => <option key={row.key} value={row.key}>{w(row.title)}</option>)}</select></label><label><span>03 · {w(C.age)}</span><select value={age} onChange={event => setAge(event.target.value as GatewayAge)}><option value="all">{w(C.allAges)}</option>{(['0-2', '3-5', '6-8', '9-12'] as const).map(value => <option value={value} key={value}>{value} {w(words('ans', 'years', 'سنوات'))}</option>)}</select></label><button type="button" className={styles.resetButton} onClick={resetFinder}><X size={15}/>{w(C.reset)}</button></div><div className={styles.finderResult} role="status" aria-live="polite"><span><Check size={17}/>{w(activeNeed.title)}</span><strong>{discovery.length} {w(C.offers)}</strong><WorldLink locale={locale} world={activeNeed.world}/></div>{discovery.length ? <Offers items={discovery} locale={locale} selection={selection} label={w(C.finderTitle)} limit={3}/> : <Empty locale={locale} world={activeNeed.world} onReset={resetFinder}/>}</section>
    <section id="family-care" data-family-section="home-services" className={`${styles.section} ${styles.care}`}><span id="family-event-care" hidden/><span id="rail-family-event-care" hidden/><div className={styles.careScene}><Photo src={editorial('care')}/><span>{w(words('HOME SERVICES · À DOMICILE', 'HOME SERVICES · AT HOME', 'الخدمات المنزلية'))}</span></div><div className={styles.careCopy}><Head number="05" title={w(C.careTitle)} lead={w(C.careLead)}/><div className={styles.carePoints}>{[words('Un besoin à comprendre', 'Understand your need', 'فهم احتياجكم'), words('Un rythme à organiser', 'Plan your rhythm', 'تنظيم إيقاعكم'), words('Des conditions à vérifier', 'Review the conditions', 'التحقق من الشروط')].map((value, index) => <div key={index}><span>0{index + 1}</span><strong>{w(value)}</strong></div>)}</div><WorldLink locale={locale} world="home-services"/></div><div className={styles.careShelf}>{care.length ? <Offers items={care} locale={locale} selection={selection} label={w(C.careTitle)}/> : <Empty locale={locale} world="home-services"/>}</div></section>
    <section id="family-rhythm" data-family-section="rhythms" className={styles.section}><Head number="06" title={w(C.rhythmTitle)} lead={w(C.rhythmLead)}/><div className={styles.rhythmGrid}>{RHYTHMS.map((row, index) => <button key={row.key} type="button" className={styles.rhythmCard} onClick={() => { setNeed('care'); setRhythm(row.key); setAge('all'); scrollTo('family-finder') }}><span className={styles.rhythmNumber}>0{index + 1}</span><Photo src={editorial(row.media)}/><CalendarDays size={22}/><strong>{w(row.title)}</strong><span>{w(row.detail)}</span><small>{care.filter(item => matchesRhythm(item, row.key)).length} {w(C.offers)}<ArrowRight size={17}/></small></button>)}</div><p className={styles.fineprint}>{w(C.rhythmNote)}</p></section>
    <section id="family-learn" data-family-section="development" className={`${styles.section} ${styles.development}`}><div className={styles.developmentIntro}><Head number="07" title={w(C.developTitle)} lead={w(C.developLead)}/><WorldLink locale={locale} world="development"/></div><div className={styles.developmentPhoto}><Photo src={editorial('montessori')}/><span>{w(words('LE MONDE S’APPREND EN EXPLORANT', 'A WORLD TO LEARN THROUGH DISCOVERY', 'عالم نتعلمه بالاكتشاف'))}</span></div><div className={styles.goalControls} role="group" aria-label={w(C.allGoals)}><button className={styles.goalReset} aria-pressed={interest === 'all'} onClick={() => setInterest('all')} type="button">{w(C.allGoals)}</button>{INTERESTS.map(row => <button key={row.key} type="button" aria-pressed={interest === row.key} onClick={() => setInterest(row.key)}><span>{row.symbol}</span><strong>{w(row.title)}</strong><ArrowUpRight size={18}/></button>)}</div><div className={styles.developmentShelf} aria-live="polite">{learningItems.length ? <Offers items={learningItems} locale={locale} selection={selection} label={w(C.developTitle)}/> : <Empty locale={locale} world="development" onReset={() => setInterest('all')}/>}</div></section>
    <section id="family-play" data-family-section="kits" className={`${styles.section} ${styles.kits}`}><Head number="08" title={w(C.kitsTitle)} lead={w(C.kitsLead)}><WorldLink locale={locale} world="kits"/></Head><div className={styles.kitShowcase} data-family-offer={kit?.id}><div className={styles.kitStage}><Photo src={kit?.media_url || editorial('kits')} alt={kit?.media_url ? kit.name : ''} contain={!!kit?.media_url}/><span className={styles.kitSeal}><PackageOpen size={28}/>{kit ? w(C.contents) : w(C.editorial)}</span></div><div className={styles.kitDetails}><span className={styles.kicker}>KITS · {w(words('DÉCOUVRIR PAR LE JEU', 'DISCOVER THROUGH PLAY', 'اكتشاف باللعب'))}</span><h3>{kit?.name || w(words('Une nouvelle expérience à la maison.', 'A new experience at home.', 'تجربة جديدة في المنزل.'))}</h3><p>{kit?.short_description || w(C.kitEditorial)}</p>{components.length ? <ul>{components.map((value, index) => <li key={index}><Check size={17}/>{value}</li>)}</ul> : null}{kit ? <><span className={styles.kitStatus}>{familyAvailability(kit, locale)}</span><strong className={styles.kitPrice}>{familyPrice(kit, locale)}</strong><Link className={styles.action} href={familyDetailHref(locale, kit)}>{w(C.preview)}<ArrowUpRight size={18}/></Link></> : <WorldLink locale={locale} world="kits"/>}</div></div>{kits.length > 1 ? <div className={styles.kitPicker} role="group" aria-label={w(words('Explorer les kits', 'Explore kits', 'استكشفوا المجموعات'))}>{kits.slice(0, 6).map((item, index) => <button key={item.id} type="button" aria-pressed={kit?.id === item.id} onClick={() => setKitIndex(index)}>{item.media_url ? <Photo src={item.media_url} contain/> : <PackageOpen size={26}/>}<span>{item.name}</span></button>)}</div> : null}</section>
    <section id="family-ages" data-family-section="ages" className={`${styles.section} ${styles.ages}`}><Head number="09" title={w(C.agesTitle)} lead={w(C.agesLead)}/><div className={styles.ageTabs} role="group" aria-label={w(C.age)}><button type="button" aria-pressed={age === 'all'} onClick={() => setAge('all')}>{w(C.allAges)}</button>{(['0-2', '3-5', '6-8', '9-12'] as const).map((value, index) => <button key={value} type="button" aria-pressed={age === value} onClick={() => setAge(value)}><small>0{index + 1}</small><strong>{value}</strong><span>{w(words('ans', 'years', 'سنوات'))}</span></button>)}</div><div aria-live="polite">{ageItems.length ? <Offers items={ageItems} locale={locale} selection={selection} label={w(C.agesTitle)}/> : <Empty locale={locale} world="development" onReset={() => setAge('all')}/>}</div></section>
    <section id="family-moments" data-family-section="moments" className={styles.section}><Head number="10" title={w(C.momentsTitle)}/><div className={styles.moments}>{[
      { image: 'school', title: words('Après l’école, un nouveau chapitre.', 'After school, a new chapter.', 'بعد المدرسة، فصل جديد.'), body: words('Un relais à préparer. Un jeu à découvrir. Un moment pour se retrouver.', 'Support to plan. A game to discover. A moment to reconnect.', 'دعم للتخطيط ولعبة للاكتشاف ولحظة للقاء.'), world: 'home-services' as const },
      { image: 'flashcards', title: words('Un mot. Un regard. Une découverte.', 'A word. A glance. A discovery.', 'كلمة. ونظرة. واكتشاف.'), body: words('Explorez les thèmes et les formats des cartes pédagogiques.', 'Explore the themes and formats of learning cards.', 'استكشفوا مواضيع وصيغ البطاقات التعليمية.'), world: 'development' as const },
      { image: 'games', title: words('Le plaisir de faire ensemble.', 'The joy of making together.', 'متعة العمل معًا.'), body: words('Des idées concrètes pour vos moments à la maison.', 'Practical ideas for your moments at home.', 'أفكار عملية للحظاتكم في المنزل.'), world: 'kits' as const },
    ].map((row, index) => <article key={row.image} className={styles.moment}><div><Photo src={editorial(row.image)}/><span>0{index + 1}</span></div><div><small>{w(C.editorial)}</small><h3>{w(row.title)}</h3><p>{w(row.body)}</p><WorldLink locale={locale} world={row.world} secondary/></div></article>)}</div></section>
    <section id="family-featured" data-family-section="featured" className={styles.section}><span id="family-more-offers"/><span id="rail-family-more-offers"/><Head number="11" title={w(C.featuredTitle)} lead={w(C.featuredLead)}/><label className={styles.search}><Search size={20}/><input value={query} type="search" onChange={event => setQuery(event.target.value)} placeholder={w(C.search)} aria-label={w(C.search)} maxLength={120}/>{query ? <button type="button" onClick={() => setQuery('')} aria-label={w(C.reset)}><X size={17}/></button> : null}</label><p className={styles.resultCount} role="status">{selectFamilyItems(all, { query }, locale).length} {w(C.offers)}</p>{featured.length ? <Offers items={featured} locale={locale} selection={selection} label={w(C.featuredTitle)} limit={8}/> : <Empty locale={locale} world="home-services" onReset={() => setQuery('')}/>}</section>
    <section id="family-collections" data-family-section="collections" className={`${styles.section} ${styles.collections}`}><Head number="12" title={w(C.collectionsTitle)} lead={w(C.collectionsLead)}/>{collections.length ? <div className={styles.collectionGrid}>{collections.slice(0, 4).map((collection, index) => <article key={collection.id} data-variant={index % 2 ? 'compact' : 'editorial'}><div className={styles.collectionCover}><Photo src={collection.items.find(item => item.media_url)?.media_url || editorial('games')}/><span>{collection.items.length} {w(C.offers)}</span></div><div><h3>{collection.title}</h3>{collection.subtitle ? <p>{collection.subtitle}</p> : null}{collection.items.slice(0, 3).map(item => <Link key={item.id} data-family-offer={item.id} href={familyDetailHref(locale, item)}>{item.name}<ArrowUpRight size={16}/></Link>)}</div></article>)}</div> : <div className={styles.collectionEditorial}><Photo src={editorial('games')}/><div><span className={styles.kicker}>{w(C.editorial)}</span><h3>{w(C.collectionEmpty)}</h3><p>{w(words('Cartes pour explorer, kits pour expérimenter. Découvrez chaque univers et ses offres.', 'Cards to explore, kits to experiment. Discover each world and its offers.', 'بطاقات للاكتشاف ومجموعات للتجربة. اكتشفوا كل عالم وعروضه.'))}</p><div className={styles.actions}><WorldLink locale={locale} world="development"/><WorldLink locale={locale} world="kits" secondary/></div></div></div>}</section>
    <section id="family-confidence" data-family-section="confidence" className={styles.section}><Head number="13" title={w(C.confidenceTitle)}/><div className={styles.confidenceGrid}>{[
      { Icon: ShieldCheck, title: words('Comprendre les engagements', 'Understand the commitments', 'فهم الالتزامات'), body: words('Consultez les informations de confiance et les conditions de chaque offre.', 'Read trust information and each offer’s conditions.', 'اطلعوا على معلومات الثقة وشروط كل عرض.'), href: `/angelcare-marketplace/${locale}/trust` },
      { Icon: MapPin, title: words('Vérifier votre lieu et vos horaires', 'Check your location and times', 'تحققوا من المكان والأوقات'), body: words('La couverture et les possibilités se précisent dans le parcours du service.', 'Service coverage and possibilities are checked in the offer journey.', 'يتم التحقق من التغطية والإمكانيات في مسار الخدمة.'), href: gatewayHref(locale, 'home-services') },
      { Icon: BookOpen, title: words('Choisir un format adapté', 'Choose a suitable format', 'اختاروا صيغة مناسبة'), body: words('Âges, contenus, accès digital ou livraison : chaque fiche apporte ses repères.', 'Ages, contents, digital access or delivery: each page provides its details.', 'أعمار ومحتويات ووصول رقمي أو تسليم: التفاصيل في كل صفحة.'), href: gatewayHref(locale, 'development') },
    ].map(({ Icon, ...row }) => <Link key={row.href} href={row.href}><Icon size={29}/><h3>{w(row.title)}</h3><p>{w(row.body)}</p><ArrowUpRight size={19}/></Link>)}</div></section>
    <section id="family-continue" data-family-section="continue" className={`${styles.section} ${styles.continue}`}><Head number="14" title={w(C.continueTitle)} lead={w(C.continueLead)}><Link className={styles.secondary} href={`/angelcare-marketplace/${locale}/account`}>{w(words('Mon espace', 'My account', 'حسابي'))}<ArrowUpRight size={17}/></Link></Head><div className={styles.continueTabs} role="group" aria-label={w(C.continueTitle)}>{(['recent', 'saved'] as const).map(value => <button type="button" key={value} aria-pressed={continuation === value} onClick={() => setContinuation(value)}>{value === 'saved' ? <Heart size={16}/> : <BookOpen size={16}/>} {w(C[value])}</button>)}</div><div aria-live="polite">{continuation === 'saved' && selection.savedState === 'loading' ? <p role="status">{w(C.savedLoading)}</p> : continuation === 'saved' && selection.savedState === 'unavailable' ? <p>{w(C.savedUnavailable)}</p> : continued.length ? <Offers items={continued} locale={locale} selection={selection} label={w(C.continueTitle)}/> : <div className={styles.continueEmpty}><div><Sparkles size={30}/><p>{w(words('Une envie ? Ouvrez une offre et retrouvez-la ici pendant cette visite.', 'See something you like? Open an offer and find it here during this visit.', 'وجدتم ما يعجبكم؟ افتحوا عرضًا واعثروا عليه هنا خلال الزيارة.'))}</p></div><div className={styles.actions}>{WORLDS.map(world => <WorldLink key={world.key} locale={locale} world={world.key} secondary/>)}</div></div>}</div></section>
    <section id="family-travel" data-family-section="more" className={styles.section}><Head number="15" title={w(C.moreTitle)}/><div className={styles.moreGrid}>{(['hotel-travel-childcare', 'holiday-excursion-programme', 'preschool-admission'] as const).map(key => <Link key={key} href={directoryHref(locale, key)}><Photo src={FAMILY_EDITORIAL_MEDIA[key]}/><span><strong>{familyLabel(key, locale)}</strong><ArrowUpRight size={20}/></span></Link>)}</div><button className={styles.directoryToggle} type="button" onClick={() => setExpanded(current => !current)} aria-expanded={expanded} aria-controls="family-directory">{w(expanded ? C.lessUniverses : C.moreUniverses)}<ChevronDown size={18}/></button><div id="family-directory" className={styles.directory} hidden={!expanded}>{FAMILY_ATOMIC_STORIES.map(story => <article key={story.schemaKey} id={story.anchor} data-schema={story.schemaKey}><span id={`rail-${story.anchor}`}/><Link href={directoryHref(locale, story.schemaKey)}><Photo src={FAMILY_EDITORIAL_MEDIA[story.schemaKey]}/><strong>{familyLabel(story.schemaKey, locale)}</strong><ArrowUpRight size={16}/></Link><div>{all.filter(item => familyDisplayKey(item) === story.schemaKey).slice(0, 2).map(item => <Link href={familyDetailHref(locale, item)} data-family-offer={item.id} key={item.id}>{item.name}<ArrowUpRight size={13}/></Link>)}</div></article>)}</div></section>
    <section id="family-guidance" data-family-section="closing" className={`${styles.section} ${styles.closing}`}><div><Photo src={editorial('family')}/></div><div><span className={styles.kicker}>16 / ANGELCARE FAMILIES</span><h2>{w(C.closingTitle)}</h2><p>{w(C.closingLead)}</p><div className={styles.actions}><Link className={styles.action} href={familyRequestHref(locale)}>{w(C.guide)}<Heart size={18}/></Link><a className={styles.secondary} href="#family-gateways">{w(C.explore)}<ArrowUp size={18}/></a></div><div className={styles.closingDoors}>{WORLDS.map(world => <Link key={world.key} href={gatewayHref(locale, world.key)}>{w(world.title)}<ArrowUpRight size={17}/></Link>)}</div></div></section>
    {selection.saveError ? <div className={styles.error} role="alert">{w(C.saveError)}<button type="button" onClick={selection.dismissError} aria-label={w(words('Fermer', 'Close', 'إغلاق'))}><X size={18}/></button></div> : null}
    <nav className={styles.mobileDock} aria-label={w(words('Raccourcis famille', 'Family shortcuts', 'اختصارات الأسرة'))}>{WORLDS.map(world => <Link href={gatewayHref(locale, world.key)} key={world.key}>{world.key === 'home-services' ? <Heart size={17}/> : world.key === 'development' ? <Sparkles size={17}/> : <PackageOpen size={17}/>}<span>{w(world.title)}</span></Link>)}<a href="#family-finder" aria-label={w(C.guide)}><Search size={20}/></a></nav>
  </div>
}
