'use client'

import {useEffect,useRef,useState} from 'react'
import type { StudioSourceReference } from '@/angelcare-marketplace/studio-source-registry/types'
import { UniversalSourcePickerField } from '@/angelcare-marketplace/studio-picker/components/UniversalSourcePicker'
import {isStudioSourceReference} from '@/angelcare-marketplace/studio-picker/reference'
import styles from './studio-workspace.module.css'
import type { MediaAsset } from '@/angelcare-marketplace/commerce-studio/types'
import { MEDIA_ALLOWED_MIME, MEDIA_MAX_BYTES, sha256File } from '@/angelcare-marketplace/commerce-studio/media-library-operations'

type UploadSession={assetId:string;uploadUrl:string;completionUrl:string}
type PreflightResult={checksumSha256:string;errors:string[];duplicate:MediaAsset|null;state:'READY'|'FAILED'}
function putMedia(url:string,file:File,onProgress:(value:number)=>void){return new Promise<void>((resolve,reject)=>{const request=new XMLHttpRequest();request.open('PUT',url);request.setRequestHeader('content-type',file.type);request.upload.onprogress=event=>{if(event.lengthComputable)onProgress(Math.round(event.loaded/event.total*100))};request.onerror=()=>reject(new Error('Le stockage média Marketplace est injoignable.'));request.onload=()=>request.status>=200&&request.status<300?resolve():reject(new Error(`Téléversement refusé (HTTP ${request.status}).`));request.send(file)})}
async function json<T>(url:string,init:RequestInit):Promise<T>{const response=await fetch(url,init),body=await response.json();if(!response.ok||body?.error)throw new Error(body?.error?.message||`HTTP ${response.status}`);return (body?.data??body) as T}

export function MediaField({value,onChange}:{value:string|StudioSourceReference|null|undefined;onChange:(value:StudioSourceReference|null)=>void}){
  const input=useRef<HTMLInputElement|null>(null),[uploading,setUploading]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState('')
  const upload=async(file?:File)=>{if(!file)return;setError('');if(!MEDIA_ALLOWED_MIME.has(file.type)){setError('Format média non autorisé.');return}if(file.size<=0||file.size>MEDIA_MAX_BYTES){setError('Le fichier dépasse la limite média Marketplace.');return}setUploading(true);setProgress(2);try{const checksum=await sha256File(file);const preflight=await json<PreflightResult[]>('/api/angelcare-marketplace/admin/media/preflight',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({files:[{fileName:file.name,mimeType:file.type,sizeBytes:file.size,checksumSha256:checksum,folderId:null}]})});const check=preflight[0];if(!check||check.state!=='READY'){throw new Error(check?.errors?.join(' ')||'Préflight média refusé.')}if(check.duplicate){onChange({sourceId:'media.assets',entityId:check.duplicate.id});setProgress(100);return}const session=await json<UploadSession>('/api/angelcare-marketplace/admin/media/upload-session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fileName:file.name,mimeType:file.type,sizeBytes:file.size,folderId:null,altTextFr:file.name.replace(/\.[^.]+$/,'').replaceAll(/[-_]+/g,' '),replaceAssetId:null})});await putMedia(session.uploadUrl,file,setProgress);const asset=await json<MediaAsset>(session.completionUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fileName:file.name,mimeType:file.type,sizeBytes:file.size,checksumSha256:checksum,folderId:null,altTextFr:file.name.replace(/\.[^.]+$/,'').replaceAll(/[-_]+/g,' '),productReference:''})});onChange({sourceId:'media.assets',entityId:asset.id});setProgress(100)}catch(e){setError(e instanceof Error?e.message:'Téléversement impossible.')}finally{setUploading(false)}}
  return <div className={styles.inlineMediaField}><UniversalSourcePickerField sourceId="media.assets" label="Media Vault" description="Sélectionnez un média existant ou téléversez-en un nouveau sans quitter l’inspecteur." value={value} onChange={next=>onChange(Array.isArray(next)?next[0]||null:next)} legacyValueField="asset_key"/><input ref={input} hidden type="file" accept="image/*" onChange={event=>{void upload(event.target.files?.[0]);event.currentTarget.value=''}}/><div className={styles.inlineMediaActions}><button type="button" disabled={uploading} onClick={()=>input.current?.click()}>{uploading?`Téléversement ${progress}%`:'Téléverser un nouveau média'}</button>{value?<button type="button" onClick={()=>onChange(null)}>Détacher</button>:null}</div>{error?<p className={styles.inlineMediaError}>{error}</p>:null}</div>
}

type PreviewItem={id:string;title:string;subtitle?:string;image?:{url:string};metadata?:Record<string,unknown>}
export function RecordField({kind,value,onChange}:{kind:'category'|'collection';value:string|StudioSourceReference|null|undefined;onChange:(value:StudioSourceReference|null)=>void}){
  const category=kind==='category',ref=isStudioSourceReference(value)?value:null
  const[preview,setPreview]=useState<{items:PreviewItem[];total:number}|null>(null),[error,setError]=useState('')
  useEffect(()=>{if(!ref){setPreview(null);setError('');return}const controller=new AbortController(),recipe={version:1,sourceId:'catalog.items',strategy:category?'category_items':'collection_items',limit:8,emptyPolicy:'empty',...(category?{category:ref}:{collection:ref})};fetch('/api/angelcare-marketplace/cms/studio/dynamic-sources/preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({recipe}),signal:controller.signal}).then(async r=>{const b=await r.json();if(!r.ok||b.error)throw new Error(b.error?.message||'Aperçu indisponible.');setPreview({items:(b.data?.result?.items||[]).slice(0,8),total:Number(b.data?.result?.total||0)});setError('')}).catch(e=>{if(e?.name!=='AbortError')setError(e instanceof Error?e.message:'Aperçu indisponible.')});return()=>controller.abort()},[category,ref?.entityId,ref?.sourceId])
  return <div className={styles.canonicalRecordField}><UniversalSourcePickerField sourceId={category?'catalog.categories':'homepage.collections'} label={category?'Catégorie Marketplace':'Collection Marketplace'} description={category?'Sélection hiérarchique depuis le catalogue canonique.':'Sélection depuis les collections gouvernées du Marketplace.'} value={value} onChange={next=>onChange(Array.isArray(next)?next[0]||null:next)} legacyValueField={category?'category_key':'collection_key'}/>{ref?<div className={styles.canonicalPreview}><header><strong>{category?'Contenu éligible':'Membres éligibles'}</strong><span>{preview?`${preview.total} résultat(s)`:'Chargement…'}</span></header>{error?<p>{error}</p>:null}{preview?.items.length?<div>{preview.items.map(row=><article key={row.id}>{row.image?.url?<img src={row.image.url} alt=""/>:<i/>}<span><b>{row.title}</b><small>{row.subtitle||String(row.metadata?.availability_status||'Ressource canonique')}</small></span></article>)}</div>:null}</div>:null}</div>
}
