import Link from 'next/link'
import {
  ArrowRight, BadgeCheck, BarChart3, BookOpen, BriefcaseBusiness, Building2, CheckCircle2, ChevronDown,
  ChevronRight, ClipboardCheck, Clock3, FileCheck2, Handshake, HeartHandshake, Layers3, MapPin,
  MessageCircleMore, PackageCheck, Quote, ShieldCheck, Sparkles, Star, Target, Users2, WandSparkles,
} from 'lucide-react'
import type {PublicExperience360,PublicExperienceTruthReport} from '@/angelcare-marketplace/public-experience-authority/types'
import {B2BCommercialConfiguratorClient,type B2BCommercialMode,type B2BConfiguratorOption} from './StudioB2BConversionActions'
import styles from './studio-b2b-world-runtime.module.css'

type Row=Record<string,unknown>
type WorldProps=Record<string,unknown>
const obj=(v:unknown):Row=>v&&typeof v==='object'&&!Array.isArray(v)?v as Row:{}
const arr=(v:unknown):unknown[]=>Array.isArray(v)?v:[]
const text=(v:unknown)=>typeof v==='string'?v.trim():v==null?'':String(v)
const finite=(v:unknown)=>Number.isFinite(Number(v))?Number(v):null
const lower=(v:unknown)=>text(v).toLowerCase()
const bool=(v:unknown)=>typeof v==='boolean'?v:['true','1','yes','oui'].includes(lower(v))
const clean=(v:string)=>v.replaceAll('_',' ').replaceAll('-',' ').replace(/\s+/g,' ').trim()
const proven=(report:PublicExperienceTruthReport,key:string)=>report.decisions.some(row=>row.key===key&&row.state==='PROVEN')
const money=(amount:number|null,currency:string,label='')=>amount===null?(label||'Sur devis'):`${new Intl.NumberFormat('fr-MA',{maximumFractionDigits:2}).format(amount)} ${currency||'MAD'}`
const icons=[BookOpen,Users2,ShieldCheck,ClipboardCheck,BarChart3,Handshake,Layers3,Target]

function worldSections(worldProps:WorldProps){return arr(worldProps.content).map(obj)}
function sectionConfig(worldProps:WorldProps,id:string){return worldSections(worldProps).find(row=>text(row.id).toLowerCase()===id.toLowerCase())||{} as Row}
function sectionEnabled(worldProps:WorldProps,id:string){const row=sectionConfig(worldProps,id);return row.hidden!==true&&row.enabled!==false}
function sourceItems(worldProps:WorldProps,id:string){return arr(sectionConfig(worldProps,id).items).map(obj)}
function domain(data:PublicExperience360){return obj(data.domainExtension)}
function b2b(data:PublicExperience360){return obj(domain(data).b2b)}
function fieldRows(data:PublicExperience360){return data.content.fields.filter(row=>row.formatted||row.value!==null&&row.value!==undefined)}
function hintRows(data:PublicExperience360,hints:string[],limit=20){return fieldRows(data).filter(row=>hints.some(h=>lower(row.key).includes(h)||lower(row.label).includes(h))).slice(0,limit)}
function fieldRow(data:PublicExperience360,hints:string[]){return hintRows(data,hints,1)[0]||null}
function fieldText(data:PublicExperience360,hints:string[]){const row=fieldRow(data,hints);return row?row.formatted||text(row.value):''}
function fieldNumber(data:PublicExperience360,hints:string[]){const row=fieldRow(data,hints);return row?finite(row.value??row.formatted):null}
function fieldBoolean(data:PublicExperience360,hints:string[]){const row=fieldRow(data,hints);return row?bool(row.value??row.formatted):false}
function values(v:unknown){if(Array.isArray(v))return v.flatMap(item=>typeof item==='object'&&item!==null?Object.values(item as Row).map(text):[text(item)]).filter(Boolean);if(v&&typeof v==='object')return Object.values(v as Row).map(text).filter(Boolean);const s=text(v);return s?s.split(/[,;|]/).map(x=>x.trim()).filter(Boolean):[]}
function fieldValues(data:PublicExperience360,hints:string[]){const row=fieldRow(data,hints);return row?values(row.value).length?values(row.value):values(row.formatted):[]}
function extensionRows(value:unknown){return arr(value).map(obj)}
function unique(rows:string[]){return [...new Set(rows.filter(Boolean))]}
function doctrineLabel(key:string){const map:Record<string,string>={'school-managed-programme':'Écoles & crèches','school-staff-reinforcement':'Renfort d’équipes','hospitality-kids-programme':'Hospitality','corporate-childcare-benefit':'Corporate benefit','health-adjacent-programme':'Health partner','event-venue-programme':'Événementiel','partner-os-plan':'Partner OS','quality-check-assessment':'Quality Check 360','custom-managed-solution':'Solution sur mesure'};return map[key]||clean(key)}
function pricingMode(data:PublicExperience360):B2BCommercialMode{const raw=lower(fieldText(data,['pricing_mode'])||data.pricing.mode);if(raw.includes('per_site'))return'per_site';if(raw.includes('per_child'))return'per_child';if(raw.includes('per_employee'))return'per_employee';if(raw.includes('per_event'))return'per_event';if(raw.includes('subscription')||raw.includes('recurr'))return'subscription';if(raw.includes('volume'))return'volume_pricing';if(raw.includes('fixed'))return'fixed';if(raw.includes('starting'))return'starting_from';if(raw.includes('configured'))return'configured_estimate';if(raw.includes('quote'))return'quote_only';return data.pricing.amount===null?'quote_only':'starting_from'}
function publicAction(data:PublicExperience360,id:string){return data.actions.some(row=>row.actionId===id&&row.available)}
function mainMedia(data:PublicExperience360){return data.media[0]?.url||null}

function options(rows:string[]):B2BConfiguratorOption[]{return unique(rows).map(value=>({value,label:clean(value)}))}
function organisationOptions(data:PublicExperience360){return options(fieldValues(data,['organization_type','organisation_type']))}
function territoryOptions(data:PublicExperience360){return options(fieldValues(data,['territory_codes','city','ville','region','zone']))}
function moduleOptions(data:PublicExperience360){return options(fieldValues(data,['programme_modules','required_components','included_modules','benefit_models','assessment_scope','solution_scope','add_on_keys']))}
function capacityConfig(data:PublicExperience360){const doctrine=data.classification.doctrineKey;let hints=['children_capacity','expected_child_volume','beneficiary_volume'];let label='Bénéficiaires';if(doctrine==='school-staff-reinforcement'){hints=['personnel_count'];label='Personnel'}else if(doctrine==='corporate-childcare-benefit'){hints=['employee_population'];label='Employés'}else if(doctrine==='hospitality-kids-programme'){hints=['expected_child_volume','property_size_rooms'];label='Enfants / volume'}else if(doctrine==='health-adjacent-programme'){hints=['expected_family_volume'];label='Familles'}else if(doctrine==='event-venue-programme'){hints=['expected_child_volume','expected_attendance'];label='Participants'}else if(doctrine==='partner-os-plan'){hints=['user_limit'];label='Utilisateurs'}else if(doctrine==='quality-check-assessment'){hints=['site_count'];label='Sites évalués'}
 const value=fieldNumber(data,hints)??1;return{label,defaultValue:Math.max(1,Math.round(value)),min:1,max:Math.max(10,Math.ceil(value*4)||1000),step:value>=100?10:value>=20?5:1}}
function commercialAmount(data:PublicExperience360,truth:PublicExperienceTruthReport){if(!proven(truth,'pricing'))return null;const recurring=fieldNumber(data,['recurring_fee_dh']);const starting=fieldNumber(data,['starting_price_dh']);return data.pricing.amount??recurring??starting}
function trustClaims(data:PublicExperience360){return data.trust.claims.filter(row=>row.status==='verified'||row.status==='active'||Boolean(row.evidenceReference)).map(row=>row.label).filter(Boolean)}
function metricRows(data:PublicExperience360){const rows=hintRows(data,['impact','result','beneficiary','partner','satisfaction','compliance','experience','capacity','site'],12);return rows.map(row=>({label:row.label,value:row.formatted||text(row.value)})).filter(r=>r.value).slice(0,6)}
function includedRows(data:PublicExperience360){const hints=['programme_modules','required_components','included_modules','benefit_models','covered_service_keys','assessment_scope','solution_scope','equipment_requirements','staffing_requirements','support_level','report_type'];const rows=hintRows(data,hints,18);const flat=rows.flatMap(row=>{const vals=values(row.value);return vals.length?vals.map(v=>({title:clean(v),copy:row.label})):row.formatted?[{title:row.formatted,copy:row.label}]:[]});return flat.slice(0,8)}
function fitRows(data:PublicExperience360){const ext=extensionRows(b2b(data).organisationFit);return ext.map(row=>({label:clean(text(row.key||row.label)),value:text(row.value||row.formatted||row.description)})).filter(r=>r.label&&r.value).slice(0,8)}
function diagnosticRows(data:PublicExperience360){const ext=extensionRows(b2b(data).diagnostic);return ext.map(row=>({label:clean(text(row.key||row.label)),value:text(row.value||row.formatted||row.description)})).filter(r=>r.label&&r.value).slice(0,8)}
function deploymentRows(data:PublicExperience360,worldProps:WorldProps){const ext=extensionRows(b2b(data).deploymentModel).map(row=>({title:clean(text(row.key||row.label||row.title)),copy:text(row.value||row.formatted||row.description)})).filter(r=>r.title&&r.copy);if(ext.length)return ext.slice(0,6);return arr(worldProps.deploymentFallback).map(obj).map(row=>({title:text(row.title),copy:text(row.copy)})).filter(r=>r.title).slice(0,6)}
function programmeRows(data:PublicExperience360,worldProps:WorldProps){const source=sourceItems(worldProps,'b06-programme');if(source.length)return source.slice(0,6);const rel=extensionRows(b2b(data).programmes);if(rel.length)return rel.slice(0,6);return []}
function relatedRows(data:PublicExperience360,worldProps:WorldProps){const source=sourceItems(worldProps,'b12-related');if(source.length)return source.slice(0,6);return data.recommendations.slice(0,6).map(row=>({id:row.id,slug:row.slug,title:row.name,price:row.priceAmount,currency:row.currency,mediaUrl:row.mediaUrl}))}
function faqRows(worldProps:WorldProps){return arr(worldProps.faqItems).map(obj).map(row=>({q:text(row.q||row.question||row.title),a:text(row.a||row.answer||row.copy)})).filter(row=>row.q&&row.a).slice(0,8)}

function Breadcrumb({data}:{data:PublicExperience360}){const l=data.classification.locale;return <nav className={styles.breadcrumb} data-ac-b2b-section="B00" aria-label="Fil d’Ariane"><Link href={`/angelcare-marketplace/${l}/marketplace`}>Accueil</Link><ChevronRight/><span>Solutions B2B</span><ChevronRight/><span>{doctrineLabel(data.classification.doctrineKey)}</span><ChevronRight/><strong>{data.identity.name}</strong></nav>}
function Identity({data,truth}:{data:PublicExperience360;truth:PublicExperienceTruthReport}){const trust=trustClaims(data).slice(0,4);return <div className={styles.identity}><div className={styles.badges}><span>B2B Institutionnel</span><b>{doctrineLabel(data.classification.doctrineKey)}</b></div><h1>{data.identity.name}</h1><p>{data.identity.shortDescription||data.identity.description}</p>{trust.length?<div className={styles.microProof}>{trust.map(label=><span key={label}><BadgeCheck/>{label}</span>)}</div>:null}<div className={styles.heroActions}><a href={`#b2b-commercial-panel`}>Demander un devis<ArrowRight/></a><Link href={`/angelcare-marketplace/${data.classification.locale}/account/support`}>Parler à un conseiller</Link></div></div>}
function Media({data}:{data:PublicExperience360}){const media=mainMedia(data);return <div className={styles.mediaStage}>{media?<img src={media} alt={data.media[0]?.alt||data.identity.name}/>:<div className={styles.mediaFallback}><Building2/><span>{doctrineLabel(data.classification.doctrineKey)}</span></div>}<div className={styles.mediaAtmosphere}/></div>}
function Conversion({data,truth}:{data:PublicExperience360;truth:PublicExperienceTruthReport}){const mode=pricingMode(data),capacity=capacityConfig(data),siteMin=Math.max(1,Math.round(fieldNumber(data,['site_minimum'])??1)),siteMax=Math.max(siteMin,Math.round(fieldNumber(data,['site_maximum'])??Math.max(4,siteMin))),siteDefault=Math.max(siteMin,Math.round(fieldNumber(data,['site_count'])??siteMin)),amount=commercialAmount(data,truth),billingPeriod=fieldText(data,['billing_period','company_billing_cycle','billing_basis']),quoteRequired=fieldBoolean(data,['quotation_required'])||mode==='quote_only',lead=fieldText(data,['implementation_lead_time_days']);return <div id="b2b-commercial-panel"><B2BCommercialConfiguratorClient locale={data.classification.locale} slug={data.identity.slug} doctrine={data.classification.doctrineKey} currency={data.pricing.currency||'MAD'} amount={amount} amountLabel={data.pricing.label||'Sur devis'} pricingMode={mode} billingPeriod={billingPeriod} recurringFee={proven(truth,'pricing')?fieldNumber(data,['recurring_fee_dh']):null} setupFee={proven(truth,'pricing')?fieldNumber(data,['setup_fee_dh']):null} quotationRequired={quoteRequired} quoteEnabled={publicAction(data,'quotation.start')||quoteRequired} requestEnabled={publicAction(data,'b2b.request')||publicAction(data,'inquiry.submit')} subscriptionEnabled={publicAction(data,'subscription.start')} organizationType={fieldText(data,['organization_type','organisation_type'])} organizationOptions={organisationOptions(data)} capacityLabel={capacity.label} capacityDefault={capacity.defaultValue} capacityMin={capacity.min} capacityMax={capacity.max} capacityStep={capacity.step} siteDefault={siteDefault} siteMin={siteMin} siteMax={siteMax} territoryDefault={territoryOptions(data)[0]?.value||''} territoryOptions={territoryOptions(data)} moduleOptions={moduleOptions(data)} implementationLeadTime={lead?`${lead}${/^\d+$/.test(lead)?' jours':''}`:''}/></div>}
function TrustRail({data}:{data:PublicExperience360}){const claims=trustClaims(data).slice(0,5);const extras=hintRows(data,['implementation_lead_time_days','reporting_frequency','support_level','replacement_sla_hours'],4).map(row=>row.formatted||text(row.value)).filter(Boolean);const rows=unique([...claims,...extras]).slice(0,5);if(!rows.length)return null;return <section className={styles.trustRail} data-ac-b2b-section="B04">{rows.map((label,index)=>{const I=icons[index%icons.length];return <div key={`${label}:${index}`}><I/><span>{label}</span></div>})}</section>}
function Included({data}:{data:PublicExperience360}){const rows=includedRows(data);if(!rows.length)return null;return <section className={styles.section} data-ac-b2b-section="B05"><header><span>CE QUI EST INCLUS</span><h2>Une solution structurée autour de votre besoin.</h2><p>Les modules affichés proviennent des champs publics canoniques de cette offre.</p></header><div className={styles.includedGrid}>{rows.map((row,index)=>{const I=icons[index%icons.length];return <article key={`${row.title}:${index}`}><div><I/></div><strong>{row.title}</strong><small>{row.copy}</small></article>})}</div></section>}
function Programme({data,worldProps}:{data:PublicExperience360;worldProps:WorldProps}){const rows=programmeRows(data,worldProps);if(!rows.length)return null;return <section className={styles.section} data-ac-b2b-section="B06"><header><span>ARCHITECTURE DE LA SOLUTION</span><h2>Des composantes claires, combinées selon votre contexte.</h2></header><div className={styles.programmeGrid}>{rows.map((row,index)=>{const r=obj(row),title=text(r.title||r.name||r.label)||`Module ${index+1}`,copy=text(r.description||r.copy||r.body),media=text(r.mediaUrl||r.imageUrl);return <article key={`${title}:${index}`}>{media?<img src={media} alt={title} loading="lazy"/>:<div className={styles.programmeFallback}><WandSparkles/></div>}<div><span>{String(index+1).padStart(2,'0')}</span><strong>{title}</strong>{copy?<p>{copy}</p>:null}</div></article>})}</div></section>}
function Deployment({data,worldProps}:{data:PublicExperience360;worldProps:WorldProps}){const rows=deploymentRows(data,worldProps);if(!rows.length)return null;return <section className={`${styles.section} ${styles.deploymentSection}`} data-ac-b2b-section="B07"><header><span>DÉPLOIEMENT</span><h2>Une mise en place pilotée, visible et progressive.</h2><p>{fieldText(data,['implementation_lead_time_days'])?`Délai indicatif canonique : ${fieldText(data,['implementation_lead_time_days'])} jours.`:'Le planning précis est confirmé pendant le cadrage.'}</p></header><div className={styles.timeline}>{rows.map((row,index)=><article key={`${row.title}:${index}`}><b>{index+1}</b><div><strong>{row.title}</strong>{row.copy?<p>{row.copy}</p>:null}</div></article>)}</div></section>}
function FitDiagnostic({data}:{data:PublicExperience360}){const fit=fitRows(data),diag=diagnosticRows(data);if(!fit.length&&!diag.length)return null;return <section className={styles.dualSection} data-ac-b2b-section="B08"><article><span>FIT ORGANISATIONNEL</span><h2>Pour quel contexte cette solution est-elle conçue ?</h2>{fit.length?<div className={styles.factList}>{fit.map(row=><div key={row.label}><CheckCircle2/><span><small>{row.label}</small><strong>{row.value}</strong></span></div>)}</div>:null}</article><article><span>DIAGNOSTIC</span><h2>Les éléments qui cadrent la recommandation.</h2>{diag.length?<div className={styles.factList}>{diag.map(row=><div key={row.label}><ClipboardCheck/><span><small>{row.label}</small><strong>{row.value}</strong></span></div>)}</div>:<p>Le diagnostic est déclenché par le parcours B2B canonique quand la solution le requiert.</p>}</article></section>}
function Proof({data,truth}:{data:PublicExperience360;truth:PublicExperienceTruthReport}){const metrics=metricRows(data),claims=trustClaims(data).slice(0,6),rating=proven(truth,'rating')?data.reviews.rating:null;if(!metrics.length&&!claims.length&&rating===null)return null;return <section className={`${styles.section} ${styles.proofSection}`} data-ac-b2b-section="B09"><header><span>RÉSULTATS & PREUVES</span><h2>Uniquement les éléments soutenus par une autorité publique.</h2></header>{metrics.length?<div className={styles.metrics}>{metrics.map((row,index)=><div key={`${row.label}:${index}`}><strong>{row.value}</strong><small>{row.label}</small></div>)}</div>:null}<div className={styles.proofBody}>{claims.length?<div className={styles.claims}>{claims.map(row=><span key={row}><ShieldCheck/>{row}</span>)}</div>:null}{rating!==null?<div className={styles.rating}><Star/><strong>{rating.toFixed(1)}</strong><span>{data.reviews.count||0} avis</span></div>:null}</div></section>}
function CommercialTerms({data,truth}:{data:PublicExperience360;truth:PublicExperienceTruthReport}){const rows=hintRows(data,['pricing_mode','starting_price_dh','quotation_required','implementation_lead_time_days','contract_duration_months','billing_basis','billing_model','company_billing_cycle','support_level','trial_days','duration_days'],12).filter(row=>!row.key.includes('starting_price')||proven(truth,'pricing'));if(!rows.length)return null;return <section className={styles.section} data-ac-b2b-section="B10"><header><span>CADRE COMMERCIAL</span><h2>Les paramètres utiles avant devis ou activation.</h2></header><div className={styles.termGrid}>{rows.map(row=><div key={row.key}><small>{row.label}</small><strong>{row.formatted||text(row.value)}</strong></div>)}</div><p className={styles.truthNote}><ShieldCheck/> Les montants, remises, capacités et garanties ne sont jamais inventés par le thème.</p></section>}
function FAQ({worldProps}:{worldProps:WorldProps}){const rows=faqRows(worldProps);if(!rows.length)return null;return <section className={styles.section} data-ac-b2b-section="B11"><header><span>FAQ</span><h2>Questions fréquentes sur la mise en place.</h2></header><div className={styles.faqList}>{rows.map((row,index)=><details key={`${row.q}:${index}`}><summary>{row.q}<ChevronDown/></summary><p>{row.a}</p></details>)}</div></section>}
function Related({data,worldProps}:{data:PublicExperience360;worldProps:WorldProps}){const rows=relatedRows(data,worldProps);if(!rows.length)return null;const l=data.classification.locale;return <section className={styles.section} data-ac-b2b-section="B12"><header><span>SOLUTIONS ASSOCIÉES</span><h2>Construisez un dispositif institutionnel cohérent.</h2></header><div className={styles.relatedRail}>{rows.map((row,index)=>{const r=obj(row),slug=text(r.slug),title=text(r.title||r.name||r.label)||`Solution ${index+1}`,media=text(r.mediaUrl||r.imageUrl),price=finite(r.price||r.priceAmount);return <article key={`${title}:${index}`}>{slug?<Link href={`/angelcare-marketplace/${l}/marketplace/${encodeURIComponent(slug)}`}>{media?<img src={media} alt={title} loading="lazy"/>:<div className={styles.relatedFallback}><BriefcaseBusiness/></div>}<div><strong>{title}</strong>{price!==null?<small>{money(price,text(r.currency)||'MAD')}</small>:null}<span>Découvrir<ArrowRight/></span></div></Link>:<div><div className={styles.relatedFallback}><BriefcaseBusiness/></div><strong>{title}</strong></div>}</article>})}</div></section>}
function FinalConversion({data}:{data:PublicExperience360}){const l=data.classification.locale;return <section className={styles.finalBand} data-ac-b2b-section="B13"><div><span>VOTRE PROJET</span><h2>Passez du besoin institutionnel à une proposition structurée.</h2><p>Diagnostic, devis et handover restent gouvernés par les workflows B2B AngelCare.</p></div><div><a href={`/angelcare-marketplace/${l}/quotation/${encodeURIComponent(data.identity.slug)}`}>Demander un devis<ArrowRight/></a><Link href={`/angelcare-marketplace/${l}/account/support`}>Parler à un conseiller</Link></div></section>}

export async function StudioB2BWorldRuntime({data,truthReport,worldProps}:{data:PublicExperience360;truthReport:PublicExperienceTruthReport;worldProps:WorldProps}){
 if(data.classification.masterDomain!=='b2b_institutional')return null
 const worldKey=text(worldProps.worldKey)||'ac.b2b.solution.immersive.2030.v2'
 return <main className={styles.root} dir={data.classification.locale==='ar'?'rtl':'ltr'} data-ac-public-experience="studio-b2b-semantic-runtime-v2" data-ac-b2b-world-key={worldKey} data-ac-b2b-doctrine={data.classification.doctrineKey}>
  <div className={styles.shell}>
   {sectionEnabled(worldProps,'b00-breadcrumb')?<Breadcrumb data={data}/>:null}
   <section className={styles.heroGrid} data-ac-b2b-section="B01" data-ac-b2b-decision-triad>
    {sectionEnabled(worldProps,'b01-identity')?<Identity data={data} truth={truthReport}/>:null}
    {sectionEnabled(worldProps,'b02-media')?<Media data={data}/>:null}
    {sectionEnabled(worldProps,'b03-conversion')?<Conversion data={data} truth={truthReport}/>:null}
   </section>
   {sectionEnabled(worldProps,'b04-trust')?<TrustRail data={data}/>:null}
   {sectionEnabled(worldProps,'b05-included')?<Included data={data}/>:null}
   {sectionEnabled(worldProps,'b06-programme')?<Programme data={data} worldProps={worldProps}/>:null}
   {sectionEnabled(worldProps,'b07-deployment')?<Deployment data={data} worldProps={worldProps}/>:null}
   {sectionEnabled(worldProps,'b08-fit-diagnostic')?<FitDiagnostic data={data}/>:null}
   {sectionEnabled(worldProps,'b09-proof')?<Proof data={data} truth={truthReport}/>:null}
   {sectionEnabled(worldProps,'b10-commercial')?<CommercialTerms data={data} truth={truthReport}/>:null}
   {sectionEnabled(worldProps,'b11-faq')?<FAQ worldProps={worldProps}/>:null}
   {sectionEnabled(worldProps,'b12-related')?<Related data={data} worldProps={worldProps}/>:null}
   {sectionEnabled(worldProps,'b13-final')?<FinalConversion data={data}/>:null}
  </div>
 </main>
}
