'use client'

import { Puck, useGetPuck, type Data } from '@puckeditor/core'
import Link from 'next/link'
import '@puckeditor/core/puck.css'
import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties, type PointerEvent as ReactPointerEvent } from 'react'
import { ExternalLink, Import, Maximize2, Monitor, PanelLeftOpen, PanelRightOpen, Rocket, Save, Send, ShieldCheck, Smartphone, Tablet, X } from 'lucide-react'
import type { CmsPage } from '@/angelcare-marketplace/experience-builder/types'
import { createAngelCarePuckConfig } from '../puck-config'
import type { StudioPickerData } from '../types'
import { PuckOperatorTools } from './PuckOperatorTools'
import { StudioGovernancePanel } from './StudioGovernancePanel'
import { StudioReleasePanel } from './StudioReleasePanel'
import { UniversalImportWorkbench } from './UniversalImportWorkbench'
import styles from './studio-workspace.module.css'

type ApiEnvelope<T>={data?:T;error?:{message?:string;code?:string};requestId?:string}
async function api<T>(url:string,init?:RequestInit):Promise<{data:T;requestId:string}>{const response=await fetch(url,init);const body=await response.json() as ApiEnvelope<T>;if(!response.ok||body.error){const e=new Error(body.error?.message||'Action impossible') as Error&{requestId?:string};e.requestId=body.requestId;throw e}return {data:body.data as T,requestId:body.requestId||''}}

type SyncRequest={sequence:number;data:Data;status:string}
function ExternalDataSync({request,onApplied}:{request:SyncRequest|null;onApplied:(request:SyncRequest)=>void}){const getPuck=useGetPuck(),applied=useRef(0);useEffect(()=>{if(!request||request.sequence===applied.current)return;applied.current=request.sequence;getPuck().dispatch({type:'setData',data:request.data,recordHistory:true});onApplied(request)},[getPuck,onApplied,request]);return null}

export function UniversalExperienceStudio({page,initialData,pickers,canPreview,canPublish}:{page:CmsPage;initialData:Data;pickers:StudioPickerData;canPreview:boolean;canPublish:boolean}){
 const [data,setData]=useState<Data>(initialData),[status,setStatus]=useState('Prêt'),[tone,setTone]=useState<'ready'|'busy'|'error'>('ready'),[toast,setToast]=useState<{title:string;message:string;requestId?:string;tone?:'error'}|null>(null),[importOpen,setImportOpen]=useState(false),[governanceOpen,setGovernanceOpen]=useState(false),[releaseOpen,setReleaseOpen]=useState(false),[leftOpen,setLeftOpen]=useState(true),[rightOpen,setRightOpen]=useState(true),[leftWidth,setLeftWidth]=useState(330),[rightWidth,setRightWidth]=useState(380),[device,setDevice]=useState<'mobile'|'tablet'|'desktop'|'wide'>('desktop'),[fullscreen,setFullscreen]=useState(false),[leftMode,setLeftMode]=useState<'components'|'outline'>('components'),[sync,setSync]=useState<SyncRequest|null>(null)
 const publishReady=canPublish&&['approved','scheduled','published'].includes(page.status)
 const config=useMemo(()=>createAngelCarePuckConfig(pickers),[pickers]),saveTimer=useRef<ReturnType<typeof setTimeout>|null>(null),sequence=useRef(0),saving=useRef(false)
 const setProgress=(message:string,state:'ready'|'busy'|'error'='ready')=>{setStatus(message);setTone(state)}
 const persist=useCallback(async(next:Data,reason='Autosave Puck Studio')=>{if(saving.current)return;saving.current=true;setProgress('Enregistrement…','busy');try{const result=await api<{data:Data}>(`/api/angelcare-marketplace/cms/studio/pages/${page.id}/draft`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({data:next,reason})});setProgress('Enregistré','ready');return result.data}catch(error){const e=error as Error&{requestId?:string};setProgress('Erreur d’enregistrement','error');setToast({title:'Enregistrement impossible',message:e.message,requestId:e.requestId,tone:'error'});throw error}finally{saving.current=false}},[page.id])
 const schedule=useCallback((next:Data)=>{if(saveTimer.current)clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>{void persist(next).catch(()=>{})},900)},[persist])
 useEffect(()=>()=>{if(saveTimer.current)clearTimeout(saveTimer.current)},[])
 const applyImported=useCallback(async(next:Data,summary:string)=>{await persist(next,summary);setData(next);sequence.current+=1;setSync({sequence:sequence.current,data:next,status:'Import appliqué'});setToast({title:'Import appliqué',message:summary})},[persist])
 const preview=async()=>{setProgress('Préparation de l’aperçu…','busy');try{await persist(data,'Sauvegarde avant aperçu');const result=await api<{url:string}>(`/api/angelcare-marketplace/cms/studio/pages/${page.id}/preview`,{method:'POST'});window.open(result.data.url,'_blank','noopener,noreferrer');setProgress('Aperçu sécurisé prêt','ready')}catch(error){const e=error as Error&{requestId?:string};setProgress('Aperçu indisponible','error');setToast({title:'Aperçu impossible',message:e.message,requestId:e.requestId,tone:'error'})}}
 const publish=async(next=data)=>{setProgress('Publication…','busy');try{await persist(next,'Sauvegarde avant publication');const result=await api<{status:string}>(`/api/angelcare-marketplace/cms/studio/pages/${page.id}/publish`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reason:'Publication depuis AngelCare Marketplace Studio'})});setProgress('Publié','ready');setToast({title:'Publication terminée',message:`Page ${result.data.status}.`})}catch(error){const e=error as Error&{requestId?:string};setProgress('Publication bloquée','error');setToast({title:'Publication impossible',message:e.message,requestId:e.requestId,tone:'error'})}}
 const resize=useCallback((side:'left'|'right',event:ReactPointerEvent<HTMLButtonElement>)=>{event.preventDefault();const start=event.clientX,base=side==='left'?leftWidth:rightWidth;const move=(e:PointerEvent)=>{const delta=e.clientX-start;if(side==='left'){setLeftWidth(Math.max(270,Math.min(620,base+delta)))}else{setRightWidth(Math.max(320,Math.min(760,base-delta)))}};const stop=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',stop)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',stop)},[leftWidth,rightWidth])
 const canvasWidth=device==='mobile'?390:device==='tablet'?768:device==='wide'?1440:1280
 return <main className={styles.shell}>
  <section className={styles.hero}><div><span>ANGELCARE MARKETPLACE STUDIO · PUCK 0.23</span><h1>{page.title}</h1><p>Canvas, contenu, import universel, aperçu sécurisé, versions et publication sur une seule autorité.</p></div><div className={styles.heroMeta}><span>{page.locale.toUpperCase()}</span><span>{page.status}</span><span>/{page.slug}</span><a href={`/angelcare-marketplace/${page.locale}/${page.slug}`} target="_blank" rel="noreferrer">Public <ExternalLink size={11}/></a></div></section>
  <Puck config={config} data={data} onChange={next=>{setData(next);schedule(next)}} onPublish={publishReady&&page.status!=='published'?async next=>{setData(next);await publish(next)}:undefined} dnd={{behavior:'auto'}} iframe={{enabled:false}} height="100%">
  <div className={styles.command}><div className={styles.commandLeft}><div className={styles.status} data-state={tone}><i/>{status}</div><div className={styles.deviceGroup}>{(['mobile','tablet','desktop','wide'] as const).map(key=><button key={key} data-active={device===key} onClick={()=>setDevice(key)} title={key}>{key==='mobile'?<Smartphone size={13}/>:key==='tablet'?<Tablet size={13}/>:<Monitor size={13}/>}</button>)}</div><button data-active={leftOpen} onClick={()=>setLeftOpen(v=>!v)}><PanelLeftOpen size={13}/> Bibliothèque</button><button data-active={rightOpen} onClick={()=>setRightOpen(v=>!v)}><PanelRightOpen size={13}/> Inspecteur</button><button data-active={fullscreen} onClick={()=>setFullscreen(v=>!v)}><Maximize2 size={13}/> Focus</button><button onClick={()=>setImportOpen(true)}><Import size={13}/> Importer</button><button onClick={()=>setGovernanceOpen(true)}><ShieldCheck size={13}/> Gouvernance</button><button onClick={()=>setReleaseOpen(true)}><Rocket size={13}/> Release</button><Link className={styles.commandLink} href="/angelcare-marketplace/admin/homepage/composer">Thème</Link><Link className={styles.commandLink} href="/angelcare-marketplace/admin/configuration/web-presence">Web Presence</Link><Link className={styles.commandLink} href="/angelcare-marketplace/admin/navigation">Navigation</Link><Link className={styles.commandLink} href="/angelcare-marketplace/admin/footer-studio">Footer</Link><Link className={styles.commandLink} href="/angelcare-marketplace/admin/experience/pages">Pages</Link></div><div className={styles.commandRight}><PuckOperatorTools/><button onClick={()=>void persist(data,'Enregistrement manuel')}><Save size={13}/> Enregistrer</button>{canPreview?<button onClick={()=>void preview()}><ExternalLink size={13}/> Prévisualiser</button>:null}{canPublish?<button data-publish="true" disabled={!publishReady||page.status==='published'} title={publishReady?'Publication gouvernée':'La page doit être approuvée ou planifiée avant publication.'} onClick={()=>void publish()}><Send size={13}/> {page.status==='published'?'Publié':publishReady?'Publier':'Validation requise'}</button>:null}</div></div>
  <div className={styles.frame} data-fullscreen={String(fullscreen)}><ExternalDataSync request={sync} onApplied={request=>{setData(request.data);setProgress(request.status,'ready')}}/><div className={styles.grid} style={{'--left':leftOpen?`${leftWidth}px`:'0px','--right':rightOpen?`${rightWidth}px`:'0px','--lh':leftOpen?'8px':'0px','--rh':rightOpen?'8px':'0px'} as CSSProperties}><aside className={styles.rail} data-side="left" style={{display:leftOpen?'flex':'none'}}><div className={styles.railHead}><span className={styles.panelKicker}>Bibliothèque · {leftWidth}px</span><strong>{leftMode==='components'?'Blocs AngelCare':'Structure & calques'}</strong><div className={styles.tabs}><button data-active={leftMode==='components'} onClick={()=>setLeftMode('components')}>Blocs</button><button data-active={leftMode==='outline'} onClick={()=>setLeftMode('outline')}>Structure</button></div></div><div className={styles.railBody}>{leftMode==='components'?<Puck.Components/>:<Puck.Outline/>}</div></aside><button className={styles.resize} style={{display:leftOpen?'block':'none'}} onPointerDown={event=>resize('left',event)} aria-label="Redimensionner la bibliothèque"/><section className={styles.canvas}><div className={styles.canvasHead}><strong>Canvas live · {Array.isArray(data.content)?data.content.length:0} blocs racine</strong><span>{canvasWidth}px · autosave</span></div><div className={styles.viewport}><div className={styles.stage} style={{width:canvasWidth,maxWidth:'100%'}}><Puck.Preview id="angelcare-marketplace-studio-canvas"/><div className={styles.endcap}>Fin de page · glissez un bloc depuis la Bibliothèque pour continuer.</div></div></div></section><button className={styles.resize} style={{display:rightOpen?'block':'none'}} onPointerDown={event=>resize('right',event)} aria-label="Redimensionner l’inspecteur"/><aside className={styles.rail} data-side="right" style={{display:rightOpen?'flex':'none'}}><div className={styles.railHead}><span className={styles.panelKicker}>Inspecteur · {rightWidth}px</span><strong>Contenu · Design · Responsive · Données</strong><small>Les modifications restent localisées au composant sélectionné.</small></div><div className={styles.railBody}><Puck.Fields wrapFields={false}/></div></aside></div></div>
  </Puck>
  <UniversalImportWorkbench open={importOpen} currentData={data} pickers={pickers} onClose={()=>setImportOpen(false)} onApply={applyImported}/>{toast?<div className={styles.toast} data-tone={toast.tone||'ready'}><button className={styles.srOnly} onClick={()=>setToast(null)}>Fermer</button><strong>{toast.title}</strong><p>{toast.message}</p>{toast.requestId?<code>Réf. {toast.requestId}</code>:null}<button onClick={()=>setToast(null)} style={{position:'absolute',right:8,top:8,border:0,background:'transparent'}}><X size={14}/></button></div>:null}
   {governanceOpen?<StudioGovernancePanel pageId={page.id} onClose={()=>setGovernanceOpen(false)}/>:null}
   {releaseOpen?<StudioReleasePanel onClose={()=>setReleaseOpen(false)}/>:null}
</main>
}
