'use client'

import { Puck, useGetPuck, type Data } from '@puckeditor/core'
import Link from 'next/link'
import '@puckeditor/core/puck.css'
import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties, type KeyboardEvent as ReactKeyboardEvent, type PointerEvent as ReactPointerEvent } from 'react'
import { Activity, BadgeCheck, Code2, Copy, Database, Download, ExternalLink, FileJson2, GripVertical, Images, Import, LayoutTemplate, Maximize2, Monitor, MoreHorizontal, PanelLeftOpen, PanelRightOpen, Rocket, Save, Search, Send, ShieldCheck, Smartphone, Tablet, Upload, X } from 'lucide-react'
import type { CmsPage } from '@/angelcare-marketplace/experience-builder/types'
import { createAngelCarePuckConfig } from '../puck-config'
import type { StudioPickerData } from '../types'
import { studioBlockExperienceByLabel, studioBlockFamilies, studioBlockSearchMatches } from '../block-experience'
import { STUDIO_PAGE_JSON_MAX_BYTES, studioPageJsonEnvelope, validateStudioPageJson } from '../page-json'
import { PuckOperatorTools } from './PuckOperatorTools'
import { StudioMaterializationProvider,type StudioMaterializationState } from './StudioMaterializationContext'
import { StudioInspector2031 } from './StudioInspector2031'
import { StudioDocumentDoctorPanel,type StudioServerPreflight } from './StudioDocumentDoctorPanel'
import { StudioHomepageHealthPanel } from './StudioHomepageHealthPanel'
import { diagnoseStudioDocument } from '../document-doctor'
import { StudioGovernancePanel } from './StudioGovernancePanel'
import { StudioReleasePanel } from './StudioReleasePanel'
import { UniversalImportWorkbench } from './UniversalImportWorkbench'
import { HomepageProMaxLibrary } from '@/angelcare-marketplace/studio-homepage-pro-max/components/HomepageProMaxLibrary'
import { StudioTemplateAssignmentPanel } from '@/angelcare-marketplace/studio-template-assignment/components/StudioTemplateAssignmentPanel'
import { StudioLiveBindingInspector } from '@/angelcare-marketplace/studio-live-binding/components/StudioLiveBindingInspector'
import { StudioDynamicSourceInspector } from '@/angelcare-marketplace/studio-dynamic-source/components/StudioDynamicSourceInspector'
import { StudioTrustInspector } from '@/angelcare-marketplace/studio-trust-inspector/components/StudioTrustInspector'
import { StudioPolicyInspector } from '@/angelcare-marketplace/studio-governance-engine/components/StudioPolicyInspector'
import { StudioImpactInspector } from '@/angelcare-marketplace/studio-dependency-invalidation/components/StudioImpactInspector'
import { StudioContractSaturationInspector } from '@/angelcare-marketplace/studio-contract-saturation/components/StudioContractSaturationInspector'
import styles from './studio-workspace.module.css'

type ApiEnvelope<T>={data?:T;error?:{message?:string;code?:string;fieldErrors?:Record<string,string[]>};requestId?:string}
async function api<T>(url:string,init?:RequestInit):Promise<{data:T;requestId:string}>{const response=await fetch(url,init);const body=await response.json() as ApiEnvelope<T>;if(!response.ok||body.error){const field=Object.entries(body.error?.fieldErrors||{}).flatMap(([name,messages])=>messages.map(message=>`${name}: ${message}`))[0];const e=new Error(field||body.error?.message||'Action impossible') as Error&{requestId?:string;code?:string;fieldErrors?:Record<string,string[]>};e.requestId=body.requestId;e.code=body.error?.code;e.fieldErrors=body.error?.fieldErrors;throw e}return {data:body.data as T,requestId:body.requestId||''}}

type SyncRequest={sequence:number;data:Data;status:string}
function ExternalDataSync({request,onApplied}:{request:SyncRequest|null;onApplied:(request:SyncRequest)=>void}){const getPuck=useGetPuck(),applied=useRef(0);useEffect(()=>{if(!request||request.sequence===applied.current)return;applied.current=request.sequence;getPuck().dispatch({type:'setData',data:request.data,recordHistory:true});onApplied(request)},[getPuck,onApplied,request]);return null}

const clampRail=(side:'left'|'right',value:number)=>side==='left'?Math.max(280,Math.min(480,value)):Math.max(340,Math.min(560,value))

export function UniversalExperienceStudio({page,initialData,pickers,canPreview,canPublish}:{page:CmsPage;initialData:Data;pickers:StudioPickerData;canPreview:boolean;canPublish:boolean}){
 const [data,setData]=useState<Data>(initialData)
 const [status,setStatus]=useState('Prêt'),[tone,setTone]=useState<'ready'|'busy'|'error'>('ready')
 const [toast,setToast]=useState<{title:string;message:string;requestId?:string;tone?:'error'}|null>(null)
 const [importOpen,setImportOpen]=useState(false),[governanceOpen,setGovernanceOpen]=useState(false),[releaseOpen,setReleaseOpen]=useState(false),[templateAssignmentOpen,setTemplateAssignmentOpen]=useState(false),[liveBindingOpen,setLiveBindingOpen]=useState(false),[dynamicSourceOpen,setDynamicSourceOpen]=useState(false),[trustInspectorOpen,setTrustInspectorOpen]=useState(false),[policyInspectorOpen,setPolicyInspectorOpen]=useState(false),[impactInspectorOpen,setImpactInspectorOpen]=useState(false),[contractSaturationOpen,setContractSaturationOpen]=useState(false)
 const [leftOpen,setLeftOpen]=useState(true),[rightOpen,setRightOpen]=useState(true),[leftWidth,setLeftWidth]=useState(310),[rightWidth,setRightWidth]=useState(390)
 const [device,setDevice]=useState<'mobile'|'tablet'|'desktop'|'wide'>('desktop'),[fullscreen,setFullscreen]=useState(false),[leftMode,setLeftMode]=useState<'components'|'outline'>('components')
 const [sync,setSync]=useState<SyncRequest|null>(null),[blockSearch,setBlockSearch]=useState(''),[blockFamily,setBlockFamily]=useState('Tous')
 const [materialization,setMaterialization]=useState<StudioMaterializationState>({data:null,report:null,loading:false,error:'',refreshedAt:null})
 const [dirty,setDirty]=useState(false)
 const [doctorOpen,setDoctorOpen]=useState(false),[doctorBusy,setDoctorBusy]=useState(false),[serverPreflight,setServerPreflight]=useState<StudioServerPreflight|null>(null),[serverReady,setServerReady]=useState<boolean|null>(null),[healthOpen,setHealthOpen]=useState(false)
 const jsonInput=useRef<HTMLInputElement|null>(null)
 const publishReady=canPublish&&['approved','scheduled','published'].includes(page.status)
 const config=useMemo(()=>createAngelCarePuckConfig(pickers),[pickers])
 const saveTimer=useRef<ReturnType<typeof setTimeout>|null>(null),sequence=useRef(0),saveQueue=useRef<Promise<unknown>>(Promise.resolve())
 const normalizedSearch=blockSearch.trim().toLocaleLowerCase('fr')
 const blockFamilies=useMemo(()=>studioBlockFamilies(),[])
 const doctorReport=useMemo(()=>diagnoseStudioDocument(data),[data])
 useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>{setMaterialization(current=>({...current,loading:true,error:''}));fetch('/api/angelcare-marketplace/cms/studio/dynamic-sources/preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({data,locale:page.locale}),signal:controller.signal}).then(async response=>{const body=await response.json() as ApiEnvelope<{report:StudioMaterializationState['report'];data:Data}>;if(!response.ok||body.error)throw new Error(body.error?.message||'Matérialisation Studio indisponible.');setMaterialization({data:body.data?.data||null,report:body.data?.report||null,loading:false,error:'',refreshedAt:new Date().toISOString()})}).catch(error=>{if((error as Error).name==='AbortError')return;setMaterialization(current=>({...current,loading:false,error:error instanceof Error?error.message:'Matérialisation Studio indisponible.'}))})},450);return()=>{clearTimeout(timer);controller.abort()}},[data,page.locale])
 const puckOverrides=useMemo(()=>({drawerItem:(props:any)=>{const name=String(props?.name??'');const meta=studioBlockExperienceByLabel(name);const familyMatches=blockFamily==='Tous'||meta?.family===blockFamily;const searchMatches=!normalizedSearch||(meta?studioBlockSearchMatches(meta,normalizedSearch):name.toLocaleLowerCase('fr').includes(normalizedSearch));if(!familyMatches||!searchMatches)return <div hidden aria-hidden="true" data-angelcare-filtered-drawer-item="true"/>;return <div className={styles.drawerItem} data-preview={meta?.preview||'cards'} title={`Glisser ${name} dans le canvas`}><div className={styles.blockVisual} aria-hidden="true"><span/><span/><span/></div><div className={styles.blockCopy}><div><strong>{meta?.label||name}</strong>{meta?<em>{meta.badge}</em>:null}</div><p>{meta?.description||'Composant AngelCare éditable'}</p></div><GripVertical className={styles.drawerGrip} size={15}/></div>}}),[blockFamily,normalizedSearch])
 const setProgress=(message:string,state:'ready'|'busy'|'error'='ready')=>{setStatus(message);setTone(state)}
 const preflight=useCallback(async(next:Data,repair=false)=>{const result=await api<StudioServerPreflight>(`/api/angelcare-marketplace/cms/studio/pages/${page.id}/preflight`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({data:next,repair})});setServerPreflight(result.data);setServerReady(Boolean(result.data.ready));return result.data},[page.id])
 const persist=useCallback((next:Data,reason='Autosave Puck Studio')=>{const task=saveQueue.current.catch(()=>undefined).then(async()=>{setProgress('Validation avant enregistrement…','busy');try{const gate=await preflight(next,false);if(!gate.ready){setDoctorOpen(true);const first=gate.issues?.[0]?.message||gate.message||'Le Document Doctor a détecté un blocker.';throw new Error(first)}setProgress('Enregistrement…','busy');const result=await api<{data:Data}>(`/api/angelcare-marketplace/cms/studio/pages/${page.id}/draft`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({data:next,reason})});setServerReady(true);setDirty(false);setProgress('Enregistré','ready');return result.data}catch(error){const e=error as Error&{requestId?:string};setServerReady(false);setProgress('Enregistrement bloqué','error');setToast({title:'Enregistrement impossible',message:e.message,requestId:e.requestId,tone:'error'});throw error}});saveQueue.current=task.then(()=>undefined,()=>undefined);return task},[page.id,preflight])
 const schedule=useCallback((next:Data)=>{if(saveTimer.current)clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>{void persist(next).catch(()=>{})},900)},[persist])
 useEffect(()=>()=>{if(saveTimer.current)clearTimeout(saveTimer.current)},[])
 const syncDocument=useCallback((next:Data,statusLabel:string)=>{setData(next);sequence.current+=1;setSync({sequence:sequence.current,data:next,status:statusLabel})},[])
 const patchSelected=useCallback((blockId:string,patch:Record<string,unknown>)=>{const clone=JSON.parse(JSON.stringify(data)) as Data;const walk=(components:any[])=>{for(const component of components){if(component?.props?.id===blockId){component.props={...(component.props||{}),...patch};return true}const nested=Array.isArray(component?.props?.content)?component.props.content:[];if(walk(nested))return true}return false};walk(Array.isArray(clone.content)?clone.content:[]);setDirty(true);setServerReady(null);syncDocument(clone,'Bloc mis à jour');schedule(clone)},[data,schedule,syncDocument])
 const recheckDoctor=useCallback(async()=>{setDoctorBusy(true);try{await preflight(data,false)}finally{setDoctorBusy(false)}},[data,preflight])
 const repairDoctor=useCallback(async()=>{setDoctorBusy(true);try{const result=await preflight(data,true);if(result.repairs.length){setDirty(true);syncDocument(result.data,'Réparations sûres appliquées');setToast({title:'Réparation appliquée',message:`${result.repairs.length} réparation(s) déterministe(s) ont été appliquées. Vérifiez puis enregistrez.`})}}finally{setDoctorBusy(false)}},[data,preflight,syncDocument])
 const applyImported=useCallback(async(next:Data,summary:string)=>{
  let validated:Data
  try{validated=validateStudioPageJson(next)}catch(error){const e=error as Error;setProgress('Application refusée','error');setToast({title:'Application impossible',message:e.message,tone:'error'});throw error}
  await persist(validated,summary);syncDocument(validated,'Import appliqué');setToast({title:'Import appliqué',message:summary})
 },[persist,syncDocument])
 const preview=async()=>{setProgress('Préparation de l’aperçu…','busy');try{await persist(data,'Sauvegarde avant aperçu');const result=await api<{url:string}>(`/api/angelcare-marketplace/cms/studio/pages/${page.id}/preview`,{method:'POST'});window.open(result.data.url,'_blank','noopener,noreferrer');setProgress('Aperçu sécurisé prêt','ready')}catch(error){const e=error as Error&{requestId?:string};setProgress('Aperçu indisponible','error');setToast({title:'Aperçu impossible',message:e.message,requestId:e.requestId,tone:'error'})}}
 const publish=async(next=data)=>{setProgress('Publication…','busy');try{await persist(next,'Sauvegarde avant publication');const result=await api<{status:string}>(`/api/angelcare-marketplace/cms/studio/pages/${page.id}/publish`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reason:'Publication depuis AngelCare Marketplace Studio'})});setProgress('Publié','ready');setToast({title:'Publication terminée',message:`Page ${result.data.status}.`})}catch(error){const e=error as Error&{requestId?:string};setProgress('Publication bloquée','error');setToast({title:'Publication impossible',message:e.message,requestId:e.requestId,tone:'error'})}}
 const exportJson=()=>{const payload=studioPageJsonEnvelope(data,{pageId:page.id,title:page.title,slug:page.slug,locale:page.locale});const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`angelcare-${page.slug||'page'}-studio.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);setToast({title:'Export JSON prêt',message:'Le document Puck complet a été exporté.'})}
 const importJson=async(file:File)=>{try{if(file.size>STUDIO_PAGE_JSON_MAX_BYTES)throw new Error('Le fichier JSON dépasse la limite de 5 Mo.');const parsed=JSON.parse(await file.text()) as unknown;const next=validateStudioPageJson(parsed);await persist(next,`Import JSON ${file.name}`);syncDocument(next,'JSON importé');setToast({title:'Document JSON importé',message:`${file.name} a remplacé le document courant après validation.`})}catch(error){const e=error as Error;setProgress('Import JSON refusé','error');setToast({title:'Import JSON impossible',message:e.message,tone:'error'})}finally{if(jsonInput.current)jsonInput.current.value=''}}
 const duplicate=async()=>{setProgress('Duplication…','busy');try{await persist(data,'Sauvegarde avant duplication');const result=await api<CmsPage>(`/api/angelcare-marketplace/cms/studio/pages/${page.id}/duplicate`,{method:'POST'});setProgress('Copie créée','ready');window.location.assign(`/angelcare-marketplace/admin/experience/studio/${result.data.id}`)}catch(error){const e=error as Error&{requestId?:string};setProgress('Duplication impossible','error');setToast({title:'Duplication impossible',message:e.message,requestId:e.requestId,tone:'error'})}}
 const resize=useCallback((side:'left'|'right',event:ReactPointerEvent<HTMLButtonElement>)=>{event.preventDefault();const start=event.clientX,base=side==='left'?leftWidth:rightWidth;const move=(e:PointerEvent)=>{const delta=e.clientX-start;side==='left'?setLeftWidth(clampRail(side,base+delta)):setRightWidth(clampRail(side,base-delta))};const stop=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',stop);window.removeEventListener('pointercancel',stop);window.removeEventListener('blur',stop)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',stop);window.addEventListener('pointercancel',stop);window.addEventListener('blur',stop)},[leftWidth,rightWidth])
 const resizeKey=useCallback((side:'left'|'right',event:ReactKeyboardEvent<HTMLButtonElement>)=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const current=side==='left'?leftWidth:rightWidth;let next=current;if(event.key==='Home')next=side==='left'?280:340;else if(event.key==='End')next=side==='left'?480:560;else{const direction=event.key==='ArrowRight'?1:-1;next=current+(side==='left'?direction:-direction)*(event.shiftKey?48:16)}side==='left'?setLeftWidth(clampRail(side,next)):setRightWidth(clampRail(side,next))},[leftWidth,rightWidth])
 const canvasWidth=device==='mobile'?390:device==='tablet'?768:device==='wide'?1440:1280
 return <main className={styles.shell}>
  <section className={styles.hero}><div><span>ANGELCARE MARKETPLACE STUDIO · PUCK 0.23</span><h1>{page.title}</h1><p>Experience World, catalogue 10×10, import universel, Media Vault, aperçu sécurisé et publication gouvernée.</p></div><div className={styles.heroMeta}><span>{page.locale.toUpperCase()}</span><span>{page.status}</span><span>/{page.slug}</span><a href={`/angelcare-marketplace/${page.locale}/${page.slug}`} target="_blank" rel="noreferrer">Public <ExternalLink size={11}/></a></div></section>
  <input ref={jsonInput} className={styles.srOnly} type="file" accept="application/json,.json" onChange={event=>{const file=event.target.files?.[0];if(file)void importJson(file)}}/>
  <StudioMaterializationProvider state={materialization}><Puck config={config} data={data} overrides={puckOverrides} onChange={next=>{setData(next);setDirty(true);setServerReady(null);schedule(next)}} onPublish={publishReady&&page.status!=='published'?async next=>{setData(next);await publish(next)}:undefined} dnd={{behavior:'auto'}} iframe={{enabled:false}} height="100%">
  <div className={styles.command}>
   <div className={styles.commandLeft}>
    <div className={styles.status} data-state={tone}><i/><span>{status}</span></div>
    <div className={styles.readinessBar}><span data-state={serverReady===false?'block':dirty?'dirty':serverReady===true?'pass':'pending'}>SAVE</span><span data-state={canPreview?'pass':'block'}>PREVIEW</span><span data-state={publishReady?'pass':'block'}>PUBLISH</span></div>
    <PuckOperatorTools/>
    <div className={styles.commandDivider}/>
    <div className={styles.deviceGroup} aria-label="Format du canvas">{(['mobile','tablet','desktop','wide'] as const).map(key=><button key={key} className={styles.iconButton} data-active={device===key} onClick={()=>setDevice(key)} title={key==='wide'?'Wide 1440':key}>{key==='mobile'?<Smartphone size={14}/>:key==='tablet'?<Tablet size={14}/>:<Monitor size={14}/>}</button>)}</div>
    <div className={styles.commandDivider}/>
    <button data-active={leftOpen} onClick={()=>setLeftOpen(v=>!v)}><PanelLeftOpen size={14}/><span>Bibliothèque</span></button>
    <button data-active={rightOpen} onClick={()=>setRightOpen(v=>!v)}><PanelRightOpen size={14}/><span>Inspecteur</span></button>
    <button data-active={fullscreen} onClick={()=>setFullscreen(v=>!v)}><Maximize2 size={14}/><span>Focus</span></button>
   </div>
   <div className={styles.commandRight}>
    <details className={styles.commandMenu}>
     <summary title="Outils et réglages"><MoreHorizontal size={15}/><span>Outils</span></summary>
     <div className={styles.commandMenuPopover}>
      <header><div><span>ANGELCARE STUDIO</span><strong>Outils & contrôle</strong></div><kbd>•••</kbd></header>
      <div className={styles.commandMenuScroll}>
       <section><h4>Page</h4><button className={styles.commandMenuItem} onClick={()=>setImportOpen(true)}><Import size={14}/> Importer</button><button className={styles.commandMenuItem} onClick={exportJson}><Download size={14}/> Exporter JSON</button><button className={styles.commandMenuItem} onClick={()=>jsonInput.current?.click()}><Upload size={14}/> Charger JSON</button><button className={styles.commandMenuItem} onClick={()=>void duplicate()}><Copy size={14}/> Dupliquer</button></section>
       <section><h4>Qualité & publication</h4><button className={styles.commandMenuItem} onClick={()=>setHealthOpen(true)}><Activity size={14}/> Santé</button><button className={styles.commandMenuItem} onClick={()=>setDoctorOpen(true)}><Activity size={14}/> Doctor {doctorReport.blockers||doctorReport.repairable?`(${doctorReport.blockers+doctorReport.repairable})`:''}</button><button className={styles.commandMenuItem} onClick={()=>setGovernanceOpen(true)}><ShieldCheck size={14}/> Gouvernance</button><button className={styles.commandMenuItem} onClick={()=>setReleaseOpen(true)}><Rocket size={14}/> Release</button></section>
       <section><h4>Données & sources</h4><button className={styles.commandMenuItem} onClick={()=>setTemplateAssignmentOpen(true)}><LayoutTemplate size={14}/> Templates</button><button className={styles.commandMenuItem} onClick={()=>setLiveBindingOpen(true)}><Database size={14}/> Données live</button><button className={styles.commandMenuItem} onClick={()=>setDynamicSourceOpen(true)}><Database size={14}/> Sources dynamiques</button><button className={styles.commandMenuItem} onClick={()=>setTrustInspectorOpen(true)}><BadgeCheck size={14}/> Confiance</button></section>
       <section><h4>Contrôle avancé</h4><button className={styles.commandMenuItem} onClick={()=>setPolicyInspectorOpen(true)}><ShieldCheck size={14}/> Policy P11</button><button className={styles.commandMenuItem} onClick={()=>setImpactInspectorOpen(true)}><Activity size={14}/> Impact P12</button><button className={styles.commandMenuItem} onClick={()=>setContractSaturationOpen(true)}><Code2 size={14}/> Contrat P13</button></section>
       <section><h4>Site & ateliers</h4><Link className={styles.commandMenuItem} href="/angelcare-marketplace/admin/media/library"><Images size={14}/> Media Vault</Link><Link className={styles.commandMenuItem} href="/angelcare-marketplace/admin/experience/developer"><Code2 size={14}/> Developer</Link><Link className={styles.commandMenuItem} href="/angelcare-marketplace/admin/homepage/composer"><LayoutTemplate size={14}/> Thème</Link><Link className={styles.commandMenuItem} href="/angelcare-marketplace/admin/configuration/web-presence"><FileJson2 size={14}/> Web Presence</Link><Link className={styles.commandMenuItem} href="/angelcare-marketplace/admin/navigation"><LayoutTemplate size={14}/> Navigation</Link><Link className={styles.commandMenuItem} href="/angelcare-marketplace/admin/footer-studio"><LayoutTemplate size={14}/> Footer</Link><Link className={styles.commandMenuItem} href="/angelcare-marketplace/admin/experience/pages"><LayoutTemplate size={14}/> Pages</Link></section>
      </div>
     </div>
    </details>
    <button data-primary="true" onClick={()=>void persist(data,'Enregistrement manuel')}><Save size={14}/><span>Enregistrer</span></button>
    {canPreview?<button onClick={()=>void preview()}><ExternalLink size={14}/><span>Prévisualiser</span></button>:null}
    {canPublish?<button data-publish="true" disabled={!publishReady||page.status==='published'} title={publishReady?'Publication gouvernée':'La page doit être approuvée ou planifiée avant publication.'} onClick={()=>void publish()}><Send size={14}/><span>{page.status==='published'?'Publié':publishReady?'Publier':'Validation requise'}</span></button>:null}
   </div>
  </div>
  <div className={styles.frame} data-fullscreen={String(fullscreen)}><ExternalDataSync request={sync} onApplied={request=>{setData(request.data);setProgress(request.status,'ready')}}/><div className={styles.grid} style={{'--left':leftOpen?`${leftWidth}px`:'0px','--right':rightOpen?`${rightWidth}px`:'0px','--lh':leftOpen?'8px':'0px','--rh':rightOpen?'8px':'0px'} as CSSProperties}>
    <aside className={styles.rail} data-side="left" style={{display:leftOpen?'flex':'none'}}><div className={styles.railHead}><span className={styles.panelKicker}>BIBLIOTHÈQUE · {leftWidth}px</span><strong>{leftMode==='components'?'Sections & blocs':'Structure & calques'}</strong><small>{leftMode==='components'?'Commencez par les sections de la page, puis ajoutez uniquement ce qui est utile.':'Arborescence du document courant.'}</small><div className={styles.tabs}><button data-active={leftMode==='components'} onClick={()=>setLeftMode('components')}>Blocs</button><button data-active={leftMode==='outline'} onClick={()=>setLeftMode('outline')}>Structure</button></div>{leftMode==='components'?<div className={styles.blockFilters}><label><Search size={13}/><input value={blockSearch} onChange={event=>setBlockSearch(event.target.value)} placeholder="Rechercher hero, postpartum, confiance…"/>{blockSearch?<button type="button" onClick={()=>setBlockSearch('')} aria-label="Effacer la recherche"><X size={12}/></button>:null}</label><select value={blockFamily} onChange={event=>setBlockFamily(event.target.value)} aria-label="Filtrer la famille de blocs">{blockFamilies.map(family=><option key={family} value={family}>{family}</option>)}</select></div>:null}</div><div className={styles.railBody}>{leftMode==='components'?<><HomepageProMaxLibrary currentData={data} onApply={applyImported}/><Puck.Components/></>:<Puck.Outline/>}</div></aside>
    <button className={styles.resize} style={{display:leftOpen?'block':'none'}} onPointerDown={event=>resize('left',event)} onKeyDown={event=>resizeKey('left',event)} role="separator" aria-orientation="vertical" aria-valuemin={280} aria-valuemax={480} aria-valuenow={leftWidth} aria-label="Redimensionner la bibliothèque"/>
    <section className={styles.canvas}><div className={styles.canvasHead}><div><strong>Canvas live · {Array.isArray(data.content)?data.content.length:0} blocs racine</strong><span>{canvasWidth}px · autosave</span></div>{fullscreen?<button className={styles.focusExit} onClick={()=>setFullscreen(false)}><X size={13}/> Quitter Focus</button>:null}</div><div className={styles.viewport}><div className={styles.stage} style={{width:canvasWidth,maxWidth:'100%'}}><Puck.Preview id="angelcare-marketplace-studio-canvas"/><div className={styles.endcap}>Fin de page · glissez un bloc depuis la Bibliothèque pour continuer.</div></div></div></section>
    <button className={styles.resize} style={{display:rightOpen?'block':'none'}} onPointerDown={event=>resize('right',event)} onKeyDown={event=>resizeKey('right',event)} role="separator" aria-orientation="vertical" aria-valuemin={340} aria-valuemax={560} aria-valuenow={rightWidth} aria-label="Redimensionner l’inspecteur"/>
    <aside className={styles.rail} data-side="right" style={{display:rightOpen?'flex':'none'}}><div className={styles.railHead}><span className={styles.panelKicker}>INSPECTEUR PRO · {rightWidth}px</span><strong>Éditer · Personnaliser · Vérifier</strong><small>Standard pour l’essentiel. Avancé et Developer restent disponibles sans encombrer le parcours quotidien.</small></div><div className={styles.railBody}><StudioInspector2031 page={page} data={data} device={device} materialization={materialization} serverReady={serverReady} onOpenDoctor={()=>setDoctorOpen(true)} onPatchSelected={patchSelected}/></div></aside>
  </div></div>
  </Puck></StudioMaterializationProvider>
  <UniversalImportWorkbench open={importOpen} currentData={data} pickers={pickers} onClose={()=>setImportOpen(false)} onApply={applyImported}/>
  {toast?<div className={styles.toast} data-tone={toast.tone||'ready'}><button className={styles.srOnly} onClick={()=>setToast(null)}>Fermer</button><strong>{toast.title}</strong><p>{toast.message}</p>{toast.requestId?<code>Réf. {toast.requestId}</code>:null}<button onClick={()=>setToast(null)} style={{position:'absolute',right:8,top:8,border:0,background:'transparent'}}><X size={14}/></button></div>:null}
  {healthOpen?<StudioHomepageHealthPanel page={page} data={data} materialization={materialization} serverReady={serverReady} dirty={dirty} canPreview={canPreview} publishReady={publishReady} onClose={()=>setHealthOpen(false)}/>:null}
    {doctorOpen?<StudioDocumentDoctorPanel report={doctorReport} server={serverPreflight} busy={doctorBusy} onClose={()=>setDoctorOpen(false)} onRepair={()=>void repairDoctor()} onRecheck={()=>void recheckDoctor()}/>:null}
    {governanceOpen?<StudioGovernancePanel pageId={page.id} onClose={()=>setGovernanceOpen(false)}/>:null}
  {releaseOpen?<StudioReleasePanel onClose={()=>setReleaseOpen(false)}/>:null}
  {templateAssignmentOpen?<StudioTemplateAssignmentPanel locale={page.locale as 'fr'|'en'|'ar'} onClose={()=>setTemplateAssignmentOpen(false)}/>:null}
  {liveBindingOpen?<StudioLiveBindingInspector locale={page.locale as 'fr'|'en'|'ar'} onClose={()=>setLiveBindingOpen(false)}/>:null}
  {dynamicSourceOpen?<StudioDynamicSourceInspector data={data} locale={page.locale as 'fr'|'en'|'ar'} onClose={()=>setDynamicSourceOpen(false)}/>:null}
  {trustInspectorOpen?<StudioTrustInspector data={data} locale={page.locale as 'fr'|'en'|'ar'} pageId={page.id} pageRoute={`/angelcare-marketplace/${page.locale}/${page.slug}`} onClose={()=>setTrustInspectorOpen(false)}/>:null}
  {policyInspectorOpen?<StudioPolicyInspector data={data} pageId={page.id} pageRoute={`/angelcare-marketplace/${page.locale}/${page.slug}`} onClose={()=>setPolicyInspectorOpen(false)}/>:null}
  {impactInspectorOpen?<StudioImpactInspector data={data} pageId={page.id} onClose={()=>setImpactInspectorOpen(false)}/>:null}
  {contractSaturationOpen?<StudioContractSaturationInspector onClose={()=>setContractSaturationOpen(false)}/>:null}
 </main>
}
