 'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { AlertTriangle, ArrowRight, SlidersHorizontal } from 'lucide-react'
import type { EligibleRelease, OntologyOption } from '@/lib/flashcards-os/solutions/types'
import styles from './solutions-os.module.css'

function list(value:string){return value.split(',').map((item)=>item.trim()).filter(Boolean)}
export default function ConstraintArchitectureStudio({releases,ontology}:{releases:EligibleRelease[];ontology:OntologyOption[]}){
 const router=useRouter();const [submitting,setSubmitting]=useState(false);const [error,setError]=useState('')
 const objectiveOptions=ontology.filter((item)=>item.kind==='capability_objective').slice(0,12)
 const contextOptions=ontology.filter((item)=>item.kind==='usage_context').slice(0,12)
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSubmitting(true);setError('');const form=new FormData(event.currentTarget)
  const body={title:String(form.get('title')||''),universe:String(form.get('universe')||'b2c'),profile:{customerSegment:String(form.get('segment')||''),learnerAgesMonths:list(String(form.get('ages')||'')).map(Number).filter(Number.isFinite),learnerCount:Number(form.get('learnerCount')||1),languages:list(String(form.get('languages')||'fr')),individualOrGroup:String(form.get('mode')||'individual'),supportProfiles:list(String(form.get('supportProfiles')||''))},constraints:{usageContexts:list(String(form.get('contexts')||'')),objectiveKeys:list(String(form.get('objectives')||'')),painPointKeys:list(String(form.get('painPoints')||'')),outcomeKeys:list(String(form.get('outcomes')||'')),deliveryMode:String(form.get('deliveryMode')||'physical'),budgetMinDh:Number(form.get('budgetMin')||0),budgetMaxDh:Number(form.get('budgetMax')||0),durationDays:Number(form.get('durationDays')||1),deliveryDeadline:String(form.get('deadline')||'')||null,region:String(form.get('region')||''),supportLevel:String(form.get('supportLevel')||''),minimumCollections:Number(form.get('minimumCollections')||1),maximumCollections:Number(form.get('maximumCollections')||4),requiredReleaseIds:list(String(form.get('requiredReleaseIds')||'')),excludedReleaseIds:list(String(form.get('excludedReleaseIds')||'')),requiredCategoryKeys:[],excludedCategoryKeys:[],requiredFormats:[String(form.get('deliveryMode')||'physical')],maximumLeadTimeDays:Number(form.get('leadTime')||30),minimumGrossMarginPercent:Number(form.get('minimumMargin')||40),maximumDiscountPercent:Number(form.get('maximumDiscount')||10),priceBookId:null,taxProfileId:null,allowRepeatedProductsAcrossScenarios:true,maximumRepeatedCollections:Number(form.get('repeatLimit')||2),requireVisiblyDifferentScenarios:true},requestedScenarioCount:Number(form.get('scenarioCount')||3),priorities:list(String(form.get('priorities')||'coverage,affordability')),scenarioRoles:list(String(form.get('roles')||'essential,balanced,premium'))}
  const response=await fetch('/api/flashcards-os/solutions/requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({}));if(!response.ok){setError(String(payload.error||'Request creation failed.'));setSubmitting(false);return}router.push(`/flashcards-os/solutions/requests/${payload.id}`);router.refresh()}
 return <div className={styles.page}><section className={styles.hero}><div><div className={styles.kicker}><SlidersHorizontal size={15}/> CONSTRAINT ARCHITECTURE STUDIO</div><h1>Définir ce que la solution doit satisfaire avant de laisser le système composer.</h1><p>Le studio sépare profil, besoin, contraintes produit, contraintes commerciales et stratégie de diversification. Les conflits sont visibles avant toute dépense OpenRouter.</p></div><aside className={styles.heroSeal}><span>LIVE CANDIDATE POOL</span><strong>{releases.length} exact releases</strong><small>{objectiveOptions.length} objectifs · {contextOptions.length} contextes chargés.</small></aside></section>
 <form className={styles.constraintStudio} onSubmit={submit}><aside className={styles.constraintRail}><span className={styles.eyebrow}>REQUEST ARCHITECTURE</span><ol><li>01 · Univers commercial</li><li>02 · Profil apprenant</li><li>03 · Besoin et contexte</li><li>04 · Contraintes produit</li><li>05 · Prix et marge</li><li>06 · Diversification</li></ol></aside><main className={styles.formCanvas}>
  <section className={styles.formBlock}><h3>Mission commerciale</h3><p>Identité, univers et segment de la demande.</p><div className={styles.fieldGrid}><div className={styles.fieldWide}><label>Titre</label><input name="title" required defaultValue="Solution langage & autonomie"/></div><div className={styles.field}><label>Univers</label><select name="universe"><option value="b2c">B2C</option><option value="b2b">B2B</option></select></div><div className={styles.field}><label>Segment</label><input name="segment" defaultValue="Famille"/></div></div></section>
  <section className={styles.formBlock}><h3>Profil apprenant</h3><p>Âge en mois, langues, volume et besoin de support.</p><div className={styles.fieldGrid}><div className={styles.field}><label>Âges en mois</label><input name="ages" defaultValue="48"/></div><div className={styles.field}><label>Nombre d’apprenants</label><input name="learnerCount" type="number" min="1" defaultValue="1"/></div><div className={styles.field}><label>Langues</label><input name="languages" defaultValue="fr"/></div><div className={styles.field}><label>Mode</label><select name="mode"><option value="individual">Individuel</option><option value="group">Groupe</option></select></div><div className={styles.fieldWide}><label>Profils de support</label><input name="supportProfiles" placeholder="bilingual_learner, short_attention"/></div></div></section>
  <section className={styles.formBlock}><h3>Objectifs, contexte et problème</h3><p>Clés gouvernées séparées par des virgules.</p><div className={styles.fieldGrid}><div className={styles.field}><label>Contextes</label><input name="contexts" defaultValue="home_parent_led"/></div><div className={styles.field}><label>Objectifs</label><input name="objectives" defaultValue="vocabulary,emotional_identification"/></div><div className={styles.field}><label>Pain points</label><input name="painPoints" defaultValue="limited_vocabulary,difficulty_identifying_emotions"/></div><div className={styles.field}><label>Outcomes</label><input name="outcomes" defaultValue="recognise_target_words,identify_core_emotions"/></div><div className={styles.field}><label>Durée de besoin</label><input name="durationDays" type="number" min="1" defaultValue="14"/></div><div className={styles.field}><label>Région</label><input name="region" defaultValue="Rabat"/></div></div></section>
  <section className={styles.formBlock}><h3>Contraintes produit</h3><p>Nombre de collections, formats, releases imposées ou exclues.</p><div className={styles.fieldGrid}><div className={styles.field}><label>Mode de livraison</label><select name="deliveryMode"><option value="physical">Physique</option><option value="digital">Digital</option><option value="hybrid">Hybride</option></select></div><div className={styles.field}><label>Délai maximum (jours)</label><input name="leadTime" type="number" defaultValue="7"/></div><div className={styles.field}><label>Collections minimum</label><input name="minimumCollections" type="number" min="1" defaultValue="2"/></div><div className={styles.field}><label>Collections maximum</label><input name="maximumCollections" type="number" min="1" max="24" defaultValue="4"/></div><div className={styles.fieldWide}><label>Release IDs obligatoires</label><input name="requiredReleaseIds" placeholder={releases.slice(0,2).map((item)=>item.id).join(', ')}/></div><div className={styles.fieldWide}><label>Release IDs exclus</label><input name="excludedReleaseIds"/></div></div></section>
  <section className={styles.formBlock}><h3>Commercial & diversification</h3><p>Les calculs restent déterministes; OpenRouter ne reçoit que les faits validés.</p><div className={styles.fieldGrid}><div className={styles.field}><label>Budget minimum</label><input name="budgetMin" type="number" defaultValue="80"/></div><div className={styles.field}><label>Budget maximum</label><input name="budgetMax" type="number" defaultValue="200"/></div><div className={styles.field}><label>Marge minimum %</label><input name="minimumMargin" type="number" defaultValue="40"/></div><div className={styles.field}><label>Discount maximum %</label><input name="maximumDiscount" type="number" defaultValue="10"/></div><div className={styles.field}><label>Nombre de scénarios</label><input name="scenarioCount" type="number" min="1" max="10" defaultValue="3"/></div><div className={styles.field}><label>Répétitions max</label><input name="repeatLimit" type="number" min="0" defaultValue="2"/></div><div className={styles.fieldWide}><label>Priorités</label><input name="priorities" defaultValue="coverage,affordability,diversity"/></div><div className={styles.fieldWide}><label>Rôles des scénarios</label><input name="roles" defaultValue="essential,balanced,premium"/></div></div></section>
  {error?<div className={styles.notice}><AlertTriangle size={14}/> {error}</div>:null}<button className={styles.primary} type="submit" disabled={submitting}>{submitting?'Création…':'Créer la demande gouvernée'}<ArrowRight size={14}/></button>
 </main><aside className={styles.constraintInspector}><h3>Readiness inspector</h3><ul><li>Maximum 10 scénarios appliqué côté serveur.</li><li>Maximum collections appliqué avant et après composition.</li><li>Une release non approuvée ne peut jamais entrer dans le pool.</li><li>Prix, coût, taxe et marge sont recalculés après chaque modification.</li><li>B2C et B2B restent deux registres séparés.</li></ul></aside></form></div>
}
