import type { CatalogLocale } from '../catalog-discovery/types'
import type { CategoryNativeExperienceFamily } from './types'

const general = {
  fr: {
    configure: 'Configurer cette offre', continue: 'Continuer', review: 'Vérifier ma configuration',
    availability: 'Disponibilité réelle', price: 'Prix et conditions', included: 'Ce qui est prévu',
    details: 'Détails essentiels', guidance: 'Comment cela fonctionne', trust: 'Confiance ANGELCARE',
    recommendations: 'À découvrir aussi', save: 'Enregistrer', compare: 'Comparer',
    unavailable: 'Cette configuration n’est pas disponible actuellement.', quote: 'Proposition sur mesure',
    from: 'Dès', next: 'Étape suivante', configuration: 'Votre configuration',
  },
  en: {
    configure: 'Configure this offer', continue: 'Continue', review: 'Review my configuration',
    availability: 'Live availability', price: 'Price and terms', included: 'What is included',
    details: 'Essential details', guidance: 'How it works', trust: 'ANGELCARE trust',
    recommendations: 'You may also like', save: 'Save', compare: 'Compare',
    unavailable: 'This configuration is not currently available.', quote: 'Tailored proposal',
    from: 'From', next: 'Next step', configuration: 'Your configuration',
  },
  ar: {
    configure: 'إعداد هذا العرض', continue: 'متابعة', review: 'مراجعة الإعداد',
    availability: 'التوفر الفعلي', price: 'السعر والشروط', included: 'ما يشمله العرض',
    details: 'التفاصيل الأساسية', guidance: 'كيف يعمل', trust: 'ثقة ANGELCARE',
    recommendations: 'قد يناسبك أيضاً', save: 'حفظ', compare: 'مقارنة',
    unavailable: 'هذا الإعداد غير متاح حالياً.', quote: 'عرض مخصص',
    from: 'ابتداءً من', next: 'الخطوة التالية', configuration: 'إعدادك',
  },
} as const

const familyCopy: Record<CategoryNativeExperienceFamily, Record<CatalogLocale, { eyebrow: string; promise: string; proof: string }>> = {
  home_childcare: { fr:{eyebrow:'GARDE À DOMICILE',promise:'Une garde construite autour de votre enfant, de votre rythme et de votre domicile.',proof:'Informations, horaires et instructions sont collectés avant la coordination.'}, en:{eyebrow:'HOME CHILDCARE',promise:'Childcare built around your child, schedule and home.',proof:'Details, schedule and instructions are collected before coordination.'}, ar:{eyebrow:'رعاية منزلية',promise:'رعاية مبنية حول طفلك وجدولك ومنزلك.',proof:'يتم جمع التفاصيل والجدول والتعليمات قبل التنسيق.'}},
  recurring_care: { fr:{eyebrow:'GARDE RÉCURRENTE',promise:'Visualisez votre semaine, vos exceptions et votre estimation mensuelle.',proof:'Le planning transmis aux opérations reste identique à votre sélection.'}, en:{eyebrow:'RECURRING CARE',promise:'See your week, exceptions and monthly estimate.',proof:'The schedule handed to operations remains identical to your selection.'}, ar:{eyebrow:'رعاية متكررة',promise:'شاهد أسبوعك والاستثناءات والتقدير الشهري.',proof:'يبقى الجدول المنقول للعمليات مطابقاً لاختيارك.'}},
  school_pickup: { fr:{eyebrow:'SORTIE D’ÉCOLE',promise:'Reliez école, trajet, destination et personne de remise dans un seul parcours.',proof:'Les informations alimentent Transport, Dispatch et Journey Control.'}, en:{eyebrow:'SCHOOL PICKUP',promise:'Connect school, route, destination and handover in one journey.',proof:'The data flows to Transport, Dispatch and Journey Control.'}, ar:{eyebrow:'الاستلام من المدرسة',promise:'اربط المدرسة والمسار والوجهة والتسليم في رحلة واحدة.',proof:'تنتقل البيانات إلى النقل والتوزيع ومتابعة الرحلة.'}},
  overnight_care: { fr:{eyebrow:'GARDE DE NUIT',promise:'Un parcours rassurant pour les routines du soir, de la nuit et du matin.',proof:'Les limites, accès, routines et contacts sont clarifiés avant la mission.'}, en:{eyebrow:'OVERNIGHT CARE',promise:'A reassuring journey for evening, night and morning routines.',proof:'Limits, access, routines and contacts are clarified before the mission.'}, ar:{eyebrow:'رعاية ليلية',promise:'مسار مطمئن لروتين المساء والليل والصباح.',proof:'تُوضح الحدود والدخول والروتين والاتصالات قبل المهمة.'}},
  emergency_care: { fr:{eyebrow:'BESOIN URGENT',promise:'Une demande accélérée, sans fausse promesse de confirmation instantanée.',proof:'La capacité réelle et le délai restant sont vérifiés avant confirmation.'}, en:{eyebrow:'URGENT NEED',promise:'A fast request without a false instant-confirmation promise.',proof:'Real capacity and remaining lead time are checked before confirmation.'}, ar:{eyebrow:'حاجة عاجلة',promise:'طلب سريع دون وعد زائف بالتأكيد الفوري.',proof:'يتم التحقق من السعة الفعلية والمهلة قبل التأكيد.'}},
  hotel_childcare: { fr:{eyebrow:'CONCIERGERIE FAMILLE',promise:'Une expérience adaptée à l’hôtel, au voyage et aux lieux temporaires.',proof:'Réservation, point de rencontre, langue et facturation sont structurés.'}, en:{eyebrow:'FAMILY CONCIERGE',promise:'An experience tailored to hotels, travel and temporary locations.',proof:'Reservation, meeting point, language and billing are structured.'}, ar:{eyebrow:'كونسيرج العائلة',promise:'تجربة مخصصة للفنادق والسفر والمواقع المؤقتة.',proof:'يتم تنظيم الحجز ونقطة اللقاء واللغة والفوترة.'}},
  event_care: { fr:{eyebrow:'GARDE ÉVÉNEMENTIELLE',promise:'Dimensionnez enfants, espaces, activités et équipe avant le devis.',proof:'Le brief structuré réduit les échanges manuels de qualification.'}, en:{eyebrow:'EVENT CHILDCARE',promise:'Size children, spaces, activities and team before quotation.',proof:'The structured brief reduces manual qualification exchanges.'}, ar:{eyebrow:'رعاية الفعاليات',promise:'حدد الأطفال والمساحات والأنشطة والفريق قبل العرض.',proof:'يقلل الملخص المنظم من التأهيل اليدوي.'}},
  holiday_programme: { fr:{eyebrow:'PROGRAMME & EXCURSION',promise:'Itinéraire, transport, capacité et autorisations visibles avant réservation.',proof:'Aucune place ne sera affichée sans autorité de capacité.'}, en:{eyebrow:'PROGRAMME & EXCURSION',promise:'See itinerary, transport, capacity and permissions before booking.',proof:'No seat is displayed without a capacity authority.'}, ar:{eyebrow:'برنامج ورحلة',promise:'شاهد المسار والنقل والسعة والتصاريح قبل الحجز.',proof:'لا يتم عرض أي مكان دون مرجع للسعة.'}},
  development_service: { fr:{eyebrow:'DÉVELOPPEMENT À DOMICILE',promise:'Objectifs, niveau, matériel et progression réunis dans un parcours clair.',proof:'La mission reçoit les objectifs et la préparation choisis.'}, en:{eyebrow:'AT-HOME DEVELOPMENT',promise:'Goals, level, materials and progression in one clear journey.',proof:'The mission receives the selected goals and preparation.'}, ar:{eyebrow:'تطوير منزلي',promise:'الأهداف والمستوى والمواد والتقدم في مسار واضح.',proof:'تتلقى المهمة الأهداف والتحضير المختارين.'}},
  learning_support: { fr:{eyebrow:'SOUTIEN D’APPRENTISSAGE',promise:'Matière, niveau, langue et fréquence configurés avant la demande.',proof:'Le besoin pédagogique est transmis sans ressaisie.'}, en:{eyebrow:'LEARNING SUPPORT',promise:'Configure subject, level, language and frequency before requesting.',proof:'The learning need is handed over without re-entry.'}, ar:{eyebrow:'دعم التعلم',promise:'حدد المادة والمستوى واللغة والتكرار قبل الطلب.',proof:'يتم نقل الحاجة التعليمية دون إعادة إدخال.'}},
  non_medical_support: { fr:{eyebrow:'SOUTIEN NON MÉDICAL',promise:'Décrivez routines et accommodations dans un cadre explicitement non médical.',proof:'Aucun diagnostic, traitement ou acte médical n’est proposé.'}, en:{eyebrow:'NON-MEDICAL SUPPORT',promise:'Describe routines and accommodations within an explicitly non-medical scope.',proof:'No diagnosis, treatment or medical act is offered.'}, ar:{eyebrow:'دعم غير طبي',promise:'صف الروتين والتسهيلات ضمن نطاق غير طبي بوضوح.',proof:'لا يتم تقديم تشخيص أو علاج أو إجراء طبي.'}},
  flashcards: { fr:{eyebrow:'FLASHCARDS PÉDAGOGIQUES',promise:'Explorez contenu, dimensions, langue et objectifs avant de choisir votre édition.',proof:'Chaque variante conserve son média, son prix et son stock réels.'}, en:{eyebrow:'LEARNING FLASHCARDS',promise:'Explore content, dimensions, language and outcomes before choosing an edition.',proof:'Each variant keeps its real media, price and stock.'}, ar:{eyebrow:'بطاقات تعليمية',promise:'استكشف المحتوى والأبعاد واللغة والأهداف قبل اختيار الإصدار.',proof:'يحتفظ كل متغير بصوره وسعره ومخزونه الفعلي.'}},
  montessori_kit: { fr:{eyebrow:'KIT MONTESSORI',promise:'Visualisez chaque composant, chaque activité et les besoins de supervision.',proof:'Remplacements et recharges sont reliés au même produit canonique.'}, en:{eyebrow:'MONTESSORI KIT',promise:'See every component, activity and supervision need.',proof:'Replacements and refills remain linked to the same canonical product.'}, ar:{eyebrow:'حقيبة مونتيسوري',promise:'شاهد كل مكوّن ونشاط ومتطلبات الإشراف.',proof:'تبقى القطع البديلة وإعادة التعبئة مرتبطة بالمنتج نفسه.'}},
  development_game: { fr:{eyebrow:'JEU DE DÉVELOPPEMENT',promise:'Comprenez règles, durée, joueurs et compétences avant la commande.',proof:'La fiche privilégie le fonctionnement réel du jeu.'}, en:{eyebrow:'DEVELOPMENT GAME',promise:'Understand rules, duration, players and skills before ordering.',proof:'The page prioritizes how the game actually works.'}, ar:{eyebrow:'لعبة تطوير',promise:'افهم القواعد والمدة واللاعبين والمهارات قبل الطلب.',proof:'تركز الصفحة على طريقة عمل اللعبة فعلياً.'}},
  activity_box: { fr:{eyebrow:'BOX D’ACTIVITÉS',promise:'Choisissez thème, enfants, fréquence et personnalisation.',proof:'Le calendrier et les règles de pause restent visibles après souscription.'}, en:{eyebrow:'ACTIVITY BOX',promise:'Choose theme, children, frequency and personalization.',proof:'The calendar and pause rules remain visible after subscription.'}, ar:{eyebrow:'صندوق أنشطة',promise:'اختر الموضوع والأطفال والتكرار والتخصيص.',proof:'يبقى التقويم وقواعد الإيقاف ظاهرة بعد الاشتراك.'}},
  digital_resource: { fr:{eyebrow:'RESSOURCE DIGITALE',promise:'Prévisualisez, comprenez la licence et accédez sans livraison physique.',proof:'Aucun stock ou transport physique ne sera présenté.'}, en:{eyebrow:'DIGITAL RESOURCE',promise:'Preview, understand the license and access without physical delivery.',proof:'No physical stock or transport is shown.'}, ar:{eyebrow:'مورد رقمي',promise:'عاين وافهم الترخيص واحصل على الوصول دون توصيل مادي.',proof:'لا يتم عرض مخزون أو نقل مادي.'}},
  preschool_admission: { fr:{eyebrow:'ADMISSION PRÉSCOLAIRE',promise:'Campus, éligibilité, programme, frais et documents dans un dossier unique.',proof:'L’expérience crée un parcours d’admission, pas une commande retail.'}, en:{eyebrow:'PRESCHOOL ADMISSION',promise:'Campus, eligibility, programme, fees and documents in one application.',proof:'The experience creates an admissions journey, not a retail order.'}, ar:{eyebrow:'القبول التمهيدي',promise:'الحرم والأهلية والبرنامج والرسوم والوثائق في ملف واحد.',proof:'تنشئ التجربة رحلة قبول وليست طلباً للبيع بالتجزئة.'}},
  academy_course: { fr:{eyebrow:'COURS ACADEMY',promise:'Résultats, programme, prérequis et certification avant inscription.',proof:'L’inscription reste liée à l’autorité Academy.'}, en:{eyebrow:'ACADEMY COURSE',promise:'Outcomes, syllabus, prerequisites and certification before enrollment.',proof:'Enrollment remains linked to Academy authority.'}, ar:{eyebrow:'دورة الأكاديمية',promise:'النتائج والمنهج والمتطلبات والشهادة قبل التسجيل.',proof:'يبقى التسجيل مرتبطاً بسلطة الأكاديمية.'}},
  academy_cohort: { fr:{eyebrow:'COHORTE ACADEMY',promise:'Dates, sessions, places et exigences visibles avant inscription.',proof:'Les places proviennent de la capacité de cohorte réelle.'}, en:{eyebrow:'ACADEMY COHORT',promise:'See dates, sessions, seats and requirements before enrollment.',proof:'Seats come from real cohort capacity.'}, ar:{eyebrow:'فوج الأكاديمية',promise:'شاهد التواريخ والجلسات والأماكن والمتطلبات قبل التسجيل.',proof:'تأتي الأماكن من السعة الفعلية للفوج.'}},
  certification_pathway: { fr:{eyebrow:'PARCOURS CERTIFIANT',promise:'Visualisez la séquence, les évaluations et le renouvellement.',proof:'Chaque étape reste visible dans le parcours apprenant.'}, en:{eyebrow:'CERTIFICATION PATHWAY',promise:'See sequence, assessments and renewal.',proof:'Every step remains visible in the learner journey.'}, ar:{eyebrow:'مسار الشهادة',promise:'شاهد التسلسل والتقييمات والتجديد.',proof:'تبقى كل خطوة ظاهرة في رحلة المتعلم.'}},
  parent_workshop: { fr:{eyebrow:'ATELIER PARENTS',promise:'Choisissez sujet, format, dates et ressources associées.',proof:'Le replay et les supports suivent les règles publiées.'}, en:{eyebrow:'PARENT WORKSHOP',promise:'Choose topic, format, dates and associated resources.',proof:'Replay and materials follow published rules.'}, ar:{eyebrow:'ورشة للآباء',promise:'اختر الموضوع والصيغة والتواريخ والموارد.',proof:'تتبع الإعادة والمواد القواعد المنشورة.'}},
  institutional_training: { fr:{eyebrow:'FORMATION INSTITUTIONNELLE',promise:'Modules, participants, sites et certification structurés avant devis.',proof:'Le brief arrive directement dans le pipeline commercial.'}, en:{eyebrow:'INSTITUTIONAL TRAINING',promise:'Structure modules, participants, sites and certification before quotation.',proof:'The brief flows directly to the commercial pipeline.'}, ar:{eyebrow:'تدريب مؤسسي',promise:'حدد الوحدات والمشاركين والمواقع والشهادة قبل العرض.',proof:'ينتقل الملخص مباشرة إلى المسار التجاري.'}},
  school_programme: { fr:{eyebrow:'PROGRAMME ÉTABLISSEMENT',promise:'Configurez sites, enfants, horaires, modules et reporting.',proof:'La proposition conserve toute la portée sélectionnée.'}, en:{eyebrow:'SCHOOL PROGRAMME',promise:'Configure sites, children, schedules, modules and reporting.',proof:'The proposal retains the full selected scope.'}, ar:{eyebrow:'برنامج مؤسسة',promise:'حدد المواقع والأطفال والجداول والوحدات والتقارير.',proof:'يحتفظ العرض بكامل النطاق المختار.'}},
  staff_reinforcement: { fr:{eyebrow:'RENFORT D’ÉQUIPE',promise:'Définissez rôles, compétences, shifts et période.',proof:'La demande alimente Provider Workforce sans recréer les profils.'}, en:{eyebrow:'STAFF REINFORCEMENT',promise:'Define roles, skills, shifts and period.',proof:'The request feeds Provider Workforce without recreating profiles.'}, ar:{eyebrow:'تعزيز الفريق',promise:'حدد الأدوار والمهارات والمناوبات والفترة.',proof:'يغذي الطلب إدارة مقدمي الخدمة دون إعادة إنشاء الملفات.'}},
  hospitality_programme: { fr:{eyebrow:'HOSPITALITY KIDS FRIENDLY',promise:'Composez babysitting, kids club, événements et expérience famille.',proof:'Saisonnalité et facturation sont intégrées au brief.'}, en:{eyebrow:'HOSPITALITY KIDS FRIENDLY',promise:'Compose babysitting, kids club, events and family experience.',proof:'Seasonality and billing are included in the brief.'}, ar:{eyebrow:'ضيافة صديقة للأطفال',promise:'كوّن رعاية الأطفال ونادي الأطفال والفعاليات وتجربة العائلة.',proof:'تُدرج الموسمية والفوترة في الملخص.'}},
  corporate_benefit: { fr:{eyebrow:'AVANTAGE FAMILLE',promise:'Configurez contribution, éligibilité, limites et territoires.',proof:'Les données privées des familles restent séparées du reporting employeur.'}, en:{eyebrow:'FAMILY BENEFIT',promise:'Configure contribution, eligibility, limits and territories.',proof:'Private family data remains separate from employer reporting.'}, ar:{eyebrow:'ميزة عائلية',promise:'حدد المساهمة والأهلية والحدود والمناطق.',proof:'تبقى بيانات العائلات الخاصة منفصلة عن تقارير صاحب العمل.'}},
  health_adjacent: { fr:{eyebrow:'PARTENAIRE NON MÉDICAL',promise:'Structurez un programme famille sans dépasser le périmètre non médical.',proof:'Aucun acte clinique n’est proposé ou suggéré.'}, en:{eyebrow:'NON-MEDICAL PARTNER',promise:'Structure a family programme without crossing the non-medical boundary.',proof:'No clinical act is offered or implied.'}, ar:{eyebrow:'شريك غير طبي',promise:'نظم برنامجاً عائلياً دون تجاوز النطاق غير الطبي.',proof:'لا يتم تقديم أو الإيحاء بأي عمل سريري.'}},
  venue_programme: { fr:{eyebrow:'LIEU & ÉVÉNEMENT',promise:'Dimensionnez fréquentation, espace, sécurité, équipe et équipements.',proof:'Le programme peut être temporaire ou permanent.'}, en:{eyebrow:'VENUE & EVENT',promise:'Size attendance, space, security, team and equipment.',proof:'The programme may be temporary or permanent.'}, ar:{eyebrow:'مكان وفعالية',promise:'حدد الحضور والمساحة والأمن والفريق والمعدات.',proof:'يمكن أن يكون البرنامج مؤقتاً أو دائماً.'}},
  partner_os: { fr:{eyebrow:'PARTNER OS',promise:'Comparez modules, limites, sites, utilisateurs et onboarding.',proof:'La sélection alimente l’autorité de provisioning tenant.'}, en:{eyebrow:'PARTNER OS',promise:'Compare modules, limits, sites, users and onboarding.',proof:'The selection feeds tenant provisioning authority.'}, ar:{eyebrow:'PARTNER OS',promise:'قارن الوحدات والحدود والمواقع والمستخدمين والتهيئة.',proof:'يغذي الاختيار سلطة تهيئة المستأجر.'}},
  quality_check: { fr:{eyebrow:'QUALITY CHECK 360',promise:'Définissez cadre, sites, preuves, dates et livrables.',proof:'Aucun score n’est affiché avant une évaluation fondée sur des preuves.'}, en:{eyebrow:'QUALITY CHECK 360',promise:'Define framework, sites, evidence, dates and deliverables.',proof:'No score is shown before an evidence-backed assessment.'}, ar:{eyebrow:'QUALITY CHECK 360',promise:'حدد الإطار والمواقع والأدلة والتواريخ والمخرجات.',proof:'لا يتم عرض أي نتيجة قبل تقييم قائم على الأدلة.'}},
  managed_solution: { fr:{eyebrow:'SOLUTION SUR MESURE',promise:'Transformez un besoin complexe en brief commercial structuré.',proof:'Sites, territoires, modules et documents restent attachés à l’opportunité.'}, en:{eyebrow:'MANAGED SOLUTION',promise:'Turn a complex need into a structured commercial brief.',proof:'Sites, territories, modules and documents remain attached to the opportunity.'}, ar:{eyebrow:'حل مخصص',promise:'حوّل الحاجة المعقدة إلى ملخص تجاري منظم.',proof:'تبقى المواقع والمناطق والوحدات والوثائق مرتبطة بالفرصة.'}},
}

export function categoryNativeCopy(locale: CatalogLocale) { return general[locale] }
export function categoryNativeFamilyCopy(family: CategoryNativeExperienceFamily, locale: CatalogLocale) { return familyCopy[family][locale] }
