create extension if not exists pgcrypto;

create table if not exists public.angelcare_marketplace_cms_pages(
 id uuid primary key default gen_random_uuid(), public_reference text unique not null default ('PGE-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,10))), route_key text not null, locale text not null default 'fr' check(locale in('fr','en','ar')), territory_id uuid, title text not null, navigation_label text, slug text not null, description text, status text not null default 'draft' check(status in('draft','submitted','in_review','approved','scheduled','published','retired','archived')), translation_status text not null default 'source' check(translation_status in('source','missing','draft','reviewed','approved','stale')), sensitive boolean not null default false, owner_id uuid, reviewer_id uuid, current_version int not null default 1, published_version int, seo_title text, seo_description text, canonical_url text, scheduled_at timestamptz, published_at timestamptz, created_by uuid, updated_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique nulls not distinct(locale,slug,territory_id)
);
create table if not exists public.angelcare_marketplace_cms_page_versions(id uuid primary key default gen_random_uuid(),page_id uuid not null references public.angelcare_marketplace_cms_pages(id) on delete cascade,version_number int not null,title text not null,description text,slug text not null,status text not null,snapshot jsonb not null default '{}',change_summary text,created_by uuid,created_at timestamptz not null default now(),unique(page_id,version_number));
create table if not exists public.angelcare_marketplace_cms_blocks(id uuid primary key default gen_random_uuid(),page_id uuid not null references public.angelcare_marketplace_cms_pages(id) on delete cascade,block_key text not null,block_type text not null,sort_order int not null default 0,status text not null default 'active' check(status in('draft','active','hidden','archived')),content jsonb not null default '{}',settings jsonb not null default '{}',audience text[] not null default '{}',territory_id uuid,locale text not null default 'fr',updated_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(page_id,block_key));
create table if not exists public.angelcare_marketplace_cms_block_library(id uuid primary key default gen_random_uuid(),block_type text unique not null,name text not null,description text,schema_definition jsonb not null default '{}',allowed_audiences text[] not null default '{}',rtl_ready boolean not null default true,status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare_marketplace_cms_menus(id uuid primary key default gen_random_uuid(),menu_key text unique not null,name text not null,locale text not null default 'fr' check(locale in('fr','en','ar')),territory_id uuid,status text not null default 'draft',owner_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare_marketplace_cms_menu_items(id uuid primary key default gen_random_uuid(),menu_id uuid not null references public.angelcare_marketplace_cms_menus(id) on delete cascade,label text not null,href text not null,page_id uuid references public.angelcare_marketplace_cms_pages(id) on delete set null,parent_id uuid references public.angelcare_marketplace_cms_menu_items(id) on delete cascade,sort_order int not null default 0,visibility text not null default 'public',status text not null default 'active',created_at timestamptz not null default now());
create table if not exists public.angelcare_marketplace_cms_ctas(id uuid primary key default gen_random_uuid(),cta_key text unique not null,label text not null,href text not null,intent text not null default 'navigate',audience text[] not null default '{}',locale text not null default 'fr',territory_id uuid,status text not null default 'draft',analytics_event text,owner_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.angelcare_marketplace_cms_publication_jobs(id uuid primary key default gen_random_uuid(),public_reference text unique not null default ('PUBJ-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,10))),page_id uuid not null references public.angelcare_marketplace_cms_pages(id),action text not null check(action in('publish','unpublish','rollback')),status text not null default 'queued' check(status in('queued','validating','blocked','ready','completed','failed','cancelled')),scheduled_at timestamptz,blocker text,requested_by uuid,approved_by uuid,created_at timestamptz not null default now(),completed_at timestamptz);
create table if not exists public.angelcare_marketplace_cms_preview_sessions(id uuid primary key default gen_random_uuid(),preview_token text unique not null default encode(gen_random_bytes(24),'hex'),page_id uuid not null references public.angelcare_marketplace_cms_pages(id) on delete cascade,version_number int not null,locale text not null default 'fr',territory_id uuid,created_by uuid,expires_at timestamptz not null default now()+interval '4 hours',revoked_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.angelcare_marketplace_cms_redirects(id uuid primary key default gen_random_uuid(),source_path text not null,target_path text not null,territory_id uuid,status text not null default 'active',created_at timestamptz not null default now(),unique nulls not distinct(source_path,territory_id));

create or replace function public.angelcare_marketplace_transition_cms_page(p_page_id uuid,p_target_status text,p_reason text,p_actor_id uuid) returns public.angelcare_marketplace_cms_pages language plpgsql security definer set search_path=public as $$declare r public.angelcare_marketplace_cms_pages; current_status text;begin select status into current_status from public.angelcare_marketplace_cms_pages where id=p_page_id for update;if current_status is null then raise exception 'Page not found';end if;if p_target_status='published' and current_status not in('approved','scheduled') then raise exception 'Page is not publishable';end if;if p_target_status='approved' and current_status not in('submitted','in_review') then raise exception 'Page is not approvable';end if;update public.angelcare_marketplace_cms_pages set status=p_target_status,updated_by=p_actor_id,updated_at=now(),published_at=case when p_target_status='published' then now() else published_at end,published_version=case when p_target_status='published' then current_version else published_version end where id=p_page_id returning * into r;insert into public.angelcare_marketplace_cms_page_versions(page_id,version_number,title,description,slug,status,snapshot,change_summary,created_by) select id,current_version,title,description,slug,p_target_status,jsonb_build_object('page',to_jsonb(p.*),'blocks',coalesce((select jsonb_agg(to_jsonb(b) order by b.sort_order) from public.angelcare_marketplace_cms_blocks b where b.page_id=p_page_id),'[]'::jsonb)),p_reason,p_actor_id from public.angelcare_marketplace_cms_pages p where id=p_page_id on conflict(page_id,version_number) do update set snapshot=excluded.snapshot,status=excluded.status,change_summary=excluded.change_summary;insert into public.angelcare_marketplace_cms_publication_jobs(page_id,action,status,scheduled_at,requested_by,approved_by) values(p_page_id,case when p_target_status='published' then 'publish' else 'unpublish' end,case when p_target_status='published' then 'completed' else 'ready' end,case when p_target_status='scheduled' then r.scheduled_at else null end,p_actor_id,case when p_target_status in('approved','published') then p_actor_id else null end);return r;end$$;
create or replace function public.angelcare_marketplace_rollback_cms_page(p_page_id uuid,p_version_number int,p_reason text,p_actor_id uuid) returns public.angelcare_marketplace_cms_pages language plpgsql security definer set search_path=public as $$declare v public.angelcare_marketplace_cms_page_versions; r public.angelcare_marketplace_cms_pages;begin select * into v from public.angelcare_marketplace_cms_page_versions where page_id=p_page_id and version_number=p_version_number;if v.id is null then raise exception 'Version not found';end if;update public.angelcare_marketplace_cms_pages set title=v.title,description=v.description,slug=v.slug,current_version=current_version+1,status='draft',updated_by=p_actor_id,updated_at=now() where id=p_page_id returning * into r;delete from public.angelcare_marketplace_cms_blocks where page_id=p_page_id;insert into public.angelcare_marketplace_cms_blocks(page_id,block_key,block_type,sort_order,status,content,settings,audience,territory_id,locale) select p_page_id,x->>'block_key',x->>'block_type',coalesce((x->>'sort_order')::int,0),coalesce(x->>'status','active'),coalesce(x->'content','{}'),coalesce(x->'settings','{}'),coalesce(array(select jsonb_array_elements_text(coalesce(x->'audience','[]'::jsonb))),'{}'),r.territory_id,r.locale from jsonb_array_elements(coalesce(v.snapshot->'blocks','[]'::jsonb))x;insert into public.angelcare_marketplace_cms_publication_jobs(page_id,action,status,blocker,requested_by,completed_at)values(p_page_id,'rollback','completed',p_reason,p_actor_id,now());return r;end$$;

insert into public.angelcare_marketplace_cms_block_library(block_type,name,description,schema_definition,allowed_audiences) values
('hero','Hero institutionnel','Promesse, preuve et CTA primaire.','{"required":["eyebrow","title","lead"]}','{public,family,b2b}'),('audience_router','Routeur d’audiences','Orientation familles, établissements, hôtels, cliniques et entreprises.','{"required":["items"]}','{public}'),('service_grid','Architecture de services','Familles de services sans prix fictif.','{"required":["items"]}','{public,family,b2b}'),('trust_strip','Preuves de confiance','SOP, contrôle, certification et limites.','{"required":["items"]}','{public,family,b2b}'),('proof_grid','Grille de preuves','Preuves structurées et vérifiables.','{"required":["items"]}','{public,family,b2b}'),('editorial','Contenu éditorial','Texte structuré et accessible.','{"required":["title","body"]}','{public,family,b2b}'),('timeline','Chronologie','Étapes d’un parcours.','{"required":["items"]}','{public,family,b2b}'),('faq','FAQ','Questions et réponses gouvernées.','{"required":["items"]}','{public,family,b2b}'),('inquiry_form','Formulaire de demande','Création de demande publique persistante.','{"required":["audience"]}','{public}'),('marketplace_entry','Entrée Marketplace','Accès contrôlé au futur catalogue.','{}','{public}'),('partner_os_entry','Entrée Partner OS','Accès contrôlé au futur SaaS.','{}','{public}'),('academy_entry','Entrée Academy','Accès contrôlé à la future Academy.','{}','{public}'),('family_story','Parcours famille','Narration confiance-first.','{}','{public,family}'),('cta_band','Bandeau CTA','Action primaire et secondaire.','{"required":["label"]}','{public,family,b2b}'),('stats','Indicateurs sourcés','Indicateurs sans données fabriquées.','{"required":["items"]}','{public,b2b}') on conflict(block_type) do update set name=excluded.name,description=excluded.description,schema_definition=excluded.schema_definition;

insert into public.angelcare_marketplace_permissions(permission_key,name,category,sensitive) values
('marketplace.cms.view','Voir Experience Builder','CMS',false),('marketplace.cms.create','Créer une page','CMS',true),('marketplace.cms.edit','Modifier une page','CMS',true),('marketplace.cms.pages.manage','Gérer les pages','CMS',true),('marketplace.cms.blocks.manage','Gérer les blocs','CMS',true),('marketplace.cms.menus.manage','Gérer les menus','CMS',true),('marketplace.cms.ctas.manage','Gérer les CTA','CMS',true),('marketplace.cms.preview','Prévisualiser','CMS',false),('marketplace.cms.submit','Soumettre en revue','CMS',true),('marketplace.cms.review','Réviser le contenu','CMS',true),('marketplace.cms.approve','Approuver le contenu','CMS',true),('marketplace.cms.publish','Publier le contenu','CMS',true),('marketplace.cms.schedule','Planifier le contenu','CMS',true),('marketplace.cms.rollback','Restaurer une version','CMS',true),('marketplace.cms.archive','Archiver une page','CMS',true),('marketplace.cms.redirects.manage','Gérer les redirections','CMS',true),('marketplace.cms.export','Exporter les preuves CMS','CMS',true) on conflict(permission_key) do update set name=excluded.name,category=excluded.category,sensitive=excluded.sensitive;
insert into public.angelcare_marketplace_role_permissions(role_key,permission_key) select r.role_key,p.permission_key from public.angelcare_marketplace_roles r cross join public.angelcare_marketplace_permissions p where r.role_key in('marketplace_super_admin','marketplace_executive','marketplace_product_admin') and p.permission_key like 'marketplace.cms.%' on conflict do nothing;
update public.angelcare_marketplace_modules set status='enabled',enabled=true,health_status='healthy',route_prefix='/angelcare-marketplace/admin/experience',required_permissions=array['marketplace.cms.view']::text[],version=version+1,updated_at=now() where introduced_by_mega_zip=5;
insert into public.angelcare_marketplace_feature_flags(flag_key,name,description,enabled,status,reason) values('marketplace.experience-builder.enabled','Experience Builder & CMS','Pages, blocs, menus, CTA, preview, publication et rollback.',true,'active','Ultra Delivery 1/5') on conflict(flag_key) do update set enabled=true,status='active',updated_at=now();

alter table public.angelcare_marketplace_cms_pages enable row level security;alter table public.angelcare_marketplace_cms_page_versions enable row level security;alter table public.angelcare_marketplace_cms_blocks enable row level security;alter table public.angelcare_marketplace_cms_block_library enable row level security;alter table public.angelcare_marketplace_cms_menus enable row level security;alter table public.angelcare_marketplace_cms_menu_items enable row level security;alter table public.angelcare_marketplace_cms_ctas enable row level security;alter table public.angelcare_marketplace_cms_publication_jobs enable row level security;alter table public.angelcare_marketplace_cms_preview_sessions enable row level security;alter table public.angelcare_marketplace_cms_redirects enable row level security;
revoke all on table public.angelcare_marketplace_cms_pages,public.angelcare_marketplace_cms_page_versions,public.angelcare_marketplace_cms_blocks,public.angelcare_marketplace_cms_block_library,public.angelcare_marketplace_cms_menus,public.angelcare_marketplace_cms_menu_items,public.angelcare_marketplace_cms_ctas,public.angelcare_marketplace_cms_publication_jobs,public.angelcare_marketplace_cms_preview_sessions,public.angelcare_marketplace_cms_redirects from anon,authenticated;
grant all on table public.angelcare_marketplace_cms_pages,public.angelcare_marketplace_cms_page_versions,public.angelcare_marketplace_cms_blocks,public.angelcare_marketplace_cms_block_library,public.angelcare_marketplace_cms_menus,public.angelcare_marketplace_cms_menu_items,public.angelcare_marketplace_cms_ctas,public.angelcare_marketplace_cms_publication_jobs,public.angelcare_marketplace_cms_preview_sessions,public.angelcare_marketplace_cms_redirects to service_role;
grant execute on function public.angelcare_marketplace_transition_cms_page(uuid,text,text,uuid),public.angelcare_marketplace_rollback_cms_page(uuid,int,text,uuid) to service_role;
