"use client"

import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react"
import { Activity, AlertTriangle, MonitorCog as Browser, Command, Download, KeyRound, Laptop2, LoaderCircle, LockKeyhole, MonitorCog, RefreshCw, RotateCcw, Save, ShieldCheck, Wifi, WifiOff } from "lucide-react"

type Row = Record<string, any>
type Overview = { counts: Row; devices: Row[]; policies: Row[]; browser_policies: Row[]; assignments: Row[]; commands: Row[]; events: Row[]; tab_templates: Row[]; unlock_attempts: Row[] }
async function api<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,cache:"no-store",headers:{"Content-Type":"application/json",...(init?.headers||{})}});const payload=await response.json().catch(()=>null);if(!response.ok||!payload?.ok)throw new Error(payload?.error||`HTTP_${response.status}`);return payload.data as T}
const modeTone:Record<string,string>={standard:"border-blue-200 bg-blue-50 text-blue-700",focus:"border-amber-200 bg-amber-50 text-amber-700",locked:"border-red-200 bg-red-50 text-red-700"}
const commandOptions=["ENTER_STANDARD_MODE","ENTER_FOCUS_MODE","ENTER_LOCKED_MODE","LOCK_NOW","UNLOCK_TEMPORARILY","RELOCK","OPEN_URL","OPEN_TAB_TEMPLATE","CLOSE_CORPORATE_TABS","REFRESH_STATION_POLICY","RELOAD_ACTIVE_TAB","RESTART_BROWSER_RUNTIME","RESTART_DESKTOP_RUNTIME","CLEAR_CORPORATE_BROWSER_CACHE","REQUEST_STATION_DIAGNOSTICS","SHOW_ADMINISTRATOR_MESSAGE"]
function relative(value?:string|null){if(!value)return"Jamais";const ms=Date.now()-new Date(value).getTime();if(ms<60000)return"À l’instant";if(ms<3600000)return`Il y a ${Math.floor(ms/60000)} min`;if(ms<86400000)return`Il y a ${Math.floor(ms/3600000)} h`;return new Date(value).toLocaleString("fr-FR")}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-1.5 block text-[10px] font-black uppercase tracking-[.12em] text-slate-500">{label}</span>{children}</label>}
const input="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-xs font-bold text-slate-800 outline-none focus:border-blue-400"
export default function CorporateStationAdmin(){
 const[data,setData]=useState<Overview|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[busy,setBusy]=useState(false)
 const[selectedDeviceId,setSelectedDeviceId]=useState(""),[selectedPolicyId,setSelectedPolicyId]=useState(""),[selectedBrowserPolicyId,setSelectedBrowserPolicyId]=useState("")
 const[policy,setPolicy]=useState<Row>({mode:"standard",start_at_login:false,restore_after_crash:true,relock_after_restart:true,pin_required:true,failed_attempt_threshold:5,lockout_duration_minutes:15,maximum_tabs:8,offline_unlock_permitted:true})
 const[browserPolicy,setBrowserPolicy]=useState<Row>({default_action:"deny",allowed_domains:["opsmanagement.angelcarehub.com","google.com","www.google.com","mail.google.com","accounts.google.com"],blocked_domains:[],allow_google_search:true,allow_gmail:true,allow_downloads:true,download_confirmation_required:true,allow_microphone:false,allow_camera:false,allow_notifications:true,allow_printing:false,allow_external_open:false})
 const[command,setCommand]=useState<Row>({command_type:"REFRESH_STATION_POLICY",reason:"Instruction administrative ANGELCARE",url:"",message:""})
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const overview=await api<Overview>("/api/desktop-stations/admin/overview");setData(overview);const deviceId=selectedDeviceId||overview.devices[0]?.id||"";setSelectedDeviceId(deviceId);const policyId=selectedPolicyId||overview.policies[0]?.id||"";setSelectedPolicyId(policyId);const policyRow=overview.policies.find(x=>x.id===policyId)||overview.policies[0];if(policyRow)setPolicy(policyRow);const browserId=selectedBrowserPolicyId||policyRow?.browser_policy_id||overview.browser_policies[0]?.id||"";setSelectedBrowserPolicyId(browserId);const browserRow=overview.browser_policies.find(x=>x.id===browserId)||overview.browser_policies[0];if(browserRow)setBrowserPolicy(browserRow)}catch(cause){setError(cause instanceof Error?cause.message:String(cause))}finally{setLoading(false)}},[selectedBrowserPolicyId,selectedDeviceId,selectedPolicyId])
 useEffect(()=>{void load()},[load])
 const selectedDevice=useMemo(()=>data?.devices.find(x=>x.id===selectedDeviceId)||null,[data,selectedDeviceId])
 const run=async(task:()=>Promise<unknown>,message:string)=>{setBusy(true);setError(null);setNotice(null);try{await task();setNotice(message);await load()}catch(cause){setError(cause instanceof Error?cause.message:String(cause))}finally{setBusy(false)}}
 const savePolicy=()=>run(async()=>{let p:any;if(policy.id)p=await api("/api/desktop-stations/policies",{method:"PATCH",body:JSON.stringify(policy)});else p=await api("/api/desktop-stations/policies",{method:"POST",body:JSON.stringify({...policy,name:policy.name||"Politique Corporate Station"})});const pid=(p as any).id;setSelectedPolicyId(pid);let b:any;if(browserPolicy.id)b=await api("/api/desktop-stations/browser-policies",{method:"PATCH",body:JSON.stringify(browserPolicy)});else b=await api("/api/desktop-stations/browser-policies",{method:"POST",body:JSON.stringify({...browserPolicy,name:browserPolicy.name||"Navigation Corporate"})});setSelectedBrowserPolicyId((b as any).id);await api("/api/desktop-stations/policies",{method:"PATCH",body:JSON.stringify({id:pid,browser_policy_id:(b as any).id})});if(selectedDevice)await api("/api/desktop-stations/assignments",{method:"POST",body:JSON.stringify({policy_id:pid,target_type:"device",target_id:selectedDevice.id,precedence:600})})},"Politique versionnée, assignée et prête à être synchronisée.")
 const sendCommand=()=>run(()=>api("/api/desktop-stations/commands",{method:"POST",body:JSON.stringify({device_id:selectedDeviceId,command_type:command.command_type,reason:command.reason,payload:{url:command.url||undefined,message:command.message||undefined,minutes:15}})}),"Commande distante émise et auditée.")
 const createPin=()=>{const pin=window.prompt("Nouveau PIN administrateur (6 chiffres minimum)");if(!pin)return;void run(()=>api("/api/desktop-stations/unlock/credentials",{method:"POST",body:JSON.stringify({policy_id:selectedPolicyId,device_id:selectedDeviceId,pin,failed_attempt_threshold:policy.failed_attempt_threshold,offline_verifier_eligible:policy.offline_unlock_permitted})}),"PIN sécurisé créé. Sa valeur en clair n’est plus accessible.")}
 const recoveryCodes=()=>void run(async()=>{const result=await api<{codes:string[]}>("/api/desktop-stations/unlock/recovery-codes",{method:"POST",body:JSON.stringify({policy_id:selectedPolicyId,device_id:selectedDeviceId,count:8})});window.alert(`Codes de récupération à conserver hors ligne :\n\n${result.codes.join("\n")}`)},"Codes de récupération générés.")
 if(loading&&!data)return <div className="grid min-h-[520px] place-items-center"><div className="text-center"><LoaderCircle className="mx-auto h-9 w-9 animate-spin text-blue-600"/><p className="mt-3 text-sm font-black text-slate-800">Chargement des postes Corporate Station…</p></div></div>
 return <div className="space-y-5">
  <div className="flex flex-wrap items-start justify-between gap-4 rounded-[28px] border border-blue-100 bg-[linear-gradient(135deg,#ffffff,#eff6ff_58%,#ecfdf5)] p-5"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-blue-700"><MonitorCog className="h-4 w-4"/>Corporate Station OS 1.5.0</div><h2 className="mt-2 text-2xl font-black tracking-[-.04em] text-slate-950">Postes & Mode Corporate</h2><p className="mt-2 max-w-4xl text-xs font-semibold leading-6 text-slate-600">Gouvernez les modes Standard, Focus et Locked, la navigation, les permissions, les téléchargements, les credentials et les commandes distantes de chaque poste.</p></div><button onClick={()=>void load()} className="inline-flex h-10 items-center gap-2 rounded-xl bg-slate-950 px-4 text-xs font-black text-white"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/>Actualiser</button></div>
  {error?<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-xs font-black text-red-700">{error}</div>:null}{notice?<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-xs font-black text-emerald-700">{notice}</div>:null}
  {data?<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[
   [Laptop2,"Postes",data.counts.total_stations,"bg-slate-100 text-slate-700"],[Wifi,"En ligne",data.counts.online_stations,"bg-emerald-50 text-emerald-700"],[LockKeyhole,"Locked",data.counts.locked_stations,"bg-red-50 text-red-700"],[Activity,"À synchroniser",data.counts.policy_refresh_required,"bg-amber-50 text-amber-700"],[AlertTriangle,"Violations",data.counts.browser_violations,"bg-violet-50 text-violet-700"]
  ].map(([Icon,label,value,tone]:any)=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className={`grid h-9 w-9 place-items-center rounded-xl ${tone}`}><Icon className="h-4 w-4"/></div><p className="mt-3 text-2xl font-black text-slate-950">{value}</p><p className="text-[10px] font-black uppercase tracking-[.1em] text-slate-500">{label}</p></div>)}</div>
  <div className="grid gap-5 xl:grid-cols-[370px_minmax(0,1fr)]"><aside className="rounded-[26px] border border-slate-200 bg-white p-3 shadow-sm"><p className="px-2 py-2 text-[10px] font-black uppercase tracking-[.14em] text-slate-500">Flotte autorisée</p><div className="max-h-[760px] space-y-2 overflow-auto">{data.devices.map(device=>{const online=device.last_heartbeat_at&&Date.now()-new Date(device.last_heartbeat_at).getTime()<180000;return <button key={device.id} onClick={()=>setSelectedDeviceId(device.id)} className={`w-full rounded-2xl border p-3 text-left transition ${selectedDeviceId===device.id?"border-blue-300 bg-blue-50":"border-slate-100 bg-slate-50 hover:border-slate-200"}`}><div className="flex items-center justify-between gap-2"><span className="truncate text-xs font-black text-slate-900">{device.device_name||device.hostname||device.installation_id}</span>{online?<Wifi className="h-4 w-4 text-emerald-600"/>:<WifiOff className="h-4 w-4 text-slate-400"/>}</div><div className="mt-2 flex items-center justify-between"><span className={`rounded-full border px-2 py-1 text-[8px] font-black uppercase ${modeTone[device.station_mode||"standard"]}`}>{device.station_mode||"standard"}</span><span className="text-[9px] font-bold text-slate-500">{relative(device.last_heartbeat_at)}</span></div><p className="mt-2 truncate text-[9px] font-semibold text-slate-500">v{device.desktop_version||"—"} · {device.operating_system||device.platform||"OS inconnu"} · {device.station_tab_count||0} onglets</p></button>})}</div></aside>
  <div className="space-y-5">{selectedDevice?<section className="rounded-[26px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-blue-600">Poste sélectionné</p><h3 className="mt-1 text-xl font-black text-slate-950">{selectedDevice.device_name||selectedDevice.hostname||selectedDevice.installation_id}</h3><p className="mt-1 text-xs font-semibold text-slate-500">{selectedDevice.installation_id}</p></div><span className={`rounded-full border px-3 py-1.5 text-[9px] font-black uppercase ${modeTone[selectedDevice.station_mode||"standard"]}`}>{selectedDevice.station_mode||"standard"}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Utilisateur",selectedDevice.current_user_id||"Non assigné"],["Version",selectedDevice.desktop_version||"—"],["Politique",selectedDevice.station_policy_version||0],["Dernier unlock",relative(selectedDevice.station_last_unlock_at)],["Navigateur",selectedDevice.station_browser_health||"unknown"],["Onglets",selectedDevice.station_tab_count||0],["Kiosk",selectedDevice.station_kiosk_state?"Actif":"Inactif"],["Lockout",selectedDevice.station_lockout_until?relative(selectedDevice.station_lockout_until):"Aucun"]].map(([l,v])=><div key={l} className="rounded-2xl bg-slate-50 p-3"><p className="text-[9px] font-black uppercase text-slate-400">{l}</p><p className="mt-1 truncate text-xs font-black text-slate-800">{v}</p></div>)}</div></section>:null}
  <section className="rounded-[26px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-blue-600"/><h3 className="text-lg font-black text-slate-950">Politique du poste</h3></div><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="Nom"><input className={input} value={policy.name||""} onChange={e=>setPolicy({...policy,name:e.target.value})}/></Field><Field label="Mode"><select className={input} value={policy.mode||"standard"} onChange={e=>setPolicy({...policy,mode:e.target.value})}><option value="standard">Standard</option><option value="focus">Corporate Focus</option><option value="locked">Corporate Locked</option></select></Field><Field label="Maximum onglets"><input className={input} type="number" min={2} max={50} value={policy.maximum_tabs||8} onChange={e=>setPolicy({...policy,maximum_tabs:Number(e.target.value)})}/></Field></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{[["start_at_login","Démarrer à la connexion"],["restore_after_crash","Restaurer après crash"],["relock_after_restart","Relocker après redémarrage"],["pin_required","PIN obligatoire"],["offline_unlock_permitted","Recovery hors ligne"],["exit_reason_required","Motif de sortie"],["always_on_top","Toujours au premier plan"],["restore_tabs","Restaurer les onglets"]].map(([key,label])=><label key={key} className="flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-[10px] font-black text-slate-700"><input type="checkbox" checked={Boolean(policy[key])} onChange={e=>setPolicy({...policy,[key]:e.target.checked})}/>{label}</label>)}</div><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="Tentatives max"><input className={input} type="number" value={policy.failed_attempt_threshold||5} onChange={e=>setPolicy({...policy,failed_attempt_threshold:Number(e.target.value)})}/></Field><Field label="Lockout (min)"><input className={input} type="number" value={policy.lockout_duration_minutes||15} onChange={e=>setPolicy({...policy,lockout_duration_minutes:Number(e.target.value)})}/></Field><Field label="Relock temporaire (min)"><input className={input} type="number" value={policy.auto_relock_minutes||15} onChange={e=>setPolicy({...policy,auto_relock_minutes:Number(e.target.value)})}/></Field></div></section>
  <section className="rounded-[26px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Browser className="h-5 w-5 text-violet-600"/><h3 className="text-lg font-black text-slate-950">Navigation & permissions</h3></div><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Domaines autorisés"><textarea className="min-h-28 w-full rounded-xl border border-slate-200 p-3 text-xs font-semibold outline-none" value={(browserPolicy.allowed_domains||[]).join("\n")} onChange={e=>setBrowserPolicy({...browserPolicy,allowed_domains:e.target.value.split(/\n|,/).map(x=>x.trim()).filter(Boolean)})}/></Field><Field label="Domaines bloqués"><textarea className="min-h-28 w-full rounded-xl border border-slate-200 p-3 text-xs font-semibold outline-none" value={(browserPolicy.blocked_domains||[]).join("\n")} onChange={e=>setBrowserPolicy({...browserPolicy,blocked_domains:e.target.value.split(/\n|,/).map(x=>x.trim()).filter(Boolean)})}/></Field></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{[["allow_google_search","Google Search"],["allow_gmail","Gmail"],["allow_downloads","Téléchargements"],["download_confirmation_required","Confirmer téléchargement"],["allow_uploads","Uploads manuels"],["allow_microphone","Microphone"],["allow_camera","Caméra"],["allow_notifications","Notifications"],["allow_clipboard_read","Lecture presse-papiers"],["allow_clipboard_write","Écriture presse-papiers"],["allow_printing","Impression"],["allow_external_open","Navigateur externe"]].map(([key,label])=><label key={key} className="flex items-center gap-2 rounded-xl border border-slate-200 p-3 text-[10px] font-black text-slate-700"><input type="checkbox" checked={Boolean(browserPolicy[key])} onChange={e=>setBrowserPolicy({...browserPolicy,[key]:e.target.checked})}/>{label}</label>)}</div><div className="mt-5 flex flex-wrap gap-2"><button disabled={busy} onClick={savePolicy} className="inline-flex h-10 items-center gap-2 rounded-xl bg-blue-600 px-4 text-xs font-black text-white disabled:opacity-50"><Save className="h-4 w-4"/>Versionner & assigner</button><button disabled={!selectedPolicyId||busy} onClick={createPin} className="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-xs font-black text-slate-700"><KeyRound className="h-4 w-4"/>Créer / tourner PIN</button><button disabled={!selectedPolicyId||busy} onClick={recoveryCodes} className="inline-flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-xs font-black text-slate-700"><RotateCcw className="h-4 w-4"/>Codes recovery</button></div></section>
  <section className="rounded-[26px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Command className="h-5 w-5 text-emerald-600"/><h3 className="text-lg font-black text-slate-950">Commande distante gouvernée</h3></div><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Commande"><select className={input} value={command.command_type} onChange={e=>setCommand({...command,command_type:e.target.value})}>{commandOptions.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Motif"><input className={input} value={command.reason} onChange={e=>setCommand({...command,reason:e.target.value})}/></Field><Field label="URL approuvée"><input className={input} placeholder="https://…" value={command.url} onChange={e=>setCommand({...command,url:e.target.value})}/></Field><Field label="Message administrateur"><input className={input} value={command.message} onChange={e=>setCommand({...command,message:e.target.value})}/></Field></div><button disabled={!selectedDeviceId||busy} onClick={sendCommand} className="mt-4 inline-flex h-10 items-center gap-2 rounded-xl bg-slate-950 px-4 text-xs font-black text-white disabled:opacity-50"><Command className="h-4 w-4"/>Émettre la commande</button></section>
  </div></div></>:null}
 </div>
}
