/* AUTO-GENERATED by npm run build - edit src/views/frontend instead */
const template = "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <title>AngelCare Commerce Console</title>\n  <script type=\"module\" crossorigin src=\"/assets/index-DgUL88rv.js\"></script>\n  <link rel=\"stylesheet\" crossorigin href=\"/assets/index-DkipvtAN.css\">\n</head>\n<body>\n  <div id=\"root\" data-shop=\"__SHOP_DOMAIN__\"></div>\n</body>\n</html>\n";

export default template;