"use client";

import { CheckCircle2, Clock3, FileLock2, Gavel, LockKeyhole, RotateCcw, ShieldAlert, Stamp, UserRoundCheck, XCircle } from "lucide-react";
import { useCallback, useState } from "react";
import { AcCapitalShell } from "../../core/AcCapitalShell";
import { EmptyState, ErrorState, LoadingState } from "../../core/AsyncState";
import { ActionFeedback, Field } from "../../core/FormParts";
import { MetricTile } from "../../core/MetricTile";
import { Dialog, Drawer } from "../../core/Overlay";
import { StatusBadge } from "../../core/StatusBadge";
import { AuditTimeline, FactGrid, PrimaryButton, SecondaryButton, SectionHeading, TruthChip } from "../../core/WorkspaceParts";
import { postEnvelope } from "../../core/api";
import { rowsFrom, shortDate, text } from "../../core/data";
import type { CapitalActor, Row } from "../../core/types";
import { canApprove } from "../../core/role";
import { useAction } from "../../core/useAction";
import { useActionQuery } from "../../core/useActionQuery";
import { useWorkspace } from "../../core/useWorkspace";
import styles from "./approvals.module.css";

type Modal="create"|"decision"|null;

export function ApprovalsPage({actor}:{actor:CapitalActor}){
 const workspace=useWorkspace("/api/ac-capital-os/approvals");const action=useAction();const [selected,setSelected]=useState<Row|null>(null);const [modal,setModal]=useState<Modal>(null);const [decision,setDecision]=useState("approve");const [note,setNote]=useState("");
 const [create,setCreate]=useState({title:"",approvingFounder:"Founder / Managing Director",reason:"",riskIfUnapproved:"",dueAt:"",relatedCaseId:"",relatedDocumentId:""});
 const openAction=useCallback((next:Modal)=>setModal(next),[]);useActionQuery({create:"create",review:"decision"},openAction);
 const approvals=rowsFrom(workspace.envelope,"approvals");const pending=approvals.filter(row=>/pending|required|review/i.test(text(row,["status"],""))).length;const approved=approvals.filter(row=>/approved/i.test(text(row,["status"],""))).length;const revision=approvals.filter(row=>/revision/i.test(text(row,["status"],""))).length;const critical=approvals.filter(row=>/critical|financial|founder/i.test(text(row,["risk_if_unapproved","reason_required","reason"],""))).length;
 async function createRequest(){if(!create.title.trim()||!create.reason.trim())return action.validate("Approval title and reason are required.");await action.execute(()=>postEnvelope("/api/ac-capital-os/approvals",{...create}),"Founder approval request created.");await workspace.refresh();}
 async function decide(){if(!selected)return action.validate("Select an approval request.");if(!canApprove(actor))return action.disabled("Founder or authorized capital strategy authority is required.");const source=text(selected,["source_table"],"");if(!source)return action.validate("Approval source table is missing.");await action.execute(()=>postEnvelope(`/api/ac-capital-os/approvals/${String(selected.id)}/decision`,{sourceTable:source,decision,note}),`Approval decision persisted: ${decision}.`);await workspace.refresh();}
 const insights=[{label:"Governance firewall",value:`${pending} pending approvals`},{label:"Authorized actor",value:canApprove(actor)?"Decision authority available":"Read/review only"},{label:"Exact-version authority",value:"Universal approvals + legacy sources"},{label:"Decision persistence",value:"Approved object version and snapshot remain traceable"}];

 return <AcCapitalShell actor={actor} workspaceKey="founder-approval-chamber" title="Founder Approval Chamber" subtitle="The central governance firewall for final submissions, sensitive emails, financial releases, equity language, doctrine activation, AI prepared actions and proof-package release." envelope={workspace.envelope} insights={insights} primaryAction="Create Approval Request" onPrimaryAction={()=>setModal("create")}>
  {workspace.loading?<LoadingState label="Loading approval queue and source objects…"/>:workspace.error?<ErrorState message={workspace.error} onRetry={()=>void workspace.refresh()}/>:<>
   <section className={styles.chamberHero}><div><span><Gavel size={15}/> Founder Decision Authority</span><h2>No sensitive capital action should move because a button looked available.</h2><p>The chamber prioritizes universal exact-version approvals while preserving legacy coordinator, case, AI and Data Room decisions. Material changes supersede old authority automatically.</p><div><PrimaryButton onClick={()=>setModal("create")}>Create approval request</PrimaryButton><SecondaryButton onClick={()=>selected?setModal("decision"):action.validate("Select an approval first.")}>Open decision stamp</SecondaryButton></div></div><div className={styles.seal}><Stamp/><strong>{pending}</strong><span>Pending decisions</span><TruthChip kind="approval">Founder governance</TruthChip></div></section>
   <section className={styles.metrics}><MetricTile label="Pending" value={String(pending)} detail="Pending, required or review states." tone={pending?"red":"green"}/><MetricTile label="Approved" value={String(approved)} detail="Persisted approved states." tone="green"/><MetricTile label="Revision requested" value={String(revision)} detail="Items returned for correction." tone={revision?"amber":"blue"}/><MetricTile label="Critical exposure" value={String(critical)} detail="Reason/risk language indicates sensitive exposure." tone={critical?"violet":"green"}/></section>

   <section className={styles.queue}><SectionHeading eyebrow="Approval Queue" title="Founder-controlled capital actions" copy="Every card exposes its source object, risk reason, due date, affected content and decision state."/>
    {approvals.length?<div className={styles.approvalGrid}>{approvals.map(row=><button key={`${text(row,["source_table"])}-${String(row.id)}`} className={`${styles.approvalCard} ${selected?.id===row.id&&selected?.source_table===row.source_table?styles.selected:""}`} onClick={()=>setSelected(row)}><div><StatusBadge value={text(row,["status"],"Pending Review")}/><span>{text(row,["source_type"],"Approval")}</span></div><FileLock2/><strong>{text(row,["approval_title","approval_item","title"],"Approval request")}</strong><p>{text(row,["reason_required","reason"],"No approval reason returned.")}</p><footer><span><Clock3 size={12}/>{shortDate(row.due_at||row.due_date)}</span><span><ShieldAlert size={12}/>{text(row,["risk_if_unapproved","target_approver"],"Founder review")}</span></footer></button>)}</div>:<EmptyState title="No approval requests" copy="Create a request or generate one from a case, AI action, Data Room item or coordinator mission. No pending count is fabricated." action="Create approval request" onAction={()=>setModal("create")}/>}
   </section>

   <section className={styles.controlledActions}><SectionHeading eyebrow="Mandatory Governance" title="Actions that belong in the chamber"/><div>{["Final bank submission","VC introduction","Equity / dilution communication","Financial projection release","Final pitch deck","Founder biography use","Women-cofounder positioning","Sensitive email","International claims","Legal / compliance claims","Doctrine activation","AI sensitive action","Final proof package"].map(item=><article key={item}><LockKeyhole/><strong>{item}</strong><span>Founder or authorized approval required before external execution.</span></article>)}</div></section>
  </>}

  <Drawer open={Boolean(selected)} title={selected?text(selected,["approval_title","approval_item","title"],"Approval"):"Approval"} eyebrow="Approval Request Drawer" onClose={()=>setSelected(null)} footer={<><SecondaryButton onClick={()=>{setDecision("request-revision");setModal("decision")}}>Request revision</SecondaryButton><SecondaryButton onClick={()=>{setDecision("reject");setModal("decision")}}>Reject</SecondaryButton><PrimaryButton onClick={()=>{setDecision("approve");setModal("decision")}}>Approve</PrimaryButton></>}>
   {selected?<><FactGrid facts={[{label:"Source",value:text(selected,["source_type"])},{label:"Source table",value:text(selected,["source_table"])},{label:"Status",value:text(selected,["status"])},{label:"Object",value:text(selected,["object_type"],"Legacy approval")},{label:"Exact version",value:text(selected,["object_version"],"—")},{label:"Risk",value:text(selected,["risk_level","risk_if_unapproved"],"—")},{label:"Approver",value:text(selected,["approving_founder","approver","target_approver","approver_role"])},{label:"Due / expiry",value:shortDate(selected.due_at||selected.due_date||selected.expires_at)},{label:"Related object",value:text(selected,["object_id","related_case_id","case_id"],"—")}]}/><div className={styles.drawerBlock}><h3>Version-bound evidence</h3><p><b>Requested decision:</b> {text(selected,["decision_requested"],"Legacy decision")}</p><p><b>Snapshot:</b> {selected.snapshot?"Persisted exact-version snapshot":"Legacy source record"}</p><p><b>Evidence package:</b> {selected.evidence_package?"Attached":"Not attached"}</p></div><div className={styles.drawerBlock}><h3>Risk & reason</h3><p>{text(selected,["reason_required","reason"],"No reason returned.")}</p><p><b>Risk if unapproved:</b> {text(selected,["risk_if_unapproved"],"Not recorded")}</p></div><div className={styles.drawerBlock}><h3>Decision history</h3><AuditTimeline items={(Array.isArray(selected.approval_history)?selected.approval_history:[]).map((item,index)=>{const row=item as Record<string,unknown>;return {title:String(row.status||row.decision||`Decision ${index+1}`),meta:String(row.actor||"Founder")+" · "+shortDate(row.at),note:String(row.note||"")}})}/></div></>:null}
  </Drawer>

  <Dialog open={modal==="create"} title="Create Founder Approval Request" eyebrow="Governance Escalation" wide onClose={()=>{setModal(null);action.reset()}} footer={<><SecondaryButton onClick={()=>setModal(null)}>Cancel</SecondaryButton><PrimaryButton onClick={()=>void createRequest()}>Create request</PrimaryButton></>}><div className={styles.formGrid}><Field label="Approval title"><input value={create.title} onChange={e=>setCreate({...create,title:e.target.value})}/></Field><Field label="Approving founder"><input value={create.approvingFounder} onChange={e=>setCreate({...create,approvingFounder:e.target.value})}/></Field><Field label="Reason"><textarea value={create.reason} onChange={e=>setCreate({...create,reason:e.target.value})}/></Field><Field label="Risk if unapproved"><textarea value={create.riskIfUnapproved} onChange={e=>setCreate({...create,riskIfUnapproved:e.target.value})}/></Field><Field label="Due at"><input type="datetime-local" value={create.dueAt} onChange={e=>setCreate({...create,dueAt:e.target.value})}/></Field><Field label="Related case ID"><input value={create.relatedCaseId} onChange={e=>setCreate({...create,relatedCaseId:e.target.value})}/></Field><Field label="Related document ID"><input value={create.relatedDocumentId} onChange={e=>setCreate({...create,relatedDocumentId:e.target.value})}/></Field></div><ActionFeedback phase={action.state.phase} message={action.state.message}/></Dialog>

  <Dialog open={modal==="decision"} title="Founder Decision Stamp" eyebrow="Persisted Approval Decision" onClose={()=>{setModal(null);action.reset()}} footer={<><SecondaryButton onClick={()=>setModal(null)}>Cancel</SecondaryButton><PrimaryButton onClick={()=>void decide()}>Persist decision</PrimaryButton></>}><div className={styles.decisions}><button className={decision==="approve"?styles.decisionActive:""} onClick={()=>setDecision("approve")}><CheckCircle2/>Approve</button><button className={decision==="reject"?styles.decisionActive:""} onClick={()=>setDecision("reject")}><XCircle/>Reject</button><button className={decision==="request-revision"?styles.decisionActive:""} onClick={()=>setDecision("request-revision")}><RotateCcw/>Request revision</button></div><Field label="Founder note"><textarea value={note} onChange={e=>setNote(e.target.value)}/></Field><TruthChip kind="approval">This updates the source approval record; it does not execute the waiting external action automatically.</TruthChip><ActionFeedback phase={action.state.phase} message={action.state.message}/></Dialog>
 </AcCapitalShell>
}
