"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, BrainCircuit, CheckCircle2, GitBranch, Play, RefreshCw, ShieldCheck, Sparkles, Workflow } from "lucide-react";
import { AcCapitalShell } from "../../core/AcCapitalShell";
import styles from "./orchestrator.module.css";
type Row = Record<string, any>;
const text=(v:any)=>String(v??""); const fmt=(v:any)=>new Intl.DateTimeFormat("fr-FR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v));
export function OrchestratorPage(){
 const [data,setData]=useState<Row>({}); const [busy,setBusy]=useState(""); const [error,setError]=useState("");
 const load=useCallback(async()=>{setError(""); const r=await fetch('/api/ac-capital-os/orchestrator',{cache:'no-store'}); const j=await r.json(); if(!r.ok||j.ok===false) throw new Error(j.error||j.message||'LOAD_FAILED'); setData(j.data||j);},[]);
 useEffect(()=>{void load().catch(e=>setError(e.message));},[load]);
 const act=async(action:string,payload:Row={})=>{setBusy(action);setError('');try{const r=await fetch('/api/ac-capital-os/orchestrator',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})});const j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.error||j.message||'ACTION_FAILED');await load();}catch(e:any){setError(e.message)}finally{setBusy('')}};
 const workflows=(data.workflows||[]) as Row[], events=(data.events||[]) as Row[], agents=(data.agents||[]) as Row[], approvals=(data.approvals||[]) as Row[], integrity=(data.integrity||[]) as Row[], doctrine=(data.doctrine||[]) as Row[];
 const active=workflows.filter(x=>['active','blocked','waiting-approval'].includes(text(x.status))).length, queued=events.filter(x=>['queued','processing'].includes(text(x.status))).length, critical=integrity.filter(x=>x.status==='open'&&['critical','high'].includes(text(x.severity))).length, pending=approvals.filter(x=>x.status==='pending').length;
 return <AcCapitalShell activeKey="orchestrator"><main className={styles.page}>
  <header className={styles.hero}><div><span><BrainCircuit size={16}/> CAPITAL EXECUTIVE ORCHESTRATOR</span><h1>One AI-operated capital department—not disconnected rooms.</h1><p>Event-driven internal execution across research, underwriting, proof, case production, pipeline, approvals, coordinator missions, reporting and learning.</p></div><div className={styles.actions}><button onClick={()=>void act('process-queue',{maxEvents:20})} disabled={!!busy}><Play size={15}/> Process queue</button><button onClick={()=>void act('integrity-scan')} disabled={!!busy}><ShieldCheck size={15}/> Integrity scan</button><button onClick={()=>void act('compile-doctrine')} disabled={!!busy}><Sparkles size={15}/> Compile doctrine</button><button onClick={()=>void load()}><RefreshCw size={15}/></button></div></header>
  {error?<div className={styles.error}><AlertTriangle size={16}/>{error}</div>:null}
  <section className={styles.metrics}>{[[Workflow,'Active workflows',active],[Activity,'Queued events',queued],[AlertTriangle,'Critical integrity',critical],[ShieldCheck,'Pending approvals',pending],[BrainCircuit,'Enabled agents',agents.filter(x=>x.enabled).length]].map(([I,l,v]:any)=><article key={l}><I size={19}/><span>{l}</span><strong>{v}</strong></article>)}</section>
  <section className={styles.grid}><article className={styles.panel}><div className={styles.panelHead}><div><span>DEPARTMENT FLOW</span><h2>Active capital lifecycles</h2></div><GitBranch/></div><div className={styles.list}>{workflows.slice(0,15).map(w=><div className={styles.workflow} key={w.id}><div><b>{text(w.title)}</b><small>{text(w.current_stage)} · {text(w.status)}</small></div><p>{text(w.next_action||w.blocked_reason||'Awaiting orchestrator decision')}</p><time>{fmt(w.updated_at||w.created_at)}</time></div>)}{!workflows.length?<p className={styles.empty}>No workflow yet. Validate evidence or materialize an opportunity to start the chain.</p>:null}</div></article>
  <article className={styles.panel}><div className={styles.panelHead}><div><span>AGENT REGISTRY</span><h2>Capital executive team</h2></div><BrainCircuit/></div><div className={styles.agentGrid}>{agents.map(a=><div key={a.id}><i className={a.enabled?styles.live:styles.off}/><b>{text(a.agent_name)}</b><span>{text(a.workspace_key)} · {text(a.capability)}</span><small>{a.external_actions_allowed?'External authority':'Internal-only authority'}</small></div>)}</div></article></section>
  <section className={styles.grid}><article className={styles.panel}><div className={styles.panelHead}><div><span>EVENT BUS</span><h2>Department execution evidence</h2></div><Activity/></div><div className={styles.table}><table><thead><tr><th>Event</th><th>Entity</th><th>Workspace</th><th>Status</th><th>Time</th></tr></thead><tbody>{events.slice(0,30).map(e=><tr key={e.id}><td>{text(e.event_type)}</td><td>{text(e.entity_type)}</td><td>{text(e.source_workspace)}</td><td><b data-status={e.status}>{text(e.status)}</b></td><td>{fmt(e.created_at)}</td></tr>)}</tbody></table></div></article>
  <article className={styles.panel}><div className={styles.panelHead}><div><span>INTEGRITY CONTROL</span><h2>Broken-chain prevention</h2></div><ShieldCheck/></div><div className={styles.list}>{integrity.filter(x=>x.status==='open').slice(0,20).map(i=><div className={styles.issue} key={i.id}><AlertTriangle size={15}/><div><b>{text(i.title)}</b><span>{text(i.issue_code)} · {text(i.entity_type)}</span><p>{text(i.recommended_action)}</p></div></div>)}{!integrity.filter(x=>x.status==='open').length?<div className={styles.good}><CheckCircle2/> No open integrity issue detected.</div>:null}</div></article></section>
  <section className={styles.grid}><article className={styles.panel}><div className={styles.panelHead}><div><span>FOUNDER AUTHORITY</span><h2>Universal approvals</h2></div><ShieldCheck/></div><div className={styles.list}>{approvals.slice(0,20).map(a=><div className={styles.approval} key={a.id}><div><b>{text(a.approval_type)}</b><span>{text(a.object_type)} · version {text(a.object_version)}</span><p>{text(a.decision_requested)}</p></div>{a.status==='pending'?<div><button onClick={()=>void act('approval-decision',{approvalId:a.id,decision:'approved'})}>Approve</button><button className={styles.reject} onClick={()=>void act('approval-decision',{approvalId:a.id,decision:'rejected'})}>Reject</button></div>:<strong>{text(a.status)}</strong>}</div>)}</div></article>
  <article className={styles.panel}><div className={styles.panelHead}><div><span>EXECUTABLE DOCTRINE</span><h2>Latest compiled capital brain</h2></div><Sparkles/></div>{doctrine[0]?<div className={styles.doctrine}><b>{text(doctrine[0].compilation_key)}</b><span>Status: {text(doctrine[0].status)}</span><p>{Object.keys(doctrine[0].effective_bundle||{}).length} doctrine domains compiled.</p><time>{fmt(doctrine[0].compiled_at)}</time></div>:<p className={styles.empty}>Compile the Doctrine Vault to create the effective agent policy bundle.</p>}</article></section>
 </main></AcCapitalShell>
}
