export const SERVICE_OS_ROUTES = [
  { href:'/services', label:'Services Catalog', tier:'core' },
  { href:'/services/blueprints', label:'Blueprint Studio', tier:'core' },
  { href:'/services/blueprints/new', label:'New Blueprint', tier:'action' },
  { href:'/services/configuration', label:'Configuration', tier:'core' },
  { href:'/services/rules', label:'Rules', tier:'core' },
  { href:'/services/operations', label:'Operations', tier:'execution' },
  { href:'/services/workflows', label:'Workflows', tier:'execution' },
  { href:'/services/incidents', label:'Incidents', tier:'quality' },
  { href:'/services/commercial', label:'Commercial', tier:'revenue' },
  { href:'/services/pricing-engine', label:'Pricing Engine', tier:'revenue' },
  { href:'/services/subscriptions', label:'Subscriptions', tier:'revenue' },
  { href:'/services/live-ops', label:'LiveOps', tier:'execution' },
  { href:'/services/capacity', label:'Capacity', tier:'expansion' },
  { href:'/services/expansion', label:'Expansion', tier:'expansion' },
  { href:'/services/client-journey', label:'Client Journey', tier:'client' },
  { href:'/services/contracts', label:'Contracts', tier:'client' },
  { href:'/services/compliance', label:'Compliance', tier:'client' },
  { href:'/services/ai-matching', label:'AI Matching', tier:'ai' },
  { href:'/services/ai-strategy', label:'AI Strategy', tier:'ai' },
  { href:'/services/market-intelligence', label:'Market Intelligence', tier:'ai' },
  { href:'/services/enterprise', label:'Enterprise Command', tier:'command' },
] as const
