"use client"

import { useEffect, useMemo, useState } from "react"
import { Bot, BrainCircuit, CheckCircle2, CirclePause, CirclePlay, ShieldCheck, SlidersHorizontal, Sparkles, Target, UserRoundCheck, XCircle } from "lucide-react"
import { cx, ModalFrame, NoticeBanner, ProgressBar, StatusPill } from "./ACWhatsAppUI"
import { acApi, friendlyAcError } from "./useAcWhatsApp"
import type { AcWhatsAppConversation } from "@/lib/ac-whatsapp/types"

const modes = [
  {id:"manual",label:"Human only",detail:"Aucune réponse autonome. Le moteur conserve son intelligence en assistance.",tone:"slate"},
  {id:"assist",label:"Assist",detail:"Analyse, prochaine action et suggestion — validation humaine avant envoi.",tone:"blue"},
  {id:"selected_auto",label:"AUTO · Cette conversation",detail:"Autonomie gouvernée sur ce fil uniquement selon seuils, doctrine et risques.",tone:"emerald"},
  {id:"account_auto",label:"AUTO · Compte",detail:"Ce fil suit la politique du compte et les doctrines admissibles.",tone:"violet"},
  {id:"protected",label:"Protected",detail:"Conversation explicitement exclue de toute autonomie flotte.",tone:"rose"},
]

export default function ConversationRevenueAutomationControl({conversation,onChanged,onNotice}:{conversation:AcWhatsAppConversation;onChanged:()=>void|Promise<void>;onNotice:(tone:"success"|"warning"|"danger"|"info",title:string,description:string)=>void}){
  const [open,setOpen]=useState(false)
  const [data,setData]=useState<any>(null)
  const [loading,setLoading]=useState(false)
  const [busy,setBusy]=useState(false)
  const current=String((conversation as any).automation_mode||((conversation as any).automation_paused?"manual":"assist"))
  const active=current==="selected_auto"||current==="account_auto"

  async function load(){setLoading(true);try{setData(await acApi(`/api/ac-whatsapp/revenue-intelligence/conversations/${conversation.id}/automation`))}catch(cause){const f=friendlyAcError(cause);onNotice("danger",f.title,f.description)}finally{setLoading(false)}}
  useEffect(()=>{if(open)void load()},[open,conversation.id])

  async function update(patch:any){setBusy(true);try{await acApi(`/api/ac-whatsapp/revenue-intelligence/conversations/${conversation.id}/automation`,{method:"PATCH",body:JSON.stringify(patch)});await load();await onChanged();onNotice("success","Automation gouvernée actualisée","Le mode, la doctrine et la prise de contrôle humaine sont maintenant persistés et audités.")}catch(cause){const f=friendlyAcError(cause);onNotice("danger",f.title,f.description)}finally{setBusy(false)}}

  async function evaluate(){setBusy(true);try{const result=await acApi<any>("/api/ac-whatsapp/revenue-intelligence/runtime/evaluate",{method:"POST",body:JSON.stringify({conversation_id:conversation.id,dry_run:true})});setData((prev:any)=>({...prev,preview:result}));onNotice("info","Décision locale simulée",`Action ${result.decision?.action||"—"} · confiance ${Math.round(Number(result.decision?.confidence||0)*100)}%.`)}catch(cause){const f=friendlyAcError(cause);onNotice("danger",f.title,f.description)}finally{setBusy(false)}}
  async function teach(eventType:string){const decisionId=data?.preview?.decisionRow?.id||data?.state?.last_decision_id||null;try{await acApi("/api/ac-whatsapp/revenue-intelligence/learning",{method:"POST",body:JSON.stringify({conversation_id:conversation.id,decision_id:decisionId,event_type:eventType,metadata:{source:"live_command_control"}})});onNotice("success","Learning evidence captured","Le feedback est enregistré comme preuve de maturité et ne modifie jamais une doctrine live sans gouvernance.")}catch(cause){const f=friendlyAcError(cause);onNotice("danger",f.title,f.description)}}

  return <>
    <button type="button" onClick={()=>setOpen(true)} className={cx("acw-composer-tool",active?"is-healthy":current==="protected"?"is-warning":"")} title="Sovereign Revenue Intelligence"><Bot className="h-3.5 w-3.5"/>{active?"AUTO Revenue":current==="protected"?"Protégé":"Automation"}</button>
    {open?<ModalFrame title="Revenue Intelligence · Conversation Control" eyebrow="Sovereign autonomy gate" description="Choisissez qui contrôle ce fil, avec quelle doctrine et sous quels garde-fous. L’opérateur conserve toujours la priorité." onClose={()=>setOpen(false)} footer={<div className="flex flex-wrap items-center justify-between gap-2"><button type="button" onClick={()=>void evaluate()} disabled={busy} className="inline-flex items-center gap-2 rounded-xl border border-sky-200 bg-sky-50 px-4 py-2.5 text-[9px] font-black text-sky-800"><Sparkles className="h-3.5 w-3.5"/>Simuler maintenant</button><button type="button" onClick={()=>setOpen(false)} className="rounded-xl bg-slate-950 px-4 py-2.5 text-[9px] font-black text-white">Fermer</button></div>}>
      {loading&&!data?<div className="grid min-h-60 place-items-center"><BrainCircuit className="h-7 w-7 animate-pulse text-sky-600"/></div>:null}
      {data?<div className="space-y-5">
        <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-5">{modes.map(mode=><button key={mode.id} type="button" disabled={busy} onClick={()=>void update({mode:mode.id,paused:mode.id==="manual"||mode.id==="protected",excluded:mode.id==="protected",reason:`Live Command mode ${mode.id}`})} className={cx("rounded-[20px] border p-3 text-left transition",String(data.state?.mode||current)===mode.id?"border-sky-300 bg-slate-950 text-white shadow-lg":"border-slate-200 bg-white hover:border-sky-200")}><div className="flex items-center justify-between"><span className={cx("grid h-8 w-8 place-items-center rounded-xl",String(data.state?.mode||current)===mode.id?"bg-white/10 text-sky-300":"bg-slate-100 text-slate-700")}>{mode.id==="protected"?<ShieldCheck className="h-3.5 w-3.5"/>:mode.id==="manual"?<UserRoundCheck className="h-3.5 w-3.5"/>:mode.id==="assist"?<BrainCircuit className="h-3.5 w-3.5"/>:<Bot className="h-3.5 w-3.5"/>}</span>{String(data.state?.mode||current)===mode.id?<CheckCircle2 className="h-4 w-4 text-emerald-400"/>:null}</div><p className={cx("mt-3 text-[9px] font-black",String(data.state?.mode||current)===mode.id?"text-white":"text-slate-900")}>{mode.label}</p><p className={cx("mt-1 text-[8px] font-semibold leading-4",String(data.state?.mode||current)===mode.id?"text-slate-300":"text-slate-500")}>{mode.detail}</p></button>)}</div>
        <div className="grid gap-4 lg:grid-cols-[1fr_320px]">
          <div className="rounded-[24px] border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between"><div><p className="text-[8px] font-black uppercase tracking-[.14em] text-slate-400">Doctrine pack</p><p className="mt-1 text-[12px] font-black text-slate-950">Commercial brain affecté</p></div><Target className="h-5 w-5 text-sky-600"/></div><select value={data.state?.doctrine_pack_id||""} onChange={e=>void update({mode:data.state?.mode||current,paused:Boolean(data.conversation?.automation_paused),doctrine_pack_id:e.target.value||null,reason:"Doctrine assignment from Live Command"})} className="mt-4 w-full rounded-2xl border border-slate-200 bg-white px-3 py-3 text-[9px] font-black text-slate-800"><option value="">Auto-select doctrine</option>{(data.packs||[]).map((pack:any)=><option key={pack.id} value={pack.id}>{pack.name} · {pack.maturity_level} · fit {pack.applicability_score}%</option>)}</select><input defaultValue={data.state?.current_goal||""} placeholder="Objectif commercial spécifique (optionnel)" onBlur={e=>{const value=e.currentTarget.value.trim();if(value!==String(data.state?.current_goal||""))void update({mode:data.state?.mode||current,paused:Boolean(data.conversation?.automation_paused),goal:value||null,reason:"Commercial goal update from Live Command"})}} className="mt-3 w-full rounded-2xl border border-slate-200 bg-white px-3 py-3 text-[9px] font-bold text-slate-800 outline-none focus:border-sky-300"/></div>
          <div className="rounded-[24px] border border-slate-200 bg-white p-4"><p className="text-[8px] font-black uppercase tracking-[.14em] text-slate-400">Current intelligence</p><div className="mt-3 space-y-2"><Row label="Journey" value={data.state?.journey_stage||"unknown"}/><Row label="Intent" value={data.state?.intent_family||"unknown"}/><Row label="Relation" value={data.state?.relationship_temperature||"unknown"}/><Row label="Momentum" value={data.state?.momentum||"unknown"}/><Row label="Maturity" value={data.state?.maturity_level||"L0"}/></div></div>
        </div>
        {data.preview?<div className="rounded-[24px] border border-sky-200 bg-sky-50/60 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[8px] font-black uppercase tracking-[.14em] text-sky-700">Decision preview</p><p className="mt-1 text-[12px] font-black text-slate-950">{String(data.preview.decision?.action||"—").toUpperCase()} · {Math.round(Number(data.preview.decision?.confidence||0)*100)}%</p></div><StatusPill status={data.preview.decision?.eligibility||"info"} label={String(data.preview.decision?.eligibility||"—").toUpperCase()} compact/></div><p className="mt-3 whitespace-pre-wrap text-[10px] font-semibold leading-5 text-slate-800">{data.preview.decision?.responseText||"Aucune réponse autonome : protection, attente ou handoff."}</p><div className="mt-3"><ProgressBar value={Math.round(Number(data.preview.decision?.confidence||0)*100)} tone={Number(data.preview.decision?.confidence||0)>=.82?"emerald":Number(data.preview.decision?.confidence||0)>=.55?"blue":"amber"} label="Confidence"/></div><div className="mt-4 flex flex-wrap gap-1.5">{[["good_response","Bonne réponse"],["wrong_reasoning","Raisonnement faux"],["wrong_tone","Ton faux"],["missed_sales_opportunity","Vente manquée"],["too_aggressive","Trop agressif"],["too_passive","Trop passif"],["should_escalate","Devait escalader"]].map(([id,label])=><button key={id} type="button" onClick={()=>void teach(id)} className="rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-[7px] font-black text-slate-600 hover:border-sky-200 hover:text-sky-800">{label}</button>)}</div></div>:null}
        <NoticeBanner tone="info" title="Human priority is absolute" description="Prendre la main, mode Protected ou une exclusion de consentement bloque immédiatement l’autonomie. Les contextes à risque élevé passent en handoff au lieu d’être exploités commercialement."/>
      </div>:null}
    </ModalFrame>:null}
  </>
}
function Row({label,value}:{label:string;value:any}){return <div className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2"><span className="text-[8px] font-black uppercase tracking-[.1em] text-slate-400">{label}</span><span className="max-w-[160px] truncate text-[9px] font-black text-slate-900">{String(value||"—").replaceAll("_"," ")}</span></div>}
