import { requireMarketplaceApiContext } from '../auth/context'
import { apiFailure,apiSuccess,cleanOptionalText,parseJsonObject,requestId } from '../server/request'
import { analyticsSummary,executeIsolationTest,listAccessReviews,listBackups,listDataQuality,listIsolationTests,listMetricDefinitions,listRecoveryTests,listRetentionPolicies,listSecurityEvents,listSnapshots,refreshAnalytics,securitySummary,transitionRecoveryTest } from './repository'
export async function handleAnalyticsSummary(request:Request){const id=requestId(request);try{return apiSuccess(await analyticsSummary(await requireMarketplaceApiContext('marketplace.analytics.view')),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleMetrics(request:Request){const id=requestId(request);try{await requireMarketplaceApiContext('marketplace.analytics.view');return apiSuccess(await listMetricDefinitions(),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleSnapshots(request:Request){const id=requestId(request);try{const context=await requireMarketplaceApiContext('marketplace.analytics.view');return apiSuccess(await listSnapshots(context,new URL(request.url).searchParams.get('domain')||undefined),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleDataQuality(request:Request){const id=requestId(request);try{await requireMarketplaceApiContext('marketplace.analytics.view');return apiSuccess(await listDataQuality(),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleAnalyticsRefresh(request:Request){const id=requestId(request);try{return apiSuccess(await refreshAnalytics(await requireMarketplaceApiContext('marketplace.analytics.definitions.manage'),id,request),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleSecuritySummary(request:Request){const id=requestId(request);try{await requireMarketplaceApiContext('marketplace.security.view');return apiSuccess(await securitySummary(),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleAccessReviews(request:Request){const id=requestId(request);try{return apiSuccess(await listAccessReviews(await requireMarketplaceApiContext('marketplace.security.access_review')),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleIsolationTests(request:Request){const id=requestId(request);try{return apiSuccess(await listIsolationTests(await requireMarketplaceApiContext('marketplace.security.isolation.review')),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleSecurityEvents(request:Request){const id=requestId(request);try{return apiSuccess(await listSecurityEvents(await requireMarketplaceApiContext('marketplace.security.events.view')),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleRetention(request:Request){const id=requestId(request);try{await requireMarketplaceApiContext('marketplace.security.view');return apiSuccess(await listRetentionPolicies(),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleBackups(request:Request){const id=requestId(request);try{await requireMarketplaceApiContext('marketplace.backup.view');return apiSuccess(await listBackups(),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleRecoveryTests(request:Request){const id=requestId(request);try{await requireMarketplaceApiContext('marketplace.backup.view');return apiSuccess(await listRecoveryTests(),{requestId:id})}catch(error){return apiFailure(error,id)}}
export async function handleIsolationExecution(request:Request,id:string){const rid=requestId(request);try{const context=await requireMarketplaceApiContext('marketplace.security.isolation.review');const body=await parseJsonObject(request);return apiSuccess(await executeIsolationTest(id,String(body.observedResult||''),typeof body.evidence==='object'&&body.evidence!==null?body.evidence as Record<string,unknown>:{},context,rid,request),{requestId:rid})}catch(error){return apiFailure(error,rid)}}
export async function handleRecoveryTransition(request:Request,id:string){const rid=requestId(request);try{const context=await requireMarketplaceApiContext('marketplace.recovery_test.approve');const body=await parseJsonObject(request);return apiSuccess(await transitionRecoveryTest(id,String(body.nextStatus||''),cleanOptionalText(body.reason,2000),context,rid,request),{requestId:rid})}catch(error){return apiFailure(error,rid)}}
