#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const htmlPath = path.join(__dirname, '../dist/index.html');
const outPath = path.join(__dirname, '../src/views/dist-index.ts');

export function embedFrontend() {
  if (!fs.existsSync(htmlPath)) {
    throw new Error('dist/index.html not found. Run vite build first.');
  }

  const html = fs.readFileSync(htmlPath, 'utf8');
  const output = [
    '/* AUTO-GENERATED by npm run build - edit src/views/frontend instead */',
    `const template = ${JSON.stringify(html)};`,
    '',
    'export default template;',
  ].join('\n');

  fs.writeFileSync(outPath, output);
  console.log(`[embed] Wrote ${html.length.toLocaleString()} chars to src/views/dist-index.ts`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    embedFrontend();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
