import { createClient } from '@/lib/supabase/server'
import { Angelcare360AccessError, getAngelcare360AccessContext, type Angelcare360AccessContext } from '@/lib/angelcare360/server/context'
import { recordAngelcare360AuditEventServer } from '@/lib/angelcare360/server/audit'
import type { Angelcare360Area12CommandData, Angelcare360Area12Dossier, Angelcare360Area12Matter, Angelcare360Area12Metric, Angelcare360Area12MutationRequest, Angelcare360Area12MutationResult, Angelcare360Area12TimelineEvent, Angelcare360Area12Tone, Angelcare360Area12View } from '@/types/angelcare360/parent-relationship-area12'

type Row=Record<string,any>
type Client=Awaited<ReturnType<typeof createClient>>
type Area12AccessContext=Angelcare360AccessContext & { school:NonNullable<Angelcare360AccessContext['school']> }
export const ANGELCARE360_AREA12_VIEWS:Angelcare360Area12View[]=['today', 'requests', 'communications', 'meetings', 'commitments', 'complaints', 'resolutions', 'satisfaction', 'family-care', 'renewals', 'departure-risk', 'feedback', 'attention', 'ownership', 'history', 'performance']
export const ANGELCARE360_AREA12_OPERATIONS=[
  'parent_request.view',
  'parent_request.view_sensitive',
  'parent_request.create',
  'parent_request.assign',
  'parent_request.acknowledge',
  'parent_request.respond',
  'parent_request.request_information',
  'parent_request.wait_family',
  'parent_request.wait_team',
  'parent_request.prepare_response',
  'parent_request.resolve',
  'parent_request.verify_resolution',
  'parent_request.close',
  'parent_request.reopen',
  'parent_request.escalate',
  'parent_request.link_source',
  'parent_communication.view',
  'parent_communication.view_sensitive',
  'parent_communication.prepare',
  'parent_communication.send',
  'parent_communication.record_inbound',
  'parent_communication.record_outbound',
  'parent_communication.link_matter',
  'parent_communication.acknowledge',
  'parent_communication.request_acknowledgement',
  'parent_communication.mark_unreachable',
  'parent_meeting.view',
  'parent_meeting.create',
  'parent_meeting.confirm',
  'parent_meeting.reschedule',
  'parent_meeting.prepare',
  'parent_meeting.add_agenda',
  'parent_meeting.record_outcome',
  'parent_meeting.create_followup',
  'parent_meeting.cancel',
  'parent_meeting.record_no_show',
  'parent_commitment.view',
  'parent_commitment.create',
  'parent_commitment.assign',
  'parent_commitment.update',
  'parent_commitment.complete',
  'parent_commitment.verify',
  'parent_commitment.mark_waiting',
  'parent_commitment.mark_impossible',
  'parent_commitment.cancel',
  'parent_commitment.reopen',
  'parent_commitment.escalate',
  'parent_complaint.view',
  'parent_complaint.view_sensitive',
  'parent_complaint.create',
  'parent_complaint.acknowledge',
  'parent_complaint.qualify',
  'parent_complaint.assign',
  'parent_complaint.add_evidence',
  'parent_complaint.request_information',
  'parent_complaint.escalate',
  'parent_complaint.add_observation',
  'parent_complaint.prepare_resolution',
  'parent_complaint.request_approval',
  'parent_complaint.approve_resolution',
  'parent_complaint.resolve',
  'parent_complaint.confirm_resolution',
  'parent_complaint.close',
  'parent_complaint.reopen',
  'service_recovery.view',
  'service_recovery.create',
  'service_recovery.assign',
  'service_recovery.add_action',
  'service_recovery.complete_action',
  'service_recovery.prepare_response',
  'service_recovery.complete',
  'service_recovery.verify',
  'service_recovery.reopen',
  'parent_satisfaction.view',
  'parent_satisfaction.create_campaign',
  'parent_satisfaction.send',
  'parent_satisfaction.record_response',
  'parent_satisfaction.request_followup',
  'parent_satisfaction.assign_followup',
  'parent_satisfaction.complete_followup',
  'parent_relationship.view',
  'parent_relationship.view_sensitive',
  'parent_relationship.create_attention',
  'parent_relationship.assign_attention',
  'parent_relationship.update_attention',
  'parent_relationship.resolve_attention',
  'parent_relationship.reopen_attention',
  'parent_relationship.add_context',
  'parent_renewal.view',
  'parent_renewal.prepare',
  'parent_renewal.contact',
  'parent_renewal.record_intent',
  'parent_renewal.request_meeting',
  'parent_renewal.record_condition',
  'parent_renewal.confirm_relationship',
  'parent_renewal.defer',
  'parent_renewal.mark_not_renewing',
  'parent_renewal.handover',
  'parent_renewal.reopen',
  'parent_departure.view',
  'parent_departure.create_case',
  'parent_departure.record_reason',
  'parent_departure.request_intervention',
  'parent_departure.record_intervention',
  'parent_departure.prepare_handover',
  'parent_departure.confirm',
  'parent_departure.handover',
  'parent_departure.cancel',
  'parent_departure.reopen',
  'parent_feedback.view',
  'parent_feedback.create',
  'parent_feedback.review',
  'parent_feedback.assign',
  'parent_feedback.convert_action',
  'parent_feedback.acknowledge',
  'parent_feedback.close',
  'parent_handoff.view',
  'parent_handoff.create',
  'parent_handoff.accept',
  'parent_handoff.return',
  'parent_handoff.complete',
  'parent_handoff.escalate',
  'parent_task.view',
  'parent_task.assign',
  'parent_task.complete',
  'parent_task.reopen',
  'parent_note.add',
  'parent_evidence.request',
  'parent_history.view',
  'parent_topup.request'
] as const
const T={cases:'angelcare360_area12_relationship_cases',requests:'angelcare360_area12_parent_requests',communications:'angelcare360_area12_communication_links',meetings:'angelcare360_area12_meetings',commitments:'angelcare360_area12_commitments',complaints:'angelcare360_area12_complaints',recoveries:'angelcare360_area12_service_recoveries',campaigns:'angelcare360_area12_satisfaction_campaigns',responses:'angelcare360_area12_satisfaction_responses',attention:'angelcare360_area12_attention_cases',renewals:'angelcare360_area12_renewal_cases',departures:'angelcare360_area12_departure_cases',feedback:'angelcare360_area12_feedback',handoffs:'angelcare360_area12_handoffs',tasks:'angelcare360_area12_tasks',notes:'angelcare360_area12_notes',receipts:'angelcare360_area12_action_receipts'} as const
const text=(v:any,f='')=>typeof v==='string'&&v.trim()?v.trim():f
const opt=(v:any)=>{const s=text(v);return s||null}
const tone=(status:string,priority='normal'):Angelcare360Area12Tone=>priority==='critical'||['escalated','overdue','blocked'].includes(status)?'danger':['open','pending','waiting','review'].includes(status)?'warning':['resolved','closed','completed','confirmed'].includes(status)?'success':'info'
async function rows(client:Client,table:string,schoolId:string,limit=120):Promise<Row[]> { const {data,error}=await client.from(table).select('*').eq('school_id',schoolId).order('updated_at',{ascending:false}).limit(limit); if(error) return []; return (data||[]) as Row[] }
async function access(operation?:string):Promise<Area12AccessContext> { const context=await getAngelcare360AccessContext(); if(!context?.school) throw new Angelcare360AccessError('Aucun établissement actif.',403); if(!context.access.canSeePeopleData) throw new Angelcare360AccessError('Accès relation parents non autorisé.',403); if(operation && !ANGELCARE360_AREA12_OPERATIONS.includes(operation as any)) throw new Angelcare360AccessError('Opération Relation Parents inconnue.',422); return {...context,school:context.school} }
const metric=(key:string,label:string,value:number|string,detail:string,toneValue:Angelcare360Area12Tone,targetView:Angelcare360Area12View):Angelcare360Area12Metric=>({key,label,value,detail,tone:toneValue,targetView})
function label(row:Row) { return text(row.display_name)||text(row.family_label)||text(row.full_name)||text(row.title)||text(row.name)||'Famille' }
function matter(kind:Angelcare360Area12Matter['kind'],r:Row,families:Map<string,string>):Angelcare360Area12Matter { const status=text(r.status,'open'); const priority=text(r.priority,'normal'); const familyId=opt(r.family_id); return {id:text(r.id),kind,familyId,parentId:opt(r.parent_id)||opt(r.person_id),studentId:opt(r.student_id),familyLabel:familyId?families.get(familyId)||'Famille':'Famille',parentLabel:opt(r.parent_label),studentLabel:opt(r.student_label),title:text(r.title)||text(r.subject)||text(r.complaint_subject)||text(r.commitment_text)||kind,detail:text(r.description)||text(r.detail)||text(r.body)||text(r.reason)||'',status,priority,ownerLabel:opt(r.owner_label)||opt(r.assignee_label),dueAt:opt(r.due_at)||opt(r.response_due_at),updatedAt:opt(r.updated_at)||opt(r.created_at),tone:tone(status,priority),nextAction:opt(r.next_action),deepLink:opt(r.deep_link)} }
async function dossier(client:Client,schoolId:string,familyId:string,familyLabel:string):Promise<Angelcare360Area12Dossier> { const all=await Promise.all([rows(client,T.requests,schoolId),rows(client,T.communications,schoolId),rows(client,T.meetings,schoolId),rows(client,T.commitments,schoolId),rows(client,T.complaints,schoolId),rows(client,T.recoveries,schoolId),rows(client,T.responses,schoolId),rows(client,T.renewals,schoolId),rows(client,T.departures,schoolId),rows(client,T.feedback,schoolId),rows(client,T.tasks,schoolId),rows(client,T.notes,schoolId)]); const by=(xs:Row[])=>xs.filter(x=>text(x.family_id)===familyId); const events:Angelcare360Area12TimelineEvent[]=[]; const event=(xs:Row[],category:string,titleKey:string='title')=>by(xs).forEach(r=>events.push({id:`${category}:${r.id}`,at:opt(r.updated_at)||opt(r.created_at),category,title:text(r[titleKey])||text(r.subject)||category,detail:text(r.description)||text(r.detail)||text(r.body)||text(r.status),source:'Area 12',tone:tone(text(r.status,'open'),text(r.priority,'normal'))})); event(all[0],'Demande');event(all[1],'Échange');event(all[2],'Rendez-vous');event(all[3],'Engagement','commitment_text');event(all[4],'Réclamation');event(all[7],'Réinscription');event(all[8],'Départ');event(all[9],'Retour & suggestion'); events.sort((a,b)=>(b.at||'').localeCompare(a.at||''));
 const {data:family}=await client.from('angelcare360_area11_families').select('*').eq('school_id',schoolId).eq('id',familyId).maybeSingle(); const {data:links}=await client.from('angelcare360_area11_family_memberships').select('*').eq('school_id',schoolId).eq('family_id',familyId).limit(100); const {data:studentLinks}=await client.from('angelcare360_area11_relationships').select('*').eq('school_id',schoolId).eq('family_id',familyId).limit(100);
 return {familyId,familyLabel:label((family||{display_name:familyLabel}) as Row),children:(studentLinks||[]) as Row[],adults:(links||[]) as Row[],requests:by(all[0]),communications:by(all[1]),meetings:by(all[2]),commitments:by(all[3]),complaints:by(all[4]),recoveries:by(all[5]),satisfaction:by(all[6]),renewals:by(all[7]),departures:by(all[8]),feedback:by(all[9]),tasks:by(all[10]),notes:by(all[11]),timeline:events,sourceWarnings:[]} }
export async function loadAngelcare360Area12Command(input:{view?:string;familyId?:string|null}={}):Promise<Angelcare360Area12CommandData> { const context=await access(); const client=await createClient(); const schoolId=context.school!.id; const view=ANGELCARE360_AREA12_VIEWS.includes(input.view as Angelcare360Area12View)?input.view as Angelcare360Area12View:'today'; const {data:familyRows}=await client.from('angelcare360_area11_families').select('id,display_name,family_code,status').eq('school_id',schoolId).limit(500); const families=new Map<string,string>(((familyRows||[]) as Row[]).map(r=>[text(r.id),label(r)])); const data=await Promise.all([rows(client,T.requests,schoolId),rows(client,T.communications,schoolId),rows(client,T.meetings,schoolId),rows(client,T.commitments,schoolId),rows(client,T.complaints,schoolId),rows(client,T.recoveries,schoolId),rows(client,T.responses,schoolId),rows(client,T.attention,schoolId),rows(client,T.renewals,schoolId),rows(client,T.departures,schoolId),rows(client,T.feedback,schoolId),rows(client,T.tasks,schoolId)]); const matters:Angelcare360Area12Matter[]=[...data[0].map(r=>matter('request',r,families)),...data[1].map(r=>matter('communication',r,families)),...data[2].map(r=>matter('meeting',r,families)),...data[3].map(r=>matter('commitment',r,families)),...data[4].map(r=>matter('complaint',r,families)),...data[5].map(r=>matter('recovery',r,families)),...data[6].map(r=>matter('satisfaction',r,families)),...data[7].map(r=>matter('attention',r,families)),...data[8].map(r=>matter('renewal',r,families)),...data[9].map(r=>matter('departure',r,families)),...data[10].map(r=>matter('feedback',r,families)),...data[11].map(r=>matter('task',r,families))]; const now=Date.now(); const overdue=matters.filter(m=>m.dueAt&&new Date(m.dueAt).getTime()<now&&!['resolved','closed','completed','confirmed'].includes(m.status)).length; const metrics=[metric('requests','Demandes à traiter',data[0].filter(r=>!['resolved','closed'].includes(text(r.status))).length,'Demandes parents encore actives.','info','requests'),metric('overdue','Échéances dépassées',overdue,'Réponses ou engagements au-delà du délai.','danger','attention'),metric('meetings','Rendez-vous',data[2].filter(r=>['scheduled','confirmed','open'].includes(text(r.status))).length,'Rendez-vous à préparer.','violet','meetings'),metric('complaints','Réclamations ouvertes',data[4].filter(r=>!['closed','resolved'].includes(text(r.status))).length,'Réclamations nécessitant suivi.','warning','complaints'),metric('renewals','Réinscriptions',data[8].filter(r=>!['confirmed','not_renewing','closed'].includes(text(r.status))).length,'Familles en parcours de réinscription.','success','renewals'),metric('care','Familles à accompagner',data[7].filter(r=>!['resolved','closed'].includes(text(r.status))).length,'Signaux relationnels explicables nécessitant attention.','warning','family-care')]; const selected=input.familyId?await dossier(client,schoolId,input.familyId,families.get(input.familyId)||'Famille'):null; return {view,school:{id:schoolId,name:context.school!.name},academicYear:{id:context.academicYear?.id||null,label:context.academicYear?.label||'Année en cours'},metrics,matters,selectedDossier:selected,sourceWarnings:[],permissions:Array.from(context.permissions),generatedAt:new Date().toISOString()} }
async function priorReceipt(client:Client,schoolId:string,operation:string,key:string) { const {data}=await client.from(T.receipts).select('*').eq('school_id',schoolId).eq('operation_key',operation).eq('idempotency_key',key).maybeSingle(); return data as Row|null }
async function receipt(client:Client,row:Row) { const {data,error}=await client.from(T.receipts).insert(row).select('id').single(); if(error) throw new Error(error.message); return text(data?.id) }
function targetTable(operation:string) { if(operation.startsWith('parent_request.'))return T.requests;if(operation.startsWith('parent_communication.'))return T.communications;if(operation.startsWith('parent_meeting.'))return T.meetings;if(operation.startsWith('parent_commitment.'))return T.commitments;if(operation.startsWith('parent_complaint.'))return T.complaints;if(operation.startsWith('service_recovery.'))return T.recoveries;if(operation.startsWith('parent_satisfaction.'))return T.responses;if(operation.startsWith('parent_relationship.'))return T.attention;if(operation.startsWith('parent_renewal.'))return T.renewals;if(operation.startsWith('parent_departure.'))return T.departures;if(operation.startsWith('parent_feedback.'))return T.feedback;if(operation.startsWith('parent_handoff.'))return T.handoffs;if(operation.startsWith('parent_task.'))return T.tasks;if(operation.startsWith('parent_note.'))return T.notes;return T.tasks }
function nextStatus(operation:string,current='open') { const a=operation.split('.').pop()||''; const map:Record<string,string>={acknowledge:'acknowledged',assign:'open',respond:'response_sent',request_information:'waiting',wait_family:'waiting_family',wait_team:'waiting_team',prepare_response:'response_prepared',resolve:'resolved',verify_resolution:'verified',close:'closed',reopen:'open',escalate:'escalated',confirm:'confirmed',complete:'completed',verify:'verified',cancel:'cancelled',record_no_show:'no_show',mark_waiting:'waiting',mark_impossible:'impossible',approve_resolution:'approved',confirm_resolution:'confirmed',record_intent:'intent_recorded',mark_not_renewing:'not_renewing',handover:'handed_over',activate:'active'}; return map[a]||current }
export async function executeAngelcare360Area12Operation(request:Angelcare360Area12MutationRequest):Promise<Angelcare360Area12MutationResult> { const operation=text(request.operation),subjectId=text(request.subjectId),key=text(request.idempotencyKey); if(!operation||!subjectId||!key) throw new Angelcare360AccessError('Opération, matière et clé d’intégrité obligatoires.',422); const context=await access(operation); const client=await createClient(); const schoolId=context.school!.id; const existing=await priorReceipt(client,schoolId,operation,key); if(existing) {const r=(existing.result_json||{}) as Row;return {ok:true,operation,subjectKind:request.subjectKind,subjectId,receiptId:text(existing.id),message:text(r.message,'Opération déjà enregistrée.'),deepLink:opt(r.deepLink),refresh:true,data:(r.data||null) as Row|null}} const payload=(request.payload||{}) as Row; const table=targetTable(operation); let data:Row|null=null; let deepLink:string|null=null; let message='Action Relation Parents enregistrée.'; const isCreate=['create','prepare','create_campaign','record_inbound','record_outbound','record_response','add','request','assign'].some(x=>operation.endsWith('.'+x)); if(isCreate) { const row:Row={school_id:schoolId,family_id:opt(payload.familyId)||(request.subjectKind==='family'?subjectId:null),parent_id:opt(payload.parentId)||(request.subjectKind==='person'?subjectId:null),student_id:opt(payload.studentId)||(request.subjectKind==='student'?subjectId:null),title:text(payload.title)||text(payload.subject)||operation,description:opt(payload.description)||opt(payload.detail),status:text(payload.status,'open'),priority:text(payload.priority,'normal'),owner_user_id:opt(payload.ownerUserId),due_at:opt(payload.dueAt),next_action:opt(payload.nextAction),deep_link:opt(payload.deepLink),metadata:payload.metadata||{},created_by_user_id:context.user.id}; const {data:d,error}=await client.from(table).insert(row).select('*').single(); if(error) throw new Error(error.message);data=d as Row;message='Matter relationnelle créée et placée sous responsabilité.' } else if(['view','view_sensitive'].some(x=>operation.endsWith('.'+x))||operation==='parent_history.view') { deepLink=request.subjectKind==='family'?`/angelcare-360-command-center/relation-parents/${subjectId}`:`/angelcare-360-command-center/relation-parents?subject=${encodeURIComponent(subjectId)}`; message='Ouverture de la matière canonique.' } else if(operation==='parent_evidence.request') { deepLink=`/angelcare-360-command-center/administration?plane=audit&view=evidence&entity=family&entityId=${encodeURIComponent(subjectId)}&source=parent-relationship`; message='Demande de preuve préparée dans l’autorité Audit.' } else if(operation==='parent_topup.request') { deepLink='/angelcare-360-operator/platform?source=parent-relationship'; message='Demande de capacité préparée.' } else { const patch:Row={status:nextStatus(operation,text(payload.currentStatus,'open')),updated_at:new Date().toISOString(),next_action:opt(payload.nextAction)}; if(operation.includes('complete')||operation.includes('resolve')||operation.includes('close')) patch.resolved_at=new Date().toISOString(); const {data:d,error}=await client.from(table).update(patch).eq('school_id',schoolId).eq('id',opt(payload.matterId)||subjectId).select('*').maybeSingle(); if(error) throw new Error(error.message); data=d as Row|null; message=`Action ${operation} appliquée avec résultat traçable.` } const result={message,deepLink,data}; const rid=await receipt(client,{school_id:schoolId,operation_key:operation,idempotency_key:key,subject_kind:request.subjectKind,subject_id:subjectId,actor_user_id:context.user.id,result_json:result,status:'completed'}); await recordAngelcare360AuditEventServer({schoolId,category:'parent',module:'parent_relationship',action:operation,entityType:request.subjectKind,entityId:subjectId,severity:operation.includes('complaint')||operation.includes('escalate')?'warning':'info',beforeData:{operation},afterData:data||{},metadata:{area:12,idempotency_key:key,receipt_id:rid,no_black_box_scoring:true,area11_identity_preserved:true}} as any); return {ok:true,operation,subjectKind:request.subjectKind,subjectId,receiptId:rid,message,deepLink,refresh:true,data} }
