import {MarketplaceError} from '../server/errors'
const allowedExperimentTransitions:Record<string,string[]>={draft:['review'],review:['approved','rejected'],approved:['scheduled','cancelled'],scheduled:['running','cancelled'],running:['paused','completed','stopped'],paused:['running','stopped'],completed:['rollout_approved','archived'],stopped:['archived'],rollout_approved:['archived'],rejected:['draft'],cancelled:['archived'],archived:[]}
const allowedDefectTransitions:Record<string,string[]>={detected:['triaged'],triaged:['assigned','rejected'],assigned:['in_correction'],in_correction:['verification'],verification:['regression','reopened'],regression:['evidence_review','reopened'],evidence_review:['closed','reopened'],reopened:['assigned'],closed:[],rejected:[]}
const allowedReleaseTransitions:Record<string,string[]>={draft:['evidence_collection'],evidence_collection:['gate_review','blocked'],gate_review:['conditional_approval','approved_for_limited_release','approved_for_phased_release','approved_for_production','blocked'],conditional_approval:['gate_review','approved_for_limited_release','blocked'],approved_for_limited_release:['released','blocked'],approved_for_phased_release:['released','blocked'],approved_for_production:['released','blocked'],released:['paused','rolled_back','monitoring'],monitoring:['closed','paused','rolled_back'],paused:['monitoring','rolled_back'],rolled_back:['closed'],blocked:['evidence_collection'],closed:[]}
function assertTransition(map:Record<string,string[]>,current:string,next:string,label:string){if(!map[current]?.includes(next))throw new MarketplaceError('VALIDATION_ERROR',`Transition ${label} interdite: ${current} → ${next}.`)}
export const assertExperimentTransition=(c:string,n:string)=>assertTransition(allowedExperimentTransitions,c,n,'expérience')
export const assertDefectTransition=(c:string,n:string)=>assertTransition(allowedDefectTransitions,c,n,'défaut')
export const assertReleaseTransition=(c:string,n:string)=>assertTransition(allowedReleaseTransitions,c,n,'release')
export function assertLaunchEvidence(gates:Array<{requirement_level:string;status:string;evidence_status:string}>,criticalDefects:number,securityBlockers:number){const blocked=gates.filter(g=>g.requirement_level.startsWith('mandatory')&&(g.status!=='passed'||g.evidence_status!=='accepted'));if(blocked.length||criticalDefects||securityBlockers)throw new MarketplaceError('VALIDATION_ERROR','Autorisation de lancement refusée: gates obligatoires, défaut critique ou sécurité non résolus.')}
