import {createServiceClient} from '@/lib/supabase/server'
import type {MarketplaceRequestContext} from '../domain/types'
import {MarketplaceError} from '../server/errors'
import {writeMarketplaceAudit} from '../audit/write-audit'
import type {AcademyAssessment,AcademyAssessmentResult,AcademyB2BTrainingOrder,AcademyCohort,AcademyCourse,AcademyEnrollment,AcademyProgram,AcademySession} from './types'
import type {AcademyFinalSnapshot,AcademyRemediation} from './final-types'
import {assertAcademyPublicationTransition,assertB2BTransition,assertCohortFinalTransition,assertSessionTransition} from './final-validation'
const rows=<T>(v:unknown):T[]=>Array.isArray(v)?v as T[]:[]
function fail(action:string,error:unknown):never{throw new MarketplaceError('INTERNAL_ERROR',`Impossible de ${action}.`,{cause:error,retryable:true})}
function scoped(q:any,c:MarketplaceRequestContext){if(c.roleKeys.includes('marketplace_admin'))return q;if(c.tenantId)return q.eq('tenant_id',c.tenantId);if(c.territoryId)return q.eq('territory_id',c.territoryId);return q}
async function list<T>(table:string,c:MarketplaceRequestContext,order='updated_at'){const db=await createServiceClient();let q=db.from(table).select('*').order(order,{ascending:false}).limit(500);q=scoped(q,c);const{data,error}=await q;if(error)fail(`charger ${table}`,error);return rows<T>(data)}
export async function academyFinalSnapshot(c:MarketplaceRequestContext):Promise<AcademyFinalSnapshot>{const[programs,courses,cohorts,sessions,enrollments,attendance,assessments,results,certificates,b2bOrders,remediations]=await Promise.all([list<AcademyProgram>('angelcare_marketplace_academy_programs',c),list<AcademyCourse>('angelcare_marketplace_academy_courses',c),list<AcademyCohort>('angelcare_marketplace_academy_cohorts',c),list<AcademySession>('angelcare_marketplace_academy_sessions',c,'starts_at'),list<AcademyEnrollment>('angelcare_marketplace_academy_enrollments',c,'enrolled_at'),list('angelcare_marketplace_academy_attendance_records',c,'recorded_at'),list<AcademyAssessment>('angelcare_marketplace_academy_assessments',c),list<AcademyAssessmentResult>('angelcare_marketplace_academy_assessment_results',c,'assessed_at'),list('angelcare_marketplace_academy_certificates',c,'updated_at'),list<AcademyB2BTrainingOrder>('angelcare_marketplace_academy_b2b_training_orders',c),list<AcademyRemediation>('angelcare_marketplace_academy_remediations',c)]);return{programs,courses,cohorts,sessions,enrollments,attendance:attendance as AcademyFinalSnapshot['attendance'],assessments,results,certificates:certificates as AcademyFinalSnapshot['certificates'],b2bOrders,remediations}}
export async function createAcademySession(input:{cohortId:string;title:string;startsAt:string;endsAt:string;deliveryMode:string;trainerId:string|null;location:Record<string,unknown>},c:MarketplaceRequestContext,requestId:string,request?:Request){const db=await createServiceClient();if(new Date(input.endsAt)<=new Date(input.startsAt))throw new MarketplaceError('VALIDATION_ERROR','La fin de session doit suivre le début.');const{data,error}=await db.from('angelcare_marketplace_academy_sessions').insert({cohort_id:input.cohortId,title_fr:input.title,starts_at:input.startsAt,ends_at:input.endsAt,delivery_mode:input.deliveryMode,trainer_id:input.trainerId,location:input.location,status:'scheduled',territory_id:c.territoryId,tenant_id:c.tenantId}).select('*').single();if(error)fail('créer la session Academy',error);await writeMarketplaceAudit({context:c,requestId,request,action:'academy.session.created',objectType:'academy_session',objectId:String(data.id),afterValue:data});return data}
export async function transitionAcademySession(id:string,next:string,reason:string,c:MarketplaceRequestContext,requestId:string,request?:Request){const db=await createServiceClient();const{data:current,error:e}=await db.from('angelcare_marketplace_academy_sessions').select('*').eq('id',id).single();if(e||!current)fail('charger la session',e);assertSessionTransition(String(current.status),next);const patch:Record<string,unknown>={status:next,updated_at:new Date().toISOString()};if(next==='completed')patch.attendance_locked=true;const{data,error}=await db.from('angelcare_marketplace_academy_sessions').update(patch).eq('id',id).select('*').single();if(error)fail('faire évoluer la session',error);await writeMarketplaceAudit({context:c,requestId,request,action:`academy.session.${next}`,objectType:'academy_session',objectId:id,beforeValue:current,afterValue:data,reason});return data}
export async function transitionAcademyCohort(id:string,next:string,reason:string,c:MarketplaceRequestContext,requestId:string,request?:Request){const db=await createServiceClient();const{data:current,error:e}=await db.from('angelcare_marketplace_academy_cohorts').select('*').eq('id',id).single();if(e||!current)fail('charger la cohorte',e);assertCohortFinalTransition(String(current.status),next);const{data,error}=await db.from('angelcare_marketplace_academy_cohorts').update({status:next,updated_by:c.actor.id,updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)fail('faire évoluer la cohorte',error);await writeMarketplaceAudit({context:c,requestId,request,action:`academy.cohort.${next}`,objectType:'academy_cohort',objectId:id,beforeValue:current,afterValue:data,reason});return data}
export async function createAcademyAssessment(input:{courseId:string;cohortId:string|null;title:string;assessmentType:string;passingScore:number;rubric:Record<string,unknown>},c:MarketplaceRequestContext,requestId:string,request?:Request){const db=await createServiceClient();const{data,error}=await db.from('angelcare_marketplace_academy_assessments').insert({course_id:input.courseId,cohort_id:input.cohortId,title_fr:input.title,assessment_type:input.assessmentType,passing_score:input.passingScore,rubric:input.rubric,status:'draft',territory_id:c.territoryId,tenant_id:c.tenantId}).select('*').single();if(error)fail('créer l’évaluation',error);await writeMarketplaceAudit({context:c,requestId,request,action:'academy.assessment.created',objectType:'academy_assessment',objectId:String(data.id),afterValue:data});return data}
export async function reviewAssessmentResult(id:string,decision:'approved'|'rejected',reason:string,c:MarketplaceRequestContext,requestId:string,request?:Request){const db=await createServiceClient();const{data:current,error:e}=await db.from('angelcare_marketplace_academy_assessment_results').select('*').eq('id',id).single();if(e||!current)fail('charger le résultat',e);if(!['pending_review','appealed'].includes(String(current.status)))throw new MarketplaceError('VALIDATION_ERROR','Ce résultat n’est pas en attente de revue.');const{data,error}=await db.from('angelcare_marketplace_academy_assessment_results').update({status:decision,reviewed_by:c.actor.id,reviewed_at:new Date().toISOString(),evidence:{...(current.evidence||{}),review_reason:reason}}).eq('id',id).select('*').single();if(error)fail('décider le résultat',error);await writeMarketplaceAudit({context:c,requestId,request,action:`academy.assessment_result.${decision}`,objectType:'academy_assessment_result',objectId:id,beforeValue:current,afterValue:data,reason,severity:decision==='rejected'?'warning':'info'});return data}
export async function createAcademyRemediation(input:{enrollmentId:string;assessmentResultId:string|null;reason:string;actionPlan:string;dueAt:string|null},c:MarketplaceRequestContext,requestId:string,request?:Request){const db=await createServiceClient();const{data,error}=await db.from('angelcare_marketplace_academy_remediations').insert({enrollment_id:input.enrollmentId,assessment_result_id:input.assessmentResultId,reason:input.reason,action_plan:input.actionPlan,status:'open',owner_id:c.actor.id,due_at:input.dueAt,territory_id:c.territoryId,tenant_id:c.tenantId,created_by:c.actor.id}).select('*').single();if(error)fail('ouvrir la remédiation',error);await writeMarketplaceAudit({context:c,requestId,request,action:'academy.remediation.opened',objectType:'academy_remediation',objectId:String(data.id),afterValue:data,severity:'warning'});return data}
export async function transitionAcademyRemediation(id:string,next:string,reason:string,c:MarketplaceRequestContext,requestId:string,request?:Request){if(!['in_progress','evidence_review','completed','cancelled','reopened'].includes(next))throw new MarketplaceError('VALIDATION_ERROR','Statut remédiation invalide.');const db=await createServiceClient();const{data:current,error:e}=await db.from('angelcare_marketplace_academy_remediations').select('*').eq('id',id).single();if(e||!current)fail('charger la remédiation',e);const{data,error}=await db.from('angelcare_marketplace_academy_remediations').update({status:next,completed_at:next==='completed'?new Date().toISOString():null,updated_at:new Date().toISOString(),evidence:{...(current.evidence||{}),transition_reason:reason}}).eq('id',id).select('*').single();if(error)fail('faire évoluer la remédiation',error);await writeMarketplaceAudit({context:c,requestId,request,action:`academy.remediation.${next}`,objectType:'academy_remediation',objectId:id,beforeValue:current,afterValue:data,reason});return data}
export async function transitionAcademyB2B(id:string,next:string,reason:string,c:MarketplaceRequestContext,requestId:string,request?:Request){const db=await createServiceClient();const{data:current,error:e}=await db.from('angelcare_marketplace_academy_b2b_training_orders').select('*').eq('id',id).single();if(e||!current)fail('charger la commande B2B',e);assertB2BTransition(String(current.status),next);const{data,error}=await db.from('angelcare_marketplace_academy_b2b_training_orders').update({status:next,updated_by:c.actor.id,updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)fail('faire évoluer la commande B2B',error);await writeMarketplaceAudit({context:c,requestId,request,action:`academy.b2b.${next}`,objectType:'academy_b2b_order',objectId:id,beforeValue:current,afterValue:data,reason});return data}
export async function transitionAcademyPublication(kind:'program'|'course',id:string,next:string,reason:string,c:MarketplaceRequestContext,requestId:string,request?:Request){const table=kind==='program'?'angelcare_marketplace_academy_programs':'angelcare_marketplace_academy_courses',db=await createServiceClient();const{data:current,error:e}=await db.from(table).select('*').eq('id',id).single();if(e||!current)fail(`charger ${kind}`,e);assertAcademyPublicationTransition(String(current.status),next);const patch:Record<string,unknown>={status:next,updated_by:c.actor.id,updated_at:new Date().toISOString()};if(next==='published'&&kind==='program')patch.published_at=new Date().toISOString();const{data,error}=await db.from(table).update(patch).eq('id',id).select('*').single();if(error)fail(`faire évoluer ${kind}`,error);await writeMarketplaceAudit({context:c,requestId,request,action:`academy.${kind}.${next}`,objectType:`academy_${kind}`,objectId:id,beforeValue:current,afterValue:data,reason});return data}


export async function assignAcademyTrainer(cohortId:string,trainerId:string,reason:string,c:MarketplaceRequestContext,requestId:string,request?:Request){
 const db=await createServiceClient()
 const[{data:cohort,error:cohortError},{data:profile,error:profileError},{data:eligibility,error:eligibilityError}]=await Promise.all([
  db.from('angelcare_marketplace_academy_cohorts').select('*').eq('id',cohortId).single(),
  db.from('angelcare_marketplace_provider_profiles').select('id,operational_status,territory_id,tenant_id,service_categories').eq('id',trainerId).single(),
  db.from('angelcare_marketplace_provider_operational_eligibility').select('status,blockers,eligible_services,eligible_territories,calculated_at').eq('provider_id',trainerId).order('calculated_at',{ascending:false}).limit(1).maybeSingle(),
 ])
 if(cohortError||!cohort)fail('charger la cohorte',cohortError)
 if(profileError||!profile)throw new MarketplaceError('NOT_FOUND','Trainer/provider introuvable.')
 if(eligibilityError)fail('charger l’éligibilité trainer',eligibilityError)
 if(!eligibility||!['eligible','eligible_with_restrictions'].includes(String(eligibility.status)))throw new MarketplaceError('DEPENDENCY_BLOCKED','Trainer non éligible opérationnellement.',{cause:{blockers:eligibility?.blockers||[]}})
 if(c.tenantId&&profile.tenant_id&&String(profile.tenant_id)!==c.tenantId)throw new MarketplaceError('FORBIDDEN','Trainer hors tenant autorisé.')
 if(c.territoryId&&profile.territory_id&&String(profile.territory_id)!==c.territoryId)throw new MarketplaceError('FORBIDDEN','Trainer hors territoire autorisé.')
 const before=cohort
 const{data,error}=await db.from('angelcare_marketplace_academy_cohorts').update({trainer_id:trainerId,updated_by:c.actor.id,updated_at:new Date().toISOString()}).eq('id',cohortId).select('*').single()
 if(error||!data)fail('affecter le trainer',error)
 await writeMarketplaceAudit({context:c,requestId,request,action:'academy.cohort.trainer_assigned',objectType:'academy_cohort',objectId:cohortId,beforeValue:before,afterValue:data,reason,severity:'info',source:'reality-completion'})
 return data
}
