import { BriefcaseBusiness, Clock3, FileCheck2, ShieldCheck } from 'lucide-react'
import type { ApprovalItem } from '@/types/homeservice-design'
import { Badge, EmptyState, MetricCard, Panel, WorkspaceTitle } from '../DesignSystem'
import { ApprovalDecisionAction } from '../MutationPanels'

export function ApprovalInboxWorkspace({ approvals }: { approvals: ApprovalItem[] }) {
  const pending = approvals.filter((item) => item.status === 'pending')
  return <div className="space-y-6"><WorkspaceTitle eyebrow="Autorité humaine" title="Approval & Decision Chamber" description="Centralise les validations techniques, standards, exceptions et imports. Chaque décision expose sa conséquence, ses preuves et l’autorité qui l’assume." />
    <section className="grid gap-4 md:grid-cols-3"><MetricCard label="En attente" value={pending.length} detail="Décisions devant être assumées" tone="amber" icon={<Clock3 size={18} />} /><MetricCard label="Approuvées" value={approvals.filter((item) => item.status === 'approved').length} detail="Décisions historiques visibles" tone="emerald" icon={<ShieldCheck size={18} />} /><MetricCard label="Preuves rattachées" value={approvals.reduce((sum, item) => sum + item.evidenceCount, 0)} detail="Éléments de décision enregistrés" tone="blue" icon={<FileCheck2 size={18} />} /></section>
    <Panel title="Decision Queue" subtitle="Créateur et approbateur restent séparables; l’IA ne décide jamais.">{pending.length ? <div className="space-y-4">{pending.map((item) => <article key={item.id} className="rounded-[26px] border border-amber-200 bg-gradient-to-r from-amber-50 to-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-amber-100 text-amber-800"><BriefcaseBusiness size={20} /></div><div><p className="text-[9px] font-black uppercase tracking-[0.2em] text-amber-700">{item.approvalType} · {item.entityType}</p><h3 className="mt-1 text-lg font-black text-slate-950">{item.entityLabel}</h3><p className="mt-2 text-xs font-semibold text-slate-500">Demandé par {item.requestedBy} · Autorité: {item.assignedRole}</p></div></div><Badge tone="amber">Décision requise</Badge></div><div className="mt-5 grid gap-3 lg:grid-cols-2"><div className="rounded-2xl bg-white p-4 ring-1 ring-slate-100"><p className="text-[9px] font-black uppercase tracking-[0.15em] text-slate-400">Conséquence</p><p className="mt-2 text-xs font-semibold leading-5 text-slate-700">{item.consequenceSummary || 'Conséquence à préciser dans la demande.'}</p></div><div className="rounded-2xl bg-white p-4 ring-1 ring-slate-100"><p className="text-[9px] font-black uppercase tracking-[0.15em] text-slate-400">Blocages / preuves</p><p className="mt-2 text-xs font-semibold leading-5 text-slate-700">{item.blockerSummary.join(' · ') || 'Aucun blocage déclaré'} · {item.evidenceCount} preuve(s)</p></div></div><div className="mt-5 flex flex-wrap justify-end gap-2"><ApprovalDecisionAction approvalId={item.id} decision="return" label="Retour correction" tone="amber" /><ApprovalDecisionAction approvalId={item.id} decision="reject" label="Rejeter" tone="rose" /><ApprovalDecisionAction approvalId={item.id} decision="approve" label="Approuver" tone="emerald" /></div></article>)}</div> : <EmptyState title="Aucune décision en attente" detail="La chambre restera vide tant qu’un dossier, une règle, un import ou une exception n’est pas soumis à validation." />}</Panel>
    {approvals.filter((item) => item.status !== 'pending').length ? <Panel title="Historique récent" subtitle="Les décisions passées restent consultables et ne sont jamais effacées."><div className="grid gap-3 lg:grid-cols-2">{approvals.filter((item) => item.status !== 'pending').slice(0, 12).map((item) => <div key={item.id} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex justify-between gap-3"><div><p className="text-[9px] font-black uppercase text-slate-400">{item.approvalType}</p><p className="mt-1 text-sm font-black">{item.entityLabel}</p></div><Badge tone={item.status === 'approved' ? 'emerald' : item.status === 'rejected' ? 'rose' : 'amber'}>{item.status}</Badge></div></div>)}</div></Panel> : null}
  </div>
}
