'use client'

import type { ReactNode } from 'react'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { Activity, ArrowLeft, BriefcaseBusiness, CheckCircle2, ChevronRight, ClipboardCheck, Database, Gauge, Layers3, LockKeyhole, MapPinned, PackageCheck, ShieldAlert, Sparkles, UsersRound } from 'lucide-react'
import type { CategoryDossier } from '@/types/homeservice-design'
import { readinessBand, statusLabel } from '@/lib/homeservice-design/constants'
import { Badge, EmptyState, MetricCard, Panel, ProgressBar, WarningBanner, WorkspaceTitle, cx } from '../DesignSystem'

const sectionIcons: Record<string, ReactNode> = {
  identity_positioning: <Sparkles size={17} />, doctrine_promise: <LockKeyhole size={17} />, customer_profiles: <BriefcaseBusiness size={17} />,
  beneficiary_profiles: <UsersRound size={17} />, capacity: <Gauge size={17} />, activities: <Activity size={17} />, staffing: <UsersRound size={17} />,
  materials: <PackageCheck size={17} />, safety: <ShieldAlert size={17} />, route_transport: <MapPinned size={17} />, quality_evidence: <ClipboardCheck size={17} />,
}

function DetailList({ rows }: { rows: Array<[string, ReactNode]> }) {
  return <div className="divide-y divide-slate-100">{rows.map(([label, value]) => <div key={label} className="grid gap-2 py-3 sm:grid-cols-[190px_1fr]"><span className="text-[10px] font-black uppercase tracking-[0.15em] text-slate-400">{label}</span><span className="text-sm font-bold text-slate-800">{value}</span></div>)}</div>
}

export function CategoryDossierWorkspace({ dossier }: { dossier: CategoryDossier }) {
  const [activeSection, setActiveSection] = useState(dossier.sections[0]?.sectionCode || 'identity_positioning')
  const section = dossier.sections.find((item) => item.sectionCode === activeSection) || dossier.sections[0]
  const readiness = readinessBand(dossier.overallReadiness)
  const sectionContent = useMemo(() => {
    if (activeSection === 'identity_positioning') return <DetailList rows={[["Nom commercial", dossier.commercialNameFr], ["Nom opérationnel", dossier.operationalNameFr], ["Code stable", dossier.code], ["Audience", dossier.audience.toUpperCase()], ["Version", `V${dossier.versionNumber}`], ["Langues", dossier.languages.join(' · ') || 'À configurer'], ["Villes", dossier.cities.join(' · ') || 'À configurer'], ["Type CARELINK", dossier.carelinkServiceType || 'Mapping requis']]}/>
    if (activeSection === 'doctrine_promise') return dossier.doctrineRules.length ? <div className="space-y-3">{dossier.doctrineRules.map((rule) => <article key={rule.id} className={cx('rounded-2xl border p-4', rule.blocking ? 'border-rose-200 bg-rose-50' : 'border-slate-200 bg-white')}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[0.18em] text-slate-400">{rule.code} · {rule.kind}</p><h4 className="mt-1 text-sm font-black text-slate-950">{rule.titleFr}</h4></div><Badge tone={rule.blocking ? 'rose' : rule.severity === 'critical' ? 'amber' : 'blue'}>{rule.severity}</Badge></div><p className="mt-3 text-xs font-semibold leading-5 text-slate-600">{rule.descriptionFr}</p>{rule.requiredEvidence.length ? <p className="mt-3 text-[10px] font-bold text-slate-500">Preuves: {rule.requiredEvidence.join(' · ')}</p> : null}</article>)}</div> : <EmptyState title="Doctrine à construire" detail="La catégorie ne possède pas encore de règle de doctrine enregistrée." />
    if (activeSection === 'capacity') return dossier.capacityRule ? <DetailList rows={[["Durée mission", `${dossier.capacityRule.minimumHours} à ${dossier.capacityRule.maximumHours} h`], ["Plage horaire", `${dossier.capacityRule.earliestStartTime} → ${dossier.capacityRule.latestEndTime}`], ["Jours consécutifs max", dossier.capacityRule.maximumConsecutiveDays], ["Bénéficiaires / agent", dossier.capacityRule.maxBeneficiariesPerAgent], ["Agents minimum", dossier.capacityRule.minimumAgents], ["Backup", dossier.capacityRule.backupRequired ? 'Obligatoire' : 'Selon contexte'], ["Supervision", dossier.capacityRule.supervisorRequired ? 'Obligatoire' : 'Selon règle'], ["Préavis", `${dossier.capacityRule.leadTimeHours} h`], ["Villes autorisées", dossier.capacityRule.allowedCities.join(' · ') || 'Non limitées']]}/> : <EmptyState title="Capacité non configurée" detail="Aucune promesse de durée, ratio ou zone ne doit être considérée comme autorisée avant configuration." />
    if (activeSection === 'activities') return dossier.activities.length ? <div className="grid gap-3 md:grid-cols-2">{dossier.activities.map((activity) => <article key={activity.id} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[0.18em] text-blue-600">{activity.code}</p><h4 className="mt-1 text-sm font-black">{activity.nameFr}</h4></div><Badge tone="violet">{activity.minMinutes}–{activity.maxMinutes} min</Badge></div><p className="mt-3 text-xs font-semibold leading-5 text-slate-500">{activity.descriptionFr}</p><div className="mt-3 flex flex-wrap gap-1.5"><Badge tone="slate">{activity.energyLevel}</Badge><Badge tone="slate">{activity.locationType}</Badge>{activity.objectiveCodes.slice(0, 2).map((item) => <Badge key={item} tone="blue">{item}</Badge>)}</div></article>)}</div> : <EmptyState title="Aucun bloc compatible" detail="Le moteur UMZ2 ne pourra pas composer de déroulé tant que des activités validées ne sont pas liées à cette catégorie." />
    if (activeSection === 'staffing') return dossier.competencies.length ? <div className="grid gap-3 md:grid-cols-2">{dossier.competencies.map((item) => <div key={item.id} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between"><h4 className="text-sm font-black">{item.nameFr}</h4><Badge tone="blue">{item.family}</Badge></div><p className="mt-2 text-xs font-semibold leading-5 text-slate-500">{item.descriptionFr}</p><p className="mt-3 text-[10px] font-black uppercase text-slate-400">Preuve: {item.evidenceType}</p></div>)}</div> : <EmptyState title="Profil requis incomplet" detail="La catégorie ne peut pas prétendre à une exécution fiable sans exigences de compétences explicites." />
    if (activeSection === 'safety') return dossier.risks.length ? <div className="space-y-3">{dossier.risks.map((risk) => <article key={risk.id} className={cx('rounded-2xl border p-4', risk.stopWork ? 'border-rose-200 bg-rose-50' : 'border-amber-200 bg-amber-50/60')}><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[0.18em] text-slate-500">{risk.code}</p><h4 className="mt-1 text-sm font-black">{risk.nameFr}</h4></div><Badge tone={risk.stopWork ? 'rose' : 'amber'}>{risk.stopWork ? 'Arrêt obligatoire' : risk.severity}</Badge></div><p className="mt-3 text-xs font-semibold leading-5 text-slate-600">{risk.descriptionFr}</p><p className="mt-3 text-[10px] font-bold text-slate-500">Escalade: {risk.escalationRoute}</p></article>)}</div> : <EmptyState title="Matrice de risques vide" detail="Aucun service ne doit être déclaré prêt avant l’identification de ses risques et safeguards." />
    if (activeSection === 'features_upsells') return <div className="grid gap-4 lg:grid-cols-3"><Panel title="Fonctions incluses"><div className="space-y-2">{dossier.features.length ? dossier.features.map((item: any) => <div key={String(item.id)} className="rounded-xl bg-slate-50 p-3 text-xs font-bold">{String(item.name_fr || item.name || item.code)}</div>) : <p className="text-xs font-semibold text-slate-400">À configurer</p>}</div></Panel><Panel title="Top-ups"><div className="space-y-2">{dossier.topups.length ? dossier.topups.map((item: any) => <div key={String(item.id)} className="rounded-xl bg-blue-50 p-3 text-xs font-bold text-blue-800">{String(item.name_fr || item.name || item.code)}</div>) : <p className="text-xs font-semibold text-slate-400">À configurer</p>}</div></Panel><Panel title="Upsells"><div className="space-y-2">{dossier.upsells.length ? dossier.upsells.map((item: any) => <div key={String(item.id)} className="rounded-xl bg-violet-50 p-3 text-xs font-bold text-violet-800">{String(item.name_fr || item.name || item.code)}</div>) : <p className="text-xs font-semibold text-slate-400">À configurer</p>}</div></Panel></div>
    if (activeSection === 'pricing') return dossier.priceEntries.length ? <div className="overflow-x-auto rounded-2xl border border-slate-200"><table className="min-w-[760px] w-full text-left text-xs"><thead className="bg-slate-950 text-white"><tr><th className="p-3">Code</th><th>Base</th><th>Prix</th><th>Coût</th><th>Marge plancher</th><th>Effet</th></tr></thead><tbody>{dossier.priceEntries.map((item: any) => <tr key={String(item.id)} className="border-t border-slate-100"><td className="p-3 font-black">{String(item.code)}</td><td>{String(item.pricing_basis)}</td><td>{Number(item.unit_price_dh || 0).toFixed(2)} Dh</td><td>{Number(item.cost_amount_dh || 0).toFixed(2)} Dh</td><td>{Number(item.margin_floor_percent || 0)}%</td><td>{String(item.effective_from || 'À définir')}</td></tr>)}</tbody></table></div> : <EmptyState title="Tarification non configurée" detail="UMZ3 activera le noyau commercial; UMZ1 conserve déjà l’architecture de prix et d’import." />
    return <div className="grid gap-4 md:grid-cols-2"><div className="rounded-[24px] border border-slate-200 bg-white p-5"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-600">But de la section</p><p className="mt-3 text-sm font-semibold leading-6 text-slate-600">{section?.purposeFr || 'Section de dossier gouvernée.'}</p></div><div className="rounded-[24px] border border-slate-200 bg-slate-50 p-5"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400">État actuel</p><p className="mt-3 text-2xl font-black">{section?.completionPercent || 0}%</p><p className="mt-2 text-xs font-semibold text-slate-500">{section?.blockerCount || 0} blocage(s) · Responsable: {section?.ownerRole || 'À affecter'}</p></div></div>
  }, [activeSection, dossier, section])
  return (
    <div className="space-y-5">
      <section className="relative overflow-hidden rounded-[34px] border border-slate-800 bg-slate-950 p-6 text-white shadow-[0_26px_80px_rgba(15,23,42,0.24)] xl:p-8">
        <div className="pointer-events-none absolute -right-20 -top-24 h-72 w-72 rounded-full bg-blue-500/25 blur-3xl" />
        <div className="pointer-events-none absolute bottom-[-120px] left-[28%] h-64 w-64 rounded-full bg-violet-500/20 blur-3xl" />
        <div className="relative flex flex-wrap items-start justify-between gap-6">
          <div className="max-w-4xl">
            <Link href="/carelink-ops/service-design/catalogue/categories" className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-[10px] font-black uppercase tracking-[0.16em] text-slate-300 transition hover:bg-white/10 hover:text-white"><ArrowLeft size={13} /> Registre catégories</Link>
            <p className="mt-6 text-[10px] font-black uppercase tracking-[0.28em] text-blue-300">{dossier.familyName || 'Famille de services'} · {dossier.code}</p>
            <h1 className="mt-3 text-3xl font-black tracking-[-0.05em] sm:text-4xl xl:text-5xl">{dossier.commercialNameFr}</h1>
            <p className="mt-4 max-w-3xl text-sm font-semibold leading-7 text-slate-300">{dossier.descriptionFr}</p>
            <div className="mt-6 flex flex-wrap gap-2"><Badge tone={readiness.tone}>{dossier.overallReadiness}% · {readiness.label}</Badge><Badge tone="slate">Version {dossier.versionNumber}</Badge><Badge tone={dossier.carelinkServiceType ? 'emerald' : 'amber'}>{dossier.carelinkServiceType ? 'CARELINK mappé' : 'Mapping à configurer'}</Badge></div>
          </div>
          <div className="flex flex-col gap-2 sm:min-w-[230px]">
            <Link href={`/carelink-ops/service-design/factory/category/${dossier.code}?mode=single_mission`} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-blue-600 px-5 py-3 text-sm font-black text-white shadow-[0_16px_34px_rgba(37,99,235,0.35)] transition hover:bg-blue-500"><Sparkles size={17} /> Concevoir une mission</Link>
            <Link href={`/carelink-ops/service-design/factory/category/${dossier.code}?mode=multi_mission`} className="inline-flex items-center justify-center gap-2 rounded-2xl border border-white/15 bg-white/10 px-5 py-3 text-sm font-black text-white transition hover:bg-white/15"><Layers3 size={17} /> Créer un programme</Link>
            <Link href={`/carelink-ops/service-design/factory/category/${dossier.code}?mode=commercial_package`} className="inline-flex items-center justify-center gap-2 rounded-2xl border border-white/15 bg-white/10 px-5 py-3 text-sm font-black text-white transition hover:bg-white/15"><PackageCheck size={17} /> Composer un package</Link>
            <Link href={`/carelink-ops/service-design/factory/import?category=${encodeURIComponent(dossier.id)}&type=doctrine_rules`} className="inline-flex items-center justify-center gap-2 rounded-2xl border border-cyan-300/25 bg-cyan-300/10 px-5 py-3 text-sm font-black text-cyan-100 transition hover:bg-cyan-300/15"><Database size={17} /> Importer les ressources</Link>
          </div>
        </div>
      </section>

      {dossier.blockers.length ? (
        <section className="grid gap-3 rounded-[28px] border border-rose-200 bg-gradient-to-r from-rose-50 to-white p-4 shadow-sm lg:grid-cols-[1fr_auto] lg:items-center">
          <div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-rose-600 text-white"><ShieldAlert size={17} /></div><div><p className="text-sm font-black text-rose-950">{dossier.blockers.length} élément(s) à compléter</p><p className="mt-1 text-xs font-semibold leading-5 text-rose-700">{dossier.blockers.join(' · ')}</p><p className="mt-1 text-[10px] font-bold text-slate-500">La conception reste accessible; ces éléments deviennent des alertes de préparation et des contrôles avant publication.</p></div></div>
          <div className="flex gap-2"><Link href={`/carelink-ops/service-design/factory/import?category=${dossier.code}`} className="rounded-2xl border border-rose-200 bg-white px-4 py-2.5 text-xs font-black text-rose-700 shadow-sm">Importer précisément</Link><Link href="/carelink-ops/service-design/standards/doctrine" className="rounded-2xl bg-slate-950 px-4 py-2.5 text-xs font-black text-white">Ouvrir doctrine</Link></div>
        </section>
      ) : null}

      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        {[
          { label: 'Doctrine', value: dossier.doctrineReadiness, detail: `${dossier.doctrineRules.length} règle(s) locale(s)`, icon: <LockKeyhole size={18} />, tone: 'blue' },
          { label: 'Capacité', value: dossier.capacityReadiness, detail: dossier.capacityRule ? `${dossier.capacityRule.minimumHours}–${dossier.capacityRule.maximumHours} h` : 'Enveloppe à configurer', icon: <Gauge size={18} />, tone: 'violet' },
          { label: 'Activités', value: dossier.activityReadiness, detail: `${dossier.activities.length} bloc(s) exploitable(s)`, icon: <Activity size={18} />, tone: 'emerald' },
          { label: 'Sécurité', value: dossier.safetyReadiness, detail: `${dossier.risks.filter((item) => item.stopWork).length} contrôle(s) stop-work`, icon: <ShieldAlert size={18} />, tone: 'rose' },
        ].map((metric) => <article key={metric.label} className="rounded-[26px] border border-slate-200 bg-white p-4 shadow-[0_12px_34px_rgba(15,23,42,0.06)]"><div className="flex items-center justify-between"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-slate-950 text-white">{metric.icon}</div><span className="text-2xl font-black tracking-[-0.04em] text-slate-950">{metric.value}%</span></div><div className="mt-4 text-[10px] font-black uppercase tracking-[0.2em] text-slate-400">{metric.label}</div><p className="mt-1 text-xs font-semibold text-slate-600">{metric.detail}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-600 to-cyan-400" style={{ width: `${Math.max(3, metric.value)}%` }} /></div></article>)}
      </section>

      <section className="grid gap-5 xl:grid-cols-[286px_minmax(0,1fr)_300px]">
        <aside className="rounded-[28px] border border-slate-200 bg-white p-3 shadow-[0_16px_44px_rgba(15,23,42,0.07)] xl:sticky xl:top-4 xl:self-start">
          <div className="px-3 pb-3 pt-2"><p className="text-[10px] font-black uppercase tracking-[0.22em] text-blue-600">Architecture du dossier</p><p className="mt-1 text-xs font-semibold leading-5 text-slate-500">{dossier.sections.length} sections configurables</p></div>
          <div className="max-h-[68vh] space-y-1 overflow-y-auto pr-1">{dossier.sections.map((item) => <button key={item.id} onClick={() => setActiveSection(item.sectionCode)} className={cx('flex w-full items-center gap-3 rounded-2xl border px-3 py-3 text-left transition', activeSection === item.sectionCode ? 'border-blue-200 bg-blue-50 text-blue-950 shadow-sm' : 'border-transparent hover:border-slate-200 hover:bg-slate-50')}><div className={cx('grid h-9 w-9 shrink-0 place-items-center rounded-xl', item.status === 'approved' ? 'bg-emerald-100 text-emerald-700' : item.blockerCount ? 'bg-rose-100 text-rose-700' : 'bg-slate-100 text-slate-500')}>{sectionIcons[item.sectionCode] || <Layers3 size={16} />}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-black">{item.titleFr}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-[0.12em] text-slate-400">{item.completionPercent}% · {statusLabel(item.status)}</p></div><ChevronRight size={14} className="text-slate-300" /></button>)}</div>
        </aside>

        <article className="min-w-0 overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-[0_18px_50px_rgba(15,23,42,0.07)]">
          <header className="border-b border-slate-100 bg-gradient-to-r from-white to-slate-50 px-5 py-5 sm:px-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[0.22em] text-blue-600">Chambre active</p><h2 className="mt-2 text-xl font-black tracking-[-0.035em] text-slate-950">{section?.titleFr || 'Section'}</h2><p className="mt-1 text-xs font-semibold leading-5 text-slate-500">{section?.purposeFr || 'Dossier catégorie'}</p></div><Badge tone={section?.blockerCount ? 'rose' : 'blue'}>{section?.completionPercent || 0}% complet</Badge></div></header>
          <div className="p-5 sm:p-6">{sectionContent}</div>
        </article>

        <aside className="space-y-4 xl:sticky xl:top-4 xl:self-start">
          <section className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-[0_16px_44px_rgba(15,23,42,0.07)]"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400">Contrôle actuel</p><div className="mt-4"><ProgressBar value={section?.completionPercent || 0} tone={section?.blockerCount ? 'rose' : 'blue'} label="Complétude" /></div><div className="mt-4"><DetailList rows={[["Statut", statusLabel(section?.status || 'draft')], ["Responsable", section?.ownerRole || 'À affecter'], ["Blocages", section?.blockerCount || 0]]}/></div></section>
          <section className="rounded-[28px] bg-slate-950 p-5 text-white shadow-[0_18px_48px_rgba(15,23,42,0.22)]"><p className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-300">Actions immédiates</p><div className="mt-4 space-y-2"><Link href={`/carelink-ops/service-design/factory/category/${dossier.code}?mode=single_mission`} className="flex items-center justify-between rounded-2xl bg-white px-4 py-3 text-xs font-black text-slate-950">Mission unique <ChevronRight size={14} /></Link><Link href={`/carelink-ops/service-design/factory/category/${dossier.code}?mode=multi_mission`} className="flex items-center justify-between rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-xs font-black">Programme <ChevronRight size={14} /></Link><Link href={`/carelink-ops/service-design/factory/category/${dossier.code}?mode=commercial_package`} className="flex items-center justify-between rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-xs font-black">Package commercial <ChevronRight size={14} /></Link></div></section>
          <section className="rounded-[28px] border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-center gap-3"><CheckCircle2 size={18} className="text-emerald-700" /><div><p className="text-xs font-black text-emerald-950">Lignage protégé</p><p className="mt-1 text-[10px] font-semibold text-emerald-700">{dossier.code} · V{dossier.versionNumber}</p></div></div><p className="mt-3 text-[11px] font-semibold leading-5 text-emerald-800">Les changements matériels créent une nouvelle version; CARELINK conserve l’exécution.</p></section>
        </aside>
      </section>
    </div>
  )
}
