import { NextResponse } from 'next/server'
import { revalidatePath } from 'next/cache'
import { assertFlashcardsApiAccess } from '@/lib/flashcards-os/server/access'
import { deleteCardPermanently, recordFlashcardsAudit, updateCard } from '@/lib/flashcards-os/server/repository'

function paths(collectionId:string){revalidatePath(`/flashcards-os/product/collections/${collectionId.toLowerCase()}`);revalidatePath(`/flashcards-os/product/collections/${collectionId.toLowerCase()}/cards`)}
export async function PATCH(request:Request,context:{params:Promise<{collectionId:string;cardId:string}>}){
 const access=await assertFlashcardsApiAccess('flashcards_os.manage_content');if(!access.ok)return NextResponse.json({error:access.message},{status:access.status})
 try{const {collectionId,cardId}=await context.params;const body=await request.json();const card=await updateCard(cardId,{sequence:body.sequence==null?undefined:Number(body.sequence),concept:body.concept==null?undefined:String(body.concept),frontText:body.frontText==null?undefined:String(body.frontText),backGuidance:body.backGuidance==null?undefined:String(body.backGuidance),language:body.language==null?undefined:String(body.language),translation:body.translation==null?undefined:String(body.translation),pronunciation:body.pronunciation==null?undefined:String(body.pronunciation),example:body.example==null?undefined:String(body.example),activity:body.activity==null?undefined:String(body.activity),difficulty:body.difficulty,imageBrief:body.imageBrief==null?undefined:String(body.imageBrief),rightsStatus:body.rightsStatus,approvalStatus:body.approvalStatus});await recordFlashcardsAudit({actorId:String((access.user as any).id||''),actorName:String((access.user as any).full_name||(access.user as any).email||''),actionKey:'card.updated',actionLabel:'Carte modifiée',entityType:'card',entityId:cardId,summary:`Carte ${cardId} modifiée`,after:body});paths(decodeURIComponent(collectionId));return NextResponse.json({card})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Card update failed.'},{status:400})}
}
export async function DELETE(_request:Request,context:{params:Promise<{collectionId:string;cardId:string}>}){
 const access=await assertFlashcardsApiAccess('flashcards_os.manage_content');if(!access.ok)return NextResponse.json({error:access.message},{status:access.status})
 try{const {collectionId,cardId}=await context.params;const deleted=await deleteCardPermanently(cardId);await recordFlashcardsAudit({actorId:String((access.user as any).id||''),actorName:String((access.user as any).full_name||(access.user as any).email||''),actionKey:'card.deleted_permanently',actionLabel:'Carte supprimée définitivement',entityType:'card',entityId:cardId,summary:`Suppression définitive de la carte ${cardId}`,before:deleted,riskLevel:'high'});paths(decodeURIComponent(collectionId));return NextResponse.json({deleted:true,id:cardId})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Permanent deletion failed.'},{status:409})}
}
