"use client"

import * as React from "react"
import Link from "next/link"

export type SeoStatus = "idea" | "brief" | "draft" | "review" | "approved" | "scheduled" | "published" | "archived"
export type SeoIntent = "informational" | "commercial" | "transactional" | "navigational" | "local"
export type SeoPriority = "Low" | "Medium" | "High" | "Critical"
export type SeoChannel = "Blog" | "SEO Landing" | "Academy Blog" | "Partnership Article" | "Clinic Guide" | "Homecare Guide" | "Press/News"

export type SeoArticle = {
  id:string; title:string; slug:string; status:SeoStatus; priority:SeoPriority; channel:SeoChannel; owner:string; reviewer:string; cluster:string; primaryKeyword:string; secondaryKeywords:string[]; intent:SeoIntent; audience:string; objective:string; metaTitle:string; metaDescription:string; h1:string; outline:string[]; body:string; internalLinks:string[]; externalLinks:string[]; brandScore:number; seoScore:number; readability:number; dueDate:string; scheduledDate:string; publishedDate?:string; createdAt:string; updatedAt:string; notes:string; canonicalUrl:string; wordCount:number; impressions:number; clicks:number; rank:number; conversions:number }
export type SeoTask = { id:string; articleId:string; title:string; owner:string; status:"todo"|"doing"|"blocked"|"done"; dueDate:string; note:string }
export type SeoCluster = { id:string; name:string; pillar:string; intent:SeoIntent; owner:string; target:string; status:"planning"|"active"|"expanding"|"complete"; notes:string }
export type SeoRule = { id:string; title:string; category:"brand"|"technical"|"medical"|"conversion"|"editorial"; required:boolean; active:boolean; description:string }
export type SeoLog = { id:string; action:string; entity:string; detail:string; at:string }
export type SeoStore = { articles:SeoArticle[]; tasks:SeoTask[]; clusters:SeoCluster[]; rules:SeoRule[]; logs:SeoLog[] }

export const SEO_STORE_KEY = "angelcare_market_os_seo_blog_real_execution_v3"
export const statuses: SeoStatus[] = ["idea","brief","draft","review","approved","scheduled","published"]
export const channels: SeoChannel[] = ["Blog","SEO Landing","Academy Blog","Partnership Article","Clinic Guide","Homecare Guide","Press/News"]
export const intents: SeoIntent[] = ["informational","commercial","transactional","navigational","local"]
export const priorities: SeoPriority[] = ["Low","Medium","High","Critical"]

export function uid(prefix="seo"){ return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}` }
export function todayISO(offset=0){ const d=new Date(); d.setDate(d.getDate()+offset); return d.toISOString().slice(0,10) }
export function label(v:string){ return v.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase()) }
export function pct(v:number){ return `${Math.max(0,Math.min(100,Math.round(v)))}%` }
export function scoreTone(v:number){ if(v>=85)return "text-emerald-700 bg-emerald-50 border-emerald-200"; if(v>=70)return "text-amber-700 bg-amber-50 border-amber-200"; return "text-red-700 bg-red-50 border-red-200" }
export function statusTone(s:string){ if(["published","approved","scheduled"].includes(s))return "border-emerald-200 bg-emerald-50 text-emerald-800"; if(["review","draft"].includes(s))return "border-amber-200 bg-amber-50 text-amber-800"; if(s==="archived")return "border-slate-200 bg-slate-100 text-slate-9500"; return "border-sky-200 bg-sky-50 text-sky-800" }
export function nextStatus(s:SeoStatus):SeoStatus{ const i=statuses.indexOf(s); return statuses[Math.min(statuses.length-1,i+1)] || s }
export function isOverdue(a:SeoArticle){ return a.dueDate < todayISO() && a.status!=="published" && a.status!=="archived" }
export function articleReadiness(a:SeoArticle,tasks:SeoTask[],rules:SeoRule[]){ let n=20; if(a.primaryKeyword)n+=10; if(a.metaTitle.length>=35&&a.metaTitle.length<=65)n+=10; if(a.metaDescription.length>=90&&a.metaDescription.length<=160)n+=10; if(a.outline.length>=4)n+=10; if(a.body.length>=600)n+=10; if(a.internalLinks.length>=2)n+=10; if(a.brandScore>=75)n+=10; if(tasks.filter(t=>t.articleId===a.id&&t.status!=="done").length===0)n+=10; if(rules.filter(r=>r.active&&r.required).length>0)n+=0; return Math.max(0,Math.min(100,n)) }
export function canPublish(a:SeoArticle,tasks:SeoTask[],rules:SeoRule[]){ return a.status==="approved" && articleReadiness(a,tasks,rules)>=80 && a.seoScore>=75 && a.brandScore>=75 }

export const defaultStore: SeoStore = {
  articles: [
    { id:"seo-001", title:"Postpartum home care in Rabat: complete family guide", slug:"postpartum-home-care-rabat-guide", status:"approved", priority:"High", channel:"Homecare Guide", owner:"SEO Lead", reviewer:"Medical Brand Reviewer", cluster:"Postpartum Care", primaryKeyword:"postpartum home care Rabat", secondaryKeywords:["postnatal support Rabat","new mother care Morocco"], intent:"commercial", audience:"Families seeking trusted after-birth support", objective:"Generate qualified homecare leads", metaTitle:"Postpartum Home Care in Rabat | AngelCare Guide", metaDescription:"A practical guide for families comparing trusted postpartum home care options in Rabat, Temara and Salé.", h1:"Postpartum home care in Rabat", outline:["Who needs postpartum support","Services included","How to choose provider","AngelCare process"], body:"This editorial item is prepared as a conversion-focused SEO guide for premium family care decisions.", internalLinks:["/services/homecare","/academy"], externalLinks:[], brandScore:88, seoScore:84, readability:81, dueDate:todayISO(2), scheduledDate:todayISO(4), createdAt:new Date().toISOString(), updatedAt:new Date().toISOString(), notes:"Ready for publishing after final image check.", canonicalUrl:"", wordCount:1450, impressions:3200, clicks:220, rank:8, conversions:14 },
    { id:"seo-002", title:"How clinics can refer safe homecare support", slug:"clinic-referral-homecare-support", status:"review", priority:"Critical", channel:"Partnership Article", owner:"Partnership Content", reviewer:"SEO Manager", cluster:"Clinic Partnerships", primaryKeyword:"clinic homecare referral Morocco", secondaryKeywords:["maternity clinic partnership","homecare referral"], intent:"commercial", audience:"Clinic directors and maternity partners", objective:"Build partner authority and meetings", metaTitle:"Clinic Homecare Referral Program in Morocco", metaDescription:"How maternity clinics can work with AngelCare to guide families toward reliable support after birth.", h1:"Clinic homecare referral program", outline:["Why referrals matter","Patient experience","Partnership model","Next step"], body:"Article needs stronger proof, partner positioning and CTA discipline.", internalLinks:["/partners","/services"], externalLinks:[], brandScore:72, seoScore:69, readability:78, dueDate:todayISO(-1), scheduledDate:todayISO(6), createdAt:new Date().toISOString(), updatedAt:new Date().toISOString(), notes:"Needs review and stronger authority signals.", canonicalUrl:"", wordCount:980, impressions:900, clicks:42, rank:17, conversions:3 },
    { id:"seo-003", title:"Academy career path for caregivers in Morocco", slug:"academy-caregiver-career-path-morocco", status:"draft", priority:"Medium", channel:"Academy Blog", owner:"Academy Marketing", reviewer:"Brand Lead", cluster:"Academy Recruitment", primaryKeyword:"caregiver training Morocco", secondaryKeywords:["nanny training Rabat","homecare academy"], intent:"informational", audience:"Young candidates considering training and career pathways", objective:"Recruit academy candidates", metaTitle:"Caregiver Training in Morocco | AngelCare Academy", metaDescription:"Discover how AngelCare Academy helps candidates build a professional care career with training and certification.", h1:"Caregiver training in Morocco", outline:["Training path","Skills learned","Certification","Career access"], body:"Draft content prepared for academy recruitment.", internalLinks:["/academy","/careers"], externalLinks:[], brandScore:82, seoScore:76, readability:86, dueDate:todayISO(5), scheduledDate:todayISO(10), createdAt:new Date().toISOString(), updatedAt:new Date().toISOString(), notes:"Add candidate FAQ section.", canonicalUrl:"", wordCount:1120, impressions:1700, clicks:98, rank:12, conversions:9 },
  ],
  tasks: [
    { id:"task-001", articleId:"seo-002", title:"Add partner proof paragraph", owner:"Partnership Content", status:"doing", dueDate:todayISO(), note:"Need stronger clinic authority." },
    { id:"task-002", articleId:"seo-001", title:"Approve hero visual", owner:"Design", status:"todo", dueDate:todayISO(1), note:"Use premium family visual." },
    { id:"task-003", articleId:"seo-003", title:"Add FAQ schema draft", owner:"SEO Lead", status:"blocked", dueDate:todayISO(2), note:"Waiting for academy answers." },
  ],
  clusters: [
    { id:"cl-001", name:"Postpartum Care", pillar:"postpartum-home-care-rabat-guide", intent:"commercial", owner:"SEO Lead", target:"Own premium family care queries in Rabat-Salé-Temara", status:"active", notes:"Priority cluster for paid + organic alignment." },
    { id:"cl-002", name:"Clinic Partnerships", pillar:"clinic-referral-homecare-support", intent:"commercial", owner:"Partnership Lead", target:"Build authority for clinic referral program", status:"planning", notes:"Needs case-study style support." },
    { id:"cl-003", name:"Academy Recruitment", pillar:"academy-caregiver-career-path-morocco", intent:"informational", owner:"Academy Marketing", target:"Recruit caregivers and trainees", status:"active", notes:"Strong FAQ potential." },
  ],
  rules: [
    { id:"rule-001", title:"No unsafe medical promises", category:"medical", required:true, active:true, description:"Avoid diagnosis, treatment guarantees or medical claims beyond AngelCare service scope." },
    { id:"rule-002", title:"Clear premium CTA", category:"conversion", required:true, active:true, description:"Every publishable article needs one clear CTA connected to service, academy or partner outcome." },
    { id:"rule-003", title:"Morocco-local relevance", category:"editorial", required:false, active:true, description:"Use city, region and local context where useful without keyword stuffing." },
  ],
  logs: [{ id:"log-001", action:"seed", entity:"SEO Blog", detail:"Workspace initialized with AngelCare SEO examples.", at:new Date().toISOString() }],
}

export function readStore(): SeoStore { if(typeof window==="undefined") return defaultStore; try{ const raw=localStorage.getItem(SEO_STORE_KEY); return raw?JSON.parse(raw):defaultStore }catch{return defaultStore} }
export function writeStore(s:SeoStore){ if(typeof window!=="undefined") localStorage.setItem(SEO_STORE_KEY,JSON.stringify(s)) }
export function useSeoStore(){
  const [store,setStore]=React.useState<SeoStore>(defaultStore)
  React.useEffect(()=>setStore(readStore()),[])
  const commit=React.useCallback((fn:(draft:SeoStore)=>void, action="update", detail="Updated SEO workspace")=>{ setStore(prev=>{ const draft:SeoStore=JSON.parse(JSON.stringify(prev)); fn(draft); draft.logs=[{id:uid("log"), action, entity:"SEO Blog", detail, at:new Date().toISOString()}, ...draft.logs].slice(0,80); writeStore(draft); return draft }) },[])
  const reset=React.useCallback(()=>{ writeStore(defaultStore); setStore(defaultStore) },[])
  return { store, commit, reset }
}

export function cx(...p:Array<string|false|null|undefined>){ return p.filter(Boolean).join(" ") }
export function Shell({children}:{children:React.ReactNode}){ return <div data-market-os-root className="min-h-screen bg-slate-50 text-slate-950 selection:bg-sky-200 selection:text-slate-950">{children}</div> }
export function Panel({children,className=""}:{children:React.ReactNode; className?:string}){ return <section className={cx("rounded-[1.75rem] border border-slate-200 bg-white shadow-sm", className)}>{children}</section> }
export function Badge({children,kind="default"}:{children:React.ReactNode; kind?:"default"|"danger"|"success"|"warning"|"dark"}){ const tone=kind==="danger"?"border-red-200 bg-red-50 text-red-700":kind==="success"?"border-emerald-200 bg-emerald-50 text-emerald-700":kind==="warning"?"border-amber-200 bg-amber-50 text-amber-700":kind==="dark"?"border-slate-950 bg-white text-slate-950":"border-slate-200 bg-white text-slate-700"; return <span className={cx("inline-flex rounded-full border px-2.5 py-1 text-[11px] font-black uppercase tracking-wide",tone)}>{children}</span> }
export function Button({children,href,onClick,kind="secondary"}:{children:React.ReactNode; href?:string; onClick?:()=>void; kind?:"primary"|"secondary"|"danger"|"success"|"dark"}){ const cls=cx("inline-flex items-center justify-center rounded-2xl px-4 py-3 text-sm font-black transition hover:-translate-y-0.5", kind==="primary"&&"bg-sky-600 text-slate-950 shadow-lg shadow-sky-100", kind==="dark"&&"bg-white text-slate-950", kind==="danger"&&"bg-red-600 text-slate-950", kind==="success"&&"bg-emerald-600 text-slate-950", kind==="secondary"&&"border border-slate-200 bg-white text-slate-950 hover:bg-slate-50"); return href?<Link href={href} className={cls}>{children}</Link>:<button onClick={onClick} className={cls}>{children}</button> }
export function Field({label,children}:{label:string; children:React.ReactNode}){ return <label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-9500">{label}</span>{children}</label> }
export const inputClass="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-950 outline-none transition placeholder:text-slate-500 focus:border-sky-600 focus:ring-4 focus:ring-sky-100"
export function Meter({value}:{value:number}){ return <div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-sky-600" style={{width:pct(value)}} /></div> }
export function Metric({label,value,sub,tone="sky"}:{label:string; value:string; sub:string; tone?:"sky"|"emerald"|"amber"|"red"|"slate"}){ const bg={sky:"bg-sky-50 text-sky-700",emerald:"bg-emerald-50 text-emerald-700",amber:"bg-amber-50 text-amber-700",red:"bg-red-50 text-red-700",slate:"bg-slate-50 text-slate-700"}[tone]; return <Panel className="p-5"><p className="text-xs font-black uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-3xl font-black text-slate-950">{value}</p><p className={cx("mt-2 rounded-xl px-3 py-2 text-xs font-black",bg)}>{sub}</p></Panel> }
export function ArticleRow({article,tasks,onAdvance,onArchive,onDelete}:{article:SeoArticle; tasks:SeoTask[]; onAdvance:()=>void; onArchive:()=>void; onDelete:()=>void}){ const open=tasks.filter(t=>t.articleId===article.id&&t.status!=="done").length; return <div className="grid gap-4 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm xl:grid-cols-[1.2fr_.7fr_.6fr_.6fr_.8fr]"><div><div className="flex flex-wrap gap-2"><span className={cx("rounded-full border px-2.5 py-1 text-[11px] font-black uppercase",statusTone(article.status))}>{label(article.status)}</span><Badge kind={article.priority==="Critical"?"danger":article.priority==="High"?"warning":"default"}>{article.priority}</Badge></div><Link href={`/market-os/seo-blog-workspace/${article.id}`} className="mt-3 block text-base font-black text-slate-950 hover:underline">{article.title}</Link><p className="mt-1 text-xs font-bold text-slate-9500">{article.channel} • {article.owner} • {article.primaryKeyword}</p></div><div><p className="text-xs font-black uppercase text-slate-500">Scores</p><div className="mt-2 space-y-2"><Meter value={article.seoScore}/><Meter value={article.brandScore}/></div></div><div><p className="text-xs font-black uppercase text-slate-500">Rank / clicks</p><p className="mt-2 text-sm font-black text-slate-950">#{article.rank} • {article.clicks}</p><p className="text-xs font-bold text-slate-9500">{article.impressions} impressions</p></div><div><p className="text-xs font-black uppercase text-slate-500">Open tasks</p><p className="mt-2 text-xl font-black text-slate-950">{open}</p><p className="text-xs font-bold text-slate-9500">Due {article.dueDate}</p></div><div className="flex flex-wrap items-center gap-2 xl:justify-end"><Button href={`/market-os/seo-blog-workspace/${article.id}`}>Open</Button><Button href={`/market-os/seo-blog-workspace/${article.id}/edit`}>Edit</Button><Button onClick={onAdvance} kind="dark">Next</Button><Button onClick={onArchive}>Archive</Button><Button onClick={onDelete} kind="danger">Delete</Button></div></div> }
