'use client'
import Link from 'next/link'
import { useSearchParams } from 'next/navigation'
import { ArchiveRestore, Edit3, GitBranch, ShieldCheck, Trash2 } from 'lucide-react'
import styles from './bulk9-governance.module.css'
const ROOT='/market-os/content-command-center'
function routeContext(pathname:string){
 const dossier=pathname.match(/\/dossiers\/([^/]+)/);if(dossier)return{entityType:'dossier',entityId:dossier[1],family:'Dossier 360',label:'Dossier actif'}
 const task=pathname.match(/\/tasks\/([^/]+)/);if(task&&task[1]!=='execution')return{entityType:'task',entityId:task[1],family:'Exécution',label:'Tâche active'}
 const legacy=pathname.match(new RegExp(`${ROOT.replaceAll('/','\\/')}\\/([^/]+)$`));if(legacy&&/^[0-9a-f-]{16,}$/i.test(legacy[1]))return{entityType:'dossier',entityId:legacy[1],family:'Dossier 360',label:'Contenu actif'}
 const map:Array<[RegExp,string,string]>=[[/\/opportunities/,'signal','Opportunity Intelligence'],[/\/signals/,'signal','Intelligence'],[/\/strategies/,'strategy','Stratégie'],[/\/briefs/,'dossier','Dossier 360'],[/\/missions/,'mission','Exécution'],[/\/tasks/,'task','Exécution'],[/\/evidence/,'evidence','Preuve & validation'],[/\/review|\/validation/,'human_review','Preuve & validation'],[/\/assets|\/studio/,'asset','Sources & assets'],[/\/source-vault/,'source_object','Sources & assets'],[/\/distribution|\/publishing/,'publication_package','Distribution & publication'],[/\/performance|\/attribution/,'performance_event','Impact & apprentissage'],[/\/optimization|\/learning/,'learning_record','Impact & apprentissage'],[/\/ai-director\/commands/,'ai_command','AI Director'],[/\/ai-director\/skills/,'ai_skill','AI Director'],[/\/ai-director\/schedules/,'ai_schedule','AI Director'],[/\/ai-director\/missions/,'ai_mission','AI Director'],[/\/ai-director\/compiler/,'ai_compilation','AI Director'],[/\/ai-director\/queue|\/ai-director\/runs|\/ai-director\/recovery/,'ai_execution_job','AI Director'],[/\/ai-director\/decisions/,'ai_decision','AI Director'],[/\/ai-director\/doctrine/,'ai_doctrine','AI Director'],[/\/ai-director\/learning/,'ai_learning','AI Director'],[/\/ai-director/,'ai_director','AI Director']]
 const match=map.find(([pattern])=>pattern.test(pathname));return match?{entityType:match[1],entityId:'',family:match[2],label:'Registre du workspace'}:{entityType:'dossier',entityId:'',family:'Dossier 360',label:'Registre institutionnel'}
}
export default function LifecycleControlDock({pathname}:{pathname:string}){const searchParams=useSearchParams();let context=routeContext(pathname);const contextualKeys:Array<[string,string,string]>=[['dossierId','dossier','Dossier actif'],['contentDossierId','dossier','Dossier actif'],['missionId','mission','Mission active'],['taskId','task','Tâche active'],['evidenceId','evidence','Preuve active'],['packageId','publication_package','Package actif'],['strategyId','strategy','Stratégie active'],['opportunityId','signal','Opportunité active'],['signalId','signal','Signal actif'],['assetId','asset','Asset actif'],['directorId','ai_director','AI Director actif'],['compilationId','ai_compilation','Compilation active'],['jobId','ai_execution_job','Job actif'],['scheduleId','ai_schedule','Planification active']];for(const [key,type,label] of contextualKeys){const value=searchParams.get(key);if(value){context={...context,entityType:type,entityId:value,label};break}};const params=new URLSearchParams({family:context.family});if(context.entityId){params.set('entityType',context.entityType);params.set('entityId',context.entityId)}const href=`${ROOT}/record-governance?${params}`;return <section className={styles.globalDock} aria-label="Contrôle global du cycle de vie"><div><span><ShieldCheck/></span><div><small>CONTRÔLE DU CYCLE · BULKS 1–8</small><strong>{context.label}</strong><p>Modifier, annuler, archiver, restaurer ou supprimer selon l’état, les dépendances et l’autorité.</p></div></div><div className={styles.globalDockActions}><span><Edit3/>Édition gouvernée</span><span><ArchiveRestore/>Archives & restauration</span><span><GitBranch/>Conséquences</span><span><Trash2/>Purge contrôlée</span><Link href={href}>Ouvrir l’autorité</Link></div></section>}
