import { createServiceClient } from '@/lib/supabase/server'
import { writeMarketplaceAudit } from '../audit/write-audit'
import type { MarketplaceRequestContext } from '../domain/types'
import { MarketplaceError } from '../server/errors'
import type { FamilyAccount, FamilyChild, FamilyDashboardData, FamilyMission, FamilyQuoteRequest, MissionReport, MissionTimelineEvent, NeedsDiagnostic, SupportMessage, SupportTicket } from './types'

function dbError(operation: string, error: { code?: string; message?: string } | null) {
  const missing = error?.code === '42P01' || String(error?.message || '').includes('angelcare_marketplace_family_')
  return new MarketplaceError(missing ? 'CONFIGURATION_ERROR' : 'INTERNAL_ERROR', missing ? 'Les migrations Family Experience doivent être appliquées.' : `L’espace famille n’a pas pu ${operation}.`)
}

export async function ensureFamilyAccount(context: MarketplaceRequestContext): Promise<FamilyAccount> {
  const supabase = await createServiceClient()
  const { data: existing, error: selectError } = await supabase.from('angelcare_marketplace_family_accounts').select('*').eq('app_user_id', context.actor.id).maybeSingle()
  if (selectError) throw dbError('charger le dossier famille', selectError)
  if (existing) return existing as FamilyAccount
  const { data, error } = await supabase.from('angelcare_marketplace_family_accounts').insert({ app_user_id: context.actor.id, display_name: context.actor.displayName, email: context.actor.email, preferred_locale: context.locale, territory_id: context.territoryId, status: 'incomplete', onboarding_status: 'not_started', consent_status: 'pending' }).select('*').single()
  if (error || !data) throw dbError('créer le dossier famille', error)
  return data as FamilyAccount
}

export async function getFamilyDashboard(context: MarketplaceRequestContext): Promise<FamilyDashboardData> {
  const account = await ensureFamilyAccount(context)
  const supabase = await createServiceClient()
  const [{ data: children }, { data: requests }, { data: missions }, { data: reports }, { data: tickets }] = await Promise.all([
    supabase.from('angelcare_marketplace_family_children').select('*').eq('family_account_id', account.id).neq('status','archived').order('created_at'),
    supabase.from('angelcare_marketplace_family_quote_requests').select('*').eq('family_account_id', account.id).order('created_at',{ascending:false}).limit(20),
    supabase.from('angelcare_marketplace_family_missions').select('*').eq('family_account_id', account.id).order('starts_at',{ascending:false}).limit(20),
    supabase.from('angelcare_marketplace_family_mission_reports').select('*,mission:angelcare_marketplace_family_missions!inner(family_account_id)').eq('mission.family_account_id',account.id).eq('status','published').order('published_at',{ascending:false}).limit(20),
    supabase.from('angelcare_marketplace_family_support_tickets').select('*').eq('family_account_id', account.id).order('created_at',{ascending:false}).limit(20),
  ])
  const childRows=(children||[]) as FamilyChild[];const requestRows=(requests||[]) as FamilyQuoteRequest[];const missionRows=(missions||[]) as FamilyMission[];const reportRows=(reports||[]) as MissionReport[];const ticketRows=(tickets||[]) as SupportTicket[]
  const nextActions: FamilyDashboardData['nextActions']=[]
  if(account.onboarding_status!=='completed')nextActions.push({key:'profile',title:'Compléter votre dossier',text:'Coordonnées, ville, langue et consentement.',route:'/angelcare-marketplace/family/account',priority:'high'})
  if(!childRows.length)nextActions.push({key:'child',title:'Ajouter un enfant',text:'Créer un profil privé avant le diagnostic.',route:'/angelcare-marketplace/family/children/new',priority:'high'})
  if(childRows.length&&!requestRows.length)nextActions.push({key:'diagnostic',title:'Préciser votre besoin',text:'Réaliser le diagnostic puis transmettre une demande.',route:'/angelcare-marketplace/family/diagnostic',priority:'normal'})
  const waiting=requestRows.find(item=>['submitted','qualified','proposal_ready'].includes(item.status));if(waiting)nextActions.push({key:'request',title:`Suivre ${waiting.public_reference}`,text:waiting.next_action||'Votre demande est en traitement.',route:`/angelcare-marketplace/family/requests/${waiting.id}`,priority:'normal'})
  return {account,children:childRows,requests:requestRows,missions:missionRows,reports:reportRows,tickets:ticketRows,nextActions}
}

export async function updateFamilyAccount(input:{patch:Record<string,unknown>;context:MarketplaceRequestContext;requestId:string}):Promise<FamilyAccount>{const account=await ensureFamilyAccount(input.context);const supabase=await createServiceClient();const allowed=['display_name','phone','city','preferred_locale','consent_status'];const patch:Record<string,unknown>={updated_at:new Date().toISOString()};for(const key of allowed){if(key in input.patch)patch[key]=input.patch[key]}if(patch.display_name&&patch.city&&patch.phone&&patch.consent_status==='granted')patch.onboarding_status='completed';else patch.onboarding_status='in_progress';const{data,error}=await supabase.from('angelcare_marketplace_family_accounts').update(patch).eq('id',account.id).select('*').single();if(error||!data)throw dbError('mettre à jour le dossier',error);await writeMarketplaceAudit({context:input.context,requestId:input.requestId,action:'marketplace.family.account_updated',objectType:'family_account',objectId:account.id,result:'success',severity:'info',beforeValue:account,afterValue:data,source:'ultra-delivery-01-family'});return data as FamilyAccount}

export async function listChildren(context:MarketplaceRequestContext):Promise<FamilyChild[]>{const account=await ensureFamilyAccount(context);const supabase=await createServiceClient();const{data,error}=await supabase.from('angelcare_marketplace_family_children').select('*').eq('family_account_id',account.id).neq('status','archived').order('created_at');if(error)throw dbError('charger les enfants',error);return(data||[])as FamilyChild[]}
export async function getChild(context:MarketplaceRequestContext,childId:string):Promise<FamilyChild>{const account=await ensureFamilyAccount(context);const supabase=await createServiceClient();const{data,error}=await supabase.from('angelcare_marketplace_family_children').select('*').eq('id',childId).eq('family_account_id',account.id).single();if(error||!data)throw new MarketplaceError('NOT_FOUND','Profil enfant introuvable.');return data as FamilyChild}
export async function createChild(input:{firstName:string;birthDate:string;ageGroup:string;gender?:string|null;schoolLevel?:string|null;languages:string[];interests:string[];allergies?:string|null;medicalBoundaries?:string|null;supportNotes?:string|null;context:MarketplaceRequestContext;requestId:string}):Promise<FamilyChild>{const account=await ensureFamilyAccount(input.context);if(account.consent_status!=='granted')throw new MarketplaceError('DEPENDENCY_BLOCKED','Le consentement du dossier famille doit être accordé avant de créer un profil enfant.');const supabase=await createServiceClient();const{data,error}=await supabase.from('angelcare_marketplace_family_children').insert({family_account_id:account.id,first_name:input.firstName,birth_date:input.birthDate,age_group:input.ageGroup,gender:input.gender||null,school_level:input.schoolLevel||null,languages:input.languages,interests:input.interests,allergies:input.allergies||null,medical_boundaries:input.medicalBoundaries||null,support_notes:input.supportNotes||null,created_by:input.context.actor.id}).select('*').single();if(error||!data)throw dbError('créer le profil enfant',error);await writeMarketplaceAudit({context:input.context,requestId:input.requestId,action:'marketplace.family.child_created',objectType:'family_child',objectId:String(data.id),result:'success',severity:'warning',afterValue:{public_reference:data.public_reference,age_group:data.age_group},source:'ultra-delivery-01-family'});return data as FamilyChild}

export async function createDiagnostic(input:{childId:string;scheduleNeeds:Record<string,unknown>;developmentGoals:string[];routineNeeds:string[];safetyConstraints:string[];familyPriorities:string[];freeContext?:string|null;context:MarketplaceRequestContext;requestId:string}):Promise<NeedsDiagnostic>{const account=await ensureFamilyAccount(input.context);await getChild(input.context,input.childId);const supabase=await createServiceClient();const{data,error}=await supabase.from('angelcare_marketplace_family_diagnostics').insert({family_account_id:account.id,child_id:input.childId,status:'submitted',schedule_needs:input.scheduleNeeds,development_goals:input.developmentGoals,routine_needs:input.routineNeeds,safety_constraints:input.safetyConstraints,family_priorities:input.familyPriorities,free_context:input.freeContext||null,submitted_at:new Date().toISOString(),created_by:input.context.actor.id}).select('*').single();if(error||!data)throw dbError('enregistrer le diagnostic',error);await writeMarketplaceAudit({context:input.context,requestId:input.requestId,action:'marketplace.family.diagnostic_submitted',objectType:'family_diagnostic',objectId:String(data.id),result:'success',severity:'warning',afterValue:{public_reference:data.public_reference,child_id:input.childId},source:'ultra-delivery-01-family'});return data as NeedsDiagnostic}

export async function listDiagnostics(context:MarketplaceRequestContext):Promise<NeedsDiagnostic[]>{const account=await ensureFamilyAccount(context);const supabase=await createServiceClient();const{data,error}=await supabase.from('angelcare_marketplace_family_diagnostics').select('*').eq('family_account_id',account.id).order('created_at',{ascending:false});if(error)throw dbError('charger les diagnostics',error);return(data||[])as NeedsDiagnostic[]}

export async function createQuoteRequest(input:{childId?:string|null;diagnosticId?:string|null;serviceFamily:string;city:string;requestedStartDate?:string|null;schedule:Record<string,unknown>;durationExpectation?:string|null;locationNotes?:string|null;priorities:string[];context:MarketplaceRequestContext;requestId:string}):Promise<FamilyQuoteRequest>{const account=await ensureFamilyAccount(input.context);if(input.childId)await getChild(input.context,input.childId);const supabase=await createServiceClient();const{data,error}=await supabase.from('angelcare_marketplace_family_quote_requests').insert({family_account_id:account.id,child_id:input.childId||null,diagnostic_id:input.diagnosticId||null,service_family:input.serviceFamily,city:input.city,requested_start_date:input.requestedStartDate||null,schedule:input.schedule,duration_expectation:input.durationExpectation||null,location_notes:input.locationNotes||null,priorities:input.priorities,status:'submitted',submitted_at:new Date().toISOString(),next_action:'Qualification par une coordinatrice ANGELCARE.',created_by:input.context.actor.id}).select('*').single();if(error||!data)throw dbError('transmettre la demande',error);await supabase.from('angelcare_marketplace_admin_action_items').insert({title:`Qualifier ${data.public_reference}`,description:'Demande famille reçue depuis le parcours B2C.',object_type:'family_quote_request',object_id:data.id,status:'open',priority:'high',territory_id:account.territory_id,next_action:'Vérifier le besoin, la couverture et préparer la prochaine étape.',created_by:input.context.actor.id});await writeMarketplaceAudit({context:input.context,requestId:input.requestId,action:'marketplace.family.quote_request_submitted',objectType:'family_quote_request',objectId:String(data.id),result:'success',severity:'info',afterValue:{public_reference:data.public_reference,status:data.status},source:'ultra-delivery-01-family'});return data as FamilyQuoteRequest}

export async function listQuoteRequests(context:MarketplaceRequestContext):Promise<FamilyQuoteRequest[]>{const account=await ensureFamilyAccount(context);const supabase=await createServiceClient();const{data,error}=await supabase.from('angelcare_marketplace_family_quote_requests').select('*').eq('family_account_id',account.id).order('created_at',{ascending:false});if(error)throw dbError('charger les demandes',error);return(data||[])as FamilyQuoteRequest[]}
export async function getQuoteRequest(context:MarketplaceRequestContext,id:string):Promise<FamilyQuoteRequest>{const account=await ensureFamilyAccount(context);const supabase=await createServiceClient();const{data,error}=await supabase.from('angelcare_marketplace_family_quote_requests').select('*').eq('id',id).eq('family_account_id',account.id).single();if(error||!data)throw new MarketplaceError('NOT_FOUND','Demande introuvable.');return data as FamilyQuoteRequest}

export async function listMissions(context:MarketplaceRequestContext):Promise<FamilyMission[]>{const account=await ensureFamilyAccount(context);const supabase=await createServiceClient();const{data,error}=await supabase.from('angelcare_marketplace_family_missions').select('*').eq('family_account_id',account.id).order('starts_at',{ascending:false});if(error)throw dbError('charger les missions',error);return(data||[])as FamilyMission[]}
export async function getMission(context:MarketplaceRequestContext,id:string):Promise<{mission:FamilyMission;events:MissionTimelineEvent[];reports:MissionReport[]}>{const account=await ensureFamilyAccount(context);const supabase=await createServiceClient();const[{data:mission,error},{data:events},{data:reports}]=await Promise.all([supabase.from('angelcare_marketplace_family_missions').select('*').eq('id',id).eq('family_account_id',account.id).single(),supabase.from('angelcare_marketplace_family_mission_timeline').select('*').eq('mission_id',id).eq('visible_to_family',true).order('occurred_at'),supabase.from('angelcare_marketplace_family_mission_reports').select('*').eq('mission_id',id).eq('status','published').order('published_at',{ascending:false})]);if(error||!mission)throw new MarketplaceError('NOT_FOUND','Mission introuvable.');return{mission:mission as FamilyMission,events:(events||[])as MissionTimelineEvent[],reports:(reports||[])as MissionReport[]}}

export async function listSupportTickets(context:MarketplaceRequestContext):Promise<SupportTicket[]>{const account=await ensureFamilyAccount(context);const supabase=await createServiceClient();const{data,error}=await supabase.from('angelcare_marketplace_family_support_tickets').select('*').eq('family_account_id',account.id).order('created_at',{ascending:false});if(error)throw dbError('charger les tickets',error);return(data||[])as SupportTicket[]}
export async function createSupportTicket(input:{subject:string;category:string;priority:string;message:string;context:MarketplaceRequestContext;requestId:string}):Promise<SupportTicket>{const account=await ensureFamilyAccount(input.context);const supabase=await createServiceClient();const{data,error}=await supabase.rpc('angelcare_marketplace_create_family_support_ticket',{p_family_account_id:account.id,p_subject:input.subject,p_category:input.category,p_priority:input.priority,p_message:input.message,p_actor_id:input.context.actor.id}).single();if(error||!data)throw dbError('ouvrir le ticket',error);const ticket=data as unknown as SupportTicket;await writeMarketplaceAudit({context:input.context,requestId:input.requestId,action:'marketplace.family.support_opened',objectType:'family_support_ticket',objectId:ticket.id,result:'success',severity:input.priority==='urgent'?'warning':'info',afterValue:{public_reference:ticket.public_reference,category:ticket.category},source:'ultra-delivery-01-family'});return ticket}
export async function getSupportTicket(context:MarketplaceRequestContext,id:string):Promise<{ticket:SupportTicket;messages:SupportMessage[]}>{const account=await ensureFamilyAccount(context);const supabase=await createServiceClient();const[{data:ticket,error},{data:messages}]=await Promise.all([supabase.from('angelcare_marketplace_family_support_tickets').select('*').eq('id',id).eq('family_account_id',account.id).single(),supabase.from('angelcare_marketplace_family_support_messages').select('*').eq('ticket_id',id).eq('visible_to_family',true).order('created_at')]);if(error||!ticket)throw new MarketplaceError('NOT_FOUND','Ticket introuvable.');return{ticket:ticket as SupportTicket,messages:(messages||[])as SupportMessage[]}}
export async function addSupportMessage(input:{ticketId:string;body:string;context:MarketplaceRequestContext;requestId:string}):Promise<SupportMessage>{await getSupportTicket(input.context,input.ticketId);const supabase=await createServiceClient();const{data,error}=await supabase.from('angelcare_marketplace_family_support_messages').insert({ticket_id:input.ticketId,author_type:'family',author_id:input.context.actor.id,body:input.body,visible_to_family:true}).select('*').single();if(error||!data)throw dbError('ajouter le message',error);return data as SupportMessage}

export async function adminListFamilies():Promise<FamilyAccount[]>{const supabase=await createServiceClient();const{data,error}=await supabase.from('angelcare_marketplace_family_accounts').select('*').order('updated_at',{ascending:false}).limit(300);if(error)throw dbError('charger les familles',error);return(data||[])as FamilyAccount[]}
export async function adminListRequests(status?:string):Promise<FamilyQuoteRequest[]>{const supabase=await createServiceClient();let query=supabase.from('angelcare_marketplace_family_quote_requests').select('*').order('created_at',{ascending:false}).limit(300);if(status)query=query.eq('status',status);const{data,error}=await query;if(error)throw dbError('charger les demandes familles',error);return(data||[])as FamilyQuoteRequest[]}
export async function qualifyRequest(input:{id:string;status:'qualified'|'proposal_ready'|'declined';notes:string;nextAction:string;context:MarketplaceRequestContext;requestId:string}):Promise<FamilyQuoteRequest>{const supabase=await createServiceClient();const{data,error}=await supabase.from('angelcare_marketplace_family_quote_requests').update({status:input.status,qualification_notes:input.notes,next_action:input.nextAction,owner_id:input.context.actor.id,qualified_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',input.id).in('status',['submitted','qualified']).select('*').single();if(error||!data)throw dbError('qualifier la demande',error);await writeMarketplaceAudit({context:input.context,requestId:input.requestId,action:`marketplace.family.request_${input.status}`,objectType:'family_quote_request',objectId:input.id,result:'success',severity:'info',reason:input.notes,afterValue:data,source:'ultra-delivery-01-family-admin'});return data as FamilyQuoteRequest}
