import { NextRequest, NextResponse } from 'next/server'
import { contentHeadquartersApiError, requireContentHeadquartersUser, type ContentHeadquartersPermission } from '@/lib/market-os/content-command-headquarters/auth'
import { addCampaignExperiment, addCampaignWave, convertCampaignToWorkflow, createCampaignCandidate, decideCampaign, duplicateCampaign, lifecycleCampaign, linkCanonicalCampaign, mergeCampaigns, updateCampaignProfile } from '@/lib/market-os/content-command-headquarters/campaign-orchestration-service'
const clean=(value:unknown)=>String(value||'').trim();const list=(value:unknown)=>Array.isArray(value)?value.map(String).map(item=>item.trim()).filter(Boolean):[]
export const dynamic='force-dynamic'
export async function POST(request:NextRequest){try{const body=await request.json() as Record<string,unknown>;const action=clean(body.action);const permission:ContentHeadquartersPermission=action==='permanent_delete'?'purge':action==='archive'?'archive':['authorize','activate','pause','resume','cancel','complete','close','reopen','supersede','override'].includes(action)?'govern':action==='generate_candidate'?'configure_ai':action==='edit'?'edit':'operate';const actor=await requireContentHeadquartersUser(permission);let result:unknown
 if(action==='create_candidate'||action==='generate_candidate')result=await createCampaignCandidate({actorId:actor.id,actorName:actor.name,title:clean(body.title),opportunityIds:list(body.opportunityIds),reason:clean(body.reason),useAi:action==='generate_candidate',continuationMode:(clean(body.continuationMode)||'auto') as any})
 else if(action==='edit')result=await updateCampaignProfile({actorId:actor.id,actorName:actor.name,campaignId:clean(body.campaignId),reason:clean(body.reason),title:clean(body.title)||undefined,profilePatch:(body.profilePatch&&typeof body.profilePatch==='object'?body.profilePatch:{}) as Record<string,unknown>})
 else if(['submit','authorize','activate','pause','resume','cancel','complete','close','reopen','supersede'].includes(action))result=await decideCampaign({actorId:actor.id,actorName:actor.name,campaignId:clean(body.campaignId),decision:action as any,reason:clean(body.reason),conditions:list(body.conditions)})
 else if(action==='duplicate')result=await duplicateCampaign({actorId:actor.id,actorName:actor.name,campaignId:clean(body.campaignId),title:clean(body.title),reason:clean(body.reason)})
 else if(action==='merge')result=await mergeCampaigns({actorId:actor.id,actorName:actor.name,campaignIds:list(body.campaignIds),title:clean(body.title),reason:clean(body.reason)})
 else if(action==='convert')result=await convertCampaignToWorkflow({actorId:actor.id,actorName:actor.name,campaignId:clean(body.campaignId),reason:clean(body.reason),contentObjectIds:list(body.contentObjectIds),waveIds:list(body.waveIds),ownerId:clean(body.ownerId),ownerName:clean(body.ownerName),reviewerId:clean(body.reviewerId),reviewerName:clean(body.reviewerName),aiDirectorId:clean(body.aiDirectorId)})
 else if(action==='archive'||action==='permanent_delete')result=await lifecycleCampaign({actorId:actor.id,actorName:actor.name,campaignId:clean(body.campaignId),action:action as any,reason:clean(body.reason),confirmation:clean(body.confirmation)})
 else if(action==='link_canonical')result=await linkCanonicalCampaign({actorId:actor.id,actorName:actor.name,campaignId:clean(body.campaignId),externalCampaignId:clean(body.externalCampaignId),reason:clean(body.reason)})
 else if(action==='add_wave')result=await addCampaignWave({actorId:actor.id,actorName:actor.name,campaignId:clean(body.campaignId),reason:clean(body.reason),wave:(body.wave&&typeof body.wave==='object'?body.wave:{}) as any})
 else if(action==='add_experiment')result=await addCampaignExperiment({actorId:actor.id,actorName:actor.name,campaignId:clean(body.campaignId),reason:clean(body.reason),experiment:(body.experiment&&typeof body.experiment==='object'?body.experiment:{}) as any})
 else throw new Error('CAMPAIGN_ACTION_UNSUPPORTED')
 return NextResponse.json({ok:true,result})}catch(error){return contentHeadquartersApiError(error)}}
