import type { ProspectEnterpriseMode } from "./types"

export type ProspectRouteContract = {
  mode: ProspectEnterpriseMode
  href: string
  label: string
  eyebrow: string
  title: string
  description: string
  primaryAction: string
  primaryHref?: string
  focus: string
  accent: "navy" | "blue" | "teal" | "green" | "amber" | "red" | "violet"
}

export const PROSPECT_ROUTE_CONTRACTS: Record<ProspectEnterpriseMode, ProspectRouteContract> = {
  acquisition: {
    mode: "acquisition",
    href: "/revenue-command-center/prospects",
    label: "Acquisition",
    eyebrow: "Prospects & comptes · Acquisition",
    title: "Centre d’acquisition commerciale",
    description: "Piloter l’entrée des prospects, la qualité des données, la vitesse de prise en charge et la conversion vers un compte exploitable.",
    primaryAction: "Créer un prospect",
    primaryHref: "/revenue-command-center/prospects/new",
    focus: "Transformer chaque signal entrant en dossier commercial attribué, qualifié et actionnable.",
    accent: "navy",
  },
  directory: {
    mode: "directory",
    href: "/revenue-command-center/prospects/directory",
    label: "Répertoire",
    eyebrow: "Répertoire commercial unifié",
    title: "Prospects, comptes et responsables",
    description: "Rechercher, comparer et ouvrir chaque dossier depuis une vue dense conçue pour les opérations nationales.",
    primaryAction: "Nouveau dossier",
    primaryHref: "/revenue-command-center/prospects/new",
    focus: "Maintenir une identité commerciale fiable et éviter les dossiers sans propriétaire ni prochaine action.",
    accent: "blue",
  },
  executive: {
    mode: "executive",
    href: "/revenue-command-center/prospects/executive",
    label: "Direction",
    eyebrow: "Lecture Direction · Portefeuille prospects",
    title: "Posture exécutive du développement commercial",
    description: "Valeur pondérée, concentration du portefeuille, pression opérationnelle et interventions requises par la Direction.",
    primaryAction: "Ouvrir le pipeline",
    primaryHref: "/revenue-command-center/prospects/pipeline",
    focus: "Arbitrer les priorités, protéger la valeur et accélérer les dossiers stratégiques.",
    accent: "navy",
  },
  pipeline: {
    mode: "pipeline",
    href: "/revenue-command-center/prospects/pipeline",
    label: "Pipeline",
    eyebrow: "Progression commerciale",
    title: "Pipeline prospects et opportunités",
    description: "Visualiser la progression réelle, la valeur par étape, les dossiers stagnants et les prochaines transitions contrôlées.",
    primaryAction: "Créer une opportunité",
    focus: "Faire avancer les dossiers avec preuve, propriétaire et prochaine étape explicite.",
    accent: "teal",
  },
  qualification: {
    mode: "qualification",
    href: "/revenue-command-center/prospects/qualification",
    label: "Qualification",
    eyebrow: "Qualité commerciale",
    title: "Bureau de qualification entreprise",
    description: "Évaluer le besoin, l’autorité, le budget, le timing, l’adéquation et la qualité des preuves avant progression.",
    primaryAction: "Évaluer un dossier",
    focus: "Refuser les progressions superficielles et protéger le temps commercial ANGELCARE.",
    accent: "green",
  },
  "decision-map": {
    mode: "decision-map",
    href: "/revenue-command-center/prospects/decision-map",
    label: "Décision",
    eyebrow: "Cartographie des décideurs",
    title: "Centre de pouvoir et d’influence",
    description: "Identifier les décideurs, sponsors, bloqueurs, utilisateurs et influenceurs qui déterminent la conversion.",
    primaryAction: "Ajouter un décideur",
    focus: "Ne jamais négocier avec une organisation sans comprendre qui décide, qui influence et qui bloque.",
    accent: "violet",
  },
  appointments: {
    mode: "appointments",
    href: "/revenue-command-center/prospects/appointments",
    label: "Rendez-vous",
    eyebrow: "Préparation commerciale",
    title: "Rendez-vous reliés aux prospects",
    description: "Préparer les rencontres, contrôler les objectifs, détecter les dossiers sans rendez-vous et assurer les suites.",
    primaryAction: "Planifier un rendez-vous",
    primaryHref: "/revenue-command-center/appointments/new",
    focus: "Chaque rendez-vous doit produire une décision, un engagement ou une prochaine étape datée.",
    accent: "blue",
  },
  proposals: {
    mode: "proposals",
    href: "/revenue-command-center/prospects/proposals",
    label: "Propositions",
    eyebrow: "Préparation des offres",
    title: "Portefeuille des propositions commerciales",
    description: "Identifier les dossiers prêts, incomplets, bloqués ou exposés avant l’entrée dans le Studio de proposition.",
    primaryAction: "Ouvrir les dossiers prêts",
    focus: "Aucune proposition ne doit partir sans besoin validé, décideur identifié et valeur défendable.",
    accent: "amber",
  },
  negotiation: {
    mode: "negotiation",
    href: "/revenue-command-center/prospects/negotiation",
    label: "Négociation",
    eyebrow: "Protection de valeur",
    title: "Salle de négociation commerciale",
    description: "Concentrer les dossiers en négociation, les objections, les risques de concession et les décisions attendues.",
    primaryAction: "Ouvrir un dossier",
    focus: "Protéger la marge, structurer les concessions et conserver une trace de chaque position.",
    accent: "amber",
  },
  recovery: {
    mode: "recovery",
    href: "/revenue-command-center/prospects/recovery",
    label: "Récupération",
    eyebrow: "Revenue Rescue",
    title: "Cellule de récupération commerciale",
    description: "Réactiver les dossiers stagnants, perdus ou silencieux avec un plan, un responsable et une échéance.",
    primaryAction: "Lancer une récupération",
    focus: "Transformer les silences et blocages en interventions mesurées plutôt qu’en perte invisible.",
    accent: "red",
  },
  analytics: {
    mode: "analytics",
    href: "/revenue-command-center/prospects/analytics",
    label: "Analytics",
    eyebrow: "Intelligence portefeuille",
    title: "Analyse des prospects et de la valeur",
    description: "Comprendre la distribution, la vélocité, la concentration, la qualité et la valeur pondérée du portefeuille.",
    primaryAction: "Voir la performance",
    primaryHref: "/revenue-command-center/prospects/performance",
    focus: "Relier chaque métrique à une décision commerciale et à une action vérifiable.",
    accent: "blue",
  },
  performance: {
    mode: "performance",
    href: "/revenue-command-center/prospects/performance",
    label: "Performance",
    eyebrow: "Exécution des équipes",
    title: "Performance et discipline du portefeuille",
    description: "Comparer la charge, la valeur, les retards, la qualité et la progression par responsable commercial.",
    primaryAction: "Rééquilibrer la charge",
    primaryHref: "/revenue-command-center/workload-balancer",
    focus: "Récompenser la progression réelle, corriger les portefeuilles abandonnés et équilibrer la charge.",
    accent: "green",
  },
  "high-value": {
    mode: "high-value",
    href: "/revenue-command-center/prospects/high-value",
    label: "Haute valeur",
    eyebrow: "Comptes stratégiques",
    title: "Portefeuille prospects à haute valeur",
    description: "Isoler les dossiers les plus importants, leur concentration de risque et les prochaines décisions de Direction.",
    primaryAction: "Ouvrir le briefing exécutif",
    primaryHref: "/revenue-command-center/executive-briefing",
    focus: "Donner un traitement disproportionné aux dossiers qui peuvent transformer le revenu ANGELCARE.",
    accent: "navy",
  },
  risk: {
    mode: "risk",
    href: "/revenue-command-center/prospects/risk",
    label: "Risques",
    eyebrow: "Protection du pipeline",
    title: "Radar des risques commerciaux",
    description: "Classer les risques par sévérité, probabilité, impact, propriétaire et échéance de mitigation.",
    primaryAction: "Déclarer un risque",
    focus: "Rendre les risques visibles avant qu’ils ne deviennent des pertes de revenu.",
    accent: "red",
  },
  new: {
    mode: "new",
    href: "/revenue-command-center/prospects/new",
    label: "Nouveau",
    eyebrow: "Création contrôlée",
    title: "Studio de création d’un dossier commercial",
    description: "Créer le prospect, le compte, le contact principal et l’opportunité initiale sans fragmenter la source de vérité.",
    primaryAction: "Enregistrer le dossier",
    focus: "Capturer suffisamment de contexte pour déclencher une prise en charge immédiate et responsable.",
    accent: "navy",
  },
}

export const PROSPECT_ROUTE_NAVIGATION = [
  PROSPECT_ROUTE_CONTRACTS.acquisition,
  PROSPECT_ROUTE_CONTRACTS.directory,
  PROSPECT_ROUTE_CONTRACTS.pipeline,
  PROSPECT_ROUTE_CONTRACTS.qualification,
  PROSPECT_ROUTE_CONTRACTS["decision-map"],
  PROSPECT_ROUTE_CONTRACTS.appointments,
  PROSPECT_ROUTE_CONTRACTS.proposals,
  PROSPECT_ROUTE_CONTRACTS.negotiation,
  PROSPECT_ROUTE_CONTRACTS.recovery,
  PROSPECT_ROUTE_CONTRACTS["high-value"],
  PROSPECT_ROUTE_CONTRACTS.risk,
  PROSPECT_ROUTE_CONTRACTS.analytics,
  PROSPECT_ROUTE_CONTRACTS.performance,
  PROSPECT_ROUTE_CONTRACTS.executive,
]
