import Link from 'next/link'
import type { CmsBlock } from '../../experience-builder/types'
import type { PublicPageExperience } from '../types'
import { PublicInquiryForm } from './PublicInquiryForm'
import styles from '../public.module.css'

function text(value:unknown,fallback=''){return typeof value==='string'?value:fallback}
function list(value:unknown):Record<string,unknown>[]{return Array.isArray(value)?value.filter((item):item is Record<string,unknown>=>Boolean(item)&&typeof item==='object'&&!Array.isArray(item)):[]}
function ctaHref(key:unknown,locale:string){const map:Record<string,string>={family_start:'/angelcare-marketplace/family/request',family_diagnostic:'/angelcare-marketplace/family/diagnostic',family_request:'/angelcare-marketplace/family/request',contact:`/angelcare-marketplace/${locale}/contact`,schools:`/angelcare-marketplace/${locale}/establishments`,hotels:`/angelcare-marketplace/${locale}/hospitality`,clinics:`/angelcare-marketplace/${locale}/health-partners`,corporates:`/angelcare-marketplace/${locale}/corporates`,academy:`/angelcare-marketplace/${locale}/academy`,partner_os:`/angelcare-marketplace/${locale}/partner-os`,marketplace:`/angelcare-marketplace/${locale}/marketplace`};return map[String(key)]||`/angelcare-marketplace/${locale}/contact`}
function Block({block,locale,route}:{block:CmsBlock;locale:'fr'|'en'|'ar';route:string}){const c=block.content
  if(block.block_type==='hero')return <section className={styles.hero}><div><span className={styles.heroEyebrow}>{text(c.eyebrow,'ANGELCARE BUILD 360')}</span><h1>{text(c.title)}</h1><p>{text(c.lead)}</p><div className={styles.actions}><Link className={styles.primary} href={ctaHref(c.primaryCtaKey,locale)}>{text(c.primaryCtaLabel,'Commencer')}</Link>{c.secondaryCtaKey?<Link className={styles.secondary} href={ctaHref(c.secondaryCtaKey,locale)}>{text(c.secondaryCtaLabel,'Découvrir')}</Link>:null}</div></div><div className={styles.heroVisual}><div className={styles.visualContent}><span>{text(c.visualKicker,'Une méthode gouvernée')}</span><strong>{text(c.visualTitle,'Confiance, clarté et continuité.')}</strong><p>{text(c.visualText,'Chaque parcours se rattache à un dossier, une équipe et une prochaine action.')}</p></div></div></section>
  if(block.block_type==='audience_router')return <section className={`${styles.section} ${styles.sectionAlt}`}><header className={styles.sectionHeader}><span>Orientation</span><h2>{text(c.title)}</h2><p>{text(c.lead)}</p></header><div className={styles.audienceGrid}>{list(c.audiences).map((item,index)=><article className={styles.audienceCard} key={index}><div><strong>{text(item.title)}</strong><p>{text(item.description)}</p></div><Link href={ctaHref(item.ctaKey,locale)}>{text(item.ctaLabel,'Explorer')} →</Link></article>)}</div></section>
  if(block.block_type==='service_grid'||block.block_type==='proof_grid')return <section className={styles.section}><header className={styles.sectionHeader}><span>{block.block_type==='proof_grid'?'Preuves':'Architecture'}</span><h2>{text(c.title)}</h2><p>{text(c.lead)}</p></header><div className={styles.serviceGrid}>{list(c.items).map((item,index)=><article className={styles.serviceCard} key={index}><span>{text(item.label,'ANGELCARE')}</span><h3>{text(item.title)}</h3><p>{text(item.description)}</p></article>)}</div></section>
  if(block.block_type==='trust_strip')return <section className={styles.section}><div className={styles.trustStrip}>{list(c.items).map((item,index)=><article className={styles.trustItem} key={index}><strong>{text(item.title)}</strong><p>{text(item.description)}</p></article>)}</div></section>
  if(block.block_type==='editorial')return <section className={`${styles.section} ${styles.editorial}`}><div><header className={styles.sectionHeader}><span>{text(c.kicker,'Notre approche')}</span><h2>{text(c.title)}</h2></header><div className={styles.editorialBody}>{text(c.body)}</div></div><aside className={styles.editorialAside}>{text(c.aside)}</aside></section>
  if(block.block_type==='timeline'||block.block_type==='family_story')return <section className={`${styles.section} ${styles.sectionAlt}`}><header className={styles.sectionHeader}><span>Parcours</span><h2>{text(c.title)}</h2></header><div className={styles.timeline}>{list(c.steps||c.stages).map((item,index)=><article className={styles.step} key={index}><strong>{text(item.title)}</strong><p>{text(item.description)}</p></article>)}</div></section>
  if(block.block_type==='faq')return <section className={styles.section}><header className={styles.sectionHeader}><span>Questions fréquentes</span><h2>{text(c.title)}</h2></header><div className={styles.faq}>{list(c.items).map((item,index)=><details key={index}><summary>{text(item.question)}</summary><p>{text(item.answer)}</p></details>)}</div></section>
  if(block.block_type==='inquiry_form')return <section className={styles.section}><PublicInquiryForm locale={locale} audience={text(c.audience,'other')} sourceRoute={route} title={text(c.title,'Parlons de votre besoin')} lead={text(c.lead,'Votre demande sera enregistrée et orientée vers la bonne équipe.')}/></section>
  if(['marketplace_entry','partner_os_entry','academy_entry'].includes(block.block_type))return <section className={styles.section}><header className={styles.sectionHeader}><span>{text(c.availabilityLabel,'Accès gouverné')}</span><h2>{text(c.title)}</h2><p>{text(c.lead)}</p></header><Link className={styles.primary} href={ctaHref(c.ctaKey,locale)}>{text(c.ctaLabel,'Découvrir')}</Link></section>
  if(block.block_type==='cta_band')return <section className={styles.ctaBand}><div><h2>{text(c.title)}</h2><p>{text(c.lead)}</p></div><Link className={styles.primary} href={ctaHref(c.ctaKey,locale)}>{text(c.ctaLabel,'Continuer')}</Link></section>
  return null
}
export function PublicPageRenderer({experience,locale}:{experience:PublicPageExperience;locale:'fr'|'en'|'ar'}){const route=`/angelcare-marketplace/${locale}/${experience.page.slug}`;return <>{experience.blocks.map(block=><Block block={block} locale={locale} route={route} key={block.id}/>)}</>}
