\pset pager off
SELECT installation_key,release_code,module_version,execution_mode,contract_locked,external_actions_enabled,metadata->>'currentPhase' AS current_phase,metadata->>'missionCompiler' AS mission_compiler,metadata->>'deterministicCompilation' AS deterministic,metadata->>'propagationEnabled' AS propagation_enabled FROM public.revenue_os_installations WHERE installation_key='revenue-command-os';
SELECT count(*) AS compiler_tables FROM information_schema.tables WHERE table_schema='public' AND table_name IN ('revenue_os_compilation_runs','revenue_os_compilation_blueprints','revenue_os_revenue_plays','revenue_os_programs','revenue_os_campaigns','revenue_os_campaign_waves','revenue_os_account_plans','revenue_os_missions','revenue_os_mission_tasks','revenue_os_task_steps','revenue_os_compiled_scripts','revenue_os_evidence_requirements','revenue_os_compiled_deadlines','revenue_os_compiled_capacity_requirements','revenue_os_compiled_owners','revenue_os_assignment_eligibility','revenue_os_compilation_dependencies','revenue_os_compilation_approval_gates','revenue_os_compilation_kpis','revenue_os_compilation_retry_rules','revenue_os_compilation_rescue_routes','revenue_os_compilation_stop_conditions','revenue_os_compilation_escalations','revenue_os_compilation_conflicts','revenue_os_compilation_versions','revenue_os_compilation_deltas','revenue_os_compilation_rollbacks','revenue_os_compilation_audit_events','revenue_os_propagation_packages');
SELECT count(*) AS external_action_violations FROM (SELECT external_actions FROM public.revenue_os_compilation_runs WHERE external_actions<>0 UNION ALL SELECT external_actions FROM public.revenue_os_compilation_blueprints WHERE external_actions<>0 UNION ALL SELECT external_actions FROM public.revenue_os_propagation_packages WHERE external_actions<>0) x;
SELECT count(*) AS eligible_mz12_approvals FROM public.revenue_os_approval_requests WHERE ready_for_mz13=true;
DO $$ BEGIN
 IF (SELECT count(*) FROM information_schema.tables WHERE table_schema='public' AND table_name IN ('revenue_os_compilation_runs','revenue_os_compilation_blueprints','revenue_os_revenue_plays','revenue_os_programs','revenue_os_campaigns','revenue_os_campaign_waves','revenue_os_account_plans','revenue_os_missions','revenue_os_mission_tasks','revenue_os_task_steps','revenue_os_compiled_scripts','revenue_os_evidence_requirements','revenue_os_compiled_deadlines','revenue_os_compiled_capacity_requirements','revenue_os_compiled_owners','revenue_os_assignment_eligibility','revenue_os_compilation_dependencies','revenue_os_compilation_approval_gates','revenue_os_compilation_kpis','revenue_os_compilation_retry_rules','revenue_os_compilation_rescue_routes','revenue_os_compilation_stop_conditions','revenue_os_compilation_escalations','revenue_os_compilation_conflicts','revenue_os_compilation_versions','revenue_os_compilation_deltas','revenue_os_compilation_rollbacks','revenue_os_compilation_audit_events','revenue_os_propagation_packages'))<>29 THEN RAISE EXCEPTION 'MZ13 verification failed: table count'; END IF;
 IF EXISTS(SELECT 1 FROM public.revenue_os_installations WHERE installation_key='revenue-command-os' AND (release_code<>'AC-REVENUE-OS-MZ13-MISSION-COMPILER' OR execution_mode<>'shadow' OR external_actions_enabled)) THEN RAISE EXCEPTION 'MZ13 verification failed: registry or safety'; END IF;
END $$;
