import 'server-only'
import { createServiceClient } from '@/lib/supabase/server'
import { PRODUCTION_TENANT_KEY, PRODUCTION_VIEW_PREFIX } from '../config'
import { compileExternalProductionCommand } from '../adapters/openrouter-command'
import { getProductionCommand, persistCompiledCommand, setCommandValidation } from './repository'
import { resolveProductionSource } from './source-resolver'
import type { ActorContext, ProductionCommand, ProductionSourceType } from '../types'
function table(client:Awaited<ReturnType<typeof createServiceClient>>,name:string){return client.from(`${PRODUCTION_VIEW_PREFIX}${name}`)}
const requiredKeys=['mission','authority','content','pedagogy','creative','technical','producer','negative','quality','manifest','evidence']
export function deterministicCommandValidation(command:ProductionCommand){const findings:string[]=[];if(!command.sourceType||!command.sourceId)findings.push('Production source authority is missing.');if(!command.collectionIds.length&&command.sourceType!=='product_design')findings.push('Collection lineage is missing for this production source.');if(!command.edition.trim())findings.push('Edition is required.');if(!command.variant.trim())findings.push('Commercial variant is required.');if(!command.externalProfile.trim())findings.push('External production profile is required.');const keys=new Set(command.sections.map((section)=>section.key));for(const key of requiredKeys)if(!keys.has(key))findings.push(`Required command section is missing: ${key}.`);for(const section of command.sections)if(!section.content.trim())findings.push(`Section ${section.title} has no production instruction.`);if(!command.sections.find((s)=>s.key==='manifest')?.content.match(/source|final|preview|manifest/i))findings.push('Delivery manifest does not define the required returned package.');if(!command.sections.find((s)=>s.key==='negative')?.content.trim())findings.push('Negative constraints are mandatory.');return findings}
export async function compileCommand(commandId:string,actor:ActorContext){const client=await createServiceClient();const {data:command,error:commandError}=await table(client,'production_commands').select('*').eq('tenant_key',PRODUCTION_TENANT_KEY).eq('id',commandId).single();if(commandError||!command)throw new Error('Production Command not found.');const sourceType=String(command.source_type||'product_design') as ProductionSourceType;const sourceId=String(command.source_id||command.design_id||command.collection_id||'');const source=await resolveProductionSource(sourceType,sourceId);const result=await compileExternalProductionCommand({source:{type:source.sourceType,id:source.sourceId,title:source.title,code:source.code,status:source.status,snapshot:source.sourceSnapshot,collectionIds:source.collectionIds},collection:source.primaryCollection||{id:source.collectionId},outputType:command.output_type,edition:command.edition,variant:command.variant,externalProfile:command.external_profile});return persistCompiledCommand(commandId,{title:result.title,mission:result.mission,sections:result.sections,advisoryFindings:result.advisoryFindings,usage:result},actor)}
export async function validateCommand(commandId:string,actor:ActorContext){const command=await getProductionCommand(commandId);if(!command)throw new Error('Production Command not found.');const findings=deterministicCommandValidation(command);return setCommandValidation(command.id,findings,actor)}
