import { executionConfig } from './config'
import { hashPayload, stableId } from './crypto'
import { EXTERNAL_ACTIONS, requiresApproval } from './policies'
import type { ActionMappingContext, AdapterCode, ExecutionAction, ExecutionActionType, Reversibility } from './types'
const toolMap:Array<[RegExp,AdapterCode,ExecutionActionType]>= [
 [/campaign|campagne/i,'campaigns','create_campaign'],[/wave|cohort/i,'campaigns','create_account_wave'],[/assign|affect|owner/i,'internal_tasks','assign_account'],[/whatsapp/i,'whatsapp','prepare_message'],[/email|mail/i,'email_os','prepare_email'],[/follow|relance|reminder/i,'internal_tasks','schedule_followup'],[/meeting|réunion|rendez/i,'meetings','propose_meeting'],[/brief/i,'meetings','prepare_meeting_brief'],[/proposal|proposition|offre/i,'proposals','draft_proposal'],[/approval|approbation/i,'internal_tasks','request_approval'],[/stage|étape|pipeline/i,'opportunities','update_stage'],[/rescue|sauvetage|recovery/i,'opportunities','launch_rescue_mission'],[/delivery|livraison|handoff/i,'academy_delivery','create_delivery_handoff'],[/payment|paiement|recouvrement/i,'payments','create_payment_followup'],[/renew|renouvel/i,'traininghub_commercial','initiate_renewal']]
function choose(ctx:ActionMappingContext):[AdapterCode,ExecutionActionType]{const hay=[ctx.task.title,ctx.task.purpose,ctx.task.nextAction,...ctx.task.allowedTools].join(' ');for(const row of toolMap)if(row[0].test(hay))return[row[1],row[2]];return['internal_tasks','schedule_followup']}
function rollback(action:ExecutionActionType):Reversibility{if(['send_email','send_whatsapp','send_proposal'].includes(action))return'compensatable';if(action==='create_calendar_event')return'cancellable';return'reversible'}
export function mapTaskToAction(ctx:ActionMappingContext):ExecutionAction{const [adapterCode,actionType]=choose(ctx);const runtime=executionConfig();const external=EXTERNAL_ACTIONS.has(actionType);const payload={title:ctx.task.title,purpose:ctx.task.purpose,businessImpact:ctx.task.businessImpact,accountId:ctx.task.accountId,segment:ctx.task.segment,territory:ctx.task.territory,ownerId:ctx.task.ownerId,ownerRole:ctx.task.ownerRole,dueAt:ctx.task.dueAt,allowedTools:ctx.task.allowedTools,scriptId:ctx.task.scriptId,templateReference:ctx.task.templateReference,successCondition:ctx.task.successCondition,failureCondition:ctx.task.failureCondition,nextAction:ctx.task.nextAction,completionOutputSchema:ctx.task.completionOutputSchema};const idempotencyKey=hashPayload({tenantId:ctx.package.tenantId,taskId:ctx.task.id,adapterCode,actionType,payload,generation:1});const createdAt=new Date().toISOString();const id=stableId('mz14-action',ctx.package.id,ctx.task.id,adapterCode,actionType);const required=requiresApproval(actionType,external);return{id,tenantId:ctx.package.tenantId,propagationRunId:'',packageId:ctx.package.id,adapterCode,actionType,source:{objectiveId:String(ctx.blueprint.run.objectiveId),strategyId:ctx.blueprint.run.strategyId,strategyVersion:ctx.blueprint.run.strategyVersion,approvalRequestId:ctx.blueprint.run.approvalRequestId,approvalDecisionId:ctx.blueprint.run.approvalDecisionId,compilationId:ctx.blueprint.run.id,missionId:ctx.task.missionId,taskId:ctx.task.id},target:{module:adapterCode,entityType:actionType,entityId:ctx.task.accountId},payload,approval:{class:required?'action_approval':'internal_record',required,decisionId:required?undefined:ctx.blueprint.run.approvalDecisionId,conditions:[]},controls:{idempotencyKey,executionMode:runtime.mode,maximumAttempts:runtime.maxAttempts,timeoutMs:runtime.timeoutMs,rollbackPolicy:rollback(actionType),sensitive:['gmail','whatsapp','payments','proposals'].includes(adapterCode),externalAction:external,approvalRequired:required},status:required?'awaiting_approval':'validated',priority:ctx.task.priority==='critical'?100:ctx.task.priority==='high'?80:50,scheduledAt:ctx.task.startAt,createdAt,updatedAt:createdAt,attemptCount:0,generation:1}}
