import {notFound} from 'next/navigation'
import {DiscoverySearch} from '@/angelcare-marketplace/catalog-discovery/components/DiscoverySearch'
import {CategoryNativeCard} from '@/angelcare-marketplace/category-native-experience/components/CategoryNativeCard'
import {CategoryNativeFilters} from '@/angelcare-marketplace/category-native-experience/components/CategoryNativeFilters'
import {categoryNativeFilters} from '@/angelcare-marketplace/category-native-experience/repository'
import {searchDiscovery} from '@/angelcare-marketplace/catalog-discovery/repository'
import type {CatalogLocale,DiscoveryItem} from '@/angelcare-marketplace/catalog-discovery/types'
import styles from '@/angelcare-marketplace/catalog-discovery/catalog-discovery.module.css'
function configured(item:DiscoveryItem,key:string){const nested=item.metadata.experience_configuration;const source=nested&&typeof nested==='object'&&!Array.isArray(nested)?nested as Record<string,unknown>:item.metadata;return source[key]}
function matches(item:DiscoveryItem,filters:Record<string,string>){return Object.entries(filters).every(([key,expected])=>{const value=configured(item,key);if(Array.isArray(value))return value.map(String).includes(expected);return String(value??'').toLocaleLowerCase().includes(expected.toLocaleLowerCase())})}
export default async function Page({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){const {locale}=await params;if(!['fr','en','ar'].includes(locale))notFound();const s=await searchParams;const one=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]:v;const data=await searchDiscovery({locale:locale as CatalogLocale,query:one(s.q),territoryCode:one(s.territory),kind:one(s.kind),category:one(s.category),availability:one(s.availability),sort:one(s.sort),limit:240});const selected=Object.fromEntries(Object.entries(s).filter(([key,value])=>key.startsWith('filter_')&&one(value)).map(([key,value])=>[key.slice(7),String(one(value))]));const items=data.items.filter((item)=>matches(item,selected));const schemaKeys:string[]=[...new Set<string>(data.items.map((item)=>String(item.metadata.experience_schema_key||'')).filter(Boolean))];const nativeFilters=await categoryNativeFilters({locale:locale as CatalogLocale,schemaKeys,categoryKey:one(s.category)});return <main className={styles.marketplace} dir={locale==='ar'?'rtl':'ltr'}><section className={styles.resultSection}><header><div><span>ADAPTIVE MARKETPLACE SEARCH</span><h1>{locale==='fr'?'Trouvez la meilleure réponse à votre besoin':locale==='ar'?'اعثر على أفضل استجابة لاحتياجك':'Find the best answer to your need'}</h1></div></header><DiscoverySearch locale={locale as CatalogLocale} categories={data.categories} total={items.length}/><CategoryNativeFilters filters={nativeFilters} locale={locale as CatalogLocale} route={`/angelcare-marketplace/${locale}/marketplace/search`}/><div className={styles.cardGrid}>{items.map(item=><CategoryNativeCard key={item.id} item={item} locale={locale as CatalogLocale} schemaKey={String(item.metadata.experience_schema_key||item.category_title||item.kind)}/>)}</div></section></main>}
