import type { RevenueStrategy } from '../strategy-brain/types'
import { accountLimit, allowedTerritories, approvedDeadline, budgetLimit, compileApprovalConditions } from './approval-conditions'
import { resolveOwner, type AssignmentCandidate } from './assignment'
import { buildCapacityRequirements } from './capacity'
import { detectConflicts } from './conflict-detector'
import { validateDependencyGraph } from './dependency-graph'
import { code, hashObject, isoNow, stableUuid } from './identifiers'
import { kpi } from './kpis'
import type { AccountPlan, CampaignWave, CompilationApprovalGate, CompilationBlueprint, CompilationDependency, CompilationEligibility, CompilationEscalation, CompilationKpi, CompilationRescueRoute, CompilationRetryRule, CompilationRun, CompilationStopCondition, CompiledBase, CompiledCampaign, CompiledDeadline, AssignmentEligibility, CompiledMission, CompiledOwner, CompiledScript, CompiledTask, EvidenceRequirement, ExecutionStep, RevenuePlay, RevenueProgram, CompilationLevel } from './types'

const VERSION='13.0.0'
const now=()=>isoNow()
const plusDays=(date:string,days:number)=>{const d=new Date(date);d.setUTCDate(d.getUTCDate()+days);return d.toISOString()}
function base(run:CompilationRun,kind:string,key:string):CompiledBase{return{id:stableUuid(run.id,kind,key),code:code(kind.toUpperCase().slice(0,5),run.id,key),tenantId:run.tenantId,compilationRunId:run.id,strategyId:run.strategyId,strategyVersion:run.strategyVersion,approvalDecisionId:run.approvalDecisionId,version:'1.0.0',status:'draft',createdAt:now(),externalActions:0}}
function evidence(run:CompilationRun,level:CompilationLevel,objectId:string,key:string,label:string,kind:EvidenceRequirement['kind']='required'):EvidenceRequirement{return{...base(run,'evidence',`${objectId}:${key}`),level,objectId,kind,label,description:`Preuve requise: ${label}`,sourceTypes:['system_record','document','interaction','approval'],required:kind!=='optional',sensitive:kind==='sensitive',completionRule:'Une référence vérifiable et horodatée doit être attachée.'}}
function retry(run:CompilationRun,level:CompilationLevel,objectId:string):CompilationRetryRule{return{...base(run,'retry',objectId),level,objectId,maximumAttempts:3,minimumDelayHours:48,channelRotation:['email_draft','phone_task','whatsapp_draft'],retryConditions:['no_response','temporary_unavailability'],stopRetryWhen:['explicit_rejection','invalid_contact','account_blocked','approval_expired']}}
function rescue(run:CompilationRun,level:CompilationLevel,objectId:string,destinationRole='revenue_manager'):CompilationRescueRoute{return{...base(run,'rescue',objectId),level,objectId,trigger:'failure_condition_met',action:'review_and_reframe',destinationRole,requiredEvidence:['failure_evidence','interaction_history'],status:'available',stopAfterRescue:false}}
function stop(run:CompilationRun,level:CompilationLevel,objectId:string,condition:string,signal:string,threshold:unknown,action:CompilationStopCondition['action']='stop'):CompilationStopCondition{return{...base(run,'stop',`${objectId}:${signal}`),level,objectId,condition,signal,operator:'triggered',threshold,action,severity:'critical'}}
function escalation(run:CompilationRun,level:CompilationLevel,objectId:string,destinationRole:string):CompilationEscalation{return{...base(run,'escalation',objectId),level,objectId,trigger:'critical_failure_or_expired_gate',severity:'high',destinationRole,deadlineHours:24,requiredContext:['objective','strategy_version','account_context','failure_reason'],requiredEvidence:['failure_evidence'],fallbackIfUnanswered:'pause_and_return_to_strategy_studio'}}
function gate(run:CompilationRun,level:CompilationLevel,objectId:string,gateType:string,approvalClass:string,conditionId?:string,status:CompilationApprovalGate['status']='required'):CompilationApprovalGate{return{...base(run,'gate',`${objectId}:${gateType}:${conditionId||''}`),level,objectId,gateType,approvalClass,requiredRoles:approvalClass==='multi_director'?['managing_director','operations_director']:['revenue_manager'],conditionId,status,machineReadable:true}}
function script(run:CompilationRun,taskId:string,type:string,channel:string,audience:string,strategy:RevenueStrategy):CompiledScript{return{...base(run,'script',`${taskId}:${channel}`),taskType:type,audience,channel,language:'fr',purpose:`Soutenir ${type} sans engagement externe automatique.`,approvedContent:`Préparer un brouillon ${channel} aligné sur la proposition de valeur approuvée: ${strategy.valueProposition}`,allowedVariables:['account_name','decision_maker_name','territory','approved_offer','meeting_window'],prohibitedClaims:['garantie de résultat','prix non approuvé','capacité non confirmée','fausse rareté'],approvalClass:'standard',sourceDoctrineIds:strategy.trustEvidence.map(x=>x.evidenceId)}}

interface MissionTemplate { code:string; title:string; purpose:string; role:string; tasks:Array<{title:string;purpose:string;tool:string;effort:number}> }
const missionTemplates:MissionTemplate[]=[
  {code:'research',title:'Recherche et qualification du compte',purpose:'Vérifier le compte, ses décideurs et son potentiel réel.',role:'business_developer',tasks:[{title:'Vérifier le dossier compte',purpose:'Confirmer identité, segment, territoire et historique.',tool:'account_research',effort:45},{title:'Cartographier les décideurs',purpose:'Identifier autorité économique et opérationnelle.',tool:'stakeholder_research',effort:60}]},
  {code:'activation',title:'Activation commerciale gouvernée',purpose:'Préparer une activation multicanale conforme aux conditions approuvées.',role:'business_developer',tasks:[{title:'Préparer le message de premier contact',purpose:'Créer un brouillon adapté au décideur.',tool:'message_draft',effort:35},{title:'Préparer le plan de suivi',purpose:'Définir cadence, canaux, retries et arrêt.',tool:'sequence_planner',effort:30}]},
  {code:'conversion',title:'Conversion réunion et proposition',purpose:'Préparer la réunion, le diagnostic et la progression vers proposition.',role:'account_manager',tasks:[{title:'Préparer le brief réunion',purpose:'Structurer objectifs, preuves et questions diagnostiques.',tool:'meeting_brief',effort:60},{title:'Préparer la posture de proposition',purpose:'Définir offre, prix approuvé, gates et prochaine décision.',tool:'proposal_draft',effort:75}]},
]

export function buildCompilationRun(eligibility:CompilationEligibility,input:{actorId:string;scope:CompilationRun['scope'];idempotencyKey:string;previousRunId?:string}):CompilationRun{const source=eligibility.source;return{id:stableUuid(source.tenantId,source.strategy.id,source.strategy.version,source.approvalDecisionId,VERSION,input.scope,input.idempotencyKey),tenantId:source.tenantId,objectiveId:source.objective.id,strategyId:source.strategy.id,strategyVersion:source.strategy.version,approvalRequestId:source.approval.id,approvalDecisionId:source.approvalDecisionId,councilRunId:source.councilRunId,compilerVersion:VERSION,scope:input.scope,status:eligibility.eligible?'building_blueprint':'blocked',idempotencyKey:input.idempotencyKey,requestedBy:input.actorId,sourceHash:hashObject({context:source.contextHash,strategy:source.strategy.version,approval:source.approval.id,conditions:source.approvalConditions}),startedAt:now(),previousRunId:input.previousRunId,externalActions:0}}

export function buildBlueprint(eligibility:CompilationEligibility,run:CompilationRun,candidates:AssignmentCandidate[]=[]):CompilationBlueprint{
  if(!eligibility.eligible)throw new Error(`COMPILATION_SOURCE_BLOCKED:${eligibility.blockers.join(',')}`)
  const {source}=eligibility;const {strategy,objective}=source;const conditionConstraints=compileApprovalConditions(source.approvalConditions,strategy)
  const territories=allowedTerritories(source.approvalConditions,objective.territories.length?objective.territories:strategy.targetMarket).slice(0,6);if(!territories.length)throw new Error('NO_APPROVED_TERRITORY')
  const segments=(objective.targetSegments.length?objective.targetSegments:strategy.targetSegments).slice(0,6);if(!segments.length)throw new Error('NO_TARGET_SEGMENT')
  const start=now();const rawEnd=objective.deadline||plusDays(start,180);const end=approvedDeadline(source.approvalConditions,rawEnd);const budget=budgetLimit(source.approvalConditions,objective.budgetLimit)
  const play:RevenuePlay={...base(run,'play',strategy.id),name:`Revenue Play — ${strategy.archetype}`,purpose:strategy.objective,commercialThesis:strategy.thesis,businessUnits:objective.businessUnits,segments,territories,offers:objective.approvedOffers,economicModel:{pricingPosture:strategy.pricingPosture,revenueTarget:objective.revenueTarget,marginTarget:objective.marginTarget,budget},activationConditions:['MZ12 approval valid',...conditionConstraints.map(c=>`${c.key}:${c.operator}`)],successDefinition:objective.successDefinition,failureDefinition:objective.failureDefinition,constraints:objective.constraints,approvalConditionIds:source.approvalConditions.map(c=>c.id),ownerRole:'revenue_manager',programIds:[]}
  const program:RevenueProgram={...base(run,'program',play.id),playId:play.id,title:`Programme — ${objective.title}`,objective:strategy.objective,revenueTarget:objective.revenueTarget,marginTarget:objective.marginTarget,startDate:start,endDate:end,businessUnits:objective.businessUnits,territories,segments,budget,capacityAllocation:Object.fromEntries(strategy.capacityRequirements.map(c=>[c.capacity,c.amount])),programOwnerRole:'revenue_manager',participatingRoles:['business_developer','account_manager','sales_operations','operations_manager'],campaignIds:[],kpiIds:[],approvalGateIds:[],risks:strategy.risks.map(r=>r.risk),stopConditionIds:[]}
  play.programIds=[program.id]
  const campaigns:CompiledCampaign[]=[];const deadlines:CompiledDeadline[]=[];const assignmentEligibility:AssignmentEligibility[]=[];const waves:CampaignWave[]=[];const accountPlans:AccountPlan[]=[];const missions:CompiledMission[]=[];const tasks:CompiledTask[]=[];const steps:ExecutionStep[]=[];const scripts:CompiledScript[]=[];const evidenceRequirements:EvidenceRequirement[]=[];const owners:CompiledOwner[]=[];const dependencies:CompilationDependency[]=[];const approvalGates:CompilationApprovalGate[]=[];const kpis:CompilationKpi[]=[];const retryRules:CompilationRetryRule[]=[];const rescueRoutes:CompilationRescueRoute[]=[];const stopConditions:CompilationStopCondition[]=[];const escalations:CompilationEscalation[]=[]
  const targetAccounts=objective.targetAccounts.slice(0,accountLimit(source.approvalConditions,200))
  segments.slice(0,3).forEach((segment,si)=>{
    const campaign:CompiledCampaign={...base(run,'campaign',`${program.id}:${segment}`),programId:program.id,purpose:`Activer le segment ${segment}`,commercialObjective:strategy.objective,targetSegments:[segment],targetAccountIds:targetAccounts,offer:strategy.offer,valueProposition:strategy.valueProposition,channelMix:strategy.channelMix.map(x=>x.channel),messageArchitecture:strategy.messageArchitecture,sequence:strategy.campaignSequence,startDate:plusDays(start,si*14),endDate:end,budget:budget?Math.floor(budget/Math.min(3,segments.length)):undefined,ownerRole:'campaign_manager',contributorRoles:['business_developer','account_manager'],capacityRequirementIds:[],approvalGateIds:[],kpiIds:[],successCondition:`Atteindre les seuils de progression approuvés pour ${segment}`,failureCondition:`Aucune progression qualifiée après les waves autorisées`,retryRuleIds:[],rescueRouteIds:[],stopConditionIds:[],waveIds:[]}
    campaigns.push(campaign);program.campaignIds.push(campaign.id)
    territories.forEach((territory,ti)=>{
      const waveNumber=ti+1;const waveAccounts=targetAccounts.filter((_,index)=>index%territories.length===ti);const wave:CampaignWave={...base(run,'wave',`${campaign.id}:${territory}`),campaignId:campaign.id,waveNumber,territory,segment,accountIds:waveAccounts,accountLimit:Math.max(1,waveAccounts.length||10),startWindow:plusDays(campaign.startDate,ti*10),endWindow:plusDays(campaign.startDate,ti*10+21),capacityReserved:{commercial_hours:Math.max(10,(waveAccounts.length||5)*3)},ownerRole:'business_developer',entryCriteria:['approval gates satisfied','capacity feasible','account cohort validated'],exitCriteria:['wave KPI met','failure threshold met','window expired'],progressionRule:'advance accounts with verified authority and positive engagement',holdRule:'hold when evidence, capacity or approval is incomplete',failureThreshold:0.5,rescueRouteIds:[],accountPlanIds:[]};waves.push(wave);campaign.waveIds.push(wave.id)
      const planSeeds=waveAccounts.length?waveAccounts:[undefined]
      planSeeds.forEach((accountId,ai)=>{
        const planKey=accountId||`${segment}:${territory}:segment-plan`;const plan:AccountPlan={...base(run,'account_plan',`${wave.id}:${planKey}`),waveId:wave.id,accountId,segment:accountId?undefined:segment,territory,commercialObjective:strategy.objective,accountThesis:accountId?`Appliquer la stratégie approuvée au compte gouverné ${accountId}.`:`Appliquer la stratégie au cohort ${segment} — ${territory} sans inventer de compte.`,currentRelationship:'à confirmer depuis la source de vérité compte',decisionMakers:[],stakeholderMap:{economic_buyer:'à identifier',operational_buyer:'à identifier'},businessProblem:strategy.businessProblem,recommendedOffer:strategy.offer,valueProposition:strategy.valueProposition,contactStrategy:strategy.channelMix.map(x=>`${x.sequence}. ${x.channel}: ${x.purpose}`),meetingStrategy:strategy.meetingStrategy,proposalStrategy:strategy.proposalStrategy,pricingPosture:strategy.pricingPosture,objectionRisks:strategy.risks.map(r=>r.risk).slice(0,5),nextBestActions:['verify account truth','map decision makers','prepare approved contact drafts'],missionIds:[],evidenceRequirementIds:[],successCondition:'Compte ou cohort qualifié avec prochaine décision explicite',failureCondition:'Compte non qualifiable, refus explicite ou absence de capacité',rescueRouteIds:[]};accountPlans.push(plan);wave.accountPlanIds.push(plan.id)
        let previousMissionLastTask:string|undefined
        missionTemplates.forEach((mt,mi)=>{
          const mission:CompiledMission={...base(run,'mission',`${plan.id}:${mt.code}`),accountPlanId:plan.id,programId:program.id,campaignId:campaign.id,waveId:wave.id,title:mt.title,purpose:mt.purpose,businessImpact:`Contribue à ${strategy.objective}`,accountId,segment:accountId?undefined:segment,ownerRole:mt.role,eligibleRoles:[mt.role,'sales_operations'],assignmentStatus:'proposed',priority:mi===0?'high':'normal',startDate:plusDays(wave.startWindow,mi*4),deadline:plusDays(wave.startWindow,mi*4+5),taskIds:[],dependencyIds:[],requiredTools:mt.tasks.map(t=>t.tool),approvedScriptIds:[],approvalGateIds:[],evidenceRequirementIds:[],kpiIds:[],successCondition:`Mission ${mt.code} complétée avec preuves`,failureCondition:`Échec critique ou dépendance non satisfaite`,retryRuleIds:[],rescueRouteIds:[],escalationIds:[],stopConditionIds:[],nextAction:mi<missionTemplates.length-1?missionTemplates[mi+1].title:'Préparer la propagation MZ14'};missions.push(mission);plan.missionIds.push(mission.id)
          const owner=resolveOwner(run,{objectId:mission.id,level:'mission',territory,requiredRole:mt.role,workloadMinutes:mt.tasks.reduce((a,t)=>a+t.effort,0)},candidates);owners.push(owner);mission.ownerId=owner.ownerId;mission.ownerRole=owner.ownerRole;mission.assignmentStatus=owner.status
          let previousTaskId=previousMissionLastTask
          mt.tasks.forEach((tt,tix)=>{
            const task:CompiledTask={...base(run,'task',`${mission.id}:${tix}`),missionId:mission.id,title:tt.title,purpose:tt.purpose,businessImpact:mission.businessImpact,accountId,segment:accountId?undefined:segment,territory,ownerId:owner.ownerId,ownerRole:owner.ownerRole,eligibleRoles:owner.eligibleRoles,priority:mission.priority,taskStatus:'draft',startAt:plusDays(mission.startDate,tix*2),dueAt:plusDays(mission.startDate,tix*2+2),estimatedEffortMinutes:tt.effort,stepIds:[],allowedTools:[tt.tool],forbiddenTools:['send_email','send_whatsapp','place_call','commit_price','apply_discount','sign_contract','release_payment'],dependencyIds:[],approvalGateIds:[],evidenceRequirementIds:[],successCondition:`Sortie ${tt.tool} validée et enregistrée`,failureCondition:`Sortie absente, invalide ou non prouvée`,retryRuleIds:[],rescueRouteIds:[],escalationIds:[],nextAction:tix<mt.tasks.length-1?mt.tasks[tix+1].title:mission.nextAction,completionOutputSchema:{type:'object',required:['status','evidenceIds','nextAction'],properties:{status:{type:'string'},evidenceIds:{type:'array',items:{type:'string'}},nextAction:{type:'string'}}}};tasks.push(task);mission.taskIds.push(task.id)
            const sc=script(run,task.id,mt.code,tt.tool.includes('phone')?'phone':'internal_draft',accountId?'account_decision_maker':segment,strategy);scripts.push(sc);task.scriptId=sc.id;mission.approvedScriptIds.push(sc.id)
            const ev=evidence(run,'task',task.id,'completion',`Preuve de réalisation — ${tt.title}`);evidenceRequirements.push(ev);task.evidenceRequirementIds.push(ev.id);mission.evidenceRequirementIds.push(ev.id);plan.evidenceRequirementIds.push(ev.id)
            const rr=retry(run,'task',task.id);retryRules.push(rr);task.retryRuleIds.push(rr.id);mission.retryRuleIds.push(rr.id)
            const rs=rescue(run,'task',task.id);rescueRoutes.push(rs);task.rescueRouteIds.push(rs.id);mission.rescueRouteIds.push(rs.id);wave.rescueRouteIds.push(rs.id);plan.rescueRouteIds.push(rs.id)
            const es=escalation(run,'task',task.id,'revenue_manager');escalations.push(es);task.escalationIds.push(es.id);mission.escalationIds.push(es.id)
            const st=stop(run,'task',task.id,'Stopper après refus explicite ou expiration approval','task_stop',true);stopConditions.push(st);task.approvalGateIds.push(...source.approvalConditions.map(c=>{const g=gate(run,'task',task.id,c.type,source.approval.approvalClass,c.id,c.status==='satisfied'||c.status==='waived'?'satisfied':'blocked');approvalGates.push(g);return g.id}));mission.stopConditionIds.push(st.id)
            for(let sx=0;sx<3;sx++){const step:ExecutionStep={...base(run,'step',`${task.id}:${sx+1}`),taskId:task.id,stepNumber:sx+1,instruction:[`Vérifier le contexte et les dépendances de « ${task.title} »`,`Exécuter la préparation interne avec l’outil autorisé ${tt.tool}`,'Enregistrer la sortie, les preuves et la prochaine action'][sx],purpose:task.purpose,tool:sx===0?'context_read':sx===1?tt.tool:'evidence_record',input:{strategyVersion:run.strategyVersion,accountId,segment,territory},expectedOutput:sx===2?task.completionOutputSchema:{type:'object'},evidenceRequirementIds:sx===2?[ev.id]:[],successCondition:'Étape terminée sans action externe',failureCondition:'Contexte, outil ou preuve invalide',fallback:'pause_and_escalate'};steps.push(step);task.stepIds.push(step.id)}
            if(previousTaskId){const dep:CompilationDependency={...base(run,'dependency',`${previousTaskId}:${task.id}`),fromObjectId:previousTaskId,toObjectId:task.id,fromLevel:'task',toLevel:'task',kind:'finish_to_start',required:true};dependencies.push(dep);task.dependencyIds.push(dep.id);mission.dependencyIds.push(dep.id)}
            previousTaskId=task.id;previousMissionLastTask=task.id
          })
          const mk=kpi(run,'mission',mission.id,`Achèvement — ${mission.title}`,'mission_completion_rate',1,'ratio');kpis.push(mk);mission.kpiIds.push(mk.id)
        })
      })
      const wk=kpi(run,'wave',wave.id,`Progression wave ${waveNumber}`,'qualified_accounts',Math.max(1,Math.ceil(wave.accountLimit*.25)),'accounts');kpis.push(wk)
    })
    const ck=kpi(run,'campaign',campaign.id,`Réunions qualifiées — ${segment}`,'qualified_meetings',Math.max(1,Math.ceil((targetAccounts.length||20)*.1)),'meetings');kpis.push(ck);campaign.kpiIds.push(ck.id)
    const cRetry=retry(run,'campaign',campaign.id);retryRules.push(cRetry);campaign.retryRuleIds.push(cRetry.id);const cRescue=rescue(run,'campaign',campaign.id,'commercial_director');rescueRoutes.push(cRescue);campaign.rescueRouteIds.push(cRescue.id);const cStop=stop(run,'campaign',campaign.id,'Stopper si budget, marge ou capacité dépasse le cadre approuvé','campaign_guard',true,'revalidate');stopConditions.push(cStop);campaign.stopConditionIds.push(cStop.id)
  })
  const pk=kpi(run,'program',program.id,'Pipeline qualifié du programme','qualified_pipeline',objective.revenueTarget||100000,'Dh');kpis.push(pk);program.kpiIds.push(pk.id)
  const pStop=stop(run,'program',program.id,'Stopper en cas d’expiration approval ou contradiction majeure','program_guard',true,'revalidate');stopConditions.push(pStop);program.stopConditionIds.push(pStop.id)
  const programOwner=resolveOwner(run,{objectId:program.id,level:'program',requiredRole:'revenue_manager',workloadMinutes:240},candidates);owners.push(programOwner)
  for(const c of source.approvalConditions){const g=gate(run,'program',program.id,c.type,source.approval.approvalClass,c.id,c.status==='satisfied'||c.status==='waived'?'satisfied':'blocked');approvalGates.push(g);program.approvalGateIds.push(g.id)}
  const capacityObjects=[{id:program.id,level:'program' as const,code:program.code},...campaigns.map(x=>({id:x.id,level:'campaign' as const,code:x.code})),...waves.map(x=>({id:x.id,level:'wave' as const,code:x.code})),...missions.map(x=>({id:x.id,level:'mission' as const,code:x.code}))]
  const deadlineRows:Array<{level:CompilationLevel;objectId:string;type:CompiledDeadline['deadlineType'];at:string;hard:boolean}>=[{level:'program',objectId:program.id,type:'start',at:program.startDate,hard:true},{level:'program',objectId:program.id,type:'due',at:program.endDate,hard:true},...campaigns.flatMap(x=>[{level:'campaign' as const,objectId:x.id,type:'start' as const,at:x.startDate,hard:true},{level:'campaign' as const,objectId:x.id,type:'due' as const,at:x.endDate,hard:true}]),...waves.flatMap(x=>[{level:'wave' as const,objectId:x.id,type:'window_start' as const,at:x.startWindow,hard:true},{level:'wave' as const,objectId:x.id,type:'window_end' as const,at:x.endWindow,hard:true}]),...missions.flatMap(x=>[{level:'mission' as const,objectId:x.id,type:'start' as const,at:x.startDate,hard:true},{level:'mission' as const,objectId:x.id,type:'due' as const,at:x.deadline,hard:true}]),...tasks.flatMap(x=>[{level:'task' as const,objectId:x.id,type:'start' as const,at:x.startAt,hard:true},{level:'task' as const,objectId:x.id,type:'due' as const,at:x.dueAt,hard:true}])];for(const d of deadlineRows)deadlines.push({...base(run,'deadline',`${d.objectId}:${d.type}`),level:d.level,objectId:d.objectId,deadlineType:d.type,at:d.at,timezone:'Africa/Casablanca',hard:d.hard})
  for(const owner of owners){for(const role of owner.eligibleRoles)assignmentEligibility.push({...base(run,'eligibility',`${owner.objectId}:${role}`),level:owner.level,objectId:owner.objectId,candidateRole:role,criteria:{territory:owner.territory,requiredAuthority:owner.requiredAuthority,workloadMinutes:owner.workloadEstimateMinutes},eligible:owner.status!=='authority_conflict'&&owner.status!=='territory_conflict',reasons:owner.reason})}
  const capacityRequirements=buildCapacityRequirements(run,strategy,capacityObjects)
  for(const c of campaigns)c.capacityRequirementIds=capacityRequirements.filter(x=>x.objectId===c.id).map(x=>x.id)
  const graph=validateDependencyGraph(tasks.map(x=>x.id),dependencies,tasks.filter(t=>!dependencies.some(d=>d.toObjectId===t.id)).map(t=>t.id));if(!graph.valid){for(const cycle of graph.cycles){dependencies.push({...base(run,'dependency',`invalid:${cycle.join(':')}`),fromObjectId:cycle[0],toObjectId:cycle[cycle.length-1],fromLevel:'task',toLevel:'task',kind:'finish_to_start',required:true,condition:'INVALID_CYCLE_MARKER'})}}
  const partial={id:stableUuid(run.id,'blueprint'),run,source,revenuePlays:[play],programs:[program],campaigns,waves,accountPlans,missions,tasks,steps,scripts,evidenceRequirements,deadlines,capacityRequirements,assignmentEligibility,owners,dependencies,approvalGates,kpis,retryRules,rescueRoutes,stopConditions,escalations} as Omit<CompilationBlueprint,'conflicts'|'outputHash'|'readyForMZ14'|'externalActions'>
  const conflicts=detectConflicts(partial);const outputHash=hashObject({plays:[play],programs:[program],campaigns,waves,accountPlans,missions,tasks,steps,scripts,evidenceRequirements,deadlines,capacityRequirements,assignmentEligibility,owners,dependencies,approvalGates,kpis,retryRules,rescueRoutes,stopConditions,escalations});const readyForMZ14=!conflicts.some(x=>x.blocking)&&graph.valid&&approvalGates.every(x=>x.status!=='blocked')
  run.status=readyForMZ14?'ready_for_mz14':conflicts.some(x=>x.blocking)?'conflict_detected':'compiled';run.outputHash=outputHash;run.completedAt=now()
  return{...partial,conflicts,outputHash,readyForMZ14,externalActions:0}
}
