import { createHash } from 'node:crypto'
import { HOMEPAGE_PRO_MAX_SECTION_DEFINITIONS,HOMEPAGE_PRO_MAX_WORLD_01 } from './recipe'
export const HOMEPAGE_PRO_MAX_DEVELOPER_CONTRACT={schemaVersion:'2026-09-20.HOMEPAGE-PRO-MAX.01',category:{ordinal:11,id:'homepage_pro_max',label:'HOMEPAGE PRO MAX'},worlds:[{id:HOMEPAGE_PRO_MAX_WORLD_01.id,revision:HOMEPAGE_PRO_MAX_WORLD_01.revision,sectionCount:HOMEPAGE_PRO_MAX_SECTION_DEFINITIONS.length,referenceSha256:HOMEPAGE_PRO_MAX_WORLD_01.referenceSha256,insertion:['REPLACE_PAGE','INSERT_COMPOSITION']}],authoring:{fullPageRecipe:true,rootSectionsEditable:true,undoRestoresPreviousPage:true,previewBeforeReplace:true},brand:{logo:'/brand/angelcare-official-user-transparent.png',officialOnly:true,aiLogoForbidden:true},commerce:{currency:'MAD/Dhs',fakePrice:false,fakeRating:false,fakeStock:false,fakeUrgency:false,fakePartner:false},runtime:{experienceCore:true,p03Actions:true,p05Bindings:true,p06DynamicSources:true,p07Workflows:true,p08PublicRuntime:true,p11FailClosed:true,p12Invalidation:true,p13StableIds:true},boundaries:{legacyVisualCategoriesPreserved:10,noShadowStore:true,noSql:true,noMigration:true,localBuild:false,globalTypescript:false}} as const
const raw=JSON.stringify(HOMEPAGE_PRO_MAX_DEVELOPER_CONTRACT)
export const HOMEPAGE_PRO_MAX_DEVELOPER_CONTRACT_SHA256=createHash('sha256').update(raw).digest('hex')

export function homepageProMaxDeveloperContractJson(){return {...HOMEPAGE_PRO_MAX_DEVELOPER_CONTRACT,hash:HOMEPAGE_PRO_MAX_DEVELOPER_CONTRACT_SHA256}}
export function homepageProMaxDeveloperContractTxt(){const c=homepageProMaxDeveloperContractJson();return `ANGELCARE MARKETPLACE STUDIO — HOMEPAGE PRO MAX\nSchema: ${c.schemaVersion}\nCategory: 11 · HOMEPAGE PRO MAX\nWorlds: ${c.worlds.length}\nSections: ${c.worlds[0].sectionCount}\nReference SHA256: ${c.worlds[0].referenceSha256}\nCurrency: MAD/Dhs\nFake commercial data: FORBIDDEN\nHash: ${c.hash}\n`}
export function homepageProMaxDeveloperContractCsv(){const c=homepageProMaxDeveloperContractJson();return `key,value\nschemaVersion,${c.schemaVersion}\ncategory,11 HOMEPAGE PRO MAX\nworldId,${c.worlds[0].id}\nsections,${c.worlds[0].sectionCount}\nreferenceSha256,${c.worlds[0].referenceSha256}\ncurrency,MAD/Dhs\n`}
