'use client'
import {useMemo,useState} from 'react'
import {useRouter} from 'next/navigation'
import type {LiveGovernanceMode} from '../repository'
import styles from '../live-governance.module.css'
type Row=Record<string,unknown>
const text=(v:unknown)=>typeof v==='string'?v:String(v??'')
async function send(mode:LiveGovernanceMode,method:'POST'|'PATCH',body:Row){const r=await fetch(`/api/angelcare-marketplace/admin/live-experience/${mode}`,{method,headers:{'content-type':'application/json'},body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error?.message||'Commande refusée');return j.data}
const COPY:Record<LiveGovernanceMode,[string,string,string]>={audiences:['AUDIENCE AUTHORITY','Cibler sans opacité','Segments, exclusions, territoires et règles client restent persistants et auditables.'],placements:['PLACEMENT AUTHORITY','Décider où chaque expérience peut vivre','Surface, famille et configuration sont contrôlées avant activation.'],schedules:['SCHEDULE AUTHORITY','Planifier sans collisions silencieuses','Fenêtres, timezone, recurrence et chevauchements sont validés côté serveur.'],experiments:['EXPERIMENT AUTHORITY','Tester, mesurer, décider','Deux variantes minimum, groupe contrôle, lifecycle et evidence du gagnant.'],history:['IMMUTABLE HISTORY','Voir ce qui a réellement changé','Versions et événements d’audit restent lisibles sans mutation.'],settings:['CAPABILITY GOVERNANCE','Contrôler les capacités autorisées','Activer ou retirer les patterns Live Experience sans modifier le code métier.']}
const NEXT:Record<string,string[]|undefined>={draft:['review','ready','scheduled'],review:['active','draft'],ready:['running'],scheduled:['active','paused'],active:['paused','completed'],paused:['active','completed'],running:['paused','significance_review'],significance_review:['winner','running'],winner:['closed'],completed:['archived'],inactive:['active']}
export function LiveGovernanceCommand({mode,rows}:{mode:LiveGovernanceMode;rows:Row[]}){const router=useRouter(),copy=COPY[mode],[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[key,setKey]=useState(''),[name,setName]=useState(''),[family,setFamily]=useState('popup'),[campaignId,setCampaignId]=useState(''),[json,setJson]=useState('{}');const active=useMemo(()=>rows.filter(r=>['active','running','scheduled','ready'].includes(text(r.status))).length,[rows]);async function run(method:'POST'|'PATCH',body:Row){setBusy(true);setMessage('');try{await send(mode,method,body);setMessage('Commande appliquée et auditée.');router.refresh()}catch(e){setMessage(e instanceof Error?e.message:'Échec')}finally{setBusy(false)}}function parsed(){try{return JSON.parse(json) as Row}catch{return{}}}
 return <main className={styles.shell}><section className={styles.hero}><div><span>{copy[0]}</span><h1>{copy[1]}</h1><p>{copy[2]}</p></div><aside><b>{rows.length}</b><small>objets gouvernés</small><strong>{active}</strong><small>actifs / programmés</small></aside></section>{mode!=='history'?<section className={styles.editor}><h2>Créer une autorité {mode}</h2><div className={styles.form}><input value={key} onChange={e=>setKey(e.target.value)} placeholder="Clé stable"/><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nom / label"/>{mode==='placements'?<input value={family} onChange={e=>setFamily(e.target.value)} placeholder="Famille"/>:null}{mode==='schedules'?<input value={campaignId} onChange={e=>setCampaignId(e.target.value)} placeholder="Campaign UUID"/>:null}<textarea value={json} onChange={e=>setJson(e.target.value)} placeholder="Configuration JSON"/><button disabled={busy} onClick={()=>{const data=parsed();const body:Row=mode==='audiences'?{audience_key:key,name,definition:data,status:'draft'}:mode==='placements'?{placement_key:key,label:name,family,configuration:data,status:'draft'}:mode==='schedules'?{schedule_key:key,campaign_id:campaignId,recurrence:data,status:'scheduled'}:mode==='experiments'?{experiment_key:key,name,variants:Array.isArray(data.variants)?data.variants:[{key:'control',weight:50},{key:'variant_b',weight:50}],allocation:data.allocation||{},status:'draft'}:{capability_key:key,kind:family,description:name,status:'active'};void run('POST',body)}}>Créer</button></div></section>:null}{message?<div className={styles.message}>{message}</div>:null}<section className={styles.table}><header><strong>Registre réel</strong><span>Statut</span><span>Commandes</span></header>{rows.map((row,i)=>{const id=text(row.id||i),label=text(row.name||row.label||row.audience_key||row.placement_key||row.schedule_key||row.experiment_key||row.capability_key||row.action||id),status=text(row.status||row.record_type||'recorded'),next=NEXT[status]||[];return <article key={`${id}-${i}`}><div><strong>{label}</strong><small>{text(row.object_type||row.family||row.kind||row.objective||row.created_at||row.updated_at)}</small></div><span>{status}</span><div className={styles.actions}>{mode!=='history'?next.slice(0,3).map(n=><button key={n} disabled={busy} onClick={()=>void run('PATCH',{action:'transition',id,nextStatus:n,reason:`Transition ${status} → ${n} depuis MZ2`})}>{n}</button>):<small>{text(row.created_at)}</small>}</div></article>})}{!rows.length?<div className={styles.empty}>Aucun objet persisté. Aucun exemple n’est injecté.</div>:null}</section></main>}
