import { createServiceClient } from '@/lib/supabase/server'
import { writeMarketplaceAudit } from '../audit/write-audit'
import type { MarketplaceRequestContext } from '../domain/types'
import { MarketplaceError } from '../server/errors'
import { assertDevelopmentTransition } from './validation'
import type { DevelopmentActivity,DevelopmentCategory,DevelopmentKit,DevelopmentStatus,DevelopmentSummary,SupplierSpec } from './types'
function fail(op:string,error:{code?:string;message?:string}|null){const missing=error?.code==='42P01'||String(error?.message||'').includes('angelcare_marketplace_development_');return new MarketplaceError(missing?'CONFIGURATION_ERROR':'INTERNAL_ERROR',missing?'La migration Développement enfant doit être appliquée.':`Impossible de ${op}.` )}
export async function developmentSummary():Promise<DevelopmentSummary>{const db=await createServiceClient();const [categories,activities,kits,specs,review,gaps]=await Promise.all([db.from('angelcare_marketplace_development_categories').select('id',{count:'exact',head:true}).neq('status','archived'),db.from('angelcare_marketplace_development_activities').select('id',{count:'exact',head:true}).eq('status','published'),db.from('angelcare_marketplace_development_kits').select('id',{count:'exact',head:true}).neq('status','archived'),db.from('angelcare_marketplace_development_supplier_specs').select('id',{count:'exact',head:true}).neq('status','archived'),db.from('angelcare_marketplace_development_activities').select('id',{count:'exact',head:true}).eq('status','review'),db.from('angelcare_marketplace_development_categories').select('id',{count:'exact',head:true}).or('age_min_months.is.null,age_max_months.is.null')]);return {categories:categories.count||0,publishedActivities:activities.count||0,kits:kits.count||0,supplierSpecs:specs.count||0,reviewQueue:review.count||0,ageCoverageGaps:gaps.count||0}}
export async function listDevelopmentCategories():Promise<DevelopmentCategory[]>{const db=await createServiceClient();const {data,error}=await db.from('angelcare_marketplace_development_categories').select('*').neq('status','archived').order('sort_order');if(error)throw fail('charger les catégories',error);return (data||[]) as DevelopmentCategory[]}
export async function listDevelopmentActivities(filters?:{status?:string;categoryId?:string}):Promise<DevelopmentActivity[]>{const db=await createServiceClient();let q=db.from('angelcare_marketplace_development_activities').select('*').neq('status','archived').order('updated_at',{ascending:false}).limit(400);if(filters?.status)q=q.eq('status',filters.status);if(filters?.categoryId)q=q.eq('category_id',filters.categoryId);const {data,error}=await q;if(error)throw fail('charger les activités',error);return (data||[]) as DevelopmentActivity[]}
export async function createDevelopmentActivity(input:{payload:Record<string,unknown>;context:MarketplaceRequestContext;requestId:string;request?:Request}):Promise<DevelopmentActivity>{const db=await createServiceClient();const row={...input.payload,source_locale:'fr',status:'draft',owner_id:input.context.actor.id,territory_id:input.context.territoryId,created_by:input.context.actor.id,updated_by:input.context.actor.id};const {data,error}=await db.from('angelcare_marketplace_development_activities').insert(row).select('*').single();if(error||!data)throw fail('créer l’activité',error);await writeMarketplaceAudit({context:input.context,requestId:input.requestId,action:'marketplace.development.activity_created',objectType:'development_activity',objectId:String(data.id),afterValue:data,source:'ultra-delivery-02-mz08',request:input.request});return data as DevelopmentActivity}
export async function transitionDevelopmentActivity(input:{id:string;target:DevelopmentStatus;reason:string;context:MarketplaceRequestContext;requestId:string;request?:Request}):Promise<DevelopmentActivity>{const db=await createServiceClient();const {data:before,error:loadError}=await db.from('angelcare_marketplace_development_activities').select('*').eq('id',input.id).single();if(loadError||!before)throw fail('charger l’activité',loadError);assertDevelopmentTransition(before.status as DevelopmentStatus,input.target);const {data,error}=await db.from('angelcare_marketplace_development_activities').update({status:input.target,updated_by:input.context.actor.id,updated_at:new Date().toISOString()}).eq('id',input.id).select('*').single();if(error||!data)throw fail('changer le statut',error);await writeMarketplaceAudit({context:input.context,requestId:input.requestId,action:`marketplace.development.activity_${input.target}`,objectType:'development_activity',objectId:input.id,beforeValue:before,afterValue:data,reason:input.reason,severity:input.target==='published'?'warning':'info',source:'ultra-delivery-02-mz08',request:input.request});return data as DevelopmentActivity}
export async function listDevelopmentKits():Promise<DevelopmentKit[]>{const db=await createServiceClient();const {data,error}=await db.from('angelcare_marketplace_development_kits').select('*,items:angelcare_marketplace_development_kit_items(id)').neq('status','archived').order('updated_at',{ascending:false});if(error)throw fail('charger les kits',error);return (data||[]).map((row:Record<string,unknown>)=>({...row,item_count:Array.isArray(row.items)?row.items.length:0})) as DevelopmentKit[]}
export async function listSupplierSpecs():Promise<SupplierSpec[]>{const db=await createServiceClient();const {data,error}=await db.from('angelcare_marketplace_development_supplier_specs').select('*').neq('status','archived').order('updated_at',{ascending:false});if(error)throw fail('charger les spécifications',error);return (data||[]) as SupplierSpec[]}
