export type ProductionSourceMode = 'database' | 'controlled_bootstrap'
export type CommandOutputType = 'print_pdf' | 'digital_pdf' | 'mp4' | 'classroom' | 'parent_guide' | 'teacher_guide' | 'promotional_preview' | 'editable_source'
export type CommandStatus = 'draft' | 'compiling' | 'compiled' | 'validation_required' | 'human_review' | 'corrections_required' | 'approved' | 'copied' | 'externally_submitted' | 'production_active' | 'returned' | 'closed' | 'superseded'
export type ExternalJobStatus = 'prepared' | 'command_approved' | 'submitted' | 'accepted_by_producer' | 'in_production' | 'questions_received' | 'correction_requested' | 'awaiting_return' | 'files_returned' | 'under_review' | 'accepted' | 'rejected' | 'closed'
export type UploadStatus = 'initiated' | 'uploading' | 'paused' | 'finalising' | 'completed' | 'cancelled' | 'expired' | 'failed' | 'quarantined'
export type StorageClassification = 'working_source' | 'returned_editable_source' | 'final_print_pdf' | 'final_digital_pdf' | 'final_mp4' | 'digital_classroom_package' | 'parent_guide' | 'teacher_guide' | 'cover' | 'thumbnail' | 'promotional_preview' | 'supporting_asset' | 'font_manifest' | 'linked_asset_manifest' | 'production_notes' | 'superseded_release' | 'archived_release' | 'quarantined_file'
export type ReviewDiscipline = 'integrity' | 'manifest' | 'content' | 'pedagogy' | 'language' | 'brand' | 'technical' | 'source_package' | 'rights' | 'release'
export type FindingSeverity = 'observation' | 'minor' | 'major' | 'release_blocker' | 'critical'
export type ReleaseStatus = 'draft' | 'assembly' | 'validation' | 'approval_requested' | 'approved' | 'released' | 'commercially_active' | 'superseded' | 'retired' | 'archived'

export type CommandSection = { id: string; key: string; title: string; order: number; content: string; locked: boolean; validationStatus: 'pending' | 'valid' | 'warning' | 'blocking'; findings: string[] }
export type ProductionCommand = {
  id: string; code: string; collectionId: string; collectionCode: string; collectionName: string; designId: string; designCode: string; designVersion: number; outputType: CommandOutputType; edition: string; variant: string; externalProfile: string; status: CommandStatus; version: number; title: string; mission: string; sections: CommandSection[]; deterministicFindings: string[]; advisoryFindings: string[]; approvalNote: string | null; approvedBy: string | null; approvedAt: string | null; copiedAt: string | null; createdAt: string | null; updatedAt: string | null
}
export type ExternalProductionJob = { id: string; code: string; commandId: string; collectionName: string; outputType: CommandOutputType; producer: string; externalEnvironment: string; externalReference: string | null; status: ExternalJobStatus; targetDeliveryDate: string | null; estimatedCost: number; actualCost: number; correctionCycles: number; blocker: string | null; returnedFileCount: number; createdAt: string | null; updatedAt: string | null }
export type StorageNode = { id: string; nodeKey: string; label: string; status: 'online' | 'degraded' | 'offline' | 'unconfigured'; lastHeartbeatAt: string | null; totalBytes: number; usedBytes: number; freeBytes: number; activeTransfers: number; failedTransfers: number; quarantineCount: number; rootAlias: string; version: string | null }
export type UploadSession = { id: string; code: string; collectionId: string; fileName: string; classification: StorageClassification; mimeType: string; totalBytes: number; chunkSize: number; uploadedBytes: number; uploadedParts: number; totalParts: number; status: UploadStatus; checksumExpected: string | null; checksumActual: string | null; storageNodeId: string | null; createdAt: string | null; expiresAt: string | null; errorMessage: string | null }
export type StorageObject = { id: string; code: string; collectionId: string; collectionName: string; version: number; classification: StorageClassification; fileName: string; mimeType: string; sizeBytes: number; checksumSha256: string; status: 'working' | 'review' | 'approved' | 'quarantined' | 'superseded' | 'archived'; sourcePackageId: string | null; deliverableId: string | null; nodeKey: string; rootAlias: string; createdAt: string | null }
export type SourcePackage = { id: string; code: string; collectionId: string; collectionName: string; commandId: string; externalJobId: string; version: number; producer: string; environment: string; storageObjectIds: string[]; manifestComplete: boolean; reviewStatus: 'pending' | 'review' | 'approved' | 'rejected'; createdAt: string | null }
export type Deliverable = { id: string; code: string; collectionId: string; collectionName: string; commandId: string; externalJobId: string; sourcePackageId: string | null; outputType: CommandOutputType; version: number; storageObjectIds: string[]; reviewStatus: 'pending' | 'review' | 'approved' | 'rejected'; releaseId: string | null; supersededById: string | null; receivedAt: string | null }
export type QualityFinding = { id: string; reviewId: string; discipline: ReviewDiscipline; severity: FindingSeverity; title: string; detail: string; locator: string | null; expectedCorrection: string; responsibleParty: string; dueDate: string | null; status: 'open' | 'acknowledged' | 'resolved' | 'waived'; resolution: string | null }
export type QualityReview = { id: string; code: string; deliverableId: string; deliverableName: string; status: 'draft' | 'active' | 'correction_required' | 'approved' | 'rejected' | 'closed'; disciplines: Array<{ discipline: ReviewDiscipline; status: 'pending' | 'passed' | 'failed' | 'waived'; reviewer: string | null }>; findings: QualityFinding[]; blockers: number; createdAt: string | null; updatedAt: string | null }
export type ProductRelease = { id: string; code: string; collectionId: string; collectionName: string; collectionVersion: number; designId: string; commandId: string; sourcePackageId: string; deliverableIds: string[]; status: ReleaseStatus; version: number; blockingReasons: string[]; approvedBy: string | null; approvedAt: string | null; releasedAt: string | null; supersedesReleaseId: string | null; createdAt: string | null }
export type ProductionOverview = { sourceMode: ProductionSourceMode; commands: ProductionCommand[]; jobs: ExternalProductionJob[]; uploads: UploadSession[]; storageObjects: StorageObject[]; sourcePackages: SourcePackage[]; deliverables: Deliverable[]; reviews: QualityReview[]; releases: ProductRelease[]; nodes: StorageNode[]; metrics: { approvedDesignsReady: number; commandsAwaitingReview: number; activeExternalJobs: number; transfersInProgress: number; openBlockers: number; releasesEligible: number; nodeHealth: string } }
export type ActorContext = { id: string; name: string; role: string }
export type CreateCommandInput = { designId: string; outputType: CommandOutputType; edition: string; variant: string; externalProfile: string; title?: string }
export type CreateExternalJobInput = { commandId: string; producer: string; externalEnvironment: string; targetDeliveryDate?: string; estimatedCost?: number }
export type CreateUploadInput = { collectionId: string; fileName: string; classification: StorageClassification; mimeType: string; totalBytes: number; checksumExpected?: string; commandId?: string; externalJobId?: string }
