import 'server-only'
import type { MarketplaceRequestContext } from '@/angelcare-marketplace/domain/types'
import type { StudioSourceReference } from '@/angelcare-marketplace/studio-source-registry/types'
import { writeMarketplaceAudit } from '@/angelcare-marketplace/audit/write-audit'
import { revalidateStudioPaths,revalidateStudioTags } from './cache'
import { resolveStudioDependencyImpact } from './repository'
import { STUDIO_ASSIGNMENT_CACHE_TAG,studioCacheTag,studioPageTag,studioSourceEntityTag,studioSourceFamilyTag,studioTemplateRevisionTag,studioTemplateTag } from './registry'
import type { StudioDependencyInvalidationResult } from './types'

const itemPaths=(locale:string,slug:string)=>[`/angelcare-marketplace/${locale}/experience/${slug}`,`/angelcare-marketplace/${locale}/marketplace/${slug}`,`/angelcare-marketplace/${locale}/marketplace/item/${slug}`]
export async function invalidateStudioReference(input:{reference:StudioSourceReference;reason:string;context?:MarketplaceRequestContext;requestId?:string;slug?:string|null;locale?:string|null;extraTags?:string[];extraPaths?:string[]}):Promise<StudioDependencyInvalidationResult>{const impact=await resolveStudioDependencyImpact(input.reference),tags=[...impact.cacheTags,...(input.extraTags||[])],paths=[...impact.affectedPages.map(p=>p.path),...(input.extraPaths||[])];if(input.reference.sourceId==='catalog.items'&&input.slug)paths.push(...itemPaths(input.locale&&['fr','en','ar'].includes(input.locale)?input.locale:'fr',input.slug));revalidateStudioTags(tags);revalidateStudioPaths(paths);if(input.context&&input.requestId)await writeMarketplaceAudit({context:input.context,requestId:input.requestId,action:'marketplace.studio.p12.invalidated',objectType:'studio_dependency',objectId:`${input.reference.sourceId}:${input.reference.entityId}`,result:'success',severity:'info',reason:input.reason,source:'studio-p12-dependency-invalidation',afterValue:{tagCount:new Set(tags).size,pathCount:new Set(paths).size,affectedPages:impact.affectedPages.length}});return{tags:[...new Set(tags)],paths:[...new Set(paths)],affectedPages:impact.affectedPages.length,reason:input.reason}}
export async function invalidateStudioPage(input:{pageId:string;locale:string;slug:string;reason:string;context?:MarketplaceRequestContext;requestId?:string}){revalidateStudioTags([studioPageTag(input.pageId)]);revalidateStudioPaths([`/angelcare-marketplace/${input.locale}/${input.slug}`]);if(input.context&&input.requestId)await writeMarketplaceAudit({context:input.context,requestId:input.requestId,action:'marketplace.studio.p12.page_invalidated',objectType:'cms_page',objectId:input.pageId,result:'success',severity:'info',reason:input.reason,source:'studio-p12-dependency-invalidation'})}
export async function invalidateStudioTemplate(input:{templateId:string;revisionId?:string|null;reason:string;context?:MarketplaceRequestContext;requestId?:string}){return invalidateStudioReference({reference:{sourceId:'content.templates',entityId:input.templateId},reason:input.reason,context:input.context,requestId:input.requestId,extraTags:[studioTemplateTag(input.templateId),...(input.revisionId?[studioTemplateRevisionTag(input.revisionId)]:[]),STUDIO_ASSIGNMENT_CACHE_TAG]})}
export async function invalidateStudioAssignment(input:{scope:string;target?:StudioSourceReference|null;templateId?:string|null;reason:string;context?:MarketplaceRequestContext;requestId?:string}){const tags=[STUDIO_ASSIGNMENT_CACHE_TAG,studioCacheTag('assignment-scope',input.scope)];if(input.templateId)tags.push(studioTemplateTag(input.templateId));if(input.target)tags.push(studioSourceFamilyTag(input.target.sourceId),studioSourceEntityTag(input.target));revalidateStudioTags(tags);if(input.target)return invalidateStudioReference({reference:input.target,reason:input.reason,context:input.context,requestId:input.requestId,extraTags:tags});return{tags,paths:[],affectedPages:0,reason:input.reason}}

const RESOURCE_SOURCE:Record<string,string|null>={media:'media.assets','homepage-campaigns':'homepage.campaigns','homepage-collections':'homepage.collections','homepage-placements':'homepage.placements','catalog-items':'catalog.items','catalog-categories':'catalog.categories'}
export async function invalidateStudioCommerceMutation(input:{resource:string;id:string;slug?:string|null;locale?:string|null;reason:string;context?:MarketplaceRequestContext;requestId?:string}){const sourceId=RESOURCE_SOURCE[input.resource];if(!sourceId){revalidateStudioTags([studioCacheTag('commerce',input.resource)]);return}await invalidateStudioReference({reference:{sourceId,entityId:input.id},slug:input.slug,locale:input.locale,reason:input.reason,context:input.context,requestId:input.requestId,extraTags:[studioCacheTag('commerce',input.resource)]})}
