import type { MarketplaceRequestContext } from '../domain/types'
import { MarketplaceError } from '../server/errors'
import type { B2BOrganization, DiagnosticStatus, ProgramStatus } from './types'
const diagnosticTransitions:Record<DiagnosticStatus,DiagnosticStatus[]>={draft:['in_progress','archived'],in_progress:['submitted','archived'],submitted:['under_review','clarification_required'],under_review:['clarification_required','qualified','not_qualified'],clarification_required:['in_progress','submitted','archived'],qualified:['converted','archived'],not_qualified:['archived'],converted:['archived'],archived:[]}
const programTransitions:Record<ProgramStatus,ProgramStatus[]>={configuration:['readiness_review','archived'],readiness_review:['configuration','approved','suspended'],approved:['scheduled','active','paused'],scheduled:['active','paused','suspended'],active:['paused','completed','suspended'],paused:['scheduled','active','suspended','archived'],completed:['archived'],suspended:['configuration','readiness_review','paused','archived'],archived:[]}
export function assertDiagnosticTransition(current:DiagnosticStatus,target:DiagnosticStatus){if(!diagnosticTransitions[current].includes(target))throw new MarketplaceError('INVALID_STATE_TRANSITION',`Transition diagnostic ${current} → ${target} interdite.`)}
export function assertProgramTransition(current:ProgramStatus,target:ProgramStatus){if(!programTransitions[current].includes(target))throw new MarketplaceError('INVALID_STATE_TRANSITION',`Transition programme ${current} → ${target} interdite.`)}
export function assertOrganizationScope(context:MarketplaceRequestContext,organization:Pick<B2BOrganization,'territory_id'|'tenant_id'>){if(context.permissions.includes('marketplace.b2b.manage'))return;if(context.tenantId&&organization.tenant_id===context.tenantId)return;if(context.territoryId&&organization.territory_id===context.territoryId)return;throw new MarketplaceError('SCOPE_MISMATCH','Cette organisation ne fait pas partie de votre périmètre autorisé.')}
export function assertNonMedicalBoundary(input:{vertical:string;programType:string;prohibitedActions?:string[]}){if(input.vertical!=='health_partner')return;const forbidden=['diagnosis','prescription','medication administration','medical treatment','clinical triage'];const combined=[input.programType,...(input.prohibitedActions||[])].join(' ').toLowerCase();if(forbidden.some(term=>combined.includes(term)))throw new MarketplaceError('VALIDATION_ERROR','Le programme dépasse les limites non médicales autorisées.')}
export function assertActivationReady(input:{blockingChecks:number;failedChecks:number;status:ProgramStatus}){if(input.status!=='approved'&&input.status!=='scheduled')throw new MarketplaceError('INVALID_STATE_TRANSITION','Le programme doit être approuvé avant activation.');if(input.blockingChecks>0||input.failedChecks>0)throw new MarketplaceError('DEPENDENCY_BLOCKED','Des contrôles de readiness bloquent encore l’activation.')}
export function assertQuotaAvailable(input:{remaining:number;requested:number}){if(input.requested<=0)throw new MarketplaceError('VALIDATION_ERROR','La quantité demandée doit être positive.');if(input.requested>input.remaining)throw new MarketplaceError('DEPENDENCY_BLOCKED','Le quota disponible est insuffisant pour cette demande.')}
