'use client'
import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowRight, BookOpenCheck, CalendarDays, CheckCircle2, LibraryBig, ShieldCheck } from 'lucide-react'
import type { CatalogueComposerOptions } from '@/lib/flashcards-os/catalogue-composer/types'
import styles from './catalogue-composer.module.css'
import { Chip, Field, money, sourceLabel } from './ComposerPrimitives'
function toggle(list:string[],value:string){return list.includes(value)?list.filter((item)=>item!==value):[...list,value]}
const ages=[['24','2 ans'],['36','3 ans'],['48','4 ans'],['60','5 ans'],['72','6 ans'],['84','7 ans'],['96','8 ans'],['120','10 ans']]
export default function CatalogueJourneyComposer({options}:{options:CatalogueComposerOptions}){
 const router=useRouter();const [universe,setUniverse]=useState<'b2c'|'b2b'>('b2c');const [age,setAge]=useState('48');const [language,setLanguage]=useState('fr');const [delivery,setDelivery]=useState<'physical'|'digital'|'hybrid'>('physical');const [profiles,setProfiles]=useState<string[]>([]);const [contexts,setContexts]=useState<string[]>([]);const [pains,setPains]=useState<string[]>([]);const [objectives,setObjectives]=useState<string[]>([]);const [outcomes,setOutcomes]=useState<string[]>([]);const [categories,setCategories]=useState<string[]>([]);const [required,setRequired]=useState<string[]>([]);const [days,setDays]=useState(5);const [sessions,setSessions]=useState(1);const [minutes,setMinutes]=useState(20);const [intensity,setIntensity]=useState<'light'|'medium'|'intensive'>('medium');const [maxCollections,setMaxCollections]=useState(4);const [proposalCount,setProposalCount]=useState(4);const [budget,setBudget]=useState(250);const [working,setWorking]=useState(false);const [error,setError]=useState('')
 const eligible=useMemo(()=>options.collections.filter((item)=>item.status!=='archived'&&item.commercialStatus==='active'&&(categories.length===0||categories.includes(item.categoryId))&&(item.ageMinMonths==null||Number(age)>=item.ageMinMonths)&&(item.ageMaxMonths==null||Number(age)<=item.ageMaxMonths)&&(item.languages.length===0||item.languages.includes(language))&&(delivery==='hybrid'||item.formats.includes(delivery))),[options.collections,categories,age,language,delivery])
 const fiveComplete=profiles.length>0&&contexts.length>0&&pains.length>0&&objectives.length>0&&outcomes.length>0
 async function submit(){setWorking(true);setError('');try{const response=await fetch('/api/flashcards-os/catalogue-composer/journeys',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:`Programme ${days} jours · ${objectives[0]||'Flashcards'}`,universe,learnerAgesMonths:[Number(age)],learnerCount:1,languages:[language],learnerProfileKeys:profiles,usageContextKeys:contexts,painPointKeys:pains,objectiveKeys:objectives,outcomeKeys:outcomes,durationDays:days,sessionsPerDay:sessions,minutesPerSession:minutes,intensity,facilitatorType:universe==='b2b'?'Éducateur / enseignant':'Parent / accompagnant',deliveryMode:delivery,requiredCategoryIds:categories,excludedCategoryIds:[],requiredCollectionIds:required,excludedCollectionIds:[],maximumCollections:maxCollections,budgetMaxDh:budget,quantity:1,requestedProposalCount:proposalCount})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(String(payload.error||'Programme impossible.'));router.push(`/flashcards-os/solutions/catalogue-results/${payload.requestId}`)}catch(e){setError(e instanceof Error?e.message:'Programme impossible.');setWorking(false)}}
 return <div className={styles.page}><section className={styles.composerHeader}><div><div className={styles.kicker}><BookOpenCheck size={16}/> LEARNING PROGRAMME COMPOSER</div><h1>Chaque jour, chaque séance et chaque activité utilisent une collection locale exacte.</h1><p>Le programme est construit sur cinq dimensions obligatoires. Le serveur refuse les collections inventées, les durées incohérentes et les plans sans lignée catalogue.</p></div><aside><strong>{fiveComplete?'5/5':'INCOMPLET'}</strong><span>dimensions obligatoires</span><small>{eligible.length} collections éligibles · {sourceLabel(options.sourceMode)}</small></aside></section>
 <div className={styles.composerLayout}><main className={styles.composerMain}><section className={styles.formSection}><div className={styles.sectionTitle}><span>01</span><div><h2>Profil et environnement</h2><p>Paramètres fondamentaux du bénéficiaire et du format.</p></div></div><div className={styles.fieldGrid}><Field label="Univers"><select value={universe} onChange={(e:any)=>setUniverse(e.target.value as any)}><option value="b2c">B2C</option><option value="b2b">B2B</option></select></Field><Field label="Âge"><select value={age} onChange={(e:any)=>setAge(e.target.value)}>{ages.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Langue"><select value={language} onChange={(e:any)=>setLanguage(e.target.value)}><option value="fr">Français</option><option value="en">English</option><option value="ar">Arabe</option></select></Field><Field label="Format"><select value={delivery} onChange={(e:any)=>setDelivery(e.target.value as any)}><option value="physical">Physique</option><option value="digital">Digital</option><option value="hybrid">Hybride</option></select></Field></div></section>
 <section className={styles.formSection}><div className={styles.sectionTitle}><span>02</span><div><h2>Les cinq dimensions obligatoires</h2><p>Profil, contexte, difficulté, objectif et résultat attendu.</p></div></div><Dimension title="1 · Profil apprenant" items={options.ontology.learnerProfiles} selected={profiles} onChange={(k)=>setProfiles(toggle(profiles,k))}/><Dimension title="2 · Contexte d’usage" items={options.ontology.usageContexts} selected={contexts} onChange={(k)=>setContexts(toggle(contexts,k))}/><Dimension title="3 · Situation / pain point" items={options.ontology.painPoints} selected={pains} onChange={(k)=>setPains(toggle(pains,k))}/><Dimension title="4 · Objectifs" items={options.ontology.objectives} selected={objectives} onChange={(k)=>setObjectives(toggle(objectives,k))}/><Dimension title="5 · Outcomes désirés" items={options.ontology.outcomes} selected={outcomes} onChange={(k)=>setOutcomes(toggle(outcomes,k))}/></section>
 <section className={styles.formSection}><div className={styles.sectionTitle}><span>03</span><div><h2>Collections et catégories sources</h2><p>Sélection facultative de catégories et collections obligatoires.</p></div></div><div className={styles.categoryGrid}>{options.categories.filter((item)=>item.collectionCount>0).map((item)=><Chip key={item.id} active={categories.includes(item.id)} onClick={()=>setCategories(toggle(categories,item.id))}>{item.name} <em>{item.collectionCount}</em></Chip>)}</div><div className={styles.collectionPicker}>{eligible.slice(0,60).map((item)=><button type="button" key={item.id} className={`${styles.collectionRow} ${required.includes(item.id)?styles.collectionRequired:''}`} onClick={()=>setRequired(toggle(required,item.id))}><span><strong>{item.name}</strong><small>{item.code} · {item.categoryName} · v{item.versionLabel}</small></span><span>{money(item.priceDh)}</span>{required.includes(item.id)?<CheckCircle2 size={16}/>:null}</button>)}</div></section></main>
 <aside className={styles.controlRail}><div className={styles.railTitle}><CalendarDays size={18}/><div><strong>Programme contract</strong><span>Durée exacte</span></div></div><Field label="Nombre de jours"><input type="number" min="1" max="90" value={days} onChange={(e:any)=>setDays(Number(e.target.value))}/></Field><Field label="Sessions par jour"><input type="number" min="1" max="5" value={sessions} onChange={(e:any)=>setSessions(Number(e.target.value))}/></Field><Field label="Minutes par session"><input type="number" min="5" max="120" value={minutes} onChange={(e:any)=>setMinutes(Number(e.target.value))}/></Field><Field label="Intensité"><select value={intensity} onChange={(e:any)=>setIntensity(e.target.value as any)}><option value="light">Légère</option><option value="medium">Moyenne</option><option value="intensive">Intensive</option></select></Field><Field label="Maximum collections"><input type="number" min="1" max="24" value={maxCollections} onChange={(e:any)=>setMaxCollections(Number(e.target.value))}/></Field><Field label="Propositions"><input type="number" min="1" max="10" value={proposalCount} onChange={(e:any)=>setProposalCount(Number(e.target.value))}/></Field><Field label="Budget cible"><input type="number" min="0" value={budget} onChange={(e:any)=>setBudget(Number(e.target.value))}/></Field><div className={styles.eligibilityBox}><ShieldCheck size={16}/><strong>{days*sessions} séances</strong><span>{days*sessions*minutes} minutes</span><span>{eligible.length} collections éligibles</span><span>{required.length} obligatoires</span></div>{error?<div className={styles.errorBox}>{error}</div>:null}<button className={styles.generateButton} type="button" onClick={submit} disabled={working||!fiveComplete||eligible.length===0||required.length>maxCollections}><LibraryBig size={17}/>{working?'Architecture du programme…':'Compiler les programmes'}<ArrowRight size={16}/></button><p className={styles.railNote}>Chaque activité doit citer une collection enregistrée. La somme des activités doit correspondre exactement aux minutes de chaque séance.</p></aside></div></div>
}
function Dimension({title,items,selected,onChange}:{title:string;items:Array<{key:string;label:string}>;selected:string[];onChange:(key:string)=>void}){return <div className={styles.dimensionRow}><h3>{title}</h3><div>{items.slice(0,24).map((item)=><Chip key={item.key} active={selected.includes(item.key)} onClick={()=>onChange(item.key)}>{item.label}</Chip>)}{items.length===0?<span className={styles.muted}>Options à configurer dans l’ontologie.</span>:null}</div></div>}
