'use client'
import Link from 'next/link'
import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Check, GitCompareArrows, GitMerge, LibraryBig, PanelsTopLeft, Sparkles } from 'lucide-react'
import type { CatalogueCompositionResult } from '@/lib/flashcards-os/catalogue-composer/types'
import { money } from './ComposerPrimitives'
import styles from './catalogue-scenario-compare-2030.module.css'

export default function CatalogueScenarioCompare2030({result,initialIds}:{result:CatalogueCompositionResult;initialIds:string[]}){
 const router=useRouter();const [selected,setSelected]=useState<string[]>(initialIds.length?initialIds:result.scenarios.slice(0,Math.min(3,result.scenarios.length)).map((item)=>item.id));const [working,setWorking]=useState(false);const [error,setError]=useState('')
 const scenarios=useMemo(()=>result.scenarios.filter((item)=>selected.includes(item.id)).slice(0,4),[result.scenarios,selected])
 const allCollections=useMemo(()=>[...new Set(scenarios.flatMap((item)=>item.collectionIds))],[scenarios])
 function toggle(id:string){setSelected((current)=>current.includes(id)?current.filter((item)=>item!==id):current.length<4?[...current,id]:current)}
 async function workbench(id:string){setWorking(true);setError('');try{const response=await fetch('/api/flashcards-os/px/workbenches/from-scenario',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenarioId:id})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Workbench impossible.');router.push(`/flashcards-os/workbench/${payload.workbench.kind}/${payload.workbench.id}`)}catch(e){setError(e instanceof Error?e.message:'Workbench impossible.');setWorking(false)}}
 async function merge(){if(selected.length<2)return;setWorking(true);setError('');try{const ids:string[]=[];for(const id of selected){const response=await fetch('/api/flashcards-os/px/workbenches/from-scenario',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenarioId:id})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Workbench impossible.');ids.push(payload.workbench.id)}const response=await fetch('/api/flashcards-os/px/merge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workbenchIds:ids,title:`${result.title} · Version fusionnée`,strategy:'operator_selection'})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Fusion impossible.');router.push(`/flashcards-os/workbench/${payload.workbench.kind}/${payload.workbench.id}`)}catch(e){setError(e instanceof Error?e.message:'Fusion impossible.');setWorking(false)}}
 return <div className={styles.page}><header className={styles.hero}><div><Link href={`/flashcards-os/solutions/catalogue-results/${result.requestId}`}><ArrowLeft size={15}/> Retour au théâtre</Link><span><GitCompareArrows size={15}/> VISUAL DIFFERENCE & MERGE THEATRE</span><h1>Décider par différence, pas par lecture exhaustive.</h1><p>Comparez jusqu’à quatre propositions issues du catalogue local, voyez exactement ce qui change, puis ouvrez ou fusionnez une version persistante.</p></div><aside><strong>{selected.length}/4</strong><span>scénarios comparés</span><small>{allCollections.length} collections uniques</small><button type="button" disabled={selected.length<2||working} onClick={merge}><GitMerge size={16}/> Fusionner la sélection</button></aside></header>{error?<div className={styles.error}>{error}</div>:null}<nav className={styles.selector}>{result.scenarios.map((item,index)=><button type="button" key={item.id} data-active={selected.includes(item.id)} onClick={()=>toggle(item.id)}><span>{selected.includes(item.id)?<Check size={13}/>:String(index+1).padStart(2,'0')}</span><strong>{item.name}</strong><small>{money(item.commercial.finalTotalDh)}</small></button>)}</nav><section className={styles.matrix}><div className={styles.labelColumn}><span>Positionnement</span><span>Prix total</span><span>Collections</span><span>Modèle utilisé</span>{allCollections.map((id)=><span key={id}><LibraryBig size={13}/>{result.collections.find((item)=>item.id===id)?.name||id}</span>)}</div>{scenarios.map((scenario)=><article key={scenario.id}><header><Sparkles size={18}/><h2>{scenario.name}</h2><p>{scenario.mode==='package'?scenario.positioning:scenario.thesis}</p><button type="button" disabled={working} onClick={()=>workbench(scenario.id)}><PanelsTopLeft size={14}/> Ouvrir Workbench</button></header><div>{scenario.mode==='package'?scenario.positioning:scenario.thesis}</div><div className={styles.money}>{money(scenario.commercial.finalTotalDh)}</div><div>{scenario.collectionIds.length}</div><div>{scenario.modelUsed||'openrouter/free'}</div>{allCollections.map((id)=><div key={id} data-present={scenario.collectionIds.includes(id)}>{scenario.collectionIds.includes(id)?<><Check size={14}/> Inclus</>:<span>—</span>}</div>)}</article>)}</section></div>
}
