'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import styles from './MaterialCommand.module.css'
import type { MaterialCategory,MaterialIntegrityStatus,MaterialItemDossier,MaterialStaff } from '@/types/angelcare360/material-control'
import { formatDate,formatMad } from './MaterialCommandShell'
import { MovementStudio } from './MovementStudio'

export function MaterialDossier({schoolId,dossier,categories,staff,integrity}:{schoolId:string;dossier:MaterialItemDossier;categories:MaterialCategory[];staff:MaterialStaff[];integrity:MaterialIntegrityStatus}){
 const router=useRouter();const item=dossier.item; const [edit,setEdit]=useState(false);const [assign,setAssign]=useState(false);const [form,setForm]=useState({id:item.id,categoryId:item.categoryId,code:item.code,label:item.label,unit:item.unit,barcode:item.barcode||'',reorderLevel:String(item.reorderLevel),purchasePrice:String(item.purchasePrice),responsibleStaffId:item.responsibleStaffId||'',status:['inactive','archived'].includes(item.status)?item.status:'active'});const [staffId,setStaffId]=useState(item.responsibleStaffId||'');const[feedback,setFeedback]=useState('');const[busy,setBusy]=useState(false)
 async function post(operation:string,payload:Record<string,unknown>){const response=await fetch('/api/angelcare360/inventory-command',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({entity:'item',operation,payload:{schoolId,...payload}})});return response.json() as Promise<{ok:boolean;error?:string}>}
 async function update(e:React.FormEvent){e.preventDefault();setBusy(true);setFeedback('');try{const r=await post('update',{...form,reorderLevel:Number(form.reorderLevel),purchasePrice:Number(form.purchasePrice)});if(!r.ok){setFeedback(r.error||'Modification impossible.');return}setFeedback('Identité matérielle mise à jour. Le stock n’a pas été édité directement.');setEdit(false);router.refresh()}finally{setBusy(false)}}
 async function changeResponsible(e:React.FormEvent){e.preventDefault();setBusy(true);setFeedback('');try{const r=await post('assign',{id:item.id,responsibleStaffId:staffId});if(!r.ok){setFeedback(r.error||'Affectation impossible.');return}setFeedback('Responsabilité matérielle mise à jour et auditée.');setAssign(false);router.refresh()}finally{setBusy(false)}}
 const max=Math.max(item.currentStock,item.reorderLevel*2,1);const fill=Math.max(0,Math.min(100,item.currentStock/max*100));const threshold=Math.max(0,Math.min(100,item.reorderLevel/max*100))
 return <div className={styles.stack}>
  <div className={styles.dossierGrid}>
   <aside className={styles.rail}><div className={styles.railBody}><div className={styles.identity}><span>{item.code}</span><strong>{item.label}</strong><span>{item.categoryLabel||'Catégorie non résolue'}</span></div><div className={styles.factList}><div className={styles.fact}><span>Unité</span><b>{item.unit}</b></div><div className={styles.fact}><span>Code-barres</span><b>{item.barcode||'Non renseigné'}</b></div><div className={styles.fact}><span>Responsable</span><b>{item.responsibleStaffName||'Sans responsable'}</b></div><div className={styles.fact}><span>État</span><b>{item.status}</b></div><div className={styles.fact}><span>Prix d’achat</span><b>{formatMad(item.purchasePrice)}</b></div><div className={styles.fact}><span>Valeur indicative</span><b>{formatMad(item.indicativeValue)}</b></div><div className={styles.fact}><span>Créé</span><b>{formatDate(item.createdAt)}</b></div></div><div className={styles.actions} style={{marginTop:16}}><button className={styles.buttonGhost} onClick={()=>setEdit(v=>!v)}>Identité & seuil</button><button className={styles.buttonGhost} onClick={()=>setAssign(v=>!v)}>Responsabilité</button></div></div></aside>
   <section className={styles.dossier}><div className={styles.panelHead}><div><p className={styles.eyebrow}>STOCK HORIZON</p><h2>Position matérielle actuelle</h2><p>Le seuil est une limite opérationnelle enregistrée, pas une prévision de consommation.</p></div><span className={styles.pill} data-tone={item.health==='healthy'?'success':item.health==='pressure'?'warning':'danger'}>{item.health}</span></div><div className={styles.stockHorizon}><div className={styles.stockHero}><strong>{item.currentStock}</strong><span>{item.unit}<br/>seuil {item.reorderLevel}</span></div><div className={styles.horizonTrack}><div className={styles.horizonFill} style={{width:`${fill}%`}}/><div className={styles.thresholdMark} style={{left:`${threshold}%`}}/></div><div className={styles.thresholdLabel}>Distance au seuil: {item.thresholdDelta} {item.unit} · ratio {item.thresholdRatio===null?'non applicable':item.thresholdRatio.toFixed(2)}</div></div><div className={styles.panelHead}><div><p className={styles.eyebrow}>MATERIAL CHRONICLE</p><h2>Mouvements certifiés</h2></div><span className={styles.panelMeta}>{dossier.movements.length} événements</span></div><div className={styles.timeline}>{dossier.movements.length?dossier.movements.slice(0,40).map(m=><div className={styles.timelineItem} key={m.id}><div className={styles.timelineTime}>{formatDate(m.createdAt)}<br/>{m.movementCode}</div><div className={styles.timelineBody}><span className={styles.movementType} data-type={m.movementType}>{m.movementType}</span><strong style={{display:'block',marginTop:6}}>{m.quantity} {item.unit}</strong><p>{m.notes||'Sans note'} · {m.performerName||m.performedBy||'acteur non résolu'}</p></div></div>):<div className={styles.empty}><div><strong>Aucun mouvement</strong><p>Ce dossier ne possède pas encore de chronologie stock.</p></div></div>}</div></section>
   <aside className={styles.rail}><div className={styles.panelHead}><div><p className={styles.eyebrow}>MATERIAL FORENSICS</p><h2>Traçabilité</h2></div></div><div className={styles.timeline}>{dossier.audit.slice(0,25).map(a=><div className={styles.timelineItem} key={a.id}><div className={styles.timelineTime}>{formatDate(a.createdAt)}</div><div className={styles.timelineBody}><strong>{a.action}</strong><p>{a.actorRole||'acteur'} · {a.severity}</p></div></div>)}</div></aside>
  </div>
  {edit?<form className={styles.studio} onSubmit={update}><div className={styles.studioHead}><div><h3>Material Identity Studio</h3><p>Cette surface modifie l’identité, le seuil et le prix de référence — jamais le stock courant.</p></div></div><div className={styles.studioBody}><div className={styles.formGrid}><label className={styles.field}><span className={styles.label}>Code</span><input className={styles.input} value={form.code} onChange={e=>setForm({...form,code:e.target.value})} required/></label><label className={styles.field}><span className={styles.label}>Libellé</span><input className={styles.input} value={form.label} onChange={e=>setForm({...form,label:e.target.value})} required/></label><label className={styles.field}><span className={styles.label}>Catégorie</span><select className={styles.select} value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}>{categories.map(c=><option value={c.id} key={c.id}>{c.label}</option>)}</select></label><label className={styles.field}><span className={styles.label}>Unité</span><input className={styles.input} value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/></label><label className={styles.field}><span className={styles.label}>Barcode</span><input className={styles.input} value={form.barcode} onChange={e=>setForm({...form,barcode:e.target.value})}/></label><label className={styles.field}><span className={styles.label}>Seuil</span><input className={styles.input} type="number" min="0" step="any" value={form.reorderLevel} onChange={e=>setForm({...form,reorderLevel:e.target.value})}/></label><label className={styles.field}><span className={styles.label}>Prix d’achat</span><input className={styles.input} type="number" min="0" step="any" value={form.purchasePrice} onChange={e=>setForm({...form,purchasePrice:e.target.value})}/></label><label className={styles.field}><span className={styles.label}>Cycle de vie</span><select className={styles.select} value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Actif</option><option value="inactive">Inactif</option><option value="archived">Archivé</option></select></label></div></div><div className={styles.studioFooter}><button className={styles.button} disabled={busy}>Mettre à jour</button></div></form>:null}
  {assign?<form className={styles.studio} onSubmit={changeResponsible}><div className={styles.studioHead}><div><h3>Stewardship Command</h3><p>Le changement de responsable est une décision de gouvernance matérielle auditée.</p></div></div><div className={styles.studioBody}><div className={styles.reviewBox}><div className={styles.reviewLine}><span>Responsable actuel</span><b>{item.responsibleStaffName||'Aucun'}</b></div><label className={styles.field}><span className={styles.label}>Nouveau responsable</span><select className={styles.select} value={staffId} onChange={e=>setStaffId(e.target.value)}><option value="">Retirer l’affectation</option>{staff.map(s=><option key={s.id} value={s.id}>{s.fullName} · {s.department||'Sans département'}</option>)}</select></label></div></div><div className={styles.studioFooter}><button className={styles.button} disabled={busy}>Confirmer la responsabilité</button></div></form>:null}
  {feedback?<div className={styles.notice} data-tone={feedback.includes('mise à jour')||feedback.includes('Responsabilité')?'success':'danger'}>{feedback}</div>:null}
  <MovementStudio schoolId={schoolId} items={[item]} integrity={integrity} defaultItemId={item.id}/>
 </div>
}
