export type PlanningStatus = 'draft'|'incomplete'|'ready'|'generating'|'generated'|'validation_required'|'correction_required'|'approval_requested'|'approved'|'rejected'|'superseded'|'archived'
export type FindingSeverity = 'info'|'warning'|'major'|'blocking'
export type PlanBlockKind = 'opening'|'care'|'learning'|'movement'|'meal'|'hygiene'|'rest'|'transport'|'adapted'|'handover'|'reporting'
export interface PlanningBeneficiary { id:string; displayName:string; ageYears:number; ageBand:string; language:string; communicationLevel:string; independenceLevel:string; attentionMinutes:number; interests:string[]; sensoryNeeds:string[]; mobilityLevel:string; mealRequired:boolean; snackRequired:boolean; napRequired:boolean; hygieneRequired:boolean; allergies:string[]; dietaryRestrictions:string[]; supportIntensity:string }
export interface PlanningDate { id:string; serviceDate:string; startTime:string; endTime:string; declaredMinutes:number; grossMinutes:number; handoverMinutes:number; careRoutineMinutes:number; reportMinutes:number; travelMinutes:number; usableMinutes:number; status:'valid'|'conditional'|'blocked'; messages:string[] }
export interface PlanningRequest { id:string; code:string; title:string; status:PlanningStatus; categoryId:string; categoryCode:string; categoryName:string; serviceVersionId:string; universe:'b2c'|'b2b'; missionFormat:string; customerProfile:string; objectives:string[]; outcomes:string[]; beneficiaries:PlanningBeneficiary[]; dates:PlanningDate[]; environment:Record<string,unknown>; constraints:Record<string,unknown>; requestedScenarioCount:number; createdAt:string|null; updatedAt:string|null }
export interface PlanBlock { id:string; dayId:string; activityId:string; activityCode:string; label:string; kind:PlanBlockKind; startTime:string; endTime:string; durationMinutes:number; objective:string; beneficiaryIds:string[]; materials:string[]; competencies:string[]; safeguards:string[]; evidence:string[]; checklistCodes:string[]; doctrineRefs:string[]; locked:boolean; status:'valid'|'conditional'|'blocked'; messages:string[] }
export interface PlanDay { id:string; scenarioId:string; serviceDate:string; dayNumber:number; objective:string; progressionPhase:string; startTime:string; endTime:string; grossMinutes:number; usableMinutes:number; blocks:PlanBlock[]; status:'valid'|'conditional'|'blocked'; messages:string[] }
export interface PlanScenario { id:string; requestId:string; code:string; name:string; intent:string; thesis:string; status:PlanningStatus; customerFit:string; beneficiaryFit:string; totalMinutes:number; days:PlanDay[]; staffing:Record<string,unknown>; resources:Record<string,unknown>; safety:Record<string,unknown>; deterministicStatus:'valid'|'conditional'|'blocked'; providerRoute:string; actualModel:string|null; runId:string|null; createdAt:string|null }
export interface ValidationFinding { id:string; planId:string; discipline:string; severity:FindingSeverity; ruleCode:string; title:string; detail:string; consequence:string; correctiveAction:string; ownerId:string|null; dueAt:string|null; status:'open'|'resolved'|'waived'; evidence:unknown[] }
export interface PlanningDashboard { requests:PlanningRequest[]; scenarios:PlanScenario[]; findings:ValidationFinding[]; metrics:{ totalRequests:number; readyRequests:number; generatedScenarios:number; blockedPlans:number; approvalQueue:number; approvedPlans:number; failedRuns:number }; provider:{ configured:boolean; route:'openrouter/free'; lastStatus:string; actualModel:string|null; lastFailure:string|null } }
