'use client'

import { useState } from 'react'
import { BadgeCheck, Boxes, Check, Gauge, ShieldCheck, UsersRound } from 'lucide-react'
import type { CatalogLocale, DiscoveryItem } from '../../catalog-discovery/types'
import type { ConversionOption } from '../types'
import { conversionCopy } from '../content'
import { ConversionFrame, EvidencePanel } from './ConversionFrame'
import { useConversionEngine } from './useConversionEngine'
import styles from '../conversion.module.css'

export function PartnerSubscriptionExperience({ item, locale, plans }: { item: DiscoveryItem; locale: CatalogLocale; plans: ConversionOption[] }) {
  const engine = useConversionEngine({ item, locale, journey: 'partner_subscription' })
  const copy = conversionCopy(locale)
  const [step,setStep]=useState(1)
  const [form,setForm]=useState({planId:plans[0]?.id||'',tenantType:'school',sites:'1',users:'10',renewalMode:'manual',organizationName:'',contactName:'',email:'',phone:'',modules:''})
  const set=(key:keyof typeof form,value:string)=>setForm(current=>({...current,[key]:value}))
  const selected=plans.find(plan=>plan.id===form.planId)
  async function configure(){await engine.update({configuration:{planId:form.planId,planKey:selected?.metadata.planKey||null,tenantType:form.tenantType,sites:Number(form.sites),users:Number(form.users),renewalMode:form.renewalMode,requestedModules:form.modules.split(',').map(value=>value.trim()).filter(Boolean)},status:'identity_pending'});await engine.revalidatePrice(1);await engine.revalidateAvailability({planId:form.planId,tenantType:form.tenantType});setStep(2)}
  async function identity(){await engine.update({identity:{organizationName:form.organizationName,contactName:form.contactName,fullName:form.contactName,email:form.email,phone:form.phone},status:'consent_pending'});setStep(3)}
  async function accept(){await engine.consent('marketplace_terms',true,{journey:'partner_subscription'});await engine.consent('privacy_notice',true,{journey:'partner_subscription'});await engine.consent('partner_os_subscription_scope',true,{tenantType:form.tenantType});setStep(4)}
  async function confirm(){await engine.update({status:'ready'});await engine.confirm();setStep(5)}
  return <ConversionFrame item={item} locale={locale} journey="partner_subscription" step={Math.min(step,5)} price={engine.price} error={engine.error} busy={engine.loading||engine.busy} outcome={engine.outcome} sidebar={<><EvidencePanel item={item} locale={locale}/><div className={styles.saasSide}><Gauge size={32}/><span>PARTNER OS AUTHORITY</span><h3>Plan, modules, limites d’usage et onboarding restent gouvernés par l’autorité SaaS existante.</h3></div></>}>
    {step===1?<section className={styles.stagePanel}><div className={styles.stageHeading}><span>01 · PLAN & TENANT ARCHITECTURE</span><h2>Configurez le périmètre SaaS réel</h2><p>Aucun plan, module ou plafond d’usage n’est inventé dans le checkout.</p></div><div className={styles.planGrid}>{plans.map(plan=><button type="button" key={plan.id} data-selected={form.planId===plan.id} onClick={()=>set('planId',plan.id)}><div><Boxes size={22}/><span>{String(plan.metadata.billingPeriod||'custom')}</span></div><h3>{plan.label}</h3><p>{plan.subtitle}</p><strong>{plan.priceAmount===null?'Sur devis':`${plan.priceAmount} ${plan.currencyLabel||'Dh'}`}</strong></button>)}{!plans.length?<div className={styles.noOption}><Boxes size={42}/><h3>Plan publié requis</h3><p>Le parcours restera une demande qualifiée sans inventer de plan.</p></div>:null}</div><div className={styles.identityGrid}><label><span>Type de tenant</span><select value={form.tenantType} onChange={event=>set('tenantType',event.target.value)}><option value="school">École / crèche</option><option value="hospitality">Hospitality</option><option value="corporate">Corporate</option><option value="health_partner">Partenaire santé</option></select></label><label><span>Sites</span><input type="number" min="1" value={form.sites} onChange={event=>set('sites',event.target.value)}/></label><label><span>Utilisateurs estimés</span><input type="number" min="1" value={form.users} onChange={event=>set('users',event.target.value)}/></label><label><span>Renouvellement</span><select value={form.renewalMode} onChange={event=>set('renewalMode',event.target.value)}><option value="manual">Manuel</option><option value="contractual">Contractuel</option><option value="automatic">Automatique après contrat</option></select></label></div><label className={styles.fullField}><span>Modules demandés (séparés par virgule)</span><textarea rows={3} value={form.modules} onChange={event=>set('modules',event.target.value)}/></label><div className={styles.stageActions}><button onClick={()=>void configure()}>{copy.continue}</button></div></section>:null}
    {step===2?<section className={styles.stagePanel}><div className={styles.stageHeading}><span>02 · ORGANIZATION OWNER</span><h2>Organisation et responsable du tenant</h2></div><div className={styles.identityGrid}><label><span>Organisation</span><input value={form.organizationName} onChange={event=>set('organizationName',event.target.value)}/></label><label><span>Responsable</span><input value={form.contactName} onChange={event=>set('contactName',event.target.value)}/></label><label><span>Email</span><input type="email" value={form.email} onChange={event=>set('email',event.target.value)}/></label><label><span>Téléphone</span><input value={form.phone} onChange={event=>set('phone',event.target.value)}/></label></div><div className={styles.stageActions}><button className={styles.secondaryAction} onClick={()=>setStep(1)}>{copy.back}</button><button disabled={!form.organizationName||!form.contactName||!form.email} onClick={()=>void identity()}>{copy.continue}</button></div></section>:null}
    {step===3?<section className={styles.stagePanel}><div className={styles.stageHeading}><span>03 · SAAS GOVERNANCE</span><h2>Conditions, confidentialité et périmètre d’abonnement</h2></div><div className={styles.consentCards}><article><BadgeCheck/><div><b>Conditions Marketplace</b><p>La demande ne crée pas automatiquement un tenant actif.</p></div></article><article><ShieldCheck/><div><b>Protection des données</b><p>Les accès et données restent soumis à l’onboarding et aux permissions du Partner OS.</p></div></article><article><Check/><div><b>Périmètre de souscription</b><p>Plan, modules, limites et renouvellement seront repris dans le dossier canonique.</p></div></article></div><div className={styles.stageActions}><button className={styles.secondaryAction} onClick={()=>setStep(2)}>{copy.back}</button><button onClick={()=>void accept()}>Accepter et vérifier</button></div></section>:null}
    {step===4?<section className={styles.reviewPanel}><span>04 · SUBSCRIPTION REVIEW</span><h2>Résumé de configuration Partner OS</h2><div className={styles.reviewGrid}><div><small>Plan</small><b>{selected?.label||'Qualification manuelle'}</b></div><div><small>Tenant</small><b>{form.tenantType}</b></div><div><small>Sites</small><b>{form.sites}</b></div><div><small>Utilisateurs</small><b>{form.users}</b></div><div><small>Organisation</small><b>{form.organizationName}</b></div><div><small>Prix</small><b>{engine.price?.status==='quote_required'?'Sur devis':`${engine.price?.grand_total||0} ${engine.price?.currency_label||'Dh'}`}</b></div></div><div className={styles.stageActions}><button className={styles.secondaryAction} onClick={()=>setStep(3)}>{copy.back}</button><button onClick={()=>void confirm()}>Créer la demande d’abonnement</button></div></section>:null}
    {step===5&&engine.outcome?<section className={styles.confirmationPanel}><UsersRound size={54}/><span>PARTNER OS HANDOVER</span><h2>{engine.outcome.public_reference}</h2><p>La configuration est enregistrée pour onboarding, validation commerciale et activation gouvernée.</p></section>:null}
  </ConversionFrame>
}
