import AppShell, { PageAction } from '@/app/components/erp/AppShell'
import { createClient } from '@/lib/supabase/server'
import { requireRole } from '@/lib/auth/session'
import { redirect } from 'next/navigation'
import { Panel, WorkspaceHero } from '../../_components/RevenueOpsPrimitives'

export default async function NewProspectPage() {
  await requireRole(['ceo','manager','agent'])
  async function createProspect(formData: FormData) { 'use server'; const supabase = await createClient(); const payload:any = { name: String(formData.get('name') || 'Prospect').trim(), company_name: String(formData.get('company_name') || '').trim() || null, segment: String(formData.get('segment') || 'b2c'), city: String(formData.get('city') || '').trim() || null, phone: String(formData.get('phone') || '').trim() || null, email: String(formData.get('email') || '').trim() || null, stage: String(formData.get('stage') || 'new'), priority: String(formData.get('priority') || 'medium'), estimated_value: Number(formData.get('estimated_value') || 0), score: Number(formData.get('score') || 0), next_action: String(formData.get('next_action') || '').trim() || null, notes: String(formData.get('notes') || '').trim() || null }; const { data, error } = await supabase.from('bd_prospects').insert([payload]).select('id').single(); if (error) throw new Error(error.message); redirect(`/revenue-command-center/prospects/${data.id}`) }
  return <AppShell title="Nouveau prospect" subtitle="Créer une fiche CRM exploitable." breadcrumbs={[{label:'Prospects',href:'/revenue-command-center/prospects'}, {label:'New'}]} actions={<PageAction href="/revenue-command-center/prospects" variant="light">Retour</PageAction>}><div style={{display:'grid',gap:20}}><WorkspaceHero eyebrow="PROSPECT CREATION" title="Créer un prospect exploitable" subtitle="Chaque fiche doit avoir segment, potentiel, statut, prochaine action et notes utiles pour l'équipe."/><Panel title="Fiche prospect" subtitle="Base commerciale."><form action={createProspect} style={formStyle}>{['name','company_name','city','phone','email','next_action'].map(n=><input key={n} name={n} placeholder={n} style={inputStyle}/>)}<select name="segment" style={inputStyle}><option value="b2c">B2C</option><option value="b2b">B2B</option></select><select name="stage" style={inputStyle}><option value="new">New</option><option value="contacted">Contacted</option><option value="qualified">Qualified</option><option value="proposal">Proposal</option></select><select name="priority" style={inputStyle}><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select><input name="estimated_value" type="number" placeholder="Valeur estimée" style={inputStyle}/><input name="score" type="number" placeholder="Score" style={inputStyle}/><textarea name="notes" placeholder="Notes / contexte" style={{...inputStyle,minHeight:110,gridColumn:'1/-1'}}/><button style={buttonStyle}>Créer prospect</button></form></Panel></div></AppShell>
}
const formStyle:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12}.valueOf(); const inputStyle:React.CSSProperties={padding:'13px 14px',borderRadius:14,border:'1px solid #cbd5e1',background:'#f8fafc',fontWeight:800}.valueOf(); const buttonStyle:React.CSSProperties={border:'none',borderRadius:14,padding:'14px 18px',background:'#0f172a',color:'#fff',fontWeight:950,cursor:'pointer',gridColumn:'1/-1'}.valueOf()
