import type {AdaptiveExperienceData} from '@/angelcare-marketplace/category-native-experience/types'
import type {StudioResolvedTemplate} from '@/angelcare-marketplace/studio-template-assignment/types'
import {CategoryNativeExperience} from '@/angelcare-marketplace/category-native-experience/components/AdaptiveExperience'
import {StudioPublishedDataRenderer} from '@/angelcare-marketplace/studio-universal/StudioPublishedRenderer'
import {prepareStudioPublicRuntime} from '../orchestrator'
import {resolvePublicExperienceDetailTemplate} from '@/angelcare-marketplace/public-experience-authority/detail-resolver'
import {buildPublicExperience360} from '@/angelcare-marketplace/public-experience-authority/public-experience-360'
import {evaluatePublicExperienceTruth} from '@/angelcare-marketplace/public-experience-authority/truth-firewall'
import {enforcePublicExperienceTruthOnData} from '@/angelcare-marketplace/public-experience-authority/truth-enforcement'
import {isCanonicalBuiltinWorld} from '@/angelcare-marketplace/public-experience-authority/canonical-worlds'
import {CanonicalAtomicDetailWorld} from '@/angelcare-marketplace/public-experience-authority/components/CanonicalAtomicDetailWorld'
import {ProductProMaxWorld01,PRODUCT_PRO_MAX_WORLD01_ID} from '@/angelcare-marketplace/public-experience-authority/product-worlds/pro-max-01'

export async function PublicCatalogExperience({data,templateResolution,collectionId=null,placementId=null,audienceId=null,campaignId=null}:{data:AdaptiveExperienceData;templateResolution:StudioResolvedTemplate|null;collectionId?:string|null;placementId?:string|null;audienceId?:string|null;campaignId?:string|null}){
 const authority=await resolvePublicExperienceDetailTemplate({experience:data,legacyResolution:templateResolution}),effectiveResolution=authority.resolution,experience360=await buildPublicExperience360(data),truth=evaluatePublicExperienceTruth(experience360)
 if(effectiveResolution?.status==='RESOLVED'&&effectiveResolution.templateId&&isCanonicalBuiltinWorld(effectiveResolution.templateId)){if(effectiveResolution.templateId===PRODUCT_PRO_MAX_WORLD01_ID)return <ProductProMaxWorld01 data={experience360} truthReport={truth} authority={authority.source}/>;return <CanonicalAtomicDetailWorld data={experience360} truthReport={truth} authority={authority.source}/>}
 const runtime=await prepareStudioPublicRuntime({experience:data,resolution:effectiveResolution,collectionId,placementId,audienceId,campaignId,visibility:'public_runtime'})
 if(runtime.status==='STUDIO_READY'&&runtime.data){const enforced=enforcePublicExperienceTruthOnData(runtime.data,truth);if(!enforced.report.blocked)return <div data-ac-public-experience="studio" data-ac-public-experience-authority={authority.source} data-ac-master-domain={authority.context.masterDomain||undefined} data-ac-doctrine={authority.context.doctrineKey||undefined} data-ac-business-family={authority.context.businessFamilyKey||undefined} data-ac-template-scope={runtime.resolution?.matchedScope||undefined} data-ac-template-key={runtime.resolution?.templateKey||undefined} data-ac-binding-count={runtime.bindingReport?.bindingCount||0} data-ac-dynamic-source-count={runtime.dynamicReport?.sourceCount||0} data-ac-action-count={runtime.preflight.actionCount} data-ac-workflow-count={runtime.preflight.workflowCount} data-ac-truth-state={truth.level} data-ac-truth-proven={truth.provenClaims} data-ac-truth-blocked={truth.blockedClaims} data-ac-truth-sanitized={enforced.report.sanitizedComponentCount}><StudioPublishedDataRenderer data={enforced.data} locale={data.locale} territoryId={runtime.context.territoryId} audienceId={runtime.context.audienceId} attribution={runtime.attribution} dynamicAlreadyApplied dynamicReport={runtime.dynamicReport}/></div>}
 return <div data-ac-public-experience="category-native" data-ac-public-experience-authority={authority.source} data-ac-master-domain={authority.context.masterDomain||undefined} data-ac-doctrine={authority.context.doctrineKey||undefined} data-ac-business-family={authority.context.businessFamilyKey||undefined} data-ac-studio-fallback={runtime.status==='STUDIO_READY'?'TRUTH_FIREWALL_BLOCKED':runtime.fallbackReason||'NO_RESOLVED_TEMPLATE'} data-ac-truth-state={truth.level}><CategoryNativeExperience data={data} templateResolution={effectiveResolution}/></div>
}
