import { BaseExecutionAdapter } from '../adapter'
import { googleAccessToken, requestJson } from '../http'
import type { AdapterConfig, AdapterExecutionResult, CompensationResult, ExecutionAction, PreparedAdapterAction } from '../types'
const b64url=(value:string)=>Buffer.from(value).toString('base64url')
function rawMessage(payload:Record<string,unknown>){const to=String(payload.to||'');const subject=String(payload.subject||'');const body=String(payload.body||payload.content||'');const cc=payload.cc?`Cc: ${String(payload.cc)}\r\n`:'';return b64url(`To: ${to}\r\n${cc}Subject: ${subject}\r\nContent-Type: text/plain; charset=UTF-8\r\n\r\n${body}`)}
export class GmailAdapter extends BaseExecutionAdapter{
 constructor(config:AdapterConfig){super(config)}
 async execute(prepared:PreparedAdapterAction):Promise<AdapterExecutionResult>{if(prepared.action.controls.executionMode==='shadow')return{success:true,payload:{simulated:true},retryable:false,reversible:prepared.reversible};try{const token=await googleAccessToken();const user=process.env.GMAIL_USER_ID||'me';const send=prepared.action.actionType==='send_email';const path=send?'messages/send':'drafts';const body=send?{raw:rawMessage(prepared.request)}:{message:{raw:rawMessage(prepared.request)}};const r=await requestJson(`https://gmail.googleapis.com/gmail/v1/users/${encodeURIComponent(user)}/${path}`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(body)},this.config.timeoutMs);return{success:r.ok,statusCode:r.status,externalReference:String((r.body as any)?.id||''),providerRequestId:String((r.body as any)?.threadId||''),payload:(r.body as Record<string,unknown>)||{},retryable:r.status===429||r.status>=500,errorCode:r.ok?undefined:`GMAIL_${r.status}`,errorMessage:r.ok?undefined:'Gmail API request failed.',reversible:send?'compensatable':'reversible'}}catch(error){return{success:false,payload:{},retryable:true,errorCode:'GMAIL_EXCEPTION',errorMessage:error instanceof Error?error.message:String(error),reversible:prepared.reversible}}}
 async compensate(action:ExecutionAction):Promise<CompensationResult>{if(action.actionType==='prepare_email'&&action.externalReference){try{const token=await googleAccessToken();const user=process.env.GMAIL_USER_ID||'me';const r=await requestJson(`https://gmail.googleapis.com/gmail/v1/users/${encodeURIComponent(user)}/drafts/${encodeURIComponent(action.externalReference)}`,{method:'DELETE',headers:{authorization:`Bearer ${token}`}},this.config.timeoutMs);return{success:r.ok,actionId:action.id,kind:'rollback',reference:action.externalReference,message:r.ok?'Gmail draft deleted.':`Gmail delete failed (${r.status}).`,at:new Date().toISOString()}}catch(error){return{success:false,actionId:action.id,kind:'rollback',reference:action.externalReference,message:error instanceof Error?error.message:String(error),at:new Date().toISOString()}}}return{success:true,actionId:action.id,kind:'suppression',reference:action.externalReference,message:'Message cannot be unsent; future actions suppressed.',at:new Date().toISOString()}}
}
