'use client'
import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowRight, CheckCircle2, LibraryBig, PackagePlus, ShieldCheck } from 'lucide-react'
import type { CatalogueComposerOptions } from '@/lib/flashcards-os/catalogue-composer/types'
import { evaluateCatalogueEligibility } from '@/lib/flashcards-os/catalogue-composer/eligibility'
import styles from './catalogue-composer.module.css'
import { Chip, Field, money, sourceLabel } from './ComposerPrimitives'
const segments=['Famille · usage à domicile','Famille premium','Crèche / maternelle','École primaire','Orthophonie / accompagnement','Hôtel kids programme','Entreprise / événement']
const ages=[['24','2 ans'],['36','3 ans'],['48','4 ans'],['60','5 ans'],['72','6 ans'],['84','7 ans'],['96','8 ans'],['120','10 ans']]
function toggle(list:string[],value:string){return list.includes(value)?list.filter((item)=>item!==value):[...list,value]}
function Funnel({f}:{f:ReturnType<typeof evaluateCatalogueEligibility>['funnel']}){const items=[['Catalogue',f.registered],['Actives',f.active],['Catégories',f.categoryCompatible],['Âge',f.ageCompatible],['Langue',f.languageCompatible],['Format',f.formatCompatible],['Contexte',f.contextCompatible],['Objectifs',f.objectiveCompatible],['Tarifées',f.commerciallyActive],['Budget',f.withinBudget]];return <div style={{display:'grid',gridTemplateColumns:'repeat(5,minmax(0,1fr))',gap:8,marginTop:12}}>{items.map(([label,value])=><div key={String(label)} style={{border:'1px solid #d9e2ee',borderRadius:10,padding:'8px 10px',background:'#fff'}}><small style={{display:'block',color:'#66788e',fontSize:9,textTransform:'uppercase'}}>{label}</small><strong style={{fontSize:15}}>{value}</strong></div>)}</div>}
export default function CataloguePackageComposer({options,initialCollectionId}:{options:CatalogueComposerOptions;initialCollectionId?:string}){
  const router=useRouter();const [catalogue,setCatalogue]=useState(options);const [universe,setUniverse]=useState<'b2c'|'b2b'>('b2c');const [segment,setSegment]=useState(segments[0]);const [age,setAge]=useState('48');const [language,setLanguage]=useState('fr');const [delivery,setDelivery]=useState<'physical'|'digital'|'hybrid'>('physical')
  const [contexts,setContexts]=useState<string[]>([]);const [objectives,setObjectives]=useState<string[]>([]);const [pains,setPains]=useState<string[]>([]);const [outcomes,setOutcomes]=useState<string[]>([]);const [categories,setCategories]=useState<string[]>([]);const [required,setRequired]=useState<string[]>(initialCollectionId?[initialCollectionId]:[])
  const [maxCollections,setMaxCollections]=useState(4);const [proposalCount,setProposalCount]=useState(4);const [budget,setBudget]=useState(300);const [quantity,setQuantity]=useState(1);const [working,setWorking]=useState(false);const [reloading,setReloading]=useState(false);const [error,setError]=useState('')
  useEffect(()=>{if(!initialCollectionId)return;setRequired((current)=>current.includes(initialCollectionId)?current:[initialCollectionId,...current])},[initialCollectionId])
  useEffect(()=>{let cancelled=false;async function reload(){setReloading(true);setError('');try{const response=await fetch(`/api/flashcards-os/catalogue-composer/options?universe=${universe}`,{cache:'no-store'});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Catalogue commercial indisponible.');if(!cancelled){setCatalogue(payload);setRequired((current)=>current.filter((id)=>payload.collections.some((item:any)=>item.id===id)))}}catch(reason){if(!cancelled)setError(reason instanceof Error?reason.message:'Catalogue commercial indisponible.')}finally{if(!cancelled)setReloading(false)}}if(universe!=='b2c')reload();else setCatalogue(options);return()=>{cancelled=true}},[universe,options])
  const evaluation=useMemo(()=>evaluateCatalogueEligibility(catalogue.collections,{learnerAgesMonths:[Number(age)],languages:[language],deliveryMode:delivery,usageContexts:contexts,objectiveKeys:objectives,painPointKeys:pains,outcomeKeys:outcomes,requiredCategoryIds:categories,excludedCategoryIds:[],requiredCollectionIds:required,excludedCollectionIds:[],budgetMaxDh:budget,quantity}),[catalogue.collections,age,language,delivery,contexts,objectives,pains,outcomes,categories,required,budget,quantity])
  const eligible=evaluation.eligible
  async function submit(){setWorking(true);setError('');try{const response=await fetch('/api/flashcards-os/catalogue-composer/packages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:`Package ${segment}`,universe,customerSegment:segment,learnerAgesMonths:[Number(age)],learnerCount:quantity,languages:[language],deliveryMode:delivery,usageContexts:contexts,objectiveKeys:objectives,painPointKeys:pains,outcomeKeys:outcomes,requiredCategoryIds:categories,excludedCategoryIds:[],requiredCollectionIds:required,excludedCollectionIds:[],minimumCollections:1,maximumCollections:maxCollections,budgetMaxDh:budget,quantity,requestedProposalCount:proposalCount,variationPriorities:['diversity','coverage','commercial_clarity']})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(String(payload.error||'Composition impossible.'));router.push(`/flashcards-os/solutions/catalogue-results/${payload.requestId}`)}catch(e){setError(e instanceof Error?e.message:'Composition impossible.');setWorking(false)}}
  return <div className={styles.page}><section className={styles.composerHeader}><div><div className={styles.kicker}><PackagePlus size={16}/> PACKAGE COMPOSER · LOCAL CATALOGUE</div><h1>Construire des packages à partir des collections réellement enregistrées.</h1><p>Un seul moteur d’éligibilité est utilisé avant et pendant la compilation. Le changement B2C/B2B recharge réellement le price book correspondant.</p><Funnel f={evaluation.funnel}/></div><aside><strong>{eligible.length}</strong><span>collections réellement éligibles</span><small>{reloading?'Rechargement tarifaire…':sourceLabel(catalogue.sourceMode)}</small>{initialCollectionId?<small>Collection source préchargée</small>:null}</aside></section>
  <div className={styles.composerLayout}><main className={styles.composerMain}>
    <section className={styles.formSection}><div className={styles.sectionTitle}><span>01</span><div><h2>Client et usage</h2><p>Choix contrôlés, texte libre réduit au strict minimum.</p></div></div><div className={styles.fieldGrid}><Field label="Univers"><select value={universe} onChange={(e:any)=>setUniverse(e.target.value)}><option value="b2c">B2C</option><option value="b2b">B2B</option></select></Field><Field label="Profil client"><select value={segment} onChange={(e:any)=>setSegment(e.target.value)}>{segments.map((item)=><option key={item}>{item}</option>)}</select></Field><Field label="Âge cible"><select value={age} onChange={(e:any)=>setAge(e.target.value)}>{ages.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></Field><Field label="Langue"><select value={language} onChange={(e:any)=>setLanguage(e.target.value)}><option value="fr">Français</option><option value="en">English</option><option value="ar">Arabe</option></select></Field><Field label="Format"><select value={delivery} onChange={(e:any)=>setDelivery(e.target.value)}><option value="physical">Physique</option><option value="digital">Digital</option><option value="hybrid">Hybride</option></select></Field></div></section>
    <section className={styles.formSection}><div className={styles.sectionTitle}><span>02</span><div><h2>Conditions de composition</h2><p>Les filtres visibles correspondent exactement à ceux appliqués côté serveur.</p></div></div><ChoiceGroup title="Contextes" items={catalogue.ontology.usageContexts} selected={contexts} onChange={(key)=>setContexts(toggle(contexts,key))}/><ChoiceGroup title="Objectifs" items={catalogue.ontology.objectives} selected={objectives} onChange={(key)=>setObjectives(toggle(objectives,key))}/><ChoiceGroup title="Pain points" items={catalogue.ontology.painPoints} selected={pains} onChange={(key)=>setPains(toggle(pains,key))}/><ChoiceGroup title="Outcomes" items={catalogue.ontology.outcomes} selected={outcomes} onChange={(key)=>setOutcomes(toggle(outcomes,key))}/></section>
    <section className={styles.formSection}><div className={styles.sectionTitle}><span>03</span><div><h2>Collections et catégories sources</h2><p>Une collection imposée reste visible avec sa raison d’exclusion si elle n’est plus compatible.</p></div></div><div className={styles.categoryGrid}>{catalogue.categories.filter((item)=>item.collectionCount>0).map((item)=><Chip key={item.id} active={categories.includes(item.id)} onClick={()=>setCategories(toggle(categories,item.id))}>{item.name} <em>{item.collectionCount}</em></Chip>)}</div><div className={styles.collectionPicker}>{catalogue.collections.slice(0,80).map((item)=>{const decision=evaluation.decisions.find((d)=>d.collection.id===item.id);const isRequired=required.includes(item.id);return <button type="button" key={item.id} className={`${styles.collectionRow} ${isRequired?styles.collectionRequired:''}`} onClick={()=>setRequired(toggle(required,item.id))}><span><strong>{item.name}</strong><small>{item.code} · {item.categoryName} · v{item.versionLabel}{!decision?.eligible&&decision?.reasons.length?` · ${decision.reasons.join(', ')}`:''}</small></span><span>{money(item.priceDh)}</span>{isRequired?<CheckCircle2 size={16}/>:null}</button>})}</div></section>
  </main><aside className={styles.controlRail}><div className={styles.railTitle}><ShieldCheck size={18}/><div><strong>Commercial contract</strong><span>{universe.toUpperCase()}</span></div></div><Field label="Maximum collections"><input type="number" min="1" max="24" value={maxCollections} onChange={(e:any)=>setMaxCollections(Number(e.target.value))}/></Field><Field label="Quantité"><input type="number" min="1" value={quantity} onChange={(e:any)=>setQuantity(Number(e.target.value))}/></Field><Field label="Propositions"><input type="number" min="1" max="10" value={proposalCount} onChange={(e:any)=>setProposalCount(Number(e.target.value))}/></Field><Field label="Budget max"><input type="number" min="0" value={budget} onChange={(e:any)=>setBudget(Number(e.target.value))}/></Field><div className={styles.eligibilityBox}><LibraryBig size={16}/><strong>{eligible.length} éligibles</strong><span>{evaluation.funnel.commerciallyActive} commercialement actives</span><span>{required.length} obligatoires</span></div>{error?<div className={styles.errorBox}>{error}</div>:null}<button className={styles.generateButton} type="button" onClick={submit} disabled={working||reloading||eligible.length===0||required.length>maxCollections}><PackagePlus size={17}/>{working?'Composition…':'Compiler les packages'}<ArrowRight size={16}/></button></aside></div></div>
}
function ChoiceGroup({title,items,selected,onChange}:{title:string;items:Array<{key:string;label:string}>;selected:string[];onChange:(key:string)=>void}){return <div className={styles.dimensionRow}><h3>{title}</h3><div>{items.slice(0,24).map((item)=><Chip key={item.key} active={selected.includes(item.key)} onClick={()=>onChange(item.key)}>{item.label}</Chip>)}{!items.length?<span className={styles.muted}>Aucune option configurée.</span>:null}</div></div>}
